build.gradle, wpilibj/build.gradle, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CANJaguar.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CANTalon.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Encoder.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/PWM.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Preferences.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Encoder.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Jaguar.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Preferences.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Servo.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Talon.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Victor.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/internal/SimTimer.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/simulation/SimSpeedController.java, wpilibjIntegrationTests/build.gradle
Errorprone is a Java compilation plugin that fails the build when certain things that could cause bugs are detected.
=> Adds Error Prone as compile time check to java projects

wpilibj/src/sim/java/edu/wpi/first/wpilibj/DriverStation.java
Fixed #12 
Change-Id: I5a79a348ab55a8592b54804783303edc9573bf4e
=> Use interrupt() in our interrupt exceptions

hal/lib/athena/Notifier.cpp
As the notifierMutex is unlocked while the callback is being called in
alarmCallback(), it's possible for next to be invalidated due to a
cleanNotifier() call.  Now, instead of deleting the notifier immediately,
add it to a freelist to be cleaned up at the tail end of alarmCallback.
=> HAL Notifier: Use freelist to avoid use-after-free race.

.travis.yml, simulation/frc_gazebo_plugins/clock/src/clock.h, simulation/frc_gazebo_plugins/dc_motor/src/dc_motor.h, simulation/frc_gazebo_plugins/encoder/src/encoder.h, simulation/frc_gazebo_plugins/gyro/src/gyro.cpp, simulation/frc_gazebo_plugins/gyro/src/gyro.h, simulation/frc_gazebo_plugins/limit_switch/src/external_limit_switch.cpp, simulation/frc_gazebo_plugins/limit_switch/src/limit_switch.h, simulation/frc_gazebo_plugins/pneumatic_piston/src/pneumatic_piston.h, simulation/frc_gazebo_plugins/potentiometer/src/potentiometer.h, simulation/frc_gazebo_plugins/rangefinder/src/rangefinder.cpp, simulation/frc_gazebo_plugins/rangefinder/src/rangefinder.h, simulation/frc_gazebo_plugins/servo/src/servo.cpp, simulation/frc_gazebo_plugins/servo/src/servo.h
-  replaced uses of boost with std, because it's cleaner.
- ran formatted on all the plugins
- upgrade to gazebo 7 (previously gazebo 6)
- fixed documentation of how to use plugins in SDF because they've been wrong
- one tiny tweak to make gyros actually
=> cleanup of gazebo plugins

wpilibc/athena/src/ControllerPower.cpp
This is consistent with all other source files.
=> ControllerPower.cpp: Use quoted include instead of bracket for HAL.

wpilibc/athena/src/Vision/VisionAPI.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/85)
=> VisionAPI.cpp: Remove non-UTF8 characters.

hal/lib/athena/HALAthena.cpp, wpilibc/athena/include/BuiltInAccelerometer.h, wpilibc/athena/include/Preferences.h, wpilibc/athena/include/SerialPort.h, wpilibc/athena/src/BuiltInAccelerometer.cpp, wpilibc/athena/src/Utility.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/BuiltInAccelerometer.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Preferences.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SerialPort.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Utility.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/Preferences.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/87)
=> Replaced "RoboRIO" with "roboRIO" in comments

.pullapprove.yml
waiting on a fix from pullapprove
[skip ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/84)
=> remove author requirement for now

styleguide/cppguide.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/86)
=> Made include ordering/organization more explicit in style guide

hal/lib/athena/handles/IndexedHandleResource.h, hal/lib/athena/handles/LimitedHandleResource.h, hal/lib/athena/handles/UnlimitedHandleResource.h
Issues were found when adding unit testing. The classes should now work properly.
The tests ran can be found here: https://github.com/ThadHouse/MockHalTesting/tree/master/test/unit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/95)
=> Fixes HandleResource classes

hal/include/HAL/Handles.h, hal/lib/athena/AnalogInput.cpp, hal/lib/athena/AnalogOutput.cpp, hal/lib/athena/DIO.cpp, hal/lib/athena/Solenoid.cpp, hal/lib/athena/handles/HandlesInternal.cpp, hal/lib/athena/handles/HandlesInternal.h, hal/lib/athena/handles/IndexedHandleResource.h, hal/lib/athena/handles/LimitedHandleResource.h, hal/lib/athena/handles/UnlimitedHandleResource.h
As discussed, we don't really need the error checking specifically, as
we are just going to throw exceptions anyway, so this will make sure you
can check for 0 and be sure you catch any handle errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/100)
=> Switches all HAL Handle errors to be zero

wpilibc/athena/src/IterativeRobot.cpp, wpilibc/athena/src/RobotBase.cpp, wpilibc/athena/src/SampleRobot.cpp, wpilibc/athena/src/Servo.cpp, wpilibc/athena/src/Vision/BaeUtilities.cpp, wpilibc/sim/src/AnalogGyro.cpp, wpilibc/sim/src/AnalogInput.cpp, wpilibc/sim/src/DigitalInput.cpp, wpilibc/sim/src/DoubleSolenoid.cpp, wpilibc/sim/src/Encoder.cpp, wpilibc/sim/src/IterativeRobot.cpp, wpilibc/sim/src/PWM.cpp, wpilibc/sim/src/Relay.cpp, wpilibc/sim/src/Solenoid.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/106)
=> Added std:: prefix to more C standard library uses

hal/include/HAL/Interrupts.h, hal/lib/athena/Interrupts.cpp, hal/lib/athena/handles/HandlesInternal.h, wpilibc/athena/include/InterruptableSensorBase.h, wpilibc/athena/src/AnalogTriggerOutput.cpp, wpilibc/athena/src/DigitalInput.cpp, wpilibc/athena/src/InterruptableSensorBase.cpp, wpilibj/src/athena/cpp/lib/InterruptJNI.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/InterruptableSensorBase.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/InterruptJNI.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/99)
=> Moves Interrupts over to Handles instead of pointers

hal/include/HAL/AnalogAccumulator.h, hal/include/HAL/AnalogInput.h, hal/include/HAL/AnalogTrigger.h, hal/include/HAL/Handles.h, hal/lib/athena/AnalogAccumulator.cpp, hal/lib/athena/AnalogInput.cpp, hal/lib/athena/AnalogInternal.cpp, hal/lib/athena/AnalogInternal.h, hal/lib/athena/AnalogTrigger.cpp, hal/lib/athena/handles/HandlesInternal.h, wpilibc/athena/include/AnalogInput.h, wpilibc/athena/include/AnalogTrigger.h, wpilibc/athena/src/AnalogInput.cpp, wpilibc/athena/src/AnalogTrigger.cpp, wpilibj/src/athena/cpp/lib/AnalogJNI.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogInput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogTrigger.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/AnalogJNI.java
Results in a breaking change to AnalogTriggers. Old code would not allocate an AnalogInput, whereas the new one does.
=> Switches AnalogInputs to Handles

hal/include/HAL/HAL.h, hal/include/HAL/Ports.h, hal/lib/athena/AnalogAccumulator.cpp, hal/lib/athena/AnalogInput.cpp, hal/lib/athena/AnalogInternal.cpp, hal/lib/athena/AnalogInternal.h, hal/lib/athena/AnalogOutput.cpp, hal/lib/athena/AnalogTrigger.cpp, hal/lib/athena/Compressor.cpp, hal/lib/athena/Counter.cpp, hal/lib/athena/DIO.cpp, hal/lib/athena/DigitalInternal.cpp, hal/lib/athena/DigitalInternal.h, hal/lib/athena/Encoder.cpp, hal/lib/athena/HALAthena.cpp, hal/lib/athena/I2C.cpp, hal/lib/athena/Interrupts.cpp, hal/lib/athena/PCMInternal.cpp, hal/lib/athena/PCMInternal.h, hal/lib/athena/PDP.cpp, hal/lib/athena/PWM.cpp, hal/lib/athena/Ports.cpp, hal/lib/athena/PortsInternal.h, hal/lib/athena/Relay.cpp, hal/lib/athena/Solenoid.cpp
Work on getting JNI implemented, and then integrate it up into the HAL
=> Adds port constants to the HAL

wpilibc/athena/include/Joystick.h, wpilibc/athena/src/Joystick.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Joystick.java
Added a method to get the port number of a joystick.
=> Add method to get the port number of a Joystick

hal/include/Log.h
I verified that NowTime() returns the same output as the previous implementation.
=> Made Log.h use std::chrono

styleguide/cpplint.py, styleguide/format.py, styleguide/lint.py
If either Gradle or format.py downloaded cpplint.py if it didn't exist and ran 2to3 on it, we wouldn't need to keep it in the repository history. I'm not sure which we would want. Either way, cpplint.py would be added to the .gitignore file.
=> Added Lint task and parallelized format.py

wpilibc/athena/src/PIDController.cpp, wpilibc/shared/include/PIDController.h, wpilibc/sim/src/PIDController.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/PIDController.java
=> Fixed PIDController::GetError() for continuous inputs

hal/include/HAL/DriverStation.h, hal/include/HAL/HAL.h, hal/lib/athena/HALAthena.cpp, hal/lib/shared/FRCDriverStation.cpp
To allow for future use as a plugin for the HAL simulator.
=> Moves DriverStation HAL code to its own header and definition

hal/include/HAL/handles/HandlesInternal.h, hal/lib/athena/AnalogOutput.cpp, hal/lib/athena/Counter.cpp, hal/lib/athena/DIO.cpp, hal/lib/athena/DigitalInternal.cpp, hal/lib/athena/Encoder.cpp, hal/lib/athena/FPGAEncoder.cpp, hal/lib/athena/HALAthena.cpp, hal/lib/athena/I2C.cpp, hal/lib/athena/Interrupts.cpp, hal/lib/athena/Notifier.cpp, hal/lib/athena/PWM.cpp, hal/lib/athena/SerialPort.cpp, styleguide/cpplint.py, styleguide/lint.py, wpilibc/athena/src/ADXL345_I2C.cpp, wpilibc/athena/src/ADXL345_SPI.cpp, wpilibc/athena/src/ADXL362.cpp, wpilibc/athena/src/ADXRS450_Gyro.cpp, wpilibc/athena/src/AnalogTriggerOutput.cpp, wpilibc/athena/src/CANJaguar.cpp, wpilibc/athena/src/Notifier.cpp, wpilibc/athena/src/USBCamera.cpp, wpilibc/athena/src/Vision/ColorImage.cpp
Additional C-style cast warnings thrown were also fixed.
=> Updated cpplint.py and fixed its regexes for C-style casts

wpilibc/athena/src/PIDController.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/PIDController.java
=> PIDController queue now stores inputs instead of errors

wpilibc/athena/src/PIDController.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/PIDController.java
This reverts commit 7501ae65a1c7f8e31fd19589979793b99527348d.
=> Revert "PIDController queue now stores inputs instead of errors (#138)"

cppSettings.gradle
Should be a heavy increase in performance
=> Switches compiler from -O0 to -Og

hal/include/HAL/handles/DigitalHandleResource.h, hal/include/HAL/handles/HandlesInternal.h, hal/include/HAL/handles/IndexedHandleResource.h, hal/include/HAL/handles/LimitedClassedHandleResource.h, hal/include/HAL/handles/LimitedHandleResource.h, hal/include/HAL/handles/UnlimitedHandleResource.h, wpilibc/athena/src/AnalogTriggerOutput.cpp, wpilibc/athena/src/CameraServer.cpp, wpilibc/athena/src/InterruptableSensorBase.cpp, wpilibc/athena/src/Task.cpp, wpilibj/src/athena/cpp/lib/DigitalGlitchFilterJNI.cpp, wpilibj/src/athena/cpp/lib/HALUtil.cpp, wpilibj/src/athena/cpp/lib/InterruptJNI.cpp, wpilibj/src/athena/cpp/lib/NIVisionJNI.cpp, wpilibj/src/athena/cpp/lib/NotifierJNI.cpp, wpilibj/src/athena/cpp/nivision/gen_java.py
If we want to add -Wold-style-cast to the build, I can also submit PRs to ntcore and allwpilib which add a warning disable pragma to the LLVM headers and CTRE files respectively.
=> Replaced C-style casts found by GCC in HAL, wpilibc, and JNI

hal/include/HAL/Counter.h, hal/include/HAL/DriverStation.h, hal/include/HAL/Task.h, hal/include/HAL/cpp/Semaphore.h, hal/lib/athena/Accelerometer.cpp, hal/lib/athena/AnalogAccumulator.cpp, hal/lib/athena/AnalogInput.cpp, hal/lib/athena/AnalogInternal.cpp, hal/lib/athena/AnalogInternal.h, hal/lib/athena/DIO.cpp, hal/lib/athena/DigitalInternal.h, hal/lib/athena/Encoder.cpp, hal/lib/athena/EncoderInternal.h, hal/lib/athena/FRCDriverStation.cpp, hal/lib/athena/Notifier.cpp, hal/lib/athena/SPI.cpp, hal/lib/athena/SerialPort.cpp, hal/lib/athena/Solenoid.cpp, hal/lib/athena/Task.cpp, hal/lib/athena/cpp/Semaphore.cpp
Replaced all uses of built-in types except char with stdint.h typedefs and all unsigned types with signed in the HAL
=> Cleaned up integer type usage in the HAL

wpilibc/athena/include/IterativeRobot.h, wpilibc/athena/src/IterativeRobot.cpp, wpilibc/sim/include/IterativeRobot.h, wpilibc/sim/src/IterativeRobot.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/IterativeRobot.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/IterativeRobot.java
Called globally during each IterativeRobot loop
=> Adds a RobotPeriodic method to IterativeRobot

.styleguide-license
See wpilibsuite/styleguide #7.
=> Added license template file

hal/include/HAL/Errors.h
Change-Id: Ie7687a966749aa070b94b67a1810eadd47856f02
=> Fix Typos. Fixes artf4853

wpilibc/shared/include/CircularBuffer.h, wpilibc/shared/include/CircularBuffer.inc, wpilibcIntegrationTests/src/CircularBufferTest.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/CircularBuffer.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/CircularBufferTest.java
If the comments don't explain the algorithm well enough, let me know.
=> Implemented CircularBuffer resizing

hal/include/HAL/HAL.h, hal/include/HAL/cpp/priority_condition_variable.h, hal/lib/athena/FRCDriverStation.cpp, hal/lib/athena/HAL.cpp, hal/lib/athena/SPI.cpp, wpilibc/athena/src/AnalogGyro.cpp, wpilibc/athena/src/IterativeRobot.cpp, wpilibc/athena/src/RobotBase.cpp, wpilibc/athena/src/Task.cpp, wpilibc/athena/src/USBCamera.cpp, wpilibc/athena/src/Utility.cpp, wpilibc/athena/src/Vision/AxisCamera.cpp, wpilibc/athena/src/Vision/BaeUtilities.cpp, wpilibc/shared/src/Commands/PrintCommand.cpp, wpilibc/shared/src/ErrorBase.cpp, wpilibc/sim/src/Utility.cpp, wpilibcIntegrationTests/src/TestEnvironment.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/IterativeRobot.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/HALUtil.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/IterativeRobot.java
See wpilibsuite/styleguide #9.
=> Ran format.py after writing unit tests for and fixing bugs in it

wpilibj/src/athena/cpp/lib/AnalogGyroJNI.cpp, wpilibj/src/athena/cpp/lib/CanTalonJNI.cpp, wpilibj/src/athena/cpp/lib/CounterJNI.cpp, wpilibj/src/athena/cpp/lib/EncoderJNI.cpp, wpilibj/src/athena/cpp/lib/HALUtil.cpp, wpilibj/src/athena/cpp/lib/HALUtil.h, wpilibj/src/athena/cpp/lib/I2CJNI.cpp, wpilibj/src/athena/cpp/lib/InterruptJNI.cpp, wpilibj/src/athena/cpp/lib/NotifierJNI.cpp, wpilibj/src/athena/cpp/lib/SPIJNI.cpp, wpilibj/src/athena/cpp/lib/SerialPortJNI.cpp
=> Forces exceptions to throw on HAL handle creation functions

wpilibc/shared/include/SmartDashboard/SmartDashboard.h, wpilibc/shared/src/SmartDashboard/SmartDashboard.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
SetDefault functions were added as well, but commented out until that
gets merged upstream.
=> Updates SmartDashboard with new NetworkTables3 functions

test-scripts/run-tests-on-robot.sh
This fixes the java integration test rpath to point to the correct location.
=> Fixes java test rpath

wpilibc/athena/include/DriverStation.h, wpilibc/athena/src/DriverStation.cpp, wpilibc/sim/include/DriverStation.h, wpilibc/sim/src/DriverStation.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/DriverStation.java
As discussed in #234, we now check for the timeout case and handle a
timeout correctly.
=> Fixes guarantees for waitForData

wpilibc/athena.gradle
=> Fixes the gradle dependencies for building

wpilibj/src/athena/java/edu/wpi/first/wpilibj/DoubleSolenoid.java
=> DoubleSolenoid free reverse port handle instead of channel

wpilibc/athena/src/RobotBase.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotBase.java
=> Updated version for beta 1

build.gradle
@PeterJohnson. Fixes an issue @JacisNonsense found with submodules.
=> Updated the wpilib version plugin to 1.2. Fixes issues with submodules.

hal/include/HAL/Interrupts.h, hal/include/HAL/Notifier.h, hal/lib/athena/Interrupts.cpp, hal/lib/athena/Notifier.cpp
=> Implements threaded notifiers and interrupts in the HAL

myRobot/build.gradle, myRobot/src/main/java/MyRobot.java, myRobotCpp/build.gradle, myRobotCpp/src/MyRobot.cpp, settings.gradle
C++ builds the same, but Java now places the required native libraries into the same directory as the jar to help upload it to the Rio
=> C++ and Java tests for the new build system

myRobotCpp/build.gradle, wpilibc/athena/src/Ultrasonic.cpp
Also adds test to ensure this doens't happen again
=> Fixes ultrasonic declaration

build.gradle, hal/build.gradle, hal/include/HAL/ChipObject.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAI.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAO.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAccel.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAccumulator.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAlarm.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tAnalogTrigger.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tBIST.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tCounter.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tDIO.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tDMA.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tEncoder.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tGlobal.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tInterrupt.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tPWM.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tPower.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tRelay.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tSPI.h, ni-libraries/include/FRC_FPGA_ChipObject/nRoboRIO_FPGANamespace/tSysWatchdog.h, ni-libraries/include/FRC_NetworkCommunication/FRCComm.h, ni-libraries/include/FRC_NetworkCommunication/LoadOut.h, ni-libraries/include/FRC_NetworkCommunication/UsageReporting.h, ni-libraries/lib/genlinks.bat, ni-libraries/ni-libraries.gradle
Generates genlinks, and modifies headers to make them self contained
=> Adds gradle task to fix NI libraries whenever new ones are added.

wpilibc/shared/include/Commands/Command.h, wpilibc/shared/include/Commands/InstantCommand.h, wpilibc/shared/include/Commands/PrintCommand.h, wpilibc/shared/include/Commands/TimedCommand.h, wpilibc/shared/include/Commands/WaitCommand.h, wpilibc/shared/include/Commands/WaitForChildren.h, wpilibc/shared/include/Commands/WaitUntilCommand.h, wpilibc/shared/src/Commands/Command.cpp, wpilibc/shared/src/Commands/InstantCommand.cpp, wpilibc/shared/src/Commands/PrintCommand.cpp, wpilibc/shared/src/Commands/StartCommand.cpp, wpilibc/shared/src/Commands/TimedCommand.cpp, wpilibc/shared/src/Commands/WaitCommand.cpp, wpilibc/shared/src/Commands/WaitForChildren.cpp, wpilibc/shared/src/Commands/WaitUntilCommand.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Command.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/InstantCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/PrintCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/StartCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/TimedCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/WaitCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/WaitForChildren.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/WaitUntilCommand.java
This is the C++ side of issue #235. It implements default life-cycle methods in the `Command` class, adds two new classes (`TimedCommand` and `InstantCommand`) to handle common behaviors, and updates the existing commands to take advantage of these.
=> Easier Command Based Programming

wpilibc/athena/include/CameraServer.h, wpilibc/athena/include/WPILib.h, wpilibc/athena/src/CameraServer.cpp, wpilibc/shared/include/WPIErrors.h, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java
Not fully functional yet, but allows interoperation with LabView dashboard.
=> Add cscore-based CameraServer

wpilibc/shared/include/Commands/Command.h, wpilibc/shared/include/Commands/InstantCommand.h, wpilibc/shared/include/Commands/TimedCommand.h, wpilibc/shared/src/Commands/Command.cpp, wpilibc/shared/src/Commands/InstantCommand.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Command.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/InstantCommand.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/TimedCommand.java
Documentation was added for InstantCommand and TimedCommand.
=> Command::IsFinished() must be overriden by subclasses again

wpilibj/src/athena/java/edu/wpi/first/wpilibj/SerialPort.java
Some enums need a specific value when they get passed to JNI
=> Fixes incorrectly changed Java enums

hal/include/HAL/Errors.h, hal/include/HAL/SerialPort.h, hal/lib/athena/HAL.cpp, hal/lib/athena/SerialHelper.cpp, hal/lib/athena/SerialHelper.h, hal/lib/athena/SerialPort.cpp, wpilibc/athena/include/SerialPort.h, wpilibc/athena/src/SerialPort.cpp, wpilibj/src/athena/cpp/lib/SerialPortJNI.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SerialPort.java
Fix was made in LabVIEW, and this matches what was done there.
=> Searches for USB serial devices to get the correct VISA object

hal/lib/athena/SerialHelper.cpp, hal/lib/athena/SerialHelper.h, hal/lib/athena/SerialPort.cpp
Also removes regex and uses simple splits instead
=> Splits out SerialHelper to allow using OS or VISA resources

build.gradle, cppSettings.gradle, hal/build.gradle, myRobot/build.gradle, settings.gradle, wpilibc/athena.gradle, wpilibc/build.gradle, wpilibc/simulation.gradle, wpilibj/build.gradle, wpilibj/simulation.gradle, wpilibjIntegrationTests/build.gradle
This performs a major update and refactor to our gradle files. It updates us to version 1.5.1 of the WPILib Version Plugin, which fixes a lifecycle issue, and updates our manual dependency download code to use configurations instead of using bad manual configuration management. This has the wonderful benefit of removing about 100 lines from cppSettings.gradle. I've also removed all use of manual dependency strings, which are now generated via a set of simple helper functions.
@PeterJohnson @ThadHouse
=> Gradle configuration

ni-libraries/ni-libraries.gradle
Still requires manual intervention to make files not readonly, but that's easier.
=> Updates ni patch task to automatically switch all files to LF

hal/include/HAL/DriverStation.h, hal/include/HAL/HAL.h, hal/include/HAL/LabVIEW/HAL.h, hal/lib/athena/FRCDriverStation.cpp, hal/lib/athena/HAL.cpp
They can only include HAL/LV/HAL.h, HAL/cpp/*.h, and HAL/handles/*.h.
Nothing else will work properly.
=> Adds capabilities to support certain HAL functionality from LabVIEW

ni-libraries/include/FRC_NetworkCommunication/UsageReporting.h
Updated UsageReporting header file to file in azalea 2017 v8 release.
=> Updated Usage Reporting for 2017 v8 Image

wpilibc/athena/include/CameraServer.h, wpilibc/athena/src/CameraServer.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java
* Follow MixedCase rename.
* Add GetVideo function to get cameras by name.
Note: build will fail until https://github.com/wpilibsuite/cscore/pull/22 is merged.
=> Update CameraServer support.

styleguide/checkstyle.xml, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogOutput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogTrigger.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/PWM.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Relay.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/EncoderJNI.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/FRCNetComm.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/HAL.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/JNIWrapper.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/SPIJNI.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Command.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/ConstantsPortsTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/TestBench.java
Added the check style checks for redundant and unused imports.
=> Remove unused imports

styleguide/pmd-ruleset.xml, wpilibj/athena.gradle, wpilibj/build.gradle, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogOutput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogTrigger.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DoubleSolenoid.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/InterruptableSensorBase.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/IterativeRobot.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/PWM.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Relay.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotDrive.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SampleRobot.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SensorBase.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/EncoderJNI.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/FRCNetComm.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/HAL.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/JNIWrapper.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/SPIJNI.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/buttons/Trigger.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/LinkedListElement.java
@333fred Can you help me add this to the Jenkins build?
=> Add PMD and solve issues

wpilibc/athena/src/DigitalOutput.cpp
=> Fix javadoc typo

hal/include/HAL/cpp/SerialHelper.h, hal/lib/athena/SerialPort.cpp, hal/lib/athena/cpp/SerialHelper.cpp
Also makes the SerialHelper API public so it can be used externally.
=> Fixes SerialHelper when used with OS serial ports.

wpilibc/athena/include/RobotBase.h, wpilibc/athena/include/WPILib.h, wpilibc/athena/include/vision/VisionPipeline.h, wpilibc/athena/include/vision/VisionRunner.h, wpilibc/athena/include/vision/VisionRunner.inc, wpilibc/athena/src/RobotBase.cpp, wpilibc/athena/src/vision/VisionRunner.cpp, wpilibcIntegrationTests/src/VisionTest.cpp
Will add docs in a bit, just want to make sure I did everything right.
=> Adds CPP version of vision pipeline

wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
closes #361 
Does not need a C++ update because C++ already uses a `std::map`
=> Update SendableChooser to use HashMap

hal/include/HAL/Solenoid.h, hal/include/ctre/PCM.h, hal/lib/athena/Solenoid.cpp, hal/lib/athena/ctre/PCM.cpp
Closes #417. @ozrien look good to you?
=> Adds SetAllSolenoids function to CTRE PCM code

wpilibc/athena/src/IterativeRobot.cpp, wpilibc/athena/src/RobotBase.cpp, wpilibc/athena/src/SampleRobot.cpp, wpilibc/sim/src/IterativeRobot.cpp, wpilibc/sim/src/RobotBase.cpp, wpilibc/sim/src/SampleRobot.cpp
=> Call SmartDashboard::init() in RobotBase constructor.

wpilibc/build.gradle
=> Upgraded Doxygen gradle plugin to 0.3

wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
closes #432 
This brings the java implementation inline with the C++ implementation and documentation.
=> Java SendableChooser no longer sets a default on addObject

hal/include/HAL/Errors.h, hal/include/HAL/OSSerialPort.h, hal/lib/athena/HAL.cpp, hal/lib/athena/OSSerialPort.cpp, wpilibj/athena.gradle, wpilibj/src/athena/cpp/lib/OSSerialPortJNI.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/OSSerialPortJNI.java
Still need to write JNI, but want to get a first check on if people
thinks it looks right.
=> Starts the OS level serial port

wpilibj/src/athena/java/edu/wpi/first/wpilibj/vision/VisionRunner.java
Re: https://github.com/wpilibsuite/allwpilib/pull/388/files#r92914309
=> Allow VisionRunner to stop

wpilibc/shared/include/Commands/Command.h, wpilibc/shared/include/Commands/ConditionalCommand.h, wpilibc/shared/src/Commands/Command.cpp, wpilibc/shared/src/Commands/ConditionalCommand.cpp, wpilibcIntegrationTests/include/command/MockConditionalCommand.h, wpilibcIntegrationTests/src/command/ConditionalCommandTest.cpp, wpilibcIntegrationTests/src/command/MockConditionalCommand.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Command.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/command/ConditionalCommandTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/command/MockConditionalCommand.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/command/CommandTestSuite.java
Tests and documentation for ConditionalCommand were also added. This is a fixed version of #9, so it doesn't support lambdas.
Closes #9
=> Added a conditional command that chooses 1 of 2 commands

wpilibc/athena/include/CameraServer.h, wpilibc/athena/src/CameraServer.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java
* Add properties and video mode NetworkTables interchange.
* Automatically serve Axis cameras so they're accessible via USB.
=> CameraServer updates

wpilibc/sim/src/DriverStation.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/sim/java/edu/wpi/first/wpilibj/DriverStation.java
It's unlikely that anyone is still using the Blue Kwikbyte DS from 2009 and the reference is confusing to people who weren't around then.
=> Remove comments about Blue DS

wpilibc/athena/src/CameraServer.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java
Unfortunately, due to the way NT synchronization is currently performed,
this has unexpected and undesirable behavior: when a dashboard (or any other
NT client) is left running between code restarts, when it reconnects, any
code settings will be overwritten by the NT synchronization process.  As
fixing this will require a fairly major NT change (and likely a user-visible
one), it's not desirable to do at this point in the year.
Instead, disable NT driven settings entirely (e.g. make the NT interface
publish only).  To emphasize the read-only nature of the NT values, attempts
to change the NT values will be immediately overridden by CameraServer.
To better inform users about the actual property names (e.g. for use in their
code), the "raw_" settings no longer have "raw_" removed from their …
=> CameraServer: Remove NT-driven settings.

wpilibc/athena/include/CameraServer.h, wpilibc/athena/src/CameraServer.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java
Also add GetServer() functions so the automatically created VideoSink can
be retrieved by user code if desired.
=> CameraServer: auto-increment startAutomaticCapture().

wpilibc/athena/src/I2C.cpp
=> Fixes I2C read change size of pointer

wpilibc/athena/src/SPI.cpp
Adds a stack allocation for most use cases.
=> Fixes memory leak for SPI reads

hal/lib/athena/I2C.cpp, wpilibc/athena/src/I2C.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/I2C.java
=> Corrects assumptions about return values from i2c-lib

wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
Found some minor typos on the setDefault...() method parameter descriptions
=> Fixed Spelling Mistakes in SmartDashboard.java

styleguide/checkstyle.xml, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalInput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalOutput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Relay.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotBase.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/command/CommandSequentialGroupTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/BuiltInAccelerometerTest.java
Re: https://github.com/wpilibsuite/allwpilib/pull/461#discussion_r96167796
=> Add Checkstyle WhitespaceAfter check

wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
closes #491 
~SmartDashboard will also need an update.~ SmartDashboard respects the array order already.
=> SendableChooser Structure HashMap -> LinkedHashMap

wpilibc/athena/include/RobotDrive.h, wpilibc/athena/src/RobotDrive.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotDrive.java
Also updates the limit method to use Math.max & Math.min.
=> Refactor RobotDrive squaring into method

wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
=> Make SmartDashboard methods static

.travis.yml
This should be merged after styleguide#41.
=> Travis now passes the current year to wpiformat

hal/include/HAL/I2C.h, hal/include/HAL/SPI.h, hal/lib/athena/I2C.cpp, hal/lib/athena/SPI.cpp, wpilibc/athena/include/I2C.h, wpilibc/athena/include/SPI.h, wpilibc/athena/src/I2C.cpp, wpilibc/athena/src/SPI.cpp, wpilibj/src/athena/cpp/lib/I2CJNI.cpp, wpilibj/src/athena/cpp/lib/SPIJNI.cpp, wpilibj/src/athena/java/edu/wpi/first/wpilibj/I2C.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SPI.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/I2CJNI.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/SPIJNI.java
=> Switches SPI and I2C to use enums in the HAL for ports

hal/include/HAL/cpp/fpga_clock.h, hal/lib/shared/cpp/fpga_clock.cpp
Useful for some of the scenarios in C++ where using the chrono wrappers
might be very helpful.
=> Adds chrono wrapper around fpga time

hal/include/HAL/cpp/priority_condition_variable.h, hal/include/HAL/cpp/priority_mutex.h
=> Fixes hal shim from alias to using item

hal/include/HAL/cpp/Log.h, hal/lib/athena/FRCDriverStation.cpp, hal/lib/athena/HAL.cpp, hal/lib/athena/SPI.cpp, wpilibc/athena/include/RobotBase.h, wpilibc/athena/src/IterativeRobot.cpp, wpilibc/athena/src/SampleRobot.cpp, wpilibc/athena/src/Servo.cpp, wpilibc/athena/src/Timer.cpp, wpilibc/athena/src/Utility.cpp, wpilibc/shared/src/Commands/PrintCommand.cpp, wpilibc/shared/src/Commands/Scheduler.cpp, wpilibc/sim/include/RobotBase.h, wpilibc/sim/include/WPILib.h, wpilibc/sim/include/simulation/MainNode.h, wpilibc/sim/src/DriverStation.cpp, wpilibc/sim/src/IterativeRobot.cpp, wpilibc/sim/src/SampleRobot.cpp, wpilibc/sim/src/Utility.cpp, wpilibc/sim/src/simulation/SimContinuousOutput.cpp, wpilibc/sim/src/simulation/SimDigitalInput.cpp, wpilibc/sim/src/simulation/SimEncoder.cpp, wpilibc/sim/src/simulation/SimFloatInput.cpp, wpilibc/sim/src/simulation/SimGyro.cpp, wpilibcIntegrationTests/src/NotifierTest.cpp, wpilibcIntegrationTests/src/TestEnvironment.cpp, wpilibj/src/athena/cpp/lib/HALUtil.cpp
std::cout and std::printf were replaced with llvm::outs() and std::cerr was replaced with llvm::errs().
=> Replaced STL streams with LLVM's raw_ostream

wpilibc/shared/include/Commands/ConditionalCommand.h, wpilibc/shared/src/Commands/ConditionalCommand.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java
This also properly handles nullptrs passed into ConditionalCommand
instead of having Undefined Behavior.
=> Remove memory leak in ConditionalCommand

wpilibc/shared/include/Commands/Subsystem.h, wpilibc/shared/src/Commands/Scheduler.cpp, wpilibc/shared/src/Commands/Subsystem.cpp, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Scheduler.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/command/Subsystem.java
=> Add periodic method to subsystems

wpilibj/src/athena/java/edu/wpi/first/wpilibj/Encoder.java
=> Fix encoder sourceA null check

build.gradle, styleguide/checkstyle.xml, styleguide/suppressions.xml, wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogGyro.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Compressor.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalGlitchFilter.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalInput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalOutput.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Encoder.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/InterruptableSensorBase.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/Resource.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotBase.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotDrive.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SPI.java, wpilibj/src/athena/java/edu/wpi/first/wpilibj/SerialPort.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/CircularBuffer.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/PIDController.java, wpilibj/src/shared/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/PIDToleranceTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/command/MockCommand.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MotorEncoderTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PCMTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/MotorEncoderFixture.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/AntJunitLanucher.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/TestBench.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/TestSuite.java
Added a few checks too:
- SimplifyBooleanExpression
- SimplifyBooleanReturn
- StringLiteralEquality
- UnnecessaryParentheses
- ~ExplicitInitializationCheck~
=> Update to CheckStyle 8.1

wpilibj/athena.gradle, wpilibjIntegrationTests/build.gradle
Will break otherwise when I push a new version
=> Force OpenCV to 3.1.0

config.gradle, gmock/build.gradle, hal/build.gradle, hal/src/main/native/include/HAL/cpp/priority_mutex.h, hal/src/main/native/shared/cpp/priority_mutex.cpp, wpilibc-examples/build.gradle, wpilibc/build.gradle, wpilibcIntegrationTests/build.gradle
Did these in cscore and the other repos, but forgot about some of the
odditieis jenkins has.
=> Fixes builds with skipAthena and onlyAthena, and mac builds

hal/build.gradle, wpilibc/build.gradle
Will someone with a real linux system, and not wsl test this? run
-PonlyAthena, then clean, then -PskipAthena.
=> Gets wpilib compiling with skipAthena and onlyAthena flags

wpilibj/src/main/java/edu/wpi/first/wpilibj/SerialPort.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/OSSerialPortJNI.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/SerialPortJNI.java, wpilibj/src/main/native/cpp/OSSerialPortJNI.cpp, wpilibj/src/main/native/cpp/SerialPortJNI.cpp
=> Fix recieve typo in JNI names.

wpilibj/publish.gradle, wpilibj/src/main/java/edu/wpi/first/wpilibj/vision/package-info.java
Remove reference check and fix HTML error
=> Renable javadoc fail on error

wpilibc/src/main/native/cpp/IterativeRobot.cpp, wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/cpp/TimedRobot.cpp, wpilibc/src/main/native/include/IterativeRobotBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobot.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
It's not legal to call a virtual function from within a constructor,
so the user override is never called (the base function is always called).
See https://isocpp.org/wiki/faq/strange-inheritance#calling-virtuals-from-ctors
=> Fix IterativeRobot/TimedRobot RobotInit().

.styleguide
=> .styleguide now uses generalized config file format

wpilibc/src/main/native/cpp/Compressor.cpp, wpilibc/src/main/native/cpp/Servo.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java
=> Add missing usage reporting.

build.gradle, hal/build.gradle, wpilibc-examples/build.gradle, wpilibc/build.gradle, wpilibcIntegrationTests/build.gradle, wpilibj/build.gradle, wpilibjIntegrationTests/build.gradle
Also update to wpilib-version-plugin 2.0.
=> Depend on wpiutil 3.+, ntcore 4.+, cscore 1.+ rather than just +.

wpilibc/src/main/native/cpp/SpeedControllerGroup.cpp, wpilibc/src/main/native/include/SpeedControllerGroup.h, wpilibc/src/main/native/include/SpeedControllerGroup.inc, wpilibc/src/main/native/include/WPILib.h, wpilibcIntegrationTests/src/FRCUserProgram/cpp/MockSpeedController.cpp, wpilibcIntegrationTests/src/FRCUserProgram/cpp/SpeedControllerGroupTest.cpp, wpilibcIntegrationTests/src/FRCUserProgram/headers/MockSpeedController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedControllerGroup.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/MockSpeedController.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/SpeedControllerGroupTest.java
Thoughts on adding something like this?
=> Add SpeedControllerGroup

hal/src/main/native/athena/HAL.cpp, hal/src/main/native/sim/HAL.cpp, wpilibc/src/main/native/cpp/ErrorBase.cpp, wpilibc/src/main/native/include/ErrorBase.h
Partial fix to #663, and most likely the best we are going to be able to
get.
=> Adds HAL_Initialize to ErrorBase constructor, and makes HAL_Initialize properly reentrant

wpilibc/src/main/native/cpp/Drive/Vector2d.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/Vector2d.java
=> Specified angle units for Vector2d rotate() function.

wpilibj/src/main/java/edu/wpi/first/wpilibj/can/CANJNI.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/can/CANStatus.java, wpilibj/src/main/native/cpp/CANJNI.cpp, wpilibj/src/main/native/cpp/HALUtil.cpp, wpilibj/src/main/native/cpp/HALUtil.h, wpilibj/src/test/java/edu/wpi/first/wpilibj/can/CANStatusTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/can/CANStatusTest.java
Call already existed in the HAL.
=> Adds JNI call to get CANStatus

wpilibc/src/main/native/cpp/CameraServer.cpp
A PR didn't rerun the formatter before merging.
=> Fix formatting in CameraServer.cpp

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/cpp/GenericHID.cpp, wpilibc/src/main/native/cpp/Joystick.cpp, wpilibc/src/main/native/cpp/XboxController.cpp, wpilibc/src/main/native/include/DriverStation.h, wpilibc/src/main/native/include/GamepadBase.h, wpilibc/src/main/native/include/GenericHID.h, wpilibc/src/main/native/include/Joystick.h, wpilibc/src/main/native/include/JoystickBase.h, wpilibc/src/main/native/include/XboxController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/GamepadBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/JoystickBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/DriveTrain.java
I also shuffled around the HID interfaces to be more intuitive and deprecated
some Joystick and XboxController member functions.
Supersedes #89.
=> Added functions for detecting button press and release events

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
=> Improve error reporting for the new TCP netconsole.

hal/build.gradle, wpilibc/build.gradle, wpilibj/build.gradle
Will be used to create a generator for IDE's to get include paths.
=> Adds header task to print out all headers

build.gradle
Can be disabled with -PskipWarningPrints
=> Adds warning prints to native library builds

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/include/DriverStation.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/HAL.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/MatchInfoData.java, wpilibj/src/main/native/cpp/HAL.cpp, wpilibj/src/main/native/cpp/HALUtil.cpp, wpilibj/src/main/native/cpp/HALUtil.h, wpilibj/src/test/java/edu/wpi/first/wpilibj/hal/MatchInfoDataTest.java
Uses caching, matching the joystick calls.
=> Adds match specific calls to Java and C++

.clang-format, .travis.yml, hal/src/main/native/athena/Interrupts.cpp, hal/src/main/native/include/HAL/cpp/Log.h, hal/src/main/native/include/HAL/handles/IndexedClassedHandleResource.h, hal/src/main/native/include/HAL/handles/LimitedClassedHandleResource.h, wpilibc/src/main/native/cpp/Commands/PIDSubsystem.cpp, wpilibc/src/main/native/cpp/Counter.cpp, wpilibc/src/main/native/cpp/DigitalOutput.cpp, wpilibc/src/main/native/cpp/InterruptableSensorBase.cpp, wpilibc/src/main/native/cpp/LiveWindow/LiveWindow.cpp, wpilibc/src/main/native/cpp/SmartDashboard/SmartDashboard.cpp, wpilibcIntegrationTests/src/FRCUserProgram/cpp/NotifierTest.cpp, wpilibcIntegrationTests/src/FRCUserProgram/cpp/PIDToleranceTest.cpp, wpilibcIntegrationTests/src/FRCUserProgram/cpp/TiltPanCameraTest.cpp
This should be merged after styleguide#40.
=> Upgraded clang-format to 5.0

hal/src/main/native/include/MockData/DriverStationData.h, hal/src/main/native/sim/DriverStation.cpp, hal/src/main/native/sim/MockData/DriverStationData.cpp, hal/src/main/native/sim/MockData/DriverStationDataInternal.h, hal/src/test/native/cpp/DriverStationTests.cpp
Thanks @pjreiniger for the initiali implementation and work on this.
=> Adds ability to simulate joysticks and event info

wpilibc/src/main/native/cpp/PIDController.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
A clamp() helper function was written based on C++17's std::clamp().
=> Simplified PIDController integration logic

hal/src/main/native/include/MockData/I2CData.h, hal/src/main/native/include/MockData/NotifyListener.h, hal/src/main/native/include/MockData/NotifyListenerVector.h, hal/src/main/native/include/MockData/SPIData.h, hal/src/main/native/sim/MockData/I2CData.cpp, hal/src/main/native/sim/MockData/I2CDataInternal.h, hal/src/main/native/sim/MockData/NotifyCallbackHelpers.cpp, hal/src/main/native/sim/MockData/NotifyCallbackHelpers.h, hal/src/main/native/sim/MockData/SPIData.cpp, hal/src/main/native/sim/MockData/SPIDataInternal.h
Used to replace const_cast in SPI and I2c sim functions
=> Adds a const buffer listener

hal/src/main/native/athena/HAL.cpp, hal/src/main/native/shared/cpp/fpga_clock.cpp, hal/src/main/native/sim/MockHooks.cpp
Depends on wpilibsuite/wpiutil#56.
=> Unify WPI_Now and HAL_GetFPGATime.

wpilibc/src/main/native/cpp/Filters/LinearDigitalFilter.cpp, wpilibc/src/main/native/include/Filters/LinearDigitalFilter.h, wpilibc/src/main/native/include/circular_buffer.h, wpilibc/src/main/native/include/circular_buffer.inc, wpilibcIntegrationTests/src/FRCUserProgram/cpp/CircularBufferTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/CircularBuffer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/filters/LinearDigitalFilter.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/CircularBufferTest.java
CircularBuffer also replaces the use of queues in PIDController.
=> CircularBuffer now uses an idiomatic interface in C++ and Java

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/cpp/MotorSafetyHelper.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/MotorSafetyHelper.java
=> Fixes MotorSafetyHelper locking and race conditions

wpilibc/src/main/native/cpp/Ultrasonic.cpp, wpilibc/src/main/native/include/Commands/Scheduler.h, wpilibc/src/main/native/include/Ultrasonic.h
This is related to issue #414.
=> Removed unused includes and replaced Ultrasonic's std::set with std::vector

wpilibc/src/main/native/cpp/PIDController.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
This is branched from my `pidcontroller-cleanup` branch so it includes all of those changes as well.
=> Fix Continuous PIDController Wrapping

hal/src/main/native/athena/Notifier.cpp
This race was caused by holding a lock while calling into FRC_ChipObject,
which was waiting for the callback to exit before returning, and our
callback wanted to grab the same lock.
=> Fix HAL_CleanNotifier race.

build.gradle
This is what prints warnings to console.
=> Update to latest native plugin

test-scripts/jenkins-run-tests-get-results.sh
This commit reverts commit 0f3f5218adaa912ddde572fd3e6a295acbdc3187.
=> Revert #780 (don't kill FRC_NetCommDaemon).

hal/src/main/native/athena/Accelerometer.cpp, hal/src/main/native/athena/HAL.cpp, hal/src/main/native/athena/SPI.cpp, hal/src/main/native/include/HAL/HAL.h, hal/src/main/native/include/MockData/CanData.h, hal/src/main/native/include/MockData/DriverStationData.h, hal/src/main/native/sim/DriverStation.cpp, hal/src/main/native/sim/HAL.cpp, hal/src/main/native/sim/MockData/CanDataInternal.cpp, hal/src/main/native/sim/MockData/DriverStationData.cpp
These changes were generated by wpilibsuite/styleguide#106.
=> Replace C identifier lists with (void)

wpilibcExamples/src/main/cpp/templates/sample/Robot.cpp, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/sample/Robot.java
=> Cleaned up SampleRobot template and added warning about disabling motor safety

wpilibc/src/main/native/cpp/SmartDashboard/SmartDashboard.cpp
It's possible for SmartDashboard functions to be called from static
initializers in user code, so use a magic static to force initialization
order.
=> SmartDashboard: Use magic static for static initialization.

hal/src/main/native/athena/DigitalInternal.cpp
Workaround for Image 13, potentially will have a fix for the season.
=> Fixes SPI bad chip select

wpilibc/src/main/native/cpp/AnalogPotentiometer.cpp, wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/cpp/RobotController.cpp, wpilibc/src/main/native/cpp/Timer.cpp, wpilibc/src/main/native/cpp/Utility.cpp, wpilibc/src/main/native/include/ControllerPower.h, wpilibc/src/main/native/include/DriverStation.h, wpilibc/src/main/native/include/RobotController.h, wpilibc/src/main/native/include/Utility.h, wpilibc/src/main/native/include/WPILib.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogPotentiometer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Utility.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/internal/HardwareTimer.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/AbstractInterruptTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/DriverStationTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/TimerTest.java
Unifies random functionality from other classes
Deprecates all old functions.
=> Adds RobotController class

hal/src/main/native/athena/SPI.cpp, hal/src/main/native/include/HAL/SPI.h, hal/src/main/native/sim/SPI.cpp, wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp, wpilibc/src/main/native/cpp/SPI.cpp, wpilibc/src/main/native/include/SPI.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/SPIJNI.java, wpilibj/src/main/native/cpp/SPIJNI.cpp
The SPI Accumulator functions have been moved from HAL to wpilib and rewritten
to use the automatic transfer engine.
=> Add support for automatic SPI transfer engine.

hal/src/main/native/athena/DIO.cpp, hal/src/main/native/athena/DigitalInternal.cpp, hal/src/main/native/athena/DigitalInternal.h, hal/src/main/native/include/HAL/DIO.h, hal/src/main/native/include/HAL/cpp/UnsafeDIO.h
Adds a function to raw set the DIO direction. Also adds a C++ unsafe
function to enable fast setting of DIO direction.
=> Adds TriState DIO functionality to the HAL

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/cpp/SmartDashboard/SendableBuilderImpl.cpp, wpilibc/src/main/native/cpp/SmartDashboard/SmartDashboard.cpp, wpilibc/src/main/native/include/SmartDashboard/SendableBuilderImpl.h, wpilibc/src/main/native/include/SmartDashboard/SmartDashboard.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
Also update all PutData values in main periodic loop (same as LiveWindow).
=> Fix SmartDashboard PutData to hook setters.

hal/src/main/native/include/MockData/SPIData.h, hal/src/main/native/sim/HAL.cpp, hal/src/main/native/sim/HALInitializer.h, hal/src/main/native/sim/MockData/SPIData.cpp, hal/src/main/native/sim/MockData/SPIDataInternal.h, hal/src/main/native/sim/SPI.cpp, simulation/adx_gyro_accelerometer/src/main/native/cpp/ADXL345_I2CAccelerometerData.cpp, simulation/adx_gyro_accelerometer/src/main/native/cpp/ADXL345_SpiAccelerometerData.cpp, simulation/adx_gyro_accelerometer/src/main/native/cpp/ADXL362_SpiAccelerometerData.cpp, simulation/adx_gyro_accelerometer/src/main/native/cpp/ADXRS450_SpiGyroWrapperData.cpp, simulation/adx_gyro_accelerometer/src/main/native/include/ADXL345_I2CAccelerometerData.h, simulation/adx_gyro_accelerometer/src/main/native/include/ADXL345_SpiAccelerometerData.h, simulation/adx_gyro_accelerometer/src/main/native/include/ADXL362_SpiAccelerometerData.h, simulation/adx_gyro_accelerometer/src/main/native/include/ADXRS450_SpiGyroWrapperData.h
Some thing got broken in the past couple of weeks with updates to the
HAL
=> Fixing bugs in simulation libraries

wpilibc/src/main/native/cpp/Commands/Subsystem.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Subsystem.java
Note that SmartDashboard and Shuffleboard will need to be updated to reflect this
=> Move subsystem command metadata to metadata key format

wpilibc/src/main/native/cpp/SmartDashboard/SmartDashboard.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
=> SmartDashboard override .name entry in putData(String, Sendable)

wpilibc/src/main/native/cpp/PIDController.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
=> Fix PIDController with Continuous and no Input Range set.

wpilibc/src/main/native/cpp/SpeedControllerGroup.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedControllerGroup.java
pidWrite() now takes m_isInverted into account in SpeedControllerGroup.
This relates to #886, forgetting to put the m_isInverted inline if.
=> Fixed issue #887

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/include/DriverStation.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
Because of an expected change in 2018 that didnt happen, we had a race
condition causing a 1 packet delay on all DS values. This updates that.
=> Fixes control data packet delay

wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/MatchInfoData.java
=> Makes FMS data never be a null string.

wpilibj/src/main/native/cpp/EncoderJNI.cpp
=> Fixes double to int to double cast in encoderJNI

wpilibc/src/main/native/cpp/TimedRobot.cpp, wpilibc/src/main/native/include/TimedRobot.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
=> Added TimedRobot::GetPeriod()

wpilibc/src/main/native/cpp/Drive/MecanumDrive.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
This aligns with the current behavior of DifferentialDrive
Fixes https://github.com/wpilibsuite/shuffleboard/issues/404
=> Invert right side motors in MecanumDrive sendable

hal/src/main/native/sim/DIO.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/DIOJNI.java, wpilibj/src/main/native/cpp/DIOJNI.cpp
Also adds missing sim TriState DIO HAL call, and a ToDo for later
=> Adds TriState JNI entry point

hal/src/main/native/athena/Notifier.cpp
Addresses #959, but not a good long term solution.
=> HAL Notifier: Don't disable the notifier manager

wpilibc/src/main/native/cpp/PWM.cpp, wpilibc/src/main/native/cpp/PWMSpeedController.cpp, wpilibc/src/main/native/include/PWMSpeedController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/PWM.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMSpeedController.java
Also change type to "PWM".  Move old PWM Sendable behavior for both value
and type to PWMSpeedController.
=> PWM: Use getRaw and setRaw for Sendable "Value" property.

.gitignore
This way a git clean will force remove the files that might break the build
=> Removes old version files from git ignore

hal/src/main/native/athena/DIO.cpp, hal/src/main/native/athena/DigitalInternal.cpp, hal/src/main/native/include/HAL/cpp/UnsafeDIO.h
less risk for errors in the future.
=> Uses ComputeDigitalMask function across HAL DIO

hal/src/main/native/athena/DIO.cpp, hal/src/main/native/athena/DigitalInternal.cpp, hal/src/main/native/include/HAL/cpp/UnsafeDIO.h
Reverts wpilibsuite/allwpilib#837
=> Revert "Uses ComputeDigitalMask function across HAL DIO"

wpilibc/src/main/native/cpp/TimedRobot.cpp, wpilibc/src/main/native/include/TimedRobot.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
Fixes #941 and reverts commit 67f9c9a5b3f74b4927b68fa7c9e48ec38183f56c.
=> TimedRobot now uses the Notifier HAL API

ntcore/src/main/native/include/ntcore_c.h
Moved from wpilibsuite/ntcore#274.
=> ntcore: Make header actually a C header

.gitignore, CMakeLists.txt, cameraserver/CMakeLists.txt, cameraserver/cameraserver-config.cmake, cscore/CMakeLists.txt, cscore/cscore-config.cmake, hal/CMakeLists.txt, hal/hal-config.cmake, ntcore/CMakeLists.txt, ntcore/ntcore-config.cmake, wpilib-config.cmake.in, wpilibc/CMakeLists.txt, wpilibc/wpilibc-config.cmake, wpilibj/CMakeLists.txt, wpilibj/wpilibj-config.cmake, wpiutil/CMakeLists.txt, wpiutil/wpiutil-config.cmake
Anybody with weird systems (like maybe a different version of linux, or a mac) can you test this please.
=> Adds CMake Builds

cscore/build.gradle
=> Adds cscore examples to builds

wpilibc/src/main/native/cpp/ADXL345_SPI.cpp, wpilibc/src/main/native/cpp/ADXL362.cpp, wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp, wpilibc/src/main/native/cpp/SPI.cpp, wpilibc/src/main/native/include/SPI.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_SPI.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL362.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java
Rising and Falling mean the opposite when active is set high vs low. Leading and trailing makes much more sense.
Closes #925
=> Makes SPI edge changes more obvious

hal/src/main/native/include/MockData/NotifyListenerVector.h
=> Switches NotifyListenerVector to SmallVector

wpilibcExamples/build.gradle, wpilibcExamples/publish.gradle, wpilibcExamples/src/main/cpp/commands/command/ReplaceMeCommand.cpp, wpilibcExamples/src/main/cpp/commands/command/ReplaceMeCommand.h, wpilibcExamples/src/main/cpp/commands/commandgroup/ReplaceMeCommandGroup.cpp, wpilibcExamples/src/main/cpp/commands/commandgroup/ReplaceMeCommandGroup.h, wpilibcExamples/src/main/cpp/commands/commands.json, wpilibcExamples/src/main/cpp/commands/instant/ReplaceMeInstantCommand.cpp, wpilibcExamples/src/main/cpp/commands/instant/ReplaceMeInstantCommand.h, wpilibcExamples/src/main/cpp/commands/pidsubsystem/ReplaceMePIDSubsystem.cpp, wpilibcExamples/src/main/cpp/commands/pidsubsystem/ReplaceMePIDSubsystem.h, wpilibcExamples/src/main/cpp/commands/subsystem/ReplaceMeSubsystem.cpp, wpilibcExamples/src/main/cpp/commands/subsystem/ReplaceMeSubsystem.h, wpilibcExamples/src/main/cpp/commands/timed/ReplaceMeTimedCommand.cpp, wpilibcExamples/src/main/cpp/commands/timed/ReplaceMeTimedCommand.h, wpilibcExamples/src/main/cpp/commands/trigger/ReplaceMeTrigger.cpp, wpilibcExamples/src/main/cpp/commands/trigger/ReplaceMeTrigger.h, wpilibjExamples/publish.gradle, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/command/ReplaceMeCommand.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/commandgroup/ReplaceMeCommandGroup.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/commands.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/instant/ReplaceMeInstantCommand.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/pidsubsystem/ReplaceMePIDSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/subsystem/ReplaceMeSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/timed/ReplaceMeTimedCommand.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/trigger/ReplaceMeTrigger.java
WIP. Still need to finish adding the rest of the C++ commands, and add publishing.
=> Adds command examples to built examples

cameraserver/src/main/java/edu/wpi/first/wpilibj/vision/VisionPipeline.java, cameraserver/src/main/java/edu/wpi/first/wpilibj/vision/VisionRunner.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/CounterBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/NamedSendable.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDInterface.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDOutput.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/buttons/Trigger.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/CommandGroup.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Scheduler.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/util/SortedVector.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/UnitTestUtility.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/commandbased/Robot.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MockDS.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PDPTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/ITestFixture.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/mockhardware/FakeEncoderSource.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/QuickTest.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/TestBench.java
Generated by wpilibsuite/styleguide#115.
=> Removed extra newlines after open curly braces

styleguide/checkstyle.xml, styleguide/checkstyleExamples.xml, styleguide/pmd-ruleset.xml, styleguide/suppressions.xml, tidy-html.conf, tidy-xml.conf, wpilibj/src/main/java/edu/wpi/first/wpilibj/package.html
Generated by wpilibsuite/styleguide#52.
=> Format HTML and XML files

wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
=> Replaces Timer in PIDController.java with Notifier

hal/src/main/native/include/Simulation/AccelerometerSim.h, hal/src/main/native/include/Simulation/AnalogGyroSim.h, hal/src/main/native/include/Simulation/AnalogInSim.h, hal/src/main/native/include/Simulation/AnalogOutSim.h, hal/src/main/native/include/Simulation/AnalogTriggerSim.h, hal/src/main/native/include/Simulation/DIOSim.h, hal/src/main/native/include/Simulation/DigitalPWMSim.h, hal/src/main/native/include/Simulation/DriverStationSim.h, hal/src/main/native/include/Simulation/EncoderSim.h, hal/src/main/native/include/Simulation/PCMSim.h, hal/src/main/native/include/Simulation/PDPSim.h, hal/src/main/native/include/Simulation/PWMSim.h, hal/src/main/native/include/Simulation/RelaySim.h, hal/src/main/native/include/Simulation/RoboRioSim.h, hal/src/main/native/include/Simulation/SPIAccelerometerSim.h, hal/src/test/native/cpp/Sim/SimInitializationTest.cpp
Also adds test to ensure all the sim headers get compiled
Closes #1068
=> Fixes pessimistic std::move

build.gradle, styleguide/pmd-ruleset.xml, test-scripts/deploy-and-run-test-on-robot.sh, test-scripts/jenkins-run-tests-get-results.sh, test-scripts/run-tests-on-robot.sh
=> Add spotless to check line endings

wpilibc/src/main/native/cpp/Preferences.cpp, wpilibc/src/main/native/include/Preferences.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PreferencesTest.java
=> Add removeAll to preferences

build.gradle
New version handles dependency extraction better, and easier for IDEs
=> Updates NativeUtils dependency

hal/src/main/java/edu/wpi/first/wpilibj/CANData.java, hal/src/main/java/edu/wpi/first/wpilibj/hal/CANAPIJNI.java, hal/src/main/native/athena/CANAPI.cpp, hal/src/main/native/athena/HAL.cpp, hal/src/main/native/athena/HALInitializer.h, hal/src/main/native/cpp/jni/CANAPIJNI.cpp, hal/src/main/native/cpp/jni/HALUtil.cpp, hal/src/main/native/cpp/jni/HALUtil.h, hal/src/main/native/include/HAL/CANAPI.h, hal/src/main/native/include/HAL/Errors.h, hal/src/main/native/include/HAL/Types.h, hal/src/main/native/include/HAL/handles/HandlesInternal.h, hal/src/main/native/sim/CANAPI.cpp, hal/src/main/native/sim/HAL.cpp, hal/src/main/native/sim/HALInitializer.h, hal/src/test/native/cpp/can/CANTest.cpp, wpilibc/src/main/native/cpp/CAN.cpp, wpilibc/src/main/native/include/CAN.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/CAN.java
=> Adds new CAN API

ntcore/src/test/native/cpp/ValueTest.cpp
Thank you for the suggestion @PeterJohnson
=> Fix mac builds

wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java
=> Changes notifier to be closable.

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/cpp/RobotBase.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
Helpful for simulation, which might not use our main.
=> Fixes initialization not using the main provided

shared/examplecheck.gradle, wpilibcExamples/build.gradle, wpilibcExamples/src/main/cpp/examples/MotorControlEncoder/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/examples.json, wpilibcExamples/src/main/cpp/templates/templates.json, wpilibjExamples/build.gradle, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/motorcontrolencoder/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json
Also checks that all items in the json file have a matching example
One was missing from C++, that example was added (The one in eclipse was completely wrong)
=> Adds tests to ensure all examples have matching item in json file

myRobot/build.gradle, shared/javacpp/setupBuild.gradle, shared/jni/setupBuild.gradle, shared/libuv.gradle, shared/plugins/setupBuild.gradle, wpilibc/build.gradle, wpilibcExamples/build.gradle, wpilibcIntegrationTests/build.gradle, wpilibj/build.gradle
Don't have a way to explicitly test everything, but I did test that the library does get linked.
=> Add libuv dependency

build.gradle
Also removes an unused function from the old versioning plugin days.
=> Updates things that are deprecated in gradle 4.8

ntcore/src/test/java/edu/wpi/first/networktables/ConnectionListenerTest.java, shared/java/javacommon.gradle
Offering this as an alternative to #1112.  I'd still like to go through and really start to rewrite the tests to really use JUnit 5 features but I wanted to get this out as an alt...
=> Disable ntcore tests using JUnit 5

cscore/src/main/native/cpp/jni/CameraServerJNI.cpp, hal/src/main/native/cpp/jni/HALUtil.cpp, ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp, wpiutil/src/main/native/include/wpi/jni_util.h
Helps ensure they get freed properly (We have had a few cases before where this wasn't the case.
=> Adds simple functionality to allocate JNI global classes

gen/wpilibj_frcnetcomm.py, hal/src/main/java/edu/wpi/first/wpilibj/hal/FRCNetComm.java
=> Makes FRCNetComm interfaces static final classes.

wpiutil/.styleguide, wpiutil/src/main/native/include/wpi/MapVector.h
Supersedes wpilibsuite/wpiutil#69.
=> Import MapVector from LLVM.

hal/src/main/native/sim/Interrupts.cpp, ntcore/src/main/native/cpp/CallbackManager.h, ntcore/src/main/native/cpp/Storage.cpp, ntcore/src/test/native/cpp/StorageTest.cpp
We have done things recently that have broken any builds before VS 2015
=> Removes MSVC 2013 Shims

wpilibc/src/main/native/include/interfaces/Gyro.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java
=> Explicitly states the gyro direction contract for the Gyro interface

wpilibc/src/main/native/cpp/Commands/Command.cpp, wpilibc/src/main/native/cpp/Commands/CommandGroup.cpp, wpilibc/src/main/native/cpp/Commands/Scheduler.cpp, wpilibc/src/main/native/cpp/Commands/Subsystem.cpp, wpilibc/src/main/native/include/Commands/Command.h, wpilibc/src/main/native/include/Commands/CommandGroup.h, wpilibc/src/main/native/include/Commands/Scheduler.h, wpilibcIntegrationTests/src/main/native/cpp/command/CommandTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Subsystem.java
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/73)
=> Cleaned up Command container iteration code

wpilibc/src/main/native/cpp/PowerDistributionPanel.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistributionPanel.java
=> Add PDP usage reporting

MavenArtifacts.md
=> Add maven documentation

wpiutil/src/main/native/include/wpi/jni_util.h
Add a length-taking overload so that if a length happens to be provided for
a jarray, the direct byte buffer overload is not used.
=> Make JxArrayRef less error-prone for jxArray

simulation/frc_gazebo_plugins/src/clock/cpp/clock.cpp, simulation/frc_gazebo_plugins/src/dc_motor/cpp/dc_motor.cpp, simulation/frc_gazebo_plugins/src/drive_motor/cpp/drive_motor.cpp, simulation/frc_gazebo_plugins/src/encoder/cpp/encoder.cpp, simulation/frc_gazebo_plugins/src/gyro/cpp/gyro.cpp, simulation/frc_gazebo_plugins/src/limit_switch/cpp/internal_limit_switch.cpp, simulation/frc_gazebo_plugins/src/limit_switch/cpp/limit_switch.cpp, simulation/frc_gazebo_plugins/src/pneumatic_piston/cpp/pneumatic_piston.cpp, simulation/frc_gazebo_plugins/src/potentiometer/cpp/potentiometer.cpp, simulation/frc_gazebo_plugins/src/rangefinder/cpp/rangefinder.cpp, simulation/frc_gazebo_plugins/src/servo/cpp/servo.cpp
The Normalize() calls appeared to have been no-ops in older versions of Gazebo.
=> Update gazebo plugins to Gazebo 9.

hal/src/main/native/athena/PWM.cpp
=> Fix Initialize PWM Port not checking for MXP port

build.gradle
Should fix lag after 15 or so builds
=> Update Native Utils to fix static allocations

build.gradle
ErrorProne fixes some Java 9 issues, vscode cpp fixes a bug and updates for lazy tasks, jni updates for lazy tasks
=> Update gradle dependencies

simulation/halsim_ds_socket/src/dev/native/cpp/main.cpp, simulation/halsim_ds_socket/src/main/native/cpp/DSCommPacket.cpp, simulation/halsim_ds_socket/src/main/native/cpp/main.cpp, simulation/halsim_ds_socket/src/main/native/include/DSCommPacket.h, simulation/halsim_ds_socket/src/main/native/include/FRCComm.h
Also adds the simulation packet to force switch the DS to local.
=> Switch DS Sim Sockets to use UV loops

wpiutil/src/main/native/include/wpi/uv/Buffer.h, wpiutil/src/test/native/cpp/uv/UvBufferTest.cpp
Buffers are reused on a regular basis in many use cases.
=> Add a SimpleBufferPool for uv::Buffer

cscore/src/main/native/cpp/UsbCameraImpl.cpp
Some cameras will accept a different resolution as the mode but then provide
JPEG images of a different size.  Trust the JPEG image size if available.
This also validates the JPEG image is actually JPEG.
=> UsbCamera: In JPEG mode, get size from image instead of mode.

wpilibc/src/main/native/cpp/SensorUtil.cpp, wpilibc/src/main/native/include/frc/SensorUtil.h
C++ PDP missing module check, and channel check called module
Java docs said 1 based
=> Fix SenserUtil issues

cscore/src/main/java/edu/wpi/cscore/AxisCamera.java, cscore/src/main/java/edu/wpi/cscore/CvSink.java, cscore/src/main/java/edu/wpi/cscore/CvSource.java, cscore/src/main/java/edu/wpi/cscore/HttpCamera.java, cscore/src/main/java/edu/wpi/cscore/MjpegServer.java, cscore/src/main/java/edu/wpi/cscore/UsbCamera.java, cscore/src/main/java/edu/wpi/cscore/UsbCameraInfo.java, cscore/src/main/java/edu/wpi/cscore/VideoListener.java, cscore/src/main/java/edu/wpi/cscore/VideoProperty.java, cscore/src/main/java/edu/wpi/cscore/VideoSink.java, cscore/src/main/java/edu/wpi/cscore/VideoSource.java, cscore/src/main/native/include/cscore_c.h, cscore/src/main/native/include/cscore_cpp.h, cscore/src/main/native/include/cscore_oo.h
Reformat the C++ documentation to use the normal comment style and
add doxygen grouping.
=> cscore: Documentation cleanups

styleguide/pmd-ruleset.xml, wpilibj/src/main/java/edu/wpi/first/wpilibj/filters/LinearDigitalFilter.java
=> Add UseConcurrentHashMap exception to PMD & clean NOPMDs

shared/java/javacommon.gradle
=> Fix errorprone so it is version locked & reports warnings

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java, hal/src/main/java/edu/wpi/first/wpilibj/hal/JNIWrapper.java, ntcore/src/main/java/edu/wpi/first/networktables/NetworkTablesJNI.java, shared/config.gradle, shared/jni/publish.gradle, wpiutil/src/main/java/edu/wpi/first/wpiutil/RuntimeDetector.java, wpiutil/src/main/java/edu/wpi/first/wpiutil/RuntimeLoader.java
Can be used for smarter extraction
The code has not been added to use this yet.
The hash file is stored next to the library file with the name `libraryName.hash`
=> Add hash files for JNI jars

hal/src/main/native/include/hal/Accelerometer.h, hal/src/main/native/include/hal/AnalogAccumulator.h, hal/src/main/native/include/hal/AnalogGyro.h, hal/src/main/native/include/hal/AnalogInput.h, hal/src/main/native/include/hal/AnalogOutput.h, hal/src/main/native/include/hal/AnalogTrigger.h, hal/src/main/native/include/hal/CAN.h, hal/src/main/native/include/hal/CANAPI.h, hal/src/main/native/include/hal/Compressor.h, hal/src/main/native/include/hal/Constants.h, hal/src/main/native/include/hal/Counter.h, hal/src/main/native/include/hal/DIO.h, hal/src/main/native/include/hal/DriverStation.h, hal/src/main/native/include/hal/Encoder.h, hal/src/main/native/include/hal/Errors.h, hal/src/main/native/include/hal/Extensions.h, hal/src/main/native/include/hal/HAL.h, hal/src/main/native/include/hal/I2C.h, hal/src/main/native/include/hal/Interrupts.h, hal/src/main/native/include/hal/Notifier.h, hal/src/main/native/include/hal/PDP.h, hal/src/main/native/include/hal/PWM.h, hal/src/main/native/include/hal/Ports.h, hal/src/main/native/include/hal/Power.h, hal/src/main/native/include/hal/Relay.h, hal/src/main/native/include/hal/SPI.h, hal/src/main/native/include/hal/SerialPort.h, hal/src/main/native/include/hal/Solenoid.h, hal/src/main/native/include/hal/Threads.h, hal/src/main/native/include/hal/Types.h
This helps organize the functions in the generated docs.
=> HAL: Add Doxygen module documentation

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java, cscore/src/main/java/edu/wpi/cscore/HttpCamera.java, cscore/src/main/java/edu/wpi/cscore/VideoCamera.java, cscore/src/main/java/edu/wpi/cscore/VideoEvent.java, cscore/src/main/java/edu/wpi/cscore/VideoMode.java, cscore/src/main/java/edu/wpi/cscore/VideoProperty.java, cscore/src/main/java/edu/wpi/cscore/VideoSink.java, cscore/src/test/java/edu/wpi/cscore/UsbCameraTest.java, hal/src/main/java/edu/wpi/first/wpilibj/sim/PDPSim.java, ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableValue.java, ntcore/src/main/java/edu/wpi/first/wpilibj/networktables/NetworkTable.java, wpilibc/src/main/native/include/frc/TimedRobot.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogTrigger.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogTriggerOutput.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/I2C.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Relay.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SerialPort.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/buttons/Trigger.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/util/SortedVector.java, wpiutil/src/main/java/edu/wpi/first/wpiutil/RuntimeLoader.java
This fixes two real bugs:
- TimedRobot had a m_period that was hiding the IterativeRobotBase m_period
and was not getting initialized.
- PDPSim was swapping two parameters to getCurrent()
=> Fix many errorprone warnings and two bugs

ntcore/doc/networktables2.adoc, ntcore/doc/networktables3.adoc
=> ntcore: Make protocol revision more visible in docs

wpiutil/src/main/native/cpp/HttpUtil.cpp, wpiutil/src/main/native/include/wpi/HttpUtil.h, wpiutil/src/test/native/cpp/HttpUtilTest.cpp
This is a non-blocking version of FindMultipartBoundary.
=> Add HttpMultipartScanner.

hal/src/main/java/edu/wpi/first/hal/sim/mockdata/DriverStationDataJNI.java, hal/src/main/java/edu/wpi/first/wpilibj/sim/CallbackStore.java, hal/src/main/java/edu/wpi/first/wpilibj/sim/NotifyCallback.java, hal/src/main/java/edu/wpi/first/wpilibj/sim/SimValue.java, hal/src/test/java/edu/wpi/first/hal/sim/AccelerometerSimTest.java, styleguide/suppressions.xml
I was doing more simulator updates, and noticed I wasn't getting yelled at for obvious checkstyle things. This turns a lot of things back on for things in a *sim* package
=> Adds more checkstyle checks to simulator stuff

wpiutil/src/main/native/cpp/WebSocket.cpp, wpiutil/src/main/native/cpp/WebSocketServer.cpp, wpiutil/src/main/native/include/wpi/WebSocket.h, wpiutil/src/main/native/include/wpi/WebSocketServer.h, wpiutil/src/test/native/cpp/WebSocketClientTest.cpp, wpiutil/src/test/native/cpp/WebSocketIntegrationTest.cpp, wpiutil/src/test/native/cpp/WebSocketServerTest.cpp, wpiutil/src/test/native/cpp/WebSocketTest.cpp, wpiutil/src/test/native/cpp/WebSocketTest.h
This is a RFC 6455 compliant implementation with both client and server support.
=> Add WebSocket implementation

wpilibc/src/main/native/include/frc/PIDController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
=> PIDController: Mention unit for 'period'

cameraserver/src/main/native/include/cameraserver/CameraServerShared.h
=> Adds virtual destructor to CameraServerShared

hal/build.gradle
Had generated file in wrong directory
=> Fix HAL Headers Zip

azure-pipelines.yml
Will need to be enabled by making a microsoft account for frcjenkins likely, but the builds work.
=> Add support for Azure Pipelines

azure-pipelines.yml
=> Publish tests to azure ci

hal/src/main/native/cpp/jni/HAL.cpp, hal/src/main/native/cpp/jni/HALUtil.cpp, hal/src/main/native/cpp/jni/HALUtil.h
Was invalidly not returning when the expected exception should have been thrown.
=> Fix JNI call throwing incorrect exception

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardContainer.cpp, wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardLayout.cpp, wpilibc/src/main/native/cpp/shuffleboard/SimpleWidget.cpp, wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardComponentBase.h, wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardContainer.h, wpilibc/src/main/native/include/frc/shuffleboard/SimpleWidget.h, wpilibc/src/test/native/cpp/shuffleboard/MockActuatorSendable.cpp, wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardInstanceTest.cpp, wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardTabTest.cpp, wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardTest.cpp, wpilibc/src/test/native/include/shuffleboard/MockActuatorSendable.h, wpilibcIntegrationTests/src/main/native/cpp/shuffleboard/ShuffleboardTabTest.cpp
The tests were right, but there were major implementation issues. This PR fixes them.
=> Fixes shuffleboard C++ tests, and runs them on desktop

build.gradle
Fixes describe bug, and removes timestamp from published version number
=> Updates version plugin to 2.2

azure-pipelines.yml, build.gradle, ntcore/src/test/java/edu/wpi/first/networktables/ConnectionListenerTest.java, shared/config.gradle, shared/java/javacommon.gradle, shared/java/javastyle.gradle, shared/nilibraries.gradle, styleguide/checkstyle.xml, styleguide/pmd-ruleset.xml, wpilibj/src/test/java/edu/wpi/first/wpilibj/command/ConditionalCommandTest.java
Might need to be mixed with the Java 11 PR.
=> Update to 2019 RoboRIO and 2019 v4 image

myRobot/src/main/java/MyRobot.java, myRobot/src/main/native/cpp/MyRobot.cpp
=> Make MyRobot compilation test use TimedRobot

wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp, wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
=> It's hip to be square: squaredInputs -> squareInputs

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/CameraServer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
A bit cleaner to use, and more standard for the current java. Still java 8 compatible
=> Use Array Constructor rather then new array to toArray

hal/src/main/native/athena/AnalogGyro.cpp
Closes #1145
In reference to #1145
=> Show calibrating for n seconds.

wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java
This PR addresses issue #1086. Not sure if ArrayList is the appropriate container is for the instances (could be switched to LinkedList) or if the synchronization on the list is needed.
=> Refactor Ultrasonic.java to use a List container to store the sensor instances.

wpilibcExamples/src/main/cpp/examples/HidRumble/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hidrumble/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hidrumble/Robot.java
As requested by: https://forums.usfirst.org/forum/general-discussions/first-programs/first-robotics-competition/competition-discussion/programming-aa/c-c-ac/85971-really-quick-question-about-afterglow-controller-rumble
=> Add an example showing how to use a hid rumbler

hal/src/main/native/athena/HAL.cpp
Should fix some deploy deadlocks
=> Use a kill -9 after attemting a safe kill

cscore/src/main/native/cpp/NetworkListener.h, cscore/src/main/native/linux/NetworkListener.cpp, cscore/src/main/native/osx/NetworkListener.cpp, cscore/src/main/native/windows/NetworkListener.cpp
This enables different platforms to use very different implementations.
=> NetworkListener: use Pimpl idiom

wpilibc/src/main/native/cpp/Filesystem.cpp, wpilibc/src/main/native/include/frc/Filesystem.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Filesystem.java
=> Add Deploy Directory detection for Java / C++

cscore/src/main/native/cpp/CvSinkImpl.cpp, cscore/src/main/native/cpp/CvSourceImpl.cpp, cscore/src/main/native/cpp/CvSourceImpl.h, cscore/src/main/native/cpp/HttpCameraImpl.cpp, cscore/src/main/native/cpp/HttpCameraImpl.h, cscore/src/main/native/cpp/Instance.cpp, cscore/src/main/native/cpp/Instance.h, cscore/src/main/native/cpp/MjpegServerImpl.cpp, cscore/src/main/native/cpp/SourceImpl.h, cscore/src/main/native/cpp/UnlimitedHandleResource.h, cscore/src/main/native/cpp/cscore_c.cpp, cscore/src/main/native/cpp/cscore_cpp.cpp, cscore/src/main/native/cpp/jni/CameraServerJNI.cpp, cscore/src/main/native/include/cscore_c.h, cscore/src/main/native/include/cscore_cpp.h, cscore/src/main/native/linux/UsbCameraImpl.cpp, cscore/src/main/native/linux/UsbCameraImpl.h, shared/opencv.gradle, wpilibc/src/main/native/cpp/RobotBase.cpp, wpilibc/src/main/native/include/frc/RobotBase.h, wpiutil/src/main/native/cpp/EventLoopRunner.cpp, wpiutil/src/main/native/include/wpi/EventLoopRunner.h
Also includes an EventLoopRunner fix.
Supersedes #1403.
=> cscore improvements to sink/source and shutdown

wpilibcExamples/build.gradle, wpilibcExamples/src/main/cpp/examples/HAL/c/Robot.c, wpilibcExamples/src/main/cpp/examples/examples.json
This is useful for certain people, and shows a few things like error messages, and DS things that are needed
=> Add an example of using the HAL directly

wpilibc/src/main/native/cpp/shuffleboard/RecordingController.cpp, wpilibc/src/main/native/cpp/shuffleboard/Shuffleboard.cpp, wpilibc/src/main/native/include/frc/shuffleboard/RecordingController.h, wpilibc/src/main/native/include/frc/shuffleboard/Shuffleboard.h, wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardEventImportance.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/EventImportance.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/RecordingController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.java
Closes #1406 (relies on wpilibsuite/shuffleboard#538)
Closes #1407
=> Add mechanism to control Shuffleboard recordings and add event markers

wpilibcExamples/src/main/cpp/templates/templates.json, wpilibcExamples/src/main/cpp/templates/timedskeleton/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/templates/timedskeleton/include/Robot.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timedskeleton/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timedskeleton/Robot.java
=> Add wpilibc and wpilibj skeleton templates, per vscode-wpilib#132

hal/src/main/native/athena/HAL.cpp, hal/src/main/native/include/hal/Errors.h
Not sure if these are the right messages, but they aren't currently included so better than nothing?
=> HAL: Add additional error messages to HAL_GetErrorMessage

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
=> DriverStation: fix error checking for GetXXXAxis and GetXXXPov

shared/opencv.gradle
Want to make sure beta 3 is using the latest
=> Bump OpenCV version

wpilibj/src/main/java/edu/wpi/first/wpilibj/command/PIDSubsystem.java
=> Add missing param javadoc comment and fix argument order inconsistency

hal/src/main/native/athena/CANAPI.cpp, hal/src/main/native/sim/CANAPI.cpp
Constant calls would result in timeout, because a valid packet wasn't returning early
=> Fix periodic can packets not being received properly

wpiutil/src/main/java/edu/wpi/first/wpiutil/RuntimeDetector.java
This is how I did it in C#, and it was the most reliable way I could find.
The following is the first line returned by that file.
`PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"`
=> Add support for raspbian extraction

build.gradle
versioning fixes multi tag issue
=> Update versioning and vscode plugin

ntcore/src/main/native/cpp/Dispatcher.cpp, ntcore/src/test/java/edu/wpi/first/networktables/ConnectionListenerTest.java
=> ntcore: Strip whitespace from IP addresses

wpilibc/src/main/native/include/frc/IterativeRobotBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
=> Update docs for disabled init to match all the other modes

cscore/src/main/native/cpp/MjpegServerImpl.cpp
This uses a 1-second window average to try to hit the desired FPS.
=> cscore: MjpegServer: Fix FPS limiting

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java, cscore/src/main/java/edu/wpi/cscore/VideoSink.java, cscore/src/main/native/cpp/PropertyContainer.cpp, cscore/src/main/native/cpp/PropertyContainer.h, cscore/src/main/native/cpp/SinkImpl.cpp, cscore/src/main/native/cpp/SinkImpl.h, cscore/src/main/native/cpp/SourceImpl.cpp, cscore/src/main/native/cpp/cscore_c.cpp, cscore/src/main/native/cpp/cscore_cpp.cpp, cscore/src/main/native/cpp/cscore_oo.cpp, cscore/src/main/native/cpp/jni/CameraServerJNI.cpp, cscore/src/main/native/include/cscore_c.h, cscore/src/main/native/include/cscore_cpp.h, cscore/src/main/native/include/cscore_oo.h, cscore/src/main/native/include/cscore_oo.inl
Same format as VideoSource.
Refactor properties json handling into PropertyContainer.
=> cscore: Add config json to VideoSink

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/cpp/SampleRobot.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SampleRobot.java
Simple search and manual-replace where needed.
=> Changed terminology from "Overload" to "Override".

README.md
=> Update README for 2019 changes.

hal/src/main/native/athena/PDP.cpp
Previously multiple instances would overrun with each other. This make all instances get the same HAL handle.
=> Allow multiple instances of the same PDP

simulation/halsim_ds_socket/src/test/native/cpp/DSCommPacketTest.cpp
Mac requires the double braces
=> Fix DS Comm button tests

wpiutil/src/main/native/cpp/uv/Pipe.cpp, wpiutil/src/main/native/include/wpi/uv/Pipe.h
=> Add reuse to pipe

wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDBase.java
=> Java PIDBase: Make setPIDSourceType and getPIDSourceType public

wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java
When there is more than one ultrasonic sensor, only the last sensor
instantiated would work due to incorrect array index management. This
replaces the previous approach with range-based for loops like the C++
implementation.
Supersedes #1589.
=> Fix Ultrasonic sensor runner thread

cscore/src/main/native/cpp/Frame.cpp
=> Fix Gray to BGR conversion in CameraServer

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
Additionally, add epochs for Shuffleboard, LiveWindow, and
Smartdashboard updates.
=> Add Shuffleboard calls to IterativeRobotBase in C++

wpilibc/src/test/native/cpp/WatchdogTest.cpp, wpilibj/src/test/java/edu/wpi/first/wpilibj/WatchdogTest.java
Theyre just not reliable at all
=> Complete disable watchdog tests on mac

cscore/src/main/native/windows/UsbCameraImpl.cpp, cscore/src/main/native/windows/UsbCameraImpl.h
Wait 50ms, and then bail if failure
=> Solve race in windows CS initialization

simulation/halsim_ds_socket/src/main/native/cpp/main.cpp, wpiutil/src/main/native/include/wpi/uv/Buffer.h
Otherwise, multiple pools happen
=> Remove copy from SimpleBufferPool

cmake/toolchains/arm-frc-gnueabi.toolchain.cmake, cmake/toolchains/arm-pi-gnueabihf.toolchain.cmake, cmake/toolchains/arm.toolchain.cmake, cmake/toolchains/gnu.toolchain.cmake
To be able to build the libraries from CMake. I've had a few cases where I wanted to be able to do this
Used to be a part of #1654 but split out.
=> Add cross toolchains for Rio and Pi

gradle.properties, settings.gradle
mostly for documentation for us, but it will be useful in the wpilib build for opencv
=> Add macro include skip

wpilibc/src/main/native/cpp/ErrorBase.cpp, wpilibc/src/main/native/include/frc/ErrorBase.h, wpilibc/src/main/native/include/frc/WPIErrors.h
Fixes #1726.
Incorporates #1725.
=> ErrorBase: Use magic static singleton for globals

azure-pipelines.yml, shared/java/javacommon.gradle
JaCoCo will give us Java test code coverage.
=> Add JaCoCo Support

simulation/halsim_gazebo/build.gradle
Reference shared/config.gradle instead of shared/plugins/setupBuild.gradle.
=> Don't build halsim_gazebo on raspbian

simulation/halsim_gazebo/build.gradle
This reverts commit d9cb57a429c4e7aac86733d18955ce834cc56e99.
=> Revert "Don't build halsim_gazebo on raspbian (#1737)"

buildSrc/build.gradle, shared/plugins/setupBuild.gradle, simulation/halsim_adx_gyro_accelerometer/build.gradle, simulation/lowfi_simulation/build.gradle
They'll pretty much never work
=> Unconditionally skip athena builds for sim

.styleguide, wpilibc/src/main/native/cpp/trajectory/TrapezoidProfile.cpp, wpilibc/src/main/native/include/frc/trajectory/TrapezoidProfile.h, wpilibc/src/test/native/cpp/TrapezoidProfileTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrapezoidProfile.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/TrapezoidProfileTest.java
This PR still needs unit tests although the C++ version is known to work. We need to decide on an approach for importing the units library, assuming we decide to keep it.
=> Add TrapezoidProfile class

hal/src/main/native/sim/DriverStation.cpp
=> Add HALSIM_SetSendError implementation

wpiutil/src/main/native/include/Eigen/Core, wpiutil/src/main/native/include/Eigen/src/Core/util/BlasUtil.h, wpiutil/src/test/native/cpp/EigenTest.cpp
This fixes the compilation errors from including Eigen. I also added tests for basic operations (multiplication, transpose, inverse) to make sure we didn't miss any template instantiation errors.
=> Fix Eigen compilation errors and add tests

buildSrc/build.gradle, shared/config.gradle
Adds -latomic by default to all linux builds
=> Update native utils to 2020.0.4

build.gradle
=> Update GradleVSCode version

wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java
Fixes javadoc whitespace in SendableBuilderImpl
=> format SendableBuilderImpl

wpilibc/src/main/native/include/frc/I2C.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/I2C.java
This PR replaces #929 which we cannot merge because it is out of date and the OP deleted their fork.
=> Add tip about writeBulk() to transaction()

hal/src/main/native/sim/DIO.cpp
=> Fix sim incorrectly setting dio port to initialized on cleanup

wpilibcExamples/src/main/cpp/examples/ElevatorTrapezoidProfile/cpp/Robot.cpp
Merging #1815 broke it, then #1814 was merged before fixing the failure.
=> Fix compilation error in elevator trapezoid profile example

styleguide/checkstyle.xml, wpiutil/build.gradle, wpiutil/generate_numbers.py, wpiutil/src/generate/Nat.java.in
=> Fix wpiutil number generation to be incremental, and import order

azure-pipelines.yml
Conditional builds to use batch builds for master, and release builds on tags.
=> Update to use artifactory to publish artifacts

wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp, wpilibc/src/main/native/cpp/IterativeRobot.cpp, wpilibc/src/main/native/cpp/PIDController.cpp, wpilibc/src/main/native/cpp/SPI.cpp, wpilibc/src/main/native/include/frc/SPI.h
Also fix a units deprecated warning in IterativeRobot.
=> Use units in SPI

CONTRIBUTING.md
=> Add information to contribute to frc-docs

hal/src/main/native/athena/PWM.cpp, wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp, wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp, wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp, wpilibc/src/main/native/cpp/drive/RobotDriveBase.cpp, wpilibc/src/main/native/include/frc/drive/RobotDriveBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.java, wpiutil/src/main/java/edu/wpi/first/wpiutil/math/MathUtils.java
Also use std::clamp() and MathUtils.clamp() in as many places as
possible in place of custom clamp functions or if statements.
=> Add MathUtils.clamp() for Java

wpilibc/src/main/native/cpp/frc2/command/Command.cpp, wpilibc/src/main/native/cpp/frc2/command/WaitCommand.cpp, wpilibc/src/main/native/include/frc2/command/Command.h, wpilibc/src/main/native/include/frc2/command/WaitCommand.h, wpilibc/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp, wpilibc/src/test/native/cpp/frc2/command/WaitCommandTest.cpp, wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/Constants.h, wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/OpenClaw.cpp, wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/include/RobotContainer.h, wpilibcExamples/src/main/cpp/examples/SchedulerEventLogging/include/RobotContainer.h
=> Change WaitCommand to use units

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/cpp/TimedRobot.cpp, wpilibc/src/main/native/cpp/Watchdog.cpp, wpilibc/src/main/native/include/frc/IterativeRobotBase.h, wpilibc/src/main/native/include/frc/TimedRobot.h, wpilibc/src/main/native/include/frc/Watchdog.h, wpilibc/src/test/native/cpp/WatchdogTest.cpp
=> Make Watchdog use units::second_t instead of double

cscore/src/main/native/cpp/Log.h, ntcore/src/main/native/cpp/Dispatcher.cpp, ntcore/src/main/native/cpp/EntryNotifier.cpp, ntcore/src/main/native/cpp/Log.h, ntcore/src/main/native/cpp/NetworkConnection.cpp, ntcore/src/main/native/cpp/Storage.cpp, ntcore/src/main/native/cpp/Storage_save.cpp
=> Rename DEBUG macro to DEBUG0

wpilibc/src/main/native/cpp/geometry/Pose2d.cpp, wpilibc/src/main/native/cpp/geometry/Rotation2d.cpp, wpilibc/src/main/native/cpp/geometry/Transform2d.cpp, wpilibc/src/main/native/cpp/geometry/Translation2d.cpp, wpilibc/src/main/native/cpp/kinematics/MecanumDriveKinematics.cpp, wpilibc/src/main/native/include/frc/geometry/Pose2d.h, wpilibc/src/main/native/include/frc/geometry/Rotation2d.h, wpilibc/src/main/native/include/frc/geometry/Transform2d.h, wpilibc/src/main/native/include/frc/geometry/Translation2d.h, wpilibc/src/main/native/include/frc/geometry/Twist2d.h, wpilibc/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc, wpilibc/src/test/native/cpp/geometry/Pose2dTest.cpp, wpilibc/src/test/native/cpp/geometry/Rotation2dTest.cpp, wpilibc/src/test/native/cpp/geometry/Translation2dTest.cpp, wpilibc/src/test/native/cpp/geometry/Twist2dTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Pose2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Transform2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Translation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Twist2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/MecanumDriveKinematics.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveKinematics.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/geometry/Pose2dTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/geometry/Rotation2dTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/geometry/Translation2dTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/geometry/Twist2dTest.java
=> Add equality comparator to geometry classes

build.gradle
Fixes an issue where the symbol check task doesn't always run
=> Bump GradleJNI plugin version

wpilibc/src/main/native/cpp/controller/RamseteController.cpp, wpilibc/src/main/native/include/frc/controller/RamseteController.h, wpilibc/src/test/native/cpp/controller/RamseteControllerTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/RamseteController.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/RamseteControllerTest.java
If we add a trajectory generator, we could use a TrajectoryPoint struct for the desired pose rather than the separate Pose2d and linear/angular velocities.
=> Add Ramsete unicycle controller

wpilibc/src/main/native/cpp/RobotDrive.cpp, wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp, wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp, wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
=> Fix Drive usage reporting order

wpilibc/src/main/native/include/frc/commands/ConditionalCommand.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java
=> Document that ConditionalCommand requires all subsystems

azure-pipelines-testbench.yaml
The file just needs to be there before we can implement anything.
=> Add testbench yaml file

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
=> Fix main thread ID being potentially incorrect for simulation

azure-pipelines.yml
Windows builds are occasionally crossing 1 hour and failing
=> Remove timeouts from azure builds

cscore/src/main/java/edu/wpi/cscore/VideoListener.java, cscore/src/main/java/edu/wpi/cscore/VideoSink.java, cscore/src/main/java/edu/wpi/cscore/VideoSource.java, ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableInstance.java, ntcore/src/main/java/edu/wpi/first/networktables/RpcCall.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/I2C.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java
Replaced with the standard close()
=> Remove deprecated free() calls

docs/build.gradle
=> set extract_static for Doxygen config so that static members show up

wpilibcExamples/src/main/cpp/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
=> Set gradlebase correctly for all examples

wpilibc/src/main/native/cpp/frc2/command/Command.cpp, wpilibc/src/main/native/include/frc2/command/Command.h, wpilibc/src/main/native/include/frc2/command/NotifierCommand.h, wpilibc/src/main/native/include/frc2/command/RunCommand.h, wpilibc/src/main/native/include/frc2/command/StartEndCommand.h, wpilibc/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp, wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/RobotContainer.h, wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/commands/ComplexAuto.cpp, wpilibcExamples/src/main/cpp/examples/HatchbotInlined/include/RobotContainer.h, wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/Command.java, wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/NotifierCommand.java, wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/RunCommand.java, wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/StartEndCommand.java, wpilibj/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj2/command/CommandGroupErrorTest.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/commands/ComplexAutoCommand.java
Improves the names of a couple of the decorators.  Breaking, but better to break now, early in beta, than to regret this for the lifespan of the lib
=> improve decorator names

hal/src/main/native/athena/FRCDriverStation.cpp
With updates to netcomm, this is no longer required
=> Remove DS caching from the HAL level

wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveKinematics.java
Adding public access modifier to expose forward kinematics in `SwerveDriveKinematics.java`.
=> Exposing Forward Swerve Drive kinematics

myRobot/build.gradle
That way its a bit easier to test the Java builds
=> Add JNI dependencies to myRobotCpp library

wpilibc/src/main/native/cpp/controller/ProfiledPIDController.cpp, wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h, wpilibcExamples/src/main/cpp/examples/ElevatorProfiledPID/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/SwerveModule.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
Separate PR for the changes to ProfiledPIDController from https://github.com/wpilibsuite/allwpilib/pull/1962, for cleanliness
=> update profiledpidcontroller api

wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Pose2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Transform2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Translation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Twist2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/Trajectory.java
[Example output](https://paste.ee/p/xTRjz) of `Trajectory.toString()`
=> Add toString for geometry and trajectory classes

.gitignore, wpilibc/src/main/native/cpp/frc2/command/TrapezoidProfileCommand.cpp, wpilibc/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
updates trapezoidprofilecommand to use frc2::timer, fixing compilation error
=> Fix profilecommand timer

hal/src/main/native/cpp/jni/DigitalGlitchFilterJNI.cpp
=> Add extern C to DigitalGlitchFilterJNI

.wpilib/wpilib_preferences.json, build.gradle, buildSrc/build.gradle
Needed to fix both rio and raspbian installed, along with C++ 17 intellisense
=> Update intellisense to work with Beta 2020 code

hal/src/main/native/sim/Solenoid.cpp
=> Add HAL_SetAllSolenoids to sim

wpilibc/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineHelper.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/spline/CubicHermiteSplineTest.java
Reported by @GaganBhat
Will be adding unit tests in a separate commit later on that will catch this type of bug in the future.
=> Fix SplineHelper bug and add unit test to catch bug

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java
=> Fix bug in ramsetecommand where we were passing degrees

hal/src/main/java/edu/wpi/first/hal/PDPJNI.java, hal/src/main/native/athena/PDP.cpp, hal/src/main/native/cpp/jni/PDPJNI.cpp, hal/src/main/native/include/hal/PDP.h, hal/src/main/native/include/mockdata/PCMData.h, hal/src/main/native/include/mockdata/PDPData.h, hal/src/main/native/include/simulation/PCMSim.h, hal/src/main/native/include/simulation/PDPSim.h, hal/src/main/native/sim/PDP.cpp, hal/src/main/native/sim/mockdata/PCMData.cpp, hal/src/main/native/sim/mockdata/PDPData.cpp, myRobot/src/main/native/cpp/MyRobot.cpp
=> Add support for a multi PDP getter, and sim PCM/PDP multi arg funcs

wpilibc/src/main/native/cpp/geometry/Pose2d.cpp, wpilibc/src/main/native/cpp/geometry/Rotation2d.cpp, wpilibc/src/main/native/cpp/geometry/Translation2d.cpp, wpilibc/src/main/native/cpp/trajectory/Trajectory.cpp, wpilibc/src/main/native/cpp/trajectory/TrajectoryUtil.cpp, wpilibc/src/main/native/include/frc/geometry/Pose2d.h, wpilibc/src/main/native/include/frc/geometry/Rotation2d.h, wpilibc/src/main/native/include/frc/geometry/Translation2d.h, wpilibc/src/main/native/include/frc/trajectory/Trajectory.h, wpilibc/src/main/native/include/frc/trajectory/TrajectoryUtil.h, wpilibc/src/test/native/cpp/trajectory/TrajectoryJsonTest.cpp, wpilibj/CMakeLists.txt, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Pose2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Translation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/Trajectory.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryConfig.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryUtil.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGeneratorTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryJsonTest.java, wpiutil/CMakeLists.txt, wpiutil/build.gradle
Title. Unit tests are done and I hopefully have formatting right.
=> Add JSON support for Trajectories

simulation/halsim_gui/src/main/native/cpp/DIOGui.cpp, simulation/halsim_gui/src/main/native/cpp/PDPGui.cpp
- Use multi-channel PDP getter function
- Add duty cycle support
=> More simulation GUI improvements

wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/SwerveBot/include/SwerveModule.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
Closes #1936 
Can prevented in the future by #2024
=> Fix duplicate encoders in examples

wpilibc/src/main/native/cpp/DigitalOutput.cpp, wpilibc/src/main/native/include/frc/DigitalOutput.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DigitalOutput.java
It's perfectly safe to use as a DigitalSource, and can enable some cool tricks
=> Turn DigitalOutput into a DigitalSource

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDSubsystem.java, wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h
should be `setpoint`, not `goal` - these are different things
=> fix profiledpidsubsystem method argname

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java, wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp, wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h, wpilibc/src/main/native/cpp/controller/ArmFeedforward.cpp, wpilibc/src/main/native/include/frc/controller/ArmFeedforward.h, wpilibc/src/main/native/include/frc/controller/ElevatorFeedforward.h, wpilibc/src/main/native/include/frc/controller/SimpleMotorFeedforward.h, wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ArmFeedforward.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ElevatorFeedforward.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/SimpleMotorFeedforward.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java, wpiutil/src/main/native/include/wpi/MathExtras.h
Adds helper classes for computing feedforwards with parameters supplied by the characterization tool.
=> Add feedforward components

wpilibcExamples/src/main/cpp/examples/ArcadeDriveXboxController/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/TankDriveXboxController/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/arcadedrivexboxcontroller/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/arcadedrivexboxcontroller/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/tankdrivexboxcontroller/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/tankdrivexboxcontroller/Robot.java
Adding examples that use an Xbox Controller instead of a joystick for arcade and tank drive.
=> Add xbox controller examples for arcade and tank drive.

wpilibcExamples/src/main/cpp/templates/oldcommandbased/cpp/OI.cpp, wpilibcExamples/src/main/cpp/templates/oldcommandbased/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/templates/oldcommandbased/cpp/commands/ExampleCommand.cpp, wpilibcExamples/src/main/cpp/templates/oldcommandbased/cpp/commands/MyAutoCommand.cpp, wpilibcExamples/src/main/cpp/templates/oldcommandbased/cpp/subsystems/ExampleSubsystem.cpp, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/OI.h, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/Robot.h, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/RobotMap.h, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/commands/ExampleCommand.h, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/commands/MyAutoCommand.h, wpilibcExamples/src/main/cpp/templates/oldcommandbased/include/subsystems/ExampleSubsystem.h, wpilibcExamples/src/main/cpp/templates/templates.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/OI.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/RobotMap.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/commands/ExampleCommand.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/oldcommandbased/subsystems/ExampleSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json
=> Add template for old command-based style

wpilibc/src/main/native/include/frc/kinematics/MecanumDriveOdometry.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/MecanumDriveOdometry.java
Fix spelling mistakes in MecanumDriveOdometry.java and a minor spacing mistake in MecanumDriveOdometry.h.
=> Fix spelling mistakes in MecanumDriveOdometry.java

wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp, wpilibc/src/main/native/include/frc/smartdashboard/SmartDashboard.h
=> Add entry grabbing SmartDashboard function in C++

myRobot/build.gradle
Bug in lower level library causes having both be broken. So for now just removed release.
Issue created in low level library to fix
=> Remove release configs of deploy

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroup.java, wpilibNewCommands/src/main/native/cpp/frc2/command/ParallelDeadlineGroup.cpp, wpilibNewCommands/src/main/native/include/frc2/command/ParallelDeadlineGroup.h
Addresses https://github.com/wpilibsuite/allwpilib/issues/2093
=> Fix small logic error in ParallelDeadlineGroup

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java, wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp, wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h, wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/subsystems/DriveSubsystem.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java
This is less verbose and the same DifferentialDriveWheelSpeeds struct can be used for odometry as well (as used in the modified example).
=> Use DifferentialDriveWheelSpeeds in RamseteCommand ctor

wpilibc/src/main/native/cpp/AddressableLED.cpp, wpilibc/src/main/native/include/frc/AddressableLED.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLED.java
Closes #2107 
Depends on #2106
=> Add usage reporting for AddressableLED

cameraserver/.styleguide, wpilibNewCommands/.styleguide, wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/FunctionalCommand.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/WaitUntilCommand.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp, wpilibNewCommands/src/main/native/include/frc2/command/Command.h, wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h, wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/SelectCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h, wpilibNewCommands/src/main/native/include/frc2/command/WaitCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h, wpilibcExamples/.styleguide, wpilibcExamples/src/main/cpp/examples/HAL/c/Robot.c, wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
Also clean up other .styleguides.
Fixes #2111.
=> Fix incomplete .styleguide

wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/subsystems/ArmSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/include/Constants.h, wpilibcExamples/src/main/cpp/examples/ArmBot/include/Robot.h, wpilibcExamples/src/main/cpp/examples/ArmBot/include/RobotContainer.h, wpilibcExamples/src/main/cpp/examples/ArmBot/include/subsystems/ArmSubsystem.h, wpilibcExamples/src/main/cpp/examples/ArmBot/include/subsystems/DriveSubsystem.h, wpilibcExamples/src/main/cpp/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/Constants.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/subsystems/ArmSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/subsystems/DriveSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
Adds an example class that uses a profiledpidsubsystem to control an arm.
=> Profilepid example

hal/src/main/native/athena/Interrupts.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/DigitalOutput.java
Also fixes DigitalOutput not closing correctly, was why my testing didn't reproduce this issue originally
=> Fix double disable segfaulting interrupts

hal/src/main/native/sim/CAN.cpp
=> Make Sim receive message return message not found if no callbacks registered

hal/src/main/native/athena/PDP.cpp
=> Check status of PDP CAN reads

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java, wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h
=> Fix documentation in RamseteCommand

hal/src/main/java/edu/wpi/first/hal/sim/SimDeviceSim.java, hal/src/main/native/include/simulation/SimDeviceSim.h, hal/src/test/java/edu/wpi/first/hal/sim/SimDeviceSimTest.java, hal/src/test/native/cpp/sim/SimDeviceSimTest.cpp
This makes unit testing with SimDevice devices much easier.
=> Add user-friendly SimDeviceSim wrappers

buildSrc/build.gradle
Fixes a bug where source directories were being added to the header search path
=> Update native-utils to 2020.7.2

simulation/halsim_gui/src/main/native/cpp/AnalogInputGui.cpp
This helps make it clear they are separate controls.
=> Sim GUI: Add a bit of spacing to the analog inputs

hal/src/main/native/athena/AddressableLED.cpp, hal/src/main/native/include/hal/ChipObject.h, shared/config.gradle
=> Use ChipObject HMB function for LED

wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/Constants.java
in preparation for end-to-end trajectory tutorial.  Gains courtesy of @prateekma
=> update characterization values to match real robot used in example

wpilibc/src/main/native/cpp/PWMTalonFX.cpp, wpilibc/src/main/native/cpp/PWMVenom.cpp, wpilibc/src/main/native/include/frc/PWMTalonFX.h, wpilibc/src/main/native/include/frc/PWMVenom.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMTalonFX.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMVenom.java
Add CTRE TalonFX (PWMTalonFX)
Add Playing with Fusion Venom (PWMVenom)
Fixes #2037
=> Add 2020 speed controllers

wpilibc/src/main/native/cppcs/RobotBase.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
=> Use default path for networktables.ini in simulation

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SubsystemBase.java, wpilibNewCommands/src/main/native/cpp/frc2/command/SubsystemBase.cpp, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/Subsystem.java, wpilibOldCommands/src/main/native/cpp/commands/Subsystem.cpp
=> Fix subsystem LiveWindow usage

hal/src/main/native/sim/DriverStation.cpp
=> Add sim HAL_WaitForCachedControlData

wpilibc/src/main/native/cpp/controller/PIDController.cpp
=> Add missing definition for PIDController::SetPID()

wpilibc/src/main/native/include/frc/controller/ArmFeedforward.h, wpilibc/src/main/native/include/frc/controller/ElevatorFeedforward.h, wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h, wpilibc/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
=> Make C++ controller using declarations public

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java, wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/Scheduler.java, wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp, wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilderImpl.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java
=> Fix CommandScheduler Sendable interface

wpilibc/src/main/native/cpp/XboxController.cpp, wpilibc/src/main/native/include/frc/XboxController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java
=> Add Axis enum in XboxController

wpilibc/src/main/native/cpp/trajectory/TrajectoryGenerator.cpp, wpilibc/src/main/native/cppcs/RobotBase.cpp, wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
=> TrajectoryGenerator: Allow replacement of error reporting function (C++)

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Button.java
=> Make Button class concrete

wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrapezoidProfile.java
=> Fix aliasing of m_initial to result in TrapezoidProfile.calculate()

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Claw.cpp, wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/DriveTrain.cpp, wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Elevator.cpp, wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Wrist.cpp, wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Claw.h, wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/DriveTrain.h, wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Elevator.h, wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Wrist.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Claw.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/DriveTrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Elevator.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Wrist.java
Add logging for C++ wrist and Claw
=> Fix GearsBot log methods not being called periodically

wpilibc/src/main/native/include/frc/shuffleboard/BuiltInWidgets.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/BuiltInWidgets.java
Fix java links in C++ docs
Fix typos
=> Add new speed controllers to shuffleboard docs

wpilibc/src/main/native/cpp/Filesystem.cpp, wpilibc/src/main/native/include/frc/Filesystem.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Filesystem.java
=> Change sim Filesystem.getDeployDirectory() to src/main/deploy

wpilibNewCommands/src/main/native/include/frc2/command/button/POVButton.h, wpilibNewCommands/src/test/native/cpp/frc2/command/POVButtonTest.cpp
=> Fix C++ POVButton

wpilibcExamples/src/main/cpp/templates/timed/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/templates/timed/include/Robot.h, wpilibcExamples/src/main/cpp/templates/timedskeleton/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/templates/timedskeleton/include/Robot.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timed/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timedskeleton/Robot.java
=> Add missing methods to Timed and TimedSkeleton templates

wpilibc/src/main/native/cpp/controller/RamseteController.cpp, wpilibc/src/main/native/include/frc/controller/RamseteController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/RamseteController.java
This is to help with the troubleshooting tutorial [here](https://github.com/wpilibsuite/frc-docs/pull/484).
=> Add a method to diasble RamseteController

.styleguide, ThirdPartyNotices.txt, imgui/CMakeLists.txt, imgui/CMakeLists.txt.in, shared/config.gradle, simulation/halsim_gui/src/main/native/cpp/Field2D.cpp, simulation/halsim_gui/src/main/native/cpp/Field2D.h, simulation/halsim_gui/src/main/native/cpp/GuiUtil.cpp, simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp, simulation/halsim_gui/src/main/native/cpp/main.cpp, simulation/halsim_gui/src/main/native/include/GuiUtil.h, simulation/halsim_gui/src/main/native/include/HALSimGui.h, simulation/halsim_gui/src/main/native/include/portable-file-dialogs.h, wpilibc/src/main/native/cpp/simulation/Field2d.cpp, wpilibc/src/main/native/include/frc/simulation/Field2d.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/Field2d.java
The field image and robot image can be loaded or just a wireframe used.
The robot can be moved and rotated with a mouse click + drag.  The robot position is exposed to robot code via the Field2d class.
=> Simulation GUI: Add 2D field view

simulation/halsim_gui/src/main/native/cpp/Field2D.cpp
=> Sim GUI: Fix crash when field/robot image load is canceled

wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLEDBuffer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/AddressableLEDBufferTest.java
=> Add methods for getting color of an LED.

wpilibc/src/main/native/cpp/IterativeRobot.cpp, wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/cpp/TimedRobot.cpp, wpilibc/src/main/native/include/frc/IterativeRobotBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobot.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
=> Add SimulationInit and SimulationPeriodic functions

wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java
Unsure if synchronization is necessary here (why does timer need to be threadsafe?) but if it is, it should be done this way.
=> synchronize on lock object instead of using synchronized method keyword

wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Pose2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Translation2d.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryJsonTest.java
Jackson can do this with much less code overhead.
=> get rid of explicit serializers/deserializers for geometry classes

wpilibc/src/main/native/include/frc/GenericHID.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java
=> Improve Button API documentation in GenericHID

simulation/halsim_gui/src/main/native/cpp/IniSaverInfo.cpp, simulation/halsim_gui/src/main/native/cpp/SimDeviceGui.cpp, simulation/halsim_gui/src/main/native/include/IniSaverInfo.h
=> Sim GUI: Add user rename support to SimDevice list

wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java
Ultrasonic.setAuto() has static behavior anyway and is static in C++. Tweaked docs to be clear about this.
Fixes #2417
=> Changed Ultrasonic.setAuto() to be static

wpilibc/src/main/native/include/frc2/Timer.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java
=> Timer.start(): Match C++ behavior in Java

wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java
Also close dutyCycle before closing digitalInput.
=> DutyCycleEncoder: Set ownsDutyCycle for channel constructor

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/selectcommand/RobotContainer.java
=> Remove static import usage in SelectCommand example

wpilibc/src/main/native/include/frc/SlewRateLimiter.h
=> Make SlewRateLimiter unit declarations public

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp, wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
=> C++: Add Watchdog to CommandScheduler

wpiutil/src/main/native/include/wpi/Endian.h
- Make use of if constexpr when possible for byte_swap
- Remove unnecessary make_unsigned_t alias (added to STL in C++14)
=> [wpiutil] Endian.h: minor cleanup and improvements

gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:verification
=> [build] Check SHA-256 of downloaded Gradle distribution

wpilibj/src/main/java/edu/wpi/first/wpilibj/Tracer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java
resolves #2379 .
Needs C++ version.
=> [wpilibj] Refactor Tracer functionality out of Watchdog class

wpilibc/src/main/native/cpp/Tracer.cpp, wpilibc/src/main/native/cpp/Watchdog.cpp, wpilibc/src/main/native/include/frc/Tracer.h, wpilibc/src/main/native/include/frc/Watchdog.h
=> [wpilibc] Refactor Tracer functionality out of Watchdog class

wpilibc/src/main/native/cpp/Preferences.cpp, wpilibc/src/main/native/include/frc/Preferences.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
=> [wpilib] Add init methods to Preferences

hal/src/main/java/edu/wpi/first/hal/sim/EncoderSim.java, hal/src/main/java/edu/wpi/first/hal/sim/mockdata/EncoderDataJNI.java, hal/src/main/native/include/mockdata/EncoderData.h, hal/src/main/native/include/simulation/EncoderSim.h, hal/src/main/native/sim/jni/EncoderDataJNI.cpp, hal/src/main/native/sim/mockdata/EncoderData.cpp
=> [sim] Add HALSIM accessors for encoder rate and distance

wpilibc/src/main/native/cpp/SpeedControllerGroup.cpp, wpilibc/src/main/native/include/frc/SpeedControllerGroup.h, wpilibc/src/main/native/include/frc/SpeedControllerGroup.inc, wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedControllerGroup.java
This allows the list to be constructed dynamically.
=> [wpilib] SpeedControllerGroup: Add vector-taking constructor

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/NetworkButton.java, wpilibNewCommands/src/main/native/cpp/frc2/command/button/NetworkButton.cpp, wpilibNewCommands/src/main/native/include/frc2/command/button/NetworkButton.h, wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandTestBase.java, wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/NetworkButtonTest.java, wpilibNewCommands/src/test/native/cpp/frc2/command/button/NetworkButtonTest.cpp
=> [command] Add NetworkButton

wpilibc/src/main/native/cpp/AddressableLED.cpp, wpilibc/src/main/native/include/frc/util/Color.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLEDBuffer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
=> [wpilib] Add Color.fromHSV() static helper

simulation/halsim_gui/CMakeLists.txt, simulation/halsim_gui/build.gradle, simulation/halsim_gui/src/main/native/cpp/NetworkTablesGui.cpp, simulation/halsim_gui/src/main/native/cpp/NetworkTablesGui.h, simulation/halsim_gui/src/main/native/cpp/main.cpp
This enables seeing the tables locally, including update timestamps and
external connections.  Array keys are shown, but not their data.
=> [sim] Add NetworkTables view to Simulation GUI

wpilibc/src/main/native/cpp/trajectory/constraint/EllipticalRegionConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/RectangularRegionConstraint.cpp, wpilibc/src/main/native/include/frc/trajectory/constraint/EllipticalRegionConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/MaxVelocityConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/RectangularRegionConstraint.h, wpilibc/src/test/native/cpp/trajectory/EllipticalRegionConstraintTest.cpp, wpilibc/src/test/native/cpp/trajectory/RectangularRegionConstraintTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/EllipticalRegionConstraint.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/MaxVelocityConstraint.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/RectangularRegionConstraint.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/EllipticalRegionConstraintTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/RectangularRegionConstraintTest.java
=> [wpilib] Trajectory: Add MaxVelocity and Region constraints

wpilibc/src/main/native/cpp/kinematics/MecanumDriveKinematics.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/CentripetalAccelerationConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveKinematicsConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/EllipticalRegionConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/MecanumDriveKinematicsConstraint.cpp, wpilibc/src/main/native/cpp/trajectory/constraint/RectangularRegionConstraint.cpp, wpilibc/src/main/native/include/frc/controller/SimpleMotorFeedforward.h, wpilibc/src/main/native/include/frc/kinematics/MecanumDriveKinematics.h, wpilibc/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h, wpilibc/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc, wpilibc/src/main/native/include/frc/trajectory/constraint/CentripetalAccelerationConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveKinematicsConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveVoltageConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/EllipticalRegionConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/MaxVelocityConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/MecanumDriveKinematicsConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/RectangularRegionConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.h, wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.inc, wpilibc/src/main/native/include/frc/trajectory/constraint/TrajectoryConstraint.h
I will add a commit to fix the const-qualification in the new MaxVelocity and Region constraints once #2466 is merged.
=> [wpilibc] Fix const-qualification in kinematics and constraints

wpilibj/src/main/java/edu/wpi/first/wpilibj/SensorUtil.java
=> [wpilibj] SensorUtil: change exception type

shared/javacpp/setupBuild.gradle, shared/jni/setupBuild.gradle, wpilibj/build.gradle
This reverts commit c82b8546bc01cdf36f425e3bbbfc8bdd7eff05a9.
Azure was fixed, so we can revert this.
=> [build] Revert workaround for azure windows library loading issue (#2481)

hal/src/main/native/sim/HAL.cpp
Vendors have asked for this for testing purposes
=> [sim] Map HAL_GetSystemActive to HALSIM_GetDriverStationEnabled

.styleguide, cscore/.styleguide, cscore/src/main/native/include/cscore_oo.inl, ntcore/.styleguide, ntcore/src/main/native/include/networktables/NetworkTableEntry.inl, ntcore/src/main/native/include/networktables/NetworkTableInstance.inl, ntcore/src/main/native/include/networktables/RpcCall.inl, wpiutil/.styleguide, wpiutil/src/main/native/include/wpi/HttpUtil.inl
=> [build] Add .inl files to styleguide (NFC)

simulation/halsim_ds_socket/src/main/native/include/DSCommJoystickPacket.h
Its against the standard to be unnamed if the data and functions are non trivial.
=> [sim] Name DSCommJoystickPacket structure

hal/src/main/java/edu/wpi/first/hal/sim/mockdata/SimDeviceDataJNI.java
=> [sim] Make SimDeviceInfo/SimValueInfo data members public

cscore/src/main/native/linux/UsbCameraImpl.cpp
Previously this would list ALL /dev/video* devices.  In recent versions of
Linux this leads to listing duplicate devices, as many USB cameras provide
both a video device and a metadata device, and only the video device can
actually be used for streaming.
=> [cscore] EnumerateUsbCameras(): Only list capture devices

wpilibcExamples/src/main/cpp/examples/ArmBotOffboard/include/ExampleSmartMotorController.h, wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/ExampleSmartMotorController.h, wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/subsystems/DriveSubsystem.h, wpilibcExamples/src/main/cpp/examples/ElevatorTrapezoidProfile/include/ExampleSmartMotorController.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbotoffboard/ExampleSmartMotorController.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/ExampleSmartMotorController.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/subsystems/DriveSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatortrapezoidprofile/ExampleSmartMotorController.java, wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/ITestFixture.java
Replace Master/Slave with Main/Follower in examples
=> [wpilib] Use inclusive language where practical

imgui/CMakeLists.txt, imgui/CMakeLists.txt.in, shared/config.gradle, simulation/halsim_gui/build.gradle
Updates the following dependencies:
- glfw to latest 3.3-stable
- imgui to 1.76
- stb to latest master
Removes libvulkan dependency.
Also adds implot.
=> [sim] Update thirdparty-imgui

cscore/src/test/java/edu/wpi/cscore/UsbCameraTest.java
Introduced by camera filtering in #2532.
=> [cscore] Fix USB camera test failure

hal/src/main/native/sim/HAL.cpp
=> [sim] Set Windows timer precision to 1ms

wpilibc/src/main/native/include/frc/interfaces/Gyro.h, wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/cpp/Drivetrain.cpp, wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Drivetrain.cpp, wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/Constants.h, wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/subsystems/DriveSubsystem.h, wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h, wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/subsystems/DriveSubsystem.h, wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Drivetrain.cpp, wpilibcExamples/src/main/cpp/examples/SwerveBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/Constants.h, wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/subsystems/DriveSubsystem.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/Constants.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/subsystems/DriveSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/Constants.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java
Also clean up some of the Gyro interface comments.
=> [wpilib] Add Gyro::GetRotation2d()

wpiutil/src/main/native/include/wpi/static_circular_buffer.h, wpiutil/src/test/native/cpp/StaticCircularBufferTest.cpp
This complements wpi::circular_buffer which supports dynamic resizing.
=> [wpiutil] Add circular buffer class with static size

wpilibcExamples/src/main/cpp/examples/RamseteController/cpp/Drivetrain.cpp, wpilibcExamples/src/main/cpp/examples/RamseteController/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/RamseteController/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Robot.java
This is different from the RamseteCommand examples in that they don't use the command-based library.
=> [wpilib] Add RamseteController examples

hal/src/main/java/edu/wpi/first/hal/simulation/SimulatorJNI.java, hal/src/main/native/sim/jni/SimulatorJNI.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimHooks.java
Also move SimHooks to wpilibj (to match wpilibc).
=> [sim] Add Java wrapper for getProgramStarted

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java, cscore/src/main/java/edu/wpi/cscore/UsbCamera.java, cscore/src/main/native/cpp/UsbCameraImplCommon.cpp, cscore/src/main/native/cpp/jni/CameraServerJNI.cpp, cscore/src/main/native/include/cscore_c.h, cscore/src/main/native/include/cscore_cpp.h, cscore/src/main/native/include/cscore_oo.h, cscore/src/main/native/include/cscore_oo.inl, cscore/src/main/native/linux/UsbCameraImpl.cpp, cscore/src/main/native/linux/UsbCameraImpl.h, cscore/src/main/native/osx/UsbCameraImpl.cpp, cscore/src/main/native/windows/UsbCameraImpl.cpp, cscore/src/main/native/windows/UsbCameraImpl.h
Windows support not yet implemented.
=> [cscore] Add support for changing the USB camera path

wpiutil/src/main/native/include/wpi/HttpWebSocketServerConnection.h, wpiutil/src/main/native/include/wpi/HttpWebSocketServerConnection.inl, wpiutil/src/test/native/cpp/HttpWebSocketServerConnectionTest.cpp
This is a derived class of HttpServerConnection that implements the
WebSocket upgrade pieces.  This combination is pretty common so is
worth refactoring here.
=> [wpiutil] Add HttpWebSocketServerConnection

wpilibc/src/main/native/cpp/spline/SplineHelper.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineHelper.java
=> [wpilib] Fix SplineHelper cubic spline bug

wpiutil/src/main/native/include/wpi/HttpServerConnection.h
This allows easier customization of responses.
=> [wpiutil] HttpServerConnection: Make more functions virtual

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java, wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Subsystem.java, wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp, wpilibNewCommands/src/main/native/cpp/frc2/command/Subsystem.cpp, wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h
This adds a simulationPeriodic method to Subsystems (in the new command based). This method is run periodically during simulation.
=> [command] Add simulationPeriodic method to Subsystem

wpilibc/src/main/native/cpp/AnalogPotentiometer.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogPotentiometer.java
=> [wpilib] AnalogPotentiometer: Use average voltage

.clang-format
Fixes windows with git autocrlf
=> [build] Revert change to DeriveLineEnding made in #1961

cscore/src/main/native/windows/UsbCameraImpl.cpp, cscore/src/main/native/windows/UsbCameraImpl.h
=> [cscore] Provide USB Camera VID and PID in Windows

wpilibc/src/main/native/cpp/simulation/SimHooks.cpp, wpilibc/src/main/native/include/frc/simulation/SimHooks.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimHooks.java
This is consistent with other WPILib timer functions.
=> [sim] Change stepTiming to take seconds

hal/src/main/native/sim/Notifier.cpp
WaitForNotifierAlarm was waiting on the CV without first checking to see if
the exit condition was met.
=> [sim] Fix HAL notifier race condition

wpiutil/src/main/native/cpp/MimeTypes.cpp, wpiutil/src/main/native/include/wpi/MimeTypes.h
In reference to #2589, this PR moves the MIME type utility into wpiutil
=> [wpiutil] Add MIME type utility

hal/src/main/java/edu/wpi/first/hal/util/AllocationException.java, hal/src/main/java/edu/wpi/first/hal/util/BoundaryException.java, hal/src/main/java/edu/wpi/first/hal/util/CheckedAllocationException.java, hal/src/main/java/edu/wpi/first/hal/util/HalHandleException.java, hal/src/main/java/edu/wpi/first/hal/util/UncleanStatusException.java, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/IllegalUseOfCommandException.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogTrigger.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogTriggerOutput.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Relay.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineParameterizer.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryParameterizer.java
These are all classes (e.g. Exception classes) which will never be serialized.
=> [wpilibj] Suppress serialVersionUID warnings

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java, wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommand.java, wpilibNewCommands/src/main/native/cpp/frc2/command/MecanumControllerCommand.cpp, wpilibNewCommands/src/main/native/include/frc2/command/MecanumControllerCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.h, wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc, wpilibc/src/main/native/cpp/controller/HolonomicDriveController.cpp, wpilibc/src/main/native/include/frc/controller/HolonomicDriveController.h, wpilibc/src/test/native/cpp/controller/HolonomicDriveControllerTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/HolonomicDriveController.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/HolonomicDriveControllerTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/RamseteControllerTest.java, wpiutil/src/main/java/edu/wpi/first/wpiutil/math/MathUtil.java, wpiutil/src/main/native/include/units/math.h, wpiutil/src/test/java/edu/wpi/first/wpiutil/math/MathUtilTest.java, wpiutil/src/test/native/cpp/UnitsTest.cpp
=> Add holonomic drive controller; make swerve and mecanum commands use new controller

wpilibc/src/main/native/include/frc/SlewRateLimiter.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/SlewRateLimiter.java
=> [wpilib] Fix timestamp slew in SlewRateLimiter

hal/src/main/native/include/hal/simulation/DriverStationData.h, hal/src/main/native/sim/mockdata/DriverStationData.cpp, hal/src/main/native/sim/mockdata/DriverStationDataInternal.h
=> [sim] Add callbacks for joysticks and match info

wpilibc/src/main/native/cpp/DoubleSolenoid.cpp, wpilibc/src/main/native/cpp/Solenoid.cpp, wpilibc/src/main/native/include/frc/DoubleSolenoid.h, wpilibc/src/main/native/include/frc/Solenoid.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DoubleSolenoid.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Solenoid.java
Toggling a solenoid on a button press is a common idiom, so this commit
provides a more readable way of accomplishing that.
=> Add Toggle() function to solenoid classes

hal/src/main/native/athena/mockdata/DriverStationData.cpp, hal/src/main/native/include/hal/simulation/DriverStationData.h, hal/src/main/native/sim/DriverStation.cpp, hal/src/main/native/sim/mockdata/DriverStationData.cpp, hal/src/main/native/sim/mockdata/DriverStationDataInternal.h
Also add stubs for sim joysticks and match info on Rio.
=> [sim] Add callback for NotifyNewData

.github/workflows/ci.yml
We can use this until https://github.com/actions/setup-java/pull/57 is merged.
Diff is here: https://github.com/actions/setup-java/compare/main...AustinShalit:bugfix/architecture
=> [build] Apply temporary JDK arch fix

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
The refactor that occurred in #808 never happened to #856, thus these methods never actually held the data mutex.
=> [wpilibj] Fix joystick button edge synchronisation

wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/RobotContainer.cpp, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/RobotContainer.java
=> [wpilib] Enable continuous input on theta controller in swerve examples

wpilibc/src/main/native/include/frc/InterruptableSensorBase.h
=> Fix InterruptableSensorBase comment

.github/workflows/ci.yml
This reverts commit e680ba85fa9f200bd9fbb541587fc259feca355d.
The PR I submitted was merged and a new version was released.
=> Revert "[build] Apply temporary JDK arch fix (#2643)"

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardInstance.cpp, wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardInstance.h
=> [wpilibc] Use LLVM containers in ShuffleboardInstance

simulation/halsim_gui/src/main/native/cpp/EncoderGui.cpp, simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp, simulation/halsim_gui/src/main/native/cpp/Mechanism2D.cpp, simulation/halsim_gui/src/main/native/cpp/NetworkTablesGui.cpp
Also tweak initial sizes, positions, and visibility.
=> [sim] Fix GUI scaling of window sizes

hal/src/main/native/athena/PDP.cpp
=> [hal] Fix PDP Energy Calculation

hal/src/main/native/athena/HAL.cpp, hal/src/main/native/athena/HALInitializer.h, hal/src/main/native/athena/Interrupts.cpp
=> [hal] Fix InitialzeInterrupts naming

.gitignore, hal/src/main/native/sim/Extensions.cpp, myRobot/build.gradle, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
There is now a list of extensions to load
=> [build] Make loading sim extensions from MyRobot easier

hal/src/main/java/edu/wpi/first/hal/HAL.java, hal/src/main/native/athena/HAL.cpp, hal/src/main/native/cpp/jni/HAL.cpp, hal/src/main/native/include/hal/Extensions.h, hal/src/main/native/include/hal/HALBase.h, hal/src/main/native/sim/Extensions.cpp, hal/src/main/native/sim/HAL.cpp, simulation/halsim_ws_client/src/main/native/cpp/HALSimWS.cpp, simulation/halsim_ws_client/src/main/native/cpp/HALSimWSClient.cpp, simulation/halsim_ws_client/src/main/native/cpp/HALSimWSClientConnection.cpp, simulation/halsim_ws_client/src/main/native/cpp/main.cpp, simulation/halsim_ws_client/src/main/native/include/HALSimWS.h, simulation/halsim_ws_client/src/main/native/include/HALSimWSClient.h, simulation/halsim_ws_client/src/main/native/include/HALSimWSClientConnection.h, simulation/halsim_ws_core/src/main/native/cpp/WSProvider_SimDevice.cpp, simulation/halsim_ws_core/src/main/native/include/WSProvider_SimDevice.h, simulation/halsim_ws_server/src/main/native/cpp/HALSimHttpConnection.cpp, simulation/halsim_ws_server/src/main/native/cpp/HALSimWSServer.cpp, simulation/halsim_ws_server/src/main/native/cpp/HALSimWeb.cpp, simulation/halsim_ws_server/src/main/native/cpp/main.cpp, simulation/halsim_ws_server/src/main/native/include/HALSimHttpConnection.h, simulation/halsim_ws_server/src/main/native/include/HALSimWSServer.h, simulation/halsim_ws_server/src/main/native/include/HALSimWeb.h, simulation/halsim_ws_server/src/test/native/cpp/WebServerClientTest.cpp, simulation/halsim_ws_server/src/test/native/cpp/main.cpp, simulation/halsim_ws_server/src/test/native/include/WebServerClientTest.h, wpilibc/src/main/native/include/frc/RobotBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java, wpiutil/src/main/native/include/wpi/uv/Buffer.h
Also clean up some other implementation aspects for cleaner shutdown.
=> [sim] WebSockets: don't override HAL_Main

hal/src/main/native/sim/mockdata/EncoderData.cpp
=> [sim] Set Encoder reset to false when count set

wpilibc/src/main/native/include/frc/RobotBase.h
=> [wpilibc] RobotBase::IsReal, IsSimulation: Add doxygen comments

wpilibc/src/main/native/cpp/ScopedTracer.cpp, wpilibc/src/main/native/include/frc/ScopedTracer.h, wpilibc/src/test/native/cpp/ScopedTracerTest.cpp
This makes it easier for C++ teams to log a certain piece of code using RAII.
=> [wpilibc] Add ScopedTracer class

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp, wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h, wpilibc/src/test/native/cpp/simulation/DifferentialDriveSimTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSimTest.java
Co-authored-by: Tyler Veness <calcmogul@gmail.com>
=> [wpilib] Clean up DifferentialDrivetrainSim API

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp, wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
All the other simulation objects already have functions like this
through LinearSystemSim.
=> [wpilib] Add set functions to differential drive simulation

wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/ArmBot/include/RobotContainer.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/RobotContainer.java
=> [wpilib] Enable ArmSubsystem in ArmBot example

wpilibcExamples/src/main/cpp/examples/StateSpaceArm/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/StateSpaceElevator/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp, wpimath/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h, wpimath/src/main/native/include/frc/system/LinearSystemLoop.h, wpimath/src/test/native/cpp/StateSpaceTest.cpp
=> [wpilibc] Add LinearSystemLoop C++ ctor to match Java

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/ExtendedKalmanFilter.java, wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/UnscentedKalmanFilter.java, wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h, wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
By storing the previous dt, it can be moved into Correct() where it is
actually used. This lets us take the continuous R as an argument in the
user-provided R overload.
=> [wpimath] Move DiscretizeR() in EKF and UKF from Predict() to Correct()

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp, wpilibc/src/main/native/cpp/simulation/FlywheelSim.cpp, wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp, wpilibc/src/main/native/include/frc/simulation/ElevatorSim.h, wpilibc/src/main/native/include/frc/simulation/FlywheelSim.h, wpilibc/src/main/native/include/frc/simulation/LinearSystemSim.h, wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h, wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp, wpilibc/src/test/native/cpp/simulation/SingleJointedArmSimTest.cpp, wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/FlywheelSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/LinearSystemSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ElevatorSimTest.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSimTest.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armsimulation/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/Robot.java
=> [wpilib] Clean up physics simulation class APIs

wpimath/src/main/java/edu/wpi/first/wpilibj/geometry/Translation2d.java, wpimath/src/main/native/cpp/geometry/Translation2d.cpp, wpimath/src/main/native/include/frc/geometry/Translation2d.h, wpimath/src/test/java/edu/wpi/first/wpilibj/geometry/Translation2dTest.java, wpimath/src/test/native/cpp/geometry/Translation2dTest.cpp
=> [wpimath] Add distance/angle constructor to Translation2d

wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp, wpilibc/src/main/native/cpp/simulation/ADXRS450_GyroSim.cpp, wpilibc/src/main/native/include/frc/ADXRS450_Gyro.h, wpilibc/src/main/native/include/frc/simulation/ADXRS450_GyroSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADXRS450_GyroSim.java
=> [wpilib] Add ADXRS450_GyroSim

hal/src/main/native/sim/MockHooks.cpp
Currently, StepTiming() advances the time by the given delta, then runs
any Notifiers that expired within that timeframe until their expiration
times are in the future. This doesn't reflect how the Notifiers would
actually run on a real robot. For example, if a Notifier measures the
time between calls for state-space model advancement, it would measure
a large jump in time once, then zero for subsequent runs until the
Notifier was caught up to the current time.
With this change, the time is incremented by the full delta or until the
soonest Notifier, whichever has the smaller delta, then Notifiers set to
expire at that time are run. This is repeated until the time has been
advanced by the full delta. For the state-space model Notifier situation
mentioned before, it would measure multiple …
=> [sim] StepTiming(): incrementally step Notifiers in sequence

.github/workflows/ci.yml, CMakeLists.txt, README-CMAKE.md, cameraserver/CMakeLists.txt, cscore/CMakeLists.txt, hal/CMakeLists.txt, ntcore/CMakeLists.txt, ntcore/src/test/native/cpp/ValueTest.cpp, wpigui/CMakeLists.txt, wpilibc/CMakeLists.txt, wpilibj/CMakeLists.txt, wpimath/CMakeLists.txt, wpiutil/CMakeLists.txt
Closes #2785 
@PeterJohnson Let me know what you think of the defaults.
=> [build] Refactor CMake flags

buildSrc/build.gradle
Updates compiler folder for gradle install, and fixes sourcelink task bug
=> [build] Update NativeUtils to latest version

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp, wpilibc/src/main/native/cpp/simulation/DutyCycleEncoderSim.cpp, wpilibc/src/main/native/include/frc/DutyCycleEncoder.h, wpilibc/src/main/native/include/frc/simulation/DutyCycleEncoderSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DutyCycleEncoderSim.java
=> [wpilib] Add DutyCycleEncoderSim

CONTRIBUTING.md
Add link to code of conduct
Update clang version used to 10 to match CI
Update pull request format to match current practice
Change references to Azure
=> Update Readme to match current practice (NFC)

simulation/frc_gazebo_plugins/build.gradle, simulation/gz_msgs/build.gradle, simulation/halsim_gazebo/build.gradle
=> [build] Disable Gazebo builds when -PmakeSim is not set

wpilibc/src/test/native/cpp/simulation/StateSpaceSimTest.cpp, wpilibcExamples/src/main/cpp/examples/DifferentialDriveSimulation/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp, wpimath/src/main/java/edu/wpi/first/wpilibj/system/plant/LinearSystemId.java, wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h, wpimath/src/test/native/cpp/system/LinearSystemIDTest.cpp
=> [wpimath] Make LinearSystemId Kv and Ka use units

wpilibc/src/main/native/cpp/simulation/RoboRioSim.cpp, wpilibc/src/main/native/include/frc/simulation/RoboRioSim.h, wpilibc/src/test/native/cpp/simulation/StateSpaceSimTest.cpp, wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp
=> [sim] Use units for voltage and current in RoboRioSim

hal/src/main/native/sim/DriverStation.cpp
=> [hal] Make HAL_SendError use FPGA time

wpilibc/src/main/native/cpp/DriverStation.cpp, wpilibc/src/main/native/cpp/GenericHID.cpp, wpilibc/src/main/native/include/frc/DriverStation.h, wpilibc/src/main/native/include/frc/GenericHID.h, wpilibc/src/test/native/cpp/DriverStationTest.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/DriverStationTest.java
=> [wpilib] Add IsJoystickConnected method

wpigui/src/main/native/cpp/wpigui.cpp
This fixes scaling and black window artifacts on Mac.
=> [wpigui] Render during resize events

shared/config.gradle, shared/opencv.gradle
This avoids a false dependency on libgthread on Mac.
=> [build] Update OpenCV to remove WITH_GTK

wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp, wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/RobotContainer.cpp, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/RobotContainer.java
=> [wpilib] Reset odometry in path following examples

wpilibc/src/main/native/cpp/DriverStation.cpp
See issue https://github.com/wpilibsuite/allwpilib/issues/2764
=> Cache NT writes from driver station, reducing malloc traffic

wpimath/src/main/native/include/frc/system/plant/DCMotor.h
=> Fix param stallTorque copy-paste mistake

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java, wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp
=> [command] Fix timing issue in RamseteCommand

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
Resolves #2764 
Java version of #2768
=> [wpilibj] Cache DS data

hal/src/main/java/edu/wpi/first/hal/HAL.java, hal/src/main/java/edu/wpi/first/hal/simulation/SimulatorJNI.java, hal/src/main/native/athena/HAL.cpp, hal/src/main/native/athena/mockdata/MockHooks.cpp, hal/src/main/native/cpp/jni/HAL.cpp, hal/src/main/native/include/hal/HALBase.h, hal/src/main/native/include/hal/simulation/MockHooks.h, hal/src/main/native/sim/HAL.cpp, wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
This allows vendor libs to hook into the begin or end of simulationPeriodic().
=> [sim] Add HAL hooks for simulationPeriodic

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/parallelcommandgroup/ReplaceMeParallelCommandGroup.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/paralleldeadlinegroup/ReplaceMeParallelDeadlineGroup.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/parallelracegroup/ReplaceMeParallelRaceGroup.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/sequentialcommandgroup/ReplaceMeSequentialCommandGroup.java
This makes the Java templates consistent with the C++ templates as well as the documentation
=> [command] Use addCommands in command group templates

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp, wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h, wpilibc/src/main/native/include/frc/simulation/LinearSystemSim.h, wpilibc/src/test/native/cpp/simulation/DifferentialDriveSimTest.cpp, wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/subsystems/DriveSubsystem.cpp, wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/subsystems/DriveSubsystem.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/LinearSystemSim.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSimTest.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java
Addresses https://github.com/wpilibsuite/allwpilib/issues/2902
=> Add noise to Differential Drive simulator

glass/publish.gradle, glass/src/app/native/cpp/main.cpp, wpigui/src/main/native/cpp/wpigui.cpp, wpigui/src/main/native/include/wpigui.h, wpigui/src/main/native/include/wpigui_internal.h
~~Still needs to be tested on Linux and Windows~~ Now tested. Preferences file works through app bundle on Mac.
=> Add platform-specific wpigui saving, macOS app for Glass

glass/CMakeLists.txt, glass/Info.plist, glass/build.gradle, glass/publish.gradle
Was glassApp, which makes building an extraction setup much harder. Also matches cmake.
=> Change basename of glass to glass

buildSrc/build.gradle, glass/publish.gradle
This fixes the Glass publishing classifier
=> [build] Update native-utils to 2021.0.6

wpilibjExamples/build.gradle, wpilibjExamples/src/dev/native/cpp/main.cpp
Example: `./gradlew :wpilibjExamples:runstatespacedifferentialdrivesimulation`
=> [examples] Add tasks to run Java examples

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/FlywheelSim.java
Fixes argument mismatch in FlywheelSim
=> Fix FlywheelSim argument mixup in constructor

wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Drivetrain.cpp, wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Robot.cpp, wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/subsystems/DriveSubsystem.cpp, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java
This ensures that the robot position will be updated in dashboards like Glass when running on real hardware.
Closes #2926
=> [examples] Update Field2d position in periodic()

simulation/halsim_ws_client/src/main/native/cpp/HALSimWS.cpp, simulation/halsim_ws_server/src/main/native/cpp/HALSimWeb.cpp, simulation/halsim_ws_server/src/test/native/cpp/WebServerClientTest.cpp
=> [sim] Change default WS port number to 3300

ntcore/src/main/native/cpp/Dispatcher.cpp, ntcore/src/main/native/cpp/Dispatcher.h, wpilibc/src/main/native/cpp/IterativeRobotBase.cpp, wpilibc/src/main/native/include/frc/IterativeRobotBase.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
This functionality can be enabled by the user program by calling setNetworkTablesFlushEnabled.
=> [wpilib] Add option to flush NetworkTables every iterative loop

glass/src/lib/native/cpp/hardware/Gyro.cpp, glass/src/lib/native/cpp/hardware/SpeedController.cpp, glass/src/lib/native/cpp/other/CommandScheduler.cpp, glass/src/lib/native/cpp/other/CommandSelector.cpp, glass/src/lib/native/cpp/other/PIDController.cpp, glass/src/lib/native/cpp/other/Subsystem.cpp, glass/src/lib/native/include/glass/hardware/Gyro.h, glass/src/lib/native/include/glass/hardware/SpeedController.h, glass/src/lib/native/include/glass/other/CommandScheduler.h, glass/src/lib/native/include/glass/other/CommandSelector.h, glass/src/lib/native/include/glass/other/PIDController.h, glass/src/lib/native/include/glass/other/Subsystem.h, glass/src/libnt/native/cpp/NTCommandScheduler.cpp, glass/src/libnt/native/cpp/NTCommandSelector.cpp, glass/src/libnt/native/cpp/NTGyro.cpp, glass/src/libnt/native/cpp/NTPIDController.cpp, glass/src/libnt/native/cpp/NTSpeedController.cpp, glass/src/libnt/native/cpp/NTSubsystem.cpp, glass/src/libnt/native/cpp/StandardNetworkTables.cpp, glass/src/libnt/native/include/glass/networktables/NTCommandScheduler.h, glass/src/libnt/native/include/glass/networktables/NTCommandSelector.h, glass/src/libnt/native/include/glass/networktables/NTGyro.h, glass/src/libnt/native/include/glass/networktables/NTPIDController.h, glass/src/libnt/native/include/glass/networktables/NTSpeedController.h, glass/src/libnt/native/include/glass/networktables/NTSubsystem.h
=> [glass] Add more widgets

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
Looks for the joystick name starting with "Xbox" or containing "pad".
=> [sim] Try to guess "Map Gamepad" setting

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp, wpilibc/src/main/native/cpp/simulation/ADXRS450_GyroSim.cpp, wpilibc/src/main/native/cpp/simulation/DutyCycleEncoderSim.cpp, wpilibc/src/main/native/include/frc/DutyCycleEncoder.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADXRS450_GyroSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DutyCycleEncoderSim.java
These were broken by #2952.
Also fix Java ADXRS450_Gyro angle/rate SimValue names.
=> [sim] Fix ADXRS450_GyroSim and DutyCycleEncoderSim

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/UnscentedKalmanFilter.java, wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
This adds an overload of UnscentedKalmanFilter::Correct() that takes a
custom measurement covariance but uses default mean and residual
calculation functions.
Closes #2965.
=> Add UnscentedKalmanFilter::Correct() overload

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/DifferentialDrivePoseEstimator.java, wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/MecanumDrivePoseEstimator.java, wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/SwerveDrivePoseEstimator.java, wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp, wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp, wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h, wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h, wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
Exposes the R passed to vision correct to users.
=> Add support for varying vision standard deviations in pose estimators

OtherVersions.md
This also updates occurrences of 2020 to 2021.
=> Update OtherVersions.md to include wpimath info

glass/src/lib/native/cpp/other/Drive.cpp, glass/src/lib/native/include/glass/other/Drive.h, glass/src/libnt/native/cpp/NTDifferentialDrive.cpp, glass/src/libnt/native/cpp/NTMecanumDrive.cpp, glass/src/libnt/native/cpp/StandardNetworkTables.cpp, glass/src/libnt/native/include/glass/networktables/NTDifferentialDrive.h, glass/src/libnt/native/include/glass/networktables/NTMecanumDrive.h
This adds widgets for DifferentialDrive and MecanumDrive
=> [glass] Add drive class widgets

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
- Slicing of GlfwKeyboardJoystick
- Potential null pointer deref
=> [sim] DriverStationGui: Fix two bugs

.github/workflows/ci.yml
=> [build] Add Gazebo build to Actions CI

cameraserver/src/main/native/include/cameraserver/CameraServer.inc, cameraserver/src/main/native/include/vision/VisionRunner.inc, cscore/src/main/native/include/cscore_oo.inl, glass/src/lib/native/include/glass/Provider.inc, glass/src/lib/native/include/glass/support/IniSaver.inl, glass/src/lib/native/include/glass/support/IniSaverString.inl, glass/src/lib/native/include/glass/support/IniSaverVector.inl, ntcore/src/main/native/include/networktables/NetworkTableEntry.inl, ntcore/src/main/native/include/networktables/NetworkTableInstance.inl, ntcore/src/main/native/include/networktables/RpcCall.inl, simulation/halsim_ws_core/src/main/native/include/WSHalProviders.h, simulation/halsim_ws_core/src/main/native/include/WSHalProviders.inl, wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc, wpilibc/src/main/native/include/frc/SpeedControllerGroup.inc, wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardComponent.inc, wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.inc, wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc, wpimath/src/main/native/include/frc/kinematics/SwerveDriveOdometry.inc, wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.inc, wpimath/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.inc, wpiutil/src/main/native/include/wpi/HttpUtil.inl, wpiutil/src/main/native/include/wpi/HttpWebSocketServerConnection.inl, wpiutil/src/main/native/include/wpi/circular_buffer.inc
This helps both IDEs and linting tools.
=> Include .h from .inc/inl files (NFC)

wpilibc/src/main/native/cpp/PWMSpeedController.cpp, wpilibc/src/main/native/include/frc/PWMSpeedController.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMSpeedController.java
=> [wpilib] PWMSpeedController.get(): Apply Inversion

wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
This gives an informative error in Java instead of crashing the JVM.
=> [wpimath] Catch Drake JNI exceptions and rethrow them

.github/workflows/documentation.yml
This allows us to limit the scope of personal access tokens
=> [build] Use deploy key for doc publish

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
This was broken by #3010.
Also fix a few unknown key cases and a nullptr return that could cause a crash.
Fixes #3044.
=> [sim] GUI: Fix Keyboard Joystick

build.gradle
This allows custom formatting where desired (e.g. of table values).
=> [build] Add toggleOffOn to Java spotless

simulation/halsim_ws_core/doc/wpilib-ws.yaml
Create a version of the websocket specification which is machine-readable in response to #2758.
=> [doc] Add machine-readable websocket specification

wpimath/src/main/java/edu/wpi/first/wpilibj/system/plant/LinearSystemId.java
C++ already has the model descriptions.
Closes #3077
=> [wpimath] Add model description to LinearSystemId Javadocs

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
=> [sim] Add max value setting for keyboard joysticks

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp, wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp, wpilibc/src/main/native/include/frc/simulation/ElevatorSim.h, wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java
=> [wpilib] Fixup wouldHitLowerLimit in elevator and arm sim classes

wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
This will need an accompanying update to [this document in frc-docs](https://github.com/wpilibsuite/frc-docs/blob/master/source/docs/zero-to-robot/step-4/creating-benchtop-test-program-cpp-java.rst). I'm not quite sure how that is handled w/r/t versioning.
=> Remove negation of ArcadeDrive(...) in the C++ Getting Started Example

wpimath/src/test/java/edu/wpi/first/wpilibj/kinematics/SwerveModuleStateTest.java, wpimath/src/test/native/cpp/kinematics/SwerveModuleStateTest.cpp
=> [wpimath] Add tests for swerve module optimization

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
=> [sim] GUI: Add right click popup for keyboard joystick settings

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Robot.java
=> [examples] Instantiate m_ramseteController in example

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java, cscore/src/main/java/edu/wpi/cscore/VideoEvent.java, cscore/src/main/java/edu/wpi/cscore/VideoListener.java, cscore/src/main/native/cpp/Handle.h, cscore/src/main/native/cpp/Notifier.cpp, cscore/src/main/native/cpp/Notifier.h, cscore/src/main/native/cpp/cscore_c.cpp, cscore/src/main/native/cpp/cscore_cpp.cpp, cscore/src/main/native/cpp/jni/CameraServerJNI.cpp, cscore/src/main/native/include/cscore_c.h, cscore/src/main/native/include/cscore_cpp.h, ntcore/src/main/native/cpp/ConnectionNotifier.h, ntcore/src/main/native/cpp/EntryNotifier.h, ntcore/src/main/native/cpp/LoggerImpl.h, ntcore/src/main/native/cpp/RpcServer.h, wpiutil/src/main/native/include/wpi/CallbackManager.h
Change Java VideoListener to use polling.
=> [cscore] Add polled support to listener

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
Check values during load and operation to avoid potential crashes due to
ini file errors or corruption.
Fixes #3166.
=> [sim] GUI: Make keyboard settings loading more robust

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/ExtendedKalmanFilter.java, wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
Fixes #3145.
Co-authored-by: Declan Freeman-Gleason <declanfreemangleason@gmail.com>
=> [wpimath] Add custom residual support to EKF

docs/build.gradle, shared/javacpp/publish.gradle, shared/jni/publish.gradle, wpilibc/publish.gradle
=> Fixup doxygen generated include dirs to match what users would need

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandGroupBase.java, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/Command.java, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/CommandGroup.java, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java, wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/command/Scheduler.java, wpilibOldCommands/src/test/java/edu/wpi/first/wpilibj/MockHardwareExtension.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogEncoder.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogGyro.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/DigitalInput.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/DigitalOutput.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedController.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CallbackStore.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DriverStationSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/Mechanism2D.java, wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ElevatorSimTest.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/subsystems/Collector.java
Fixed a few things we were using internally that had deprecation warnings that could trivially be updated. Also fixed some generic issues, and some other small warnings.
=> Fix all warnings given by intellisense that are not unused variables or deprecation

wpilibc/src/main/native/cpp/RobotController.cpp, wpilibc/src/main/native/include/frc/RobotController.h
This function already exists in Java.
=> Add RobotController::GetBatteryVoltage() to C++

wpilibc/src/main/native/cpp/DoubleSolenoid.cpp, wpilibc/src/main/native/cpp/Solenoid.cpp, wpilibc/src/main/native/cpp/SolenoidBase.cpp, wpilibc/src/main/native/cpp/simulation/DoubleSolenoidSim.cpp, wpilibc/src/main/native/cpp/simulation/SolenoidSim.cpp, wpilibc/src/main/native/include/frc/DoubleSolenoid.h, wpilibc/src/main/native/include/frc/Solenoid.h, wpilibc/src/main/native/include/frc/SolenoidBase.h, wpilibc/src/main/native/include/frc/simulation/DoubleSolenoidSim.h, wpilibc/src/main/native/include/frc/simulation/SolenoidSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/DoubleSolenoid.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/Solenoid.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/SolenoidBase.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DoubleSolenoidSim.java, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SolenoidSim.java
=> Add DoubleSolenoidSim and SolenoidSim classes

wpimath/src/main/java/edu/wpi/first/wpilibj/trajectory/Trajectory.java, wpimath/src/main/native/cpp/trajectory/Trajectory.cpp, wpimath/src/main/native/include/frc/trajectory/Trajectory.h, wpimath/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryConcatenateTest.java, wpimath/src/test/native/cpp/trajectory/TrajectoryConcatenateTest.cpp
Closes #3138 
I'm not so sure about adding a seemingly random 10_ms (like the snippet in #3138) so I just discarded the first state in the second trajectory and added the total time of the first trajectory to the rest of the states.
=> [wpimath] Add methods to concatenate trajectories

simulation/halsim_gui/src/main/native/cpp/SimDeviceGui.cpp
=> [sim] GUI: Add option to show prefix in Other Devices

glass/src/libnt/native/cpp/NetworkTables.cpp
=> [glass] NT: Fix return value in StringToDoubleArray

wpimath/src/main/java/edu/wpi/first/wpilibj/util/Units.java, wpimath/src/test/java/edu/wpi/first/wpilibj/util/UnitsTest.java
=> [wpimath] Units.java: Add kg-lb conversions

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java, wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp
Relevant to #3172 but I think that a further solution should be implemented.
=> RamseteCommand: Output 0 if interrupted

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/DifferentialDrivePoseEstimator.java, wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/MecanumDrivePoseEstimator.java, wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/SwerveDrivePoseEstimator.java, wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h, wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h, wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
=> [wpimath] Add pose estimator overload for vision + std dev measurement

wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/ExampleSmartMotorController.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/ExampleSmartMotorController.java
Adds some basic functionality to the ExampleMotorController so that
controller inputs show up in LiveWindow widgets in simulation.
Closes #3108
=> [examples] Make DriveDistanceOffboard example work in sim

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
The original PR (#2934) was created before we moved to Spotless so the
formatting check was never run.
=> Run Spotless formatter

glass/src/libnt/native/cpp/NetworkTablesSettings.cpp, glass/src/libnt/native/include/glass/networktables/NetworkTablesSettings.h
Also add option to get IP from DS.
=> [glass] NetworkTablesSettings: Don't block GUI

wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
=> Make KoP drivetrain simulation weight 60 lbs

glass/src/lib/native/cpp/other/Plot.cpp
=> [glass] Plot: Show full source name as tooltip and in popup

glass/src/lib/native/cpp/other/Plot.cpp
=> [glass] Plot: Don't overwrite series ID

wpimath/src/main/java/edu/wpi/first/math/WPIMathJNI.java, wpimath/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryUtil.java, wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
=> [wpimath] Use JNI for trajectory serialization

hal/src/main/java/edu/wpi/first/hal/HAL.java, hal/src/main/java/edu/wpi/first/hal/simulation/SimulatorJNI.java
This enables the static lists to be private.
=> [hal] Move registerSimPeriodic functions to HAL package

wpilibc/src/main/native/cpp/Compressor.cpp, wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java
=> [wpilib] Fix Compressor sendable properties

wpilibc/src/main/native/cpp/AnalogEncoder.cpp, wpilibc/src/main/native/include/frc/AnalogEncoder.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogEncoder.java
=> Add AnalogEncoder(int) ctor

glass/src/lib/native/cpp/other/Log.cpp, glass/src/lib/native/include/glass/other/Log.h
Fix #3231 
I'm not sure how I can get the buffer content from `m_data` - the buffer is private and I'm not sure what's the best method of getting the content from it. Either a getter, or perhaps something with `friend`? (I'm not very C++ literate)
=> Add "copy to clipboard" button in glass::LogView

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/educational/EducationalRobot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/educational/Main.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/educational/Robot.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json
Educational robot is a very minimal template designed for educational use
(rather than competition).
=> Add Java template for educational robot

hal/src/main/native/athena/HAL.cpp, hal/src/main/native/athena/HALInternal.h, hal/src/main/native/cpp/ErrorHandling.cpp, hal/src/main/native/cpp/jni/HALUtil.cpp, hal/src/main/native/include/hal/Errors.h, hal/src/main/native/include/hal/HALBase.h, hal/src/main/native/sim/HAL.cpp, wpilibc/src/main/native/cpp/Errors.cpp, wpilibc/src/main/native/include/frc/Errors.h, wpilibcExamples/src/main/cpp/examples/HAL/c/Robot.c
This is just the infrastructure code currently, none of the hal calls have been updated. However the WPILibC and JNI sides have been updated and mainly what I want reviewed.
=> Add HAL_GetLastError to enable better error messages from HAL calls

wpimath/src/main/java/edu/wpi/first/wpilibj/system/plant/DCMotor.java, wpimath/src/main/native/include/frc/system/plant/DCMotor.h
=> Add DCMotor factory function for Romi motors

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
=> [wpilibj] DifferentialDrivetrainSim: Rename constants to match the style guide

hal/src/main/native/athena/AddressableLED.cpp, hal/src/main/native/athena/AnalogTrigger.cpp, hal/src/main/native/athena/Counter.cpp, hal/src/main/native/athena/DMA.cpp, hal/src/main/native/athena/Encoder.cpp, hal/src/main/native/athena/FPGAEncoder.cpp, hal/src/main/native/athena/PDP.cpp, hal/src/main/native/athena/SPI.cpp, hal/src/main/native/athena/SerialPort.cpp, hal/src/main/native/cpp/jni/CounterJNI.cpp, hal/src/main/native/cpp/jni/EncoderJNI.cpp, hal/src/main/native/sim/AddressableLED.cpp, hal/src/main/native/sim/Encoder.cpp, hal/src/main/native/sim/PDP.cpp, wpilibc/src/main/native/cpp/AnalogGyro.cpp
Makes the error messages much more specific to each error.
Closes #3225
=> [hal] Switch all instances of PARAMETER_OUT_OF_RANGE to last error reporting

wpilibc/src/main/native/cpp/Preferences.cpp, wpilibc/src/main/native/include/frc/Preferences.h, wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
=> [wpilib] Deprecate Put* in favor of Set* in Preferences

wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/MotorController.java
This avoids a vscode deprecation warning.
May fix #3346.
=> [wpilibj] Add MotorController.setVoltage default

wpilibcExamples/build.gradle
=> [build] Gradle: Make C++ examples runnable

outlineviewer/src/main/native/cpp/main.cpp
=> [outlineviewer] Change default size to 600x400

wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/SwerveModule.cpp, wpilibcExamples/src/main/cpp/examples/SwerveBot/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/SwerveBot/include/SwerveModule.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
=> Fix SwerveBot Example to use unique encoder ports

wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/Constants.h, wpilibcExamples/src/main/cpp/examples/SwerveBot/include/SwerveModule.h, wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/Constants.h, wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/SwerveModule.cpp, wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/include/Drivetrain.h, wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/include/SwerveModule.h, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/Constants.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/Constants.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/RobotContainer.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervesdriveposeestimator/Drivetrain.java, wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervesdriveposeestimator/SwerveModule.java
Fix encoder allocation and default command.
Fixes #3349
=> [examples] Fix Swerve and Mecanum examples
