wpilibsuite/allwpilib

.travis.yml

`sudo apt-get update -q` can fail a site doesn't respond.
This is the solution proposed here:
Related https://github.com/travis-ci/travis-ci/issues/5221

Fix apt-get update -q causing build to fail

---

wpilibcIntegrationTests/src/PCMTest.cpp
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PCMTest.java

The PCM tests recently were failing by being slightly higher than voltage than expected. raised the tolerance to account for this.
Voltage was still clearly less than the on state while in the off state.
Change-Id: I8ac28867024f3ce7b4104fc03622e6133ac2b80f

Fixed PCM tests by raising tolerance slightly

---

.travis.yml

Not sure if `./gradlew -PmakeSim build` is enough or if we also need other commands. It seemed to be running `assemble` and `check` before.
Change-Id: Iba2c5feddd19ab2402f8ca3b2087d8785e632564

Fix travis configuration to include compiling simulation

---

wpilibc/Athena/include/DriverStation.h
wpilibc/Athena/src/DriverStation.cpp
wpilibj/src/athena/cpp/lib/FRCNetworkCommunicationsLibrary.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/communication/FRCNetworkCommunicationsLibrary.java

Before, C++ had no locking on the driver station storage variables. That has been added. In addition, the data is no double buffered. This means that the 5ms that the DS loop used to take out of the main robot loop does not happen anymore.

Implements locking in C++ DriverStation, and adds double buffering to DS Thread

---

hal/include/HAL/HAL.hpp
hal/lib/Shared/HAL.cpp
wpilibc/Athena/src/DriverStation.cpp
wpilibj/src/athena/cpp/lib/FRCNetworkCommunicationsLibrary.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/communication/FRCNetworkCommunicationsLibrary.java

First part of the HAL changes. Returns -1 to 1 for joysticks instead of -128 to 127. Implemented by adding a new buffer type, and still keeping an old buffer instance. This saves allocations, at least in C++.
Sorry about the multiple commits. Dependent on #25, and that commit will go away then that gets rebased.

Changes HAL to return -1 to 1 for joysticks

---

hal/lib/shared/HAL.cpp
wpilibc/athena/include/CANTalon.h
wpilibc/athena/src/DriverStation.cpp

The previous wpilibc reformat missed an issue with CANTalon.h, and a patch merged since then didn't run the formatter.

Ran formatter again

---

styleguide/format.py

I've been using format.py in scripts for managing all my branches. Making the "Processing" lines only print with a verbose option keeps the output clean.

Added verbose flag to format.py

---

wpilibc/athena/src/PIDController.cpp

Testing to see if that could be the cause of the PID Controller SegFault.

Explicitly stops the PIDController Notifier before the destruction of the class

---

wpilibc/athena/include/CANJaguar.h
wpilibc/athena/include/CANSpeedController.h
wpilibc/athena/include/CANTalon.h
wpilibc/athena/include/PWMSpeedController.h
wpilibc/athena/include/RobotDrive.h
wpilibc/athena/include/SpeedController.h
wpilibc/athena/src/CANJaguar.cpp
wpilibc/athena/src/CANTalon.cpp
wpilibc/athena/src/PWMSpeedController.cpp
wpilibc/athena/src/RobotDrive.cpp
wpilibc/sim/include/Jaguar.h
wpilibc/sim/include/SpeedController.h
wpilibc/sim/include/Talon.h
wpilibc/sim/include/Victor.h
wpilibc/sim/src/Jaguar.cpp
wpilibc/sim/src/RobotDrive.cpp
wpilibc/sim/src/Talon.cpp
wpilibc/sim/src/Victor.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/CANJaguar.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/CANTalon.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/PWMSpeedController.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotDrive.java
wpilibj/src/shared/java/edu/wpi/first/wpilibj/SpeedController.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/Jaguar.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/RobotDrive.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/Servo.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/SpeedController.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/Talon.java
wpilibj/src/sim/java/edu/wpi/first/wpilibj/Victor.java

CANJaguar is the only motor controller using sync groups, so that feature doesn't belong in an interface used by all motor controllers. If teams want to use sync groups, they should cast to the appropriate motor controller type themselves.

Removed sync group from SpeedController interface

---

styleguide/format.py

This can happen if the script is run from a directory other than the
project root or styleguide.

format.py: Error out if no files found to format.

---

README.md

This provides a quick navigation link to our travis build.
Additionally, it makes it so that the master build status can be confirmed quickly.

Add Travis Badge to ReadMe

---

wpilibc/athena/include/DriverStation.h
wpilibc/athena/src/DriverStation.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java

In case of spontaneous wake ups, we should be checking a condition
variable in a loop in addition to the wait.
Note that we can not use the existing m_newControlData, as that has a
possible race condition with existing user code that it does not look
like we could work around.

Places while loop around DS wait condition.

---

hal/include/HAL/Handles.h
hal/lib/athena/handles/HandlesInternal.cpp
hal/lib/athena/handles/HandlesInternal.h
hal/lib/athena/handles/IndexedHandleResource.h
hal/lib/athena/handles/LimitedHandleResource.h
hal/lib/athena/handles/UnlimitedHandleResource.h

Handles will be replacing opaque pointers in the HAL for better compatibility and easier error checking. This commits adds the initial resource management and definition for handles.
The enum is not fully implemented, as values will be added as we come across them. More errors might get added later as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/91)

Adds support for Handles to the HAL

---

wpilibc/shared/src/ErrorBase.cpp

contextMessage.size() returns a size_t, but snprintf wants an int.  This
works on 32-bit platforms but is incorrect for 64-bit platforms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/66)

ErrorBase: change to ostringstream

---

hal/lib/athena/handles/HandlesInternal.cpp
hal/lib/athena/handles/HandlesInternal.h

Failure to check for invalid type on handle creation, and handle type
check was broken.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/94)

Fixes a few bugs in the initial handle implementation

---

hal/include/HAL/Handles.h
hal/include/HAL/Notifier.h
hal/lib/athena/HALAthena.cpp
hal/lib/athena/Notifier.cpp
hal/lib/athena/SPI.cpp
hal/lib/athena/handles/HandlesInternal.cpp
hal/lib/athena/handles/HandlesInternal.h
hal/lib/athena/handles/UnlimitedHandleResource.h
wpilibc/athena/include/Notifier.h
wpilibc/athena/src/Notifier.cpp
wpilibj/src/athena/cpp/lib/NotifierJNI.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/Notifier.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/NotifierJNI.java

Internally, the linked list now uses shared_ptrs instead of raw pointers. In addition, in the WPILib the notifier handle is now made atomic. Then before the class is destructed, the handle is now set to 0. This should help solve one of the existing race conditions. A 0 handle is correctly handled down at the HAL level.
One more change is the location of the Handle Enum was changed to be internal. This is needed for future compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/97)

Moves Notifier over to handles

---

wpilibc/shared/src/Error.cpp

It getting annoying to ignore this file every time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/102)

Fixes formatting in error.cpp

---

wpilibcIntegrationTests/src/PreferencesTest.cpp

ntcore recently changed GlobalDeleteAll() to not delete persistent values.
This test was relying on the old behavior to provide a clean slate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/103)

Unbreak wpilibc WritePreferencesToFile test.

---

hal/lib/athena/handles/IndexedHandleResource.h
hal/lib/athena/handles/LimitedHandleResource.h

As discussed, the old method of was going to have issues, and was not
going to help in the case of the structs containing pointers. I think we
are just going to have to be careful, as guarenteeing the internal
pointers are const is going to be very difficult.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/101)

Switches indexed handles to shared_ptr

---

wpilibc/athena/include/Notifier.h
wpilibc/athena/src/Notifier.cpp

A month ago, we discussed renaming this mutex to better reflect its current use, and this commit does that. The inline comment was also updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/105)

Rename Notifier::m_handlerMutex to Notifier::m_notifyMutex

---

hal/include/HAL/Task.h
wpilibc/athena/include/RobotBase.h
wpilibc/athena/src/DriverStation.cpp
wpilibc/athena/src/RobotBase.cpp
wpilibc/athena/src/SensorBase.cpp
wpilibc/shared/include/SensorBase.h
wpilibc/sim/include/RobotBase.h
wpilibc/sim/src/DriverStation.cpp
wpilibc/sim/src/RobotBase.cpp
wpilibc/sim/src/SensorBase.cpp

Cleaned up RobotBase, removed singleton list from SensorBase, and removed unused typedefs and NULL_TASK macro from HAL's Task.hpp. Making the robot class instance static fixed non-POD statics used by the instance during destruction from being destroyed first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/77)

Cleaned up robot startup and cleanup/shutdown code

---

wpilibc/shared/include/PIDController.h
wpilibj/src/shared/java/edu/wpi/first/wpilibj/PIDController.java

This was added to explain the apparent oversight with respect to controller behavior with different sample rates.

Clarified that PID controller runs in discrete time

---

hal/lib/athena/DIO.cpp
hal/lib/athena/DigitalInternal.h

When a digital output object that was tied to an mxp pin had enable pwm called on it
it would pwm on a pin 6 lower
(although if this wasn't an mxp pin it wouldn't do anything at all.)
Fixed in Digital.cpp by adding 6 if it is an MXP pin in setPWMOutputChannel()
This should fix the CanJaguar test because when digitalOutputs used as PWM
were freed, the PWM generator was set to the number of pins, which meant it
was actually outputing on pin 20.
Change-Id: Ib48db3e6e3bf78659622145969d24011cc231ea6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/14)

Fixed issue with digital outputs used as pwm on mxp

---

hal/include/HAL/HAL.h
hal/lib/athena/HALAthena.cpp
wpilibc/athena/src/AnalogInput.cpp
wpilibc/athena/src/AnalogOutput.cpp
wpilibc/athena/src/AnalogTrigger.cpp
wpilibc/athena/src/SensorBase.cpp
wpilibc/athena/src/SolenoidBase.cpp
wpilibj/src/athena/cpp/lib/JNIWrapper.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/AnalogOutput.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/JNIWrapper.java

It was a no-op, and most likely in the future it will be that way too.
Removing to clean up the API.

Removes freePort from the HAL

---

wpilibc/athena/include/DigitalOutput.h
wpilibc/athena/src/DigitalOutput.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DigitalOutput.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/CANMotorEncoderFixture.java

The previous version would just return the class name for the DigitalOutput port. Now it actually gets the dio port value for better readability.

Makes the CANJaguar test error status messages more useful

---

wpilibj/athena.gradle

This fixes the double-add of shared classpath. Note that simulation likely needs the same fix, but WSL does not support Gradle or Java yet, so I couldn't test it there. @bradamiller, I don't know who does sim now, but if they could try making this same change in wpilibj/simulation.gradle, try building, and seeing if ntcore.so is duplicated in the resulting jar I'll make the same change on this pull request.

Removed double-add of shared classpath. Fixes #157.

---

wpilibc/athena/include/DriverStation.h
wpilibc/athena/src/DriverStation.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/ControlWord.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/HAL.java

This is one of the calls with the delayed IPC. In the past, teams have
called an IsMode function so much that their code would start lagging.
This adds a cache, so the data is updated either when new data arrives
and we are notified of it, or after 50ms has passes since the last time
the cache was checked and updated.

Adds a maximum time based cache to HALControlWord data

---

hal/include/HAL/DIO.h
hal/include/HAL/PDP.h
hal/include/HAL/Solenoid.h
hal/lib/athena/AnalogInput.cpp
hal/lib/athena/AnalogOutput.cpp
hal/lib/athena/Compressor.cpp
hal/lib/athena/DIO.cpp
hal/lib/athena/PDP.cpp
hal/lib/athena/PWM.cpp
hal/lib/athena/Relay.cpp
hal/lib/athena/Solenoid.cpp
wpilibc/athena/include/SensorBase.h
wpilibc/athena/src/SensorBase.cpp
wpilibc/sim/include/SensorBase.h
wpilibc/sim/src/SensorBase.cpp
wpilibj/src/athena/cpp/lib/DIOJNI.cpp
wpilibj/src/athena/cpp/lib/PDPJNI.cpp
wpilibj/src/athena/cpp/lib/PWMJNI.cpp
wpilibj/src/athena/cpp/lib/SolenoidJNI.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/SensorBase.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/DIOJNI.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/PDPJNI.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/PWMJNI.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/SolenoidJNI.java

I don't know what the proper way to make the constants for size use the HAL functions in C++. Java it works fine because of how static final works, but C++ would make the variables non const.

Makes SensorBase checks use HAL check methods

---

hal/lib/athena/Accelerometer.cpp
hal/lib/athena/AnalogInput.cpp
hal/lib/athena/AnalogTrigger.cpp
hal/lib/athena/Counter.cpp
hal/lib/athena/FPGAEncoder.cpp
hal/lib/athena/Interrupts.cpp

AnalogTrigger initialization checks are now in the correct order. Plus frees no longer grab the structure if it is not needed.

Some general cleanups in the HAL

---

wpilibc/athena/include/Joystick.h
wpilibc/athena/src/Joystick.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/Joystick.java

HAL joystick functions now use uint32_t for joystick number and DriverStation functions were rearranged in wpilibc and wpilibj to be consistent with wpilibc header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/98)

Added Joystick::GetAxisType()

---

CONTRIBUTING.md
README.md
styleguide/cppguide.html

include guard section now requires #pragma once, enumerators now exclusively use constant naming, and a mention of format.py was added to the "Formatting" section.
If you see any other inconsistencies in the style guide, let me know.

Updated C++ style guide

---

simulation/SimDS/build.gradle
simulation/build.gradle
wpilibc/athena.gradle
wpilibj/athena.gradle
wpilibj/simulation.gradle

This will prevent duplicates from appearing in any of our produced binaries, even accidentally.

Set duplicate strategy for all jars and zips to prevent duplicates

---

test-scripts/run-tests-on-robot.sh

This will save core dumps (and an archive of the executable that generated it) on the test stand.

run-tests-on-robot.sh: Save coredump on crash.

---

.styleguide

wpilibsuite/styleguide is going to use extensions specified in .styleguide instead of hardcoded extensions (see #4). This PR should be merged first to maintain correct operation of format.py.

Added extensions to .styleguide

---

hal/lib/athena/SPI.cpp

According to #192, we don't cast integers to pointers anymore. The size static_assert is unnecessary.

Remove static_assert for sizeof(uint32_t) <= sizeof(void*)

---

hal/include/HAL/DriverStation.h
hal/include/HAL/cpp/make_unique.h
hal/lib/athena/DIO.cpp
hal/lib/athena/HAL.cpp
wpilibc/athena/src/CameraServer.cpp
wpilibc/athena/src/DriverStation.cpp
wpilibc/athena/src/Joystick.cpp
wpilibc/athena/src/Vision/AxisCamera.cpp
wpilibc/athena/src/Vision/BaeUtilities.cpp
wpilibc/shared/include/CircularBuffer.h
wpilibc/shared/src/Filters/LinearDigitalFilter.cpp
wpilibc/sim/src/DoubleSolenoid.cpp
wpilibc/sim/src/DriverStation.cpp
wpilibc/sim/src/Joystick.cpp
wpilibc/sim/src/RobotBase.cpp
wpilibc/sim/src/RobotDrive.cpp
wpilibc/sim/src/Utility.cpp
wpilibcIntegrationTests/src/FilterNoiseTest.cpp
wpilibcIntegrationTests/src/FilterOutputTest.cpp
wpilibcIntegrationTests/src/PreferencesTest.cpp

See wpilibsuite/styleguide #8.

C standard library functions and types are now prefixed with std::

---

wpilibj/src/athena/java/edu/wpi/first/wpilibj/IterativeRobot.java

Removes the delay from the default IterativeRobot periodic methods.  
Per @ThadHouse's [comment](https://github.com/wpilibsuite/allwpilib/pull/240#r79291125)

Remove delay from periodic methods.

---

wpilibc/athena/src/CANJaguar.cpp
wpilibcIntegrationTests/src/CANJaguarTest.cpp
wpilibcIntegrationTests/src/TiltPanCameraTest.cpp

Since newer versions of GCC emit more warnings and errors, I tried building WPILib with GCC 6.2.0. This patch fixes compilation errors that occurred.

Fixed compilation with GCC 6

---

.travis.yml

Slack integration is useless noise that no one reads. This removes it.

Remove slack integration

---

wpilibc/athena/src/IterativeRobot.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/IterativeRobot.java

Previously could cause a race condition. Also moves wait to the top of
the loop in order to avoid having an initial loop be ran before data can
be check.
Sim is handled in #232, except that needs to be updated as well to move
the wait to the top of the loop.

Makes IterativeRobot not double check for new control data

---

hal/lib/athena/Power.cpp

Was not declared in header, so never used anywhere

Removes an unnecessary function from HAL Power

---

wpilibc/athena/include/DriverStation.h
wpilibc/athena/src/DriverStation.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/DriverStation.java

In C++, we were using a custom Semaphore class, which could have resulted in unexpected behavior from teams. For instance, if the main robot loop stopped, and the DS loop went 5 loops, when the main robot looped resumed, the main loop could run 5 times, which might not be expected. Java just used a boolean to show new control data, so C++ was changed to do this as well. Both C++ and Java were switched to use Atomic booleans instead of a mutex and a regular bool, which is what Java did previously.

Replaces C++ IsNewControlData semaphore with atomic bool, and Java code with AtomicBool

---

wpilibc/athena/include/WPILib.h

Interferes with OpenCV, and is heavy namespace polution anyway.

Removes the REAL definition from wpilib.h

---

.styleguide

format.py now considers files that match patterns in .gitignore to be modifiable files. Therefore, listing them in .styleguide is redundant.

Removed entries from .styleguide that are include in .gitignore

---

wpilibj/src/athena/cpp/lib/HAL.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/HAL.java

This should fix issue #340 where joystick buttons >=8 do not work correctly in wpilibj.
Needed to update the HAL JNI layer to treat the button field as an int rather than a byte

Fixes joystick button handling HAL JNI layer

---

wpilibcIntegrationTests/src/TiltPanCameraTest.cpp

Necessary to allow testing for SPI DIO

Updates SPI device pin in integration testing

---

hal/lib/athena/SerialHelper.cpp

This is more correct, and non-const fails on gcc 4.8.

Use const parameters in std::sort lambda.

---

hal/include/HAL/handles/DigitalHandleResource.h
hal/include/HAL/handles/IndexedHandleResource.h
hal/include/HAL/handles/LimitedClassedHandleResource.h
hal/include/HAL/handles/LimitedHandleResource.h

The binary size is being increased much less then when we originally
tried this. Using static arrays save a pointer indirection and will help
with cache in real time cases.

Switches handles back to std::array

---

wpilibc/athena/include/DriverStation.h
wpilibc/athena/src/DriverStation.cpp

Previously this would have allocated the std::string every time, even if
the message wasn't printed. Now takes a StringRef, and only converts to
std::string when the message actually gets printed.

Switches internal joystick errors to take StringRef

---

wpilibc/athena/src/RobotBase.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/RobotBase.java

As a CSA, I found it very handy to look at what language
a team was using while checking SW versions on the DS.
That was removed when updating to 2017 versioning.

Put language in version string

---

wpilibc/athena/include/SerialPort.h
wpilibc/athena/src/SerialPort.cpp

The old method had a fairly large race condition, and the way the docs
were written could cause users to get confused. Up for discussion on
adding the old API back and deprecating it, however I think this is
probably a change were we want a full break. The break will also affect
only teams sending a std::string directly to the API, and will most
likely fix teams trying to send a char* to the API.

Adds safe serial port write methods

---

wpilibc/athena/src/CameraServer.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java

The current LabVIEW dashboard (Beta 4) requires the source type to be either
"usb:" or "ip:" and does not support "cv:".  To work around this, use a source
type of "usb:" for OpenCV sources as well.

CameraServer: Fix LabVIEW dashboard OpenCV compatibility.

---

hal/include/HAL/handles/DigitalHandleResource.h
hal/include/HAL/handles/IndexedClassedHandleResource.h
hal/include/HAL/handles/IndexedHandleResource.h
hal/include/HAL/handles/LimitedClassedHandleResource.h
hal/include/HAL/handles/LimitedHandleResource.h
hal/include/HAL/handles/UnlimitedHandleResource.h

While it technically doesn't matter what the return type of the assignment operator is since it's deleted, assignment operators should return a reference instead of a value.

Fixed signatures of deleted assignment operators

---

hal/lib/athena/SPI.cpp

Was goint to throw an exception if used, as it was attempting to read the analog accumulator.

Fixes SPI Accumulator averages

---

README.md
cppSettings.gradle
hal/build.gradle
myRobotCpp/build.gradle
wpilibc/athena.gradle
wpilibcIntegrationTests/build.gradle
wpilibj/athena.gradle

Currently, a hack exists in WPILib's build system regarding the RoboRIO Cross-Toolchain, in that an ARM target must be added to both the GCC and Clang toolchain to maintain build capabilities on Macintosh Systems. This is not necessary and causes the RoboRIO GCC Toolchain to be incorrectly identified as Clang on Mac systems. This PR fixes this hack.
The toolchains `visualCpp`, `gcc`, and `clang` are created by the Gradle Native Platform, and exist as 'default' toolchains should other toolchains not be declared by the buildscript. In the current version of the buildscript, both `gcc(Gcc)` and `macGcc(Clang)` are created (see [here](https://github.com/wpilibsuite/allwpilib/blob/master/cppSettings.gradle#L167-L216)). As described in the comment above `macGcc`, the hack is needed because …

Fix RoboRIO Cross-Toolchain GCC Status

---

.gitignore

VsCode now supports Java, but it creates these files, and there is no
way to turn it off. Will be adding this to a few other repos too.

Adds project and classpath ignores

---

hal/lib/athena/Solenoid.cpp

The error was NO_AVAILABLE_RESOURCES, which is not the proper error to
return. Instead,  just return the error directly from the allocation.

Fixes solenoid allocation error message

---

wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java

Would throw if the camera was disconnected. We handle this properly at
the JNI level to not have this crash the entire program, but the error
is still kind of annoying, and not really an error.

Fixes exception on camera creation without plugged in camera

---

wpilibc/athena/src/PowerDistributionPanel.cpp

The exceptions were removed from Java because these fail more often then
not. Teams are noticing this in C++ as well. In addition for some reason
ClearErrors() is causing about 0.5 seconds of lag. That's another issue,
but this will match Java and solve that issue for users.

Removes StatusIsFatal checks from PDP

---

wpilibc/athena/src/CameraServer.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/CameraServer.java

This should prevent (as currently happens) occassionally getting just the
mDNS address in the stream value.

CameraServer: Always update addresses when updating stream values.

---

wpilibc/athena/src/Relay.cpp
wpilibcIntegrationTests/src/RelayTest.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/Relay.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/RelayCrossConnectTest.java

Add additional tests that would have caught this previously.

Fix exception when getting a relay in kReverse Direction. Fixes #458

---

wpilibc/athena/include/SolenoidBase.h
wpilibc/athena/src/SolenoidBase.cpp
wpilibj/src/athena/cpp/lib/SolenoidJNI.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/SolenoidBase.java
wpilibj/src/athena/java/edu/wpi/first/wpilibj/hal/SolenoidJNI.java

Instance methods were kept around for backwards compat in Java. In C++,
the instance methods were changed to match Java. Also some cleanup to
the JNI layer to match updated variable types we missed.
Closes #416

SolenoidBase functions are now static

---

wpilibc/athena/src/Utility.cpp
wpilibc/sim/src/Utility.cpp

We can't read [0] on an empty StringRef or the StringRef itself asserts.
Instead, we can just check if size() != 0
Closes #502

Fixes assertions to not crash StringRef

---

wpilibc/shared/include/SmartDashboard/SendableChooser.h
wpilibc/shared/include/SmartDashboard/SendableChooser.inc

Fixed undefined behavior when returning nullptr for T = std::string. Also added
support for T = std::unique_ptr<U> by returning U* in that case.

Fixed return value of SendableChooser<T>::GetSelected() for non-pointer T's

---

hal/include/HAL/DriverStation.h
hal/lib/athena/FRCDriverStation.cpp
wpilibj/src/athena/cpp/lib/HAL.cpp

No safe way to do this with interop, so a function is needed.

Adds function to HAL to free malloc'd joystick name

---

hal/build.gradle
hal/include/HAL/handles/DigitalHandleResource.h
hal/include/HAL/handles/HandlesInternal.h
hal/include/HAL/handles/IndexedClassedHandleResource.h
hal/include/HAL/handles/IndexedHandleResource.h
hal/include/HAL/handles/LimitedClassedHandleResource.h
hal/include/HAL/handles/LimitedHandleResource.h
hal/include/HAL/handles/UnlimitedHandleResource.h
hal/lib/athena/Compressor.cpp
hal/lib/shared/handles/HandlesInternal.cpp

Useful in the sim to force a full reset. On roboRIO, the information is
still created and added, but is not checked because of speed
considerations.  In addition, the reset functionality will do nothing.

Adds way to reset and version all HAL handles

---

hal/include/HAL/Notifier.h
hal/include/HAL/cpp/NotifierInternal.h
hal/lib/athena/HAL.cpp
hal/lib/athena/Notifier.cpp
wpilibj/src/athena/cpp/lib/NotifierJNI.cpp

Testing showed this wasn't an issue with timing, and allows for more
safety in user code making mistakes. Places where the extra thread
wouldn't help have been kept non threaded, using a new internal API.

Switches all notifiers created with the external API to be threaded

---

wpilibcIntegrationTests/include/command/MockCommand.h
wpilibcIntegrationTests/include/command/MockConditionalCommand.h
wpilibcIntegrationTests/src/RelayTest.cpp

Added newline before comment block and replaced angle brackets around includes
with quotation marks. All other integration tests use quotation marks for WPILib
includes.

Miscellaneous formatting and style fixes for integration tests

---

wpilibj/src/athena/cpp/lib/CANJNI.cpp
wpilibj/src/athena/java/edu/wpi/first/wpilibj/can/CANJNI.java

Switches CANJNI to use byte[] rather then ByteBuffer, and throws exceptions for invalid platforms

---

wpilibj/src/athena/cpp/lib/HAL.cpp

Must have been missing a compiler flag in the new build system, and errors were getting thrown regarding aliasing of pointers in JNI. This fixes that to be not alias anymore.

Fixes JNI aliasing issues involving ControlWord and AllianceStation

---

wpilibc/athena/src/TimedRobot.cpp

This also gets allwpilib compiling again with gcc 4.8.

Remove use of std::chrono_literals (C++14 feature).

---

hal/src/main/native/athena/CAN.cpp
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/include/HAL/CAN.h
hal/src/main/native/include/HAL/HAL.h
hal/src/main/native/sim/CAN.cpp
hal/src/main/native/sim/ErrorsInternal.h
hal/src/main/native/sim/HAL.cpp

Can someday be added to the simulator. Removes the last use case for the
ni headers directly.

Adds a HAL wrapper around the CAN API's

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

wpilibj was always returning true for if it was a real robot or not.  The HAL has the functionality to return different values if you are using the athena vs. sim code, so just tap into that.

Java now asks the HAL if it is a simulation or not

---

wpilibj/src/main/native/cpp/CANJNI.cpp
wpilibj/src/main/native/cpp/HALUtil.cpp

Keep that header and the ifdefs out of wpilibj libraray.  Based on #623

Replacing FRC_NetworkCommunication in wpilibj with the HAL CAN code to maintain consistency

---

wpilibj/publish.gradle

Move published wpilibj JNI shared artifact into shared/ subfolder

---

wpilibc/src/main/native/cpp/Commands/Command.cpp
wpilibc/src/main/native/cpp/LiveWindow/LiveWindow.cpp
wpilibc/src/main/native/cpp/RobotBase.cpp
wpilibc/src/main/native/cpp/SmartDashboard/SmartDashboard.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Command.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

Closes #548 
Changed to dotfile format from tildes: `~TYPE~`, `~STATUS~` => `.type`, `.status`
Keys that are now metadata:
| Component | Old key | New key |
|---|---|---|
| Sendable (in LiveWindow) | `"Name"` | `".name"` |
|  | `"Subsystem"` | `".subsystem"` |
| Command | `"name"` | `".name"`
|  | `"isParented"` | `".isParented"`
These keys are now metadata to reduce clutter in dashboards and table viewers
Supersedes and closes #600 due to many merge conflicts in that PR
Smartdashboard currently uses the dotfile format so this is required for beta. Shuffleboard and OutlineViewer are both backwards compatible.

Change metadata format to dotfile, make certain entries metadata

---

wpilibj/build.gradle

Not exactly sure why it was there in the first place. Closes #664

Removes OpenCV dependency from wpilibJNI

---

simulation/halsim_print/build.gradle

Building a non-athena library in athena only is not possible.

Fixes halsim_print to not try and build when the 'onlyAthena' flag has been set

---

hal/src/main/native/athena/HAL.cpp
hal/src/main/native/sim/HAL.cpp

This is particularly useful for the simulation when invoked
inside Eclipse.  Otherwise, you won't see the robot starting
message.
I have tested this on both Linux and Windows with the simulator.  I am currently unable to test this on Athena as I don't have ready access to a Rio.

Set the llvm standard output stream to be unbuffered.

---

hal/src/main/native/sim/DriverStation.cpp

Causes the HALSIM_WaitForProgramStart loop to break, essentially
notifying simulators the robot is good to go.

Adding call to notify program started

---

wpilibc/src/main/native/cpp/Preferences.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java

Allows shuffleboard to automatically discover the type, instead of inflexibly hardcoding it
This also puts it in line with "sendable" components

Add .type metadata to preferences table

---

hal/src/main/native/athena/cpp/SerialHelper.cpp

This avoids a fork that causes an out-of-memory error in Java.
Depends on wpilibsuite/wpiutil#43

SerialHelper: Use llvm path functions instead of popen.

---

.gitignore
build.gradle

As the title implies. Adding to the root project allows for an intellij project file to be created, since the individual sub-project 'module' files are pretty useless without a linking, parent idea project.

Add IDEA plugin to root project

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/I2C.java

Allows underrun, which matches c++ behavior.
Fixes #711

Fixes receive size in Java I2C

---

hal/src/main/native/athena/PWM.cpp
hal/src/main/native/include/HAL/cpp/Log.h
wpilibc/src/main/native/cpp/DoubleSolenoid.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Command.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Scheduler.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Set.java

Instances of the ternary operator were replaced with if statements if the result was either easier to understand or had no effect.

Replaced ternary operators with if statements

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Fixes bugs where Mat's are initialized before anything cscore was
called.

Force load OpencCV and cscore libraries on program initialization

---

hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/PWM.cpp

Works around an NI bug in image 10.

Only returns lower 32 bits of FPGA time

---

wpilibc/src/main/native/cpp/PIDController.cpp
wpilibc/src/main/native/include/Filters/Filter.h
wpilibc/src/main/native/include/PIDController.h
wpilibc/src/main/native/include/PIDSource.h
wpilibcIntegrationTests/src/FRCUserProgram/cpp/PIDToleranceTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/PIDToleranceTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MotorEncoderTest.java

I prefer this solution over the queue we're using now because it avoids all the special cases we kept tacking on. This patch is related to #29 in that it filters the inputs rather than the errors. Therefore, it fixes the problem described therein and also simplifies maintenance.
The only functional regression I've noticed in this implementation is that the filter's buffer is cleared upon resizing. This could be worked around by adding a copy constructor to LinearDigitalFilter that copies the internal ring buffer contents of an old filter. I'll do that when I have time in a few days.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/wpilibsuite/allwpilib/38)

PIDController class now uses LinearDigitalFilter for filtering velocity instead of an internal queue

---

wpilibc/src/main/native/cpp/PIDController.cpp
wpilibc/src/main/native/include/PIDController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java

It got removed during the LinearDigitalFilter change (#38) instead of deprecated
by mistake.

Added PIDController::GetAvgError() back in

---

wpilibcIntegrationTests/src/FRCUserProgram/cpp/FilterOutputTest.cpp
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/FilterOutputTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/FilterOutputFixture.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/TestBench.java

Ensures LinearDigitalFilter moving average returns to zero after non-zero
values are inserted.
Tests for issue #642

Add return-to-zero test for LinearDigitalFilter moving average

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/SampleRobot.java

robotInit() and HAL.observeUserProgramStarting() should be called in
startCompetition() rather than the constructor.

Fixed crash in wpilibj SampleRobot

---

wpilibc/src/main/native/cpp/Filters/LinearDigitalFilter.cpp
wpilibc/src/main/native/include/Filters/LinearDigitalFilter.h

llvm::ArrayRef<> replaces both the std::initializer_list<> and std::vector<>
constructor overloads.

Replaced extra constructors in LinearDigitalFilter with llvm::ArrayRef<>

---

hal/src/main/native/include/MockData/CanData.h
hal/src/main/native/include/MockData/NotifyCallbackHelpers.h
hal/src/main/native/sim/CAN.cpp
hal/src/main/native/sim/MockData/CanDataInternal.cpp
hal/src/main/native/sim/MockData/CanDataInternal.h
hal/src/main/native/sim/MockData/NotifyCallbackHelpers.cpp

Basically added callback scheme for a pass through to something higher
level.  Since the ID is embedded into the arbitration ID, and some
devices can use different schemes whether it is plugged in through a
device or put into the daisy chain (pigeonImu), I made one "internal
data object" for max reusability.

Adding callbacks for CAN

---

wpilibc/src/main/native/include/PIDController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java

PIDController::SetPercentTolerance() behaves identically to it, so removing
SetTolerance() leaves one obvious way to do absolute or percent tolerance.

Deprecated PIDController::SetTolerance()

---

wpilibc/src/main/native/cpp/Drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/Drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/Drive/MecanumDrive.cpp
wpilibc/src/main/native/include/Drive/DifferentialDrive.h
wpilibc/src/main/native/include/Drive/KilloughDrive.h
wpilibc/src/main/native/include/Drive/MecanumDrive.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java

I also found some inconsistencies in MecanumDrive and KilloughDrive and fixed
them.
Drive now uses the NED axes convention. Therefore, the positive X axis points
ahead, the positive Y axis points to the right, and the positive Z axis points
down.
Translation in X assumes forward is positive. Translation in Y assumes right is
positive. Rotation rate assumes clockwise is positive. Angles are measured
clockwise from the positive X axis.
Based on the angle origin convention, DrivePolar() for both Mecanum and Killough
needed the normalization removed, sine used to compute the Y component, and
cosine used to compute the X component.
The vector rotation done in DriveCartesian() needs to rotate by a negative angle
instead of positive to undo the robot's rotation. RobotDrive assumed a clockwise …

Improved Drive docs and fix implementation bugs revealed by this

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/include/Timer.h

* GetClock() is now officially deprecated since its comment already informally
did so and the function just forwards to Timer::GetFPGATimestamp().
* The declaration of GetPPCTimestamp() is missing a definition and has been
removed.
* std::this_thread::sleep_for() returns immediately when given a negative
duration, so the check for that was removed from Wait().

Performed cleanup of Timer's free functions

---

wpilibc/src/main/native/cpp/NidecBrushless.cpp
wpilibc/src/main/native/include/NidecBrushless.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/NidecBrushless.java

This provides a way to stop motor operation even if the DIO is disconnected.
Also change Set() to enable the PWM instead of having the constructor do it.
Provide an explicit Enable() call to re-enable after Disable() is called.
This is different from the other motor controllers (which automatically
re-enable when Set() is called) due to the dual-wiring of this motor
controller.
Motor safety results in disabling the motor only until the next Set() call.

NidecBrushless: Have disable() call PWM.setDisabled().

---

test-scripts/jenkins-run-tests-get-results.sh

Potentially will fix java tests not enabling.

Waits 10 seconds between running the C++ and Java test

---

config.gradle
wpilibc/src/main/native/include/PIDController.h
wpilibcIntegrationTests/src/FRCUserProgram/cpp/MotorEncoderTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MotorEncoderTest.java

This was replaced with an external LinearDigitalFilter. To reduce boilerplate,
constructor overloads that take references were added to LinearDigitalFilter.
External ownership is now expected rather than shared ownership.

Deprecated internal filter of PID controller

---

wpilibc/src/main/native/cpp/Filters/Filter.cpp
wpilibc/src/main/native/cpp/Filters/LinearDigitalFilter.cpp
wpilibc/src/main/native/include/Filters/Filter.h
wpilibc/src/main/native/include/Filters/LinearDigitalFilter.h

Composition is less verbose with references than with smart pointers.

Add reference constructors/factory methods to LinearDigitalFilter

---

wpilibcIntegrationTests/src/FRCUserProgram/cpp/TestEnvironment.cpp
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/test/AbstractComsSetup.java

A failure is much better then an infinite loop.

Bail out of the integration tests if enable fails

---

wpilibc/src/main/native/cpp/PIDController.cpp
wpilibc/src/main/native/include/PIDController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java

m_pidInput and m_pidOutput are considered constant after their construction.
Setting the input range, output range, tolerance, or continuous mode locks the
controller. m_error and m_result are held in temp variables and set at the end
of the calculation.
Getters of P, I, D, F, m_error, m_setpoint, m_result, and m_enabled lock the
critical section. P, I, D, F, and m_setpoint are retrieved at the beginning of
Calculate().
Fixes #40.

Reduced scope of PIDController's critical sections

---

hal/build.gradle
hal/src/main/native/include/HAL/handles/HandlesInternal.h
myRobot/build.gradle
myRobot/src/main/native/cpp/MyRobot.cpp
simulation/adx_gyro_accelerometer/build.gradle
simulation/halsim_print/build.gradle
wpilibc/build.gradle
wpilibcIntegrationTests/build.gradle
wpilibj/build.gradle

In roborio GCC 5.5, __FRC_ROBORIO__ has been added directly to the
compiler. So we can instead use that to detect if we are build for the
roborio, and in a much more reliable way.

Removes custom CONFIG_ATHENA compiler directive

---

hal/src/main/native/include/MockData/AccelerometerData.h
hal/src/main/native/include/MockData/AnalogGyroData.h
hal/src/main/native/include/MockData/AnalogInData.h
hal/src/main/native/include/MockData/AnalogOutData.h
hal/src/main/native/include/MockData/AnalogTriggerData.h
hal/src/main/native/include/MockData/CanData.h
hal/src/main/native/include/MockData/DIOData.h
hal/src/main/native/include/MockData/DigitalPWMData.h
hal/src/main/native/include/MockData/DriverStationData.h
hal/src/main/native/include/MockData/EncoderData.h
hal/src/main/native/include/MockData/HAL_Value.h
hal/src/main/native/include/MockData/I2CData.h
hal/src/main/native/include/MockData/MockHooks.h
hal/src/main/native/include/MockData/NotifyCallbackHelpers.h
hal/src/main/native/include/MockData/NotifyListener.h
hal/src/main/native/include/MockData/NotifyListenerVector.h
hal/src/main/native/include/MockData/PCMData.h
hal/src/main/native/include/MockData/PDPData.h
hal/src/main/native/include/MockData/PWMData.h
hal/src/main/native/include/MockData/RelayData.h
hal/src/main/native/include/MockData/RoboRioData.h
hal/src/main/native/include/MockData/SPIAccelerometerData.h
hal/src/main/native/include/MockData/SPIData.h
wpilibc/src/main/native/include/RobotBase.h

I want to add a few more. The current ones are removing all definitions
from the MockData headers when in simulation mode. And a constexpr
IsReal and IsSimulation in RobotBase. That's not as helpful now because
of no if constexpr, but still better then what we had, and useful for
the future.

Adds some functionality to use the new FRC compiler define

---

wpilibc/src/main/native/include/Base.h

Will help in season with teams not upgrading their GCC. Will have a
better error message.

Require GCC 5 for wpilib build

---

wpilibc/src/main/native/include/Base.h

No longer necessary in wpilibc. Also force MSVC 2015 or greater.

Remove MSVC 2013 and GCC 4 workarounds

---

wpilibc/src/main/native/cpp/vision/VisionRunner.cpp
wpilibc/src/main/native/include/vision/VisionRunner.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/vision/VisionRunner.java

This was previously possible in Java with Thread.interrupt(), but provide
the same function in both C++ and Java.
Fixes #444.

VisionRunner: Add stop() function to stop a runForever() loop.

---

build.gradle
wpilibj/build.gradle
wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/HAL.java

setErrorData symbol was missing. However, its been deprecated at the
netcomm level for years, and wasn't exposed in wpilibj. And it would
have been crashing since forever, so safe to remove.

Fixes JNI symbol check

---

wpilibc/src/main/native/cpp/LiveWindow/LiveWindowSendable.cpp
wpilibc/src/main/native/cpp/SmartDashboard/NamedSendable.cpp
wpilibc/src/main/native/include/LiveWindow/LiveWindowSendable.h
wpilibc/src/main/native/include/SmartDashboard/NamedSendable.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/NamedSendable.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindowSendable.java

This will help prevent old code from breaking (not all cases, but should help).

Add deprecated shims for LiveWindowSendable and NamedSendable.

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Subsystem.java

It's public in C++ so I'm assuming it should be in Java as well.

Make setDefaultCommand public

---

hal/src/main/native/sim/Encoder.cpp
hal/src/main/native/sim/MockData/EncoderData.cpp
hal/src/main/native/sim/MockData/EncoderDataInternal.h

I would imagine that most simulators would want to work on rotations or raw distance as opposed to "counts".  This change allows those simulators to keep track of the DPP that is set by the user, and they can react as necessary.

Adding callbacks for notifying when the distance per pulse changes

---

wpilibc/src/main/native/cpp/SpeedControllerGroup.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedControllerGroup.java

Previously, `setInverted` would cause the sign of the speed to be flipped *only when setting*. Now, the sign is flipped (if the SpeedControllerGroup is inverted) when getting as well.

Invert when getting motor speed in SpeedControllerGroup

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotDrive.java

In smart IDEs, this will allow users to easily view source for these two classes by linking to it. Just a small QOL change.

Link to replacements for RobotDrive in JavaDocs

---

wpilibc/src/main/native/cpp/Commands/Command.cpp
wpilibc/src/main/native/cpp/Commands/ConditionalCommand.cpp
wpilibc/src/main/native/include/Commands/Command.h
wpilibc/src/main/native/include/Commands/ConditionalCommand.h
wpilibcIntegrationTests/src/FRCUserProgram/cpp/command/ConditionalCommandTest.cpp
wpilibcIntegrationTests/src/FRCUserProgram/cpp/command/MockCommand.cpp
wpilibcIntegrationTests/src/FRCUserProgram/cpp/command/MockConditionalCommand.cpp
wpilibcIntegrationTests/src/FRCUserProgram/headers/command/MockCommand.h
wpilibcIntegrationTests/src/FRCUserProgram/headers/command/MockConditionalCommand.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Command.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/ConditionalCommand.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/command/ConditionalCommandTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/command/MockCommand.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/command/MockConditionalCommand.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/command/MockSubsystem.java

Make sure ConditonalCommand ends if a null command is chosen.
Don't call chosen command's isFinished twice.
Add additional tests for ConditionalCommand.
This does the same thing as #690 but less intrusive.

Fix cancel of inner commands in ConditionalCommands

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/include/DriverStation.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/hal/HAL.java

Publishes the 2018 string to NT so products like SB can present the
current setup.

Adds 2018 match specific data sender over NT

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDController.java

setcontinuous(false) shouldn't throw an exception

PIDController: setContinuous should only check input range if continuous is true

---

hal/src/main/native/include/HAL/handles/IndexedClassedHandleResource.h
hal/src/test/native/cpp/handles/HandleTests.cpp

Nothing in WPILib uses it, so it was not tested

Fixes indexed classed handle resource

---

wpilibc/src/main/native/cpp/Drive/DifferentialDrive.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java

This normalizes within -1..1 to avoid clipping and maintain the ratio between
wheel speeds, since that ratio determines the center of rotation.
Fixes #923.

Added output normalization to DifferentialDrive::CurvatureDrive()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java

```Reset()``` is the only function without a null check around it.  We call the function on startup, which means if it is unplugged the robot crashes.  I noticed null'ing it out is not what is done in C++, don't know why they are different.
Also added an accessor for checking if it is connected, as some teams (us) would like to handle the case where it was not connected on startup.

Adding null check around reset

---

wpilibc/src/main/native/cpp/Drive/RobotDriveBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.java

It now mentions that the deadband is applied to the drive inputs.

Made documentation for RobotDriveBase::SetDeadband() clearer

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/CameraServer.java

We don't want failures here to stop other video properties from updating.
Reported here: https://www.chiefdelphi.com/forums/showthread.php?t=162860

CameraServer: catch VideoExceptions in putSourcePropertyValue().

---

wpilibc/src/main/native/cpp/SmartDashboard/SendableChooserBase.cpp
wpilibc/src/main/native/include/SmartDashboard/SendableChooserBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java

SendableChooser::InitSendable() is written such that it saves the table
being used in an instance variable.  This doesn't work if the chooser is
added to both LiveWindow and SmartDashboard.  Normally it is not added to
LiveWindow because the name is empty, but if setName() is called this could
still happen.  Note adding the same SendableChooser to SmartDashboard with
two different names is also not currently supported, for the same reason.
The correct solution will be to remove the instance variable, but this is
too high risk to implement mid-season, so instead just remove from LiveWindow.

SendableChooser: Do not automatically add to LiveWindow.

---

wpilibcExamples/src/main/cpp/templates/commandbased/Commands/ExampleCommand.cpp
wpilibcExamples/src/main/cpp/templates/commandbased/Commands/MyAutoCommand.cpp
wpilibcExamples/src/main/cpp/templates/commandbased/Robot.cpp
wpilibcExamples/src/main/cpp/templates/commandbased/Robot.h
wpilibcExamples/src/main/cpp/templates/iterative/Robot.cpp
wpilibcExamples/src/main/cpp/templates/iterative/Robot.h
wpilibcExamples/src/main/cpp/templates/sample/Robot.cpp
wpilibcExamples/src/main/cpp/templates/sample/Robot.h
wpilibcExamples/src/main/cpp/templates/timed/Robot.cpp
wpilibcExamples/src/main/cpp/templates/timed/Robot.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/commandbased/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/commandbased/commands/ExampleCommand.java

Robot.cpp has been split into header-source pairs and the Command-based
examples now define an example subsystem in the Robot class.

Improved Command-based examples

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java

The `{@link SpeedControllerGroup}` was broken because SpeedControllerGroup was not imported.

Fix JavaDoc tag in Differential Drive

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Command.java

The isParented method had an incorrect javadoc tag for the return value.

Fix JavaDoc tag in Command

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java

It was using array indexing to map the return value of
DriverStation.getJoystickType() to HIDType when the enum should instead be
constructed from the int value. C++ already does this.
Fixes #968.

Fixed wpilibj GenericHID.getType()

---

cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/UsbCameraImpl.cpp
cscore/src/main/native/cpp/c_util.h
cscore/src/main/native/cpp/cscore_c.cpp
ntcore/src/main/native/cpp/Value.cpp
ntcore/src/main/native/cpp/WireDecoder.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_test.cpp
wpiutil/src/main/native/include/wpi/memory.h

These are used in ntcore and cscore.  Add inline null-checking versions
to wpi/memory.h and use them throughout.

Check for nullptr return from malloc, calloc, and realloc.

---

hal/src/main/native/sim/Notifier.cpp

- If this isn't done, then the wait will always be performed at least twice

Notifier: reset updatedAlarm before waiting

---

buildSrc/src/main/groovy/ExtraTasks.groovy

Kind of like running the `test` task will run all java tests, running `testCpp` will run only the c++ tests. Identical to what we have for compilation (`compile` for java, `compileCpp` for c++)

Adds a testCpp task to all projects

---

wpilibj/build.gradle

Fixes #1039 
Previously, gradle didn't properly output the classpath for the version file, so editors would not see the file and continuously report and error. This fixes that, and cleans up the build slightly as well.

Fixes gradle wpilibj classpath for editors

---

shared/config.gradle

For mac, 32 bit will never be supported. Apple has dropped all support.
For 32 bit linux, vscode explicitly does not support it, and it is difficult to find anybody using a 32 bit os.

Removes 32 bit configs for linux and mac.

---

shared/config.gradle
wpilibc/src/main/native/cpp/Joystick.cpp
wpilibc/src/main/native/include/Joystick.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java

The new naming makes it more clear that the constants are intended to be used
with the channel setters.

Rename Joystick default channel constants

---

myRobot/src/main/native/cpp/MyRobot.cpp
wpilibc/src/main/native/include/RobotBase.h
wpilibcExamples/src/main/cpp/examples/ArcadeDrive/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/AxisCameraSample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/CANPDP/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Encoder/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Gyro/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GyroMecanum/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/IntermediateVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/MecanumDrive/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/MotorControl/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/PacGoat/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/PotentiometerPID/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/QuickVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Relay/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Solenoid/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Ultrasonic/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/UltrasonicPID/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/commandbased/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/iterative/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/sample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/timed/cpp/Robot.cpp

The START_ROBOT_CLASS() macro's main() now calls this function through a
deprecated proxy function to encourage users to switch.

Replaced the START_ROBOT_CLASS() macro with a template function

---

wpilibc/src/main/native/cpp/Drive/KilloughDrive.cpp
wpilibc/src/main/native/include/Drive/MecanumDrive.h

The docs already have the correct name, but some headers and sources
weren't updated. Java doesn't have this mistake.

Fixed the names of the arguments to some C++ drive classes

---

wpilibc/src/main/native/cpp/PIDBase.cpp
wpilibc/src/main/native/include/PIDBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDBase.java

For example, an outer position feedback controller can now drive the
reference of an inner velocity feedback controller.

PIDController now supports composition

---

build.gradle

Has issues with some git configs, and shouldn't be an absolute build requirement. We need to fix the issue with gitattributes instead.

Remove line ending requirements from spotless

---

wpilibc/src/main/native/include/Base.h
wpilibcExamples/src/main/cpp/examples/AxisCameraSample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Encoder/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/include/Subsystems/Wrist.h
wpilibcExamples/src/main/cpp/examples/IntermediateVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/PacGoat/cpp/Subsystems/DriveTrain.cpp
wpilibcExamples/src/main/cpp/examples/PacGoat/include/Robot.h
wpilibcExamples/src/main/cpp/examples/PacGoat/include/Subsystems/DriveTrain.h
wpilibcExamples/src/main/cpp/examples/QuickVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Relay/cpp/Robot.cpp

Instead of defining NAMESPACED_WPILIB to remove the "using namespace frc"
shim in Base.h, instead require NO_NAMESPACED_WPILIB be defined to add it.
Fix up various examples to use correct namespacing.

Default to requiring frc namespace for wpilibc.

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/RobotControllerTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/UtilityClassTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/livewindow/LiveWindowTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboardTest.java

Add tests to ensure utility classes have private constructors and all public methods are static.
Should prevent issues like #870

Utility class tests

---

.styleguide
.travis.yml
gen/wpilibj_frcnetcomm.py
hal/src/main/java/edu/wpi/first/wpilibj/hal/FRCNetComm.java

Making Travis run wpilibj_frcnetcomm.py will help avoid bitrot in
FRCNetComm.java in the future. Formatting was also enabled on Python
source files and FRCNetComm.java was added back to the generated files
list.

Fixed wpilibj_frcnetcomm.py and added invocation to Travis

---

shared/config.gradle

Macs shared libaries drop about 10% in size, but the symbol library is about 5x the size of the original library

Adds Windows PDB's to release zips, and skips mac stripping

---

wpilibcExamples/src/main/cpp/templates/commandbased/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/iterative/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/sample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/timed/cpp/Robot.cpp

In order for this to properly work, we need to remove the main code.
Then the test component will actually have the main in it.  Example tests will be added later.

Adds support for unit testing from GradleRIO for C++ projects

---

ntcore/src/main/native/cpp/ntcore_c.cpp

The implementation of ConvertToC for arrays was broken.  Also change it
to be templated on the returned array type, rather than passing the array.
This makes the uses a bit more clean.

ntcore: Fix C API polling array returns.

---

ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableInstance.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTablesJNI.java
ntcore/src/main/java/edu/wpi/first/networktables/RpcAnswer.java
ntcore/src/main/native/cpp/RpcServer.cpp
ntcore/src/main/native/cpp/RpcServer.h
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

Java would never properly dispose, and C++'s were easy to respond after disposing.
For C++, we now return a bool if the call was successful or not, for java we throw an exception

Solves some safety issues with RPCs

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java

Its not needed, as the extending AutoClosable is enough.
Should we remove free() from the contract? The implementations would still be freeable, but the interface doesn't need to be explicitly freeable I don't think.

Removes close() explicitly from Gryo interface

---

wpiutil/src/main/native/include/wpi/Twine.h

This makes it possible to pass "null" Twines and detect it in the callee.

Twine: Make isNull() public.

---

wpiutil/.styleguide
wpiutil/src/main/native/include/wpi/Signal.h
wpiutil/src/test/native/cpp/sigslot/function-traits.cpp
wpiutil/src/test/native/cpp/sigslot/recursive.cpp
wpiutil/src/test/native/cpp/sigslot/signal-extended.cpp
wpiutil/src/test/native/cpp/sigslot/signal-threaded.cpp
wpiutil/src/test/native/cpp/sigslot/signal-tracking.cpp
wpiutil/src/test/native/cpp/sigslot/signal.cpp

Imported from https://github.com/palacaze/sigslot
Classes were renamed from lowercase_me to UppercaseMe style, primarily
to avoid conflicting with the C standard library "signal" function.  They
were also moved to the "wpi::sig" namespace.

wpiutil: Add a signal-slot implementation.

---

wpiutil/src/main/native/include/wpi/priority_mutex.h

On all Linux platforms it can be specifically requested by defining
WPI_USE_PRIORITY_MUTEX.

Only use priority_mutex on RoboRIO by default.

---

hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/include/HAL/Accelerometer.h
hal/src/main/native/include/HAL/AnalogTrigger.h
hal/src/main/native/include/HAL/CANAPI.h
hal/src/main/native/include/HAL/Counter.h
hal/src/main/native/include/HAL/DriverStation.h
hal/src/main/native/include/HAL/Encoder.h
hal/src/main/native/include/HAL/HAL.h
hal/src/main/native/include/HAL/I2C.h
hal/src/main/native/include/HAL/SPI.h
hal/src/main/native/include/HAL/SerialPort.h
hal/src/main/native/include/HAL/Types.h
hal/src/main/native/sim/DriverStation.cpp

This also fixes the return type of `HAL_IsNewControlData()` and `HAL_MatchType`'s type.
Since UsageReporting is intended to be namespaced, I've hidden that when this is being used in C.
Fixes: #476
Closes: #535
Ref: #1122

Make HAL headers C-compatible

---

wpilibj/src/test/java/edu/wpi/first/wpilibj/command/CommandSequentialGroupTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/command/CommandTimeoutTest.java

Fix these random failures: http://imacjenkins.dyn.wpi.edu/job/WPILib/job/WPILib%20Windows%20-%20PR/29/consoleFull

Fix race conditions in command tests by increasing the delay time

---

shared/googletest.gradle

When using the clang toolchain with GoogleTest, use the Address Sanitizer to catch memory leaks / potential memory issues. Currently will only run on macOS since we use gcc by default everywhere else.

Use ASAN when on Clang

---

myRobot/build.gradle
myRobot/src/main/java/Main.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/axiscamera/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyro/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyromecanum/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/intermediatevision/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdrive/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/motorcontrol/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/motorcontrolencoder/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/potentiometerpid/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/quickvision/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/quickvision/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/tankdrive/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonic/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/commandbased/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/iterative/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/sample/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timed/Main.java

With requiring an importer, we should be able to automate this in the importer. It is much more reliable, as it no longer depends on a magic string in a manifest file, and if the user changes their main class, or makes it not import from something RobotBase, it will fail to compile

Moves Java main function from library to user code

---

simulation/gz_msgs/build.gradle

We don't want any wildcards in allwpilib. Also uses plugin repo for protobuf rather then mavenCentral.

Remove wildcard dep version from gazebo msg

---

wpilibc/src/main/native/cpp/SmartDashboard/SendableChooserBase.cpp
wpilibc/src/main/native/include/SmartDashboard/SendableChooserBase.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/subsystems/DriveTrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/subsystems/Shooter.java

With these two fixes, and a few not-suitable-for-upstream patches, I am able to operate the PacGoat robot, in simulation, both on Windows against the nt sim as well as against the gazebo simulator.
Instructions for running this are stashed in my wip6 branch here:
https://github.com/jwhite66/allwpilib/blob/wip6/simulation/README.md
The two changes in this PR, I believe, are correct.  The other code in the wip6 branch imagines running the samples from allwpilib, when I think we eventually want to focus on using GradleRIO.  (And that code is not really correct, anyway).

Minor fixes required to enable the simulated robots to run

---

wpiutil/src/main/native/cpp/uv/Tcp.cpp
wpiutil/src/main/native/include/wpi/uv/Tcp.h

This allows reusing the Tcp object in cases when the connection errors out.

Add Reuse function to uv::Tcp

---

wpiutil/src/main/native/include/wpi/uv/Tcp.h
wpiutil/src/main/native/include/wpi/uv/Udp.h

These help avoid the need for reinterpret_casts in common use cases.

Add sockaddr_in overloads for uv::Tcp and uv::Udp

---

wpiutil/src/main/native/include/wpi/HttpParser.h

This is more user-friendly than returning the number of parsed bytes.

HttpParser: Change Execute() to return StringRef

---

wpiutil/src/main/native/cpp/HttpParser.cpp
wpiutil/src/main/native/include/wpi/HttpParser.h
wpiutil/src/test/native/cpp/HttpParserTest.cpp

This allows reuse of the HttpParser object for multiple requests.

HttpParser: Add Reset() function

---

appveyor.yml

There is a limit on artifacts, and doing both builds gains little  and doubles build time

Remove appveyor artifacts, and only build 64 bit

---

wpiutil/src/test/native/cpp/uv/UvGetAddrInfoTest.cpp

This test likes to intermittently hang for some unknown reason, so disable it.

Disable UvGetAddrInfo Concurrent test on Windows

---

cscore/src/main/native/cpp/Frame.cpp
cscore/src/main/native/cpp/Frame.h
cscore/src/main/native/cpp/Image.h
cscore/src/main/native/cpp/MjpegServerImpl.cpp

This allows two streams with different compression levels, and also allows
a stream to receive a different compression level than provided by a JPEG
camera (decompress and recompress).

cscore: Support multiple levels of JPEG compression

---

cscore/src/main/java/edu/wpi/cscore/MjpegServer.java
cscore/src/main/native/cpp/MjpegServerImpl.cpp
cscore/src/main/native/cpp/MjpegServerImpl.h
cscore/src/main/native/cpp/PropertyContainer.h
cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inl

This allows code to set the stream compression, resolution, and FPS used if
not specified in HTTP parameters by the client.

MjpegServer: Add ability to set compression, etc in code

---

cscore/src/main/native/cpp/CvSourceImpl.cpp
cscore/src/main/native/cpp/CvSourceImpl.h
cscore/src/main/native/cpp/SourceImpl.cpp
cscore/src/main/native/cpp/SourceImpl.h

This makes it easier to implement new non-camera Sources.

cscore: Move CvSourceImpl placeholders into SourceImpl

---

shared/googletest.gradle

This reverts commit 340b26badaac3eddf89e39e0cc8f293e09808fc3.
closes #1232 
We are going to revert this because it broke Mac builds.  The root cause of this is a requirement that the entire application must be built with asan to link properly.  For more information about why this is please see the link below.
https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives

Revert "Use ASAN when on Clang (#1187)"

---

wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilderImpl.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

This indicates whether or not the Sendable listeners are installed.
It is set to true when SendableBuilder.startListeners() starts the listeners,
and set to false when SendableBuilder.stopListeners() stops the listeners.
This allows dashboards to choose to change their widget display based on
whether or not the value is actually controllable.

Add a .controllable key as a standard part of Sendable

---

wpilibc/src/main/native/cpp/smartdashboard/SendableChooserBase.cpp
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.inc
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooserBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java

This echos back the "selected" value to the "active" key to enable dashboards
to display positive feedback to the user that the value is actually set on
the robot side.
Also fixes SendableChooser so it can be safely added to multiple tables.
Changes to "selected" in any table will result in all "active" values being
updated.

Add confirmation to SendableChooser

---

wpilibc/src/main/native/cpp/DoubleSolenoid.cpp
wpilibc/src/main/native/cpp/NidecBrushless.cpp
wpilibc/src/main/native/cpp/PWM.cpp
wpilibc/src/main/native/cpp/PWMSpeedController.cpp
wpilibc/src/main/native/cpp/Relay.cpp
wpilibc/src/main/native/cpp/Solenoid.cpp
wpilibc/src/main/native/cpp/SpeedControllerGroup.cpp
wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilder.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilderImpl.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DoubleSolenoid.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/NidecBrushless.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWM.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMSpeedController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Relay.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Solenoid.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedControllerGroup.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilder.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

SendableBuilder.setActuator() sets the .actuator key in the network table
so dashboards can change behavior on the client side if desired, and also
sets a local flag (retrievable via isActuator()).

Add a way to indicate a Sendable is an actuator

---

cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cameraserver/src/main/native/include/cameraserver/CameraServer.h
wpilibc/src/main/native/cpp/MotorSafetyHelper.cpp
wpilibc/src/main/native/cpp/commands/CommandGroup.cpp
wpilibc/src/main/native/cpp/commands/ConditionalCommand.cpp
wpilibc/src/main/native/cpp/commands/Scheduler.cpp
wpilibc/src/main/native/include/frc/MotorSafetyHelper.h
wpilibc/src/main/native/include/frc/commands/Command.h
wpilibc/src/main/native/include/frc/commands/Scheduler.h
wpiutil/src/main/native/include/wpi/SmallPtrSet.h

Remove a number of header dependencies by replacing std::set with wpi::SmallPtrSet and using the Pimpl idiom for Scheduler and CameraServer.
Fixes #414.

Header cleanup

---

docs/build.gradle

This avoids depending on latex for HTML formula output.

 docs: Set use_mathjax to true

---

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java
cscore/src/main/java/edu/wpi/cscore/VideoSource.java
cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/SourceImpl.h
cscore/src/main/native/cpp/UsbCameraImpl.cpp
cscore/src/main/native/cpp/cscore_c.cpp
cscore/src/main/native/cpp/cscore_cpp.cpp
cscore/src/main/native/cpp/jni/CameraServerJNI.cpp
cscore/src/main/native/include/cscore_c.h
cscore/src/main/native/include/cscore_cpp.h
cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inl

By default, sources automatically manage their connection based on whether
any sinks are connected.  This change allows the user to keep a connection
open or force it closed regardless of the number of connected sinks.

cscore: Add connection strategy to sources

---

build.gradle
shared/java/javacommon.gradle

Basically followed the instructions here: https://github.com/google/error-prone/issues/860
@auscompgeek if you wouldn't mind checking this.

Update errorprone config for Java 10

---

wpiutil/src/main/native/include/wpi/spinlock.h
wpiutil/src/test/native/cpp/spinlock_bench.cpp

Note this is only faster than mutex if compiler optimization is enabled.

wpiutil: Add a mutex-compatible spinlock implementation.

---

wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.inc
wpilibcExamples/src/main/cpp/examples/PacGoat/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/commandbased/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/iterative/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/sample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/timed/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/commandbased/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/iterative/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/sample/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/timed/Robot.java

Rename addDefault to setDefaultOption and addObject to addOption.
The old names are still available but are marked as deprecated.

SendableChooser: Rename addDefault and addObject for clarity

---

wpilibc/src/main/native/cpp/commands/Command.cpp
wpilibc/src/main/native/cpp/commands/InstantCommand.cpp
wpilibc/src/main/native/cpp/commands/PIDCommand.cpp
wpilibc/src/main/native/cpp/commands/TimedCommand.cpp
wpilibc/src/main/native/include/frc/commands/Command.h
wpilibc/src/main/native/include/frc/commands/InstantCommand.h
wpilibc/src/main/native/include/frc/commands/PIDCommand.h
wpilibc/src/main/native/include/frc/commands/TimedCommand.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/Command.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/InstantCommand.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/PIDCommand.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/TimedCommand.java

Per discussion on #1262 this adds a single optional Subsystem parameter that is automatically marked as `requires()`.

Add dependency injection of Subsystems to commands

---

.travis.yml
wpiutil/CMakeLists.txt

This is required for dlopen, which is required by libuv.

Add libdl to wpiutil cmake build

---

ntcore/doc/networktables3.adoc

Addresses documentation gap identified in #1277.

ntcore: Describe RPC version 0 in spec

---

ntcore/src/main/java/edu/wpi/first/networktables/RpcAnswer.java
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp

The underlying protocol uses raw bytes, so they should not be required to be
a valid string.

ntcore: Change params in Java RpcAnswer from String to byte[]

---

wpiutil/src/main/native/include/wpi/spinlock.h

The STL mutex header defines classes like lock_guard and unique_lock.

wpiutil spinlock.h: Include STL mutex for convenience

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/include/frc/Notifier.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java

The loop spins otherwise.
Fixes #1294.

Notifier: properly reset HAL alarm in non-periodic case

---

wpilibc/src/main/native/cpp/commands/InstantCommand.cpp
wpilibc/src/main/native/include/frc/commands/InstantCommand.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/command/InstantCommand.java

An ActionCommand is derived from a concept from the [RobotDotNet implementation of WPIlib](https://github.com/robotdotnet/WPILib/blob/master/WPILib.Extras/ActionCommand.cs). The core concept is that it "lifts" a language-native callable to become a Command.
It also is influenced by RobotDotNet's [SubsystemCommand](https://github.com/robotdotnet/WPILib/blob/master/WPILib.Extras/SubsystemCommand.cs) class, which I plan on making a PR for in the future. The rationale for this is that it allows declarative command creation, like so:
```java
public Command closeOuter() {                                                                                                                             
return new ActionCommand("Close Outer Manipulator", this, this::closeOuterManipulator); …
```

Add Lambda Support to InstantCommand for C++ and Java

---

wpilibc/src/main/native/cpp/CAN.cpp
wpilibc/src/main/native/include/frc/CAN.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/CAN.java

Useful by vendors wanting to use the API, and make their own device parameters

Adds CAN API constructor that takes explicit manufacturer and device type

---

shared/nilibraries.gradle

Explicit classifier not needed anymore because we generate usage reporing

Update NI Libraries to layout without C++

---

hal/build.gradle

Sometimes wouldn't include generated header file

Fix hal header zip task dependencies

---

hal/src/main/native/athena/I2C.cpp
hal/src/main/native/athena/SPI.cpp
hal/src/main/native/include/hal/I2C.h
hal/src/main/native/include/hal/SPI.h
wpilibc/src/main/native/include/frc/I2C.h
wpilibc/src/main/native/include/frc/SPI.h

This allows HAL_CloseI2C() and HAL_CloseSPI() to be noops, which makes
enabling move semantics in the I2C and SPI wpilibc classes easier and
cleaner.
Fixes #1328.

Add kInvalid value to HAL_I2CPort and HAL_SPIPort

---

cscore/src/main/native/cpp/Frame.h
cscore/src/main/native/cpp/Notifier.cpp
cscore/src/main/native/cpp/default_init_allocator.h
cscore/src/main/native/include/cscore_cpp.h
hal/src/main/native/include/hal/cpp/Log.h
hal/src/main/native/include/hal/cpp/fpga_clock.h
wpilibc/src/main/native/cpp/commands/Scheduler.cpp
wpilibc/src/main/native/include/frc/Error.h
wpilibc/src/main/native/include/frc/Notifier.h
wpilibc/src/main/native/include/frc/Timer.h
wpilibc/src/main/native/include/frc/circular_buffer.h
wpilibc/src/main/native/include/frc/commands/Command.h
wpilibc/src/main/native/include/frc/commands/CommandGroupEntry.h
wpiutil/src/main/native/include/wpi/Logger.h
wpiutil/src/main/native/include/wpi/priority_mutex.h

These are more readable than typedefs. C headers were left alone.

Replace typedefs in C++ source with using declarations

---

wpilibc/src/main/native/include/frc/IterativeRobot.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobot.java

Since https://github.com/wpilibsuite/allwpilib/issues/786 has been
closed as not a legitimate concern, there is now no reason to use
IterativeRobot over TimedRobot. It's a drop-in replacement that's
strictly an improvement in terms of execution jitter.
To migrate, one simply has to replace the IterativeRobot subclass in
their robot code with TimedRobot.

Deprecate IterativeRobot in favor of TimedRobot

---

cscore/src/main/native/cpp/MjpegServerImpl.cpp
cscore/src/main/native/cpp/Notifier.cpp
cscore/src/main/native/cpp/Telemetry.cpp
ntcore/src/main/native/cpp/CallbackManager.h
ntcore/src/main/native/cpp/DsClient.cpp
wpiutil/src/main/native/cpp/EventLoopRunner.cpp
wpiutil/src/main/native/cpp/SafeThread.cpp
wpiutil/src/main/native/include/wpi/SafeThread.h

Use shared_ptr to keep data alive until the thread has terminated.

SafeThread: Avoid use-after-free risk in thread shutdown

---

wpiutil/src/main/native/cpp/SafeThread.cpp
wpiutil/src/main/native/include/wpi/SafeThread.h
wpiutil/src/main/native/include/wpi/jni_util.h

This can be conditionally disabled (for cases like JNI callbacks where the JVM
may block callbacks into it during shutdown).

wpiutil: SafeThread: join on thread exit

---

wpiutil/src/main/native/cpp/SafeThread.cpp

The thread must be released with either a detach or a join, otherwise
std::terminate is called.

wpiutil: SafeThread: Ensure thread is released in destructor

---

build.gradle
shared/nilibraries.gradle

Allows for compile only shared libraries

Update NativeUtils to not copy ni libraries to jenkins RoboRIO

---

README.md

The previous license link reffered to [license.txt](https://github.com/wpilibsuite/allwpilib/blob/master/license.txt). However, it looks like the correct file is [LICENSE.txt](https://github.com/wpilibsuite/allwpilib/blob/master/LICENSE.txt).

Fix link for license

---

wpiutil/src/main/native/include/wpi/Signal.h

This causes a std::move of objects that are both moveable and copyable.

wpiutil: Signal: Don't use std::forward when calling

---

wpiutil/src/main/native/cpp/EventLoopRunner.cpp
wpiutil/src/main/native/cpp/future.cpp
wpiutil/src/main/native/cpp/uv/Async.cpp
wpiutil/src/main/native/include/wpi/future.h
wpiutil/src/main/native/include/wpi/uv/Async.h
wpiutil/src/main/native/include/wpi/uv/AsyncFunction.h
wpiutil/src/main/native/include/wpi/uv/Handle.h
wpiutil/src/test/native/cpp/future_test.cpp
wpiutil/src/test/native/cpp/uv/UvAsyncFunctionTest.cpp

This allows the called function to pass along the promise to another
asynchronous callback.
To avoid memory allocations, add a home-rolled, simplified, non-allocating
version of std::promise and std::future as wpi::promise and wpi::future.

wpiutil: Change uv::AsyncFunction to use promise/future

---

hal/src/main/native/athena/Threads.cpp
hal/src/main/native/include/hal/Threads.h
wpilibc/src/main/native/include/frc/Error.h

For HAL and wpilib, we don't need them, especially in where they were used.

Remove some usages of windows.h

---

docs/build.gradle

This will suppress the following warning during build:
>javadoc: warning - You have not specified the version of HTML to use.
The default is currently HTML 4.01, but this will change to HTML5
in a future release. To suppress this warning, please specify the
version of HTML used in your documentation comments and to be
generated by this doclet, using the -html4 or -html5 options.

Enable HTML5 javadocs

---

hal/src/main/native/sim/DriverStation.cpp

/home/tav/frc/wpilib/allwpilib/hal/src/main/native/sim/DriverStation.cpp: In function 'char* HAL_GetJoystickName(int32_t)':
/home/tav/frc/wpilib/allwpilib/hal/src/main/native/sim/DriverStation.cpp:152:15: error: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
std::strncpy(name, desc.name, len);
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/tav/frc/wpilib/allwpilib/hal/src/main/native/sim/DriverStation.cpp:150:27: note: length computed here
size_t len = std::strlen(desc.name);
~~~~~~~~~~~^~~~~~~~~~~
The next line adds a null terminator, but it's cleaner to just do a
std::memcpy() since the code already assumes a null terminator exists in
the source string.

Fix stringop truncation warning from GCC 8.2

---

wpilibcExamples/src/main/cpp/examples/HidRumble/cpp/Robot.cpp

This is a nit that we missed on #1394

Remove unused import from rumble example

---

wpiutil/src/main/native/include/wpi/WorkerThread.h
wpiutil/src/test/native/cpp/WorkerThreadTest.cpp

This provides a worker thread that can execute a work function with the result
going into either a future or a uv::Loop functor.
Builds on top of #1301.

wpiutil: Add WorkerThread

---

wpiutil/src/main/native/cpp/llvm/raw_ostream.cpp

Static destruction order is not well defined, so it was possible for outs()
or errs() return value to be destroyed even while other code was running,
resulting in a crash.  Instead dynamically allocate the static so the
destructor never runs.  While this technically leaks, valgrind generally
supresses such leaks as the data is still "reachable" from the static pointer.

Don't use static for raw_ostream outs/errs

---

wpilibc/src/main/native/include/frc/DriverStation.h

in reference to #1257
I wasn't sure exactly what `GetGameSpecificMessage` gets, but I'll add it if someone explains.

Add missing driver station documentation

---

wpiutil/src/main/native/libuv/unix/internal.h
wpiutil/src/main/native/libuv/unix/linux-core.cpp

This is set to the FPGA clock by HAL_Initialize.  Note this change means
that libuv loops should not be started until after HAL_Initialize is called.

libuv: Use WPI (FPGA) clock on roboRio

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp

The LabVIEW dashboard has been fixed to understand this prefix.
Fixes #407.

CameraServer: Change opencv sources to publish "cv:" type

---

ntcore/src/main/native/cpp/ConnectionNotifier.h
ntcore/src/main/native/cpp/RpcServer.h
ntcore/src/main/native/cpp/Storage.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp

Without this, our compiler with -Werror -Wextra fails to build ntcore.

Fix unused variable warnings in ntcore

---

cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java
cscore/src/main/java/edu/wpi/cscore/VideoSource.java
cscore/src/main/native/cpp/MjpegServerImpl.cpp
cscore/src/main/native/cpp/SourceImpl.cpp
cscore/src/main/native/cpp/SourceImpl.h
cscore/src/main/native/cpp/cscore_c.cpp
cscore/src/main/native/cpp/cscore_cpp.cpp
cscore/src/main/native/cpp/cscore_oo.cpp
cscore/src/main/native/cpp/jni/CameraServerJNI.cpp
cscore/src/main/native/include/cscore_c.h
cscore/src/main/native/include/cscore_cpp.h
cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inl
wpiutil/src/main/native/include/wpi/Logger.h

This allows save and restore of camera settings.  The restore is a bit
smarter than the save.

cscore: Add JSON for source settings

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java

All null motors will be specified in the error messages
For example, this code would previously only throw an exception when calling a drive method or updating sendable properties:
```java
private SpeedController left, right;
private DifferentialDrive drive;
@Override
public void robotInit() {
drive = new DifferentialDrive(left, right); // using motors before they're assigned
left = ...
right = ...
}
```
It will now throw a NullPointerException specifying all null motors - in this case, `java.lang.NullPointerException: leftMotor, rightMotor` will be thrown immediately from the constructor

Add eager null checks in drive base classes

---

wpilibc/src/main/native/cpp/shuffleboard/Shuffleboard.cpp
wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardInstance.cpp
wpilibc/src/main/native/include/frc/shuffleboard/Shuffleboard.h
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardInstance.h
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardRoot.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardInstance.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardRoot.java

One possible usecase would be to switch between context-specific tabs as the match transitions between states (e.g. a `Preround` tab used before the start of the match with choosers, an `Autonomous` tab that might display robot location or the running commands, a `Teleop` tab for drivers, etc.)

Add methods to change the selected tab in the Shuffleboard app

---

wpilibcExamples/src/main/cpp/examples/ShuffleBoard/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json

I ported over the Java ShuffleBoard example to C++ as referenced in Issue #1428. (I updated the `examples.json` file with this example.
I was not able to completely copy it because adding the methods `WithPosition` and `WithSize` to did not work.
[Snippet #1]( https://github.com/Tyler-Duckworth/allwpilib/blob/d4f7db0db782582360962ae50c266d73a1a0d0db/wpilibcExamples/src/main/cpp/examples/ShuffleBoard/cpp/Robot.cpp#L40-L44)
For comparison, here is the same lines in Java: 
[Snippet #2](https://github.com/Tyler-Duckworth/allwpilib/blob/d4f7db0db782582360962ae50c266d73a1a0d0db/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/shuffleboard/Robot.java#L31-L38)

Created C++ ShuffleBoard example

---

cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inl

This avoids a conversion ambiguity when StringRef is passed.

AxisCamera constructor: add StringRef overload

---

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/Watchdog.cpp
wpilibc/src/main/native/include/frc/Watchdog.h
wpilibc/src/test/native/cpp/WatchdogTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/WatchdogTest.java
wpiutil/src/main/native/include/wpi/PriorityQueue.h

Notifier has one thread per instance because the callbacks must be
asynchronous. Watchdog callbacks can be synchronous, so this overhead
can be done away with via a scheduler thread akin to what the HAL
Notifier does.

Make Watchdog use single thread dispatch

---

wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

Additionally adds a defensive check in SendableBuilderImpl to avoid the NPE
Fixes #1446

Fix LiveWindow attempting to start listeners on uninitialized sendables

---

wpilibc/src/main/native/cpp/PIDBase.cpp

Make the SmartDashboard type consistent between languages. Closes #1466.

Change SmartDashboard type of PIDBase.cpp to match PIDBase.java

---

wpiutil/build.gradle

#1433 didn't properly include the resources in the build as the source set was empty during configuration.

wpiutil: Fix resources build

---

ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/InstanceImpl.h

Windows 7 deadlocks on shutdown if the instances get destructed. So this makes them not get destructed.

Move instances to a non deleting singleton

---

hal/src/main/native/athena/cpp/SerialHelper.cpp

The USB directories we care about are not symbolic links, so we can ignore them
There was a recursive symbolic link, which was causing failure

Don't use symbolic path searching for USB detection

---

hal/src/main/native/sim/mockdata/DriverStationData.cpp
hal/src/main/native/sim/mockdata/DriverStationDataInternal.h

Otherwise, it is required to be set manually, which isn't obvious.
This is because the HighLevel DS classes check that the ds is attached before enabling

Default to DS attached to true in sim

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java

Negative numbers are properly handled, which will reduce chances of deadlocks.

Unconditionally await in awaitUntil

---

wpilibc/src/main/native/include/frc/SampleRobot.h

This way, the warning doesn't occur when including wpilib.h
Closes #1501

Move deprecation warning for SampleRobot to constructor

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java

If an epoch name contains a % symbol, this could've lead to an exception
at runtime where the number of arguments mismatches the format string.

Watchdog: Fix potential IllegalFormatException

---

simulation/halsim_adx_gyro_accelerometer/src/test/native/cpp/ADXRS450_SpiGyroWrapperTest.cpp

It fails with a mutex error very often, and we have not been able to figure out the issue.
It breaks CI.

Disable gyro sim test on mac

---

wpilibc/src/main/native/include/frc/GamepadBase.h
wpilibc/src/main/native/include/frc/JoystickBase.h
wpilibc/src/main/native/include/frc/livewindow/LiveWindowSendable.h
wpilibc/src/main/native/include/frc/smartdashboard/NamedSendable.h

This prevents deprecation messages when including a header but not
instantiating the class. SampleRobot was addressed by #1503.

Move deprecated message in C++ from class level to constructor

---

wpilibc/src/main/native/cpp/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Writing to the versions file throws an exception while simulating on Windows and might write weird files on Linux.
Fixes https://github.com/wpilibsuite/allwpilib/issues/1455

Only write version information on real robot

---

wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/include/frc/MotorSafety.h

wpilibj's default constructor is already correct.

Enable timeout message suppression in C++ MotorSafety class

---

hal/src/main/native/athena/CANAPI.cpp
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/PDP.cpp
hal/src/main/native/sim/CANAPI.cpp
wpilibcIntegrationTests/src/main/native/cpp/PowerDistributionPanelTest.cpp

HAL_GetFPGATime returns 0 if it starts with a non zero status

Fix CAN API's timing out incorrectly

---

cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/HttpCameraImpl.h

Automatically disconnect the HTTP stream if no frames have been received
for 1 second.
Fixes wpilibsuite/Shuffleboard#443.

cscore: handle HTTP stream hangs

---

cscore/examples/enum_usb/enum_usb.cpp
cscore/src/main/java/edu/wpi/cscore/CameraServerJNI.java
cscore/src/main/java/edu/wpi/cscore/UsbCamera.java
cscore/src/main/java/edu/wpi/cscore/UsbCameraInfo.java
cscore/src/main/native/cpp/MjpegServerImpl.cpp
cscore/src/main/native/cpp/UsbCameraImplCommon.cpp
cscore/src/main/native/cpp/jni/CameraServerJNI.cpp
cscore/src/main/native/include/cscore_c.h
cscore/src/main/native/include/cscore_cpp.h
cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inl
cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/osx/UsbCameraImpl.cpp
cscore/src/main/native/windows/UsbCameraImpl.cpp

This is primarily for use on Linux to get by-id or by-path device names.
This information is now part of UsbCameraInfo.
A new entry point was added to UsbCamera to get that camera's UsbCameraInfo.
The alternate paths are also returned in EnumerateUsbCameras.

Provide alternate device paths info for USB cameras

---

cscore/src/main/native/cpp/MjpegServerImpl.cpp

* All of our strings are UTF-8, but the default charset for HTML<5 was ISO-8859-1

cscore: set charset of displayed pages

---

wpilibc/src/main/native/cpp/MotorSafety.cpp

Some instances of StopMotor (most notably DifferentialDrive) call Feed(),
which deadlocks due to Check() holding the same lock.
Fixes #1525.

Fix MotorSafety deadlock

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java

It was incorrectly treating accumulated time as being in milliseconds instead of seconds.
Fixes #1530.

Java: Fix Timer.get() handling of accumulated time

---

cscore/src/main/native/windows/UsbCameraImpl.cpp

WM_CREATE is called at a time where the message pump cannot be called back into, which happens

Use custom message for connecting camera initially.

---

hal/CMakeLists.txt

A source directory was named incorrectly in CamelCase.

Fix cmake hal sim build

---

cscore/src/main/native/linux/UsbCameraProperty.cpp
cscore/src/main/native/linux/UsbCameraProperty.h

The Pi Camera is one of these.  Previously, integers were just being
cast to a string instead of formatted as a string.

cscore: Handle USB camera integer menus

---

wpilibc/src/test/native/cpp/WatchdogTest.cpp

It can't be held property on the asure test system

Disable watchdog test on mac

---

wpiutil/src/main/native/cpp/uv/Pipe.cpp

Otherwise, the acception fails.

Pass IPC value of listening pipe to accepted pipe

---

cscore/src/main/native/windows/UsbCameraImpl.cpp

For now, has to force enumerate all cameras to find the matching one

Add support for camera descriptions on windows

---

cscore/src/main/native/windows/UsbCameraImpl.cpp
cscore/src/main/native/windows/UsbCameraImpl.h
cscore/src/main/native/windows/UsbCameraProperty.cpp
cscore/src/main/native/windows/UsbCameraProperty.h

They're controlled from a separate interface

Fix missing exposure property on windows USB cameras

---

hal/src/main/native/cpp/jni/HALUtil.cpp

With the move of the HAL, the old value no longer worked, as the JNI call is in a different namespace

Update HAL GetStackTrace to properly report user errors

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cameraserver/src/main/native/include/cameraserver/CameraServer.h

This adds a new function "addSwitchedCamera" that creates and publishes a
virtual camera where the published stream information is consistent even if
the mjpeg server source is switched to a different camera.
Previously, changing the source of the mjpeg server resulted in updating the
stream information published for that source.

CameraServer: Add switched camera support

---

hal/src/main/native/athena/DigitalInternal.cpp

It was failing the check when remapping digital sources

Fix SPI CS1 not working correctly

---

cscore/src/dev/native/cpp/main.cpp
cscore/src/main/native/cpp/HttpCameraImpl.cpp
wpiutil/src/main/native/include/wpi/HttpUtil.inl

They only accept %20 instead of + for parameters, they only send '\n' at the boundaries,
And they include the -- when sending the initial boundary.  This solves those parts.
This is not fully enough to fix shuffleboard and others, as the NT format for paths is not the correct path

Fixes receive side of LabVIEW USB streams

---

wpilibc/src/main/native/cpp/Threads.cpp

The functions in Threads.h are in the frc namespace. `using namespace frc;` in
Threads.cpp doesn't put their implementations in the frc namespace, so linker
errors occur when attempting to use them in robot programs.
To fix this, one can either wrap them in a namespace block or prepend
`frc::` to the implementation's signature. Based on past discussion, I
opted for the namespace block.

Fix linker errors with free functions in Threads.h

---

hal/src/main/native/athena/FRCDriverStation.cpp

If total length is over 65536, the packet will get thrown own. This becomes a problem in stackoverflow cases

Limit length of message sent to DS SendError call

---

shared/opencv.gradle

These are common with USB cameras.

Disable extraneous data warnings in libjpeg

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServerShared.java
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/CameraServer.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Otherwise accidentally, a race could occur between coprocessors and rio
Java was done in both old and new locations as its a race

Only generate passthrough URLs for RoboRIO

---

wpiutil/src/main/native/cpp/EventLoopRunner.cpp
wpiutil/src/main/native/include/wpi/uv/Handle.h

Useful for EventLoopRunner to know if a stop is requested, or close is happening for another reason

Add LoopClosing status to Handle

---

wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h

Forward is positive for xSpeed. Java is already correct.
https://github.com/wpilibsuite/allwpilib/blob/a60f312d19ee3a38df4318e1fec86c6789ef667a/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java#L166
https://github.com/wpilibsuite/allwpilib/blob/a60f312d19ee3a38df4318e1fec86c6789ef667a/wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java#L231

Correct C++ DifferentialDrive::ArcadeDrive() xSpeed param documentation

---

wpilibc/src/main/native/cpp/SPI.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java

I would like to propose for SPI usage reporting to use the port ID as its instance numbers.
There are a few advantages to this:
- This eliminates a static variable (which are not so fun in other languages).
- This allows whoever is looking at the raw usage reporting data to differentiate between usage of the MXP and onboard ports (which may be useful in designing/selecting a roboRIO replacement in future).

SPI: Report port as instance for usage reporting

---

wpilibc/src/main/native/cpp/SPI.cpp
wpilibc/src/main/native/include/frc/SPI.h

The Java version takes an int, and `HAL_SetSPISpeed` takes an int as well.

C++ SPI: Fix SetClockRate to take int

---

wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h

The Java versions were already accidentally removed in #1059.

Remove functions in LiveWindow deprecated since 2018

---

wpiutil/src/main/native/include/wpi/Signal.h
wpiutil/src/main/native/include/wpi/uv/Handle.h

This enables const-ness in uv::Handle ReportError() and Invoke() as well.

wpiutil: Signal: make operator() const

---

buildSrc/src/main/groovy/MultiBuilds.groovy
shared/javacpp/setupBuild.gradle
shared/jni/setupBuild.gradle
wpilibc/build.gradle

Removes checks for onlyathena and onlyraspbian, and just disables gtest for cross compilers. That way azure will detect a failure in the future

Fix google test not being disabled for cross compilers

---

buildSrc/src/main/groovy/DisableBuildingGTest.groovy
buildSrc/src/main/groovy/MultiBuilds.groovy
hal/build.gradle
shared/googletest.gradle
wpilibc/build.gradle

Still build them and link them, just don't execute them

Only disable execution of cross compile google tests

---

build.gradle
shared/jni/setupBuild.gradle

This uses jelf now to parse the jni symbols.

Update jni library, fix cross builds of the jni symbol check

---

azure-pipelines.yml

This will ensure everything works with no flags, even without a rio or raspbian compiler

Use base azure image for primary wpilib build

---

ntcore/src/main/native/include/networktables/NetworkTableEntry.h
ntcore/src/main/native/include/networktables/NetworkTableEntry.inl
ntcore/src/main/native/include/networktables/NetworkTableValue.h
wpilibc/src/main/native/cpp/LinearFilter.cpp
wpilibc/src/main/native/cpp/filters/LinearDigitalFilter.cpp
wpilibc/src/main/native/cpp/shuffleboard/RecordingController.cpp
wpilibc/src/main/native/include/frc/LinearFilter.h
wpilibc/src/main/native/include/frc/filters/LinearDigitalFilter.h
wpiutil/src/main/native/cpp/WebSocket.cpp
wpiutil/src/main/native/include/wpi/ArrayRef.h
wpiutil/src/main/native/include/wpi/WebSocket.h
wpiutil/src/main/native/include/wpi/WebSocketServer.h
wpiutil/src/main/native/include/wpi/uv/Stream.h
wpiutil/src/netconsoleServer/native/cpp/main.cpp
wpiutil/src/netconsoleTee/native/cpp/main.cpp
wpiutil/src/test/native/cpp/WebSocketClientTest.cpp
wpiutil/src/test/native/cpp/WebSocketServerTest.cpp

This can be dangerous as it refers to a temporary, and GCC 9.0 warns about
its use.  Instead add std::initializer_list overloads to common places it
was used in an initializer_list sense.

Remove wpi::ArrayRef std::initializer_list constructor

---

cscore/src/main/native/cpp/ConfigurableSourceImpl.cpp
cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/PropertyContainer.cpp
cscore/src/main/native/cpp/SourceImpl.cpp
cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/linux/UsbCameraProperty.cpp
cscore/src/main/native/windows/UsbCameraImpl.cpp
wpiutil/src/main/native/cpp/llvm/Error.cpp
wpiutil/src/main/native/include/wpi/Error.h
wpiutil/src/main/native/include/wpi/Format.h
wpiutil/src/main/native/include/wpi/STLExtras.h
wpiutil/src/main/native/include/wpi/WorkerThread.h
wpiutil/src/main/native/include/wpi/deprecated.h
wpiutil/src/main/native/include/wpi/json.h
wpiutil/src/main/native/include/wpi/uv/Async.h
wpiutil/src/main/native/include/wpi/uv/AsyncFunction.h

Now that all compilers support C++17, remove some old C++14/C++17 shims.
WPI_DEPRECATED macro can't be removed because clang-format formatting of [[deprecated]] is terrible.

Remove pre-C++17 shims

---

wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/include/frc/Timer.h

Timer didn't have working move semantics because mutexes aren't moveable,
meaning the default implementations were ill-formed. MotorSafety wasn't
locking its mutex.

Fix some move constructors

---

wpilibc/src/main/native/include/frc/trajectory/TrapezoidProfile.h

This wasn't necessarily the case before because defining a nondefault
constructor results in no default move constructor.

Make sure move constructor is generated for TrapezoidProfile

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/include/frc/Notifier.h

Using std::function<void()> directly makes it much clearer to the user
what kind of function Notifier expects. The Doxygen comments already say
what the function is used for, so the typedef just discards useful
information.

Remove TimerEventHandler typedef from Notifier class

---

wpilibcIntegrationTests/src/main/native/cpp/MotorEncoderTest.cpp
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MotorEncoderTest.java

Closes #1774 
This also eliminates the call to the deprecated `setPIDSourceType` method.

Make MotorEncoderTest use LinearFilter

---

wpiutil/src/main/native/include/wpi/uv/Process.h

Was broken due to removal of ArrayRef initializer_list constructor.

wpiutil: Fix Process::Spawn()

---

wpilibc/src/main/native/include/frc/WPILib.h
wpilibcExamples/src/main/cpp/templates/commandbased/cpp/OI.cpp

It drastically increases compile times and is bad style. C++ users
should be including what they use. We don't necessarily have to remove
WPILib.h, but it should at least be deprecated.

Deprecate frc/WPILib.h

---

wpilibc/src/main/native/cpp/Joystick.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/cpp/drive/Vector2d.cpp
wpilibc/src/main/native/include/frc/geometry/Rotation2d.h
wpilibc/src/test/native/cpp/LinearFilterNoiseTest.cpp
wpilibc/src/test/native/cpp/LinearFilterOutputTest.cpp
wpilibc/src/test/native/cpp/geometry/Rotation2dTest.cpp
wpilibcExamples/src/main/cpp/examples/MotorControlEncoder/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java
wpiutil/src/main/native/include/wpi/math

Based on http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0631r7.pdf.

Add C++20 std::math constants shim

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java

Java PIDController was missing a default sendable name.

fix missing default name in java pidcontroller

---

wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableBase.cpp
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/SendableBase.java

The mutexes in SendableBase are unnecessary, as the methods are never used asynchronously.  These were preventing the class from having default copy/move constructors, which would be very handy.

remove unnecessary synchronization from SendableBase

---

wpilibc/src/main/native/include/frc/controller/PIDControllerRunner.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDControllerRunner.java

The mutexes in PIDControllerRunner are declared after the Notifier, and
we don't stop the Notifier in `~PIDControllerRunner()`; we call
`PIDControllerRunner::Disable()`, but that doesn't actually stop the
Notifier. It still calls this:
```
void PIDControllerRunner::Run() {
// Ensures m_enabled check and m_controllerOutput() call occur atomically
std::scoped_lock outputLock(m_outputMutex);
std::unique_lock mainLock(m_thisMutex);
if (m_enabled) {
// Don't block other PIDControllerRunner operations on output
mainLock.unlock();
m_controllerOutput(m_controller.Calculate(m_measurementSource()));
}
}
```
When we call `PIDControllerRunner::Disable()`, the Notifier is still
running, locking the mutexes, and accessing `m_enabled`. When the
PIDControllerRunner object is destructed, the …

Fix PIDControllerRunner member destruction order

---

wpilibc/src/main/native/cpp/smartdashboard/ListenerExecutor.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp
wpilibc/src/main/native/include/frc/smartdashboard/ListenerExecutor.h
wpilibc/src/main/native/include/frc/smartdashboard/SmartDashboard.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/ListenerExecutor.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

Previously, the listeners on `Sendable` objects called the passed-in setters asynchronously.  This is a large potential source of bugs, forces a lot of locking logic into other classes, and is not necessarily obvious to users.
This adds a synchronous executor to which setter calls can be posted asynchronously, so that they are all called synchronously from the main loop (namely, from the `SmartDashboard.updateValues()` method).

Synchronous Sendable listeners

---

cscore/src/main/native/cpp/CvSinkImpl.cpp
cscore/src/main/native/cpp/CvSourceImpl.cpp
cscore/src/main/native/cpp/Frame.cpp
cscore/src/main/native/include/cscore_cv.h

The main change in OpenCV 4 was removing its C APIs from OpenCV 1. If
the user has OpenCV 4, they have no way of obtaining the correct
arguments for cscore functions that require the C API. Therefore, we can
fix the build by just not compiling in functions reliant on the C API if
OpenCV 4 is being used.
OpenCV 3 builds should continue to work with this change.

Fix cscore build with OpenCV 4

---

cscore/build.gradle

Was only there for mac usb cam support, but we likely won't get to it this summer anyway,
and its causing a breakage in the backing libraries with cross builds

Remove objective-cpp support

---

wpilibc/src/main/native/cpp/geometry/Pose2d.cpp
wpilibc/src/main/native/cpp/geometry/Rotation2d.cpp
wpilibc/src/main/native/cpp/geometry/Translation2d.cpp
wpilibc/src/main/native/include/frc/geometry/Pose2d.h
wpilibc/src/main/native/include/frc/geometry/Rotation2d.h
wpilibc/src/main/native/include/frc/geometry/Translation2d.h
wpilibc/src/main/native/include/frc/geometry/Twist2d.h
wpilibc/src/test/native/cpp/geometry/Pose2dTest.cpp
wpilibc/src/test/native/cpp/geometry/Rotation2dTest.cpp
wpilibc/src/test/native/cpp/geometry/Translation2dTest.cpp
wpilibc/src/test/native/cpp/geometry/Twist2dTest.cpp
wpiutil/src/main/native/include/units/units.h

After some discussion with @calcmogul, we decided that it would be good to add unit-safety to the geometry classes in C++. This would help users when using kinematics and odometry to keep track of their units using a zero-cost method.

Add unit-safety to C++ geometry classes

---

wpilibc/src/main/native/include/frc/XboxController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java

The enum for the button values on an xboxcontroller should be publicly exposed, as it is not an internal implementation detail but rather is an important piece of the API.

expose xboxcontroller enum

---

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp

For both TimedRobot and IterativeRobotBase, use delegating constructors
to reduce code duplication.

TimedRobot.cpp: Fix deprecation warning

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

Fixes #1642.
C++ behavior was correct.

Correctly report -1 for POV on disconnected joystick

---

wpiutil/CMakeLists.txt

This currently only breaks when cmake is configured with WITH_TESTS but
ultimately this would have affected wpilibc builds too.

Fix cmake Eigen include directory

---

wpilibc/src/main/native/cpp/controller/PIDController.cpp
wpilibc/src/main/native/cpp/controller/ProfiledPIDController.cpp
wpilibc/src/main/native/include/frc/controller/PIDController.h
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h
wpilibc/src/test/native/cpp/controller/PIDInputOutputTest.cpp
wpilibc/src/test/native/cpp/controller/PIDToleranceTest.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/subsystems/ShooterSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/DriveStraight.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetDistanceToBox.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Elevator.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Wrist.cpp
wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/cpp/commands/TurnToAngle.cpp
wpilibcExamples/src/main/cpp/examples/PotentiometerPID/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/UltrasonicPID/cpp/Robot.cpp
wpilibcIntegrationTests/src/main/native/cpp/MotorEncoderTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/PIDInputOutputTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/PIDToleranceTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/subsystems/ShooterSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/DriveStraight.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/SetDistanceToBox.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Elevator.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Wrist.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyrodrivecommands/commands/TurnToAngle.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/potentiometerpid/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/Robot.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/MotorEncoderTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PIDTest.java

It breaks the unit system badly; the tolerance member variable has
different units depending on percent vs absolute. Absolute tolerance is
a lot more natural than percent tolerance anyway.

Remove percent tolerance from PID controller

---

wpilibc/src/main/native/include/frc/geometry/Rotation2d.h

Since a value in radians is always a rotation, it makes sense to provide
an implicit constructor for this for convenience with Pose2d's
constructor.

Make one-arg Rotation2d constructor implicit

---

wpilibc/src/main/native/include/frc/GearTooth.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/GearTooth.java

It only works with a specific sensor that isn't available anymore, the
class is a trivial wrapper around a Counter, and no one uses this class
according to FMS usage reporting.

Deprecate GearTooth class for removal

---

.gitignore
wpilibc/src/main/native/cpp/frc2/command/PIDCommand.cpp
wpilibc/src/main/native/include/frc2/command/PIDCommand.h

Fixes a small inconsistency between the Java and C++ PIDCommands.

add GetMeasurement() to PIDCommand

---

wpiutil/CMakeLists.txt

WPIUtil make installation was failing due to an incorrect INSTALL directory for Eigen.

Fix wpiutil cmake Eigen install source directory

---

shared/jni/setupBuild.gradle
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/java/edu/wpi/first/wpiutil/WPIUtilJNI.java
wpiutil/src/main/java/edu/wpi/first/wpiutil/net/PortForwarder.java
wpiutil/src/main/native/cpp/PortForwarder.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/include/wpi/PortForwarder.h

This class provides an easy way to forward local ports to another host/port.
This is primarily useful to provide a way to access Ethernet-connected devices
from a computer tethered to the RoboRIO USB port.
The most natural spot to put the shared implementation of this class was into
wpiutil, so a wpiutilJNI library has been added.
Fixes #1887.

Add PortForwarder class

---

hal/src/main/java/edu/wpi/first/hal/CANAPIJNI.java
hal/src/main/native/athena/CANAPI.cpp
hal/src/main/native/athena/PDP.cpp
hal/src/main/native/cpp/jni/CANAPIJNI.cpp
hal/src/main/native/include/hal/CANAPI.h
wpilibc/src/main/native/cpp/CAN.cpp
wpilibc/src/main/native/include/frc/CAN.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/CAN.java

It is not necessary anymore, and is a complicated and confusing API to keep around

Remove periodic can read call

---

hal/CMakeLists.txt
hal/src/main/java/edu/wpi/first/hal/HAL.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/HALInitializer.h
hal/src/main/native/cpp/Main.cpp
hal/src/main/native/cpp/jni/HAL.cpp
hal/src/main/native/include/hal/HAL.h
hal/src/main/native/include/hal/Main.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/sim/HALInitializer.h
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Default behavior is still to run the robot main loop in the main thread.
The ability to run the robot main loop in a separate thread and add a hook
for running a different function in the main thread is needed for simulation
GUI support on some platforms.

Add ability to run robot main loop in a separate thread

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryParameterizer.java

The trajectory gen docs use "->". ">" has been replaced with "&gt;".

Fix javadoc warnings about invalid usage of ">"

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableRegistry.java

This prevents LiveWindow bugs from crashing the entire robot program.
Instead, an error is printed and the object is removed from LiveWindow.

LiveWindow: catch errors in callback/builder functions

---

wpilibc/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibc/src/main/native/include/frc2/command/CommandScheduler.h
wpilibc/src/test/native/cpp/frc2/command/ScheduleCommandTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibj/src/test/java/edu/wpi/first/wpilibj2/command/ScheduleCommandTest.java

fixes concurrentmodificationexception when commands are scheduled/canceled from the execute body of other commands

fix ConcurrentModificationException in commandscheduler

---

wpilibc/src/main/native/include/frc2/command/ParallelCommandGroup.h
wpilibc/src/main/native/include/frc2/command/ParallelDeadlineGroup.h
wpilibc/src/main/native/include/frc2/command/ParallelRaceGroup.h
wpilibc/src/main/native/include/frc2/command/PerpetualCommand.h
wpilibc/src/main/native/include/frc2/command/SelectCommand.h
wpilibc/src/main/native/include/frc2/command/SequentialCommandGroup.h

Passing command groups as lvalue-references to other command groups should be illegal, as their copy constructors have been deleted.  However, copy constructors are const-qualified.  This led to a very obscure bug where passing a command group by lvalue to another command group would result in a valid template expansion 'looking like' a copy constructor, and being *preferred* to the deleted copy constructor.  This would result in constructor recursion (the expanded constructor would, in an attempt to call the copy constructor, call itself), and an eventual segfault when the stack inevitably overflowed.
This fixes the problem by explicitly deleting the problematic constructor signature - attempting to do this now (correctly) generates a compilation error.

Fix recursive constructor bug

---

wpilibc/src/main/native/include/frc/kinematics/DifferentialDriveOdometry.h
wpilibc/src/main/native/include/frc/kinematics/MecanumDriveOdometry.h
wpilibc/src/main/native/include/frc/kinematics/SwerveDriveOdometry.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometry.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/MecanumDriveOdometry.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveOdometry.java

Previously, the only way to get the updated robot pose was by storing the return value of `update`. This PR makes it possible to get the current pose without needing to call `update` with new information.

Add getters for pose in odometry classes

---

wpilibc/src/main/native/cpp/trajectory/TrajectoryGenerator.cpp
wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java

Per @Oblarg's request, I added an overload for the `generateTrajectory` method that accepts a `DifferentialDriveKinematics` instance instead of a list of constraints. This instance is used to automatically create a `DifferentialDriveKinematicsConstraint` behind the scenes, saving the user some verbosity.

Add generateTrajectory overload

---

cmake/modules/GenResources.cmake

This is only important for projects that reference this repo as a submodule.

Fix GenResources.cmake so it's usable in a submodule

---

wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp
wpilibc/src/main/native/cpp/GenericHID.cpp
wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/cpp/buttons/Trigger.cpp
wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableChooserBase.cpp
wpilibc/src/main/native/include/frc/GenericHID.h
wpilibc/src/main/native/include/frc/NidecBrushless.h
wpilibc/src/main/native/include/frc/PIDBase.h
wpilibc/src/main/native/include/frc/PIDController.h
wpilibc/src/main/native/include/frc/Resource.h
wpilibc/src/main/native/include/frc/Timer.h
wpilibc/src/main/native/include/frc/buttons/Trigger.h
wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibc/src/main/native/include/frc/drive/KilloughDrive.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooserBase.h

These were incorrect and exhibited as warnings on more recent versions of
clang (notably on Mac).
- Use pointers instead of references internally in GenericHID and *Drive
- Leave PIDBase, PIDController, and Resource non-moveable
- Remove the atomic from m_disabled in NidecBrushless
- Make Timer and Trigger copyable as well as moveable
- Implement custom move constructor/assignment for SendableChooserBase
Also comment out some unused variables that caused clang warnings.

Fix implicitly deleted move constructors

---

wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java

This utility function is made public in both the Java and C++ libraries. This utility function allows a user to turn an array of splines (generated individually perhaps), into the splinePoints needed to time parameterize.
The real world use case is my current work on Pathweaver, where I generate each spline separately for display, and then time parameterize them at the end when exporting.

Make splinePointsFromSplines public

---

hal/src/main/native/sim/mockdata/SimDeviceData.cpp
imgui/CMakeLists.txt
imgui/CMakeLists.txt.in
shared/config.gradle
simulation/halsim_gui/src/main/native/cpp/CompressorGui.cpp
simulation/halsim_gui/src/main/native/cpp/DIOGui.cpp
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
simulation/halsim_gui/src/main/native/cpp/EncoderGui.cpp
simulation/halsim_gui/src/main/native/cpp/ExtraGuiWidgets.cpp
simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp
simulation/halsim_gui/src/main/native/cpp/PDPGui.cpp
simulation/halsim_gui/src/main/native/cpp/PWMGui.cpp
simulation/halsim_gui/src/main/native/cpp/RelayGui.cpp
simulation/halsim_gui/src/main/native/cpp/RoboRioGui.cpp
simulation/halsim_gui/src/main/native/cpp/SolenoidGui.cpp
simulation/halsim_gui/src/main/native/include/ExtraGuiWidgets.h
simulation/halsim_gui/src/main/native/include/HALSimGui.h

- Map gamepad the same way as DS
- Support high DPI monitors (fixes #1919)
- Handle low resolution monitors (fixes #1928)
- Disable outputs on DS disable (fixes #1927)

Various simulation GUI fixes

---

hal/src/main/native/athena/HAL.cpp
hal/src/main/native/include/hal/HALBase.h

Because of the DS changes we made, we cannot support this anymore. Therefore it can be removed.

Remove HAL Base Initialize

---

wpilibc/src/main/native/include/frc/PIDBase.h
wpilibc/src/main/native/include/frc/PIDInterface.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PIDInterface.java

PIDBase was only used by the old PIDController, which is deprecated.
PIDInterface is only used by PIDBase, and that's deprecated by this
commit.

Deprecate old PID classes

---

wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/cpp/frc2/Timer.cpp
wpilibc/src/main/native/include/frc/Timer.h
wpilibc/src/main/native/include/frc2/Timer.h
wpilibc/src/main/native/include/frc2/command/WaitCommand.h

Adds a wrapper for the Timer class in the frc2 namespace that uses correct unit types.

write frc2::Timer

---

wpilibc/src/main/native/cpp/spline/SplineHelper.cpp
wpilibc/src/main/native/cpp/trajectory/TrajectoryGenerator.cpp
wpilibc/src/main/native/cpp/trajectory/TrajectoryParameterizer.cpp
wpilibc/src/main/native/include/frc/spline/Spline.h
wpilibc/src/main/native/include/frc/spline/SplineHelper.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryConfig.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryParameterizer.h
wpilibc/src/test/native/cpp/controller/RamseteControllerTest.cpp
wpilibc/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp
wpilibc/src/test/native/cpp/spline/QuinticHermiteSplineTest.cpp
wpilibc/src/test/native/cpp/trajectory/CentripetalAccelerationConstraintTest.cpp
wpilibc/src/test/native/cpp/trajectory/DifferentialDriveKinematicsTest.cpp
wpilibc/src/test/native/cpp/trajectory/TrajectoryGeneratorTest.cpp
wpilibc/src/test/native/include/trajectory/TestTrajectory.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/Spline.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineHelper.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryConfig.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/RamseteControllerTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/spline/CubicHermiteSplineTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/spline/QuinticHermiteSplineTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGeneratorTest.java

After discussion, for easiest integration with Pathweaver, I have split up the constraints and other config stuff into a separate Config class. Furthermore, `TrajectoryGenerator` now supports passing in control vectors for the splines (since Pathweaver has the ability to control this).

TrajectoryGenerator Refactor

---

buildSrc/build.gradle
shared/config.gradle
shared/opencv.gradle

OpenCV doesn't change anything other then the hash file. NativeUtils is needed to get the newest compiler

Bump Native Utils and OpenCV dependencies

---

cameraserver/src/main/native/cpp/cameraserver/CameraServerShared.cpp
cameraserver/src/main/native/include/cameraserver/CameraServerShared.h
wpilibc/CMakeLists.txt
wpilibc/build.gradle
wpilibc/src/main/native/cpp/shuffleboard/SendableCameraWrapper.cpp
wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardContainer.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/shuffleboard/SendableCameraWrapper.h
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardContainer.h
wpiutil/src/main/native/windows/StackWalker.cpp

Will help make linking easier, and there is VERY little that uses it. One piece of shuffleboard functionality is missing. However I might solve that by making it entirely header only. Will hurt compile times for that file, but thats OK.

Remove CameraServer and CS Core from wpilibc

---

wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/Command.java

Changes `Command` decorators to return actual implementation classes rather than `Command`s.  Previously, decorated commands were not `Sendable`, which was a problem.  Also, there's no real reason not to expose the implementation details here, as we're extremely unlikely to change the implementations in the future.

make decorators return implementing classes

---

wpilibc/src/main/native/cpp/SpeedController.cpp
wpilibc/src/main/native/include/frc/SpeedController.h
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/subsystems/ShooterSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/subsystems/DriveSubsystem.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/SpeedController.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/subsystems/ShooterSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java

Adds a voltage-compensated `setVoltage` method to `SpeedController`, which is sorely needed to help teams use feedforward-based controls effectively.  Also uses correct units on the cpp side.

add setVoltage method to SpeedController, update relevant examples

---

wpilibc/src/main/native/cpp/frc2/command/PIDCommand.cpp
wpilibc/src/main/native/cpp/frc2/command/ProfiledPIDCommand.cpp
wpilibc/src/main/native/include/frc2/command/PIDCommand.h
wpilibc/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/PIDCommand.java
wpilibj/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDCommand.java

Assorted clean-ups for pidcommands.  Wrapper methods are no longer needed now that PIDController does not take the lambdas as parameters.

Clean up pidcommand

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp

Java has a null check that was missing in C++ when adding default commands.

Fix null pointer dereference in C++ CommandScheduler

---

hal/src/main/native/athena/AnalogTrigger.cpp

They can't be caught from user code

Don't allow rising and falling values to be read from AnalogTrigger

---

wpilibOldCommands/src/main/native/include/frc/commands/Command.h

These used to be effectively public due to SendableBase, and are public
in the Java version.

Old C++ Command: Make GetName et al public

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cpp/IterativeRobot.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/IterativeRobot.h
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibc/src/main/native/include/frc/TimedRobot.h
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/include/Robot.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobot.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/robotbaseskeleton/Robot.java

This is useful for both cleanly exiting from simulation and for unit testing
at a framework level.

Add ability to end startCompetition() main loop

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/NotifierCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/NotifierCommandTest.cpp

They don't need to be testing timing, just that the command starts and stops

Switch notifier command tests to be a lot more lenient.

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Button.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/FunctionalCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Button.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/FunctionalCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/InstantCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/NotifierCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/PIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RunCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/StartEndCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Button.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

Assorted improvements to the ergonomics of declaring requirements in the new command framework.  C++ requirements list parameters have been defaulted to an empty list, some missing C++ requirements list parameters have been added, and both C++ and Java have been given requirements list params in various `InstantCommand` wrapper methods (https://github.com/wpilibsuite/allwpilib/issues/2049), whose value is forwarded to the command.

Improve requirements APIs

---

wpilibc/src/main/native/cpp/DMC60.cpp
wpilibc/src/main/native/cpp/Jaguar.cpp
wpilibc/src/main/native/cpp/PWMSparkMax.cpp
wpilibc/src/main/native/cpp/PWMTalonSRX.cpp
wpilibc/src/main/native/cpp/PWMVictorSPX.cpp
wpilibc/src/main/native/cpp/SD540.cpp
wpilibc/src/main/native/cpp/Spark.cpp
wpilibc/src/main/native/cpp/Talon.cpp
wpilibc/src/main/native/cpp/Victor.cpp
wpilibc/src/main/native/cpp/VictorSP.cpp
wpilibc/src/main/native/include/frc/DMC60.h
wpilibc/src/main/native/include/frc/Jaguar.h
wpilibc/src/main/native/include/frc/PWMSparkMax.h
wpilibc/src/main/native/include/frc/PWMTalonSRX.h
wpilibc/src/main/native/include/frc/PWMVictorSPX.h
wpilibc/src/main/native/include/frc/SD540.h
wpilibc/src/main/native/include/frc/Spark.h
wpilibc/src/main/native/include/frc/Talon.h
wpilibc/src/main/native/include/frc/Victor.h
wpilibc/src/main/native/include/frc/VictorSP.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DMC60.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Jaguar.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMSparkMax.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMTalonSRX.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWMVictorSPX.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/SD540.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Spark.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Talon.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Victor.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/VictorSP.java

Some were in constructor docs, some in init function docs, and some
inline in code. Move them all to class docs and improve formatting

Standardize documentation of Speed Controllers bounds.

---

hal/src/generate/FRCUsageReporting.h.in

This changes the C++ HALUsageReporting enums to have an
explicit type which matches the HAL_Report parameter
types.  In practice this shouldn't change much except
for tooling that might be parsing this header.

Make usage reporting enums type match

---

hal/src/main/java/edu/wpi/first/hal/NotifierJNI.java
hal/src/main/java/edu/wpi/first/hal/sim/NotifierSim.java
hal/src/main/java/edu/wpi/first/hal/sim/SimHooks.java
hal/src/main/java/edu/wpi/first/hal/sim/mockdata/NotifierDataJNI.java
hal/src/main/java/edu/wpi/first/hal/sim/mockdata/SimulatorJNI.java
hal/src/main/native/athena/Notifier.cpp
hal/src/main/native/cpp/jni/NotifierJNI.cpp
hal/src/main/native/include/hal/Notifier.h
hal/src/main/native/include/mockdata/MockHooks.h
hal/src/main/native/include/mockdata/NotifierData.h
hal/src/main/native/sim/MockHooks.cpp
hal/src/main/native/sim/Notifier.cpp
hal/src/main/native/sim/NotifierInternal.h
hal/src/main/native/sim/jni/NotifierDataJNI.cpp
hal/src/main/native/sim/jni/SimulatorJNI.cpp
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
simulation/halsim_gui/src/main/native/cpp/TimingGui.cpp
simulation/halsim_gui/src/main/native/cpp/TimingGui.h
simulation/halsim_gui/src/main/native/cpp/main.cpp
wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibc/src/main/native/include/frc/Notifier.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java

Calling HALSIM_PauseTiming pauses the FPGA clock and notifiers.
Calling HALSIM_ResumeTiming resumes the FPGA clock and notifiers.
Calling HALSIM_StepTiming steps the FPGA clock and runs applicable notifiers.
This will effectively pause TimedRobot and any other notifier-based events,
but of course will not pause user threads that do not use the notifier (e.g.
image processing).
The GUI also pauses DS new data notifications when paused.  This could be
done globally instead by blocking NotifyNewData at the HAL level?
Notifiers can now be named and appear in the simulation GUI.  A "Timing"
window has been added to the GUI to access this functionality.

Add simulation pause/step/resume support

---

wpilibc/src/main/native/cpp/kinematics/DifferentialDriveOdometry.cpp
wpilibc/src/main/native/cpp/kinematics/MecanumDriveOdometry.cpp
wpilibc/src/main/native/include/frc/kinematics/DifferentialDriveOdometry.h
wpilibc/src/main/native/include/frc/kinematics/MecanumDriveOdometry.h
wpilibc/src/main/native/include/frc/kinematics/SwerveDriveOdometry.h
wpilibc/src/main/native/include/frc/kinematics/SwerveDriveOdometry.inc
wpilibc/src/test/native/cpp/kinematics/DifferentialDriveOdometryTest.cpp
wpilibc/src/test/native/cpp/kinematics/MecanumDriveOdometryTest.cpp
wpilibc/src/test/native/cpp/kinematics/SwerveDriveOdometryTest.cpp
wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/include/Drivetrain.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometry.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/MecanumDriveOdometry.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveOdometry.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometryTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/kinematics/MecanumDriveOdometryTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/kinematics/SwerveDriveOdometryTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java

The odometry classes previously took in the robot angle as an argument, meaning that users had to take care of offsetting the gyro themselves to accurately report the robot angle. This change will make it so that users will not have to worry about resetting gyros and adding offsets themselves, as this will be handled by the odometry classes.
This directly addresses artf5920 from the beta testing bug tracker.

Use gyro angle instead of robot angle for odometry

---

hal/src/main/native/athena/AddressableLED.cpp
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/include/hal/Errors.h
hal/src/main/native/sim/AddressableLED.cpp
hal/src/main/native/sim/HAL.cpp

Only PWM Headers are supported, so enforce that.
Also fixes a bit of init checks and init order checks

Updates to addressable LED

---

wpilibc/src/main/native/cpp/kinematics/DifferentialDriveOdometry.cpp
wpilibc/src/main/native/include/frc/kinematics/DifferentialDriveOdometry.h
wpilibc/src/test/native/cpp/kinematics/DifferentialDriveOdometryTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometry.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometryTest.java

After discussion with @Oblarg, we decided it would be best to add another overload to DifferentialDriveOdometry which would take in encoder distances instead of velocities. This will benefit teams who are using lower CPR encoders and is mathematically more robust.

Add encoder distance overload to DifferentialDriveOdometry

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileSubsystem.java
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h

Adds a subsystem that continually runs a TrapezoidProfile, for composition with offboard PID controllers.

add TrapezoidProfileSubsystem

---

wpilibc/src/main/native/cpp/AddressableLED.cpp
wpilibc/src/main/native/include/frc/AddressableLED.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLED.java

The PWM object really shouldn't be used anymore.

Directly construct PWM port from HAL, avoid wpilib PWM object

---

wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h

`typename` specifier was missing on some dependent template declarations

fix missing typename

---

wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp
wpilibc/src/main/native/include/frc/controller/ArmFeedforward.h
wpilibc/src/main/native/include/frc/controller/ElevatorFeedforward.h
wpilibc/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
wpilibc/src/main/native/include/frc/kinematics/DifferentialDriveKinematics.h
wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveVoltageConstraint.h
wpilibc/src/test/native/cpp/trajectory/DifferentialDriveVoltageTest.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ArmFeedforward.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ElevatorFeedforward.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/SimpleMotorFeedforward.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveKinematics.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/DifferentialDriveKinematicsConstraint.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/DifferentialDriveVoltageConstraint.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/DifferentialDriveVoltageConstraintTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java

Adds a constraint that ensures that a trajectory never accelerates faster than a differential drive is capable of achieving given a max voltage and a set of drive characterization parameters.

Add differentialdrive voltage constraint

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDSubsystem.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDSubsystem.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileSubsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/PIDSubsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/PIDSubsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h
wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/subsystems/ArmSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/ArmBot/include/subsystems/ArmSubsystem.h
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/subsystems/ShooterSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/subsystems/ShooterSubsystem.h
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Elevator.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Wrist.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Elevator.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Wrist.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/subsystems/ArmSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/subsystems/ShooterSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Elevator.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Wrist.java

Improves the APIs for various prebuilt subsystems (`PIDSubsystem`, `TrapezoidProfileSubsystem`, `ProfiledPIDSubsystem`).  Addresses https://github.com/wpilibsuite/allwpilib/issues/2128, and also changes the rather cumbersome `getSetpoint` API to a more intuitive `setSetpoint` one.  Updates examples to match.

update subsystem APIs

---

wpilibc/src/main/native/cpp/smartdashboard/SendableRegistry.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableRegistry.java

Copy the internal map values into an array before iterating.
In C++, change to recursive mutex as well.

SendableRegistry.foreachLiveWindow: Prevent concurrent modification

---

wpilibc/src/main/native/include/frc/LinearFilter.h

They are initialized in LinearFilter's constructor, so the default is
never used.

Remove unnecessary constructor arg for LinearFilter's circular buffers

---

wpilibc/src/main/native/cpp/kinematics/DifferentialDriveOdometry.cpp
wpilibc/src/main/native/include/frc/kinematics/DifferentialDriveOdometry.h
wpilibc/src/test/native/cpp/kinematics/DifferentialDriveOdometryTest.cpp
wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometry.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometryTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java

It doesn't make sense to continue to provide a less accurate method of performing odometry when a more accurate method using distances exists.

Remove encoder velocities method in DifferentialDriveOdometry

---

wpilibj/build.gradle

This commit should like the wpiutilJNIShared library to wpilibj.

Fix jni shared linkage typo in wpilibj

---

simulation/halsim_gui/src/main/native/cpp/AddressableLEDGui.cpp
simulation/halsim_gui/src/main/native/cpp/ExtraGuiWidgets.cpp
simulation/halsim_gui/src/main/native/include/ExtraGuiWidgets.h

LED displays connect the LEDs in various ways (column major vs row major,
different starting locations, serpentine connection order), so add
configuration parameters for these options.

Sim GUI: Add support for LED displays

---

wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h

Fixes assorted bugs with the TrapezoidProfile templating and its interaction with the command framework, including a two-phase name lookup issue and several typos/oversights.

Fix up templated trapezoidprofile classes

---

myRobot/build.gradle

```
<ij_msg_gr>Gradle import errors<ij_msg_gr><ij_nav>/Users/austinshalit/git/allwpilib/myRobot/build.gradle<ij_nav><i><b>project ':myRobot': Unable to build Kotlin project configuration</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task ':myRobot:deployJava'.<eol>Caused by: org.gradle.api.UnknownTaskException: Task with name 'deployMyRobotCppLibrariesRoborio' not found in project ':myRobot'.</i>
<ij_msg_gr>Project resolve errors<ij_msg_gr><ij_nav>/Users/austinshalit/git/allwpilib/build.gradle<ij_nav><i><b>root project 'allwpilib': Unable to resolve additional project configuration.</b><eol>Details: org.gradle.api.internal.tasks.DefaultTaskContainer$TaskCreationException: Could not create task …
```

Try catch around task dependancies

---

hal/src/main/native/include/hal/Extensions.h
hal/src/main/native/sim/Extensions.cpp

We want it enabled by default, but I've gotten some requests on a way to disable it.

Add way to disable print no extensions found message

---

hal/src/main/native/athena/AnalogInput.cpp

It is a mutex and a lookup, so avoiding it does help

Hardcode channels for LSB weight to avoid channel lookup

---

hal/src/main/native/athena/DMA.cpp
wpilibc/src/main/native/include/frc/DMASample.h

The former is deprecated in C++20.

Replace std::is_pod_v with std::is_standard_layout_v

---

hal/src/main/native/athena/SPI.cpp

With the addition of stall configuration, its not very clear how it works, and seems like it would be different
per use. So adding ways to manually get them, so the functionality can be figured out how to be used.

Add hidden functions to get the SPI system and SPI DMA

---

wpilibc/src/main/native/include/frc/WPILib.h

Now that commands and cameraserver libraries are no longer direct dependencies,
it's necessary to check for their presence.

Use __has_include for WPILib.h

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/SwerveDriveKinematicsConstraint.java

Fix a javadoc in SwerveDriveKinematicsConstraint that says 
> Constructs a mecanum drive dynamics constraint.

Fix javadoc in SwerveDriveKinematicsConstraint.

---

cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp

Closes #1666 
On Windows, as soon as Main ends, you cannot access any libraries, and all threads are dead. This causes USB Cameras on windows to crash hard on shutdown.

Use ManagedStatic for CameraServer

---

wpilibc/src/main/native/include/frc/trajectory/Trajectory.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/Trajectory.java

This is useful for teams who want to reset their odometry to the initial pose of the trajectory before traversing it.
Example usage:
`m_odometry.resetPose(trajectory.getInitialPose()` or `m_odometry.ResetPose(trajectory.InitialPose())`

Add getter for initial pose in Trajectory

---

docs/build.gradle

Remove -no-module-directories flag from javadoc build

---

hal/src/main/java/edu/wpi/first/hal/sim/DriverStationSim.java
hal/src/main/java/edu/wpi/first/hal/sim/mockdata/DriverStationDataJNI.java
hal/src/main/native/sim/jni/DriverStationDataJNI.cpp

This is to allow suppressing an ugly stack trace/error message in a unit test in #2197. It doesn't support the full `HALSIM_SetSendError` callback stuff (i.e. you can only suppress, not intercept, stack traces with this), because that was all I needed.

Add JNI binding to suppress driver station error/warning messages

---

wpiutil/CMakeLists.txt

Can't use find(Python3) as it requires cmake 3.12 or later.

Fail cmake build if python3 generate_numbers.py fails

---

wpilibc/src/main/native/include/frc/SlewRateLimiter.h
wpilibc/src/test/native/cpp/SlewRateLimiterTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/SlewRateLimiter.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/SlewRateLimiterTest.java

Adds a `SlewRateLimiter` class, which is extremely useful for implementing various "ramping" functions (such as voltage ramps, setpoint ramps, etc).  Usage is straightforward; it behaves like all of our other filter classes.  C++ version is unit-safe.

write SlewRateLimiter class

---

ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableInstance.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTablesJNI.java
ntcore/src/main/native/cpp/Dispatcher.cpp
ntcore/src/main/native/cpp/Dispatcher.h
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.inl
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

StartLocal() causes future calls to StartServer() or StartClient() to have
no effect.  StopLocal() re-enables these calls.

ntcore: Add support for local-only operation

---

wpilibc/src/main/native/cpp/smartdashboard/SendableRegistry.cpp
wpilibc/src/main/native/include/frc/smartdashboard/SendableRegistry.h

Add a Sendable* overload so pointers to sendable objects work appropriately.
Otherwise an AddLW(this) in a child (which is a Sendable*) could be a
different pointer than a void* to the same object.
For example:
AnalogInput constructor calls AddLW(this)
AnalogPotentiometer constructor calls AddChild(analog input pointer)
Also add handling for the child object moving (if it's Sendable).

Fix C++ SendableRegistry::AddChild()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDSubsystem.java
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/ProfiledPIDControllerTest.java

Currently, the profiled PID Controller's m_setpoint starts at (0,0). This changes the reset() method to set m_setpoint to the current state of the system.

Fix trapezoidal profile PID controller setpoint bug

---

wpilibc/src/main/native/cpp/trajectory/TrajectoryGenerator.cpp
wpilibc/src/main/native/include/frc/spline/SplineParameterizer.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpilibc/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp
wpilibc/src/test/native/cpp/spline/QuinticHermiteSplineTest.cpp
wpilibc/src/test/native/cpp/trajectory/TrajectoryGeneratorTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/spline/SplineParameterizer.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/spline/CubicHermiteSplineTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/spline/QuinticHermiteSplineTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGeneratorTest.java

This PR changes the spline parameterizer to use an explicit stack instead of recursion. This is motivated by the fact that splines with adjacent waypoints with approximately opposite headings will never parameterize. In this case the parameterizer subdivides these malformed splines fine for a while, and then gets stuck parameterizing infinitely on some interval. In the recursive approach, this would lead to a stack overflow. We could implement a recursion depth counter (this is what my team did on our similar trajectory code last season), but it's hard to choose a good number for max depth because the initial amount of stack used varies based on how the user calls `Parameterize`.
A good solution for this is converting the recursion to an "explicit stack," which basically simulates …

Use an explicit stack instead of recursion when parameterizing splines

---

wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandBase.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/FunctionalCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/InstantCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/MecanumControllerCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/NotifierCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/PIDCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RunCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/StartEndCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Button.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandBase.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/main/native/include/frc2/command/FunctionalCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/InstantCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/MecanumControllerCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/NotifierCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/PIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RamseteCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RunCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/StartEndCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Button.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

Also default requirements to {} in all cases for consistency.
Fixes #2215.

Add ArrayRef overloads to new command classes

---

docs/build.gradle

This reverts commit f9a11cce5e08512749459cc0578e4a3d95413236.
Supersedes #2227.

Revert "Remove -no-module-directories flag from javadoc build (#2201)"

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java

This is needed to avoid use of DriverStation if used from desktop applications
such as PathWeaver.

TrajectoryGenerator: Allow replacement of error reporting function

---

cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/linux/UsbCameraImpl.h

- Valid video modes (native modes plus some low-res modes)
- Exposure setting

Add quirks support for Pi camera

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/ScheduleCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulerTest.cpp

When called outside the run loop, it would result in a CME in Java.

Fix new CommandScheduler.cancelAll()

---

simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp

This should never happen, but if it does, it's not recoverable without
either deleting imgui.ini or editing it manually.

Simulator GUI: Handle save file having window size=0

---

wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/JoystickButton.h
wpilibNewCommands/src/main/native/include/frc2/command/button/POVButton.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

C++ `JoystickButton` and `POVButton` were both nonfunctional due to slicing when trigger passes itself by value to the button scheduler it creates.
Fix is to remove the virtual `Get()` method entirely and use only the `m_isActive` functor; since the subclass now passes the button condition back as a functor to the base class, in which it's stored as a member, it will now still work after being sliced.
Still no test coverage, because I don't see how to fake `GenericHID` in any reasonable manner since none of the methods are virtual.

fix joystickbutton in cpp

---

wpilibc/src/main/native/include/frc/util/Color.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java

This is entirely unimportant but I was reading the docs and it bugged me.

Fixing color name typos

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/util/ColorTest.java

Colors were being initialized before `kPrecision` was 😢

Fix static colors having zero values & add test

---

wpilibc/src/main/native/include/frc/AnalogTrigger.h

Closes #2232 
Method wasn't implemented, and is incorrect to have.

Remove AnalogTrigger::SetDutyCycle

---

wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp

Fix LiveWindow SetEnabled C++ std::bad_function_call

---

simulation/halsim_gui/src/main/native/cpp/AnalogInputGui.cpp
simulation/halsim_gui/src/main/native/cpp/AnalogOutGui.cpp
simulation/halsim_gui/src/main/native/cpp/DIOGui.cpp
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
simulation/halsim_gui/src/main/native/cpp/EncoderGui.cpp
simulation/halsim_gui/src/main/native/cpp/IniSaverInfo.cpp
simulation/halsim_gui/src/main/native/cpp/PDPGui.cpp
simulation/halsim_gui/src/main/native/cpp/PWMGui.cpp
simulation/halsim_gui/src/main/native/cpp/RelayGui.cpp
simulation/halsim_gui/src/main/native/cpp/SolenoidGui.cpp
simulation/halsim_gui/src/main/native/include/IniSaverInfo.h

This allows users to right click on just about any name in the GUI (e.g. "PWM[0]") and rename it (e.g. "Left Motor [0]").  The index portion is not editable.  The name is saved into imgui.ini so it's persistent.

Simulation GUI: Add support for setting user names

---

wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/SwerveModule.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/include/SwerveModule.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
wpiutil/src/main/native/include/units/units.h

see: https://www.chiefdelphi.com/t/bug-or-misunderstanding-in-trajectory-tutorial-and-ramsete-example/373989/9?u=oblarg
Adds feedforward to the drive controls and filters joystick inputs with slew rate limiters (not strictly necessary but a very good idea for closed-loop teleop control).

Fix advanced drive examples

---

wpiutil/src/main/java/edu/wpi/first/wpiutil/RuntimeLoader.java

Should specify the C++ runtime is needed, along with making it easier to troubleshoot and to not lose information

Add more error handling messages to RuntimeLoader failures

---

hal/CMakeLists.txt

Previously the cmake for hal would install the entire `gen` folder into `wpilib\include\hal`, but now it will correctly copy only the contents. See [this SO answer](https://stackoverflow.com/a/23766303) for details.
For example
`wpilib\include\hal\gen\hal\FRCUsageReporting.h`
now becomes
`wpilib\include\hal\hal\FRCUsageReporting.h`

Fix hal cmake generated code install

---

wpilibc/src/main/native/cpp/ADXL345_I2C.cpp
wpilibc/src/main/native/cpp/ADXL345_SPI.cpp
wpilibc/src/main/native/cpp/ADXL362.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_I2C.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_SPI.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL362.java

- Sets `m_simY` to the virtual Y acceleration
Kudos to @SHU-matic for finding this.

Fix typo in ADXL sim double creations

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WaitCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/MecanumControllerCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/WaitCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibc/src/main/native/cpp/frc2/Timer.cpp
wpilibc/src/main/native/include/frc2/Timer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java

Fixes https://github.com/wpilibsuite/allwpilib/issues/2321

deprecate footgun method of timer

---

CMakeLists.txt
README-CMAKE.md
cscore/CMakeLists.txt

[In this issue](https://github.com/wpilibsuite/allwpilib/issues/2346#issue-561356044), the CMake build system's OpenCV Java bindings detection was shown to be flawed. On several Linux distributions, the location of the .jar file with the Java-level bindings is not located, including Arch Linux and Fedora. Since it is not possible to account for every possible system's configuration, this pull request enables the searched location to be manually set. The actual name of the .jar file cannot be configured as of now, but on all systems that I've seen it has the currently detected name. If changing it is necessary it would be possible to symlink from a directory in one's home to the correct file, and set the location there.

Improved the portability of OpenCV Java bindings detection when using CMake.

---

wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp
wpilibc/src/test/native/cpp/trajectory/DifferentialDriveVoltageTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/constraint/DifferentialDriveVoltageConstraint.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/trajectory/DifferentialDriveVoltageConstraintTest.java

fix diffdrive voltage constraint on tight turns w/ zero velocity

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java

What would happen is the Stop() call would happen between the notifier loop being triggered and calling UpdateAlarm(). This would cause the Update to overwrite the stop.
Closes #2368

Fix notifier race happening with very fast notifiers

---

hal/src/main/java/edu/wpi/first/hal/HAL.java
hal/src/main/java/edu/wpi/first/hal/sim/mockdata/DriverStationDataJNI.java
hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/cpp/jni/HAL.cpp
hal/src/main/native/include/hal/DriverStation.h
hal/src/main/native/include/mockdata/MockHooks.h
hal/src/main/native/sim/DriverStation.cpp
hal/src/main/native/sim/jni/DriverStationDataJNI.cpp

This can be use to synchronize writes between threads, assuming writes all go through this and not stdout

Expose netcomm SendConsoleLine over the HAL

---

wpiutil/src/main/native/include/units/units.h

A typedef for units::dimensionless::dimensionless is defined, which
conflicted with the namespace when we added "using namespace
dimensionless". This patch reverts the "using namespace" directive.
"using" directives were added to pull three of the four relevant
typedefs but avoid the "dimensionless" type conflict.
This issue was first introduced in #2301.

Fix "'dimensionless' ambiguous symbol" error

---

wpilibc/src/main/native/cpp/geometry/Transform2d.cpp
wpilibc/src/main/native/include/frc/geometry/Transform2d.h
wpilibc/src/test/native/cpp/geometry/Transform2dTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/geometry/Transform2d.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/geometry/Transform2dTest.java

This is useful for undoing transformations. One application my FRC team
found was converting perspective n-point data from a "camera to target"
coordinate frame transformation to a "target to camera" coordinate frame
transformation.

Add Transform2d::Inverse()

---

hal/src/main/native/athena/HAL.cpp

It reports the correct value now, and helps for future proofing.

Use netcomm function to get target class rather then hardcoded

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardContainer.cpp
wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardLayout.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ContainerHelper.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardLayout.java

In a few of the Shuffleboard classes, there was a mix up of title/name and type parameters. To stay consistent, I decided to rename the "name" parameter to "title". Unless people were directly using some of the classes I modified, this will not affect how the API is used at all. The things I changed in Java are all package private and the only benefit to this PR is to avoid future confusion when editing these. 
In ContainerHelper.java or ShuffleboardContainer.cpp, it was passing the title and type parameters backwards. However, because ShuffleboardLayout passed the values backwards too, no harm was done. The same thing applies to the C++ version. There is unit test coverage to verify that the code is correct. 
This is kind of hard to follow and the parameters needed to be named correctly.

Fixed mix up of title and type parameters in some Shuffleboard classes

---

wpilibc/src/main/native/cpp/controller/PIDController.cpp
wpilibc/src/main/native/include/frc/controller/ControllerUtil.h
wpilibc/src/main/native/include/frc/controller/PIDController.h
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h
wpilibc/src/test/native/cpp/controller/ControllerUtilTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ControllerUtil.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/ControllerUtilTest.java

Previously, it could take the long way around. This recomputes the
profile goal with the shortest error, thus taking the shortest path.
Also removed the setpoint clamping from PIDController::SetSetpoint()
because it's unnecessary to make PIDController behave correctly for
a modular arithmetic input, and it breaks the setpoint calculation in
ProfiledPIDController otherwise.
Fixes #2277.

Fix ProfiledPIDController profile direction for continuous input

---

wpilibc/src/main/native/cpp/Watchdog.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java

This was caused by m_epochs storing the timestamps as nanoseconds while
the epoch printing code expects microseconds. Adding a duration cast
fixes this.
Java stores the epoch timestamps in a double as microseconds, so it
doesn't exhibit this bug. The comments were updated to make this more
obvious.
Fixes #2392.

Fix Watchdog epoch prints being off by three orders of magnitude

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

DriverStation's getStickButtonPressed and getStickButtonReleased is public in WPILibC but not in WPILibJ.
This pull request makes them public.

Improve parity between wpilibc and wpilibj in DriverStation

---

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibc/src/main/native/include/frc/DutyCycleEncoder.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java

The DutyCycleEncoder class initializes `AnalogTrigger` even while using `simulateJava`. When initializing `AnalogTrigger` an exception is thrown as described here: https://github.com/wpilibsuite/allwpilib/issues/2367
This PR fixes the Java version by not using AnalogTrigger (or Counter) while simulating DutyCycleEncoder. I believe the CPP version also needs the same fix.

DutyCycleEncoder: Fix simulation support

---

wpilibc/src/main/native/cpp/trajectory/Trajectory.cpp
wpilibc/src/main/native/cpp/trajectory/constraint/CentripetalAccelerationConstraint.cpp
wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveKinematicsConstraint.cpp
wpilibc/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp
wpilibc/src/main/native/cpp/trajectory/constraint/MecanumDriveKinematicsConstraint.cpp
wpilibc/src/main/native/include/frc/spline/Spline.h
wpilibc/src/main/native/include/frc/spline/SplineParameterizer.h
wpilibc/src/main/native/include/frc/trajectory/Trajectory.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpilibc/src/main/native/include/frc/trajectory/TrajectoryParameterizer.h
wpilibc/src/main/native/include/frc/trajectory/constraint/CentripetalAccelerationConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveVoltageConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/MecanumDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.inc
wpilibc/src/main/native/include/frc/trajectory/constraint/TrajectoryConstraint.h
wpiutil/src/main/native/include/units/units.h

Closes #2335 
This is a breaking change; however, I do not think that many users would have used the `curvature_t` type in their robot projects.

Move curvature_t to units namespace

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java

New commands: add docs to end()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java

Lets the user see what commands and periodics cause an IterativeRobotBase loop overrun.
I have hardcoded a period of 0.02 sec because IterativeRobotBase.m_period and .m_watchdog is not visible.

Add watchdog and epoch reporting to CommandScheduler

---

hal/src/main/native/athena/Notifier.cpp

Will depend on a new image, but puts us in control of the thread that is used.

[hal] Use std::thread for Notifier thread on Rio

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandTestBase.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/ButtonTest.java

Also make CommandTestBase public to facilitate
As suggested here: https://github.com/wpilibsuite/allwpilib/pull/2373/files#r403770017

[wpilibj] Move button tests to button package

---

wpilibc/src/main/native/cpp/Tracer.cpp
wpilibc/src/main/native/include/frc/Tracer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Tracer.java

This matches the Java behavior.
Also optimizes Java to only create a StringBuffer and call
DriverStation.reportWarning if there is data to output.

[wpilibc] Output Tracer to DriverStation by default

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/include/frc/Notifier.h

Using this overload makes the thread backing the Notifier run at
real-time priority. This improves scheduling jitter substantially (5ms
+- 2ms down to 5ms +- 1ms).
A version isn't provided for Java because making threads real-time can
cause GC deadlocks.

[wpilibc] Add real-time priority constructor to Notifier

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogInput.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogOutput.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/BuiltInAccelerometer.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/sim/AnalogInputSimTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/sim/AnalogOutputSimTest.java

This approach to getting the simulation object doesn't work in C++ and
creates coupling that doesn't need to be present.

[wpilibj] Remove getSimObject

---

wpilibc/src/main/native/include/frc/trajectory/Trajectory.h

Valgrind caught this one. If you default initialize a Trajectory, it
doesn't initialize m_totalTime. This means a subsequent call to
Trajectory::TotalTime() returns the value of an uninitialized variable.
3512's software was using 0_s as a sentinel value for when a trajectory
was empty. We didn't notice a problem before because Linux zero-inits
memory.

[wpilibc] Fix uninitialized variable in Trajectory class

---

wpilibc/src/main/native/include/frc/trajectory/constraint/DifferentialDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/MecanumDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.h
wpilibc/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.inc

Apply doxygen comments to class instead of frc namespace
Correct references to differential drive

[wpilibc] Fix doxygen comments

---

wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/cpp/frc2/Timer.cpp
wpilibc/src/main/native/include/frc/Timer.h
wpilibc/src/main/native/include/frc2/Timer.h

If the 64 bit FPGA timer rolls over, a 32 bit value is added for the rollover, an artifact of when it was a 32 bit timer. The 64 bit microsecond timer won't rollover for 500k years so remove the check for simplicity.
Fixes #2504

[wpilibc] Remove incorrect timer rollover

---

wpilibc/src/main/native/cpp/trajectory/TrajectoryParameterizer.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryParameterizer.java

The most common mistake users (including contributors to WPILib) seem to make while creating new constraints is ignoring some sort of edge case that causes the calculated minimum acceleration to be greater than the calculated maximum acceleration.
This specialized exception, with its detailed error message, should make it easier and quicker for said users to debug and fix bugs within their constraints.

[wpilib] Throw separate exception for constraint misbehavior

---

hal/src/main/native/include/simulation/SimHooks.h

These are present in Java but were missed for C++.

[sim] Wrap timing functions in C++ SimHooks

---

hal/src/main/native/include/hal/handles/DigitalHandleResource.h
hal/src/main/native/include/hal/handles/IndexedClassedHandleResource.h
hal/src/main/native/include/hal/handles/IndexedHandleResource.h
hal/src/main/native/include/hal/handles/LimitedClassedHandleResource.h
hal/src/main/native/include/hal/handles/LimitedHandleResource.h
hal/src/main/native/include/hal/handles/UnlimitedHandleResource.h

This provides a lock-free way to get just the handle index.

[hal] Add GetIndex() to handles classes

---

hal/src/main/java/edu/wpi/first/hal/sim/SimHooks.java
hal/src/main/java/edu/wpi/first/hal/sim/mockdata/SimulatorJNI.java
hal/src/main/native/include/mockdata/MockHooks.h
hal/src/main/native/include/simulation/SimHooks.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/sim/jni/SimulatorJNI.cpp

This is needed for extensions that effectively access real hardware and
want to disable the "simulation" parts of user code.

[sim] Provide method to set the runtime type

---

shared/jni/setupBuild.gradle
wpiutil/build.gradle
wpiutil/src/main/java/edu/wpi/first/wpiutil/CombinedRuntimeLoader.java

Allows us to extract a list of binaries that depend on each other, and load them successfully
It is correct that there is no implementation in wpiutil for the new native method. That is a requirement, because its needed to load the libraries, and we cant load the wpiutiljni native library since it depends on wpiutil. Instead we have a separate class that handles everything

[wpiutil] Add new combined native class loader

---

wpiutil/src/main/java/edu/wpi/first/wpiutil/CombinedRuntimeLoader.java

Bytedeco uses setDllDirectory as well, and we don't want to interfere with its loader.

[wpiutil] Restore existing dll directory when setting dll directory

---

cscore/build.gradle
shared/jni/publish.gradle

With the new extraction method, we would need to provide an opencv. However, all of our tools that use opencv use an alternate version of OpenCV, so that would interfere.
This adds an artifact where opencv is statically linked into cscore, but wpiutil is a shared dependency. This solves some shared state hacks, and the extraction works so much better, so its worth making this change to allow that

[cscore] Add new jnicvstatic artifact type

---

cscore/build.gradle
shared/jni/publish.gradle

The archive needed to be zip, additionally the library needed to statically link to cscore. All better now

[cscore] Fix jnicvstatic classifier

---

wpiutil/src/main/native/include/units/angular_acceleration.h
wpiutil/src/main/native/include/units/base.h
wpiutil/src/main/native/include/units/units.h
wpiutil/src/test/native/cpp/UnitsTest.cpp

We already have predefined linear acceleration units and angular
velocity units. This makes defining acceleration constraints for angular
trapezoid profiles more convenient.
No tests were added for this because the base unit conversions are
already tested. Angular acceleration just adds another time dimension.

[wpiutil] Add angular acceleration units

---

wpilibc/src/main/native/cpp/geometry/Rotation2d.cpp
wpilibc/src/main/native/include/frc/geometry/Rotation2d.h

There's already an implicit conversion for radian_t, but there's no
implicit conversion from degree_t to radian_t.

[wpilibc] Add implicit conversion from degree_t to Rotation2d

---

hal/src/main/java/edu/wpi/first/hal/simulation/SimDeviceDataJNI.java
hal/src/main/native/include/hal/simulation/SimDeviceData.h
hal/src/main/native/sim/jni/SimDeviceDataJNI.cpp
hal/src/main/native/sim/mockdata/SimDeviceData.cpp
hal/src/main/native/sim/mockdata/SimDeviceDataInternal.h
hal/src/test/native/cpp/mockdata/SimDeviceDataTests.cpp

This allows disabling/enabling SimDevices via prefix matching.  This can be
used to force devices that normally use SimDevice in simulation mode to
instead talk directly to the hardware as in normal operation.

[sim] Add support for disabling SimDevices

---

cscore/build.gradle
shared/jni/publish.gradle

The tools plugin won't include them in the binary, but it will be easy to look them up if I need them.
Also fixes a lib link that needed to be removed, it was useless anyway.

[build] Add PDBs to jnicvstatic archives

---

hal/src/main/native/sim/HAL.cpp

Previously, HAL_InitializeDriverStation would reset any callbacks set in
extensions during load.

[sim] Move HAL_LoadExtensions to end of HAL_Initialize

---

buildSrc/build.gradle
shared/config.gradle

By default, release projects do not include symbols in the new version. This updates that to work correctly now

[build] Update to latest native utils

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java

[wpilibj] Fix Gyro.getRotation2d() units bug

---

hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/include/hal/DriverStation.h
hal/src/main/native/sim/DriverStation.cpp
wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

These are essentially the same as the HAL versions, except they also account
for the caching / transition detection logic that occurs at the WPILib level.
This also changes IsNewControlData() to check for WPILib-level caching instead
of wrapping the HAL function.

[hal] Merge WaitForCachedData into WaitForDSData

---

hal/src/main/java/edu/wpi/first/hal/simulation/DriverStationDataJNI.java
hal/src/main/native/athena/mockdata/DriverStationData.cpp
hal/src/main/native/cpp/jni/simulation/DriverStationDataJNI.cpp
hal/src/main/native/include/hal/simulation/DriverStationData.h
hal/src/main/native/sim/mockdata/DriverStationData.cpp
hal/src/main/native/sim/mockdata/DriverStationDataInternal.h
wpilibc/src/main/native/include/frc/simulation/DriverStationSim.h
wpilibc/src/main/native/include/frc/simulation/GenericHIDSim.h
wpilibc/src/main/native/include/frc/simulation/JoystickSim.h
wpilibc/src/main/native/include/frc/simulation/XboxControllerSim.h
wpilibc/src/test/native/cpp/JoystickTest.cpp
wpilibc/src/test/native/cpp/XboxControllerTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DriverStationSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/GenericHIDSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/JoystickSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/XboxControllerSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/JoystickTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/XboxControllerTest.java

This adds joystick functions to DriverStationSim, and new GenericHIDSim,
JoystickSim, and XboxControllerSim classes.
The first commit should be merged separately (#2587).

[sim] Add joystick simulation support

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/MecanumControllerCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/SwerveControllerCommandTest.cpp

Currently, these two tests take several seconds to complete and fail
intermittently in Windows CI. This is caused by relying on wall clock
time.
Sampling the trajectory with wall clock time means the simulation must
run for several seconds to reach the end of the trajectory. Also, the
controller can become unstable when Windows CI experiences process
scheduling delays of several hundred milliseconds. Feedback controllers
don't cope well with large delays on systems with fast dynamics.
This patch uses the mocking functionality of frc::Timer to advance the
clock by 5ms at every timestep instead of using the wall clock time.
This has two benefits:
1. The tests complete much faster because the simulation can step
forward faster than real time.
2. The controller is more stable because the …

[command] Speed up MecanumControllerCommand and SwerveControllerCommand tests

---

wpilibc/src/main/native/cpp/Watchdog.cpp
wpilibc/src/main/native/include/frc/Watchdog.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java

This makes it follow simulation timing instead of wall clock time.

[wpilib] Change Watchdog to use HAL notifier

---

hal/src/main/native/sim/MockHooks.cpp
hal/src/main/native/sim/MockHooksInternal.h

This matches on-robot behavior for things like NetworkTables timestamps.

[sim] Map wpi::Now() to simulated FPGA time

---

wpimath/src/main/native/cpp/trajectory/constraint/DifferentialDriveKinematicsConstraint.cpp
wpimath/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp
wpimath/src/main/native/cpp/trajectory/constraint/MecanumDriveKinematicsConstraint.cpp
wpimath/src/main/native/include/frc/trajectory/constraint/DifferentialDriveKinematicsConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/DifferentialDriveVoltageConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/MecanumDriveKinematicsConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.inc

We can simply use const-references instead because all the methods that we calling on kinematics and feedforward objects in the constraints are marked as const and there's no need to copy them.

[wpimath] Remove unnecessary copying in constraints

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/robotbaseskeleton/Robot.java

Closes #1620
This avoids users having to call `IsOperatorControl() && IsEnabled()` to figure out if their robot is enabled and in the teleop state. The expression above involves calling two methods that each have their own lock.
These new methods should only involve locking one mutex, since only one call is made to `HAL_GetControlWord()`.

[wpilib] Add methods to check game and enabled state together

---

wpimath/generate_numbers.py

The generate_numbers.py script unconditionally generated its output,
which caused every cmake regen to result in a time-consuming rebuild of the
wpimath.jar and WPIMathJNI.
This changes the python script to check if an update is necessary before
writing fresh output.

[build] Don't unconditionally regenerate wpimath numbers

---

buildSrc/build.gradle
wpilibOldCommands/src/main/native/cpp/commands/Scheduler.cpp
wpiutil/src/main/native/cpp/json_serializer.h

The beta of macOS 11.0 Big Sur comes with AppleClang 12.0, which catches some more warnings with C++ code when building. Because `-Werror` is turned on, this inevitably leads to build failures. There were three main build failures that I've categorized below:
* `wpiutil` - `tautological-overlap-compare`
- The build log for this error can be found here: https://scans.gradle.com/s/omj24fccxybfg
- The fix was in this commit: https://github.com/wpilibsuite/allwpilib/commit/9cf79189fcd461d63844e500b01d3974ef06ab73
* `opencv` - `c11-extensions`
- The build log for this type of error can be found here: https://gradle.com/s/4bndkaxghnipk
- The fix was to compile with `Wno-error=c11-extensions` on macOS. I had to add this everywhere that OpenCV headers were included.
* `wpilibOldCommands` - …

[build] Fix Gradle build on macOS 11.0 Big Sur

---

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/KalmanFilter.java
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h

I didn't notice a performance difference between the original
implementation and this one for a flywheel simulation, so this
simplifies a lot of internals.
This class can no longer implement KalmanTypeFilter because that class
allows setting the error covariance for use in the
KalmanFilterLatencyCompensator class. This won't impact the holonomic pose
estimators that use KalmanFilterLatencyCompensator because they all use an EKF.

[wpimath] Refactor KalmanFilter to be steady-state only

---

hal/src/main/native/include/hal/simulation/NotifyListener.h
hal/src/main/native/include/hal/simulation/SimDataValue.h

The uid was getting incremented by 1 during registration but not decremented
by 1 during cancellation, so cancellation didn't work correctly.
As the underlying registration ensures a non-zero result, don't increment
the result.

[sim] SimDataValue: Fix cancellation

---

wpimath/src/main/java/edu/wpi/first/wpiutil/math/Matrix.java
wpimath/src/main/java/edu/wpi/first/wpiutil/math/Vector.java

This will allow `Vector.times(double)` to return another `Vector`, helpful for scaling Q and R vectors for the LQR constructor.

[wpimath] Add Vector overload for times and div

---

wpilibcExamples/src/main/cpp/examples/StateSpaceArm/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceElevator/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheel/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceFlywheelSysId/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacearm/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceelevator/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceflywheel/Robot.java
wpimath/src/main/java/edu/wpi/first/wpilibj/controller/LinearQuadraticRegulator.java
wpimath/src/main/native/cpp/controller/LinearQuadraticRegulator.cpp
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h

It was added as part of Bryson's rule described in
https://file.tavsys.net/control/controls-engineering-in-frc.pdf. It
doesn't really simplify usage though, and the same thing can be
replicated by multiplying the elements of Q by rho manually. It's easier
to do it that way, it's how 3512 has been doing controller debugging for
a while, and it's probably what other teams will do as well instead of
using the "more structured" way.
Removing these unhelpful overloads also simplifies the LQR interface.

[wpimath] Remove rho overload from LinearQuadraticRegulator constructors

---

wpimath/src/main/native/include/frc/StateSpaceUtil.h
wpimath/src/main/native/include/frc/controller/ControlAffinePlantInversionFeedforward.h
wpimath/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h
wpimath/src/main/native/include/frc/estimator/MerweScaledSigmaPoints.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/system/Discretization.h
wpimath/src/test/native/cpp/system/DiscretizationTest.cpp

This helps reduce compilation overhead. I tried slimming down includes
of <Eigen/QR>, but the householderQr() function we use from there
requires including dependency headers from Eigen that don't fit with
lexographic ordering. It didn't seem worth the effort to work around.
This won't affect user code at all since all the Eigen feature usage
here is internal only; users generally only need <Eigen/Core>.

Use more specific Eigen includes in headers

---

wpimath/src/main/native/eigeninclude/Eigen/src/Core/ArrayBase.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/CwiseUnaryView.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/DenseBase.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/MapBase.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/MatrixBase.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/Transpose.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/TriangularMatrix.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/util/Macros.h
wpimath/src/main/native/eigeninclude/Eigen/src/Core/util/XprHelper.h

This avoids deprecated-copy warnings on recent clang and GCC compilers.
Applied from https://gitlab.com/libeigen/eigen/-/merge_requests/29/diffs

[wpimath] Fix Eigen rule-of-three violations

---

shared/config.gradle
wpigui/CMakeLists.txt
wpigui/build.gradle

Final use of wpigui is essentially always the static library.

[wpigui] Only build static for both gradle and cmake

---

cmake/modules/LinkMacOSGUI.cmake
cscore/CMakeLists.txt
simulation/halsim_gui/CMakeLists.txt
wpigui/CMakeLists.txt

```
Undefined symbols for architecture x86_64:
"_MTLCreateSystemDefaultDevice", referenced from:
wpi::gui::PlatformInitRenderer() in libwpigui.a(wpigui_metal.mm.o)
"_OBJC_CLASS_$_CAMetalLayer", referenced from:
objc-class-ref in libwpigui.a(wpigui_metal.mm.o)
"_OBJC_CLASS_$_MTLDepthStencilDescriptor", referenced from:
objc-class-ref in libimgui.a(imgui_impl_metal.mm.o)
"_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
objc-class-ref in libwpigui.a(wpigui_metal.mm.o)
"_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
objc-class-ref in libimgui.a(imgui_impl_metal.mm.o)
"_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
objc-class-ref in libwpigui.a(wpigui_metal.mm.o)
objc-class-ref in libimgui.a(imgui_impl_metal.mm.o)
"_OBJC_CLASS_$_MTLVertexDescriptor", referenced …
```

[build] CMake: Fix Metal linking on macOS

---

README.md

The bulleted list was reworded to address excessive wordiness, and links
are now provided for Windows C++ compiler options.

Improve list of build requirements in README

---

wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h

In the second constructor, a new LinearSystem is created and set to
m_plant. This takes a const ref though, so it's storing a reference to a
temporary object. After the constructor finishes, m_plant points to an
invalid object. When Update() is called, it will crash with a
segmentation fault.
This patch fixes the use-after-free by making m_plant a LinearSystem
value type. The first constructor will generate a copy, but that only
happens once.

[wpilibc] Fix a use-after-free in DifferentialDrivetrainSim

---

.github/workflows/ci.yml

The Gradle heap size is currently set to 1G, and that's becoming too
small for our builds.
Developers who want to override this without editing the project's
build.gradle can override these settings with gradle.properties in
GRADLE_USER_HOME (see
https://docs.gradle.org/current/userguide/build_environment.html for
details).

[build] Double gradle build max heap size to 2G

---

wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h
wpilibc/src/test/native/cpp/simulation/SingleJointedArmSimTest.cpp
wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java

Some vestigial functions were never removed, and C++ singe-jointed arm
sim was missing a flag for disabling gravity simulation. This is useful
for mechanisms like turrets.
Fixes #2738.

[wpilib] Clean up simulation physics API

---

hal/src/main/native/include/hal/SimDevice.h

This isn't appropriate for a RAII class.  In particular, it can cause
foot-shooting in simulation mode if the result of
HALSIM_GetSimDeviceHandle is passed instead of HAL_CreateSimDevice.
Fixes #2742.

[hal] SimDevice class: remove HAL_SimDeviceHandle constructor

---

wpilibc/src/test/native/cpp/simulation/DifferentialDriveSimTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSimTest.java

If the model is unstable, it will almost always diverge within 10
seconds, and the results are rather dramatic. We're also reducing the
threshold to 100 meters because the drivetrain is moving in a small
circle. The translation norm is also used for this reason; the X
component alone regularly crosses zero since the drivetrain moves in a
circle.

[wpilib] Shorten differential drive simulation stability test

---

hal/src/main/java/edu/wpi/first/hal/simulation/SimulatorJNI.java
hal/src/main/native/athena/mockdata/MockHooks.cpp
hal/src/main/native/cpp/jni/simulation/SimulatorJNI.cpp
hal/src/main/native/include/hal/simulation/MockHooks.h
hal/src/main/native/sim/MockHooks.cpp
hal/src/main/native/sim/Notifier.cpp
hal/src/main/native/sim/NotifierInternal.h
simulation/halsim_gui/src/main/native/cpp/TimingGui.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/NotifierCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/WaitCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandTestBase.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/NotifierCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/WaitCommandTest.cpp
wpilibc/src/main/native/cpp/simulation/SimHooks.cpp
wpilibc/src/main/native/include/frc/simulation/SimHooks.h
wpilibc/src/test/native/cpp/SlewRateLimiterTest.cpp
wpilibc/src/test/native/cpp/WatchdogTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimHooks.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/WatchdogTest.java

Old behavior is available via StepTimingAsync.
This makes it significantly easier to use simulation timing with notifiers.
Also update tests to use simulation framework.  This also speeds up the
timing-dependent tests by using simulation timing.  ResourceLock is used
in the Java tests to prevent parallel execution.
While we're here, tweak HAL Notifier implementation:
- Use wait_for instead of wait_until in WaitForNotifierAlarm
- Check for triggerTime = UINT64_MAX in UpdateNotifierAlarm

[sim] Change StepTiming to wait for notifiers

---

wpilibc/src/main/native/include/frc/simulation/LinearSystemSim.h
wpilibc/src/test/native/cpp/simulation/SingleJointedArmSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/LinearSystemSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ArmSimTest.java

This makes it more consistent with all other simulation classes,
including the differential drive simulation class.

[wpilib] Rename LinearSystemSim's ResetState() to SetState()

---

wpimath/src/main/java/edu/wpi/first/wpilibj/spline/SplineHelper.java
wpimath/src/main/java/edu/wpi/first/wpilibj/trajectory/TrajectoryGenerator.java
wpimath/src/main/native/cpp/spline/SplineHelper.cpp
wpimath/src/main/native/cpp/trajectory/TrajectoryGenerator.cpp
wpimath/src/main/native/include/frc/spline/SplineHelper.h
wpimath/src/test/java/edu/wpi/first/wpilibj/spline/QuinticHermiteSplineTest.java
wpimath/src/test/native/cpp/spline/QuinticHermiteSplineTest.cpp

Closes #2761.
This PR does not introduce any breaking changes for teams that used the TrajectoryGenerator API for quintic splines with poses. 
The `GetQuinticControlVectorsFromWaypoints()` method was removed because it is not possible for us (or would require breaking changes to the shape of the splines) to generate only one quintic control vector per Pose2d (https://github.com/wpilibsuite/allwpilib/pull/2429) whereas users who *actually have control vectors directly* (i.e. not from Pose2d objects, but a dashboard such as PathWeaver) should have the number of control vectors correspond to the number of "waypoints". 
These users can call `GetQuinticSplinesFromControlVectors()` directly.

[wpimath] Fix quintic spline generation from control vectors

---

wpimath/src/main/native/include/frc/StateSpaceUtil.h

Java does not have the issue where a std-dev of zero causes UB.

[wpimath] C++: Assign zero in MakeWhiteNoiseVector if std-dev is zero

---

.github/workflows/ci.yml

This addresses: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

[build] Update vcpkg actions to latest

---

wpilibc/src/main/native/include/frc/controller/ControllerUtil.h
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h
wpilibc/src/test/native/cpp/controller/ControllerUtilTest.cpp
wpilibc/src/test/native/cpp/controller/PIDInputOutputTest.cpp
wpilibc/src/test/native/cpp/controller/ProfiledPIDInputOutputTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ControllerUtil.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/ControllerUtilTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/ProfiledPIDInputOutputTest.java

The input range variables used in ProfiledPIDController::Calculate()
weren't being updated.

[wpilib] Fix ProfiledPIDController continuous input

---

wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibc/src/main/native/include/frc/TimedRobot.h
wpilibc/src/test/native/cpp/TimedRobotTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/TimedRobotTest.java

Currently, teams have to make a Notifier to run feedback controllers
more often than the TimedRobot loop period of 20ms (running TimedRobot
more often than this is not advised). This lets users add callbacks to
the main robot loop that run at a user-defined period. This allows
running feedback controllers more often, but does so synchronously with
TimedRobot so there aren't any thread safety issues.

[wpilib] Support scheduling functions more often than robot loop

---

wpimath/src/main/java/edu/wpi/first/wpilibj/system/LinearSystemLoop.java

This fixes a `MatrixDimensionException` when `LinearSystemLoop.predict()` is called in Java.

[wpimath] Fix m_nextR instantiation in LinearSystemLoop ctor

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDSubsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/PIDSubsystem.cpp

Previously, the PIDSubsystem's PID Controller would show as ungrouped in
livewindow.
This will fix wpilibsuite/RobotBuilder#260

[command] Add PIDSubsystem PIDController as child

---

simulation/halsim_gui/src/main/native/cpp/Field2D.cpp

Collapsed windows result in a vertical content size of 0.

[sim] Fix Field2D GUI crash when collapsed

---

.github/workflows/ci.yml
CMakeLists.txt
simulation/CMakeLists.txt

BUILD_SHARED_LIBS is a cmake built-in and must be this name.
Also check for BUILD_SHARED_LIBS with WITH_SIMULATION_MODULES.
While we're here, add WITH_GUI cmake option.

[build] Fix cmake shared library build

---

README.md
shared/java/javastyle.gradle

This task allows developers to run all of the Java code quality tools at once.
Closes #2804

Add a javaFormat Gradle task

---

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibc/src/main/native/cpp/simulation/DutyCycleEncoderSim.cpp
wpilibc/src/main/native/include/frc/DutyCycleEncoder.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DutyCycleEncoderSim.java

The source channel doesn't necessarily correspond with the HALSIM device
index.

[wpilib] Use DutyCycleEncoder FPGA index for sim device number

---

.github/workflows/ci.yml
build.gradle
codesign.sh

Closes #2777 
If the logic should be moved to native-utils, I'll need a little bit of help because I'm not sure where exactly to move it (cc: @ThadHouse).
This also depends on the existence of the following secrets:
| Secret | Description |
| --- | --- |
| CERTIFICATE_DATA | Base64 encoded `.p12` Developer ID Certificate Data |
| CERTIFICATE_PASSWORD | Password used to encrypt `.p12` when exporting from Keychain |
| KEYCHAIN_PASSWORD | Any random secure string of characters to be used as Keychain password |
| DEVELOPER_ID | The Developer ID used to sign the binaries |
Note that the `DEVELOPER_ID` isn't a "secret" (i.e. it is public information), but it's easiest to store in a GitHub secret so that we don't have to hardcode it everywhere.
Marking this PR as draft so I can get feedback as …

[build] Add Developer ID signing workflow

---

build.gradle

The way GitHub actions checks out tags checks them out as non-annotated, so look for non-annotated tags as well.
See actions/checkout#290.

[build] Fix release versioning

---

wpimath/src/main/java/edu/wpi/first/wpilibj/system/LinearSystemLoop.java
wpimath/src/main/native/include/frc/system/LinearSystemLoop.h

This address some problems with the LinearSystemLoop class that were discovered through testing.
The initial state estimate of the observer was set to the provided initial state rather than zero as previously, a non zero initial state passed into reset() would lead to a discrepancy between the current state estimate and the actual system state.

Addressing issues with LinearSystemLoop reset() and matrix initialization.

---

wpilibc/src/main/native/cpp/AnalogPotentiometer.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogPotentiometer.java

Made just a few edits to the initSendable methods to output to the Dashboards the scaled value of the device vs the 0-5 volt average. This is much better in my opinion for users to see the returned value in the user units they set up vs a widget that scale a bar from 0 to 5 volts. This takes care of issue #2814 
I would invite a discussion if there is a reason not to deploy this so I can better understand why keeping the 0-5v display.

Analog Potentiometer return Scaled Value to Dashboard

---

wpilibc/src/main/native/cpp/AnalogPotentiometer.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogPotentiometer.java

There's not a specific dashboard type for potentiometers, so use analog input.

[wpilib] Set AnalogPotentiometer dashboard type

---

buildSrc/build.gradle

This pulls in the 2021 versions of thirdparty libs.

[build] Update NativeUtils to 2021.0.4

---

wpilibc/src/main/native/cpp/smartdashboard/SendableRegistry.cpp

If a Sendable like SendableChooser is destroyed and recreated, it leaves
a stale object in the Sendable registry. Using this object results in a
crash. This patch avoids using the stale object.
We should remove stale objects from the global registry upon object
destruction, but this fixes the crashing issue for now.
Closes #2818.  Supersedes #2827.
Co-authored-by: Tyler Veness <calcmogul@gmail.com>

[wpilibc] SendableRegistry: Add range and null checks

---

wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json

Update all examples to export NewCommands Vendordep except for pacgoat,
which still uses old commands.

Update examples to export NewCommands

---

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java

Calling the resetPosition method on an odometry instance expects encoder positions to be reset to zero.

[wpilib] Fix DiffDriveSim pose reset and example

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java

`m_u` isn't initialized in the ctor, meaning that if the user calls `update()` before `setInputs()` the program will crash with an NPE. 
The even bigger problem is that the NPE is thrown a few levels deeper in the stack trace, making it even harder to debug. 
Calling functions out of the intended order shouldn't crash the program.

Add default initialization of m_u in drivetrain sim

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/test/native/cpp/DriverStationTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/DriverStationTest.java

Closes #2844 
There are no stdout tests for Java because there is no good way to capture output from native code.

[wpilib] Add way to silence joystick connection warnings

---

hal/src/main/java/edu/wpi/first/hal/simulation/SimDeviceDataJNI.java
hal/src/main/native/athena/mockdata/SimDeviceData.cpp
hal/src/main/native/cpp/jni/simulation/SimDeviceDataJNI.cpp
hal/src/main/native/include/hal/simulation/SimDeviceData.h
hal/src/main/native/sim/mockdata/SimDeviceData.cpp
simulation/halsim_ws_core/src/main/native/cpp/WSProvider_SimDevice.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/SimDeviceSimTest.java

Asynchronous callbacks are more efficient but pose synchronization challenges;
other sim callbacks are synchronous but SimDevice ones were not.
Supersedes #2834.

[sim] Make SimDevice callbacks synchronous

---

simulation/halsim_ds_socket/CMakeLists.txt
simulation/halsim_gui/CMakeLists.txt
simulation/halsim_ws_client/CMakeLists.txt
simulation/halsim_ws_server/CMakeLists.txt

This builds sim extensions as `dylib`'s instead of `so`'s on macOS.

Build sim extensions as shared libs

---

hal/src/main/native/cpp/jni/HAL.cpp
hal/src/main/native/sim/DriverStation.cpp

This ensures the padding is zero'ed.  We already do this on Athena, we just didn't in sim.

[sim] HAL_GetControlWord: Fully zero output 

---

wpimath/src/main/java/edu/wpi/first/math/WPIMathJNI.java
wpimath/src/main/java/edu/wpi/first/wpilibj/controller/LinearQuadraticRegulator.java
wpimath/src/main/java/edu/wpi/first/wpiutil/math/Matrix.java
wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/test/java/edu/wpi/first/wpilibj/controller/LinearQuadraticRegulatorTest.java
wpimath/src/test/native/cpp/controller/LinearQuadraticRegulatorTest.cpp

There were three options for where to put this function:
1. A free function in LinearQuadraticRegulator.h. Returning a K matrix
means the user can't use the LinearQuadraticRegulator in a loop
anymore.
2. A default argument added to ctors in LinearQuadraticRegulator for a
time delay (default of 0). This has the smallest API footprint from
the user perspective, but it bloats the already substantial
constructor overload set of LinearQuadraticRegulator.
3. A member function in LinearQuadraticRegulator that modifies the
internal K. This would still have to take in a LinearSystem or (A, B)
pair because the ctor doesn't store it. Storing it internally feels
like paying for what we don't use most of the time.
I went with option 3.
I verified the tests's expected values in Python with …

[wpilib] Add function to adjust LQR controller gain for pure time delay

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/SimDeviceSimTest.java

SimDeviceSim.registerValueChangedCallback internally calls SimDeviceDataJNI.registerSimValueChangedCallback with its device handle and the arguments passed to it, however, SimDeviceDataJNI.registerSimValueChangedCallback expects a value handle. This fixes #2879.

Fix sim value changed callbacks by passing correct handle to SimDeviceDataJNI

---

CMakeLists.txt
README-CMAKE.md

This allows external CMake projects to only depend on wpimath instead of
having to build the entire library.

[build] Add separate CMake setting for wpimath

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

This is a simple fix for #2872.
The only exception I see is that when the sim gui starts registers/initializes the DS sim with halsim, the initial joystick values are sent which can overwrite any set by `JoystickSim`. But after that startup process, it seems fine.

Stop halsim gui setting joysticks it doesn't have.

---

README.md

There's currently conflicting instructions: install via the archive on
the releases page, and install using a gradlew command.

Merge roboRIO toolchain installation instructions

---

CMakeLists.txt
cameraserver/CMakeLists.txt
cmake/toolchains/gnu.toolchain.cmake
cscore/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
wpigui/CMakeLists.txt
wpilibc/CMakeLists.txt
wpilibj/CMakeLists.txt
wpimath/CMakeLists.txt
wpiutil/CMakeLists.txt

This ensures that allwpilib will still build correctly when added as a CMake external project

[build] CMake: Use project-specific binary and source dirs

---

simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp

Previously, the window had a blank title.

[sim] Add title to simulator GUI window

---

buildSrc/src/main/groovy/SingleNativeBuild.groovy
hal/build.gradle
shared/config.gradle
shared/jni/setupBuild.gradle
wpilibNewCommands/build.gradle
wpilibOldCommands/build.gradle
wpilibc/build.gradle

This will remove all test folders, which removes lots of copies of dependencies.
This also fixes an issue where gtest exectubables were installed for cross builds, even though they should not have been

Delete all test folders after tests execute.

---

wpilibc/src/main/native/cpp/DriverStation.cpp

The is_convertible test was always treating the input as bool.
Use is_same on T instead.

[wpilibc] Fix MatchDataSender

---

wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/commands/ComplexAuto.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/include/RobotContainer.h
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/cpp/commands/DriveDistance.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/include/commands/DriveDistance.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/commands/ComplexAutoCommand.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbottraditional/commands/DriveDistance.java

This fixes an issue with some commands not correctly requiring their
subsytems. Furthermore, an execute() method was added to the
DriveDistance command to continuously update the voltage command.
https://www.chiefdelphi.com/t/simulation-and-command-bot/389311?u=prateek_m

[wpilib] Fix bugs in Hatchbot examples

---

wpilibc/src/main/native/cpp/controller/PIDController.cpp
wpilibc/src/main/native/include/frc/controller/PIDController.h
wpilibc/src/test/native/cpp/controller/PIDToleranceTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/PIDToleranceTest.java

This makes AtSetpoint() return false after the setpoint is changed with
SetSetpoint().
Closes #2821.

Recompute the error in AtSetpoint()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java

This caused an illegal argument exception whenever the simulated elevator velocity was retrieved.
https://usfirst.collab.net/sf/go/post6820

[wpilibj] Fix egregious typo in ElevatorSim

---

hal/src/main/native/include/hal/simulation/PCMData.h
hal/src/main/native/sim/Solenoid.cpp
hal/src/main/native/sim/mockdata/PCMData.cpp
hal/src/main/native/sim/mockdata/PCMDataInternal.h

This allows much easier/faster checking for whether any solenoid has been
initialized on a particular PCM.

[sim] Add initialized flag for all solenoids on a PCM

---

wpiutil/src/main/native/include/wpi/FunctionExtras.h

Only implicitly convert from invocable objects.  This avoids potential
ambiguity in higher-level overloaded functions.

[wpiutil] unique_function: Restrict implicit conversion

---

wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

We need to execute listener tasks first, then execute value updates.
Otherwise local changes can fight with dashboard-made changes.

[wpilib] Fix SmartDashboard update order

---

wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/RobotContainer.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/RobotContainer.java

This ensures that mechanisms will stop moving if the robot is disabled while motors are in motion

[examples] Zero motors on disabledInit() in sim physics examples

---

wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilder.h

The change to SendableBuilder to add GetTable() added a virtual function
early in the class definition.  This is an ABI break for vendor libraries.
Attempt to workaround this breakage by moving GetTable() to the end of the
class definition.

[wpilibc] Try to work around ABI break introduced in #2901

---

wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Robot.java

This provides an example of using the differential drive simulator without needing to use the command-based library.
Both of these examples were tested in the Simulator GUI and the robots followed the paths as expected.

[examples] Add simple differential drive simulation example

---

hal/src/main/java/edu/wpi/first/hal/simulation/SimDeviceDataJNI.java
hal/src/main/native/cpp/jni/simulation/SimDeviceDataJNI.cpp

This was mistakenly omitted from the Java interface.

[hal] Add Java SimDeviceDataJNI.getSimDeviceName

---

hal/src/main/native/sim/Encoder.cpp
simulation/halsim_ws_core/src/main/native/cpp/WSProvider_Encoder.cpp
simulation/halsim_ws_core/src/main/native/include/WSProvider_Encoder.h

Currently, Encoder.reset() must make a round trip to the sensor and back
in order for the count to be updated for the user program.  As the sim layer
also resets the internal encoder count, this creates a race condition (a WS
message with a new count can be "in flight" during a reset and update the
count).
This changes the WS layer to not put reset on the wire, but instead keep an
offset count internal to the robot program.  The value on the wire is not
reset, but rather all sends and receives are adjusted as necessary to the
internal robot count.
This approach is straightforward, but does result in the value on the wire
not matching the value in the user program.  A future improvement will fix
this, but this change fixes the immediate race condition problem.

[sim] Process WS Encoder reset internally

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

This allows joystick testing without a physical joystick.  Comes with a default set of keyboard mappings, but these are fully customizable by the user.  Up to 4 virtual joysticks are supported.
Default keyboard mappings:
- Joystick 0: axis 0: `AD`, axis 1: `WS`, axis 2: `ER`, buttons `ZXCV`, POV on numeric keypad
- Joystick 1: axis 0: `JL`, axis 1: `IK`, buttons `M,./`
- Joystick 2: axis 0: left/right arrow, axis 1: up/down arrow, buttons insert/home/pgup/del/end/pgdn
This PR also adds support for DS-style hotkeys of `[]\` enable, Enter disable, and spacebar disable.  All of these are disabled by default and must be explicitly enabled by the user.

[sim] GUI: Add keyboard virtual joystick support

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

If the strncpy() bound is equal to the destination size and the source
string is longer than 256 bytes, strncpy() won't write a null terminator
for the destination string.

Fix stringop truncation warning from GCC 10

---

wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/subsystems/DriveSubsystem.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java

This class did not exist when the original example was written. This
also changes the C++ example to use ADXRS450_Gyro for the sake of
consistency.

[examples] Use ADXRS450_GyroSim class in simulation example

---

wpimath/src/main/java/edu/wpi/first/wpilibj/system/LinearSystemLoop.java
wpimath/src/main/native/include/frc/system/LinearSystemLoop.h
wpimath/src/test/java/edu/wpi/first/wpilibj/controller/LinearSystemLoopTest.java
wpimath/src/test/native/cpp/StateSpaceTest.cpp

The system wasn't being used internally, and as LinearSystem is stateless, it doesn't need to be held by LinearSystemLoop.

[wpimath] Remove LinearSystem from LinearSystemLoop

---

glass/src/libnt/native/cpp/NetworkTables.cpp

Just hide it from view in the tree view.
Fixes #2990.

[glass] Fix handling of "/" NetworkTables key

---

cscore/src/main/native/windows/ComPtr.h
hal/src/main/native/include/hal/SimDevice.h
hal/src/main/native/include/hal/Types.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpiutil/src/main/native/include/wpi/HttpUtil.h
wpiutil/src/main/native/include/wpi/uv/Buffer.h
wpiutil/src/main/native/include/wpi/uv/Process.h
wpiutil/src/test/native/cpp/sigslot/recursive.cpp
wpiutil/src/test/native/cpp/sigslot/signal.cpp

cpplint.py can accept either, but clang-tidy requires NOLINT.

Replace NOLINT(runtime/explicit) comments with NOLINT (NFC)

---

glass/src/libnt/native/cpp/NetworkTables.cpp

Before this change, user settings were not loaded until after the first time they opened the settings context menu

[glass] Load NetworkTableView settings on first draw

---

wpiutil/src/main/native/cpp/timestamp.cpp

This silences a clang-tidy warning.

[wpiutil] Add noexcept to timestamp static functions

---

wpilibc/src/test/native/cpp/ScopedTracerTest.cpp

ScopedTracerTest now uses simulation time instead of wall clock time, so
it doesn't have to actually wait 1.5 seconds.

[wpilibc] Speed up ScopedTracerTest

---

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp
wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java

Breaks the function into two, so you can query the left and the right separately. Useful if you want to set the PDP channels or set the current for the 3rd party smart controllers

[sim] Create Left/Right drivetrain current accessors
