wpilibsuite/allwpilib

glass/src/lib/native/cpp/hardware/Gyro.cpp

This ensures that the colors are properly visible in light mode or any
other custom user styles.

[glass] Use ImGui style for gyro widget colors

---

ntcore/src/main/native/include/networktables/NetworkTableValue.h

Because these are forwarding references, they could unexpectedly move a
passed lvalue.  Using std::forward() makes a copy if an lvalue is passed.

[ntcore] NetworkTableValue: Use std::forward instead of std::move

---

wpilibc/src/main/native/include/frc/shuffleboard/SuppliedValueWidget.h

This is needed to break an include loop between ShuffleboardContainer.h
and SuppliedValueWidget.h.

[wpilibc] SuppliedValueWidget.h: Forward declare ShuffleboardContainer

---

.github/workflows/gazebo.yml

Several builds on master are failing due to Gradle running out of memory.

[build] Increase Gradle heap size in Gazebo build

---

wpilibcExamples/src/main/cpp/examples/RomiReference/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/romireference/RobotContainer.java

This commit flips the TeleopArcadeDrive axis directions so that positive values for x-axis speed result in the Romi driving forward (in the direction of the Raspberry Pi USB ports). This works in conjunction with version 1.0.3 (and later) of the Romi web service

[examples] Update RomiReference to match motor directions

---

.github/workflows/documentation.yml

This will publish our Javadoc and Doxygen documentation to `https://github.wpilib.org/allwpilib/docs/<track>/<lang>`. It requires a GitHub PAT secret to be added to the repo.
A slightly modified demo is available here:
https://github.com/AustinShalit/allwpilib/tree/gh-pages/allwpilib/docs
Development:
https://austinshalit.github.io/allwpilib/allwpilib/docs/development/java/
https://austinshalit.github.io/allwpilib/allwpilib/docs/development/cpp/
Beta:
https://austinshalit.github.io/allwpilib/allwpilib/docs/beta/java/
https://austinshalit.github.io/allwpilib/allwpilib/docs/beta/cpp/
Release:
https://austinshalit.github.io/allwpilib/allwpilib/docs/release/java/
https://austinshalit.github.io/allwpilib/allwpilib/docs/release/cpp/

[build] Add publish documentation script

---

ntcore/src/main/native/include/networktables/NetworkTableEntry.inl

It was calling value->GetString() instead of GetRaw(), which would assert.

[ntcore] Fix NetworkTableEntry::GetRaw()

---

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp
wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java

Using the plant output means that measurement noise can be incorporated.
SingleJointedArmSim (in C++ and Java) and ElevatorSim (in C++) used the
state instead of the measurement.
Closes #3042

[sim] Use plant output to retrieve simulated position

---

wpimath/src/main/java/edu/wpi/first/wpilibj/system/plant/DCMotor.java
wpimath/src/main/java/edu/wpi/first/wpilibj/system/plant/LinearSystemId.java
wpimath/src/main/native/include/frc/system/plant/DCMotor.h
wpimath/src/test/java/edu/wpi/first/wpilibj/estimator/ExtendedKalmanFilterTest.java
wpimath/src/test/java/edu/wpi/first/wpilibj/estimator/UnscentedKalmanFilterTest.java

The stall torque, stall current, and free current are now multiplied by
the number of motors instead of just the stall torque. This produces the
same values for Kt and Kv regardless of the number of motors; the motor
resistance still affects the system response.
For an elevator model, the response should be the same as before since a
factor of "number of motors" shows up in the same place in the
acceleration calculation, but the current calculation will also be
correct now.

[wpimath] Make Java DCMotor API consistent with C++ and fix motor calcs

---

glass/src/lib/native/cpp/hardware/SpeedController.cpp
glass/src/lib/native/cpp/other/Drive.cpp
glass/src/lib/native/cpp/other/PIDController.cpp
glass/src/libnt/native/cpp/NTDifferentialDrive.cpp
glass/src/libnt/native/cpp/NTMecanumDrive.cpp
glass/src/libnt/native/cpp/NTPIDController.cpp
glass/src/libnt/native/cpp/NTSpeedController.cpp
glass/src/libnt/native/include/glass/networktables/NTDifferentialDrive.h
glass/src/libnt/native/include/glass/networktables/NTMecanumDrive.h
glass/src/libnt/native/include/glass/networktables/NTPIDController.h
glass/src/libnt/native/include/glass/networktables/NTSpeedController.h

This modifies the mecanum drive, differential drive, speed controller,
and PID controller widgets to only be writeable when .controllable is
set to true.
Closes #3034

[glass] Use .controllable to set widgets' read-only state

---

glass/src/lib/native/cpp/other/Plot.cpp
glass/src/lib/native/cpp/support/ExtraGuiWidgets.cpp
imgui/CMakeLists.txt.in
shared/config.gradle

Also update imgui and implot to latest, to enable secondary Y axis labels (recently added to implot).
Depends on wpilibsuite/thirdparty-imgui#23.

[glass] Add support for plot Y axis labels

---

wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/SwerveModule.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/SwerveModule.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/subsystems/SwerveModule.h
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/SwerveModule.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervesdriveposeestimator/SwerveModule.java
wpimath/src/main/java/edu/wpi/first/wpilibj/kinematics/SwerveModuleState.java
wpimath/src/main/native/include/frc/kinematics/SwerveModuleState.h

This makes it easy for teams to ensure that their modules never rotate more than 90 degrees to reach a given reference.

[wpimath] Add optimize() to SwerveModuleState

---

wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/RobotContainer.java

This also shifts the trajectory up and to the right so that the robot is
always visible in the Field GUI during traversal. Some drive constants
and trajectory constraints were also synced between the two languages.
Closes #3078

[examples] Sync Java and C++ trajectories in sim example

---

hal/src/main/java/edu/wpi/first/hal/SimDeviceJNI.java
hal/src/main/java/edu/wpi/first/hal/SimDouble.java
hal/src/main/java/edu/wpi/first/hal/SimInt.java
hal/src/main/java/edu/wpi/first/hal/SimLong.java
hal/src/main/java/edu/wpi/first/hal/simulation/SimDeviceDataJNI.java
hal/src/main/native/athena/SimDevice.cpp
hal/src/main/native/athena/mockdata/SimDeviceData.cpp
hal/src/main/native/cpp/jni/SimDeviceJNI.cpp
hal/src/main/native/cpp/jni/simulation/SimDeviceDataJNI.cpp
hal/src/main/native/include/hal/SimDevice.h
hal/src/main/native/include/hal/simulation/SimDeviceData.h
hal/src/main/native/sim/SimDevice.cpp
hal/src/main/native/sim/mockdata/SimDeviceData.cpp
hal/src/main/native/sim/mockdata/SimDeviceDataInternal.h
simulation/halsim_ws_core/src/main/native/cpp/WSProvider_SimDevice.cpp
simulation/halsim_ws_core/src/main/native/include/WSProvider_SimDevice.h
wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp
wpilibc/src/main/native/include/frc/simulation/SimDeviceSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java

This enables correct behavior for resetting incremental sensor values like
encoder counts or gyro accumulated angle with WebSockets.
Fixes #3030.

[hal] Add SimValue reset() function

---

wpilibNewCommands/src/test/native/cpp/frc2/command/SwerveControllerCommandTest.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/subsystems/DriveSubsystem.h
wpimath/src/main/native/cpp/controller/LinearQuadraticRegulator.cpp
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/KalmanFilter.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/spline/CubicHermiteSpline.cpp
wpimath/src/main/native/cpp/spline/QuinticHermiteSpline.cpp
wpimath/src/main/native/cpp/spline/SplineHelper.cpp
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc
wpimath/src/main/native/include/frc/spline/CubicHermiteSpline.h
wpimath/src/main/native/include/frc/spline/QuinticHermiteSpline.h
wpimath/src/main/native/include/frc/spline/Spline.h
wpimath/src/main/native/include/frc/spline/SplineHelper.h
wpimath/src/test/native/cpp/kinematics/SwerveDriveKinematicsTest.cpp
wpiutil/src/main/native/include/wpi/array.h

The wpimath APIs use std::array, which doesn't do size checking. Passing
an array with the wrong size can result in uninitialized elements
instead of a compilation error.

[wpimath, wpiutil] Add wpi::array for compile time size checking

---

.gitattributes
.wpilib/wpilib_preferences.json
buildSrc/build.gradle
glass/publish.gradle

Updates native utils to latest.
Fixes a deprecation warning from gradle
Adds .gitattributes so building without autocrlf on windows works.
Fixes vs code project year.
Fixes file with bad line endings.

Fix issues with build on windows, deprecations, and native utils

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/romireference/commands/ArcadeDrive.java

Removed extra 'p' in "Supplier" in the parameter name `zaxisRotateSuppplier` of the  ArcadeDrive constructor of the Romi Reference example.

Fix typo in ArcadeDrive constructor parameter name

---

glass/src/lib/native/cpp/Window.cpp
glass/src/lib/native/include/glass/Window.h
glass/src/libnt/native/cpp/NetworkTablesProvider.cpp

Instead of "/SmartDashboard/name" they now default to "name (SmartDashboard)".
This allows for smaller windows while preserving the name without requiring
user customization.

[glass] Shorten SmartDashboard window names

---

wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/subsystems/DriveSubsystem.h
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/subsystems/DriveSubsystem.h

* MecanumControllerCommand
* SwerveControllerCommand

Fix feildRelative -> fieldRelative typo in XControllerCommand examples

---

hal/src/main/native/athena/Threads.cpp
hal/src/main/native/include/hal/Threads.h
wpilibc/src/main/native/include/frc/Notifier.h
wpilibc/src/main/native/include/frc/Threads.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Threads.java
wpiutil/src/test/native/cpp/priority_mutex_test.cpp

The ranges and which value was specified as highest were incorrect on
some of them. On Linux, the range is 1 to 99 with 99 being highest.
From `man 7 sched`:
```
Processes scheduled under one of the real-time policies (SCHED_FIFO,
SCHED_RR) have a sched_priority value in the range 1 (low) to 99 (high).
```
I also cleaned up the relevant javadoc and doxygen comments.

Fix RT priority docs

---

README.md

I don't like digging through my bookmarks every time I need API documentation, so this PR adds [shields.io](https://shields.io/) badges to the README for both Java and C++ documentation.

Add quick links to API documentation in README

---

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/DriveStraight.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetDistanceToBox.cpp

This is a temporary fix to prevent a dangling this pointer in the
DriveStraight and SetDistanceToBox commands by directly capturing the
drivetrain pointer by value instead.
Closes #3109

[examples] Fix segfault in GearsBot C++ example

---

ntcore/src/main/native/cpp/Dispatcher.h

`m_last_flush` should be initialized before it's used at
Dispatcher.cpp:243.
```cpp
if ((now - m_last_flush) < 5000) {
return;
}
m_last_flush = now;
```

[ntcore] Fix conditional jump on uninitialized value

---

glass/publish.gradle

This allows users to use libglass and libglassnt in their own GUI projects and/or develop Glass extensions in the future.

[build] Publish libglass and libglassnt to Maven

---

wpigui/src/main/native/cpp/wpigui.cpp

This fixes an issue with scaling on Retina displays where the frame
buffer size was double that of the window size, resulting in a content
scale factor of 2. This scale factor caused elements to appear too
large, even on the smallest zoom setting.
This change does not affect external monitors on macOS because the
reported content scale was 1 anyway.

[wpigui] Hardcode window scale to 1 on macOS

---

cscore/CMakeLists.txt

With this change, cmake finds OpenCV Java on Ubuntu with no additional search options.

[build] Tweak OpenCV cmake search paths to work better on Linux

---

wpiutil/src/main/java/edu/wpi/first/wpiutil/CombinedRuntimeLoader.java

Because of Java's type system, it is actually literally impossible to check for this cast at runtime. So instead, the only option is to suppress it. Only suppressed for the specific function.
Closes #3023

Suppress unchecked cast in CombinedRuntimeLoader

---

wpilibc/src/main/native/cpp/controller/HolonomicDriveController.cpp
wpilibc/src/main/native/include/frc/controller/HolonomicDriveController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/HolonomicDriveController.java

The atReference() method previously used the rotation error between the
desired trajectory state and the current pose. This was a bug because we
allow teams to use custom rotation setpoints and that wasn't being taken
into account.
Closes #3164

[wpilib] Fix HolonomicDriveController atReference() behavior

---

wpilibc/src/main/native/cpp/simulation/SimDeviceSim.cpp
wpilibc/src/main/native/include/frc/simulation/SimDeviceSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java

Better parallelism with `SimDevice.create()`, so teams don't have to mess with concatenating the index/channel themselves.
Any chance some can do the C++ side?

Add SimDeviceSim ctor overloads

---

wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/wpilibj/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp

The gyro offset should be determined from the desired initial pose, not the current pose. This fix reflects the behavior of the [odometry classes](https://github.com/wpilibsuite/allwpilib/blob/99b5ad9ebb826485d1e8eb6c0940f5bea17b8507/wpimath/src/main/java/edu/wpi/first/wpilibj/kinematics/DifferentialDriveOdometry.java#L68) and the c++ holonomic pose estimators.
Huge thanks to @CptJJ for finding this bug and suggesting a fix.

[wpimath] Fix order of setting gyro offset in pose estimators.

---

wpimath/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.h

Hey y'all! I was looking at the inline comments for the [Rotation2d.rotateBy](https://github.com/wpilibsuite/allwpilib/blob/43d40c6e9e95ed0d7bb5f1baa932af37d4449189/wpimath/src/main/java/edu/wpi/first/wpilibj/geometry/Rotation2d.java#L115) method the other day and found it very difficult to follow. It looks like the formatting got garbled in https://github.com/wpilibsuite/allwpilib/pull/1768
This PR restores the formatting to it's previous version so it's easier to read. It also fixes an incorrect piece in the documentation where it states return value of the function would be `atan2(cos_new, sin_new)` based on the matrix math, when the return type is actually `atan2(sin_new, cos_new)`

Revert formatting for Rotation2d.rotateBy method comment. Fix typo inRotation2d.rotateBy comments.

---

wpilibc/src/main/native/cpp/controller/PIDController.cpp
wpilibc/src/main/native/include/frc/controller/PIDController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java

Require non-zero positive value for `PIDController.period`

---

.gitignore

This is used by newer clangd versions.

gitignore: Ignore .cache directory

---

glass/src/lib/native/cpp/other/Plot.cpp

Plots can still be set to have a fixed height, in which case the remaining
space is distributed amongst the auto-sized plots.
Fixes #3192.

[glass] Auto-size plots to fit window

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandBase.java

This allows it to return the same type, retaining the Sendable portion

Change CommandBase::withName to return CommandBase

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java

Given that m_requirements uses a LinkedHashMap, the behavior of the get method is replicated in the requiring() method.

Add comment to clarify requiring return value

---

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/RobotContainer.java

[examples] Use more logical elevator setpoints in GearsBot

---

glass/src/libnt/native/cpp/NTField2D.cpp

This was causing incorrect detection of duplicate names.
Fixes #3230.

[glass] NTField2D: Fix name lookup

---

wpiutil/src/main/native/include/wpi/Format.h

This function relies on the behavior of snprintf returning an error value
when the buffer is too small.  By default, _snprintf_s aborts on Windows
instead of returning an error value.
This caused Glass to fail when trying to print a large NT value to a string.

[wpiutil] Unbreak wpi::Format on Windows

---

.github/workflows/lint-format.yml

It looks like actions/setup-python needs Ubuntu 20.04.

[build] Fix clang-tidy action

---

cameraserver/multiCameraServer/src/main/native/cpp/main.cpp
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cameraserver/src/main/native/include/cameraserver/CameraServer.h
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibOldCommands/src/main/native/cpp/commands/Scheduler.cpp
wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/Preferences.cpp
wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/Preferences.h
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h
wpilibcExamples/src/main/cpp/examples/AxisCameraSample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/IntermediateVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/QuickVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
wpilibcIntegrationTests/src/main/native/cpp/PreferencesTest.cpp
wpilibcIntegrationTests/src/main/native/cpp/TestEnvironment.cpp

Improves consistency across all classes.
Affects Preferences, LiveWindow, and CameraServer.
Old commands Scheduler::GetInstance() was not updated as this is already
deprecated.

[wpilibc] Return reference from GetInstance (breaking change)

---

wpigui/src/main/native/cpp/wpigui.cpp

Only set the initial window position if the window X/Y position is within one
of the connected monitor work areas.
Fixes #3253.

[wpigui] Ensure window will be initially visible

---

glass/src/lib/native/cpp/other/Plot.cpp

Previously the following sequence was broken:
- Add two plot windows (creates Plot<0> and Plot<1>)
- Delete Plot<0>
- Try to create a plot window
This failed because it would try to create Plot<1>, which already existed.
It was necessary to also destroy Plot<1> before another plot could be added.
This change fixes this case by trying all 0-N cases.

[glass] Plot: Fix window creation after removal

---

glass/.styleguide
glass/src/lib/native/cpp/other/Field2D.cpp
glass/src/lib/native/include/glass/other/Field2D.h
glass/src/libnt/native/cpp/NTField2D.cpp
glass/src/libnt/native/include/glass/networktables/NTField2D.h
wpilibc/src/main/native/cpp/smartdashboard/FieldObject2d.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/FieldObject2d.java

- Add raw support for pose lists > 255/3 in length
- Improve drag selection, especially with closely overlapping objects
- Drag selection of corner also highlights center of object with smaller circle
- Multiple styles (box, line, closed line, track)
- Configurable line and arrow settings (color, weight)
- Add tooltip for object name, index, x, y, rotation
- Context menu for pose edit/add/remove
- View/edit in feet or inches as well as meters
- Configurable object selectability
Implementation: use vector of Pose2d internally, use units
Fixes #3197.

[wpilib] Field2d enhancements

---

wpilibc/src/main/native/cpp/smartdashboard/FieldObject2d.cpp
wpilibc/src/main/native/include/frc/smartdashboard/FieldObject2d.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/FieldObject2d.java

[wpilib] Add setTrajectory() method to FieldObject2d

---

wpiutil/src/main/native/include/wpi/circular_buffer.inc

Some types don't support zero init.

[wpiutil] circular_buffer: Use value initialization instead of zero

---

wpilibc/src/main/native/cpp/controller/HolonomicDriveController.cpp
wpilibc/src/main/native/include/frc/controller/HolonomicDriveController.h
wpilibc/src/test/native/cpp/controller/HolonomicDriveControllerTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/HolonomicDriveController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/HolonomicDriveControllerTest.java

[wpilib] Fix initial heading behavior in HolonomicDriveController

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java

The Drive Subsystem was supplying an incorrectly constructed Rotation2d to the odometry update method. Rotation2d constructor was being called with heading in degrees, not radians as required.

Fix odometry update in SwerveControllerCommand example

---

wpiutil/src/main/native/cpp/uv/Handle.cpp
wpiutil/src/main/native/include/wpi/uv/Handle.h
wpiutil/src/main/native/include/wpi/uv/NetworkStream.h
wpiutil/src/main/native/include/wpi/uv/Stream.h

This avoids asan warnings for deleting a different pointer type.

[wpiutil] uv Handle: Use malloc/free instead of new/delete

---

cscore/src/main/native/windows/UsbCameraImpl.cpp

Can remove a memory copy in many cases. This also fixes a bug where any mjpeg cameras on windows just wouldn't work if the fast path was taken.
Closes #3287

Use Lock2DSize if possible for Windows USB cameras

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/SerialPort.java

The javadoc `@deprecated` tag didn't have a corresponding `@Deprecated`
attribute.

Fix @deprecated warning for SerialPort constructor

---

wpimath/src/main/native/cpp/drake/math/discrete_algebraic_riccati_equation.cpp
wpimath/src/main/native/include/drake/math/discrete_algebraic_riccati_equation.h
wpimath/src/test/native/cpp/drake/math/discrete_algebraic_riccati_equation_test.cpp

This version incorporated the patch we were manually applying, so we're
synced back up with upstream now except for some minor #include changes
to reduce header bloat.

Update Drake DARE solver to v0.29.0

---

wpimath/generate_numbers.py

Without this fix, I was getting the following kinds of errors from
`./gradlew testDesktopJava`.
```
> Task :wpimath:compileJava FAILED
/home/tav/git/wpilib/allwpilib/wpimath/build/generated/java/edu/wpi/first/wpiutil/math/numbers/N0.java:11: error: cannot find symbol
import edu.wpi.first.wpiutil.math.Num;
^
symbol:   class Num
location: package edu.wpi.first.wpiutil.math
```

[wpimath] Fix classpath used by generate_numbers.py

---

cameraserver/multiCameraServer/src/main/native/cpp/main.cpp
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cameraserver/src/main/native/include/cameraserver/CameraServer.h
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibOldCommands/src/main/native/cpp/commands/Scheduler.cpp
wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/Preferences.cpp
wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/Preferences.h
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h
wpilibcExamples/src/main/cpp/examples/AxisCameraSample/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/IntermediateVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/QuickVision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
wpilibcIntegrationTests/src/main/native/cpp/PreferencesTest.cpp
wpilibcIntegrationTests/src/main/native/cpp/TestEnvironment.cpp

This reverts commit a79faace1ba608ebca8bcf2f95a66ea5f78d88e8.
This change will be superseded in a non-breaking way by changing to static functions and deprecating GetInstance() entirely (#3341).

[wpilibc] Revert "Return reference from GetInstance"

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/ExampleGlobalMeasurementSensor.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervesdriveposeestimator/Robot.java

While experimenting with something I noticed that the example projects don't compile by themselves because they reference classes in different examples. This makes them actually isolated, by removing the cross-example imports

[wpilibjExamples] Fix pose estimator examples

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/MotorController.java

set() and other functions also need to be repeated on the MotorController
interface to avoid deprecation warnings from vscode.
Extension of #3347.

[wpilibj] Fix SpeedController deprecated warnings

---

simulation/halsim_ws_core/src/main/native/include/WSProviderContainer.h

This fix adds the mutex header to WSProviderContainer.h
I was building with CMake and the build failed as it could not find std::unique_lock. I am guessing this is a gcc 11 issue but I have not tested it on other compilers.
To reproduce this problem, run on Arch Linux and use CMake as `cmake -GNinja -DWITH_JAVA=OFF .. && ninja`. This demo should also work with Unix Makefiles

Fix build error when building with GCC 11.1

---

wpimath/src/main/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.java
wpimath/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
wpimath/src/test/java/edu/wpi/first/math/controller/SimpleMotorFeedforwardTest.java
wpimath/src/test/native/cpp/controller/SimpleMotorFeedforwardTest.cpp

This is often more convenient than using the overload with velocity and
acceleration.
Fixes #3160.

[wpimath] Add SimpleMotorFeedforward::Calculate(velocity, nextVelocity) overload

---

wpilibc/src/main/native/cpp/controller/PIDController.cpp
wpilibc/src/main/native/include/frc/controller/ProfiledPIDController.h
wpilibc/src/test/native/cpp/controller/PIDInputOutputTest.cpp
wpilibc/src/test/native/cpp/controller/ProfiledPIDInputOutputTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/PIDController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/controller/ProfiledPIDController.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/PIDInputOutputTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/controller/ProfiledPIDInputOutputTest.java

The inputs should all be errors, so the range should be symmetric.
Fixes #3168.

[wpilib] Fix PIDController continuous range error calculations

---

wpimath/.styleguide
wpimath/eigen-maybe-uninitialized.patch
wpimath/src/main/native/eigeninclude/Eigen/src/Core/util/DisableStupidWarnings.h
wpimath/update_eigen.py

GCC 11 emits a false positive when compiling Eigen and breaks the
allwpilib build.
Fixes #3363.

Suppress the -Wmaybe-uninitialized warning in Eigen

---

wpilibc/src/main/native/include/frc/Base.h

frc/Base.h isn't the first header included basically anywhere, so the
compiler will fail on C++17 things before the asserts in this header are
processed.

[wpilibc] Remove C++ compiler version static asserts

---

wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibc/src/main/native/cpp/AnalogTrigger.cpp
wpilibc/src/main/native/cpp/DigitalGlitchFilter.cpp
wpilibc/src/main/native/include/frc/AnalogTrigger.h
wpilibc/src/main/native/include/frc/DigitalGlitchFilter.h

The removal of ErrorBase allowed the defaults to be used in more places.

Use default copies and moves when possible

---

simulation/halsim_ws_server/src/test/native/cpp/main.cpp

I've seen the digital output test fail on Linux and the digital input
test fail on macOS.

[simulation] Disable flaky web server integration tests

---

wpilibc/src/main/native/cpp/simulation/ADXRS450_GyroSim.cpp
wpilibc/src/main/native/cpp/simulation/AnalogEncoderSim.cpp
wpilibc/src/main/native/cpp/simulation/DutyCycleEncoderSim.cpp
wpilibc/src/main/native/cpp/simulation/SimDeviceSim.cpp

Also clean up several sim classes to use the channel constructor.

[wpilibc] SimDeviceSim: use fmtlib

---

wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/cpp/Relay.cpp
wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/cpp/motorcontrol/NidecBrushless.cpp
wpilibc/src/main/native/cpp/motorcontrol/PWMMotorController.cpp
wpilibc/src/main/native/include/frc/MotorSafety.h
wpilibc/src/main/native/include/frc/Relay.h
wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibc/src/main/native/include/frc/drive/KilloughDrive.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibc/src/main/native/include/frc/drive/RobotDriveBase.h
wpilibc/src/main/native/include/frc/motorcontrol/NidecBrushless.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMMotorController.h

This is only called in an error condition, so it's not necessary to over
optimize it.

[wpilibc] MotorSafety::GetDescription(): Return std::string

---

shared/jni/setupBuild.gradle
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Robot.java
wpimath/src/main/java/edu/wpi/first/math/filter/SlewRateLimiter.java
wpimath/src/main/native/include/frc/SlewRateLimiter.h
wpimath/src/test/java/edu/wpi/first/math/filter/SlewRateLimiterTest.java
wpimath/src/test/native/cpp/SlewRateLimiterTest.cpp
wpiutil/src/main/java/edu/wpi/first/wpiutil/WPIUtilJNI.java
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/test/java/edu/wpi/first/wpiutil/WPIUtilJNITest.java

Timer was replaced with wpi::Now() to avoid a dependency on other wpilib
classes.

Move SlewRateLimiter from wpilib to wpimath

---

shared/config.gradle

This will make sure we catch any bugs for missing runtime dependencies before they become bigger problems.
Only done on rio, as iirc mac spits out a bunch of warnings by default.

Force all linker warnings to be fatal for rio builds

---

wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/Constants.h
wpimath/src/main/java/edu/wpi/first/math/system/plant/LinearSystemId.java
wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h

The units for angular Kv and Ka were inconsistent with the derivation. A
second factory function overload was added for angular units that uses a
trackwidth to convert to the other form.
This breaks existing C++ code since the units are part of the function
signature.

[wpimath] Fix drivetrain system identification

---

wpilibc/src/main/native/include/frc/AsynchronousInterrupt.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AsynchronousInterrupt.java

[wpilib] Fix a documentation typo

---

wpimath/src/main/native/include/frc/fmt/Eigen.h
wpimath/src/main/native/include/frc/fmt/Units.h
wpimath/src/test/native/cpp/FormatterTest.cpp

This allows using Eigen matrices or units natively with fmt::format() or
fmt::print().

[wpimath] Add fmtlib formatter overloads for Eigen::Matrix and units

---

shared/plugins/setupBuild.gradle
simulation/halsim_ws_core/build.gradle

This allows sim modules to be statically linked into an executable to
create a "perfectly static" simulated desktop program. The entry point
was changed to be unique when building static libraries to avoid symbol
collisions.

[build] Also build sim modules as static libraries

---

wpimath/src/main/java/edu/wpi/first/math/Drake.java
wpimath/src/main/java/edu/wpi/first/math/controller/LinearQuadraticRegulator.java
wpimath/src/main/native/cpp/controller/LinearQuadraticRegulator.cpp
wpimath/src/main/native/cpp/drake/math/discrete_algebraic_riccati_equation.cpp
wpimath/src/main/native/include/drake/math/discrete_algebraic_riccati_equation.h
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h

This is useful for implementing implicit model following. An LQR
template specialization was also added for 2x2 systems since differential drive
velocity controllers have that dimensionality.

[wpimath] Add DARE solver for Q, R, and N with LQR ctor overloads

---

.clang-tidy

This generates warnings for using fmt::print() in main(), which is a
case we're okay with.

[build] clang-tidy: Remove bugprone-exception-escape

---

hal/src/main/native/athena/Accelerometer.cpp
hal/src/test/native/cpp/mockdata/AnalogInDataTests.cpp
hal/src/test/native/cpp/mockdata/AnalogOutDataTests.cpp
hal/src/test/native/cpp/mockdata/DIODataTests.cpp
hal/src/test/native/cpp/mockdata/I2CDataTests.cpp
hal/src/test/native/cpp/mockdata/PCMDataTests.cpp
hal/src/test/native/cpp/mockdata/PDPDataTests.cpp
hal/src/test/native/cpp/mockdata/PWMDataTests.cpp
hal/src/test/native/cpp/mockdata/RelayDataTests.cpp
hal/src/test/native/cpp/mockdata/SPIDataTests.cpp
simulation/halsim_gazebo/src/main/native/cpp/GazeboAnalogIn.cpp
wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cpp/Relay.cpp

HAL functions don't set the status variable on success, so it's possible
to use the status variable in an uninitialized state.

Ensure HAL status variables are initialized to zero

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilterLatencyCompensator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/KalmanFilterLatencyCompensator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

This also fixes a member function name inconsistency between languages
and adds missing documentation to C++'s KalmanFilterLatencyCompensator.
Fixes #3229.

[wpimath] Reset error covariance in pose estimator ResetPosition()

---

.github/workflows/gradle-wrapper-validation.yml
.github/workflows/lint-format.yml

This makes the formatter run when pushing to local forks before a pull
request is made.

Run "Lint and Format" CI job on push as well as pull request

---

hal/src/main/native/athena/FRCDriverStation.cpp
wpilibc/src/main/native/cpp/PowerDistributionPanel.cpp
wpilibc/src/main/native/include/frc/PowerDistributionPanel.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistributionPanel.java

The HAL functions already had more descriptive comments in their corresponding headers.

Move Doxygen comments to headers (NFC)

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardInstance.cpp
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardValue.h

This avoids the possibility of it being accidentally sliced by users.

[wpilibc] Make ShuffleboardValue non-copyable

---

wpilibcExamples/src/main/cpp/examples/DifferentialDriveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/DifferentialDrivePoseEstimator/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/DriveTrain.cpp
wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/RamseteController/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/RomiReference/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/TankDriveXboxController/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/DriveTrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyrodrivecommands/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbottraditional/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/subsystems/DriveTrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecontroller/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/romireference/subsystems/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/tankdrive/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/tankdrivexboxcontroller/Robot.java

The right motors of a DifferentialDrive are no longer automatically
inverted (#3340) so it needs to be done explicitly.
Closes #3405

[examples] Invert right side of drive subsystems

---

.github/workflows/cmake.yml
.github/workflows/gazebo.yml
.github/workflows/gradle.yml

This reverts commit d068fb321fa912a2e8685acd7728de1f19a3ee64 (#3420).
The 18.04 docker images now use GCC 8, which was the original reason for
updating.  20.04 uses a much more recent libc, so staying with 18.04
enables more Linux platforms to use the binaries.

[build] Change CI back to 18.04 docker images

---

wpilibjExamples/build.gradle

The state-space differential drive simulation example in #3366 was failing because wpimathjni would not be found on the library path (that PR introduces changes where JNI needs to be called).

[wpilibjexamples] Add wpimathjni, wpiutiljni to library path

---

ntcore/src/main/native/cpp/LoggerImpl.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

This is a breaking change (it changes LogMessage::filename from const
char* to std::string) but there should be few users of it.

[ntcore] Fix dangling pointer in logger

---

ntcore/doc/networktables2.adoc
ntcore/doc/networktables3.adoc

[ntcore] Use "NetworkTables" instead of "Network Tables" in NT specs

---

wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp

The current 2021.3.1 release refers to `java/lang/IOException` which causes the following exception when using `toPathweaverJson` or `fromPathweaverJson`:
```
java.lang.NoClassDefFoundError: java/lang/IOException
at edu.wpi.first.math.WPIMathJNI.fromPathweaverJson(Native Method)
at edu.wpi.first.wpilibj.trajectory.TrajectoryUtil.fromPathweaverJson(TrajectoryUtil.java:79)
```

[wpimath] Fix IOException path in WPIMath JNI

---

wpimath/src/main/java/edu/wpi/first/math/Matrix.java
wpimath/src/main/java/edu/wpi/first/math/controller/LinearPlantInversionFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/LinearQuadraticRegulator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/system/Discretization.java
wpimath/src/main/java/edu/wpi/first/math/system/LinearSystem.java
wpimath/src/main/java/edu/wpi/first/math/system/NumericalIntegration.java
wpimath/src/main/native/include/frc/system/NumericalIntegration.h
wpimath/src/test/java/edu/wpi/first/math/StateSpaceUtilTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/UnscentedKalmanFilterTest.java
wpimath/src/test/java/edu/wpi/first/math/system/DiscretizationTest.java
wpimath/src/test/java/edu/wpi/first/math/system/NumericalIntegrationTest.java
wpimath/src/test/java/edu/wpi/first/math/system/RungeKuttaTimeVarying.java
wpimath/src/test/java/edu/wpi/first/math/system/RungeKuttaTimeVaryingTest.java
wpimath/src/test/native/cpp/system/DiscretizationTest.cpp
wpimath/src/test/native/cpp/system/NumericalIntegrationTest.cpp
wpimath/src/test/native/cpp/system/RungeKuttaTimeVaryingTest.cpp
wpimath/src/test/native/include/frc/system/RungeKuttaTimeVarying.h

* Rename Butcher tableau sections in NumericalIntegration such that
top-left is c, top-right is A, and bottom-right is b
* Move edu.wpi.first.math.Discretization to
edu.wpi.first.math.system.Discretization
* Sort Java Discretization to match C++ function order
* Add tests for Java Discretization
* Required adding Runge-Kutta time-varying impl to tests
* Move C++ Runge-Kutta time-varying impl to tests only
* Users don't need it

[wpimath] Clean up NumericalIntegration and add Discretization tests

---

wpilibcExamples/src/main/cpp/examples/TankDrive/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json

This is a basic C++ example that demonstrates a simple differential drive implementation using “tank”-style controls through the DifferentialDrive class and an ordinary joystick.

[examples] Create Robot.cpp for TankDrive with ordinary joystick

---

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/include/frc/IterativeRobotBase.h
wpilibc/src/test/native/cpp/TimedRobotTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/TimedRobotTest.java

Currently, we have functions like TeleopInit() for running code on mode
entry, but no such functions for running code on mode exit, and it's
cumbersome to add those in user code without making a custom robot
class. This PR adds exit functions to TimedRobot.
Some example use cases include DisabledFinal() for operations when the
robot enables (whether that be into teleop, autonomous, or test) and
AutonomousFinal() for disabling feedback controllers.

[wpilib] Add TimedRobot functions for running code on mode exit

---

.github/workflows/gazebo.yml

Only build the Gazebo simulation projects instead of all of WPILib.

Shorten Gazebo CI build

---

.github/workflows/gradle.yml
.github/workflows/lint-format.yml
README.md
build.gradle
shared/java/javastyle.gradle
wpilibjExamples/build.gradle

This saves time in CI spent performing the same source-level checks in
every build job. Checkstyle, PMD, and Spotless are now run once in the
"Lint and Format" job.
The -PskipPMD flag was replaced with a -PskipJavaFormat flag that
disables Checkstyle, PMD, and Spotless.

Remove Java formatting from build task in CI

---

wpilibcIntegrationTests/src/main/native/cpp/DMATest.cpp

"DISABLED_" must be a prefix, not a suffix.

[wpilibcIntegrationTests] Properly disable DMA integration tests

---

hal/src/main/native/athena/Threads.cpp
hal/src/main/native/cpp/jni/ThreadsJNI.cpp
hal/src/main/native/include/hal/Errors.h
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/Threads.h
wpilibcIntegrationTests/src/main/native/cpp/PriorityTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PriorityTest.java

This PR gives the Notifier HAL thread RT priority 40 in RobotBase after
HAL initialization and before the user code is run. This drastically
improves scheduling jitter for TimedRobot's AddPeriodic() functions (in
3512's experience).
I didn't set the current thread (user code) as RT because that could
break code that tight loops that currently works now because it won't
relinguish control to the scheduler. TimedRobot code whose periodic
functions always exit in a timely manner (i.e., don't have loop
overruns) should run fine. I'm not exactly sure what effects badly
behaved code will have (Would the robot lock up? Would the robot stay
connected?).
This needs wpilibsuite/GradleRIO#506 for SetProcessPriority() to work.
It wasn't needed for this PR, but it's useful to have for RT
applications.

Set HAL Notifier thread as RT by default

---

.github/workflows/lint-format.yml

Doing it for `wpiformat`, might as well cover all of the auto-formatting options.

[build] Generate spotless patch on failure

---

.gitignore

I know the org doesn't want bazel support, but I don't see why updating the `.gitignore` file should hurt. Would help me out when I switch back to a bazel-less branch so I don't have 4 folders / thousands of untracked files

[gitignore] update gitignore to ignore bazel / clion files

---

hal/src/main/native/athena/Notifier.cpp
hal/src/main/native/include/hal/Errors.h

The HAL Notifier thread is started when the first Notifier is created
and stopped when the last Notifier is destroyed. Currently,
HAL_SetNotifierThreadPriority() will cause a segfault if the Notifier thread
hasn't been started yet (that is, if no Notifier have been created yet).
This change makes HAL_SetNotifierThreadPriority() store the RT and
priority setting. If the thread has already been started, it will set
the priority immediately. If it hasn't, HAL_InitiailizeNotifier() will
set the priority when it starts the thread.

Fix HAL Notifier thread priority setting

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/native/include/frc/filter/LinearFilter.h
wpimath/src/test/java/edu/wpi/first/math/filter/LinearFilterTest.java
wpimath/src/test/native/cpp/filter/LinearFilterOutputTest.cpp

This is an alternative to #2344 that handles arbitrary order derivatives
of arbitrary precision. The downside is that since it's part of
LinearFilter, it can't utilize the units type system in the same way to
make Calculate()'s input type different from its output type.

Add LinearFilter::BackwardFiniteDifference()

---

googletest/CMakeLists.txt
googletest/CMakeLists.txt.in
ntcore/CMakeLists.txt
wpiutil/src/test/native/cpp/span/test_span.cpp

This upgrade uncovered two issues:
ntcore wasn't forcing C++17, which caused a linker error with googletest
Matcher symbols:
```
undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::basic_string_view<char, std::char_traits<char> >)'
```
test_span.cpp wasn't including `<algorithm>` to use std::sort() and
std::is_sorted().

Upgrade CMake build to googletest 1.11.0

---

docs/build.gradle

Embeds source in javadocs.
Fixes #3547

enable -linksource for javadocs

---

wpilibc/src/main/native/cpp/AnalogTrigger.cpp

Fixes #3542.
Co-authored-by: Peter Johnson <johnson.peter@gmail.com>

Fix AnalogTriggerOutput memory leak reported by asan

---

wpilibc/src/main/native/include/frc/ADXRS450_Gyro.h
wpilibc/src/main/native/include/frc/AnalogGyro.h
wpilibc/src/main/native/include/frc/AsynchronousInterrupt.h
wpilibc/src/main/native/include/frc/Counter.h
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/GenericHID.h
wpilibc/src/main/native/include/frc/Solenoid.h
wpilibc/src/main/native/include/frc/motorcontrol/DMC60.h
wpilibc/src/main/native/include/frc/motorcontrol/Jaguar.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMMotorController.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMSparkMax.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMTalonFX.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMTalonSRX.h
wpilibc/src/main/native/include/frc/motorcontrol/PWMVictorSPX.h
wpilibc/src/main/native/include/frc/motorcontrol/SD540.h
wpilibc/src/main/native/include/frc/motorcontrol/Spark.h
wpilibc/src/main/native/include/frc/motorcontrol/Talon.h
wpilibc/src/main/native/include/frc/motorcontrol/Victor.h
wpilibc/src/main/native/include/frc/motorcontrol/VictorSP.h
wpilibc/src/main/native/include/frc/simulation/DriverStationSim.h

Add % in front of name in order to suppress doxygen link creation. https://www.doxygen.nl/manual/autolink.html
Here's an example of what it looked like before: 
Both Victor and Controller are suppressed. After:

Disable doxygen linking for common words that are also classes

---

wpimath/src/main/native/include/frc/StateSpaceUtil.h
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h
wpimath/src/main/native/include/frc/estimator/MerweScaledSigmaPoints.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/system/Discretization.h

Internal headers are no longer allowed as of
https://gitlab.com/libeigen/eigen/-/merge_requests/631. Based on
benchmarking I conducted in that thread, there doesn't seem to be a
performance penalty for including the full headers anymore.

[wpimath] Use external Eigen headers only

---

hal/src/main/java/edu/wpi/first/hal/HALUtil.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/sim/HAL.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibc/src/main/native/include/frc/RuntimeType.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RuntimeType.java

In some cases, knowing roborio 2 might be useful. This also creates a higher level enum that might be usable later for the discussion on more complex runtime types.

Update runtime enum to allow selecting roborio 2

---

wpiutil/src/main/native/include/wpi/jni_util.h

These make it usable more like a standard container.

[wpiutil] jni_util: Add size, operator[] to JArrayRef

---

wpiutil/src/main/native/include/wpi/CallbackManager.h
wpiutil/src/main/native/include/wpi/UidVector.h

This makes it possible to erase and then do additional cleanup (e.g. on a unique_ptr).

[wpiutil] UidVector: Return old object from erase()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java
wpiutil/src/main/java/edu/wpi/first/util/function/BooleanConsumer.java
wpiutil/src/main/java/edu/wpi/first/util/function/FloatConsumer.java
wpiutil/src/main/java/edu/wpi/first/util/function/FloatSupplier.java
wpiutil/src/main/java/edu/wpi/first/util/sendable/SendableBuilder.java

The standard Java package is missing BooleanConsumer as well as Float classes.
Update SendableBuilder to use it instead of internal BooleanConsumer
interface.

[wpiutil] Add Java function package

---

.github/workflows/sanitizers.yml
CMakeLists.txt

* Address sanitizer uses -DCMAKE_BUILD_TYPE=Asan
* Thread sanitizer uses -DCMAKE_BUILD_TYPE=Tsan
* Undefined behavior sanitizer uses -DCMAKE_BUILD_TYPE=Ubsan
Only ubsan is enabled in CI for now because asan and tsan report
failures.

Add CMake build support for sanitizers

---

wpimath/src/main/native/include/frc/filter/LinearFilter.h

Since BackwardFiniteDifference() gives it a compile-time constant, it
can be evaluated in a constexpr context.

[wpimath] Make LinearFilter::Factorial() constexpr

---

ntcore/src/main/native/cpp/Handle.h
ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/InstanceImpl.h
ntcore/src/test/java/edu/wpi/first/networktables/ConnectionListenerTest.java
ntcore/src/test/java/edu/wpi/first/networktables/EntryListenerTest.java
ntcore/src/test/native/cpp/ConnectionListenerTest.cpp
ntcore/src/test/native/cpp/EntryListenerTest.cpp

Now that there are only 16 instances, store them all statically.

[ntcore] Match standard handle layout, only allow 16 instances

---

wpilibc/src/main/native/cpp/smartdashboard/MechanismRoot2d.cpp
wpilibc/src/main/native/include/frc/smartdashboard/MechanismRoot2d.h

Fix CPP MechanisimRoot2D to use same NT entries as Java/Glass

---

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/Autonomous.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/DriveStraight.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetDistanceToBox.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/TankDrive.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/include/RobotContainer.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/Autonomous.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/DriveStraight.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/SetDistanceToBox.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/TankDrive.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/PacGoat/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/PacGoat/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/PacGoat/include/Robot.h
wpilibcExamples/src/main/cpp/examples/PacGoat/include/subsystems/Drivetrain.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/Autonomous.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/DriveStraight.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/SetDistanceToBox.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/TankDrive.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/pacgoat/subsystems/Drivetrain.java
wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/native/include/frc/controller/HolonomicDriveController.h

Drivetrain is one word, not two.

[examples] Rename DriveTrain classes to Drivetrain

---

ntcore/src/main/native/include/ntcore_c.h
wpilibc/src/main/native/include/frc/Encoder.h
wpiutil/src/main/native/include/wpi/StringMap.h
wpiutil/src/main/native/include/wpi/jni_util.h

I generated lists of includes and uses via
`rg -l deprecated.h | sort -u` and `rg -l WPI_DEPRECATED | sort -u`
respectively. If a file was in the first list but not the second, the
include was unused. If a file was in the second list but not the first,
the include needed to be added.

Remove unused and add missing deprecated.h includes

---

wpilibc/src/main/native/include/frc/Timer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java

Timer reports a negative duration if the sim timing is restarted. This
can be worked around by calling Reset(). Other options included:
1. Have RestartTiming() call Timer::Reset() on a list of instantiated
Timers.
2. Have Timer::Get() reset the timer if it notices time went backwards.
This requires dropping const qualification though, which is a
breaking change that only fixes a minor edge case.
Closes #2732.

[wpilib] Remove Timer lock in wpilibj and update docs

---

hal/src/main/native/athena/Threads.cpp
hal/src/main/native/include/hal/Errors.h

We originally moved to setuid admin so user programs could do other
things requiring admin if they wanted. However, these things, like
setting RT priorities of other processes, can usually be done instead as
admin during the GradleRIO 2022 deploy process, or adding commands to
the robotCommand script. By going back to setcap, we can simplify the
HAL code.

[hal] Use setcap instead of setuid for setting thread priorities

---

wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp

I found these by inspecting the results of the following rg commands:
`rg --multiline 'FindClass\(\s*"'`
`rg 'JClass' -A 1`
Fixes #3660.

[wpimath] Fix classpaths for JNI class loads

---

wpiutil/src/main/native/include/wpi/raw_uv_ostream.h

This enables reuse of a raw_uv_ostream object.

[wpiutil] raw_uv_ostream: Add Reset()

---

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/Autonomous.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/CloseClaw.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/DriveStraight.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/OpenClaw.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/Pickup.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/Place.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/PrepareToPickup.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetDistanceToBox.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetElevatorSetpoint.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/SetWristSetpoint.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/TankDrive.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Claw.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Wrist.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/Autonomous.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/CloseClaw.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/DriveStraight.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/OpenClaw.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/Pickup.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/Place.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/PrepareToPickup.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/SetDistanceToBox.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/SetElevatorSetpoint.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/SetWristSetpoint.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/commands/TankDrive.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Claw.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Wrist.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Wrist.java

Replace pointer constructor arguments with references, and const qualify
getters where possible.
Also remove redundant simulation P gain.
Fixes #1146.

[wpilibcExamples] Make GearsBot use idiomatic C++

---

hal/src/main/native/athena/SPI.cpp

It's a virtual in chipobject, so at risk of breaking. SIt's not necessary, as the index equals the channel

Remove use of getDmaDescriptor from autospi

---

hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/athena/rev/PHFrames.cpp
hal/src/main/native/athena/rev/PHFrames.h
hal/src/main/native/include/hal/REVPH.h

Adds driver functions to support the multiple closed loop compressor control modes on the PH.
Modes include:
- Disabled - Disable closed loop control
- Digital - Use the digital pressure switch
- Turn compressor **on** when digital switch is **closed**
- Turn compressor **off** when digital switch is **open** (includes disconnected)
- Analog - Use the analog pressure sensor with hysteresis between two values
- Turn compressor **on** when analog sensor value is **below** the specified _minimum_ value
- Turn compressor **off** when analog sensor value is **above** the specified _maximum_ value
- Hybrid - Use both digital and analog modes together
- Digital takes priority over analog

Add HAL functions for compressor config modes on REV PH

---

wpilibc/src/main/native/include/frc/SPI.h

```
/home/tav/git/calcmogul/Robot-2020/src/main/cpp/adi/ADIS16470_IMU.cpp: In member function ‘void frc::ADIS16470_IMU::Close()’:
/home/tav/git/calcmogul/Robot-2020/src/main/cpp/adi/ADIS16470_IMU.cpp:427:3: error: deleting object of polymorphic class type ‘frc::SPI’ which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]
427 |   delete m_spi;
|   ^~~~~~~~~~~~
```

[wpilibc] Make SPI destructor virtual since SPI contains virtual functions

---

wpilibc/src/main/native/cpp/PowerDistribution.cpp
wpilibc/src/main/native/include/frc/PowerDistribution.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

Using automatic doesn't work with any module number, so the API is confusing

Remove automatic pd type from module type enum

---

glass/src/app/native/cpp/main.cpp
outlineviewer/src/main/native/cpp/main.cpp

While this is implicit in main(), WinMain() requires an explicit return.

[glass, outlineviewer] Return 0 from WinMain

---

glass/src/lib/native/cpp/other/Drive.cpp

This would crash in debug mode due to an imgui assertion in PathArcTo.

[glass] Fix Drive widget handling of negative rotation

---

wpiutil/src/main/java/edu/wpi/first/util/MulticastServiceResolver.java
wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/MulticastServiceResolver.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/include/wpi/MulticastServiceResolver.h
wpiutil/src/main/native/linux/MulticastServiceResolver.cpp
wpiutil/src/main/native/macOS/MulticastServiceResolver.cpp
wpiutil/src/main/native/windows/MulticastServiceResolver.cpp

Adding a way to read multiple items makes it so you'll never miss an event, but you also need manual reset to not accidentally trigger an empty event.

Switch MulticastResolver to a manual reset event, add way to read multiple

---

cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/JpegUtil.cpp
cscore/src/main/native/cpp/MjpegServerImpl.cpp
cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/linux/UsbCameraProperty.cpp
cscore/src/main/native/linux/UsbUtil.cpp
cscore/src/main/native/windows/UsbCameraImpl.cpp
ntcore/src/main/native/cpp/Storage_load.cpp
ntcore/src/main/native/cpp/networktables/NetworkTable.cpp
ntcore/src/test/native/cpp/WireEncoderTest.cpp
wpiutil/src/main/native/cpp/HttpUtil.cpp
wpiutil/src/main/native/cpp/MimeTypes.cpp
wpiutil/src/main/native/cpp/StringExtras.cpp
wpiutil/src/main/native/include/wpi/SmallString.h
wpiutil/src/main/native/include/wpi/StringExtras.h
wpiutil/src/main/native/include/wpi/UrlParser.h
wpiutil/src/main/native/linux/MulticastServiceResolver.cpp

Unlike std::string and std::string_view, this substr() allows a start
greater than the length of the string, in which case an empty string
is returned.  This matches llvm::StringRef behavior.

[wpiutil] StringExtras: Add substr()

---

wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui_internal.h

WindowSizeCallback can sometimes be called while doing a render. If this occurs, imgui asserts. Avoid this case

Don't recursively render frames

---

hal/src/main/java/edu/wpi/first/hal/ControlWord.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/DSControlWord.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

The root cause of https://github.com/wpilibsuite/allwpilib/issues/3747 is CommandScheduler's ds state checks are behind iterative robots checks. This means that the iterative robot state could return enabled, but the DS cache could still be reporting disabled. This results in a race in the Disabled -> Enabled transition, which manifests in commands not running.
Previously, iterative robot base pulled from the DS cache. This meant that the ds cache was always updated before an iterative robot base loop could run. This still had a race, but this could only occur on the Enabled -> Disable transition, which is much less noticeable and would usually just result in a command running for an extra loop. 
We can move back to the old behavior by grabbing the new iterative robot base check variables …

Use DS cache for iterative robot control word cache

---

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibc/src/main/native/include/frc/DutyCycleEncoder.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java

As the sensor needs to maintain an actual duty cycle, it can't go all
the way from 0-100, so provide a way to set the min and max and linearly
map between the two.
Not sure if SetDutyCycleRange() is the best name, or SetSensorRange() might be better?
The default range is 0-1 so this is a non-breaking change.

[wpilib] DutyCycleEncoder: add setting of duty cycle range

---

styleguide/spotbugs-exclude.xml
wpilibc/src/main/native/cpp/smartdashboard/MechanismLigament2d.cpp
wpilibc/src/main/native/cpp/smartdashboard/MechanismRoot2d.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismLigament2d.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismObject2d.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismRoot2d.java

UpdateEntries() and Flush() are called from methods that lock the mutex,
so locking it again will cause deadlocks. This also updates the Java
code to make MechanismObject2d::update synchronized like in the C++
version.
Closes #3766

[wpilib] Fix deadlocks in Mechanism2d et al.

---

wpilibcExamples/src/main/cpp/examples/RomiReference/cpp/subsystems/OnBoardIO.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/include/Drivetrain.h

These caused the code to crash when running.

Fix duplicate port allocations in SwerveBot/SwerveDrivePoseEstimator/RomiReference

---

hal/src/main/native/athena/PowerDistribution.cpp
hal/src/main/native/athena/REVPDH.cpp
hal/src/main/native/athena/REVPDH.h
hal/src/main/native/athena/rev/PDHFrames.cpp
hal/src/main/native/athena/rev/PDHFrames.h

Changes:
- Refactors retrieving the faults from the device to match the implementation that we have for the Pneumatic Hub. Instead of having a getter function for each fault, there is a single function to get all faults (sticky or normal) for use with the higher level API
- Renames functions to be consistent
- Removes some functions that don't need to be included in wpilib:
- Identify device - this just flashes the module LED on the device and has no use in wpilib
- Is PDH enabled - the PDH does not change state depending on robot enabled state
- PDH frame and signal names were updated in our DBC, and this PR makes use of the newly generated CAN frame helper functions

[hal] Refactor REV PDH

---

hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/athena/rev/PHFrames.cpp
hal/src/main/native/athena/rev/PHFrames.h
hal/src/main/native/include/hal/REVPH.h

This PR includes the remaining HAL functions needed to fully support the Pneumatic Hub and its latest firmware.
- Clear sticky faults
- Get device voltage
- Get 5v supply voltage (used for analog to PSI calculation)
- Get solenoid voltage
- Get solenoid current
- Get device firmware and hardware version
Some minor refactoring was done for naming of some internal functions for consistency purposes.

[hal] Add remaining driver functions for REV PH

---

wpilibc/src/main/native/cppcs/RobotBase.cpp

With the change from GetInstance to static functions, many functions
don't call DriverStation::GetInstance(), so the DS thread wasn't
getting started by default.  Call InDisabled() to make sure this
happens.

[wpilibc] Kick off DriverStation thread from RobotBase

---

glass/src/lib/native/cpp/hardware/Encoder.cpp
glass/src/lib/native/cpp/hardware/PCM.cpp
glass/src/lib/native/cpp/other/DeviceTree.cpp

The new storage approach was attempting to save both the name and the
open status to the same storage key.
Fixes #3789.

[glass] Fix CollapsingHeader in Encoder, PCM, and DeviceTree

---

cscore/src/main/native/windows/UsbCameraImpl.cpp

shared_from_this will assert if the shared pointer is in the middle of being destructed. Because we access shared_from_this in the message pump, this can easily occur. The solution is to grab the weak pointer, manually attempt to lock it, and only continue if that succeeds. The message pump is already synchronized to the usb camera being destructed, so this is a fine behavior.

[cscore] Fix crash when usbcamera is deleted before message pump thread fully starts.

---

hal/src/main/native/sim/Notifier.cpp

Fixes the following compiler warning:
```
/__w/allwpilib/allwpilib/hal/src/main/native/sim/Notifier.cpp:323:21: error: 'char* strncpy(char*, const char*, size_t)' specified bound 64 equals destination size [-Werror=stringop-truncation]
std::strncpy(arr[num].name, notifier->name.c_str(),
~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sizeof(arr[num].name));
~~~~~~~~~~~~~~~~~~~~~~
```

Don't copy byte to where null terminator goes

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java

This will allow it to be passed as a BooleanSupplier to commands, allowing querying of trigger state while not exposing anything else (like the command-button binding methods) or the overhead of creating a method ref.

[wpilibj] Trigger: implement BooleanSupplier interface

---

wpiutil/src/main/native/cpp/MulticastServiceResolver.cpp
wpiutil/src/main/native/include/wpi/MulticastServiceResolver.h

I'm not sure what I was thinking when I wrote it. It does not need to be a double pointer array at all.

Fix MulticastServiceResovler C array returning functions

---

imgui/CMakeLists.txt.in
shared/config.gradle

The GLFW upgrade fixes joysticks not being mapped at startup.

[wpigui] Upgrade to imgui 1.86, GLFW 3.3.6

---

wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp

DriveSubsystem::SetModulesStates applies module state to incorrect modules. Fixes issue https://github.com/wpilibsuite/allwpilib/issues/3814#issue-1086313694

Fix SwerveControllerCommand example code order of Module States

---

wpilibc/src/test/native/cpp/simulation/DifferentialDrivetrainSimTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSimTest.java

Also rename C++ test file to match class name.
Fixes #3818.

[wpilib] Fix trajectory sampling in DifferentialDriveSim test

---

wpimath/src/main/native/include/frc/trajectory/constraint/DifferentialDriveKinematicsConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/DifferentialDriveVoltageConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/MecanumDriveKinematicsConstraint.h
wpimath/src/main/native/include/frc/trajectory/constraint/SwerveDriveKinematicsConstraint.h

This avoids stack-use-after-scope bugs in code like the following when
the original argument goes out of scope:
```cpp
frc2::Command* RobotContainer::GetAutonomousCommand() {
// Create a voltage constraint to ensure we don't accelerate too fast
frc::DifferentialDriveVoltageConstraint autoVoltageConstraint(
frc::SimpleMotorFeedforward<units::meters>(
DriveConstants::ks, DriveConstants::kv, DriveConstants::ka),
DriveConstants::kDriveKinematics, 10_V);
```

[wpimath] Make copies of trajectory constraint arguments

---

.wpilib/wpilib_preferences.json

This means VSCode won't prompt to upgrade (added in beta 4)

Change project year to intellisense

---

wpilibc/src/main/native/cpp/counter/Tachometer.cpp
wpilibc/src/main/native/include/frc/counter/Tachometer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/Tachometer.java
wpimath/src/main/java/edu/wpi/first/math/util/Units.java
wpimath/src/main/native/include/units/angular_velocity.h

We standardize on seconds elsewhere, so it doesn't make sense for this to return in minutes (especially given typical relevant timescales for robot mechanisms).

change tachometer units to RPS from RPM

---

wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp

This exposes the equivalent of SetNowImpl(nullptr) to Java.

[wpiutil] Add disableMockTime to JNI

---

wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/cpp/timestamp.cpp
wpiutil/src/main/native/include/wpi/timestamp.h

This portably gets the time in microseconds since the Unix epoch.

[wpiutil] Add GetSystemTime()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

previously `Trigger` could only be debounced on rising edges.  This preserves the default behavior but adds an override.

expose debouncetype through trigger

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

[wpilibj] DriverStation: Set thread interrupted state

---

hal/src/main/native/include/hal/Types.h

Enumerations with fixed underlying type have been proposed for C2x in [N2575](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2575.pdf). It turns out that Clang already supports this in C since Clang 8.
This will allow static analysis tools that use clang to always determine the correct intended parameter types for HAL functions.

[hal] Use fixed size enums in clang C

---

wpigui/.styleguide
wpigui/CMakeLists.txt
wpigui/build.gradle
wpigui/src/main/native/cpp/wpigui.cpp

It was only being used for fs::remove() (added in #3463), which is easily
replaced by std::remove().

[wpigui] Remove wpiutil linkage

---

wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibc/src/main/native/cpp/PneumaticsControlModule.cpp
wpilibc/src/main/native/include/frc/Compressor.h
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibc/src/main/native/include/frc/PneumaticsBase.h
wpilibc/src/main/native/include/frc/PneumaticsControlModule.h
wpilibc/src/test/native/cpp/simulation/REVPHSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsControlModule.java

This adds the REV Analog Pressure Sensor PSI to volt (and vice versa) conversion to allow setting the compressor config in PSI and getting the sensor reading in PSI. Also adds input validation for pressure values in the API

Use PSI for compressor config and sensor reading

---

wpilibc/src/main/native/cpp/shuffleboard/SendableCameraWrapper.cpp
wpilibc/src/main/native/include/frc/shuffleboard/SendableCameraWrapper.h
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardContainer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/SendableCameraWrapper.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardContainer.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/shuffleboard/SendableCameraWrapperTest.java

Useful for adding cameras that are streamed from a coprocessor
Updated version of #1794.
Closes wpilibsuite/shuffleboard#582
Closes wpilibsuite/shuffleboard#598
Closes #1587

[wpilib] Allow SendableCameraWrappers to take arbitrary URLs

---

wpilibc/src/main/native/cpp/ADIS_16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h

When trying to import both ADIS Gyro header files, there are conflicts resulting from the fact that they use the same variables for several of their constants:
```
In file included from /home/piphi5/sysid/sysid-library/src/main/cpp/generation/SysIdSetup.cpp:13:0:   
/home/piphi5/.gradle/caches/transforms-3/f74ac6689150164c139413250433f98a/transformed/wpilibc-cpp-2022.1.1-beta-4-26-gf401ea9-headers/frc/ADIS16470_IMU.h:167:14: error: redefinition of 'const double frc::grav' 
const double grav = 9.81; 
^~~~                                                                                                                                                                                                                           In file included from …
```

Make constants ADIS Gyro Constants private

---

hal/src/main/native/athena/REVPDH.cpp
hal/src/main/native/athena/REVPH.cpp
wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java

For C++, I used the AssertionFailure error type, because I didn't whether I should add an additional value (like exists for the Jaguar), and if so, where that would belong in the file's order.

Throw exception if the REV Pneumatic Hub firmware version is older than 22.0.0

---

wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/cpp/simulation/ADIS16448_IMUSim.cpp
wpilibc/src/main/native/cpp/simulation/ADIS16470_IMUSim.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibc/src/main/native/include/frc/simulation/ADIS16448_IMUSim.h
wpilibc/src/main/native/include/frc/simulation/ADIS16470_IMUSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADIS16448_IMUSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADIS16470_IMUSim.java

The gyro rate getters were removed since that data isn't available. The "instant" data was actually unfiltered changes in angle.

[wpilib] Make ADIS IMU classes unit-safe

---

wpilibcExamples/src/main/cpp/templates/templates.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json

Previously it was a bit buried (listed after the advanced skeletons).

[templates] Change the template ordering to put command based first

---

wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/cpp/simulation/ADIS16448_IMUSim.cpp
wpilibc/src/main/native/cpp/simulation/ADIS16470_IMUSim.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibc/src/main/native/include/frc/simulation/ADIS16448_IMUSim.h
wpilibc/src/main/native/include/frc/simulation/ADIS16470_IMUSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADIS16448_IMUSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ADIS16470_IMUSim.java

The angular rate is treated somewhat like an angle during calibration,
but the datasheet says it's angular rate. The variables were renamed to
make this clearer.

[wpilib] Add GetRate() to ADIS classes

---

hal/src/main/native/athena/I2C.cpp

Adds HAL layer warning for #3842. This is needed in the case when a
vendor uses the HAL directly rather than using the WPILib I2C class.
This should not result in a duplicate warning for WPILib I2C users due
to the duplicate message checking performed in HAL_SendError().
We don't want to remove the WPILib I2C warning because it gives stack
trace information while the HAL layer one can't.

[hal] Add warning about onboard I2C

---

upstream_utils/update_fmt.py
wpilibc/src/main/native/cpp/PneumaticsBase.cpp
wpiutil/src/main/native/fmtlib/include/fmt/args.h
wpiutil/src/main/native/fmtlib/include/fmt/chrono.h
wpiutil/src/main/native/fmtlib/include/fmt/color.h
wpiutil/src/main/native/fmtlib/include/fmt/compile.h
wpiutil/src/main/native/fmtlib/include/fmt/core.h
wpiutil/src/main/native/fmtlib/include/fmt/format-inl.h
wpiutil/src/main/native/fmtlib/include/fmt/format.h
wpiutil/src/main/native/fmtlib/include/fmt/os.h
wpiutil/src/main/native/fmtlib/include/fmt/ostream.h
wpiutil/src/main/native/fmtlib/include/fmt/printf.h
wpiutil/src/main/native/fmtlib/include/fmt/ranges.h
wpiutil/src/main/native/fmtlib/include/fmt/xchar.h
wpiutil/src/main/native/fmtlib/src/format.cpp
wpiutil/src/main/native/fmtlib/src/os.cpp

The changes to PneumaticsBase.cpp were to fix errors like the following
from enum classes not being formattable:
```
allwpilib/wpilibc/src/main/native/cpp/PneumaticsBase.cpp:36:9:   required from here
allwpilib/wpiutil/src/main/native/fmtlib/include/fmt/core.h:2672:12: error: use of deleted function ‘fmt::v8::detail::fallback_formatter<T, Char, Enable>::fallback_formatter() [with T = frc::PneumaticsModuleType; Char = char; Enable = void]’
2672 |   auto f = conditional_t<has_formatter<mapped_type, context>::value,
|            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2673 |                          formatter<mapped_type, char_type>,
|                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2674 |                          fallback_formatter<T, char_type>>();
| …
```

Upgrade to fmt 8.1.1

---

wpimath/src/main/java/edu/wpi/first/math/controller/LinearQuadraticRegulator.java
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/test/java/edu/wpi/first/math/controller/LinearQuadraticRegulatorTest.java
wpimath/src/test/native/cpp/controller/LinearQuadraticRegulatorTest.cpp

It was using the continuous B matrix to compute the feedback gain
instead of the discrete B matrix.
Tests were added for the matrix constructor overloads.

[wpimath] Fix LQR matrix constructor overload for Q, R, and N

---

CMakeLists.txt

This will only ever be used by GUI applications, and the jar build
method it uses can misbehave in some cross-compile scenarios.

[build] cmake: Move fieldImages to WITH_GUI

---

wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilterLatencyCompensator.java
wpimath/src/main/native/include/frc/estimator/KalmanFilterLatencyCompensator.h

It would crash in C++ if the global measurement was sooner than all the
snapshots.

[wpimath] Fix crash in KF latency compensator

---

wpiutil/src/main/native/include/wpi/array.h
wpiutil/src/test/native/cpp/ArrayTest.cpp

[wpiutil] Fix wpi::array for move-only types

---

wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Drivetrain.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java

Fixes #3907 
Tested in Java & C++.

Use left/rightGroup.Get() for simulator inputs to fix inversions

---

fieldImages/build.gradle
fieldImages/publish.gradle

The C++ version of the field image library had some naming problems which caused it not to get picked up by the combination process, and the java version was never actually published to maven / artifactor. My bad.

[field images] Fixing maven publishing

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

It seems like the JVM does not handle recursive calls to object monitor based locks correctly. A few bugs in the past have been reported to have caused deadlocks if this occurs. It _looks_ like the version of Java we use is fixed, but there could be other bugs, and it seems like this area of the code isn't tested much. Based on the stacks reported in https://github.com/wpilibsuite/allwpilib/issues/3896, it really seems like this is occurring. So we're going to attempt to switch to explicit mutex based classes, which shouldn't have bugs like this, and we will see if that fixes the issue.

Switch ControlWord mutex to actual reentrant mutex

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/SwerveModule.java

Changed `turnOutput` from `var` to `double` in [SwerveModule](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/SwerveModule.java#L101). It doesn't make sense for `driveOutput` and `turnOutput` to have different types so they should both be doubles.

updated type in SwerveModule

---

wpilibc/src/main/native/cpp/PneumaticsControlModule.cpp

Since the CAN bus can easily become disconnected, we don't want this to crash. Instead, we just want this to report errors. This matches previous behavior.

Don't throw exceptions in PCM functions

---

hal/src/main/native/athena/CTREPCM.cpp

A call to the PCM clear function was using the wrong handle passed down to the CAN layer, causing an error.

Fix PCM sticky faults clear function crashing

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java

Reordered the swerve modules and swerve drive kinematics to match the rest of the example. Also, I don't think [m_odometry.update](https://github.com/wpilibsuite/allwpilib/blob/main/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java#L68) would have worked with the previous kinematics ordering.

Reorder SwerveModules in SwerveControllerCommand example odometry update

---

wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibc/src/main/native/include/frc/drive/KilloughDrive.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java

For the drive classes `DifferentialDrive`, `MecanumDrive`, and `KilloughDrive`, in both C++ and Java, I have commented on the WheelSpeeds structs/data classes, as well as on the return tags on the IK methods, to clarify that in drive classes, WheelSpeeds uses normalized voltage units, [-1.0..1.0].

Added docs clarification on units for drive class WheelSpeeds

---

wpimath/src/main/native/include/frc/kinematics/DifferentialDriveOdometry.h

[wpimath] Remove DifferentialDriveKinematics include from odometry

---

wpimath/src/test/native/cpp/filter/LinearFilterOutputTest.cpp

The integer conversion is deliberate.

[wpimath] Fix clang-tidy bugprone-integer-division warning

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java

Some methods for the REV PH in Java were mistakenly not made public. This fixes that.

[wpilibj] Make methods public for REV PH

---

roborioteamnumbersetter/CMakeLists.txt
roborioteamnumbersetter/src/main/native/cpp/App.cpp

We were not setting icons up in RTNS code, and also an incorrect name was used in the cmake build.

Fix rtns icons

---

shared/config.gradle
wpilibcExamples/build.gradle

They take up a LOT of disk space.

Remove debug info from examples

---

wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armsimulation/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json

This shows more real world usage then hardcoding the setpoint and PID
gains. There were no current examples using Preferences. This will also
be used to update frc-docs article for Preferences

Update ArmSimulation example to use Preferences

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java

When a PH object is initialized, the firmware version is retrieved from the device and will be written to a file in _/tmp/frc_version/_, which will be read by NetComm and sent to the driver station. 
For each PH object initialized, there will be a corresponding file named `REV_PH_<CAN_ID>_WPILib_Version.ini` containing the model, deviceID, and currentVersion which are used to be read by NetComm.

[wpilib] Write REV PH firmware version to roboRIO to display on driver station

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp

C++ API asks for  pulse duration parameter in seconds, but treats it as milliseconds.
This PR fixes the units in the REV PH data store to treat the duration as seconds.

[wpilibc] Fix REV PH pulse duration units

---

hal/src/main/native/athena/FRCDriverStation.cpp

The game specific message size might be uninitialized. If this happens, the uninitialized value is > 64, and the DS sends > 64 bytes, we have a buffer overflow. Force the message size to max to fix the issue.

Fix potential gamedata out of bounds read

---

wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java

Also fixes a few related uninitialized variables in C++.

Fix ADIS16448 imu default constructor not working in Java

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/NotifierCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RunCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/StartEndCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/NotifierCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RunCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/StartEndCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandGroupErrorTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp

no longer deprecates the old name

Rename withInterrupt to until

---

glass/src/lib/native/cpp/other/Plot.cpp

This can be called in a delayed manner, so it's possible for
m_size to already be at maximum, which results in writing past
the end of the array. Instead, just call AppendValue().

[glass] Fix PlotSeries::SetSource()

---

glass/src/lib/native/cpp/other/Plot.cpp

2K was sufficient for simulation because it's possible to pause time,
but isn't quite enough for looking at real robot data. 20K points
is 400 seconds at 50 Hz which should make pausing plots much more
useful.
As every point is looped over, this does increase CPU utilization
somewhat but doesn't seem to have much of an impact for typical
use cases. Increasing this further will necessitate some greater
optimizations (e.g. an initial cull using binary search).

[glass] Increase plot depth to 20K points

---

hal/src/main/native/athena/SerialPort.cpp
roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp
simulation/halsim_ws_server/src/dev/native/cpp/main.cpp
wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/cpp/DigitalInput.cpp
wpilibc/src/test/native/cpp/TestCallbackHelpers.cpp
wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp
wpilibc/src/test/native/cpp/simulation/StateSpaceSimTest.cpp
wpimath/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp
wpimath/src/test/native/cpp/spline/QuinticHermiteSplineTest.cpp
wpimath/src/test/native/cpp/trajectory/DifferentialDriveVoltageTest.cpp

The only one that wasn't removed is in portable-file-dialogs.cpp since
the replacement looks less trivial.

Remove uses of iostream

---

simulation/halsim_gui/src/main/native/cpp/HALProvider.cpp

Instead preserve their saved visible state.
Fixes #3996.

[sim] Sim GUI: don't force-show Timing and Other Devices

---

simulation/halsim_gui/src/main/native/cpp/HALSimGui.cpp
simulation/halsim_gui/src/main/native/include/HALSimGui.h

Allows RobotPy to add hooks to gui on windows (https://github.com/robotpy/robotpy-halsim-gui/pull/10)
... seems like maybe you should just export everything? But, this seems like the most useful set of things to export.

Export some of the wpigui functions so they can be linked to

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommand.java
wpilibOldCommands/src/main/java/edu/wpi/first/wpilibj/PIDBase.java

~~Looks like the assertions were copy-pasted from `SwerveControllerCommand` without having the class name updated.~~
Many of the non-null assertions for parameters have incorrect values for the parameter name or class they belong to.

[wpilibj] Fix typos in error messages for non-null assertions

---

wpiutil/src/main/native/libuv/src/unix/thread.cpp

[wpiutil] libuv: Fix sign compare warnings in gcc 11.2

---

wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/test/native/cpp/drive/DifferentialDriveTest.cpp
wpilibc/src/test/native/cpp/drive/KilloughDriveTest.cpp
wpilibc/src/test/native/cpp/drive/MecanumDriveTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/DifferentialDriveTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/KilloughDriveTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/MecanumDriveTest.java

If xSpeed == -0.0 and zRotation > 0, the algorithm assumes it's in the
third quadrant instead of the first since +0.0 == -0.0.
Also added tests for inverse kinematic functions, fixed some
MecanumDrive test bugs, and added Java MecanumDrive.driveCartesianIK()
and KilloughDrive.driveCartesianIK() overloads with defaulted gyro angle
that C++ already had.
Fixes #4022.

[wpilib] Check for signedness in ArcadeDriveIK()

---

wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/include/frc/MotorSafety.h

- Nothing else in that function can throw, so protecting StopMotor should be sufficient
- Fixes #4036
I'm not certain about how the error message will present itself. Will try to provoke this locally and see what happens.

[wpilibc] Prevent StopMotor from terminating robot during MotorSafety check

---

wpilibc/src/main/native/cpp/AnalogEncoder.cpp
wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibc/src/main/native/include/frc/AnalogEncoder.h
wpilibc/src/main/native/include/frc/DutyCycleEncoder.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogEncoder.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java

SetPositionOffset was added. Been requested multiple times, and easy to implement.
The javadocs mentioned GetPositionInRotation. It has tripped up many people how to get the absolute position from the encoder (You currently have to have precreated the DutyCycle object). Add this method (as GetAbsolutePostition) to make this easier to do.
The checks for making sure a matching set of values was read was doing direct double comparisions. This worked ok in the DutyCycle case, but has problems in the analog case. Solve this by using an epsilon comparison.
And finally, scale AnalogEncoders analog input to 0-1 instead of 0-5. This was reported a few years ago, but the issue was missed. This caused the encoder to count from 0-5, then 1-6, then 2-7 etc. This is solved and now works correctly. …

Some API and behavior fixes to absolute encoders

---

wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h

When trying to set the tolerance of a ProfiledPID, it fails if you don't give it a velocity value. It was missing a conversion from double to the appropiate unit.

Fix ProfiledPID SetTolerance default velocity value

---

.github/workflows/cmake.yml
.github/workflows/documentation.yml
.github/workflows/gazebo.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/gradle.yml
.github/workflows/lint-format.yml
.github/workflows/sanitizers.yml

See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
This sets the workflow concurrency to 1 for all workflows. For PRs this means if you push an additional commit older jobs will be cancelled.
The documentation workflow already only runs on tags or merges to main. For this, we cancel previous runs if they are to the same destination (tag or main) but still prevent 2 jobs from running at once if they are spawned from different refs.

Set actions workflow concurrency

---

wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

SwerveDrivePoseEstimator uses velocities, so position resets aren't
needed.
Closes #4065.

[wpimath] Remove SwerveDrivePoseEstimator encoder reset warning

---

wpigui/src/main/native/cpp/wpigui.cpp

- Seems to be intended for resource bundles in MacOS apps, which we don't use
... haven't tested this yet, but maybe later this weekend I'll build everything on OSX and test this.

[wpigui] disable changing directory when initializing on MacOS

---

wpimath/src/main/java/edu/wpi/first/math/StateSpaceUtil.java
wpimath/src/main/native/include/frc/StateSpaceUtil.h

The existing implementation will produce a cost of NaN if a tolerance of
infinity is entered, but the limit approaches zero. Being able to
specify that a state has no cost is useful, so this PR adds support for
that.

[wpimath] Support zero cost entries in MakeCostMatrix()

---

wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h

The Joseph form of the error covariance update equation is more
numerically stable when the Kalman gain isn't optimal. Numerical
instability and filter divergence can occur if the user goes long time
periods between updates and the error covariance becomes ill-conditioned
(the ratio between the largest and smallest eigenvalue gets too large).

[wpimath] Improve EKF numerical stability

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java

Rotation2d.fromRadians() doesn't exist. The constructor should be used
instead.

[wpimath] Fix reference to Rotation2d.fromRadians() (NFC)

---

wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java
wpiutil/src/main/native/include/wpi/DataLog.h

[wpiutil] DataLog: Document finish and thread safety

---

hal/src/main/native/include/hal/AnalogInput.h
hal/src/main/native/include/hal/AnalogOutput.h

If I find more doc misspellings, is there a different process I should follow? I kind of feel like I'm just generating noise in the issue tracker.

[hal] Fix miss-spelling in AnalogInput/Output docs (NFC)

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/ButtonTest.java

When you called `JoystickButton#getAsBoolean` it would always return false as the `get` method it inherited was not used in the `getAsBoolean` defined in the `Trigger` class. I think this should fix it, but I have an M1 mac and do not have the know how to get this to build. I wrote a short test to check if it does.

Fix boolean supplier with buttons

---

wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/include/frc/Compressor.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java

Heya!
A few members on my team confused the `enabled()` function in the compressor class for the function that re-enables the compressor. 
While I did point out that the documentation said the function in question just retrieves whether the compressor is on, and later found the function they should actually be using I couldn't help but notice how easy it was for them (and potentially others) to get confused. 
As a result I added the function `isEnabled()` to replace the `enabled()` function in the compressor clwss with the hope that it will lead to less confusion. 
In order to not have it break existing teams' code I chose to just deprecate the old function and point it to the new one, but keep the functionality the same.

[wpilib] Rename enabled to isEnabled in the compressor class

---

wpimath/src/main/java/edu/wpi/first/math/util/Units.java

degreesToRotations in Units refers to radians in the return value comment instead of degrees.

fix comment in degreesToRotations

---

build.gradle
shared/java/javacommon.gradle
shared/java/javastyle.gradle
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/livewindow/LiveWindow.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/UpDownCounter.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/romireference/sensors/RomiGyro.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/romireference/subsystems/OnBoardIO.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java
wpimath/src/main/java/edu/wpi/first/math/interpolation/TimeInterpolatableBuffer.java
wpiutil/src/main/java/edu/wpi/first/util/sendable/SendableRegistry.java
wpiutil/src/main/native/include/wpi/sendable/SendableRegistry.h

PMD requires that variables only initialized in the constructor be
final. The compiler errors if those final variables aren't guaranteed to
be initialized, so extra else branches were added to ensure that.
PMD also requires that classes with only private constructors be final.
The equivalent C++ classes were finalized as well, except for
TimeInterpolatableBuffer because it doesn't expose factory functions.

Update Java linters and fix new PMD errors

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/ButtonTest.java

Adds ability to do:
```java
button.and(intake::isDeployed).whileActiveContinuous(new RunIntakeCommand(intake));
```
Previously one would have to do:
```java
button.and(new Trigger(intake::isDeployed)).whileActiveContinuous(new RunIntakeCommand(intake));
```
My C++ is very lacking so help on that would be appreciated.

Add ability to use boolean supplier for trigger operations

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CallbackStore.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

They were deprecated for removal in Java 18 because they're error-prone.
Prefer AutoCloseable and Cleaner instead.
https://openjdk.java.net/jeps/421
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ref/Cleaner.html

[wpilibj] Remove finalizers

---

.github/workflows/gradle.yml
gradle.properties

I've had to increase it during local compiles since wpimath artifact
publishing runs out of heap.

Increase Gradle JVM heap size

---

wpiutil/src/main/java/edu/wpi/first/util/CircularBuffer.java

In `CircularBuffer.java`, `size`, `getFirst`, `getLast`, and `resize` are all currently package-private. This PR just adds the public modifier to them.

Make some methods on CircularBuffer public

---

hal/src/main/java/edu/wpi/first/hal/NotifierJNI.java

The previous documentation suggested that `triggerTime` is the interval until the next alarm, but I believe the implementation is that it is the absolute alarm time.

Correct documentation on updateNotifierAlarm

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp

It causes builds with the windows-2022 VM to fail.

Add missing #include

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation2dTest.java

Resolves #4164 
Maybe `fromRotations` can be renamed without a deprecation cycle due to there being no release containing it?

[wpimath] Add Rotation2d.fromRadians factory

---

wpimath/src/main/java/edu/wpi/first/math/InterpolatingMatrixTreeMap.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/cpp/controller/LTVDifferentialDriveController.cpp
wpimath/src/main/native/cpp/controller/LTVUnicycleController.cpp
wpimath/src/main/native/include/frc/controller/LTVDifferentialDriveController.h
wpimath/src/main/native/include/frc/controller/LTVUnicycleController.h
wpimath/src/test/java/edu/wpi/first/math/controller/LTVDifferentialDriveControllerTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/LTVUnicycleControllerTest.java
wpimath/src/test/native/cpp/controller/LTVDifferentialDriveControllerTest.cpp
wpimath/src/test/native/cpp/controller/LTVUnicycleControllerTest.cpp

This adds a unicycle controller that's a drop-in replacement for Ramsete and a differential drive controller that controls the full pose and outputs voltages. The main benefit is LQR-like tuning knobs using a system model.

[wpimath] Add LTV controllers

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc
wpimath/src/test/java/edu/wpi/first/math/kinematics/SwerveDriveKinematicsTest.java
wpimath/src/test/native/cpp/kinematics/SwerveDriveKinematicsTest.cpp

Change was made in the kinematics classes, with documentation+testing to ensure new behaviour functions properly. Swerve module states have the linear velocity updated to 0.0, with the angle being unchanged when calling toSwerveModuleStates() with ChassisSpeeds of [0, 0, 0].
Closes #4204

Conserve previously calculated swerve module angles when updating states for stationary ChassisSpeeds

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp

In addition to m_prevError and m_totalError, m_positionError needs to be reset
to 0 when reset() is called. Otherwise, the next time calculate() is
called, the old value of m_positionError will be used as the previous
error, but this is inaccurate since the caller wanted to reset the state
of the PID controller.

Reset m_positionError when PIDController.reset() is called.

---

wpilibc/src/main/native/cpp/DriverStation.cpp

It was returning a pointer to the axis type array cast to a bool (always
1\) instead of returning the desired axis type.
This was caught by the following warning from GCC 12.1.
```
/home/tav/frc/wpilib/allwpilib/wpilibc/src/main/native/cpp/DriverStation.cpp: In static member function ‘static int frc::DriverStation::GetJoystickAxisType(int, int)’:
/home/tav/frc/wpilib/allwpilib/wpilibc/src/main/native/cpp/DriverStation.cpp:463:39: error: the address of ‘HAL_JoystickDescriptor::axisTypes’ will never be NULL [-Werror=address]
463 |   return static_cast<bool>(descriptor.axisTypes);
|                            ~~~~~~~~~~~^~~~~~~~~
In file included from /home/tav/frc/wpilib/allwpilib/hal/src/main/native/include/hal/DriverStation.h:9,
from …
```

[wpilibc] Fix return value of DriverStation::GetJoystickAxisType()

---

upstream_utils/eigen_patches/0001-Disable-warnings.patch
wpimath/src/main/native/eigeninclude/Eigen/src/Core/util/DisableStupidWarnings.h

It originally only applied to GCC 11. The CMake build passed without
this change, but not the Gradle build.

[wpimath] Extend Eigen warning suppression to GCC 12

---

upstream_utils/upstream_utils.py

This makes update_llvm.py in particular much faster because the full
repo requires fetching 2 GB.

Use shallow clones for thirdparty repos

---

wpilibc/src/main/native/cpp/simulation/CTREPCMSim.cpp
wpilibc/src/main/native/cpp/simulation/DoubleSolenoidSim.cpp
wpilibc/src/main/native/cpp/simulation/PneumaticsBaseSim.cpp
wpilibc/src/main/native/cpp/simulation/REVPHSim.cpp
wpilibc/src/main/native/cpp/simulation/SolenoidSim.cpp
wpilibc/src/main/native/include/frc/simulation/CTREPCMSim.h
wpilibc/src/main/native/include/frc/simulation/DoubleSolenoidSim.h
wpilibc/src/main/native/include/frc/simulation/PneumaticsBaseSim.h
wpilibc/src/main/native/include/frc/simulation/REVPHSim.h
wpilibc/src/main/native/include/frc/simulation/SolenoidSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CTREPCMSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DoubleSolenoidSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PneumaticsBaseSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/REVPHSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SolenoidSim.java

Fixes #3927 
@ThadHouse there isn't a problem here with extra module sim allocations, right?
I also noticed that there's no way to sim a PH's analog sensor, and the `solenoidInitialized` states were removed.

Pneumatics sim

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp

Part of #4234. Instead of a null passed to conditional command I opted to use an `InstantCommand` to avoid NPEs. C++ was patched together so feedback on that would be appreciated. Docs PR to come. Also changed perpetually to endless in the tests.

Unless decorator for commands

---

upstream_utils/stack_walker_patches/0001-Apply-PR-35.patch
upstream_utils/stack_walker_patches/0002-Remove-_M_IX86-checks.patch
upstream_utils/stack_walker_patches/0003-Add-advapi-pragma.patch
upstream_utils/update_stack_walker.py
upstream_utils/upstream_utils.py
wpiutil/src/main/native/windows/StackWalker.cpp
wpiutil/src/main/native/windows/StackWalker.h

TL;DR. Windows line endings suck
From what I can surmise, the failure was caused by a whitespace error because of line endings. I don't know if the "download patch" from github was pulling down `\r\n`, like the repo is and github changed it to be just `\n`. Or maybe my windows computer wasn't doing the autocrlf until I went to commit stuff which caused headaches. Embarrassingly, I also seemed to have dropped two patches when I was moving between branches, and they are now included.
The patches are now part of the repo rather than downloading from the repo, and LF is update is included in the patches.
Tested with my (soon to be obsolete) patch checker branch https://github.com/pjreiniger/allwpilib/tree/beyonce_patches

[upstream utils] Fix stack walker

---

wpiutil/src/main/native/include/wpi/future.h

std::result_of is deprecated in C++17.
Partially Resolves #4291

[wpiutil] Use invoke_result_t instead of result_of in future.h

---

upstream_utils/upstream_utils.py

str.removesuffix() is only available in Python 3.9, which is not in many
Linux installations.

[upstream_utils] Make work with Python 3.8

---

wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java

The original idea of LiveWindow telemetry was to automatically make
telemetry data visible to users.  This has proved increasingly
problematic in recent years due to the "spooky action at a distance"
of telemetry happening for objects that are only constructed but not
used, and blocking or slow object reads resulting in hard-to-debug
loop overrun conditions.

[wpilib] Default off LiveWindow telemetry

---

wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java

Closes #4146
The existing C++ and Java examples differed both in documentation and in code details (such as C++ inverting the y-input but not Java) but for each I stuck closer to the original version. I am also not very proficient at C++ so if that version is lacking help would be appreciated.

Joystick changed to XboxController in gettingstarted example

---

hal/src/test/java/edu/wpi/first/hal/JNITest.java
wpinet/src/main/native/cpp/jni/WPINetJNI.cpp
wpinet/src/test/java/edu/wpi/first/net/WPINetJNITest.java

Package rename was not caught. Added unit test that would have exposed the problem, and also one for the HAL since it was the only JNI that didn't have a test loading it.

[wpinet] Fix JNI loading error

---

hal/src/main/native/cpp/jni/I2CJNI.cpp
hal/src/main/native/cpp/jni/SPIJNI.cpp

I was getting warnings from GCC 12 like the following in I2CJNI.cpp and
SPIJNI.cpp:
```
In file included from /home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/include/wpi/SmallString.h:16,
from /home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/include/wpi/jni_util.h:19,
from /home/tav/frc/wpilib/allwpilib/hal/src/main/native/cpp/jni/I2CJNI.cpp:9:
In member function ‘void wpi::SmallVectorImpl<T>::resizeImpl(size_type) [with bool ForOverwrite = false; T = unsigned char]’,
inlined from ‘void wpi::SmallVectorImpl<T>::resizeImpl(size_type) [with bool ForOverwrite = false; T = unsigned char]’ at /home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/include/wpi/SmallVector.h:594:37,
inlined from ‘void wpi::SmallVectorImpl<T>::resize(size_type) [with T = unsigned char]’ at …
```

Throw exceptions for invalid sizes in I2C and SPI JNI

---

simulation/halsim_gui/build.gradle

This fixes the following linker error:
```
> Task :simulation:halsim_gui:linkHalsim_guiDevLinuxx86-64Executable FAILED
/usr/bin/ld: warning: libwpinetd.so, needed by /home/tav/frc/wpilib/allwpilib/ntcore/build/libs/ntcore/shared/linuxx86-64/debug/libntcored.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/tav/frc/wpilib/allwpilib/ntcore/build/libs/ntcore/shared/linuxx86-64/debug/libntcored.so: undefined reference to `wpi::TCPAcceptor::TCPAcceptor(int, std::basic_string_view<char, std::char_traits<char> >, wpi::Logger&)'
/usr/bin/ld: /home/tav/frc/wpilib/allwpilib/ntcore/build/libs/ntcore/shared/linuxx86-64/debug/libntcored.so: undefined reference to `wpi::TCPConnector::connect_parallel(wpi::span<std::pair<char const*, int> const, 18446744073709551615ul>, wpi::Logger&, …
```

[halsim_gui] Link to wpinet

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandBase.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulingRecursionTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandTestBase.h
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulingRecursionTest.cpp

Resolves #4259.
Resolves #3362.
Checked for if the map returns `null`. Added a test to confirm this has been fixed.

[command] Reorder Scheduler operations

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java

Changed "final" to "exit" in the WPILibJ IterativeRobotBase JavaDoc as "exit" is used in every other instance.

Changed "final" to "exit" in the IterativeRobotBase JavaDoc

---

.github/workflows/gradle.yml

It was running out of heap space.

Use one worker for Windows release Gradle build

---

wpimath/src/main/java/edu/wpi/first/math/controller/DifferentialDriveAccelerationLimiter.java
wpimath/src/main/native/cpp/controller/DifferentialDriveAccelerationLimiter.cpp
wpimath/src/main/native/include/frc/controller/DifferentialDriveAccelerationLimiter.h

Defined trackwidth, added skipped steps to the algorithm's internal
proof, and grouped the algorithm steps more logically with blank lines.

[wpimath] Improve DifferentialDriveAccelerationLimiter docs (NFC)

---

.github/workflows/upstream-utils.yml

This catches issues like update scripts putting new files in a different
directory from the old ones.

[ci] Make upstream_utils CI fail on untracked files

---

hal/src/main/native/athena/cpp/SerialHelper.cpp

From the FRC Discord programming-help channel:
```
Ben | 217 Alum | CTRE Intern — 05/23/2022
Yeah that sounds right from what I'm seeing. Replacing the goto done; with continue; does seem to fix the issue as well (devices show up).
thadhouse WPILib Alumni — 05/23/2022
We should replace all of those goto dones with continue
The logic is already correct for closing all the objects. So we should just be continuing on error.
Since I'm not super concerned about the error if the devices still show up afterwards.
```

[hal] Replace SerialHelper "goto done" with continue

---

wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/RobotContainer.java

When I tried moving the robot in the simulation using a keyboard, I was not able to rotate it. To solve this, I copied the settings from the "Using the Keyboard as a Joystick" section of the [Simulation Specific User Interface Elements](https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-simulation/simulation-gui.html#using-the-keyboard-as-a-joystick:~:text=Using%20the%20Keyboard,%EF%83%81) page. For this reason, I thought it would be helpful if the link was provided. I also added the arcade drive comments from the Java example to the C++ example.

Add comments to StateSpaceDifferentialDrive

---

crossConnIntegrationTests/src/main/native/cpp/PWMTest.cpp
cscore/src/main/native/windows/UsbCameraImpl.cpp
cscore/src/main/native/windows/UsbCameraImpl.h
cscore/src/main/native/windows/UsbCameraProperty.cpp
hal/src/main/native/athena/Accelerometer.cpp
hal/src/main/native/athena/AnalogAccumulator.cpp
hal/src/main/native/athena/DIO.cpp
hal/src/main/native/athena/DMA.cpp
hal/src/main/native/athena/DigitalInternal.cpp
hal/src/main/native/athena/Notifier.cpp
hal/src/main/native/athena/REVPH.cpp
wpigui/src/main/native/directx11/wpigui_directx11.cpp
wpinet/src/main/native/macOS/MulticastServiceAnnouncer.cpp
wpinet/src/main/native/macOS/ResolverThread.cpp
wpiutil/src/main/native/windows/Demangle.cpp

The warnings included recommendations of braces for if statement
readability, a recommendation for default initialization of an int
array, and include-what-you-use (indirectly through clang-tidy reporting
undefined symbols).

Fix clang-tidy warnings

---

wpinet/src/test/native/cpp/MulticastTest.cpp

This fixes an MSVC compilation error with C++20.

[wpinet] include-what-you-use in MulticastTest

---

upstream_utils/update_drake.py
upstream_utils/update_eigen.py
upstream_utils/update_fmt.py
upstream_utils/update_libuv.py
upstream_utils/update_llvm.py
upstream_utils/update_stack_walker.py
upstream_utils/upstream_utils.py

* Root folder variable names are now more descriptive
* clone_repo() now restores the current working directory
* Removed setup_upstream_repo() since it's now identical to clone_repo()
* Moved am_patches()'s for loop into user scripts so the filename prefix
doesn't need to be included in every patch filename
* Renamed am_patches() to git_am() since its only job now is to run "git am"
* Removed unused apply_patches() function
* Fixed typo in git_am()'s ignore_whitespace arg name

[upstream_utils] Refactor upstream_utils scripts

---

docs/build.gradle

Doxygen 1.9.2 requires libclang-9, which is no longer available on
Ubuntu 22.04.

[docs] Upgrade to doxygen 1.9.4

---

wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/cpp/controller/LTVDifferentialDriveController.cpp
wpimath/src/main/native/cpp/controller/LTVUnicycleController.cpp

The LTV differential drive controller derivation wasn't included inline
because it's too long.

[wpimath] Add LTV controller derivations and make enums private

---

wpiutil/src/main/native/include/wpi/jni_util.h

Mac has jlong == long long and int64_t = long, so the types are
incompatible despite being the same size.

[wpiutil] jni_util: Add Mac-friendly MakeJLongArray

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelCommandGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelRaceGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SequentialCommandGroup.java
wpilibNewCommands/src/main/native/include/frc2/command/ParallelCommandGroup.h
wpilibNewCommands/src/main/native/include/frc2/command/ParallelDeadlineGroup.h
wpilibNewCommands/src/main/native/include/frc2/command/ParallelRaceGroup.h
wpilibNewCommands/src/main/native/include/frc2/command/SequentialCommandGroup.h

Piecemeal replacement of #3608 in an attempt to advance #3536.

[commands] Mark command group lifecycle methods as final

---

wpimath/src/main/java/edu/wpi/first/math/filter/SlewRateLimiter.java
wpimath/src/main/native/include/frc/filter/SlewRateLimiter.h
wpimath/src/test/java/edu/wpi/first/math/filter/SlewRateLimiterTest.java
wpimath/src/test/native/cpp/filter/SlewRateLimiterTest.cpp

Adds the option to have a separate positive and negative rate limit in the `SlewRateLimiter`. 
As of now, the change silently breaks the `SlewRateLimiter(double rateLimit, double initialValue)` constructor in favor of `SlewRateLimiter(double positiveRateLimit, double negativeRateLimit)` which to me seems like the one that would be used more often. Would a separate object (named something like `DirectionalSlewRateLimiter`) be better to avoid breaking changes? Feedback would be appreciated, particularly on the C++ constructor as I am unsure if I did that right.

Add direction to slew rate limiter

---

wpimath/src/main/native/include/frc/fmt/Eigen.h
wpimath/src/test/native/cpp/FormatterTest.cpp

Added an Eigen::SparseMatrix formatter.
Also modified the Eigen::Matrix formatter to support Eigen::MatrixXd.
Eigen::MatrixXd sets both dimension template arguments to -1, so they
can't be used for iteration. rows() and cols() are now used instead.
rows() and cols() are constexpr for statically sized matrices, so
there's no performance loss there.

[wpimath] Support formatting more Eigen types

---

.github/workflows/comment-command.yml

Triggering runners from a push from a runner requires use of a PAT.
https://stackoverflow.com/questions/67550727/push-event-doesnt-trigger-workflow-on-push-paths-github-actions

[ci] Fix comment-command action not running runners

---

.clang-tidy

We no longer use LLVM StringRef or Twine.

[ci] Remove a couple of obsolete clang-tidy checks

---

wpimath/src/main/java/edu/wpi/first/math/Vector.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Quaternion.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/native/cpp/geometry/Quaternion.cpp
wpimath/src/test/java/edu/wpi/first/math/VectorTest.java

Vector.norm() and Vector.dot() were added to make the implementation
simpler and match the C++ version more closely.

[wpimath] Clean up Java Quaternion class

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/native/cpp/geometry/Rotation3d.cpp
wpimath/src/main/native/include/frc/geometry/Rotation3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation3dTest.java
wpimath/src/test/native/cpp/geometry/Rotation3dTest.cpp

This is useful for turning a 3D vector into an orientation relative a
coordinate system vector.

[wpimath] Add two-vector Rotation3d constructor

---

wpilibc/src/main/native/cpp/motorcontrol/MotorControllerGroup.cpp
wpilibc/src/main/native/include/frc/motorcontrol/MotorControllerGroup.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/MotorControllerGroup.java

This causes setVoltage to be called on the lower level motor contollers,
which is benefical in cases when they are smart motor controllers.
Previously, the default implementation (using the bus voltage and
calling set()) was used in this case.
This does slightly pessimize the case when the lower level motor
controllers use the default setVoltage implementation, but given the
prevalence of smart motor controllers, this seems like an overall win.

[wpilib] MotorControllerGroup: Override setVoltage

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/include/frc2/command/Command.h

`until()` was added in #3981 as a more intuitive alias. At this point, keeping this decorator will just cause confusion, given the functionally equivalent `until()` alias and the similarly-named `getInterruptionBehavior()`/`withInterruptBehavior()` methods.

[commands] Deprecate withInterrupt decorator

---

wpilibNewCommands/src/main/native/cpp/frc2/command/ProxyScheduleCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/ProxyScheduleCommand.h
wpilibNewCommands/src/test/native/cpp/frc2/command/ProxyScheduleCommandTest.cpp

The non-owning overloads aren't memory-safe, especially with the `AsProxy()` decorator.

[commands] Add owning overload to ProxyScheduleCommand

---

wpimath/src/main/java/edu/wpi/first/math/Matrix.java

Replace &top; with \u22a4, since Unicode references are supported but HTML5 entities are not. Should be fixed if JDK is ever moved forward

[doc] older javadoc doesn't recognize HTML5 entities

---

wpimath/src/main/java/edu/wpi/first/math/controller/LinearQuadraticRegulator.java

The controller gain matrix K should be computed from the solution to the DARE, but this constructor does not do that. It effectively violates a postcondition enforced by the other constructors by letting the user throw in a controller gain matrix that didn't come from an LQR.
Removing this constructor is a breaking change, but it never should have been included in the class in the first place. There's also no valid reason to use it. I assume it was originally added for debugging the class internals.
This constructor does not exist in C++.

[wpimath] Remove Java LQR constructor that takes a controller gain matrix

---

wpinet/src/main/native/macOS/MulticastServiceResolver.cpp
wpinet/src/main/native/macOS/ResolverThread.cpp
wpinet/src/main/native/macOS/ResolverThread.h
wpiutil/src/main/native/windows/StackTrace.cpp

```
== clang-tidy /home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/windows/StackTrace.cpp ==
/home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/windows/StackTrace.cpp:12:33: error: expected class name [clang-diagnostic-error]
class StackTraceWalker : public StackWalker {
^
/home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/windows/StackTrace.cpp:16:17: error: unknown type name 'LPCTSTR' [clang-diagnostic-error]
void OnOutput(LPCTSTR szText) override;
^
/home/tav/frc/wpilib/allwpilib/wpiutil/src/main/native/windows/StackTrace.cpp:23:33: error: unknown type name 'LPCTSTR' [clang-diagnostic-error]
void StackTraceWalker::OnOutput(LPCTSTR szText) {
^
```

Fix clang-tidy false positive on Linux

---

wpilibcIntegrationTests/build.gradle

The new jni libraries for the libraries were never added, so they never get deployed.

Fix Java integration tests not correctly working

---

wpiutil/src/main/native/include/wpi/Logger.h

The FMT_STRING() call used in the macro does formatter initialization, overhead that's not required if Log() is not going to be called.

[wpiutil] Logger: Conditionalize around WPI_LOG

---

hal/src/main/java/edu/wpi/first/hal/SPIJNI.java
hal/src/main/native/athena/SPI.cpp
hal/src/main/native/cpp/jni/SPIJNI.cpp
hal/src/main/native/include/hal/SPI.h
hal/src/main/native/include/hal/SPITypes.h
hal/src/main/native/sim/SPI.cpp
wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/cpp/ADXL345_SPI.cpp
wpilibc/src/main/native/cpp/ADXL362.cpp
wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp
wpilibc/src/main/native/cpp/SPI.cpp
wpilibc/src/main/native/include/frc/SPI.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_SPI.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL362.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXRS450_Gyro.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java

SPI Mode setting was very broken. MSB and LSB sets did not work (MSB is the only one supported) and if LSB was set (which was the default) the ioct to set clock phase would fail. This deprecates all the individual functions, the LSB/MSB functions, and adds an SPI mode selection function. This is usually more understandable, and shows up in a lot more documentation

Fix SPI Mode Setting

---

hal/src/main/native/athena/mockdata/Reset.cpp
hal/src/main/native/include/hal/simulation/Reset.h
hal/src/main/native/sim/mockdata/Reset.cpp

- Fixes #3867
- Include #4015, but they can be considered separately
This works, but I don't necessarily need this merged this season if we want to defer this. Questions:
* I like `HALSIM_ResetAllSimData`, but I'm open to other names
* There were a lot of includes, so I put it into its own file. Maybe it should go into MockHooks.{cpp,h} instead?
* This is separate from resetting all handles, and I think that makes sense to stay that way
* For RobotPy, I'm going wrap this in `wpilib.simulation` along with the other global reset functions that were introduced in #4007. I do think this is a generally useful functionality for writing unit tests.
* Should that wrapper be put into WPILib's wpilib.simulation then? 
* RobotPy's wrapper implementation: …

[sim] Provide function that resets all simulation data

---

wpilibc/src/main/native/include/frc/util/Color.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java

the current Color.FromHSV method is not accurate and produces disjointed colours, this causes noticeable jumps in colour on real led's
I rewrote the function using the method on this [wikipedia page](https://en.wikipedia.org/wiki/HSL_and_HSV#HSV_to_RGB) with some changes to work with ints
top: actual hsv
middle: current wpilib hsv
bottom: new hsv

Fixed Color FromHSV

---

wpimath/src/main/java/edu/wpi/first/math/geometry/CoordinateSystem.java
wpimath/src/main/native/cpp/geometry/CoordinateSystem.cpp
wpimath/src/main/native/include/frc/geometry/CoordinateSystem.h
wpimath/src/test/java/edu/wpi/first/math/geometry/CoordinateSystemTest.java
wpimath/src/test/native/cpp/geometry/CoordinateSystemTest.cpp

I also refactored Pose3d's conversion implementation to use the Translation3d and Rotation3d conversions, thereby giving Translation3d and Rotation3d test coverage. No changes were made to the expected values of the Pose3d conversion tests.
The expected values of the Transform3d conversion tests were copied from the Pose3d conversion tests without modification.

[wpimath] Add CoordinateSystem conversion for Transform3d

---

wpinet/src/main/native/include/wpinet/uv/Async.h

This version assumes the loop still exists, avoiding some overhead.

[wpinet] uv::Async: Add UnsafeSend()

---

wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Button.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandHelper.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Button.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandRequirementsTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/EndlessCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/ProxyScheduleCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/RepeatCommandTest.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/RobotContainer.h

closes #4303 
Once this is more advanced, check whether renaming `CommandPtr` to `Command` (removing the current `Command` class at the head of the inheritance hierarchy) would help reducing breaking changes and keep Java/C++ syntax similarity.

[cpp commands] Migrate to unique_ptr

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/InstantCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RunCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/StartEndCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/InstantCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RunCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/StartEndCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/InstantCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RunCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/StartEndCommand.h

InstantCommand, StartEndCommand, and RunCommand are all practically FunctionalCommand with differently defaulted arguments. This makes that explicit, reducing code duplication..
Tests should prove no behavior changed.

[commands] Refactor lambda-based commands to inherit FunctionalCommand

---

datalogtool/CMakeLists.txt
roborioteamnumbersetter/CMakeLists.txt

This broke the build if the directory where libssh was installed also contained a system libuv install.

[build] cmake: Fix libssh include directory order

---

hal/src/main/java/edu/wpi/first/hal/DutyCycleJNI.java
hal/src/main/native/athena/AnalogTrigger.cpp
hal/src/main/native/athena/ConstantsInternal.h
hal/src/main/native/athena/DutyCycle.cpp
hal/src/main/native/cpp/jni/DutyCycleJNI.cpp
hal/src/main/native/include/hal/DutyCycle.h
hal/src/main/native/sim/DutyCycle.cpp
wpilibc/src/main/native/cpp/DutyCycle.cpp
wpilibc/src/main/native/include/frc/DutyCycle.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycle.java

The existing raw time has an issue where it jumps around, as in the FPGA if the frequency is not a multiple or divisor of 25 Mhz it jumps around by 1 every second. While waiting on an FPGA change, update the API to make raw output give nanoseconds rather then a scaled value. This does a longer read cycle to get the correct value, but in the future if a fast FPGA function is added this can be easily changed.
Closes #4221

Convert DutyCycle Raw output to be a high time measurement

---

CMakeLists.txt

For system installs, `DESTDIR=/usr cmake --install buildfolder` installs libraries to `/usr/lib` with the correct rpath. Example structure:
```
/usr/include/wpimath/frc/controller/LinearQuadraticRegulator.h
/usr/lib/libwpimath.so
```
Users need to provide `-I/usr/include/wpimath` in their projects. This is an artifact of the install() commands being in the subdirectory CMake files.
For other locations, `DESTDIR=/opt/wpilib cmake --install buildfolder` installs libraries to `/opt/wpilib/lib`. Example structure:
```
/opt/wpilib/include/wpimath/frc/controller/LinearQuadraticRegulator.h
/opt/wpilib/lib/libwpimath.so
```

[build] Remove wpilib prefix from CMake flat install

---

.github/workflows/cmake.yml
.github/workflows/comment-command.yml
.github/workflows/documentation.yml
.github/workflows/gradle.yml
.github/workflows/lint-format.yml
.github/workflows/upstream-utils.yml

I noticed a lot of warning on one of my last builds, so I turned on dependabot on my fork and had it auto-update all of the github actions.
Might be worth setting up dependabot in a separate PR. It can be noisy for java deps, but actions updates should be few and far between.

[ci] Update deprecated github actions

---

.github/workflows/comment-command.yml

This was the error:
```
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use
git push origin HEAD:refs/pull/4503/head
To push to the branch of the same name on the remote, use
git push origin HEAD
```

[ci] Fix comment command commit push

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandGenericHID.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandJoystick.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS4Controller.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandGenericHID.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandPS4Controller.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandXboxController.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandGenericHID.h
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandPS4Controller.h
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandXboxController.h
wpilibc/src/main/native/cpp/GenericHID.cpp
wpilibc/src/main/native/include/frc/GenericHID.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java

In C++ due to value semantics and method hiding, there's no need to replace the inheritance with delegation; only missing methods were added.
In Java, the `Trigger` factories were incompatible with the `BooleanEvent` ones, so the command HID classes couldn't inherit from the non-command ones. Thus, delegation. The missing methods are now available due to inheriting from CommandGenericHID.
Also add `Trigger` factories for POVs. Since more than one POV is extremely rare, the povIndex argument is defaulted to 0 in all methods but the root factory.

[command] Replace Command HID inheritance with delegation

---

.github/workflows/lint-format.yml
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandBase.cpp

I find that the workflow of downloading and extracting the zipped patch is quite tiresome, and the `/wpiformat` comment command is quite spammy.
This posts the patch contents to a code block at the [job summary](https://github.com/wpilibsuite/allwpilib/actions/runs/3323062430#summary-9099760328) with a convenient "copy to clipboard" button; the patch text can then be pasted into a local file (with LF line endings) and `git apply`ed.

[ci] Write wpiformat patch to job summary

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp
wpimath/src/main/native/include/frc/controller/PIDController.h
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h

These were missing and we have a use for them. Also adds them to ProfiledPIDController by just returning the value from the inner controller.

Create getters for position & velocity tolerances in PIDController

---

wpilibc/src/main/native/cppcs/RobotBase.cpp

[wpilibc] Don't hang waiting for NT server to start

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp

These are typically cached at higher levels anyway, but cache at lowest C++ layer as well for consistency with NT3.

[ntcore] Cache GetEntry(name) values

---

buildSrc/build.gradle

This has some decent changes to the toolchain plugin, so allwpilib is a great way to make sure nothing breaks

Update native utils to 2023.4.0

---

wpilibc/src/main/native/include/frc/shuffleboard/SuppliedValueWidget.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/SuppliedValueWidget.java

It was creating duplicate publishers.  In C++ the old publisher was destroyed, but since it wasn't being closed in Java, publishers simply accumulated.

[wpilib] Fix Shuffleboard SuppliedValueWidget

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandJoystick.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS4Controller.java

Closes #4551 
- Make return type of getHID reflect the specific class. `CommandXboxController` already returned `XboxController`
- Add getX and getY to CommandJoystick
This was not an issue in C++

Add missing methods in CommandJoystick and More Specific Return Type For CommandPS4Controller & CommandJoystick

---

wpilibc/src/main/native/cpp/simulation/PS4ControllerSim.cpp
wpilibc/src/main/native/cpp/simulation/XboxControllerSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PS4ControllerSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/XboxControllerSim.java

#4546 Fixes the POV sim for constructors accepting a controller object, but does not apply the fix for constructors accepting a port number. This PR applies the fix to the remaining controller sim constructors.
Further fixes #4543

[wpilib] Fix Xbox/PS4 POV sim for port number constructors

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WrapperCommand.java

Fixes #4553.
Also removed the forwarding of `getName`, as the wrapper command can be named differently than the wrapped command.
C++ has neither of these issues.

[cmd] Change WrapperCommand to inherit CommandBase

---

wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java

`SingleJointedArmSim`: Check angle equals limit on wouldHit

---

ntcore/src/generate/java/NetworkTableInstance.java.jinja
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/networktables/NetworkTableInstance.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.inc
ntcore/src/main/native/include/networktables/NetworkTableListener.inc
ntcore/src/test/native/cpp/ValueListenerTest.cpp

[ntcore] Various fixes and cleanups

---

ntcore/src/generate/java/NetworkTableInstance.java.jinja
ntcore/src/generate/java/NetworkTablesJNI.java.jinja
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableEvent.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableListener.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableListenerPoller.java
ntcore/src/main/native/include/ntcore_cpp.h
ntcore/src/test/java/edu/wpi/first/networktables/ConnectionListenerTest.java
ntcore/src/test/java/edu/wpi/first/networktables/LoggerTest.java
ntcore/src/test/java/edu/wpi/first/networktables/TopicListenerTest.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/PreferencesTest.java

[ntcore] Change Java event mask to EnumSet

---

wpilibc/src/main/native/include/frc/event/EventLoop.h

- It's already not movable because m_bindings isn't copyable, but pybind11 isn't able to detect that

Explicitly mark EventLoop as non-copyable/non-movable

---

wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

- For backwards compatibility reasons
Maybe we don't want to allow this composability... but the comment in `operatorXX(std::function<bool()> rhs)` seems to imply that it's supposed to work? My compiler isn't able to implicitly convert a trigger without this, but maybe I'm missing something?
Someone else should add a test for this.

Allow composing two triggers directly

---

wpilibc/src/main/native/cpp/apriltag/AprilTagFieldLayout.cpp
wpilibc/src/main/native/include/frc/apriltag/AprilTagFieldLayout.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/apriltag/AprilTagFieldLayout.java

This leaves the file format as a list, but internally will transform the collection of tags into a map on de/serialization. The serialization will probably happen once on startup, but the tag lookup can happen 100s of times a second. This honestly probably doesn't make too much of a performance hit since `N` is small, but this is a simple `O(n) -> O(1)` change for lookups.

[apriltags] Use map as internal data model

---

wpimath/src/main/java/edu/wpi/first/math/controller/DifferentialDriveFeedforward.java
wpimath/src/main/native/cpp/controller/DifferentialDriveFeedforward.cpp
wpimath/src/main/native/include/frc/controller/DifferentialDriveFeedforward.h
wpimath/src/test/java/edu/wpi/first/math/controller/DifferentialDriveFeedforwardTest.java
wpimath/src/test/native/cpp/controller/DifferentialDriveFeedforwardTest.cpp

This PR implements DifferentialDriveFeedforward classes which wrap LinearPlantInversionFeedforward.
Closes #3899

Add DifferentialDriveFeedforward classes which wrap LinearPlantInversionFeedforward

---

wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardComponent.h
wpilibc/src/main/native/include/frc/shuffleboard/ShuffleboardComponent.inc

ShuffleboardComponentBase::m_properties is now a StringMap<nt::Value>.

[wpilibc] ShuffleboardComponent.WithProperties: Update type

---

ntcore/src/main/native/cpp/LocalStorage.cpp

This is necessary for the simulation GUI to pick up default publishes.
Fixes #4616.

[ntcore] Notify locally on SetDefault

---

upstream_utils/update_eigen.py
upstream_utils/update_llvm.py
upstream_utils/upstream_utils.py
wpiutil/examples/printlog/datalog.py

This pull request ensures:
- Less complexity,
- Reduced method length,
- Minimized working memory,
Overall better quality.

Refactor python scripts under upstream_utils and wpiutil

---

wpilibc/src/main/native/include/frc/interfaces/Gyro.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.inc
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation2dTest.java
wpimath/src/test/native/cpp/geometry/Rotation2dTest.cpp

The `getRadians` and `getDegrees` will now always return in the -pi to pi or -180 to 180 scope.

[wpimath] Put Rotation2d's value always in the -pi to pi scope

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandRequirementsTest.java

The `isFinished` call is unsafe, since `initialize` hasn't been called yet. It also blocks various common use cases.
No assumptions are violated by this; it's just that the use cases are rather narrow so it's likely a user mistake.

[commands] Remove unsafe default command isFinished check

---

.github/workflows/gradle.yml
build.gradle
datalogtool/publish.gradle
glass/publish.gradle
outlineviewer/publish.gradle
roborioteamnumbersetter/publish.gradle

The signing step does not get passed the username and password to the server, so it will just read from the build cache. Then to make sure the tasks are all updated correctly, use if developerid exists as a property to all sign tasks, so it will see the new variable value, and relink. Additionally only update the archives during signing, which will speed up signing.

Use build cache for sign step

---

wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveOdometry.java
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

In both of these cases, encoder resets are not required for normal use. Effectively reverts https://github.com/wpilibsuite/allwpilib/pull/4569.

Remove encoder reset comments on Swerve, Mecanum Odometry and Pose Estimation

---

wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveOdometry.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveOdometry.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveOdometry.inc
wpimath/src/test/java/edu/wpi/first/math/kinematics/SwerveDriveOdometryTest.java
wpimath/src/test/native/cpp/kinematics/SwerveDriveOdometryTest.cpp

Forcing the use of `SwerveModulePostition[]` and `wpi::array<SwerveModulePosition, len>` in place of variadic function signatures.

Rework function signatures for Pose Estimation / Odometry

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandBase.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java

[cmd] Change factories return type to CommandBase

---

ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/InstanceImpl.h
ntcore/src/main/native/cpp/ListenerStorage.cpp
ntcore/src/main/native/cpp/ListenerStorage.h
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/ntcore_cpp.h
ntcore/src/test/native/cpp/NetworkTableTest.cpp

Let's talk about this. I need some way to reset the contents of the default NT instance. pyfrc runs the robot code over and over again, and it seems reasonable that for each test NT has nothing in it.
Alternatives:
* Accessing InstanceImpl via shared_ptr and resetting that (rejected)
* Adding a reader/writer lock over the instanceimpl array of instances, but it feels like that would have a lot more overhead than the other one

Provide mechanism to reset internals of NT instance

---

cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/linux/UsbCameraImpl.h

Reports exposure range as 1-5000 but real range is 1-75.

[cscore] Add Arducam OV9281 exposure quirk

---

glass/src/libnt/native/cpp/NTCommandScheduler.cpp
glass/src/libnt/native/cpp/NTCommandSelector.cpp
glass/src/libnt/native/cpp/NTDifferentialDrive.cpp
glass/src/libnt/native/cpp/NTDigitalInput.cpp
glass/src/libnt/native/cpp/NTDigitalOutput.cpp
glass/src/libnt/native/cpp/NTFMS.cpp
glass/src/libnt/native/cpp/NTField2D.cpp
glass/src/libnt/native/cpp/NTGyro.cpp
glass/src/libnt/native/cpp/NTMecanumDrive.cpp
glass/src/libnt/native/cpp/NTMechanism2D.cpp
glass/src/libnt/native/cpp/NTPIDController.cpp
glass/src/libnt/native/cpp/NTSpeedController.cpp
glass/src/libnt/native/cpp/NTStringChooser.cpp
glass/src/libnt/native/cpp/NTSubsystem.cpp
glass/src/libnt/native/cpp/NetworkTables.cpp

Checking this isn't required, and prevented these widgets from working in the simulation GUI without another NT client connected.
Fixes wpilibsuite/BetaTest#107.

[glass] Don't check IsConnected for NT widgets

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java

Renaming to avoid confusion with `Object.wait(long)`. C++ doesn't have this problem.

[java cmd] Rename wait factory to waitSeconds

---

glass/src/lib/native/cpp/other/Plot.cpp

Since m_windows is sorted using the ascii, when "Plot <10>" is created it will be before "Plot <2>" in `m_windows` which makes it so it will not add a new plot after the id 10 is reached. This also fixes a potential issue of someone manually changing an id in the file, which would break adding a new plot in some circumstances.

[glass] Plot: allow for more than 11 plots

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardContainer.cpp
wpilibc/src/main/native/cpp/shuffleboard/SimpleWidget.cpp
wpilibc/src/main/native/include/frc/shuffleboard/SimpleWidget.h
wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardInstanceTest.cpp
wpilibcExamples/src/main/cpp/examples/ShuffleBoard/cpp/Robot.cpp

Based on beta test feedback, returning a pointer is more intuitive, as typically the return value is late bound to an instance variable.

[wpilibc] Shuffleboard SimpleWidget: Return pointer instead of reference

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RepeatCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/RepeatCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/RepeatCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/RepeatCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/TriggerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/RepeatCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/button/TriggerTest.cpp

This fixes `InstantCommand.repeatdly()`.

[cmd] RepeatCommand: restart on following iteration

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp

Previously, only the first subscriber was actually matched to a topic when a topic was created; this was a problem when later publishing values as a client could have both a topic-only subscriber and a normal subscriber, and only the first one would end up being subscribed to the topic.

[ntcore] Server: Properly handle multiple subscribers

---

wpilibNewCommands/src/main/native/include/frc2/command/Commands.h

The vec-taking overloads aren't as concise as they should be, since the vector has to be constructed. This allows it to be more concise, similar to Java.

[cpp cmd] Add factory templates

---

ntcore/src/main/java/edu/wpi/first/networktables/NetworkTable.java
ntcore/src/main/native/cpp/networktables/NetworkTable.cpp
ntcore/src/main/native/cpp/networktables/NetworkTableInstance.cpp
ntcore/src/main/native/include/networktables/NetworkTable.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/test/java/edu/wpi/first/networktables/TableListenerTest.java
ntcore/src/test/native/cpp/TableListenerTest.cpp

These are similar, but not quite identical to, the NT3 NetworkTable table listeners.
Fixes #4632.

[ntcore] Add NetworkTable table-specific listeners

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Button.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/Button.h
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/TriggerTest.java
wpilibc/src/main/native/cpp/event/BooleanEvent.cpp
wpilibc/src/main/native/cpp/event/EventLoop.cpp
wpilibc/src/main/native/include/frc/event/BooleanEvent.h
wpilibc/src/main/native/include/frc/event/EventLoop.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/BooleanEvent.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/EventLoop.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/event/EventLoopTest.java

This might fix #4574 and similar.
There are no user-facing changes in this PR.

[cmd] Revert Trigger implementation

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h

Changes the behavior so calling `setDefaultCommand(subsystem, null)` unsets the default command of `subsystem`. I realize that calling `register` on the `subsystem` does the same thing, but this behavior is more explicit and intuitive.
I don't know how to do the C++ translation...

Allow unsetting a subsystem's default command

---

wpilibc/src/main/native/include/frc/util/Color.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLEDBuffer.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/AddressableLEDBufferTest.java

Rewrites `AddressableLEDBuffer.setHSV` to use `Color.fromHSV` to reduce redundancy between two HSV formulas and bring AddressableLED up to speed with Color's recent formula change.
Also, tweaks the Color algorithm to:
a) not produce incorrect values if the user happens to input a hue outside the `[0, 180)` range, and
b) more accurately convert the hue remainder from range 0-30 to 0-255. The current conversion vastly overshoots the multiplier (converts 0-30 to 0-270) and relies on clamping the value when constructing the Color object to produce a slightly incorrect result.
Fixes #4647.

Tweak and use Color HSV formula for AddressableLED

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Subsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/RapidReactCommandBot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Drive.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Intake.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Shooter.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Storage.java

Also update rapidreactcommandbot example factories to fit this convention  (as in #4655)
C++ does not need an update as `CommandPtr` already uses CommandBase (#4677)

Update Subsystem factories to return CommandBase

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp

Essentially this separates duplicate value detection between network and local.
Fixes some cases which could cause a de-synchronization between the server local copy and clients.

[ntcore] Send duplicate values to network if necessary

---

ntcore/src/main/java/edu/wpi/first/networktables/PubSubOption.java
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/PubSubOptions.cpp
ntcore/src/main/native/cpp/PubSubOptions.h
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h
ntcore/src/test/native/cpp/LocalStorageTest.cpp

This is the subscriber readQueue version of the local value listener flag.

[ntcore] Add Sub option for local vs remote changes

---

.github/workflows/gradle.yml

Linux and Athena builds are already running Java 17. Target compatibility is still enforced by gradle.

Update Mac and Windows builds to Java 17

---

wpilibcExamples/CMakeLists.txt

This fixes the following compilation errors:
```
/home/tav/frc/wpilib/allwpilib/wpilibcExamples/src/main/cpp/examples/UnitTest/cpp/subsystems/Intake.cpp:5:10: fatal error: subsystems/Intake.h: No such file or directory
5 | #include "subsystems/Intake.h"
|          ^~~~~~~~~~~~~~~~~~~~~
/home/tav/frc/wpilib/allwpilib/wpilibcExamples/src/test/cpp/examples/UnitTest/cpp/subsystems/IntakeTest.cpp:11:10: fatal error: Constants.h: No such file or directory
11 | #include "Constants.h"
|          ^~~~~~~~~~~~~
```

[examples] Add main include directory to test builds

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

Add constructors with default standard deviations to DifferentialDrive, Mecanum, and Swerve pose estimators, per #4753.

Add constructors to pose estimators with default standard deviations

---

googletest/CMakeLists.txt
shared/config.gradle

This fixes GCC 12 warnings for googletest internals that cause my local CMake build to fail.

[build] Upgrade to googletest 1.12.1

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDSubsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/PIDSubsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/PIDSubsystem.h

No longer stores a temporary setpoint in PIDSubsystem, instead immediately sending to PIDController. This fixes an issue where the setpoint didn't take effect until the Subsystem Periodic method ran, and could cause commands to finish early if they were scheduled after the subsystem periodic method ran because it used the old setpoint.
This is similar to #4062 / #4414 for ProfiledPIDSubsystem Fixes wpilibsuite/BetaTest#148

Fix PIDSubsystem setSetpoint behavior

---

wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/commands/Autos.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/subsystems/HatchSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/include/subsystems/HatchSubsystem.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/commands/Autos.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/subsystems/HatchSubsystem.java

This should show greater contrast between the traditional and inline, and provides comparison RLIs.

[examples] HatchbotInlined: Use Subsystem factories

---

wpimath/src/main/java/edu/wpi/first/math/ComputerVisionUtil.java
wpimath/src/main/native/cpp/ComputerVisionUtil.cpp
wpimath/src/main/native/include/frc/ComputerVisionUtil.h
wpimath/src/test/java/edu/wpi/first/math/ComputerVisionUtilTest.java
wpimath/src/test/native/cpp/ComputerVisionUtilTest.cpp

The ComputerVisionUtil class was added before AprilTag support was announced. Now that it has, the functions for estimating a pose from range and yaw are no longer needed; it's just better to get the pose directly from the AprilTag.
The coordinate system on some function arguments was confusing or didn't match the NWU convention the rest of the library uses. It's easier to remove the functions now and add them back after they're fixed since the fixes aren't trivial.
The range function was removed because it uses pitch and yaw in the camera's spherical coordinate system, which is obsoleted by AprilTags. AprilTags give you a 6DOF pose directly, so range can be obtained via Pose2d.getTranslation().getDistance().
Fixes #4757.

[wpimath] Remove broken and obsoleted ComputerVisionUtil functions

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ContainerHelper.java

Adding a null sendable to a container could result in a delayed NullPointerException.
Fixes https://github.com/wpilibsuite/BetaTest/issues/154
C++ doesn't have this issue because it takes a Sendable reference rather than a pointer.

[wpilibj] Shuffleboard: Check for null sendable

---

cscore/src/main/native/cpp/Frame.cpp
cscore/src/main/native/cpp/Frame.h

This is significantly more efficient than converting by way of BGR.

[cscore] Convert YUYV and UYVY directly to grayscale

---

wpilibc/src/main/native/include/frc/interfaces/Gyro.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/interfaces/Gyro.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.inc
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation2dTest.java
wpimath/src/test/native/cpp/geometry/Rotation2dTest.cpp

This broke multiple teams code in beta. It is also easier to limit the angle externally, then reconstruct a larger angle that got limited. This additionally adds comments to clarify the behavior and retains tests that were added in the reverted commit, and fixes a javadoc comment angle reference.
Revert "[wpimath] Constrain Rotation2d range to -pi to pi (#4611)"
This reverts commit d1d458db2b6c091f8167a15be54c1fa28617d04d

Revert Rotation2D change that limits angles

---

styleguide/spotbugs-exclude.xml
wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/cpp/motorcontrol/PWMMotorController.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/MotorSafety.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/PWMMotorController.java

Java was missing the motor safety thread entirely
C++ accidentally used a manual reset event, causing the motor safety thread to spin.
C++ PWMMotorController would not feed the watch kitty.
Both languages would call feed() from the StopMotor call, causing some ping ponging.
Closes #4782

Fix multiple motor safety issues

---

ntcore/src/main/java/edu/wpi/first/networktables/NetworkTable.java
ntcore/src/main/native/cpp/networktables/NetworkTable.cpp
ntcore/src/main/native/include/networktables/NetworkTable.h

This wasn't well thought out, and leaks horribly in Java.
Reverts part of #4640.
Fixes #4788.

[ntcore] Remove table multi-subscriber

---

wpiutil/src/main/native/thirdparty/llvm/cpp/llvm/StringExtras.cpp
wpiutil/src/test/native/cpp/UnescapeCStringTest.cpp

Add tests for empty, small, and string without escapes

[wpiutil] Fix UnescapeCString overflow when input size < 2

---

wpiutil/src/main/native/thirdparty/llvm/cpp/llvm/MemoryBuffer.cpp

Dereferencing an `end` iterator is undefined behavior and causes a failed assertion when running in debug.

[wpiutil] Fix MemoryBuffer initialization

---

wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java

Currently SysId refers to the gravity gain as Kg for Feedforward on arm mechanisms, and the ArmFeedforward class refers to the gravity gain as Kcos.
Additionally, the cpp version of ArmFeedforward already refers to this as `Kg`.
To ease development, this PR makes the terminology match across the library and additional tools.

Change terminology for ArmFeedforward gravity gain

---

ntcore/src/main/native/cpp/ntcore_test.cpp
ntcore/src/main/native/include/ntcore_test.h

The RPC functions are no longer implemented.
Also make header C-safe.

[ntcore] Clean up ntcore_test.h

---

glass/src/libnt/native/cpp/NetworkTables.cpp

If UpdateClients() was called in the same update batch as an entry removal, it could crash in GetEntry() due to a null entry caused by deletion before a removal erase pass was made.

[glass] Fix NT view UpdateClients() bug

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java
wpilibc/src/main/native/cpp/Joystick.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java

changes from manually taking the hypotenuse of the function to calling `Math.hypot` and `std::hypot` on the the `getX()` and `getY()` values

[wpilib] Joystick.getMagnitude(): use hypot() function

---

wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/native/cpp/controller/ProfiledPIDController.cpp
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h

This was missing from ProfiledPIDController. It is required in order to publish the Sendable to the dashboard.

ProfiledPIDController: Add to SendableRegistry

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h
ntcore/src/main/native/cpp/net/NetworkInterface.h
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.h
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp
ntcore/src/main/native/cpp/net3/ClientImpl3.h
ntcore/src/test/native/cpp/LocalStorageTest.cpp
ntcore/src/test/native/cpp/net/MockNetworkInterface.h

The current approach was slightly more efficient but didn't correctly handle meta-topic publishing for topics published before the server was started.

[ntcore] Simplify local startup

---

wpilibjExamples/build.gradle

This didn't fail until now because the JNI object was there in CI/full builds due to other tasks.

[gradle] Add missing task dependency in examples

---

wpilibNewCommands/src/test/native/cpp/frc2/command/CompositionTestBase.h

Remove final semicolon from test macro definition

---

ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp

It was possible to deadlock on instance destroy if the server had started but had not yet fully initialized its handles.
This is a patch fix.  We should fix this more globally in the libuv wrappers but that's high risk at this point in the release cycle.

[ntcore] Don't deadlock server on early destroy

---

wpiutil/src/main/native/cpp/SafeThread.cpp

This is to facilitate setting up Python's thread state when a thread starts. Currently pybind11 will set up its own state the first time that it's called on a thread, and then delete it as soon as the last GIL is released. For threads that potentially have python callbacks, that would cause the thread state to be created/destroyed over and over again... this should be more efficient to do it this way. Should be effectively zero overhead for anyone else.

[wpiutil] SafeThread: Provide start/stop hooks

---

hal/src/dev/native/cpp/main.cpp
hal/src/main/native/athena/PortsInternal.h
hal/src/main/native/athena/SPI.cpp
shared/config.gradle
wpilibc/src/dev/native/cpp/main.cpp
wpilibcExamples/CMakeLists.txt
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/include/ExampleGlobalMeasurementSensor.h
wpilibcExamples/src/main/cpp/examples/RomiReference/include/RobotContainer.h
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/include/ExampleGlobalMeasurementSensor.h

This makes the build fail on warnings. It caught two out-of-bounds reads and a deprecation warning.
Closes #4888.

[examples] Add missing compiler flags and fix warnings

---

hal/src/main/native/athena/CANAPI.cpp
hal/src/main/native/athena/DMA.cpp
hal/src/main/native/cpp/jni/simulation/BufferCallbackStore.cpp
hal/src/main/native/cpp/jni/simulation/ConstBufferCallbackStore.cpp
hal/src/main/native/cpp/jni/simulation/SimDeviceDataJNI.cpp
hal/src/main/native/cpp/jni/simulation/SpiReadAutoReceiveBufferCallbackStore.cpp
hal/src/main/native/sim/CANAPI.cpp
hal/src/main/native/sim/Encoder.cpp

- Return values of ->Get and ->Free weren't being checked in a few places
I found the CleanCAN one when debugging @auscompgeek's crash example, and I did a survey of all instances of ->Get(handle) and ->Free(handle) and found these others.

[hal] Fix segfault in various HAL functions

---

apriltag/CMakeLists.txt
fieldImages/CMakeLists.txt

These need to be relative paths, but GLOB generates absolute paths by default.

[build] Fix cmake java resources

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp
ntcore/src/main/native/cpp/net3/ClientImpl3.h

We need to ignore per-publisher send periods when flushing.
Also fix NT4 client to use flush async's (same as NT3 client).
Fixes #4902.

[ntcore] Fix client flush behavior

---

wpiutil/src/main/native/include/wpi/SymbolExports.h

MinGW gives an unknown pragma warning on Windows.

[wpiutil] Guard MSVC pragma in SymbolExports.h

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModuleState.java
wpimath/src/main/native/cpp/kinematics/SwerveModulePosition.cpp
wpimath/src/main/native/cpp/kinematics/SwerveModuleState.cpp
wpimath/src/main/native/include/frc/kinematics/SwerveModulePosition.h
wpimath/src/main/native/include/frc/kinematics/SwerveModuleState.h
wpimath/src/test/native/cpp/kinematics/SwerveModulePositionTest.cpp
wpimath/src/test/native/cpp/kinematics/SwerveModuleStateTest.cpp

~~Doesn't seem like this was a problem in C++~~. 
Should something be done about the compare to? (And it also doesn't seem like there is a compareTo implemented in C++)

[wpimath] Fix swerve kinematics util classes' equals function

---

wpilibc/src/main/native/cpp/Ultrasonic.cpp
wpilibc/src/main/native/cpp/simulation/UltrasonicSim.cpp
wpilibc/src/main/native/include/frc/simulation/UltrasonicSim.h
wpilibc/src/test/native/cpp/UltrasonicTest.cpp
wpilibcExamples/src/main/cpp/examples/PotentiometerPID/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/PotentiometerPID/include/Robot.h
wpilibcExamples/src/main/cpp/examples/Ultrasonic/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Ultrasonic/include/Robot.h
wpilibcExamples/src/main/cpp/examples/UltrasonicPID/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/UltrasonicPID/include/Robot.h
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibcExamples/src/test/cpp/examples/PotentiometerPID/cpp/PotentiometerPIDTest.cpp
wpilibcExamples/src/test/cpp/examples/PotentiometerPID/cpp/main.cpp
wpilibcExamples/src/test/cpp/examples/UltrasonicPID/cpp/UltrasonicPIDTest.cpp
wpilibcExamples/src/test/cpp/examples/UltrasonicPID/cpp/main.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Ultrasonic.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/UltrasonicSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/UltrasonicTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/potentiometerpid/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonic/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/Robot.java
wpilibjExamples/src/test/java/edu/wpi/first/wpilibj/examples/potentiometerpid/PotentiometerPIDTest.java
wpilibjExamples/src/test/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/UltrasonicPIDTest.java

All three of these ran a PID loop on an analog input; three nearly-identical examples aren't needed.
In addition, examples named `ultrasonic` without using the `Ultrasonic` class is confusing.
After this PR, the three examples diverge:
- `PotentiometerPID`: PID loop on an elevator with an `AnalogPotentiometer` (which can be any analog sensor).
- `UltrasonicPID`: PID loop on a drivetrain to hold a distance from an object, using an `Ultrasonic`.
- `Ultrasonic`: simple hardware sample of the `Ultrasonic` class, similar to the `Encoder` example.
Also adds tests.

[examples] Cleanup PotentiometerPID, Ultrasonic, UltrasonicPID

---

hal/src/main/java/edu/wpi/first/hal/simulation/EncoderDataJNI.java
hal/src/main/native/cpp/jni/simulation/EncoderDataJNI.cpp
hal/src/main/native/sim/Encoder.cpp
wpilibc/src/test/native/cpp/simulation/EncoderSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/EncoderSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/EncoderSimTest.java

Also fix C++ and Java `EncoderSim.setDistancePerPulse()` not propagating value to `SimEncoderData`
Closes #3813

Add missing distance per pulse functions to java EncoderSim

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java

The current error looks like this:
`Unhandled exception: java.lang.IllegalArgumentException: Commands that have been composed may not be added to another composition or scheduledindividually!`

Fix spacing in command composition exception

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h

This issue came to my attention a week ago on [Discord](https://discord.com/channels/176186766946992128/1060198350135234691/1060229546584068156).
This PR also rewords the command-already-composed error message to what is already used in Java; the confusing message hindered finding this bug.
I'm aware that we've already in-season and breaking changes shouldn't be done, but on the other hand this is a mistake that is very easy to make and quite difficult to diagnose. This PR does include breaking changes, but they're quite small in scope and make this type of mistake harder to make. Therefore, I think the benefit is worth breaking here.

[cpp cmd] BREAKING: Delete UB-causing rvalue variants of CommandPtr methods

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/main/native/include/frc/interpolation/TimeInterpolatableBuffer.h
wpimath/src/test/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimatorTest.java
wpimath/src/test/native/cpp/estimator/DifferentialDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/SwerveDrivePoseEstimatorTest.cpp

Without this PR, the pose estimate converges to the last vision measurement applied from the same timestamp. With it, it properly converges to a pose between the 3 of them.
Prior converged pose:
```
Observation: Pose2d(Translation2d(X: 9.12, Y: 1.19), Rotation2d(Rads: 0.30, Deg: 17.13))
Observation: Pose2d(Translation2d(X: 9.21, Y: 0.95), Rotation2d(Rads: 0.33, Deg: 19.12))
Observation: Pose2d(Translation2d(X: 8.89, Y: 1.31), Rotation2d(Rads: 0.25, Deg: 14.57))
Pose estimator: Pose2d(Translation2d(X: 8.89, Y: 1.31), Rotation2d(Rads: 0.25, Deg: 14.42))
```
After this PR:
```
Observation: Pose2d(Translation2d(X: 9.18, Y: 1.49), Rotation2d(Rads: 0.25, Deg: 14.42))
Observation: Pose2d(Translation2d(X: 9.13, Y: 1.46), Rotation2d(Rads: 0.25, Deg: 14.53))
Observation: Pose2d(Translation2d(X: …
```

Allow multiple vision measurements from same timestamp

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp

This fixes a potential race condition in code that only uses readQueue.

[ntcore] Queue current value on subscriber creation

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java

This is problematic if you call it twice before utilizing the result.
Example:
```java
ChassisSpeeds speeds1 = new ChassisSpeeds(1, 1, 1);
SwerveModuleState[] states1 = KINEMATICS.toSwerveModuleStates(speeds1);
ChassisSpeeds speeds2 = new ChassisSpeeds(32.001, -2.001, 253.001);
SwerveModuleState[] states2 = KINEMATICS.toSwerveModuleStates(speeds2);
System.out.println(Arrays.toString(states1));
System.out.println(Arrays.toString(states2));
```
Outputs:
```
[SwerveModuleState(Speed: 231.40 m/s, Angle: Rotation2d(Rads: 2.26, Deg: 129.74)), SwerveModuleState(Speed: 276.73 m/s, Angle: Rotation2d(Rads: 0.70, Deg: 40.02)), SwerveModuleState(Speed: 234.49 m/s, Angle: Rotation2d(Rads: -2.25, Deg: -129.11)), SwerveModuleState(Speed: 279.32 m/s, Angle: Rotation2d(Rads: -0.71, Deg: -40.64))] …
```

[wpimath] Fix SwerveDriveKinematics not initializing a new array each time

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp
wpimath/src/main/native/include/frc/controller/PIDController.h
wpimath/src/test/java/edu/wpi/first/math/controller/PIDInputOutputTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/PIDToleranceTest.java
wpimath/src/test/native/cpp/controller/PIDToleranceTest.cpp

Wait until setpoint and measurement have been set
Fixes wpilibsuite/BetaTest#185

[wpimath] Fix PID atSetpoint to not return true prematurely

---

wpilibcExamples/CMakeLists.txt

This fixes compilation of the apriltag vision example on my machine.

[build] Add apriltag to C++ cmake example builds

---

hal/src/main/java/edu/wpi/first/hal/DriverStationJNI.java
hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/cpp/jni/DriverStationJNI.cpp
hal/src/main/native/include/hal/DriverStation.h
hal/src/main/native/sim/DriverStation.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Closes #1198
During HAL_Initialize, wait up to 100ms for a DS packet to be received. Then in RobotBase, right after calling HAL_Initialize, call each languages RefreshData function to force a high level DS update. If the DS is connected, will get joystick data. If there is no data, nothing different will happen, but in that case theres no joysticks anyway.

Load joystick values upon code initialization

---

wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/native/cpp/controller/HolonomicDriveController.cpp
wpimath/src/main/native/include/frc/controller/HolonomicDriveController.h

Since the PIDControllers are private and, in c++, are passed by value to the constructor there is no way to access the controllers, for example to call reset on the rotation controller. This change allows you to get a reference to the controllers which also allows you to change the pid gains or constraints without creating new objects.
I also made the change in java to keep it consistent even though I don't think you would have the same issue in java.

[wpimath] HolonomicDriveController: Add getters for the controllers

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java

The other functions and languages don't have this typo.

[wpilibj] Fix typo in MecanumDrive docs (NFC)

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFieldLayout.java
apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFields.java
apriltag/src/test/java/edu/wpi/first/apriltag/LoadConfigTest.java

C++ had a method dedicated to loading a inbuilt field from the enum, Java however was missing this.  The unclear documentation on the AprilTagFieldLayout loadFromResource method led to users (read: me and my team) attempting to use it with non-internal fields.  This would NPE in a non-expected way.
This PR:
- Adds a specific method within AprilTagFields to get a AprilTagFieldLayout for the user
- Adds some documentation to ensure that users don't mistake loadFromResource for the constructor they want.

[apriltag] AprilTagFieldLayout: Improve API shape for loading builtin JSONs

---

hal/src/main/native/athena/FRCDriverStation.cpp

[hal] Properly use control word that is in sync with DS data

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

The toggleOnFalse description isn't consistent with the others.

[commands] Fix docs inconsistency for toggleOnFalse(Command)

---

shared/examplecheck.gradle
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json

<details> 
<summary>
List of tags currently:
</summary>
```
24 "Basic Robot"
23 "Differential Drive"
22 "XboxController"
21 "Encoder"
17 "Joystick"
16 "Command-based"
12 "Hardware"
11 "State-Space"
10 "PID"
9 "SmartDashboard"
9 "Gyro"
8 "Elevator"
7 "Vision"
7 "Odometry"
6 "Arm"
6 "Analog"
5 "Trajectory"
5 "Pneumatics"
5 "Path Following"
5 "Mecanum Drive"
5 "Flywheel"
5 "Complete Robot"
4 "Simulation"
4 "LQR"
3 "Trapezoid Profile"
3 "Swerve Drive"
3 "Smart Motor Controller"
3 "Shuffleboard"
3 "Ramsete"
3 "Profiled PID"
3 "Pose Estimator"
3 "Mechanism2d"
3 "Digital Input"
2 "Ultrasonic"
2 "PS4Controller"
2 "Intake"
2 "Duty Cycle"
1 "SysId"
1 "Romi"
1 "Relay"
1 "Preferences"
1 "PDP"
1 "I2C"
1 "EventLoop"
1 "Digital Output"
1 "DMA"
1 "AprilTags"
1 "AddressableLEDs"
```
</details>
I think …

[examples] Rewrite tags (NFC)

---

ntcore/src/main/native/cpp/NetworkServer.cpp

This avoids the warning appearing on every startup when persistent values aren't used.
Also add note to message saying it can be ignored if persistent values aren't expected.

[ntcore] Write empty persistent file if none found

---

wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Robot.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/RobotContainer.h

Fixes #4080.
Also fix the memory leak in the command-based auto.

[cpp example] RamseteCommand: Fix units

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/test/native/cpp/SpanMatcher.h
ntcore/src/test/native/cpp/net/ServerImplTest.cpp

Previously this wouldn't send the last value on the value subscribe if a topics only subscription already existed.
Also start adding server implementation unit tests.

[ntcore] Handle topicsonly followed by value subscribe

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/test/native/cpp/net/ServerImplTest.cpp

Previously, a setDefault() on the server could override a client doing a real set() if the time offset between client and server was negative, resulting in a negative timestamp from the client.  This is a not uncommon situation with robot code, as the robot code always starts at time 0, so any clients that set values earlier (in real time) would have negative timestamps.
Also improve special casing of 0 in the transmit side to make sure a normal timestamp will never get sent as 0.
Fixes #5002.
TODO:

[ntcore] Special-case default timestamps

---

ntcore/src/main/native/cpp/net/WireEncoder.cpp
ntcore/src/test/native/cpp/net/WireEncoderTest.cpp

Just using the index is insufficient because of Subscriber overlap with MultiSubscriber.

[ntcore] Use full handle when subscribing

---

wpiutil/src/main/native/include/wpi/Logger.h

This adds minimal overhead but is useful when debugging release binaries.

[wpiutil] Remove NDEBUG check for debug-level logging

---

wpiutil/src/main/native/thirdparty/llvm/cpp/llvm/MemoryBuffer.cpp

This would previously just write past the end of the buffer, smashing the stack.  It's only called in the case when a non-file or block device is used as the file.
Fixes #5016.

[wpiutil] MemoryBuffer: Fix GetMemoryBufferForStream

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

This was using an incorrect sizeof which would copy excessive data and could overwrite the button data.
Fixes #4997.

[simulation] GUI: Fix buffer overflow in joystick axes copy

---

glass/src/app/native/cpp/main.cpp

Remove NDEBUG check for debug-level logging so it's still compiled into release binaries.

[glass] Add option for debug-level NT logging

---

datalogtool/src/main/native/cpp/App.cpp
glass/src/app/native/cpp/main.cpp
outlineviewer/src/main/native/cpp/main.cpp
roborioteamnumbersetter/src/main/native/cpp/App.cpp
wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui.h
wpigui/src/main/native/include/wpigui_internal.h

Limiting with vsync is apparently unreliable on a number of systems; this resulted in high CPU/GPU usage.
Also add current actual frame rate to about dialog of GUI tools.

[wpigui] Limit frame rate to 120 fps by default

---

ntcore/src/generate/java/NetworkTableInstance.java.jinja
ntcore/src/generate/java/NetworkTablesJNI.java.jinja
ntcore/src/main/native/cpp/INetworkClient.h
ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkClient.h
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.inc
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

As setServer doesn't disconnect, it's useful to have a function that disconnects without needing to completely stop the client.

[ntcore] Add client disconnect function

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

If the request called the callback after the WebSocket had been destroyed, the buffers were leaked.

[ntcore] Don't leak buffers in rare WS shutdown case

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/test/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimatorTest.java
wpimath/src/test/native/cpp/estimator/DifferentialDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/SwerveDrivePoseEstimatorTest.cpp

Discard stale pose estimates

---

wpilibc/src/main/native/cpp/simulation/SimDeviceSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java

This breaks current vendor use of SimDeviceSim.
This reverts commit d991f6e435a193ed447d0c2db06d27d9b62b1a29 (#5041).

[wpilib] Revert throw on nonexistent SimDevice name in SimDeviceSim

---

cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp

GetInstance() is required to start the event listener that creates the network table entries.
This is a C++ only change; Java uses static's and thus doesn't need this.

[cameraserver] Add GetInstance() to all functions

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp

Previously this was a debug-level message. This can primarily impact users who call SetPersistent() on an entry before calling SetDefault().

[ntcore] Output warning on property set on unpublished topic

---

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java

Expected behavior:
`hasHitLowerLimit()` should return true if the ElevatorSim position is at the minimum height.
Actual behavior:
`hasHitLowerLimit()` will never return true because the position is clamped between the min and max heights. 
Solution:
Include `=` in the `wouldHitLowerLimit` and `wouldHitUpperLimit` methods

[wpilib] ElevatorSim: Fix WouldHitLimit methods

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java

This bug didn't occur in C++ because the units system caught it at compile time.

[wpimath] Fix DCMotor.getSpeed()

---

wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/test/native/cpp/WebSocketIntegrationTest.cpp

This caused crashes in ntcore.
This reverts commit b879a6f8c6a56469ccb2bbda8a84163709d00ede (#5047).

[wpinet] Revert WebSocket: When Close() is called, call closed immediately

---

wpilibcExamples/src/main/cpp/examples/MecanumDrive/cpp/Robot.cpp

[examples] MecanumDrive: Fix axis comment in C++ example (NFC)

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

[wpimath] Fix exception for empty pose buffer in pose estimators

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandBase.java
wpilibNewCommands/src/main/native/include/frc2/command/CommandBase.h

I see robot code where `addRequirements` is being called in the command `initialize` method, which won't do much good, but the documentation doesn't make this clear.

Improve documentation of addRequirements (NFC)

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/test/native/cpp/net/ServerImplTest.cpp

The client name deduplication didn't properly deduplicate.  Instead
always append the ID to guarantee a unique name.

[ntcore] Fix use-after-free in server

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
wpinet/src/main/native/cpp/DsClient.cpp
wpinet/src/main/native/cpp/EventLoopRunner.cpp
wpinet/src/main/native/cpp/ParallelTcpConnector.cpp
wpinet/src/main/native/cpp/PortForwarder.cpp
wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/cpp/uv/Async.cpp
wpinet/src/main/native/cpp/uv/Check.cpp
wpinet/src/main/native/cpp/uv/FsEvent.cpp
wpinet/src/main/native/cpp/uv/GetAddrInfo.cpp
wpinet/src/main/native/cpp/uv/GetNameInfo.cpp
wpinet/src/main/native/cpp/uv/Idle.cpp
wpinet/src/main/native/cpp/uv/NetworkStream.cpp
wpinet/src/main/native/cpp/uv/Pipe.cpp
wpinet/src/main/native/cpp/uv/Poll.cpp
wpinet/src/main/native/cpp/uv/Prepare.cpp
wpinet/src/main/native/cpp/uv/Process.cpp
wpinet/src/main/native/cpp/uv/Signal.cpp
wpinet/src/main/native/cpp/uv/Stream.cpp
wpinet/src/main/native/cpp/uv/Tcp.cpp
wpinet/src/main/native/cpp/uv/Timer.cpp
wpinet/src/main/native/cpp/uv/Tty.cpp
wpinet/src/main/native/cpp/uv/Udp.cpp
wpinet/src/main/native/cpp/uv/Work.cpp
wpinet/src/main/native/include/wpinet/ParallelTcpConnector.h
wpinet/src/main/native/include/wpinet/uv/Async.h
wpinet/src/main/native/include/wpinet/uv/AsyncFunction.h
wpinet/src/main/native/include/wpinet/uv/Loop.h

This prevents EventLoopRunner from hanging in the case when new handles are created after the async walk closes all the handles.

[wpinet] uv: Stop creating handles when closing loop

---

wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpimath/src/main/java/edu/wpi/first/math/MathShared.java
wpimath/src/main/java/edu/wpi/first/math/MathSharedStore.java
wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/filter/Debouncer.java
wpimath/src/main/java/edu/wpi/first/math/filter/SlewRateLimiter.java
wpimath/src/main/native/cpp/MathShared.cpp
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/filter/Debouncer.cpp
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/main/native/include/frc/filter/SlewRateLimiter.h
wpimath/src/main/native/include/wpimath/MathShared.h

This makes it possible to mock the timestamp for wpimath without affecting the rest of the library, related to [Mechanical-Advantage#33](https://github.com/Mechanical-Advantage/AdvantageKit/issues/33). Still TBD:
- Should the default implementation (before being overriden by RobotBase) return zero or use wpi::now?
- Should the C++ function include units or return an int like wpi::now?

[wpimath] Add timestamp getter to MathShared

---

glass/src/libnt/native/cpp/NetworkTables.cpp

This changes single strings to show containing double quotes e.g. `"hello"` and uses C-style escapes within the string.  Also improves handling of string arrays, e.g. strings in string arrays can now contain embedded commas.

[glass] NT view: Change string/string array to quoted

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java

The calculated analog pressure switch trigger voltages were calculated with a hard coded 5v. This introuduces error when the 5V provided to the Analog pressure sensor is not exactly 5v, as the pressure is a ratio of the analog voltage and provideed voltage.
This should improve
https://www.chiefdelphi.com/t/rev-pressure-sensor-enablecompressoranalog-not-reaching-configured-pressure/426868 where the 5v voltage was 4.92 volts, which introduces ~8 PSI of error.

Use PH voltage to calc analog pressure switch threshold

---

hal/src/main/native/athena/HAL.cpp

Correct fix for #5129
HAL_GetRuntimeType used to be a free call before the roboRIO2 was added. However, nLoadOut::getTargetClass() is not a free call, and I think it actually hits the IPC layer. Cache this value so its not called every time.

Fix HAL_GetRuntimeType being slow on the roboRIO

---

hal/src/main/native/sim/REVPH.cpp

The current implementation ignores channels eight and above in the simulator.

[hal] Simulation: Fix REV PH solenoids 8+

---

wpilibc/src/main/native/cpp/DataLogManager.cpp

Closes #5120 
I added an Instance destructor that stops the network tables logging. This prevents the segmentation fault on exit.

[wpilibc] Fix DataLogManager crash on exit in sim

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java

@calcmogul @sciencewhiz @PeterJohnson 
The reason why I was surprised that we hadn't already done #5115 is that we did do it, **in firmware**. The problem with the technique intended by #5115 is that it assumes that the voltage of the 5V rail won't change at all over the course of the match. We had recognized this, and intended for the voltage thresholds to be specified as if the 5V rail was at exactly 5V. The firmware then continually adjusts the thresholds based on the current voltage of the 5V rail. I added comments to explain this in the code, so that the same mistake doesn't get made again in the future.
We're taking this opportunity to double-check that the code in the firmware that does this is working as intended.

Go back to specifying PH voltage thresholds for a 5V rail that is exactly 5V

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Subsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Subsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h

An addendum to #4621 that allows `removeDefaultCommand` to be ran directly from the Subsystem, rather than from the CommandScheduler; this matches it with the style of the other Subsystem-specific methods.

[commands] Add default command removal method to Subsystem

---

wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/cpp/controller/LTVDifferentialDriveController.cpp
wpimath/src/main/native/cpp/controller/LTVUnicycleController.cpp
wpimath/src/main/native/include/frc/controller/LTVDifferentialDriveController.h
wpimath/src/main/native/include/frc/controller/LTVUnicycleController.h

[wpimath] Check LTV controller max velocity precondition

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/cpp/geometry/Pose3d.cpp
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose3dTest.java
wpimath/src/test/native/cpp/geometry/Pose3dTest.cpp

When a Pose3d log Twist3d is calculated with a `theta` value between 1e-9 and 1e-8, the `C` value becomes infinity and the Twist3d returns with `NaN` values. 
This is particularly a problem in #4943, which is how I found the issue, as `lastOdom.log(currOdom)` is able to make this happen.
Does this break anything, as `1e-9` seems to be the accepted value when comparing floats across the math classes?

[wpimath] Fix Pose3d log returning Twist3d NaN for theta between 1E-9 and 1E-8

---

wpimath/src/main/native/include/frc/interpolation/TimeInterpolatableBuffer.h

Found using a fuzzer. I ran this fix for several hundred thousand executions without any errors.

Fix invalid iterator access in TimeInterpolatableBuffer

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java

The `@throws` clause on this comment is wrong.
https://discord.com/channels/176186766946992128/368993897495527424/1084239227996348516

[cmd docs] CommandScheduler.isComposed: Remove incorrect throws clause (NFC)

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/cpp/geometry/Pose3d.cpp
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose3dTest.java
wpimath/src/test/native/cpp/geometry/Pose3dTest.cpp

Same thing as #5143 but I found a different pose that gets caught. Is there a way to find how it breaks algorithmically or are we fine with doing it experimentally?
Also updated the tests to add the broken pose and make it extensible so more poses can be added.

[wpimath] Fix Pose3d log returning Twist3d NaN for theta between 1E-8 and 1E-7.

---

wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java

There's no signal from NetComm as to when it is valid, and 1 second seems to be marginal.  Increase to 6 seconds for just DS, 5 seconds for FMS attached.

[wpilib] DataLogManager: increase time for datetime to be valid

---

datalogtool/src/main/native/cpp/Exporter.cpp
ntcore/src/main/native/cpp/LocalStorage.cpp

There's a spec difference between NT4 and datalog for integers; NT4 uses "int", datalog uses "int64". We were using "int" for datalog as well.
Also add backwards compatibility support to datalogtool for treating "int" as "int64".
Fixes #5182.

[ntcore] Use int64 for datalog type string

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java

This was broken by #2952 and was not included in the fixes in #2963

fix DutyCycleEncoder.setDistancePerRotation() in java simulation

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java

[commands] RamseteCommand: default-initialize m_prevSpeeds

---

hal/src/main/native/athena/HAL.cpp

Previously, the comment would end at any quote, escaped or unescaped. This allows UnescapeCString to handle the unescaping of quotes and properly end the string.

Fix RobotController.getComments() mishandling quotes inside the comments string

---

ntcore/src/dev/native/cpp/main.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp

The algorithm being used for scanning outgoing messages was O(n^2) because it did a full linear search and then appended. This scan is performed for each client. If there is a burst of outgoing changes, the outgoing queue can get quite deep all at once and this scan can be very slow. Replacing with a map fixes this.

[ntcore] Optimize scan of outgoing messages

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h

Pings are sent every 3 seconds.  If we don't see a response to the last ping before it's time to send the next one, close the connection.
Fixes #5146.

[ntcore] NT4 client: close timed-out connections

---

wpinet/src/main/native/cpp/ParallelTcpConnector.cpp
wpinet/src/main/native/include/wpinet/ParallelTcpConnector.h

There can be duplicate addresses coming out of name resolution; if we already started connecting to an address, don't start another connection attempt.

[wpinet] ParallelTcpConnector: don't connect to duplicate addresses

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

Was logging relative to cached value rather than previously logged value.  Was also logging cached value instead of current loop value.  C++ implementation is correct.
Fixes #5239.

[wpilibj] DriverStation: Fix joystick data logs

---

wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ElevatorSimTest.java
wpimath/src/main/java/edu/wpi/first/math/system/NumericalIntegration.java
wpimath/src/main/native/include/frc/system/NumericalIntegration.h
wpimath/src/test/java/edu/wpi/first/math/system/NumericalIntegrationTest.java
wpimath/src/test/native/cpp/system/NumericalIntegrationTest.cpp

If f(x, u) has no dynamics, the truncation error can be zero.

[wpimath] Fix potential divide-by-zero in RKDP

---

hal/src/main/java/edu/wpi/first/hal/AddressableLEDJNI.java
hal/src/main/native/athena/AddressableLED.cpp
hal/src/main/native/cpp/jni/AddressableLEDJNI.cpp
hal/src/main/native/include/hal/AddressableLED.h
hal/src/main/native/sim/AddressableLED.cpp
wpilibc/src/main/native/cpp/AddressableLED.cpp
wpilibc/src/main/native/include/frc/AddressableLED.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLED.java

HAL_SetAddressableLEDBitTiming swapped high and low timings for whatever was written to it. This fixes that bug.
Additionally, the API has been updated to take high time first, and then low time. This is due to this being the physical data format, so having the api match is clearer.
Additionally, update the docs with the defaults. Replaces #5271

[HAL] Fix and document addressable LED timings

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/Autonomous.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/DriveStraight.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/Pickup.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/Place.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/commands/PrepareToPickup.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Claw.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Elevator.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gearsbot/subsystems/Wrist.java

Creates a `Constants.java` file for the java GearsBot example, and implements it everywhere applicable.
There are also a few minor changes including replacing `Commands.parallel()` with `new ParallelCommandGroup()` in two instances, and replacing an if gate with a ternary operator in `Elevator.java`, to improve readability
This fixes half of #1948, but these changes are also required on the C++ example

Add constants to java gearsbot example

---

roborioteamnumbersetter/src/main/native/cpp/DeploySession.cpp

The current Team Number Setter tool incorrectly configures the roboRIO's hostname to `roborio-TEAM-FRC`, while the roboRIO Imaging Tool configures the hostname to `roboRIO-TEAM-FRC` (note the capitalization).
This PR aims to resolve this discrepancy by making the Team Number Setter tool match the behavior of the Imaging Tool.

Update Team Number Setter Capitalization

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RepeatCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/RepeatCommand.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/RepeatCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/RepeatCommandTest.cpp

If the command wrapped by a `RepeatCommand` finished naturally at the same time the repeat command was interrupted, `.end()` would be called twice (first `.end(false)` and then `.end(true)`).
This was especially problematic if the wrapped command is a `ProxyCommand`, since the first call to `.end()` would set its `m_command` to null and then the second call would attempt to call `m_command.cancel()`, resulting in a NPE.

[cmd] Fix RepeatCommand calling end() twice

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Filesystem.java

Fixes
https://www.chiefdelphi.com/t/filesystem-getdeploydirectory-returning-wrong-location-how-to-fix/427292 when unit tests are run with VS Code's java test runner due to VS Code extension setting working directory which changes user.dir.

strip JNI path from user.dir

---

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java

`reset` should set the offset to the properly scaled position provided by `getAbsolutePosition`, not the raw duty cycle.

fix DutyCycleEncoder reset behavior

---

wpimath/src/main/native/include/frc/StateSpaceUtil.h

It's an implementation detail left over from MakeMatrix().

[wpimath] Remove unused MatrixImpl() function

---

settings.gradle

Artifactory now does not allow repos that end in -cache. Update virtual repo naming to track this new limitation

[build] Update gradle cache repo name

---

wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.inc
wpimath/src/main/native/include/frc/estimator/KalmanFilter.inc
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.inc

Until #5339 is fixed, we have to use the slower, more accurate version.

[wpimath] Replace DiscretizeAQTaylor() with DiscretizeAQ()

---

CMakeLists.txt

```
CMake Warning (dev) at CMakeLists.txt:14 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

[build] Fix CMake warning

---

wpilibc/src/main/native/cpp/Joystick.cpp
wpilibc/src/main/native/include/frc/Joystick.h
wpilibc/src/test/native/cpp/JoystickTest.cpp

Deprecate unitless `GetDirectionRadians()` and `GetDirectionDegrees()`
Add unit tests for `GetDirection` and `GetMagnitude`

[wpilibc] Add unit-aware Joystick.GetDirection()

---

wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardInstanceTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardInstanceTest.java

Extends the timeout to 1 second, consistent with other tests that use `waitForListenerQueue`. Cause of failure was likely just the timeout being too short, particularly in Java.

Fix flaky ShuffleboardInstance test

---

wpimath/src/main/native/cpp/DARE.cpp
wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
wpimath/src/main/native/include/frc/StateSpaceUtil.h
wpimath/src/test/native/cpp/DARETest.cpp
wpimath/src/test/native/cpp/system/DiscretizationTest.cpp

We don't need the eigenvectors, so we're doing a lot of extra work we don't need to.

[wpimath] Only compute eigenvalues with EigenSolvers

---

shared/jni/publish.gradle
wpimath/build.gradle

This will allow very low level deps to use the same units library we ship with wpilib.
Closes #5362

Create separate archive with just units headers

---

wpilibNewCommands/src/test/native/cpp/frc2/command/CommandTestBase.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandTestBase.h
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulingRecursionTest.cpp

Fixes #5396 (SchedulingRecursionTest failing on Linux).
I'm not sure why this didn't manifest before, but `CommandTestBaseWithParam` (which is only used by `SchedulingRecursionTest`) was missing the call to notify the sim DS of new data (which was added last October by 3787 to just `CommandTestBase`).

Notify DriverStationSim in CommandTestBaseWithParam

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc
wpimath/src/test/java/edu/wpi/first/math/kinematics/SwerveDriveKinematicsTest.java
wpimath/src/test/native/cpp/kinematics/SwerveDriveKinematicsTest.cpp

Fixes #5167, #5029, and supersedes #5123. Adds a reset method where teams can pass in module headings for the kinematics object to use if it gets an all-zero `ChassisSpeeds` while converting `ChassisSpeeds` to module states. Also removes internal states array, replacing it with an internal headings array.

Add reset method to SwerveDriveKinematics

---

simulation/halsim_ws_client/src/main/native/cpp/HALSimWS.cpp
simulation/halsim_ws_client/src/main/native/cpp/HALSimWSClientConnection.cpp
simulation/halsim_ws_client/src/main/native/include/HALSimWS.h
simulation/halsim_ws_server/src/main/native/cpp/HALSimHttpConnection.cpp
simulation/halsim_ws_server/src/main/native/cpp/HALSimWeb.cpp
simulation/halsim_ws_server/src/main/native/include/HALSimWeb.h

The WebSocket HAL interface tends to be a little chatty and this was overwhelming the Pico W that powers the XRP robot. This PR provides the ability to filter the WS message by type that gets sent from WPILib.
Adding a line like `wpi.sim.envVar("HALSIMWS_FILTERS", "Gyro,DriverStation,DIO,AIO,Encoder")` to a robot project `build.gradle` file will only allow the listed message types to be sent over the wire.

[hal] WS Simulation: Add message filtering capability

---

ntcore/src/test/native/cpp/ValueTest.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/main/native/include/frc2/command/PerpetualCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/RepeatCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/WrapperCommand.h
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandPtrTest.cpp
wpimath/src/test/native/cpp/DARETest.cpp
wpiutil/src/test/native/cpp/ScopeExitTest.cpp

clang-tidy ignores the category filter if there's a space. wpiformat now ignores categories it doesn't understand, so we can remove the spaces.

Remove spaces in NOLINT comments

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandTestBase.h
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulerTest.cpp

As far as I can tell there is no test for `Subsystem.periodic()`

Add test for subsystem registration and periodic

---

docs/build.gradle
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/native/cpp/fs.cpp

Directives in CMakeLists.txt caused `make install` to fail. Everything else is just cleanup.

[wpiutil] Remove remnants of ghc fs and tcb_span libraries

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h

Removes the sentence on not reusing decorated commands from a few methods
Corrects onlyWhile/OnlyWhile param and return blocks to use "run" instead of "interrupt"
Fixes C++ WithInterruptBehavior doc comment
Removes a few double spaces
Removes periods from the end of a two param blocks (Mostly accidental- Waiting to hear if a consistent format should be applied or not)

[cmd docs] Clean up Command doc comments (NFC)

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandSendableButtonTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandSendableButtonTest.cpp
wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooserTest.java

This functionality has been broken a few times over the years, and upcoming telemetry PRs might break it as well.
To ensure it doesn't get broken, some tests.
All changes are in test source sets, so there shouldn't be an API/ABI breakage problem to merge it regardless of season progress.

Add tests for SendableChooser and Command Sendable functionality

---

wpiutil/CMakeLists.txt

Fixes https://github.com/wpilibsuite/allwpilib/issues/5428

Respect USE_SYSTEM_FMTLIB

---

ntcore/src/main/native/cpp/networktables/NetworkTable.cpp

In Java, a set is used. Use a two-stage approach in C++ to achieve the same result.

[ntcore] NetworkTable::GetSubTables(): Remove duplicates

---

ntcore/src/main/native/cpp/Value.cpp
ntcore/src/test/native/cpp/ValueTest.cpp

If both arrays are empty, it returns true, avoiding UB with `memcmp`.

[ntcore] Fix undefined behavior when array is empty

---

wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/RobotContainer.java

Taking the joystick inputs from -1 to 1, multiply them by the max speed (as defined in `Constants.java`) to get the target speed, rather than using the unitless raw joystick inputs.
This resolves issue https://github.com/wpilibsuite/allwpilib/issues/5417.

Convert the unitless joystick inputs to actual physical units

---

apriltag/build.gradle
cameraserver/build.gradle
shared/java/javacommon.gradle
wpilibNewCommands/build.gradle
wpilibj/build.gradle

This makes dependencies added to `implementation` also appear in `devImplementation`, making `project:run` work without needing to manually add the dependencies to `devImplementation` as well as `implementation`.
This also fixes the classpath in `wpilibNewCommands`.

Make dev configuration inherit dependencies from main configuration

---

wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/subsystems/DriveSubsystem.h
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/include/Drivetrain.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Robot.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h
wpimath/src/test/java/edu/wpi/first/math/kinematics/ChassisSpeedsTest.java

Hopefully addresses #5349 (intentionally avoiding the [auto-linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for now), with some differences:
* Instead of measuring the current pose and the desired future pose, the helper function only calculates the delta and does the log with the default `Pose2d`, since the delta is all that matters with `Pose2d.log()`.
* The helper function is in `ChassisSpeeds` instead of `SwerveDriveKinematics`, since the issue should be present in all holonomic drivetrains, not just swerve drive.
Other notes:
* I'm very uncertain about the wording ("timestep" or "duration"? Does "compensate" imply mutating the original object? Is the doc comment …

[wpimath] Add ChassisSpeeds method to fix drifting during compound swerve drive maneuvers

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileSubsystem.java
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h
wpilibcExamples/src/main/cpp/commands/trapezoidprofilecommand/ReplaceMeTrapezoidProfileCommand.cpp
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/cpp/commands/DriveDistanceProfiled.cpp
wpilibcExamples/src/main/cpp/examples/ElevatorTrapezoidProfile/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceArm/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceElevator/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/commands/trapezoidprofilecommand/ReplaceMeTrapezoidProfileCommand.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/commands/DriveDistanceProfiled.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatortrapezoidprofile/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacearm/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceelevator/Robot.java
wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrapezoidProfile.java
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.h
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.inc
wpimath/src/test/java/edu/wpi/first/math/controller/LinearSystemLoopTest.java
wpimath/src/test/java/edu/wpi/first/math/trajectory/TrapezoidProfileTest.java
wpimath/src/test/native/cpp/trajectory/TrapezoidProfileTest.cpp

ctor args were moved to `calculate`, all examples were updated, command and subsystem updated as well, and anything else that made it not compile was updated. Fixes #5453.

Refactor TrapezoidProfile API

---

wpiutil/src/main/java/edu/wpi/first/util/ClassPreloader.java

This provides an easy-to-use way to preload classes by name at startup to avoid later delays due to lazy classloading.
Will want to add this to the template main() once we've implemented native-utils support for generating (and deploying) a preload class list (see https://github.com/wpilibsuite/native-utils/pull/157).

[wpiutil] Add ClassPreloader

---

wpilibc/src/main/native/include/frc/event/EventLoop.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/EventLoop.java

Fixes #4868.
I feel like the documentation is inadequate, but `EventLoop` by itself doesn't do much; there's basically nothing that can be documented.

Remove BooleanEvent references in EventLoop documentation

---

hal/src/main/java/edu/wpi/first/hal/REVPHFaults.java

The previous PR had a typo in one of the bitmasks. Change to using 1 << N.

[hal] Fix Java REVPH faults bitfield (take 2)

---

wpilibcExamples/src/main/cpp/examples/ElevatorTrapezoidProfile/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatortrapezoidprofile/Robot.java

Missed this example when I updated the `TrapezoidProfile` API.

Update ElevatorTrapezoidProfile example

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java
wpimath/src/main/native/include/frc/system/plant/DCMotor.h

Just for convenience
I also tweaked some comments to remove some redundancy and so the java and cpp versions match better (though I think the comments are unnecessary in the first place).

Add FOC-enabled Falcon constants to the DCMotor class

---

wpilibcExamples/src/main/cpp/examples/HAL/c/Robot.c

The event wouldn't reset, causing infinite looping additionally, refresh ds data wasn't added causing a break

Fix C robot template not correctly looping

---

wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Kinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Odometry.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/WheelPositions.java
wpimath/src/main/native/cpp/kinematics/MecanumDriveKinematics.cpp
wpimath/src/main/native/include/frc/estimator/PoseEstimator.inc
wpimath/src/main/native/include/frc/kinematics/DifferentialDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/DifferentialDriveWheelPositions.h
wpimath/src/main/native/include/frc/kinematics/Kinematics.h
wpimath/src/main/native/include/frc/kinematics/MecanumDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/MecanumDriveWheelPositions.h
wpimath/src/main/native/include/frc/kinematics/Odometry.inc
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveWheelPositions.h
wpimath/src/main/native/include/frc/kinematics/SwerveModulePosition.h
wpimath/src/main/native/include/frc/kinematics/WheelPositions.h

`ToTwist2d(WheelPositions)` is removed in all kinematics classes except for mecanum, since there's tests for it (and removing it would be breaking, but not in a major way). I could just remove the tests (or rewrite them to use the new overload), and deprecating it is also an option.

Change kinematics.ToTwist2d(end - start) to kinematics.ToTwist2d(start, end)

---

hal/src/main/java/edu/wpi/first/hal/PowerJNI.java
hal/src/main/native/athena/Power.cpp
hal/src/main/native/athena/mockdata/RoboRioData.cpp
hal/src/main/native/cpp/jni/PowerJNI.cpp
hal/src/main/native/include/hal/Power.h
hal/src/main/native/include/hal/simulation/RoboRioData.h
hal/src/main/native/sim/Power.cpp
hal/src/main/native/sim/mockdata/RoboRioData.cpp
hal/src/main/native/sim/mockdata/RoboRioDataInternal.h
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

WIP
- Need to figure out what format `tPower.readOnChipTemperature()` returns data in... quick testing reads ~2600
- https://docs.xilinx.com/r/en-US/ug480_7Series_XADC/Analog-Inputs
- not sure whether power rail disable functions should be simulated on our side- disabling affects the return values of GetUserVoltage* and GetUserActive*

Expose power rail disable and cpu temp functionality

---

CMakeLists.txt

I have not found a justification for this. 
Fixes https://github.com/wpilibsuite/allwpilib/issues/5514

Don't enforce WITH_FLAT_INSTALL with MSVC

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform3d.java
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/main/native/include/frc/geometry/Rotation3d.h
wpimath/src/main/native/include/frc/geometry/Transform2d.h
wpimath/src/main/native/include/frc/geometry/Transform3d.h

I think this addresses #5196 (intentionally avoiding the [auto-linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for now), but I'm not sure I understand the wording of the issue.
Also, let me know if you think the documentation should be added to more methods. (e.g., Pose3d plus, Rotation3d plus/minus, Transform3d plus)

[wpimath] Document extrinsic vs intrinsic rotations (NFC)

---

wpilibNewCommands/CMakeLists.txt

Missing part from https://github.com/wpilibsuite/allwpilib/pull/5515

Don't enforce WITH_FLAT_INSTALL with MSVC missing parts

---

wpimath/src/main/java/edu/wpi/first/math/VecBuilder.java

Fixes #5523
Also changes the exception format to be vector-specific

[wpimath] Don't copy Matrix and underlying storage in VecBuilder

---

wpimath/CMakeLists.txt
wpimath/build.gradle
wpimath/src/main/java/edu/wpi/first/math/DARE.java
wpimath/src/main/java/edu/wpi/first/math/Matrix.java
wpimath/src/main/java/edu/wpi/first/math/SimpleMatrixUtils.java
wpimath/src/test/java/edu/wpi/first/math/DARETest.java

EJML deprecated `numRows()` and `numCols()` in favor of `getNumRows()` and `getNumCols()` respectively. Our Matrix class already uses the new naming in its API.

[wpimath] Upgrade to EJML 0.42

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Quaternion.java
wpimath/src/main/native/cpp/geometry/Quaternion.cpp
wpimath/src/main/native/include/frc/geometry/Quaternion.h

This avoids allocation overhead on construction. times() was also rewritten to not allocate any temporary objects.
Getter calls in the C++ Quaternion class were modified for parity.

[wpimath] Make Java Quaternion use doubles instead of Vector

---

wpimath/src/main/java/edu/wpi/first/math/geometry/CoordinateSystem.java
wpimath/src/main/native/cpp/geometry/CoordinateSystem.cpp
wpimath/src/test/java/edu/wpi/first/math/geometry/CoordinateSystemTest.java
wpimath/src/test/native/cpp/geometry/CoordinateSystemTest.cpp

Fixes #5385 
The current rotation conversion finds the rotation which aligns the axes from the final coordinate system onto the axes in the initial coordinate system which were first rotated by the given `Rotation3d`. This is why converting an empty rotation returns a non-empty rotation-- for example, converting an empty rotation in EDN to NWU returns the rotation from the NWU axes to the EDN axes.
The expected behavior mentioned in the issue is for rotations to extrinsically "match" in both coordinate systems. The example of an empty rotation would convert to an empty rotation. A rotation pitching up 10 degrees in NWU (axis = {0, -1, 0}, angle = 10 deg) would convert into an EDN rotation with axis = {1, 0, 0} and angle = 10 deg.
Tests not changed yet; is there a use case for the current …

[wpimath] Fix CoordinateSystem.convert() Transform3d overload

---

wpimath/src/main/java/edu/wpi/first/math/DARE.java
wpimath/src/main/java/edu/wpi/first/math/WPIMathJNI.java
wpimath/src/main/native/cpp/DARE.cpp
wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
wpimath/src/main/native/include/frc/DARE.h
wpimath/src/test/java/edu/wpi/first/math/DARETest.java
wpimath/src/test/native/cpp/DARETest.cpp

Both seem to work, but the SDA algorithm is specifically recommended for solving DAREs as opposed to P-DAREs.
The QR decomposition was replaced with a partial pivoting LU decomposition at the recommendation of section 2.4 of the paper.

[wpimath] Use SDA algorithm instead of SSCA for DARE solver

---

wpimath/src/main/java/edu/wpi/first/math/DARE.java
wpimath/src/main/java/edu/wpi/first/math/Matrix.java
wpimath/src/main/java/edu/wpi/first/math/WPIMathJNI.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/cpp/controller/LTVDifferentialDriveController.cpp
wpimath/src/main/native/cpp/controller/LTVUnicycleController.cpp
wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp
wpimath/src/test/java/edu/wpi/first/math/DARETest.java

I made JNI modifications to expose the faster function, made the API use the typesafe Matrix API, and synchronized the documentation with C++.
Sped up C++ LTV diff drive test from 20 ms to 15 ms.
Sped up C++ LTV unicycle test from 15 ms to 10 ms.

[wpimath] Make LTV controller constructors use faster DARE solver

---

wpinet/src/main/native/cpp/MulticastHandleManager.cpp
wpinet/src/main/native/cpp/MulticastHandleManager.h

Destructing either of the multicast objects during process shutdown will result in a crash due to attempting to start a task on the non existant thread pool.
Solve this by just leaking all the handles upon destruction of the static multicast manager. This won't solve the case where the user statically allocates the object, but solves Java and C access, and most cases wouldn't be statically allocation the service anouncer anyway in C++

[wpinet] Leak multicast handles during windows shutdown

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net3/UvStreamConnection3.cpp

Previously this was unlimited, which could result in holding on to a large amount of memory if the connection got backlogged or a burst of data transmission occurred.
64 KB might be too aggressive, but the only downside of exceeding this is additional heap traffic.

[ntcore] Limit buffer pool size to 64KB per connection

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SelectCommand.java
wpilibNewCommands/src/main/native/include/frc2/command/SelectCommand.h

Leftover description from removed Supplier constructor

[docs] Fix dangling SelectCommand documentation (NFC)

---

upstream_utils/update_fmt.py
upstream_utils/update_gcem.py
upstream_utils/update_libuv.py

endswith() leaves files out from subdirectories, which means projects that add new subdirectories won't have those files included when they probably should be.

[upstream_utils] Handle edge case in filename matches

---

upstream_utils/update_fmt.py
wpiutil/src/main/native/thirdparty/fmtlib/include/fmt/core.h
wpiutil/src/main/native/thirdparty/fmtlib/include/fmt/format.h
wpiutil/src/main/native/thirdparty/fmtlib/include/fmt/std.h

This fixes a partial template specialization error internal to fmt that was encountered in #5560.

[upstream_utils] Upgrade to fmt 10.1.1

---

glass/publish.gradle
roborioteamnumbersetter/publish.gradle

The logic we had for doing the mac bundles is very bad, and actually would have broken if building on macOS with the linux arm64 compiler installed. Fix it to make it slightly better and not break that case.

Fix tool builds with multiple arm platforms installed

---

wpimath/src/main/native/include/units/angular_acceleration.h

Specific unit headers should only include units they use. In this case, that's angle and time.

[wpimath] Fix incorrect header inclusion in angular_acceleration.h

---

ntcoreffi/build.gradle

This is required because wpiutil depends on these libraries and is statically linked.

[ntcoreffi] Link to NI libraries

---

wpimath/src/main/native/include/frc/DARE.h

If Q has off-diagonal entries, C and Cᵀ are different.

[wpimath] Fix computation of C for DARE (A, C) detectability check

---

wpimath/algorithms.md

Fixes a typo
Changes indentation on continued lines
Consistently includes reordering terms as a step
There are some inconsistencies between the quaternion and Kalman gain sections ("sqrt" vs "√", usage of inline code blocks outside of core math equations), which this PR could also cover if desired.

[wpimath] Cleanup wpimath/algorithms.md (NFC)

---

docs/build.gradle

Since user projects now use JDK 17, we should link to JDK 17 docs

Switch to Java 17 api docs

---

wpilibc/src/test/native/cpp/smartdashboard/Mechanism2dTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismObject2d.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismRoot2d.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/Mechanism2dTest.java

`Mechanism2d` didn't have any tests, so I added some. `MechanismRoot2d` didn't inherit from `MechanismObject2d` in Java, but did in C++, so now Java matches C++.

Add Mechanism2d tests and make Java impl match C++

---

cmake/modules/CompileWarnings.cmake
shared/config.gradle

This fixed the Linux CI build for https://github.com/wpilibsuite/allwpilib/pull/5630.

[build] Compress Linux debug info

---

cmake/modules/CompileWarnings.cmake
shared/config.gradle

This was required to make compression actually occur on my local machine.

[build] Specify zlib for debug info compression

---

wpilibc/src/main/native/cpp/Notifier.cpp
wpilibc/src/main/native/include/frc/Notifier.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java

The user-facing docs were simplified, SetHandler() was renamed to SetCallback(), and the internal documentation was synchronized.

[wpilib] Clean up Notifier

---

CMakeLists.txt
apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cscore/CMakeLists.txt
glass/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
simulation/halsim_ds_socket/CMakeLists.txt
simulation/halsim_gui/CMakeLists.txt
simulation/halsim_ws_client/CMakeLists.txt
simulation/halsim_ws_core/CMakeLists.txt
simulation/halsim_ws_server/CMakeLists.txt
wpigui/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
wpilibc/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiutil/CMakeLists.txt

`dll` files should go to `bin` instead of `lib`

[build] Use default CMake install location on Windows for dlls

---

glass/src/app/native/cpp/main.cpp
glass/src/lib/native/cpp/Context.cpp
glass/src/lib/native/cpp/MainMenuBar.cpp
glass/src/lib/native/cpp/Window.cpp
glass/src/lib/native/cpp/hardware/AnalogGyro.cpp
glass/src/lib/native/cpp/hardware/AnalogInput.cpp
glass/src/lib/native/cpp/hardware/AnalogOutput.cpp
glass/src/lib/native/cpp/hardware/Encoder.cpp
glass/src/lib/native/cpp/hardware/Gyro.cpp
glass/src/lib/native/cpp/hardware/PCM.cpp
glass/src/lib/native/cpp/hardware/PWM.cpp
glass/src/lib/native/cpp/hardware/PowerDistribution.cpp
glass/src/lib/native/cpp/other/DeviceTree.cpp
glass/src/lib/native/cpp/other/Plot.cpp
glass/src/lib/native/cpp/support/NameSetting.cpp
glass/src/libnt/native/cpp/NetworkTables.cpp
hal/src/main/native/cpp/jni/simulation/DriverStationDataJNI.cpp
hal/src/main/native/sim/Notifier.cpp
hal/src/test/native/cpp/mockdata/DriverStationDataTest.cpp
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
wpilibc/src/main/native/cpp/smartdashboard/Mechanism2d.cpp
wpilibc/src/main/native/cpp/smartdashboard/MechanismLigament2d.cpp
wpinet/src/main/native/thirdparty/tcpsockets/cpp/TCPStream.cpp
wpiutil/build.gradle
wpiutil/src/main/native/thirdparty/llvm/include/wpi/StringExtras.h

fmtlib uses consteval format string processing, which makes it more efficient than std::snprintf().
snprintf()s in libuv, mpack, processstarter, and wpigui were left alone. processstarter uses stdlib only, and wpigui only depends on imgui.
fmt::format_to_n() is analogous to std::format_to_n() (https://en.cppreference.com/w/cpp/utility/format/format_to_n)

Replace std::snprintf() with fmt::format_to_n()

---

wpiutil/src/main/native/include/wpi/SpanExtras.h

Also allow sized spans as input for drop_front and drop_back (return is always dynamic size).

[wpiutil] SpanExtras: Add take_back and take_front

---

wpinet/src/main/native/include/wpinet/uv/Error.h

Was previously UV_UNKNOWN, which meant a default-constructed uv::Error was actually an error.

[wpinet] uv::Error: Change default error to 0

---

wpinet/src/main/native/cpp/uv/Stream.cpp
wpinet/src/main/native/include/wpinet/uv/Request.h

Use this in Stream to allow the finish() callback to reuse the request via calling Keep().

[wpinet] uv::Request: Return shared_ptr from Release()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulerTest.cpp

Fixes #5301
Notes:
* Java stores the `Optional.empty()` instance since each call could potentially allocate a new instance. (There is no guarantee it is a singleton) This is not a problem for C++, which simply uses the `std::nullopt` constant.
* Java uses two separate lists for the toCancel queue to avoid allocating instances with both objects. This is not a problem for C++, which uses `std::pair` which does not allocate a new object (to my understanding).

[cmd] Add interruptor parameter to onCommandInterrupt callbacks

---

wpilibjExamples/build.gradle

In C++ each example is a separate source set, but in Java they were one source set and tested as one with the `test` task. Example-specific test tasks exist for Java, but they weren't used.
This modifies the `test` task to exclude the example tests, instead depending on each example's test task. The advantage of this is that each example is tested in a separate environment, so leftover state from one example isn't carried over.

[examples/build] Test each example in a new environment

---

wpinet/.styleguide
wpinet/CMakeLists.txt
wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/cpp/WebSocketDebug.h
wpinet/src/main/native/cpp/WebSocketSerializer.cpp
wpinet/src/main/native/cpp/WebSocketSerializer.h
wpinet/src/main/native/include/wpinet/WebSocket.h
wpinet/src/test/native/cpp/WebSocketSerializerTest.cpp
wpinet/src/test/native/cpp/WebSocketServerTest.cpp

This takes advantage of the underlying byte-level TryWrite() functionality to minimize blocking behavior and enable higher layers to do things smartly when the network blocks.

[wpinet] Add WebSocket::TrySendFrames()

---

wpimath/src/test/java/edu/wpi/first/math/controller/ArmFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/ElevatorFeedforwardTest.java
wpimath/src/test/native/cpp/controller/ArmFeedforwardTest.cpp
wpimath/src/test/native/cpp/controller/ElevatorFeedforwardTest.cpp

Add tests for ArmFeedforward and ElevatorFeedforward

---

cscore/build.gradle
datalogtool/build.gradle
fieldImages/build.gradle
glass/build.gradle
outlineviewer/build.gradle
processstarter/build.gradle
roborioteamnumbersetter/build.gradle
simulation/halsim_ds_socket/build.gradle
simulation/halsim_gui/build.gradle
simulation/halsim_ws_client/build.gradle
simulation/halsim_ws_core/build.gradle
simulation/halsim_ws_server/build.gradle
simulation/halsim_xrp/build.gradle
wpigui/build.gradle

Putting an early exit if statement at the top instead of wrapping the whole file contents unbreaks unit test configs, as was discovered for SysId. It reduces nesting as well.
Unused plugins were removed from the beginnings of files as well.

[build] Clean up Gradle configs

---

wpigui/src/main/native/cpp/wpigui_openurl.cpp

execlp() replaces the current process image, which isn't desirable.

[wpigui] Make wpi::gui::OpenURL() fork the process first

---

.github/workflows/gradle.yml

It takes 30 minutes, and the artifacts aren't used. The combine step changes so infrequently that it's unlikely to break in PRs, so it's a net benefit to speed up PR builds.

[ci] Disable combine on PR builds
