wpilibsuite/allwpilib

wpimath/update_eigen.py

NonMPL2.h clearly doesn't contain MPL2 code.

[wpimath] Fix typo in comment of update_eigen.py

---

wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibc/src/main/native/include/frc/drive/KilloughDrive.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibc/src/main/native/include/frc/drive/RobotDriveBase.h
wpilibc/src/test/native/cpp/drive/DifferentialDriveTest.cpp
wpilibc/src/test/native/cpp/drive/KilloughDriveTest.cpp
wpilibc/src/test/native/cpp/drive/MecanumDriveTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/DifferentialDriveTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/KilloughDriveTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/drive/MecanumDriveTest.java

This allows composing them with operations separate from the drive
class. This commit also removes the right side inversion and cleans up
the implementations of some inverse kinematics functions.

[wpilib] Refactor drive inverse kinematics into separate functions

---

.styleguide
CMakeLists.txt
ThirdPartyNotices.txt
wpiutil/.styleguide
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/native/fmtlib/include/fmt/args.h
wpiutil/src/main/native/fmtlib/include/fmt/chrono.h
wpiutil/src/main/native/fmtlib/include/fmt/color.h
wpiutil/src/main/native/fmtlib/include/fmt/compile.h
wpiutil/src/main/native/fmtlib/include/fmt/core.h
wpiutil/src/main/native/fmtlib/include/fmt/format-inl.h
wpiutil/src/main/native/fmtlib/include/fmt/format.h
wpiutil/src/main/native/fmtlib/include/fmt/locale.h
wpiutil/src/main/native/fmtlib/include/fmt/os.h
wpiutil/src/main/native/fmtlib/include/fmt/ostream.h
wpiutil/src/main/native/fmtlib/include/fmt/printf.h
wpiutil/src/main/native/fmtlib/include/fmt/ranges.h
wpiutil/src/main/native/fmtlib/include/fmt/wchar.h
wpiutil/src/main/native/fmtlib/src/format.cpp
wpiutil/src/main/native/fmtlib/src/os.cpp

From fmtlib HEAD as of 5/23/2021 (bc13c6de390751ecf8daa1b1ce8f775d104fdc65).

[wpiutil] Import fmtlib

---

.github/workflows/lint-format.yml

Use the official ubuntu packages on 20.04; don't use ubuntu-latest.

[build] Fix clang-tidy and clang-format

---

hal/src/main/native/athena/DIO.cpp
hal/src/main/native/include/hal/DIO.h
hal/src/main/native/sim/DIO.cpp

[hal] Error if attempting to set dio output on an input port

---

wpilibc/src/main/native/cppcs/RobotBase.cpp
wpimath/src/main/native/cpp/MathShared.cpp
wpimath/src/main/native/include/wpimath/MathShared.h

[wpimath] Add ReportWarning to MathShared

---

hal/src/main/native/athena/DIO.cpp

Unset was input, where the code was assuming set was input

[HAL] Fix DIO direction getter

---

crossConnIntegrationTests/src/main/native/cpp/PWMTests.cpp
crossConnIntegrationTests/src/main/native/cpp/TestEnvironment.cpp
crossConnIntegrationTests/src/main/native/include/LifetimeWrappers.h

Both a decent DMA test, and slightly more reliable PWM test

[HLT] Add PWM tests that use DMA as the back end

---

crossConnIntegrationTests/src/main/native/cpp/DutyCycleTests.cpp
crossConnIntegrationTests/src/main/native/include/LifetimeWrappers.h

The PWM output on the roborio a bit creative, so the logic there needs a bit more work. But wanted to commit what I had.

[HLT] Implement duty cycle cross connect tests

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h

[wpimath] Remove incorrect discretization in pose estimators

---

wpigui/.styleguide
wpigui/CMakeLists.txt
wpigui/build.gradle
wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui_internal.h

Also add wpiutil as a dependency for wpigui
Closes #3241

[wpigui] Add option to reset UI on exit

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DoubleSolenoid.java

A recent PR had an earlier version of wpiformat ran on it with more
lenient rules.

Run wpiformat

---

.github/workflows/lint-format.yml

This means users will be able to apply it locally with "git apply".

Upload wpiformat diff if one exists

---

wpilibcIntegrationTests/src/main/native/cpp/NotifierTest.cpp
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/NotifierTest.java

Add Notifier integration tests

---

cscore/src/main/native/include/cscore_cv.h
cscore/src/main/native/include/cscore_raw.h
cscore/src/main/native/include/cscore_raw_cv.h

[cscore] Add [[nodiscard]] to GrabFrame functions

---

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp
wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java
wpimath/src/main/java/edu/wpi/first/math/system/NumericalIntegration.java
wpimath/src/main/native/include/frc/system/NumericalIntegration.h
wpimath/src/test/java/edu/wpi/first/math/system/NumericalIntegrationTest.java
wpimath/src/test/native/cpp/system/NumericalIntegrationTest.cpp

Also refactored RKF45 implementation to match the new style, which is
easier to read.
The tests were switched from RKF45 to RKDP since it's more accurate.

[wpimath] Implement Dormand-Prince integration method

---

wpimath/src/main/native/include/frc/fmt/Units.h
wpimath/src/main/native/include/units/base.h
wpimath/src/test/native/cpp/FormatterTest.cpp
wpimath/src/test/native/cpp/UnitsTest.cpp

[wpimath] Disable iostream support for units and enable fmtlib

---

.github/workflows/documentation.yml
.github/workflows/gradle.yml
docs/build.gradle

https://www.doxygen.nl/manual/changelog.html#log_1_9_0

[build] Update to Doxygen 1.9.1

---

wpilibcExamples/src/main/cpp/examples/ArmBot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/ArmBotOffboard/include/Constants.h
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/Constants.h
wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/include/Constants.h
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/include/Constants.h
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/include/Constants.h
wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SchedulerEventLogging/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SelectCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/Constants.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbotoffboard/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyrodrivecommands/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbottraditional/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/schedulereventlogging/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/selectcommand/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/Constants.java

Make controller ports consistent

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Notifier.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Watchdog.java

non-breaking version of #2066
partially addresses #1824

[wpilibj] Add units to parameter names (NFC)

---

wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java

They don't provide much utility for the end user.

[wpilib] Remove IterativeRobotBase prints

---

wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h

This helps fix a bug regarding temporary Eigen values caused by the usage of auto.
This bug is currently impeding sysid from being upgraded to 2022.

Replace auto with Eigen Types

---

wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibc/src/main/native/cpp/drive/KilloughDrive.cpp
wpilibc/src/main/native/cpp/drive/MecanumDrive.cpp
wpilibc/src/main/native/cpp/drive/RobotDriveBase.cpp
wpilibc/src/main/native/include/frc/drive/RobotDriveBase.h
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Robot.java
wpimath/src/main/java/edu/wpi/first/math/MathUtil.java
wpimath/src/main/native/cpp/MathUtil.cpp
wpimath/src/main/native/include/frc/MathUtil.h
wpimath/src/test/java/edu/wpi/first/math/MathUtilTest.java
wpimath/src/test/native/cpp/MathUtilTest.cpp

It's a useful function outside of the drive classes.
Closes #2383.

Move RobotDriveBase::ApplyDeadband() to MathUtil

---

docs/build.gradle
docs/theme.css

This may be useful for the following reasons:
* It looks better (opinion)
Before:
After:
* It supports dark mode
* It's easier on mobile because the sidebar is not part of the UI, preventing it from narrowing the view (opinion)
Before:
After:

Use a doxygen theme

---

hal/src/main/native/athena/FRCDriverStation.cpp

Replace strncpy with memcpy

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/include/frc/PWM.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibc/src/main/native/include/frc/shuffleboard/BuiltInWidgets.h
wpilibc/src/main/native/include/frc/shuffleboard/Shuffleboard.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PWM.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/BuiltInWidgets.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ComplexWidget.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/Shuffleboard.java

Makes comments consistent with #3302

Replace Speed controller comments with motor controller (NFC)

---

ntcore/src/test/native/cpp/NetworkTableTest.cpp
ntcore/src/test/native/cpp/ValueTest.cpp

[ntcore] Fix NetworkTables memory leaks caught by asan

---

cscore/src/test/native/cpp/CameraSourceTest.cpp

[cscore] Fix cscore test mutex use-after-free caught by tsan

---

docs/build.gradle

https://www.doxygen.nl/manual/changelog.html

Update to doxygen 1.9.2

---

hal/src/main/native/athena/Threads.cpp

When running from admin account, this hangs for 5-10 seconds

Don't revert euid if its already current value

---

simulation/halsim_ds_socket/src/main/native/cpp/DSCommPacket.cpp

Fix halsim_ds_socket stringop overflow warning from GCC 10

---

wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armsimulation/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json

Correct several comments that referenced elevator
Changed noise to be 1 encoder tick instead of half a degree
Changed gear ratio and PID value to be better tuned and more controllable
Updated bounds to be similar to a single jointed arm
https://user-images.githubusercontent.com/4885091/133544271-49b870a7-54ab-46dd-b4a7-d3c7cf162362.mp4

Update ArmSimulation example to use Mechanism2d

---

wpilibcExamples/src/main/cpp/examples/Mechanism2d/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mechanism2d/Robot.java

Synchronize dimensions
Make both joints different colors for clarity

[examples] Synchronize C++ and Java Mechanism2d examples

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/ButtonTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/button/ButtonTest.cpp
wpilibc/src/main/native/cpp/Debouncer.cpp
wpilibc/src/main/native/include/frc/Debouncer.h
wpilibc/src/test/native/cpp/DebouncerTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Debouncer.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/DebouncerTest.java

Supersedes #2358 with updates and cleanups.
Closes #2482 and closes #2487 because we shouldn't support both
time-based and count-based debouncing approaches.
Co-authored-by: Tyler Veness <calcmogul@gmail.com>

[wpilib] Add Debouncer

---

.github/workflows/cmake.yml
.github/workflows/sanitizers.yml

ctest's -E flag skips tests that match a regular expression.

Enable asan and tsan in CI for tests that pass

---

hal/src/main/native/athena/I2C.cpp

[hal] Set error status for I2C port out of range

---

docs/build.gradle
hal/src/main/native/include/hal/simulation/SimDeviceData.h
upstream_utils/drake-fix-doxygen.patch
upstream_utils/update_drake.py
wpilibc/src/main/native/include/frc/Errors.h
wpilibc/src/main/native/include/frc/shuffleboard/BuiltInWidgets.h
wpilibc/src/main/native/include/frc/simulation/SimHooks.h
wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/include/drake/math/discrete_algebraic_riccati_equation.h
wpimath/src/main/native/include/frc/StateSpaceUtil.h
wpimath/src/main/native/include/frc/controller/ControlAffinePlantInversionFeedforward.h
wpimath/src/main/native/include/frc/controller/LinearPlantInversionFeedforward.h
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/main/native/include/frc/estimator/AngleStatistics.h
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h
wpimath/src/main/native/include/frc/estimator/MerweScaledSigmaPoints.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/UnscentedTransform.h
wpimath/src/main/native/include/frc/system/Discretization.h
wpimath/src/main/native/include/frc/system/LinearSystem.h
wpimath/src/main/native/include/frc/system/LinearSystemLoop.h
wpimath/src/main/native/include/frc/system/NumericalJacobian.h
wpiutil/src/main/native/include/wpi/Synchronization.h
wpiutil/src/main/native/include/wpi/leb128.h

Set Doxygen extract_all to true and fix Doxygen failures (NFC)

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

[wpimath] Document pose estimator states, inputs, and outputs

---

hal/src/main/native/sim/PowerDistribution.cpp

Fix sim not working with automatic pd type and default module

---

hal/src/main/native/athena/SerialPort.cpp

[hal] Check error codes during serial port initialization

---

hal/src/main/native/athena/REVPH.cpp

[hal] Fix REVPH Analog Pressure channel selection

---

docs/build.gradle

Fixes inclusion of wpi::numbers and some Eigen files

[docs] Parse files without extensions with Doxygen

---

hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/include/hal/REVPH.h

Adds driver functions for getting regular and sticky faults from the REV PH

[hal] Add REV PH faults

---

cscore/src/main/native/windows/UsbCameraImpl.cpp
cscore/src/main/native/windows/WindowsMessagePump.cpp

Use wpi string conversion rather than codecvt (which is deprecated)
Force A function types

Cleanup windows USB camera impl

---

glass/src/lib/native/cpp/other/Plot.cpp
glass/src/lib/native/cpp/support/ExtraGuiWidgets.cpp
imgui/CMakeLists.txt.in
shared/config.gradle

This in particular upgrades the plot widget with a few new features
and makes more plot configuration persistent.

[glass] Upgrade imgui to 0.85, implot to HEAD, glfw to 3.3.5

---

wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/Constants.h
wpimath/src/main/java/edu/wpi/first/math/controller/RamseteController.java
wpimath/src/main/native/cpp/controller/RamseteController.cpp
wpimath/src/main/native/include/frc/controller/RamseteController.h
wpimath/src/test/native/cpp/controller/RamseteControllerTest.cpp

[wpimath] Fix units of RamseteController's b and zeta

---

wpilibNewCommands/src/main/native/cpp/frc2/command/MecanumControllerCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/RobotContainer.cpp

Fixes #3765
Also fixes SwerveControllerCommand example calling command twice

Fix Mecanum & Swerve ControllerCommand lamda capture

---

hal/src/main/java/edu/wpi/first/hal/REVPHFaults.java
hal/src/main/java/edu/wpi/first/hal/REVPHJNI.java
hal/src/main/java/edu/wpi/first/hal/REVPHStickyFaults.java
hal/src/main/java/edu/wpi/first/hal/REVPHVersion.java
hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/HALUtil.h
hal/src/main/native/cpp/jni/REVPHJNI.cpp
hal/src/main/native/include/hal/REVPH.h
hal/src/main/native/sim/REVPH.cpp
myRobot/src/main/native/cpp/MyRobot.cpp
wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibc/src/main/native/cpp/PneumaticsControlModule.cpp
wpilibc/src/main/native/include/frc/Compressor.h
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibc/src/main/native/include/frc/PneumaticsBase.h
wpilibc/src/main/native/include/frc/PneumaticsControlModule.h
wpilibc/src/test/native/cpp/simulation/CTREPCMSimTest.cpp
wpilibc/src/test/native/cpp/simulation/REVPHSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsControlModule.java

More functionality was implemented at the HAL level, so expose that to the wpilib level.
This also does units changes for all the PH related functionality.

High Level REV PH changes

---

hal/src/main/java/edu/wpi/first/hal/PowerDistributionFaults.java
hal/src/main/java/edu/wpi/first/hal/PowerDistributionJNI.java
hal/src/main/java/edu/wpi/first/hal/PowerDistributionStickyFaults.java
hal/src/main/java/edu/wpi/first/hal/PowerDistributionVersion.java
hal/src/main/native/athena/PowerDistribution.cpp
hal/src/main/native/athena/REVPDH.cpp
hal/src/main/native/athena/REVPDH.h
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/HALUtil.h
hal/src/main/native/cpp/jni/PowerDistributionJNI.cpp
hal/src/main/native/include/hal/PowerDistribution.h
hal/src/main/native/sim/PowerDistribution.cpp
wpilibc/src/main/native/cpp/PowerDistribution.cpp
wpilibc/src/main/native/include/frc/PowerDistribution.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

Add support for getting faults and versions from power distribution

---

wpimath/src/test/java/edu/wpi/first/math/trajectory/TrajectoryJsonTest.java

[wpimath] Give drivetrain a more realistic width in TrajectoryJsonTest.java

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/romieducational/EducationalRobot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/romieducational/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/romieducational/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/romieducational/RomiDrivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json

This is a combination of a Romi Gradle project and Educational robot (added in #3309)

Add Java Romi Educational template

---

wpilibcExamples/src/main/cpp/examples/ArcadeDrive/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/ArcadeDriveXboxController/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/ArmBot/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/ArmBotOffboard/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/Frisbeebot/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Gyro/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/RobotContainer.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/arcadedrive/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/arcadedrivexboxcontroller/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbot/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armbotoffboard/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyro/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gyrodrivecommands/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/hatchbotinlined/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/RobotContainer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/RobotContainer.java

Accounts for differences between ArcadeDrive and the methods used
in some other examples

Fix arcade inversions

---

styleguide/spotbugs-exclude.xml
wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS_16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

The code currently compiles, but massively fails checkstyle.

Include ADIS IMU's in WPILib

---

MavenArtifacts.md

Add wpiutil to wpimath
Add wpimath to wpilibj and wpilibc

Fix Maven Artifacts readme

---

wpilibcExamples/src/main/cpp/examples/DigitalCommunication/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/I2CCommunication/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/digitalcommunication/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/digitalcommunication/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/i2ccommunication/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/i2ccommunication/Robot.java

As it would seem that the author of #1362 stopped developing his PR, I decided to take over it. 
Resolves #1038.

add communication examples i.e. arduino

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew

This is the same version robot projects currently use.

Upgrade to Gradle 7.3.3

---

CMakeLists.txt
cmake/modules/FindLIBSSH.cmake
roborioteamnumbersetter/CMakeLists.txt

This needs libssh to build, so on Linux systems it's necessary to
install libssh-dev.

[rtns] Add cmake build

---

wpilibcExamples/src/main/cpp/examples/DifferentialDrivePoseEstimator/include/ExampleGlobalMeasurementSensor.h

Fix Eigen out of range error when running example

---

wpimath/src/main/native/include/frc/geometry/Twist2d.h

[wpimath] Const-qualify Twist2d scalar multiply

---

build.gradle

The release notes say it fixes another log4j vulnerability.

Upgrade to shadow 7.1.2

---

wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h

Fix ProfiledPIDCommand use-after-free

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/native/include/frc/filter/LinearFilter.h
wpimath/src/test/java/edu/wpi/first/math/filter/LinearFilterTest.java
wpimath/src/test/native/cpp/filter/LinearFilterOutputTest.cpp

SysId uses this for acceleration filtering, but it makes sense to
consolidate the implementations here.

[wpimath] Add LinearFilter::FiniteDifference()

---

wpilibNewCommands/WPILibNewCommands.json
wpilibOldCommands/WPILibOldCommands.json

While the number doesn't matter, it being old is confusing a lot of
people.
Closes #3921.

Update command vendordep JSON version number

---

wpilibc/src/main/native/include/frc/PowerDistribution.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

Add docs for switchable channel
Use PDP/PDH appropriately and clarify differences
Fix typos

Improve PowerDistribution docs (NFC)

---

wpilibc/src/main/native/cpp/PowerDistribution.cpp
wpilibc/src/main/native/include/frc/PowerDistribution.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

[wpilib] PowerDistribution: Add module type getter

---

wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java

Added note that implementation may change in the future, #3930

Make MecanumDrive docs for axis to match implementation

---

wpiutil/src/main/native/cpp/StackTraceWrap.cpp
wpiutil/src/main/native/include/wpi/StackTrace.h
wpiutil/src/main/native/unix/StackTrace.cpp
wpiutil/src/main/native/windows/StackTrace.cpp

[wpiutil] StackTrace: Add ability to override default implementation

---

wpilibc/src/main/native/cpp/simulation/DCMotorSim.cpp
wpilibc/src/main/native/include/frc/simulation/DCMotorSim.h
wpilibc/src/test/native/cpp/simulation/DCMotorSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DCMotorSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DCMotorSimTest.java
wpimath/src/main/java/edu/wpi/first/math/system/plant/LinearSystemId.java
wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h
wpimath/src/test/java/edu/wpi/first/math/system/LinearSystemIDTest.java
wpimath/src/test/native/cpp/system/LinearSystemIDTest.cpp

Fixes #3901 
Anyway this seems to work.

Add DCMotorSim

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardWidget.cpp
wpilibc/src/main/native/include/frc/shuffleboard/BuiltInWidgets.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/BuiltInWidgets.java

Add Field widget to BuiltInWidgets in shuffleboard

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

[wpilibj] Make methods public for REV PDH

---

shared/config.gradle

Update to 2022 v4.0 image

---

wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp

Only call HAL_Report when initializing SmartDashboard

---

glass/src/app/native/cpp/main.cpp

This is useful for editing of values without disabling the DS.

[glass] Support remapping of Enter key

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismRoot2d.java

Add flush to MechanismRoot2d SetPosition

---

wpilibc/src/main/native/cpp/Preferences.cpp
wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp
wpiutil/src/main/native/cpp/sendable/SendableRegistry.cpp

- In 2023 these should be tied to HAL_Shutdown somehow
This is a strawman to drive discussion, I need to test it locally to see if it gets me what I need.

Add mechanism to reset various global structures

---

hal/src/main/native/sim/PortsInternal.h
hal/src/main/native/sim/mockdata/AccelerometerData.cpp
hal/src/main/native/sim/mockdata/I2CData.cpp
hal/src/main/native/sim/mockdata/PowerDistributionDataInternal.h
hal/src/main/native/sim/mockdata/SPIAccelerometerData.cpp
hal/src/main/native/sim/mockdata/SPIData.cpp

Prep for a different PR, but this seems like a good standalone PR

[hal] Replace hardcoded sim array sizes with constants

---

glass/src/app/native/cpp/main.cpp

[glass] Fix snprintf truncation warning

---

wpilibc/src/main/native/cpp/Preferences.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java

Set Persistant for Preferences Init methods

---

wpilibc/src/main/native/cpp/MotorSafety.cpp

[wpilibc] Add mechanism to reset MotorSafety list

---

simulation/halsim_gui/src/main/native/cpp/main.cpp
simulation/halsim_gui/src/main/native/include/HALSimGuiExt.h

Compiled, ~but not~ and tested locally.

[sim] expose GUI control functions via HAL_RegisterExtension

---

hal/src/main/native/athena/mockdata/MockHooks.cpp
hal/src/main/native/include/hal/simulation/MockHooks.h
hal/src/main/native/sim/HAL.cpp

Another global structure that should have been in #4006

[hal] Add mechanism to cancel all periodic callbacks

---

wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/cpp/DoubleSolenoid.cpp
wpilibc/src/main/native/cpp/Solenoid.cpp

Fix moved pneumatics objects not destructing properly

---

wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java

Update DifferentialDrive docs

---

wpilibc/src/main/native/include/frc/MotorSafety.h
wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibc/src/main/native/include/frc/drive/KilloughDrive.h
wpilibc/src/main/native/include/frc/drive/MecanumDrive.h
wpilibc/src/main/native/include/frc/drive/RobotDriveBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/MotorSafety.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/KilloughDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/RobotDriveBase.java

Remove OBE RobotDrive porting guide from MecanumDrive

Improve MotorSafety documentation (NFC)

---

wpimath/src/main/native/include/units/base.h
wpimath/src/test/native/cpp/UnitsTest.cpp

[wpimath] Constexprify units unary operators

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation2dTest.java

[wpimath] Fix Rotation2d interpolation in Java

---

wpimath/src/main/java/edu/wpi/first/math/controller/ImplicitModelFollower.java
wpimath/src/main/native/include/frc/controller/ImplicitModelFollower.h
wpimath/src/test/java/edu/wpi/first/math/controller/ImplicitModelFollowerTest.java
wpimath/src/test/native/cpp/controller/ImplicitModelFollowerTest.cpp

The math works just fine without model discretization.

[wpimath] Remove ImplicitModelFollower dt argument

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java

```java
Rotation2d.fromRotations(1).equals(new Rotation2d(2 * Math.PI)); // true
```
Also adds a member method to get the value of the `Rotation2d` in rotations.

Add Rotation2d factory method that uses rotations

---

wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/Constants.java

This suggest value mirrors the update to the documentation:
https://github.com/wpilibsuite/frc-docs/pull/1792

Reduce suggested acceleration in Ramsete example

---

wpilibc/src/main/native/cpp/simulation/ElevatorSim.cpp
wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibc/src/main/native/include/frc/simulation/ElevatorSim.h
wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h
wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp
wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ElevatorSimTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/Robot.java

[wpilib] Allow disabling ElevatorSim gravity

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/interpolation/TimeInterpolatableBuffer.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/DifferentialDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/main/native/include/frc/interpolation/TimeInterpolatableBuffer.h
wpimath/src/test/java/edu/wpi/first/math/interpolation/TimeInterpolatableBufferTest.java
wpimath/src/test/native/cpp/interpolation/TimeInterpolatableBufferTest.cpp

[wpimath] Fix pose estimator performance

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/EndlessCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/EndlessCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/EndlessCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/PerpetualCommand.h

[command] Rename PerpetualCommand to EndlessCommand

---

wpimath/src/main/java/edu/wpi/first/math/ComputerVisionUtil.java
wpimath/src/main/native/cpp/ComputerVisionUtil.cpp
wpimath/src/main/native/include/frc/ComputerVisionUtil.h
wpimath/src/test/java/edu/wpi/first/math/ComputerVisionUtilTest.java
wpimath/src/test/native/cpp/ComputerVisionUtilTest.cpp

Improved the accuracy of ComputerVisionUtil.calculateDistanceToTarget()

---

wpilibc/src/main/native/cpp/simulation/PWMSim.cpp
wpilibc/src/main/native/include/frc/simulation/PWMSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PWMSim.java

* Compiled C++, not tested
* Not compiled Java

[sim] Allow creating a PWMSim object from a PWMMotorController

---

upstream_utils/libuv_patches/0001-Fix-missing-casts.patch
upstream_utils/libuv_patches/0002-Fix-warnings.patch
upstream_utils/libuv_patches/0003-Preprocessor-cleanup.patch
upstream_utils/libuv_patches/0004-Cleanup-problematic-language.patch
upstream_utils/libuv_patches/0005-Use-roborio-time.patch
upstream_utils/libuv_patches/0006-Style-comments-cleanup.patch
upstream_utils/update_libuv.py
upstream_utils/update_stack_walker.py
upstream_utils/upstream_utils.py

Vendors them both in place, i.e. no updated version (yet)
libuv patches were created such that no actual changes are seen by the repository. These can be burned down at a later time if desired

[upstream utils] vendor libuv, stack walker

---

.github/workflows/comment-command.yml
.github/workflows/lint-format.yml

Add wpiformat command to PRs

---

upstream_utils/upstream_utils.py

Also, giving am_patches() zero patches isn't an error. The function will
just be a no-op.

Apply "git am" patches individually

---

.github/workflows/upstream-utils.yml
upstream_utils/README.md
upstream_utils/upstream_utils.py

Also, add a CI job to ensure the sources in the repo are consistent with
the update scripts.

[upstream_utils] Document how to update thirdparty libraries

---

glass/src/app/native/cpp/main.cpp

The imgui internals methods break with imgui >= 0.87.

[glass] Use glfwSetKeyCallback for Enter key remap

---

wpigui/src/main/native/cpp/wpigui_openurl.cpp
wpigui/src/main/native/include/wpigui_openurl.h

This function opens a URL using the default browser.

[wpigui] Add OpenURL

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/Tachometer.java

now it returns 1/period (like Tachometer.cpp); before it just returned period

fix bug in tachometer frequency

---

wpimath/src/main/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

[wpimath] Reset prev_time on pose estimator reset

---

wpilibc/src/main/native/cpp/motorcontrol/MotorController.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java

Remove unnecessary cast and normalization of voltages

---

wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/native/include/frc/controller/ArmFeedforward.h

[wpimath] Add angle measurement convention to ArmFeedforward docs

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color8Bit.java

Closes #4149
Let me know if there is some other desired convention that we should use for toString()

[wpilibj] Add toString() methods to Color and Color8Bit

---

upstream_utils/libuv_patches/0001-Fix-missing-casts.patch
upstream_utils/libuv_patches/0002-Fix-warnings.patch
upstream_utils/libuv_patches/0003-Preprocessor-cleanup.patch
upstream_utils/libuv_patches/0004-Cleanup-problematic-language.patch
upstream_utils/libuv_patches/0005-Use-roborio-time.patch
upstream_utils/libuv_patches/0006-Style-comments-cleanup.patch
upstream_utils/libuv_patches/0007-Squelch-GCC-12.1-warnings.patch
upstream_utils/libuv_patches/0008-Fix-Win32-warning-suppression-pragma.patch
upstream_utils/libuv_patches/0009-Avoid-unused-variable-warning-on-Mac.patch
upstream_utils/update_libuv.py
wpinet/src/main/native/thirdparty/libuv/src/unix/darwin.cpp

[wpinet] Fix libuv unused variable warning on Mac

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandGenericHID.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandJoystick.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS4Controller.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandGenericHID.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandJoystick.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandPS4Controller.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandXboxController.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandGenericHID.h
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandJoystick.h
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandPS4Controller.h
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandXboxController.h
wpilibc/src/main/native/cpp/GenericHID.cpp
wpilibc/src/main/native/cpp/Joystick.cpp
wpilibc/src/main/native/cpp/PS4Controller.cpp
wpilibc/src/main/native/cpp/XboxController.cpp
wpilibc/src/main/native/include/frc/GenericHID.h
wpilibc/src/main/native/include/frc/Joystick.h
wpilibc/src/main/native/include/frc/PS4Controller.h
wpilibc/src/main/native/include/frc/XboxController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java

Resolves #1888.
Closes #3826.
Depends on #4104.

[wpilib+commands] BooleanEvent/Trigger factories on HID classes

---

build.gradle
styleguide/spotbugs-exclude.xml
wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/ExternalDirectionCounter.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/Tachometer.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/counter/UpDownCounter.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/AbstractInterruptTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PCMTest.java

This fixes a SecurityManager deprecation warning generated by spotbugs.

Upgrade to spotbugs Gradle plugin 5.0.8

---

glass/src/libnt/native/cpp/NetworkTables.cpp
glass/src/libnt/native/include/glass/networktables/NetworkTables.h

Part of #4287. Not sure if what I did was a proper use of the flags. I'd appreciate feedback on this if you have time.

Implement decimal precision in Glass network table view and outline viewer

---

wpigui/src/main/native/cpp/portable-file-dialogs.cpp
wpigui/src/main/native/include/portable-file-dialogs.h

All commits from March 16, 2022 to June 1, 2022. The notable change is this fixes the save button in sysid on macOS.

Update portable file dialogs

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WrapperCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/WrapperCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/WrapperCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp

I'm open to better naming ideas.

[command] Add ignoringDisable decorator

---

README.md

Update location of ni-libraries

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RepeatCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RepeatCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/RepeatCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/RepeatCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/RepeatCommandTest.cpp

Rename command.repeat to repeatedly

---

wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp

This is useful in some debugging scenarios.

[wpiutil] Add JNI access to C++ stderr

---

glass/src/app/native/cpp/main.cpp
glass/src/lib/native/cpp/Context.cpp
glass/src/lib/native/cpp/other/Plot.cpp
imgui/CMakeLists.txt.in
shared/config.gradle
wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui.h

~~Also support viewports, but turn them off by default as they're unstable on multiple platforms.~~

[glass] Update imgui and add docking

---

wpiutil/build.gradle

[build] Include all thirdparty sources in distribution

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDSubsystem.java
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h

Fix ProfiledPIDSubsystem setGoal behavior

---

wpiutil/CMakeLists.txt

Fix wpiutil fmtlib include

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform3d.java
wpimath/src/main/native/cpp/geometry/Pose2d.cpp
wpimath/src/main/native/cpp/geometry/Pose3d.cpp
wpimath/src/main/native/cpp/geometry/Rotation2d.cpp
wpimath/src/main/native/cpp/geometry/Rotation3d.cpp
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/main/native/include/frc/geometry/Rotation3d.h
wpimath/src/main/native/include/frc/geometry/Transform2d.h
wpimath/src/main/native/include/frc/geometry/Transform3d.h

[wpimath] Add scalar multiply and divide operators to all geometry classes

---

wpiutil/build.gradle
wpiutil/src/main/native/cpp/MessagePack.cpp
wpiutil/src/main/native/include/wpi/MessagePack.h

[wpiutil] Add MessagePack utility functions

---

wpilibcExamples/src/main/cpp/examples/HatchbotInlined/cpp/commands/ComplexAuto.cpp

[wpilibcExamples] Fix this-capture in FrisbeeBot

---

wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/include/wpinet/WebSocket.h

Also add compile-time option for verbose debugging.

[wpinet] WebSocket: Add SendFrames()

---

wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/native/cpp/controller/HolonomicDriveController.cpp

[wpimath] Enable continuous angle input for HolonomicDriveController

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryUtil.java
wpimath/src/main/native/include/frc/trajectory/TrajectoryUtil.h

Fix ambiguous documentation for TrajectoryUtil.fromPathWeaverJson()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp

[commands] Add FinallyDo and HandleInterrupt decorators

---

ntcore/src/generate/java/Topic.java.jinja
ntcore/src/main/java/edu/wpi/first/networktables/Topic.java
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/networktables/Topic.h
ntcore/src/main/native/include/networktables/Topic.inc
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

Also fix Publisher comment typo.

[ntcore] Fix C++ Publisher and Subscriber move assignment

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/Subsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h

We forgot to add this overload before.

[cpp cmd] Add CommandPtr overload for SetDefaultCommand

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h

Surprised this overload doesn't exist already.

Add ChassisSpeeds overload for FromFieldRelativeSpeeds

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandBase.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/RobotDisabledCommandTest.java

[commands] Add Command Factories

---

hal/src/main/native/sim/DriverStation.cpp
wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibc/src/test/native/cpp/main.cpp

Add more shutdown checks to the HAL, and a way to shutdown thread motor safety thread from robot/test code.

[hal] Add more shutdown checks and motor safety shutdown

---

OtherVersions.md
buildSrc/src/main/groovy/WPIJREArtifact.groovy
myRobot/build.gradle

Updated to deploy 2023 JRE, and do version checks just like gradlerio.
Deploy using robotCommand, and runs using frcRunRobot.sh (which is in path) rather then directly. This also makes it run as lvuser rather than admin.

Update myRobot deployment

---

.github/workflows/sanitizers.yml

It has fewer false positives than the default GCC.

[ci] Build sanitizers with clang-14

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/MecanumControllerCommandTest.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumBot/include/Drivetrain.h
wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/subsystems/DriveSubsystem.h
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/include/Drivetrain.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveOdometry.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelPositions.java
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/kinematics/MecanumDriveKinematics.cpp
wpimath/src/main/native/cpp/kinematics/MecanumDriveOdometry.cpp
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/kinematics/MecanumDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/MecanumDriveOdometry.h
wpimath/src/main/native/include/frc/kinematics/MecanumDriveWheelPositions.h
wpimath/src/test/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/kinematics/MecanumDriveKinematicsTest.java
wpimath/src/test/java/edu/wpi/first/math/kinematics/MecanumDriveOdometryTest.java
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/kinematics/MecanumDriveKinematicsTest.cpp
wpimath/src/test/native/cpp/kinematics/MecanumDriveOdometryTest.cpp

Fulfills the other half of #4109.
Tasks:
Developed after #4493 passed CI and simply mimicks the design decisions made there. Feedback appreciated.

Position Delta Odometry for Mecanum

---

.github/workflows/documentation.yml

[ci] Revert upgrade of github-pages-deploy-action

---

wpimath/src/main/java/edu/wpi/first/math/ComputerVisionUtil.java
wpimath/src/main/native/cpp/ComputerVisionUtil.cpp
wpimath/src/main/native/include/frc/ComputerVisionUtil.h
wpimath/src/test/java/edu/wpi/first/math/ComputerVisionUtilTest.java
wpimath/src/test/native/cpp/ComputerVisionUtilTest.cpp

[wpimath] Make ComputerVisionUtil use 3D geometry classes

---

wpilibc/src/main/native/cpp/simulation/PS4ControllerSim.cpp
wpilibc/src/main/native/cpp/simulation/XboxControllerSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PS4ControllerSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/XboxControllerSim.java

[wpilib] Fix Xbox/PS4 POV sim

---

wpimath/src/main/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/include/frc/estimator/MecanumDrivePoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

[wpimath] Fix docs for pose estimator local measurement models

---

wpimath/src/main/native/include/frc/controller/ElevatorFeedforward.h

[wpimath] Remove template argument from ElevatorFeedforward

---

wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h

Add comments to SwerveDrivePoseEstimators, per #4538 . (The required comments were already present in the MecanumDrivePoseEstimators.)

Add comment about encoder reset back to pose estimator resetPosition()

---

glass/src/lib/native/cpp/other/Plot.cpp

Fixes #4134
Removed one of the ctors because it was not used any more and would result in repeated code.

Fix y axis not being saved in glass

---

wpinet/build.gradle
wpinet/src/main/native/cpp/jni/WPINetJNI.cpp

Also reenables the check task that would have caught this

[wpinet] Fix incorrect jni definitions

---

wpimath/src/main/native/include/units/angular_acceleration.h

Added Turns per second squared
Added Revolutions per minute squared
Added Revolutions per minute per second

Add additional angular acceleration units

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

Fixes #4593
Fixes #4562
Nullifies #4595

[cmd] Fix Trigger API docs (NFC)

---

MavenArtifacts.md

Add wpinet to MavenArtifacts.md

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFieldLayout.java
apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTagFieldLayout.h
apriltag/src/test/java/edu/wpi/first/apriltag/AprilTagPoseSetOriginTest.java
apriltag/src/test/native/cpp/AprilTagPoseSetOriginTest.cpp

Fix documentation for AprilTagFieldLayout

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/SwerveModule.java

Fix swerve examples to use getDistance for turning encoder

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Pose3d.h

[wpimath] Fix Pose relativeTo documentation

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/Types_internal.h
ntcore/src/main/native/cpp/Value.cpp
ntcore/src/main/native/cpp/Value_internal.cpp
ntcore/src/main/native/cpp/Value_internal.h
ntcore/src/main/native/include/networktables/NetworkTableValue.h
ntcore/src/test/native/cpp/LocalStorageTest.cpp
ntcore/src/test/native/cpp/TestPrinters.cpp

Also fix entry publishing behavior to allow numerically compatible set default publish following a subscribe.
Fixes https://github.com/wpilibsuite/BetaTest/issues/83

[ntcore] Allow numeric-compatible value sets

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp

Als don't data log duplicate NT sets (unless publish keep duplicates flag is set).
Fixes #4629.

[ntcore] Implement keep duplicates pub/sub flag

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp
wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

Fixes https://github.com/wpilibsuite/BetaTest/issues/88.

[wpilib] Update values on controllable sendables

---

wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandHelper.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h

This should allow sending commands to the dashboard:
```cpp
PutData(cmdptr.get())
```

[cpp cmd] Change CommandPtr to use CommandBase

---

wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/subsystems/DriveSubsystem.h

[example] Use EncoderReversed constants

---

wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/native/cpp/controller/HolonomicDriveController.cpp
wpimath/src/main/native/include/frc/controller/HolonomicDriveController.h

Rename HolonomicDriveController.calculate params

---

azure-pipelines-testbench.yaml

These are currently broken with no timetable to fix.

[ci] Disable HW testbench jobs

---

wpilibcExamples/src/main/cpp/examples/CANPDP/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/canpdp/Robot.java

The intention is to RLI to here from https://docs.wpilib.org/en/stable/docs/software/can-devices/power-distribution-module.html.

[example] CANPDP: Expand properties shown

---

glass/src/libnt/native/cpp/NetworkTables.cpp
wpiutil/src/main/native/thirdparty/llvm/cpp/llvm/StringExtras.cpp
wpiutil/src/main/native/thirdparty/llvm/include/wpi/StringExtras.h
wpiutil/src/test/native/cpp/UnescapeCStringTest.cpp

Based on implementation in glass but enhanced for generic use.

[wpiutil] StringExtras: Add UnescapeCString

---

wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/directx11/wpigui_directx11.cpp
wpigui/src/main/native/include/wpigui_internal.h
wpigui/src/main/native/metal/wpigui_metal.mm
wpigui/src/main/native/opengl2/wpigui_opengl2.cpp
wpigui/src/main/native/opengl3/wpigui_opengl3.cpp

[wpigui] Reload fonts to scale rather than preloading

---

wpilibc/src/main/native/cpp/MotorSafety.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/MotorSafety.java

Add link to MotorSafety article

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp

This apparently got missed in #4411

Remove missed isFinished check

---

wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiutil/CMakeLists.txt

[build] Fix cmake install of thirdparty includes

---

ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/test/native/cpp/LocalStorageTest.cpp

It now matches server behavior, where "" doesn't match special topics.
Also fixes duplicate notification that could occur in some cases.

[ntcore] Fix special topic multi-subscriber handling

---

hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/include/hal/DriverStation.h
hal/src/main/native/sim/DriverStation.cpp

Needed to fix https://github.com/robotpy/robotpy-wpilib/issues/632

[hal] Allow overriding stderr printing by HAL_SendError

---

apriltag/CMakeLists.txt
apriltag/apriltag-config.cmake.in
apriltag/build.gradle
apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
apriltag/src/main/java/edu/wpi/first/apriltag/jni/DetectionResult.java
apriltag/src/main/native/cpp/jni/AprilTagJNI.cpp
buildSrc/build.gradle
cscore/build.gradle
datalogtool/build.gradle
glass/build.gradle
outlineviewer/build.gradle
roborioteamnumbersetter/build.gradle
shared/apriltaglib.gradle
shared/config.gradle
shared/imgui.gradle
simulation/halsim_gui/build.gradle
wpigui/build.gradle

Depends on https://github.com/wpilibsuite/native-utils/pull/143 and https://github.com/wpilibsuite/thirdparty-apriltag/pull/1

Update native utils, depend on apriltaglib static library, add apriltag jni

---

shared/examplecheck.gradle
wpilibcExamples/src/main/cpp/examples/UnitTest/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/UnitTest/cpp/subsystems/Intake.cpp
wpilibcExamples/src/main/cpp/examples/UnitTest/include/Constants.h
wpilibcExamples/src/main/cpp/examples/UnitTest/include/Robot.h
wpilibcExamples/src/main/cpp/examples/UnitTest/include/subsystems/Intake.h
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibcExamples/src/test/cpp/examples/UnitTest/cpp/main.cpp
wpilibcExamples/src/test/cpp/examples/UnitTest/cpp/subsystems/IntakeTest.cpp
wpilibjExamples/build.gradle
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/unittest/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/unittest/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/unittest/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/unittest/subsystems/Intake.java
wpilibjExamples/src/test/java/edu/wpi/first/wpilibj/examples/unittest/subsystems/IntakeTest.java

Now we just need to actually write unit tests for the examples.

[gradle/examples] Add unit testing infrastructure to examples

---

.github/workflows/comment-command.yml
README.md

It now runs more than just wpiformat.

[ci] Rename comment command from "/wpiformat" to "/format"

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java
wpimath/src/main/native/include/frc/system/plant/DCMotor.h

Some additions to DCMotor to facilitate other calculations, as well as a WithReduction helper for calculating simple gearbox effects.

Add new DCMotor functions for alternative calculations and reduction calculation

---

cscore/src/main/native/osx/UsbCameraImpl.cpp

- Right now there's really no indication that something is wrong other than there's no camera
Note: haven't compiled or tested this, but seems like it should work?

[cscore] Emit warning that USB Camera isn't supported on OSX

---

wpilibc/src/main/native/cpp/motorcontrol/PWMMotorController.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/PWMMotorController.java

Call set(0) rather than disable for stopMotor on PWMMotorController

---

hal/src/main/native/include/hal/CANAPITypes.h

Matches wpilibsuite/frc-docs#2029.

[hal] Add CANManufacturer for The Thrifty Bot

---

glass/src/lib/native/include/glass/DataSource.h

A lock is needed here due to HAL async callbacks in the sim GUI.
An alternative approach (but more invasive) would be to separately queue HAL updates and update the data source only from the GUI thread.

[glass] DataSource: Add spinlock to protect value

---

hal/src/main/java/edu/wpi/first/hal/HALUtil.java
hal/src/main/java/edu/wpi/first/hal/simulation/RoboRioDataJNI.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/mockdata/RoboRioData.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/simulation/RoboRioDataJNI.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/include/hal/simulation/RoboRioData.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/sim/mockdata/RoboRioData.cpp
hal/src/main/native/sim/mockdata/RoboRioDataInternal.h
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/cpp/simulation/RoboRioSim.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibc/src/main/native/include/frc/simulation/RoboRioSim.h
wpilibc/src/test/native/cpp/simulation/RoboRioSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RoboRioSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/RoboRioSimTest.java

Split off of #4463 
Adds part of #4462

Add RobotController.getSerialNumber()

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.h

Add reference to angleModulus/inputModulus in docs for Rotation2d's input
~~Originally adding mod function to rotation2d~~

[wpimath] Add reference to angleModulus in docs for rotation2d

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java

[commands] Fix incorrect Trigger docs (NFC)

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulerTest.cpp

Also reorder conditions so `runsWhenDisabled` doesn't get called if the command is already scheduled.

[cmd] Test no-op behavior of scheduling a scheduled command

---

wpilibc/src/main/native/cpp/internal/DriverStationModeThread.cpp
wpilibcExamples/src/main/cpp/templates/robotbaseskeleton/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/internal/DriverStationModeThread.java

These need to be automatic reset.

Fix events being manual reset accidentally

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java

Changed many m/s and speeds to m and distance

Fixing docs in SwerveModulePosition

---

hal/src/main/native/sim/PowerDistribution.cpp

[sim] Implement PD total current and power

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Intake.java

Fix array indices in example

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h

[commands] Fix typo in waitUntil docs (NFC)

---

wpilibcExamples/build.gradle
wpilibjExamples/build.gradle

This PR links `edu.wpi.first.apriltag `package in wpilibjExamples `build.gradle`. 
Resolves #4844

Link apriltag package in wpilibjExamples build.gradle

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommand.java
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc
wpimath/src/main/native/include/frc/controller/HolonomicDriveController.h

Also adds copy and move constructors to HolonomicDriveController

[commands] Add constructor for SwerveControllerCommand that takes a HolonomicDriveController

---

ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableType.java
ntcore/src/main/java/edu/wpi/first/networktables/PubSubOption.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SelectCommand.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/java/edu/wpi/first/math/spline/SplineHelper.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryGenerator.java
wpiutil/src/main/java/edu/wpi/first/util/CircularBuffer.java
wpiutil/src/main/java/edu/wpi/first/util/EventVector.java
wpiutil/src/main/java/edu/wpi/first/util/RuntimeLoader.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogReader.java

Mostly just redundant changes. Also fixed some probable bugs and removed unneeded boxing where applicable.
Edit:
Added a comment in order to address #4856 so future devs don't get confused too

Java optimization and formatting fixes

---

buildSrc/build.gradle

Contains fix https://github.com/wpilibsuite/native-utils/pull/152 in native-utils - @ThadHouse okay to merge this?

Update native-utils version

---

wpilibjExamples/build.gradle

Fix examples linking in incorrect jni library

---

ntcore/src/generate/java/NetworkTableInstance.java.jinja
ntcore/src/generate/java/NetworkTablesJNI.java.jinja
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableEvent.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableListener.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTableListenerPoller.java
ntcore/src/main/java/edu/wpi/first/networktables/TimeSyncEventData.java
ntcore/src/main/native/cpp/IListenerStorage.h
ntcore/src/main/native/cpp/INetworkClient.h
ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/InstanceImpl.h
ntcore/src/main/native/cpp/ListenerStorage.cpp
ntcore/src/main/native/cpp/ListenerStorage.h
ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkClient.h
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.inc
ntcore/src/main/native/include/networktables/NetworkTableListener.h
ntcore/src/main/native/include/networktables/NetworkTableListener.inc
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h
ntcore/src/test/java/edu/wpi/first/networktables/TimeSyncTest.java
ntcore/src/test/native/cpp/MockListenerStorage.h
ntcore/src/test/native/cpp/TimeSyncTest.cpp
ntcoreffi/src/main/native/symbols.txt

Also exposes this as an event signaled when the offset is updated due to a ping response from the server.
Fixes #4690.

[ntcore] Add method to get server time offset

---

wpilibc/src/main/native/cpp/shuffleboard/Shuffleboard.cpp

- Needed for RobotPy test framework

[wpilibc] Add function to reset Shuffleboard instance

---

hal/src/main/native/sim/MockHooks.cpp
wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpimath/src/main/native/cpp/trajectory/constraint/DifferentialDriveVoltageConstraint.cpp
wpimath/src/main/native/include/frc/system/NumericalIntegration.h

Fix usages of std::min and std::max to be windows safe

---

glass/src/libnt/native/cpp/NetworkTables.cpp
glass/src/libnt/native/include/glass/networktables/NetworkTables.h
ntcore/src/main/native/cpp/ntcore_meta.cpp
ntcore/src/main/native/cpp/ntcore_meta_c.cpp
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h
ntcoreffi/src/main/native/symbols.txt

~~These are put into a separate header (ntcore_meta.h) due to additional header dependencies (in particular, optional).~~

[ntcore] Refactor meta-topic decoding from glass

---

wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h

- C++ best practice if there are other functions that are virtual

[commands] Make Subsystem destructor virtual

---

wpilibc/src/main/native/include/frc/Compressor.h
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibc/src/main/native/include/frc/PneumaticsBase.h
wpilibc/src/main/native/include/frc/PneumaticsControlModule.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsControlModule.java

Also update Compressor docs for consistency.
Closes #4040

Add/update documentation to PneumaticBase and subclasses (NFC)

---

README.md

Change to adoptium, and add Xcode min version

Update build requirements (NFC)

---

wpilibc/src/test/native/cpp/JoystickTest.cpp

[cpp] Add test case for fast deconstruction of GenericHID

---

wpilibc/src/main/native/cpp/simulation/SingleJointedArmSim.cpp
wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h
wpilibc/src/test/native/cpp/simulation/SingleJointedArmSimTest.cpp
wpilibc/src/test/native/cpp/simulation/StateSpaceSimTest.cpp
wpilibcExamples/src/main/cpp/examples/ArmSimulation/cpp/Robot.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSimTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/armsimulation/Robot.java

Previous calculation derivation mixed up length and distance to CG

Fix MOI calculation error in SingleJointedArmSim

---

wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumcontrollercommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdrive/Robot.java

Fix swapped arguments in MecanumControllerCommand example

---

wpilibNewCommands/build.gradle

Include wpimathjni in commands binaries

---

wpilibc/src/main/native/cpp/ADXRS450_Gyro.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java

[wpilib] Fix C++ ADXRS450 and Java SPI gyro defs

---

upstream_utils/eigen_patches/0002-Intellisense-fix.patch
upstream_utils/update_eigen.py
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/util/Macros.h

See https://github.com/microsoft/vscode-cpptools/issues/7413
Fixes wpilibsuite/vscode-wpilib#574

[wpimath] Workaround intellisense Eigen issue

---

wpilibc/src/main/native/include/frc/XboxController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java

Comments for leftTrigger said they attach to the right trigger of the controller

[wpilib] XboxController: Fix docs discrepancy (NFC)

---

wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/include/frc/Timer.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java

[wpilib] Add Timer::Restart()

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp

[wpimath] Make PIDController::Calculate(double, double) update setpoint flag

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WaitCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/MecanumControllerCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/RamseteCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/WaitCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/SwerveControllerCommand.inc
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SwerveControllerCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/MecanumControllerCommandTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/SwerveControllerCommandTest.cpp
wpilibcExamples/src/main/cpp/examples/GettingStarted/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/gettingstarted/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Robot.java

refactors internal code to use the Timer::Restart() method added in #4963

Update code to use new Timer.Restart();

---

wpilibNewCommands/src/main/native/include/frc2/command/Commands.h
wpilibcExamples/src/main/cpp/examples/SelectCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/SelectCommand/include/RobotContainer.h

[cmd cpp] Fix Select() factory

---

wpiutil/examples/printlog/datalog.py

so NT4 users can see their logs

add msgpack to datalog example

---

wpilibc/src/main/native/include/frc/DriverStation.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

Clarify DS functions provided by FMS (NFC)

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation2d.java
wpimath/src/main/native/cpp/geometry/Pose2d.cpp
wpimath/src/main/native/cpp/geometry/Translation2d.cpp
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Translation2d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose2dTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Translation2dTest.java
wpimath/src/test/native/cpp/geometry/Pose2dTest.cpp
wpimath/src/test/native/cpp/geometry/Translation2dTest.cpp

Add nearest to Pose2d and Translation2d

---

ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp

Previously the timeout was 10 times the update rate, so with low update rates it could be as small as 50 ms, causing spurious disconnects when large or many topics were published.

[ntcore] Change wire timeout to fixed 1 second

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/native/cpp/geometry/Pose3d.cpp
wpimath/src/main/native/cpp/geometry/Rotation3d.cpp
wpimath/src/main/native/include/frc/geometry/Rotation3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation3dTest.java
wpimath/src/test/native/cpp/geometry/Rotation3dTest.cpp

[wpimath] Fix Pose3d exp()/log() and add rotation vector constructor to Rotation3d

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.h

Also fix memory leak in WebSocketConnection destructor.

[ntcore] Improve disconnect error reporting

---

wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.h

Resolves #5071 with a more obvious error message.

[wpilibc] SendableChooser: static_assert copy- and default-constructibility

---

wpilibcExamples/src/main/cpp/examples/examples.json
wpilibcExamples/src/main/cpp/templates/templates.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json

Fixes #5042
Many example descriptions consisted of "An example project demostrating use of ...", that significantly bites into the less-than-100 characters visible in VS Code (which is also something we should improve, but that's a separate problem).

[examples, templates] Improve descriptions (NFC)

---

ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.h
ntcore/src/main/native/cpp/net/WireConnection.h
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp
ntcore/src/main/native/cpp/net3/UvStreamConnection3.cpp
ntcore/src/main/native/cpp/net3/UvStreamConnection3.h
ntcore/src/main/native/cpp/net3/WireConnection3.h
ntcore/src/test/native/cpp/net/MockWireConnection.h
ntcore/src/test/native/cpp/net3/MockWireConnection3.h
wpinet/src/main/native/cpp/WebSocket.cpp

Mixing the announce and value messages causes significant downstream
inefficiency in both time and space.

[ntcore] Reduce initial connection overhead

---

glass/src/libnt/native/cpp/NetworkTables.cpp
glass/src/libnt/native/include/glass/networktables/NetworkTables.h
outlineviewer/src/main/native/cpp/main.cpp

This also allows creating topics when there are no existing topics.

[glass,ov] Provide menu item to create topic from root

---

docs/build.gradle

strip path from generated nt docs

---

.clang-format

This does not result in any reformatting

Update .clang-format to c++20

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/RobotBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

Fix enableLiveWindowInTest crashing in disabled

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WaitCommand.java
wpilibNewCommands/src/main/native/include/frc2/command/WaitCommand.h

[cmd docs] WaitCommand: Remove subclass note (NFC)

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardInstance.cpp
wpilibc/src/test/native/cpp/shuffleboard/ShuffleboardInstanceTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardInstance.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardInstanceTest.java

Required for wpilibsuite/shuffleboard#771.

[wpilib] Shuffleboard: Keep duplicates on SelectTab()

---

.gitattributes

[gitattributes] Mark json files as lf text files

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc
wpimath/src/test/java/edu/wpi/first/math/kinematics/SwerveDriveKinematicsTest.java
wpimath/src/test/native/cpp/kinematics/SwerveDriveKinematicsTest.cpp

Fix desaturateWheelSpeeds to account for negative speeds

---

wpilibc/src/main/native/include/frc/XboxController.h

In response to [issue #4972](https://github.com/wpilibsuite/allwpilib/issues/4972)

[cpp docs] Add return tags to XboxController doxygen

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandDecoratorTest.cpp

Open to naming/wording changes, also I'm unsure about the C++ implementation.

[cmd] Add onlyWhile and onlyIf

---

hal/src/main/native/include/hal/CANAPITypes.h

Matches wpilibsuite/frc-docs#2225

[hal] Add CANManufacturer for Redux Robotics

---

wpilibc/src/main/native/include/frc/RobotBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

[Docs] Update RobotBase documentation (NFC)

---

datalogtool/src/main/native/cpp/Downloader.cpp
datalogtool/src/main/native/cpp/Downloader.h

[dlt] Add delete without download functionality

---

.github/workflows/documentation.yml

Update deploy and sshagent actions

---

wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java
wpiutil/src/main/native/include/wpi/DataLog.h

There wasn't any documentation, so I copy-pasted some together.

Add Javadocs for DataLog append methods

---

.github/workflows/comment-command.yml

No clue if this will fix it, but let's test it out

Fix /format nuking everything C++

---

hal/src/main/java/edu/wpi/first/hal/CANAPIJNI.java
hal/src/main/java/edu/wpi/first/hal/CANData.java
hal/src/main/native/athena/CANAPI.cpp
hal/src/main/native/cpp/jni/CANAPIJNI.cpp
hal/src/main/native/include/hal/CANAPI.h
hal/src/main/native/sim/CANAPI.cpp
wpilibc/src/main/native/cpp/CAN.cpp
wpilibc/src/main/native/include/frc/CAN.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/CAN.java

Can be useful to teams and vendors utilizing CAN timestamps. 
Also fixes and updates some documentation

[wpilib][hal] Expose CAN timestamp base clock

---

wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java

Kinda addresses #5280. Also prints deleted files, if any.

Add warnings for low storage space

---

myRobot/build.gradle
shared/javacpp/setupBuild.gradle
shared/jni/setupBuild.gradle
wpilibj/build.gradle
wpilibjExamples/build.gradle

Fix loading tests on macos 12

---

cscore/src/main/java/edu/wpi/first/cscore/VideoMode.java
cscore/src/test/java/edu/wpi/first/cscore/VideoModeTest.java

see https://github.com/PhotonVision/photonvision/pull/859

[cscore] Add equal override to VideoMode Java implement

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc

Rename currentChassisSpeed to desiredChassisSpeed

---

shared/java/javastyle.gradle

Was causing failures in fieldimages

Exclude files in bin from Spotless

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ConditionalCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/ConditionalCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/ConditionalCommand.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/ConditionalCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/ConditionalCommandTest.cpp

[cmd] Implement ConditionalCommand.getInterruptBehavior()

---

wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/cpp/RapidReactCommandBot.cpp
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/cpp/subsystems/Pneumatics.cpp
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/RapidReactCommandBot.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Intake.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Pneumatics.h
wpilibcExamples/src/main/cpp/examples/Solenoid/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/Solenoid/include/Robot.h
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/RapidReactCommandBot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Intake.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Pneumatics.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/solenoid/Robot.java

Goal here is to RLI the example.

[examples] Improve Pneumatics example coverage in Solenoid and RapidReactCmdBot examples

---

ThirdPartyNotices.txt
docs/build.gradle
wpimath/CMakeLists.txt
wpimath/build.gradle
wpimath/src/test/native/cpp/estimator/MerweScaledSigmaPointsTest.cpp

Remove references to Drake

---

.github/workflows/documentation.yml

Push to different branches for beta/release/development. The docs repo workflow will do the combine for publishing.

[ci] Change documentation publish to single-commit

---

wpimath/algorithms.md
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/native/cpp/geometry/Rotation3d.cpp
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation3dTest.java
wpimath/src/test/native/cpp/geometry/Rotation3dTest.cpp

Fixes #4994
The `1e-20` threshold was just made up, it could be adjusted if desired.

[wpimath] Improve Euler angle calculations in gimbal lock

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java

Update method names in requireNonNullParam in Trigger

---

wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.inc
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooserBase.h
wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooserTest.java

C++ doesn't work right now, my test is throwing an exception with "device or resource busy: device or resource busy" which I assume is a mutex/lock thing. How do I fix that?

Add onChange listener to SendableChooser

---

wpilibc/src/main/native/cpp/DutyCycleEncoder.cpp
wpilibc/src/main/native/cpp/simulation/DutyCycleEncoderSim.cpp
wpilibc/src/main/native/include/frc/simulation/DutyCycleEncoderSim.h
wpilibc/src/test/native/cpp/simulation/DutyCycleEncoderSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DutyCycleEncoder.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DutyCycleEncoderSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DutyCycleEncoderSimTest.java

Expand DutyCycleEncoderSim API

---

ntcore/src/generate/cpp/jni/types_jni.cpp.jinja
ntcore/src/generate/java/EntryImpl.java.jinja
ntcore/src/generate/java/GenericEntryImpl.java.jinja
ntcore/src/generate/java/GenericPublisher.java.jinja
ntcore/src/generate/java/NetworkTableEntry.java.jinja
ntcore/src/generate/java/NetworkTablesJNI.java.jinja
ntcore/src/generate/java/Publisher.java.jinja
ntcore/src/test/java/edu/wpi/first/networktables/RawTest.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogJNI.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/RawLogEntry.java
wpiutil/src/main/native/cpp/jni/DataLogJNI.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.h

Add support for start, length, and ByteBuffers.
This is needed for efficient protobuf/struct support.

Enhance Java raw value support in DataLog and NT

---

hal/src/main/java/edu/wpi/first/hal/REVPHFaults.java

[hal/java] Fix REVPH faults bitfield

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/WheelPositions.java
wpimath/src/main/native/include/frc/kinematics/SwerveModulePosition.h

Also changes wording of `WheelPositions.minus` doc comment
How well does documenting C++ concepts work with doxygen? I could also add some documentation for C++ WheelPositions too in this PR if desired.

[wpimath] Improve wording for SwerveModulePosition::operator- (NFC)

---

glass/src/libnt/native/cpp/NetworkTablesSettings.cpp

[glass] Add tooltips for Glass NT settings

---

wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LinearQuadraticRegulator.java
wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/include/frc/controller/LTVDifferentialDriveController.h
wpimath/src/main/native/include/frc/controller/LTVUnicycleController.h
wpimath/src/main/native/include/frc/controller/LinearQuadraticRegulator.h
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/KalmanFilter.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h

[wpimath] Link to docs on LQR and KF tolerances (NFC)

---

wpilibc/src/main/native/include/frc/simulation/DCMotorSim.h
wpilibc/src/main/native/include/frc/simulation/DifferentialDrivetrainSim.h
wpilibc/src/main/native/include/frc/simulation/ElevatorSim.h
wpilibc/src/main/native/include/frc/simulation/FlywheelSim.h
wpilibc/src/main/native/include/frc/simulation/SingleJointedArmSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DCMotorSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/ElevatorSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/FlywheelSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.java

[wpilib] Document how to create LinearSystem object for physics sim classes (NFC)

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/cpp/geometry/Pose3d.cpp
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Pose2d.inc
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose2dTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose3dTest.java
wpimath/src/test/native/cpp/geometry/Pose2dTest.cpp
wpimath/src/test/native/cpp/geometry/Pose3dTest.cpp

[wpimath] Add RotateBy() function to pose classes

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryParameterizer.java
wpimath/src/main/native/cpp/trajectory/TrajectoryParameterizer.cpp

[wpimath] Give infeasible trajectory constraints a better exception message

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/Trajectory.java
wpimath/src/main/native/cpp/trajectory/Trajectory.cpp
wpimath/src/main/native/include/frc/trajectory/Trajectory.h

[wpimath] Make Trajectory throw on empty lists of States from users

---

glass/src/app/native/cpp/main.cpp
outlineviewer/src/main/native/cpp/main.cpp

Detect changes to mode and update based on mode change and connection events.

[glass] Improve Glass and OutlineViewer title bar message

---

ntcore/src/generate/cpp/ntcore_cpp_types.cpp.jinja
ntcore/src/generate/include/ntcore_cpp_types.h.jinja
ntcore/src/generate/types.json
ntcore/src/main/native/cpp/ListenerStorage.cpp
ntcore/src/main/native/cpp/ListenerStorage.h
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/Log.h
ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkClient.h
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/NetworkServer.h
ntcore/src/main/native/cpp/ValueCircularBuffer.cpp
ntcore/src/main/native/cpp/ValueCircularBuffer.h
ntcore/src/main/native/cpp/Value_internal.cpp
ntcore/src/main/native/cpp/Value_internal.h
ntcore/src/main/native/cpp/VectorSet.h
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.h
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp
ntcore/src/main/native/cpp/net3/ClientImpl3.h
ntcore/src/main/native/cpp/net3/WireDecoder3.cpp
ntcore/src/main/native/cpp/net3/WireDecoder3.h
ntcore/src/test/native/cpp/LocalStorageTest.cpp

Also change Timestamped into a template

[ntcore] Remove pImpl from implementation

---

wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/include/wpinet/WebSocket.h
wpinet/src/test/native/cpp/WebSocketIntegrationTest.cpp

This is required by the spec (RFC 6455 section 5.5.2).

[wpinet] WebSocket: Send pong in response to ping

---

glass/src/lib/native/cpp/other/Plot.cpp

Fixes #2722 
Plot looks kind of bad when you use full saturation colors... might be able to manipulate the gridline color based on the background.

[glass,simgui] Add background color selector to glass plots

---

glass/src/lib/native/cpp/Storage.cpp

[glass] Fix array crash when clearing existing workspace

---

wpiutil/CMakeLists.txt

Fixes https://github.com/wpilibsuite/allwpilib/issues/5519 by applying https://github.com/wpilibsuite/allwpilib/issues/5519#issuecomment-1668796247

Fix the windows build with fmt 

---

wpimath/src/main/native/cpp/jni/WPIMathJNI.cpp

DARE is being converted in #5543.

[wpimath] Use JDoubleArrayRef in all JNI functions except DARE

---

build.gradle
cameraserver/multiCameraServer/build.gradle
cscore/src/main/java/edu/wpi/first/cscore/CameraServerCvJNI.java
fieldImages/build.gradle
hal/src/main/java/edu/wpi/first/hal/AccumulatorResult.java
hal/src/main/java/edu/wpi/first/hal/AnalogJNI.java
hal/src/main/java/edu/wpi/first/hal/CANData.java
ntcore/src/generate/java/NetworkTableInstance.java.jinja
shared/java/javacommon.gradle
shared/java/javastyle.gradle
styleguide/pmd-ruleset.xml
wpilibj/src/main/java/edu/wpi/first/wpilibj/Encoder.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/BooleanEvent.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooser.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/RobotControllerTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/livewindow/LiveWindowTest.java
wpilibjExamples/build.gradle
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/unittest/Robot.java
wpimath/build.gradle
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/java/edu/wpi/first/util/EventVector.java
wpiutil/src/test/java/edu/wpi/first/util/cleanup/ReflectionCleanupTest.java

The following source code changes were required:
* Whitespace changes from spotless
* PMD warning suppressions for utility class tests
* PMD warning rename from "BeanMembersShouldSerialize" to "NonSerializableClass"
* Declared more class members as final

Upgrade Maven dependencies

---

wpilibNewCommands/src/main/native/cpp/frc2/command/ProxyCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/ProxyCommand.h

[cpp cmd] Add CommandPtr supplier constructor to ProxyCommand

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h

Change ChassisSpeeds docs to say values aren't relative to the robot 

---

hal/src/main/java/edu/wpi/first/hal/simulation/RoboRioDataJNI.java
hal/src/main/native/athena/mockdata/RoboRioData.cpp
hal/src/main/native/cpp/jni/simulation/RoboRioDataJNI.cpp
hal/src/main/native/include/hal/simulation/RoboRioData.h
hal/src/main/native/sim/mockdata/RoboRioData.cpp
hal/src/main/native/sim/mockdata/RoboRioDataInternal.h
wpilibc/src/main/native/cpp/simulation/RoboRioSim.cpp
wpilibc/src/main/native/include/frc/simulation/RoboRioSim.h
wpilibc/src/test/native/cpp/simulation/RoboRioSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RoboRioSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/RoboRioSimTest.java

Found in an unapplied stash... oops.

Fix unfinished/incorrect GetCPUTemp functions

---

hal/src/main/java/edu/wpi/first/hal/HALUtil.java
hal/src/main/java/edu/wpi/first/hal/simulation/RoboRioDataJNI.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/mockdata/RoboRioData.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/simulation/RoboRioDataJNI.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/include/hal/simulation/RoboRioData.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/sim/mockdata/RoboRioData.cpp
hal/src/main/native/sim/mockdata/RoboRioDataInternal.h
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/cpp/simulation/RoboRioSim.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibc/src/main/native/include/frc/simulation/RoboRioSim.h
wpilibc/src/test/native/cpp/simulation/RoboRioSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RoboRioSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/RoboRioSimTest.java

[wpilib][hal] Add GetTeamNumber

---

wpilibcExamples/src/main/cpp/examples/MecanumBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Drivetrain.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h
wpimath/src/test/java/edu/wpi/first/math/kinematics/ChassisSpeedsTest.java
wpimath/src/test/native/cpp/kinematics/ChassisSpeedsTest.cpp

This better reflects what's actually going on mathematically.

[wpimath] Rename ChassisSpeeds.fromDiscreteSpeeds() to discretize()

---

ntcore/ntcore-config.cmake.in

See
https://github.com/wpilibsuite/allwpilib/blob/f63d9589958b46ca4d3530025b7334c12f33cb30/ntcore/CMakeLists.txt#L32

Add missing find_dependency call

---

.github/workflows/gradle.yml
buildSrc/src/main/groovy/MultiBuilds.groovy

This doesn't affect windows, because there it would require a massive amount of changes to build on windows.

Run Google tests in release mode

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFieldLayout.java
apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFields.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/Drivetrain.java

This eliminates the need for users to wrap initialization of the fields in a try/catch.

[apriltag] Make loadAprilTagFieldLayout throw an unchecked exception instead

---

wpimath/src/main/java/edu/wpi/first/math/filter/SlewRateLimiter.java
wpimath/src/main/native/include/frc/filter/SlewRateLimiter.h

Remove SlewRateLimiter 2 argument constructor

---

wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/include/frc/Compressor.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java

Remove Compressor.Enabled()

---

wpinet/src/main/native/include/wpinet/uv/Buffer.h

Also add uint8_t constructors.

[wpinet] uv::Buffer: Add bytes() accessor

---

ntcore/src/main/native/cpp/Value.cpp
ntcore/src/main/native/cpp/net/NetworkLoopQueue.cpp
ntcore/src/main/native/include/networktables/NetworkTableValue.h

This avoids a later switch-based computation in NetworkLoopQueue.

[ntcore] Compute Value memory size when creating value

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h

[cmd] Add proxy factory to Commands

---

ntcore/CMakeLists.txt
ntcore/src/test/native/cpp/LocalStorageTest.cpp
ntcore/src/test/native/cpp/TestPrinters.cpp
ntcore/src/test/native/cpp/TestPrinters.h
ntcore/src/test/native/cpp/net/ServerImplTest.cpp
ntcore/src/test/native/cpp/net/WireEncoderTest.cpp
ntcore/src/test/native/cpp/net3/WireDecoder3Test.cpp
ntcore/src/test/native/cpp/net3/WireEncoder3Test.cpp
shared/javacpp/setupBuild.gradle
shared/jni/setupBuild.gradle
wpiutil/.styleguide
wpiutil/CMakeLists.txt
wpiutil/src/test/native/include/wpi/SpanMatcher.h
wpiutil/src/test/native/include/wpi/TestPrinters.h

[wpiutil] Refactor SpanMatcher and TestPrinters from ntcore

---

wpilibc/src/main/native/cpp/simulation/EncoderSim.cpp
wpilibc/src/main/native/include/frc/simulation/EncoderSim.h

Apparently these were missed at some point.

[cpp sim] Const-qualify EncoderSim getters

---

datalogtool/src/main/native/cpp/App.cpp
datalogtool/src/main/native/cpp/App.h
glass/src/lib/native/cpp/support/ExtraGuiWidgets.cpp
glass/src/lib/native/include/glass/Window.h
glass/src/lib/native/include/glass/other/Field2D.h
glass/src/lib/native/include/glass/other/Mechanism2D.h
glass/src/lib/native/include/glass/support/ExtraGuiWidgets.h
imgui/CMakeLists.txt
shared/imgui.gradle

Upgrade implot to fix deprecation warning for sprintf(), and upgrade imgui docking branch to match.

[build] Upgrade ImGUI

---

apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
cameraserver/multiCameraServer/src/main/native/cpp/main.cpp
glass/src/lib/native/cpp/Context.cpp
glass/src/lib/native/cpp/other/Field2D.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
simulation/halsim_ws_server/src/main/native/cpp/HALSimHttpConnection.cpp
wpimath/src/main/native/cpp/trajectory/TrajectoryUtil.cpp

Instances of wpi::raw_istream were left that are reading incrementally from file descriptors like USB devices.

Replace wpi::raw_istream with wpi::MemoryBuffer

---

.github/workflows/cmake.yml
glass/CMakeLists.txt
googletest/CMakeLists.txt
ntcore/CMakeLists.txt
ntcore/src/test/native/cpp/LocalStorageTest.cpp
ntcore/src/test/native/cpp/TableListenerTest.cpp
ntcore/src/test/native/cpp/net/ServerImplTest.cpp
outlineviewer/CMakeLists.txt
wpigui/CMakeLists.txt

Also properly applies warning flags for some targets

[build][cmake] Fix windows tests and re-enable ci tests

---

.github/workflows/gradle.yml

- Free up disk space on Linux by deleting unused packages
- Move build to C drive on Windows

[ci] Fix Gradle disk space issues

---

hal/src/main/java/edu/wpi/first/hal/HAL.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/cpp/jni/HAL.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/sim/HAL.cpp
shared/config.gradle
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

This returns true when the system date/time (wall clock) is valid.

[hal] Add getSystemTimeValid()

---

.github/workflows/gradle.yml

The if checking of an environment variable doesn't seem to compare correctly.

[ci] Unbreak combiner

---

wpiutil/src/main/native/cpp/DataLog.cpp

Pause logging if more than 1 MB of outgoing buffers are allocated. Limit free buffer list to 256 KB.
Fixes #5201.

[wpiutil] DataLog: Limit total buffer allocation

---

ntcore/src/main/native/cpp/LocalStorage.cpp

[ntcore] Correctly start DataLog for existing publishers

---

wpilibc/src/main/native/cpp/DataLogManager.cpp
wpiutil/src/main/native/cpp/DataLog.cpp

[wpiutil] DataLog: Stop logging if insufficient free space

---

.github/workflows/gradle.yml

Addresses the same issue as https://github.com/addnab/docker-run-action/pull/17 (not yet tagged).

[ci] Fix -dirty version

---

wpigui/src/main/native/cpp/wpigui.cpp

[wpigui] Fix loading a maximized window on second monitor

---

settings.gradle

Update enterprise plugin

---

wpilibjExamples/build.gradle

This test regularly fails on Win64Debug in CI.

[build] Disable armsimulation unit test

---

romiVendordep/RomiVendordep.json
wpilibNewCommands/WPILibNewCommands.json
xrpVendordep/XRPVendordep.json

Required by wpilibsuite/native-utils#170.
Also see wpilibsuite/native-utils#168.
Fixes #5678.

[commands,romi,xrp] Add frcYear to vendordep

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java

[wpimath] Fix hardcoded module count in SwerveDriveKinematics.resetHeading()

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java
wpimath/src/main/native/include/frc/system/plant/DCMotor.h

[wpimath] Add DCMotor functions for Kraken X60 and Neo Vortex

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

[wpilib] Close sim device in ADIS IMUs

---

wpinet/src/main/native/thirdparty/tcpsockets/cpp/TCPConnector_parallel.cpp

Thread_local causes issues with LabVIEW, which makes calls on a thread pool.

[wpinet] TCPConnector_parallel: Don't use thread_local

---

.github/workflows/gradle.yml

Depends on/corresponds with https://github.com/wpilibsuite/build-tools/pull/79 (!!!)

Update JDK for combine step

---

hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/sim/DriverStation.cpp

Closes https://github.com/wpilibsuite/2024Beta/issues/18

Fix HAL AllianceStation on rio

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.h

Fixes a potential use-after-free on connection close.

[ntcore] WebSocketConnection: Use weak capture

---

wpimath/src/main/java/edu/wpi/first/math/estimator/ExtendedKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/include/frc/estimator/ExtendedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h

Also clean up comments on other overloads and fix a typo.

[wpimath] Add EKF/UKF u-y-R correct overload

---

wpilibcExamples/publish.gradle
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/publish.gradle
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json

Closes #5837 on the allwpilib side.

Export unit tests for examples

---

glass/src/libnt/native/cpp/NetworkTables.cpp

Fixes #5815 
https://github.com/wpilibsuite/allwpilib/assets/42757516/605d68e9-2bf0-4440-b737-d3c21eaee51b
A possible issue with its current state is the text overlap on struct/protobuf and arrays when it is small, see end of video.

[glass] Fix Position of Data Type in NT Tree View

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net3/UvStreamConnection3.cpp

This helps asan catch more errors.

[ntcore] Disable buf pool when asan is enabled

---

hal/src/main/native/include/hal/CANAPITypes.h

Add CAN IDs for AndyMark and Vivid Hosting

Add CAN IDs for AM and VH

---

cscore/src/main/native/linux/UsbCameraImpl.cpp
cscore/src/main/native/objcpp/UsbCameraImplObjc.mm
cscore/src/main/native/windows/UsbCameraImpl.cpp
cscore/src/test/java/edu/wpi/first/cscore/UsbCameraTest.java

Reword "Connecting to..." to "Attempting to connect to" and add "Connected to..." message
resolves #5729

[cscore] Make camera connection logging clearer

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFieldLayout.java
apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTagFieldLayout.h

[apriltag] AprilTagFieldLayout: Add accessors for origin and field dimensions

---

ntcore/src/main/native/include/networktables/ProtobufTopic.h
ntcore/src/main/native/include/networktables/StructArrayTopic.h
ntcore/src/main/native/include/networktables/StructTopic.h

These were missed due to PR merge order.
Also fix ProtobufEntry construction.

[ntcore] Use json_fwd

---

wpilibcExamples/src/main/cpp/examples/MecanumDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/Drivetrain.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Drivetrain.java

replaced gyro rotation with poseEstimator rotation

---

fieldImages/publish.gradle

Nothing appears to be using the existing name

Fix typo in field images artifact name

---

ntcoreffi/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java

[wpilib] Change default Rio log dir from /home/lvuser to /home/lvuser/logs

---

shared/jni/setupBuild.gradle

[build] Add generated protobuf headers to C++ test include path

---

shared/jni/setupBuild.gradle

[build] Add generateProto dependency to test and dev

---

cscore/src/main/native/cpp/CvSinkImpl.cpp
cscore/src/main/native/include/cscore_c.h

This fixes a compilation error introduced by #5923.

[cscore] Replace CS_PixelFormat with WPI_PixelFormat

---

wpimath/src/main/java/edu/wpi/first/math/path/TravelingSalesman.java
wpimath/src/main/native/include/frc/path/TravelingSalesman.h
wpimath/src/test/java/edu/wpi/first/math/path/TravelingSalesmanTest.java
wpimath/src/test/native/cpp/path/TravelingSalesmanTest.cpp

[wpimath] Rotate traveling salesman solution so input and solution have same initial pose

---

.github/workflows/cmake.yml
.github/workflows/pregenerate.yml
.github/workflows/sanitizers.yml
wpimath/build.gradle
wpiutil/CMakeLists.txt
wpiutil/build.gradle

[wpimath, wpiutil] bump quickbuf from 1.3.2 -> 1.3.3

---

wpilibc/src/main/native/include/frc/AddressableLED.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLED.java

Say that multiple strips can be used in series

[Doc] Update warning about single AddressableLED driver (NFC)

---

datalogtool/src/main/native/cpp/Downloader.cpp
ntcoreffi/src/main/native/include/DataLogManager.h
wpilibc/src/main/native/include/frc/DataLogManager.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java

Change datalogtool default folder to log folder

---

hal/src/main/java/edu/wpi/first/hal/LEDJNI.java
hal/src/main/java/edu/wpi/first/hal/simulation/RoboRioDataJNI.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/HALInitializer.h
hal/src/main/native/athena/LEDs.cpp
hal/src/main/native/athena/mockdata/RoboRioData.cpp
hal/src/main/native/cpp/jni/LEDJNI.cpp
hal/src/main/native/cpp/jni/simulation/RoboRioDataJNI.cpp
hal/src/main/native/include/hal/HAL.h
hal/src/main/native/include/hal/LEDs.h
hal/src/main/native/include/hal/simulation/RoboRioData.h
hal/src/main/native/sim/LEDs.cpp
hal/src/main/native/sim/mockdata/RoboRioData.cpp
hal/src/main/native/sim/mockdata/RoboRioDataInternal.h
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/cpp/simulation/RoboRioSim.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibc/src/main/native/include/frc/simulation/RoboRioSim.h
wpilibc/src/test/native/cpp/simulation/RoboRioSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RoboRioSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/RoboRioSimTest.java

The "LEDs" HAL files can be merged into HALBase or wherever if desired, I added them so as to not clutter HALBase/HAL even more
I can add a function to read the state as well, if that's desired.

Add function to control "Radio" LED

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandStadiaController.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandStadiaController.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandStadiaController.h
wpilibc/src/main/native/cpp/StadiaController.cpp
wpilibc/src/main/native/include/frc/StadiaController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/StadiaController.java

This adds StadiaController and its related Command Wrapper.
The significant differences for this controller are that the LeftTrigger and RightTrigger are Buttons rather than Axis, and the addition of several buttons (ellipses, hamburger, google, frame, and stadia) that replace the typical start and back buttons.

[wpilib] Add StadiaController and command wrapper

---

hal/src/main/java/edu/wpi/first/hal/PowerDistributionFaults.java
hal/src/main/java/edu/wpi/first/hal/PowerDistributionStickyFaults.java
hal/src/main/java/edu/wpi/first/hal/REVPHFaults.java
wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibc/src/main/native/cpp/PowerDistribution.cpp
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibc/src/main/native/include/frc/PowerDistribution.h

Method to get breaker fault at a specific channel in PowerDistribution[Sticky]Faults

---

wpilibcExamples/src/main/cpp/examples/UltrasonicPID/include/Robot.h
wpilibcExamples/src/test/cpp/examples/UltrasonicPID/cpp/UltrasonicPIDTest.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/Robot.java
wpilibjExamples/src/test/java/edu/wpi/first/wpilibj/examples/ultrasonicpid/UltrasonicPIDTest.java
wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp
wpimath/src/main/native/include/frc/controller/PIDController.h
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h

[wpimath] Report error on negative PID gains

---

wpilibc/src/main/native/cpp/motorcontrol/PWMSparkFlex.cpp
wpilibc/src/main/native/include/frc/motorcontrol/PWMSparkFlex.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/PWMSparkFlex.java

Uses same timing as PWMSparkMax

Add SparkFlex MotorController

---

.github/workflows/gradle.yml
.github/workflows/lint-format.yml
.github/workflows/pregenerate.yml

https://github.com/actions/upload-artifact#v4---whats-new

[build] Update artifact actions to v4

---

wpilibc/src/main/native/include/frc/util/Color.h
wpilibc/src/test/native/cpp/util/ColorTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/util/ColorTest.java

[wpilib] Fix precision issue in Color round-and-clamp

---

wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

[wpilib] Add access to all 3 ADIS16470 axes

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
cscore/src/main/java/edu/wpi/first/cscore/CvSink.java
cscore/src/main/java/edu/wpi/first/cscore/CvSource.java
cscore/src/main/java/edu/wpi/first/cscore/VideoMode.java
cscore/src/main/java/edu/wpi/first/cscore/VideoSource.java
cscore/src/main/java/edu/wpi/first/cscore/raw/RawSource.java
cscore/src/test/java/edu/wpi/first/cscore/VideoModeTest.java
wpiutil/src/main/java/edu/wpi/first/util/PixelFormat.java

This tracks the RawFrame move.

[wpiutil,cscore] Move VideoMode.PixelFormat to wpiutil

---

wpilibc/src/main/native/include/frc/PS4Controller.h
wpilibc/src/main/native/include/frc/PS5Controller.h
wpilibc/src/main/native/include/frc/XboxController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PS5Controller.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/XboxController.java

Document only first party controllers are guaranteed to have correct mapping

---

MAINTAINERS.md

Update third party artifacts
update installer publishing
Fixes #6106

[Doc] Update maintainers.md (NFC)

---

hal/src/main/java/edu/wpi/first/hal/HALUtil.java
hal/src/main/native/include/hal/HALBase.h
wpilibc/src/main/native/include/frc/RobotController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

[Doc] Add warning about using user button to docs (NFC)

---

sysid/src/main/native/cpp/analysis/FeedforwardAnalysis.cpp

They're usually close, but this is a better metric.

[sysid] Use eigenvector component instead of eigenvalue for fit quality check

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/ExponentialProfile.java

It was already mutable in the C++ ExponentialProfile and TrapezoidProfile in both languages.

[wpimath] Make ExponentialProfile.State mutable

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

There seems to be a latent bug in the fragmentation code that we've not been able to isolate.

[ntcore] Disable WebSocket fragmentation

---

wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

[wpilib] Correct SmartDashboard usage reporting

---

hal/src/generate/Instances.txt
hal/src/generated/main/java/edu/wpi/first/hal/FRCNetComm.java
hal/src/generated/main/native/include/hal/FRCUsageReporting.h
wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java

Is it too late for this?
Will this register properly, even if a team triggers this and not the `SmartDashboard` reporting?

[wpilib] Report LiveWindow-enabled-in-test

---

wpilibc/src/main/native/include/frc/ADXL345_I2C.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_I2C.java

[wpilib] Make ADXL345 default I2C address public

---

fieldImages/src/main/native/resources/edu/wpi/first/fields/2024-crescendo.json

field corners and field size were identical to 2023
Fixes #6177

Fix 2024 field json

---

ntcore/src/main/native/include/networktables/NetworkTable.h

[ntcore] NetworkTable::GetStruct: Add I template param

---

wpilibc/src/main/native/include/frc/sysid/SysIdRoutineLog.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/sysid/SysIdRoutineLog.java

Also add to docs that logging acceleration and current is optional.

[wpilib] Fix SysId log key for acceleration

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/sysid/SysIdRoutine.java
wpilibNewCommands/src/main/native/cpp/frc2/command/sysid/SysIdRoutine.cpp
wpilibc/src/main/native/include/frc/sysid/SysIdRoutineLog.h

Replace hash map with if statements

---

sysid/src/main/native/cpp/analysis/FilteringUtils.cpp
sysid/src/main/native/include/sysid/view/Analyzer.h

this broke in the pre-2024 shuffle

fix test duration slider responsiveness

---

glass/src/lib/native/cpp/other/Field2D.cpp

Also relax field scale check a bit so 2024 field image passes.

[glass] Default to 2024 field image

---

wpilibc/src/main/native/cpp/sysid/SysIdRoutineLog.cpp
wpilibc/src/main/native/include/frc/sysid/SysIdRoutineLog.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/sysid/SysIdRoutineLog.java

Defer creation of state log entry in `SysIdRoutineLog`

---

roborioteamnumbersetter/src/main/native/cpp/App.cpp
roborioteamnumbersetter/src/main/native/cpp/DeploySession.cpp
roborioteamnumbersetter/src/main/native/cpp/DeploySession.h
roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp
roborioteamnumbersetter/src/main/native/cpp/SshSession.h

Add functionality to enable and disable webserver to team number setter

---

ntcore/src/main/native/cpp/LocalStorage.cpp

[ntcore] Map int[] to int64[] for DataLog

---

ntcore/src/main/native/include/networktables/NetworkTable.h

Actually use the I parameter

---

wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h

[wpilibc] ADIS16448, ADIS16470: Initialize member pointers

---

wpinet/src/main/native/cpp/UDPClient.cpp

[build] Fix compilation with musl

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/ExponentialProfile.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrapezoidProfile.java
wpimath/src/main/native/include/frc/trajectory/ExponentialProfile.h
wpimath/src/main/native/include/frc/trajectory/ExponentialProfile.inc
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.h

* Reorder functions so they match between languages
* Copy more complete JavaDocs to C++
* Fix incorrect description for time parameter of TrapezoidProfile.calculate()

[wpimath] Clean up profile classes

---

wpilibc/src/main/native/cpp/DigitalOutput.cpp
wpilibc/src/main/native/cpp/counter/Tachometer.cpp
wpimath/src/test/native/cpp/trajectory/TrajectoryGeneratorTest.cpp

The latter is shorter and is what we use everywhere else.

Replace C++ unit .to<double>() with .value()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/sysid/SysIdRoutine.java
wpilibNewCommands/src/main/native/cpp/frc2/command/sysid/SysIdRoutine.cpp

Reset timer in quasistatic SysIdRoutine test

---

.github/workflows/cmake.yml
.github/workflows/comment-command.yml
.github/workflows/documentation.yml
.github/workflows/gradle.yml
.github/workflows/lint-format.yml
.github/workflows/pregenerate.yml
.github/workflows/upstream-utils.yml

Bumps the versions of Setup Java, Setup Python and Github React Script versions.

[ci] bump setup-python, setup-java and github react script version

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileSubsystem.java
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h

Fix incorrect ordering of parameters in TrapezoidProfileSubsystem

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/ExponentialProfile.java

[wpimath] ExponentialProfile: Return copies of the current and goal states

---

sysid/src/main/native/cpp/analysis/FilteringUtils.cpp

Fixes latency compensation with data from current-limited mechanisms.

Relax peak acceleration search

---

wpiunits/src/main/java/edu/wpi/first/units/Distance.java

[wpiunit] Fix Distance class javadocs to state the correct dimension

---

simulation/halsim_gui/src/main/native/cpp/main.cpp

[sim] GUI: Use shift to enable docking features

---

hal/src/main/native/cpp/jni/HAL.cpp

[hal] Use SIGKILL instead of SIGILL

---

.github/workflows/sanitizers.yml

See: https://github.com/actions/runner/issues/3207

[ci] Work around asan actions bug

---

glass/src/lib/native/cpp/Window.cpp

[glass] Don't limit window name+label to 128 chars

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/LinearSystemId.java

[wpimath] Make more LinearSystemId functions not throw if Kv = 0

---

wpimath/src/main/java/edu/wpi/first/math/Pair.java

adds the toString method to Pair.java

[wpimath] Add Pair.toString()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/EncoderSim.java

Fix EncoderSim.setDistancePerPulse parameter name and comment

---

README.md

I don't see why you should click twice to get to contributing.md

Link straight to contributing in contents.

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java

[wpimath] add Measure<Angle> getter for Rotation2d

---

wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/test/java/edu/wpi/first/units/MeasureTest.java

This implementation uses a tolerance in the same units as the measure it checks.

[wpiunits] Add isNear function implementation

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

This PR adds the onChange Trigger, which is talked about more in detail in the referenced issue. I've implemented the native and java versions, but please keep in mind that I am not experienced in native so some things may be incorrect.

[cmd] Add Trigger.onChange()

---

sysid/src/main/native/cpp/view/Analyzer.cpp
sysid/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h
sysid/src/main/native/include/sysid/view/Analyzer.h
sysid/src/test/native/cpp/analysis/FeedbackAnalysisTest.cpp

[sysid] Remove obsolete WPILib presets, rename CTRE presets

---

upstream_utils/sleipnir_patches/0001-Remove-using-enum-declarations.patch
upstream_utils/sleipnir_patches/0002-Add-implicit-typename.patch
upstream_utils/update_sleipnir.py
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/Expression.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/ExpressionGraph.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/Hessian.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/Jacobian.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/optimization/Constraints.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/optimization/Multistart.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/optimization/OptimizationProblem.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/util/Pool.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/util/SmallVector.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/util/Spy.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/FeasibilityRestoration.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/Filter.hpp

This sped up ArmFeedforward.Calculate() by up to 2x.

[upstream_utils] Upgrade Sleipnir to use a small vector type

---

.github/workflows/gradle-wrapper-validation.yml

Waiting on a stable release of v2 gradle wrapper action

[ci] update gradle wrapper validation action version

---

hal/src/main/java/edu/wpi/first/hal/DriverStationJNI.java
hal/src/main/native/cpp/jni/DriverStationJNI.cpp
wpilibc/src/test/native/cpp/GenericHIDTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/GenericHIDTest.java

Fix integer overflow in java GenericHID.setRumble

---

build.gradle
shared/java/javacommon.gradle

See https://github.com/wpilibsuite/allwpilib/pull/6584#issuecomment-2094583832

[build] change source compatibility to Java 17

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
cameraserver/src/main/native/cpp/cameraserver/CameraServer.cpp
cameraserver/src/main/native/include/cameraserver/CameraServer.h
cameraserver/src/main/native/include/cameraserver/CameraServer.inc
cscore/src/main/java/edu/wpi/first/cscore/AxisCamera.java
cscore/src/main/native/include/cscore_oo.h
cscore/src/main/native/include/cscore_oo.inc
wpilibcExamples/src/main/cpp/examples/HttpCamera/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/httpcamera/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/httpcamera/Robot.java

Deprecate AxisCamera

---

.github/workflows/sanitizers.yml

Its been added to the base image

[ci] Remove workaround for sanitizers

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h

[wpimath] add equals override for ChassisSpeeds

---

glass/src/lib/native/cpp/support/ExtraGuiWidgets.cpp
glass/src/libnt/native/cpp/NetworkTables.cpp

Resolves #6531 
I went through and tested all the topics and it seems to work to me, first time using imgui lol

[glass] Save input after clicking away 

---

buildSrc/build.gradle

Bump Native Utils to 2025.0.0

---

simulation/halsim_ws_core/doc/hardware_ws_api.md
simulation/halsim_ws_core/doc/wpilib-ws.yaml
simulation/halsim_ws_core/src/main/native/cpp/WSProvider_AddressableLED.cpp

Adds documentation for device types and values that are sent by WPILib, but not currently included in the specification.

Update WebSockets API Specification

---

wpilibc/src/main/native/cpp/Compressor.cpp
wpilibc/src/main/native/include/frc/Compressor.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Compressor.java

[wpilib] Add more data to Compressor's Sendable implementation

---

wpinet/src/main/native/cpp/PortForwarder.cpp

[wpinet] Add indication of success/failure to PortForwarder

---

wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java

Include sendable type information in topic metadata

---

.github/workflows/cmake.yml
.github/workflows/sanitizers.yml

Removed steps/packages were used for protobuf/generated files

[ci] Remove unused steps/package installs

---

sysid/src/main/native/cpp/view/Analyzer.cpp
sysid/src/main/native/include/sysid/analysis/FeedbackControllerPreset.h
sysid/src/test/native/cpp/analysis/FeedbackAnalysisTest.cpp

[sysid] Remove CTRE v5 CANCoder preset

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

[sim] Don't send joystick data during auto

---

wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cpp/Preferences.cpp
wpilibc/src/main/native/cpp/livewindow/LiveWindow.cpp
wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardLayout.cpp
wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardTab.cpp
wpilibc/src/main/native/cpp/smartdashboard/MechanismLigament2d.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/livewindow/LiveWindow.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardLayout.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardTab.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/MechanismLigament2d.java

[wpilib] add metadata to all dashboard ".type" entries

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandGenericHID.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandGenericHID.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandGenericHID.h

Resolves https://github.com/wpilibsuite/allwpilib/issues/5193

[commands] Add setRumble and isConnected to CommandGenericHID

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/Odometry.java
wpimath/src/main/native/include/frc/kinematics/Odometry.h

Resolves https://github.com/wpilibsuite/allwpilib/issues/5001

[wpimath] Add reset methods to Odometry

---

simulation/halsim_ws_core/src/main/native/cpp/WSProvider_SimDevice.cpp

Resolves https://github.com/wpilibsuite/allwpilib/issues/6835

[halsim] Fix WS sending 1 and 0 instead of boolean

---

wpimath/src/main/native/include/frc/estimator/PoseEstimator.inc

WheelPositions.h was removed in #6771.

[wpimath] Fix build by removing a bad #include

---

wpilibc/src/generate/main/native/cpp/hid.cpp.jinja
wpilibc/src/generate/main/native/include/frc/hid.h.jinja
wpilibc/src/generated/main/native/cpp/PS4Controller.cpp
wpilibc/src/generated/main/native/cpp/PS5Controller.cpp
wpilibc/src/generated/main/native/cpp/StadiaController.cpp
wpilibc/src/generated/main/native/cpp/XboxController.cpp
wpilibc/src/generated/main/native/include/frc/PS4Controller.h
wpilibc/src/generated/main/native/include/frc/PS5Controller.h
wpilibc/src/generated/main/native/include/frc/StadiaController.h
wpilibc/src/generated/main/native/include/frc/XboxController.h
wpilibj/src/generate/hid.java.jinja
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS5Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/StadiaController.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/XboxController.java

Resolves https://github.com/wpilibsuite/allwpilib/issues/5191

[wpilib] Make HID classes implement Sendable

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagDetector.java
apriltag/src/main/native/cpp/AprilTagDetector.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTagDetector.h

Resolves #4920, continuation of #5896.

[apriltag] Improve AprilTagDetector's default config

---

thirdparty/imgui_suite/glfw/CMakeLists.txt
upstream_utils/glfw.py
upstream_utils/glfw_patches/0001-Suppress-Compiler-Warnings.patch
upstream_utils/glfw_patches/0002-Disable-docs-build-by-default.patch

[upstream_utils] Disable glfw docs build by default

---

thirdparty/imgui_suite/build.gradle

[build] Don't build imgui for Athena

---

ntcoreffi/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/cpp/I2C.cpp
wpilibc/src/main/native/cpp/Tracer.cpp
wpilibc/src/main/native/cpp/Watchdog.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibc/src/main/native/include/frc/Errors.h

See https://github.com/wpilibsuite/allwpilib/issues/6680#issuecomment-2142182644

[wpilibc] Add FRC_ReportWarning

---

.github/workflows/comment-command.yml

It checked out the main branch instead of the PR branch. Now it checks out the PR branch.

[ci] Fix /pregen

---

wpilibc/src/main/native/include/frc/PneumaticsBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsBase.java

[docs] Improve bitmap function documentation in PneumaticsBase (NFC)

---

.github/workflows/comment-command.yml

[ci] Fix comment commands

---

hal/src/main/java/edu/wpi/first/hal/PowerDistributionStickyFaults.java
hal/src/main/java/edu/wpi/first/hal/REVPHStickyFaults.java
hal/src/main/native/athena/REVPDH.cpp
hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/include/hal/PowerDistribution.h
hal/src/main/native/include/hal/REVPH.h
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibc/src/main/native/include/frc/PowerDistribution.h

depends on #6898 to reduce conflicts

[hal, wpilib] Expose sticky hardware and firmware faults in PDH and PH

---

wpiutil/src/main/java/edu/wpi/first/util/CombinedRuntimeLoader.java

With the changes to all the windows dlls for library load path, this functionality is no longer necessary.

Remove SetDllDirectory support in CombinedRuntimeLoader

---

hal/src/main/java/edu/wpi/first/hal/HAL.java
hal/src/main/java/edu/wpi/first/hal/PowerJNI.java
hal/src/main/native/athena/HAL.cpp
hal/src/main/native/athena/Power.cpp
hal/src/main/native/cpp/jni/HAL.cpp
hal/src/main/native/cpp/jni/PowerJNI.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/include/hal/Power.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/sim/Power.cpp
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

- function to reset user rail fault counters
- function to get comms disable count 
- correct docs for user rail count functions

[hal] Expose more FPGA functionality

---

hal/src/main/native/athena/Counter.cpp
hal/src/main/native/athena/FPGAEncoder.cpp

[hal] Counter/Encoder: use std::numeric_limits::infinity

---

roborioteamnumbersetter/src/main/native/cpp/App.cpp

[rtns] fix crash when ssh error occurs during refresh

---

apriltag/src/test/java/edu/wpi/first/apriltag/AprilTagDetectorTest.java

Same as #6928, just for AprilTagDetectorTest instead.

[apriltag] Try loading debug OpenCV if release version fails

---

docs/build.gradle

Fixes search when building with foonathan/memory

Update to Doxygen 1.12.0 

---

cscore/src/main/java/edu/wpi/first/cscore/VideoMode.java
cscore/src/main/java/edu/wpi/first/cscore/VideoSink.java
cscore/src/main/java/edu/wpi/first/cscore/VideoSource.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color8Bit.java

Fixes https://errorprone.info/bugpattern/EqualsGetClass

[cscore, wpilibj] Use pattern matching in equals overrides

---

cameraserver/src/main/java/edu/wpi/first/cameraserver/CameraServer.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogTrigger.java

Fixes https://errorprone.info/bugpattern/ReachabilityFenceUsage

Call reachabilityFence inside finally blocks

---

CMakeLists.txt

It has to be set before `project` otherwise cmake defines it for you

Set CMAKE_BUILD_TYPE correctly

---

wpimath/CMakeLists.txt

Fixes building with multi-config generators

Put protobuf symbol export files in per-config directories

---

wpilibc/src/main/native/cpp/AnalogTrigger.cpp
wpilibc/src/main/native/include/frc/AnalogTrigger.h

[wpilibc] Refactor AnalogTrigger to use shared_ptr

---

glass/src/libnt/native/cpp/NetworkTablesProvider.cpp

Resolves https://github.com/wpilibsuite/allwpilib/issues/7012

[glass] Set immediate flag to listener

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/EpilogueGenerator.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/EpilogueGeneratorTest.java

[epilogue] Log internal debug data to the configured logger instead of networktables

---

.github/workflows/command-robotpy-pr.yml
.github/workflows/documentation.yml
.github/workflows/gradle.yml

This allows forks of allwpilib owned by wpilibsuite to exist without patching the workflows

Check for full repository name in actions

---

xrpVendordep/src/main/java/edu/wpi/first/wpilibj/xrp/XRPGyro.java

These existed in C++ but not Java

[xrp] Cleanup gyro docs (NFC)

---

.github/workflows/aql/wpilib-generic-gradle-cache_unused.aql
.github/workflows/aql/wpilib-mvn-development_unused.aql
.github/workflows/artifactory-nightly-cleanup.yml

This will prevent it from timing out due to lack of commits.

[ci] Move nightly cleanup task to monorepo

---

.github/workflows/upstream-utils.yml
upstream_utils/concurrentqueue.py
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/native/thirdparty/concurrentqueue/include/wpi/concurrentqueue.h
wpiutil/src/test/native/cpp/concurrentqueue/ConcurrentQueueTest.cpp

[upstream_utils] Import ConcurrentQueue to wpiutil

---

xrpVendordep/src/main/java/edu/wpi/first/wpilibj/xrp/XRPGyro.java
xrpVendordep/src/main/native/cpp/xrp/XRPGyro.cpp
xrpVendordep/src/main/native/include/frc/xrp/XRPGyro.h

Resolves https://github.com/wpilibsuite/allwpilib/issues/7031

[xrp] Add GetRotation2d to Gyro

---

buildSrc/build.gradle

After https://github.com/wpilibsuite/native-utils/pull/214

Update  NativeUtils

---

.github/workflows/tools.yml

Build more dependencies added by GradleRIO 2025 Alpha 2

Fix RobotBuilder tools build

---

.github/workflows/cmake.yml
CMakePresets.json

[build] Make CMake presets more consistent

---

.github/workflows/cmake.yml

There wasn't a reason to have this seperate.
Also remove WITH_JAVA=OFF flags which are unnecessary as WITH_JAVA defaults to OFF since https://github.com/wpilibsuite/allwpilib/pull/6975

[ci] Merge Windows into CMake matrix

---

.github/workflows/sentinel-build.yml

Duplicate of gradle.yml without docs, caching, and release configurations
It's set up to run off-peak weekly

Add no-cache build workflow to detect potential false-positive cache hits

---

wpilibc/src/main/native/cpp/LEDPattern.cpp
wpilibc/src/main/native/include/frc/LEDPattern.h
wpilibc/src/test/native/cpp/LEDPatternTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/LEDPattern.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/LEDPatternTest.java

Allow LED pattern gradients to be discontinuous

---

hal/src/main/native/athena/LEDs.cpp

Also make ReadStateFromFile static

Radio LED: Properly close files and improve error messages

---

wpinet/src/main/native/cpp/ParallelTcpConnector.cpp
wpinet/src/main/native/cpp/uv/GetAddrInfo.cpp
wpinet/src/main/native/include/wpinet/uv/GetAddrInfo.h

This is clearer than passing a pointer.

[wpinet] libuv: Change GetAddrInfo hints parameter to optional

---

wpilibc/src/main/native/cpp/Timer.cpp
wpilibc/src/main/native/include/frc/Timer.h
wpilibc/src/test/native/cpp/TimerTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/Timer.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/TimerTest.java

Add Timer.isRunning() method

---

upstream_utils/eigen.py
wpimath/src/main/native/thirdparty/eigen/include/Eigen/Eigenvalues
wpimath/src/main/native/thirdparty/eigen/include/Eigen/Geometry
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/AlignedBox.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/AngleAxis.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/EulerAngles.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Homogeneous.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Hyperplane.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/InternalHeaderCheck.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/OrthoMethods.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/ParametrizedLine.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Quaternion.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Rotation2D.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/RotationBase.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Scaling.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Transform.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Translation.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Umeyama.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/arch/Geometry_SIMD.h

[upstream_utils] Add Eigen geometry module

---

.github/workflows/comment-command.yml
.github/workflows/lint-format.yml

This makes the C identifier list scanner correctly handle single quotes in numeric literals.

[ci] Upgrade to wpiformat 2024.44

---

epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/CompileTestOptions.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/EpilogueGeneratorTest.java

Set source and target java versions for epilogue-processor tests

---

hal/generate_usage_reporting.py
ntcore/generate_topics.py
wpilibNewCommands/generate_hids.py
wpilibc/generate_hids.py
wpilibc/generate_pwm_motor_controllers.py
wpilibj/generate_hids.py
wpilibj/generate_pwm_motor_controllers.py
wpimath/generate_numbers.py
wpimath/generate_quickbuf.py

[build] Use lf in generated files

---

.github/workflows/bazel.yml

We were building HUGE amounts with bazel we were already building otherwise. We've been getting hugely ratelimited because of the amount of CI jobs we are running so this really isn't worth it.

[ci] Remove parts of Bazel CI

---

wpilibc/src/main/native/include/frc/simulation/BatterySim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/BatterySim.java

[simulation] Clamp battery voltage to 0

---

wpiunits/src/generate/main/java/Measure-interface.java.jinja
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Acceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Angle.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Current.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Dimensionless.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Distance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Energy.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Force.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Frequency.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mass.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/MomentOfInertia.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mult.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Per.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Power.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Resistance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Temperature.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Time.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Torque.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Velocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Voltage.java
wpiunits/src/main/java/edu/wpi/first/units/ImmutableMeasure.java
wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/main/java/edu/wpi/first/units/mutable/GenericMutableMeasureImpl.java

[wpiunits] restore and deprecate measure negate

---

wpilibcExamples/src/main/cpp/examples/XRPReference/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/XRPReference/cpp/subsystems/Arm.cpp
wpilibcExamples/src/main/cpp/examples/XRPReference/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/XRPReference/include/subsystems/Arm.h
wpilibcExamples/src/main/cpp/examples/XRPReference/include/subsystems/Drivetrain.h
xrpVendordep/src/main/native/cpp/xrp/XRPGyro.cpp
xrpVendordep/src/main/native/cpp/xrp/XRPServo.cpp
xrpVendordep/src/main/native/include/frc/xrp/XRPGyro.h
xrpVendordep/src/main/native/include/frc/xrp/XRPServo.h

Update C++ XRP Code to use SI Units

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/native/include/frc/controller/PIDController.h

[wpimath] Document default tolerances of PIDController

---

hal/generate_usage_reporting.py
hal/src/generate/UsageReporting.h.in
hal/src/generated/main/native/include/hal/UsageReporting.h

based on wpilibsuite/ni-libraries src/include/FRC_NetworkCommunication/UsageReporting.h

[hal] Generate NI Style UsageReporting header

---

hal/src/generate/Instances.txt
hal/src/generated/main/java/edu/wpi/first/hal/FRCNetComm.java
hal/src/generated/main/native/include/hal/FRCUsageReporting.h
hal/src/generated/main/native/include/hal/UsageReporting.h

[hal] Add usage reporting for Rust

---

hal/src/generate/ResourceType.txt
hal/src/generated/main/java/edu/wpi/first/hal/FRCNetComm.java
hal/src/generated/main/native/include/hal/FRCUsageReporting.h
hal/src/generated/main/native/include/hal/UsageReporting.h
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpimath/src/main/java/edu/wpi/first/math/MathUsageId.java
wpimath/src/main/java/edu/wpi/first/math/controller/BangBangController.java
wpimath/src/main/native/include/frc/controller/BangBangController.h
wpimath/src/main/native/include/wpimath/MathShared.h

[wpimath] Add BangBangController Usage Reporting

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

Closes https://github.com/wpilibsuite/2025Beta/issues/45

Fix ADIS16470 Gyro in Java

---

glass/src/lib/native/include/glass/WindowManager.h
simulation/halsim_gui/src/main/native/cpp/main.cpp

Fixes https://github.com/wpilibsuite/2025Beta/issues/48

[sim] GUI: Don't show Window menu if it has no contents

---

wpimath/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
wpimath/src/main/native/include/frc/controller/proto/SimpleMotorFeedforwardProto.h
wpimath/src/main/native/include/frc/controller/struct/SimpleMotorFeedforwardStruct.h
wpimath/src/test/native/cpp/controller/proto/SimpleMotorFeedforwardProtoTest.cpp
wpimath/src/test/native/cpp/controller/struct/SimpleMotorFeedforwardStructTest.cpp

Allow using non-base types
Allow using angles for serde

[wpimath] Improve C++ SimpleMotorFeedforward unit type support

---

wpiunits/src/generate/main/java/Measure-interface.java.jinja
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Acceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Angle.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Current.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Dimensionless.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Distance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Energy.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Force.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Frequency.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mass.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/MomentOfInertia.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mult.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Per.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Power.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Resistance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Temperature.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Time.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Torque.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Velocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Voltage.java

@deprecated javadoc tags aren't inherited

Fix deprecation javadoc for units negate

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysidroutine/SysIdRoutineBot.java

SysId Example References Shooter Subsystem

---

upstream_utils/protobuf_patches/0012-Suppress-stringop-overflow-warning-false-positives.patch
wpiutil/src/main/native/thirdparty/protobuf/include/google/protobuf/io/coded_stream.h
wpiutil/src/main/native/thirdparty/protobuf/src/unknown_field_set.cpp

[upstream_utils] Suppress protobuf warnings on GCC 12 too

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/EpilogueGenerator.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/EpilogueGeneratorTest.java

The generated Epilogue class will report when it's loaded
Closes #6918

[epilogue] Add usage reporting

---

simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp

[sim] GUI: Update FMS widget when real DS is connected

---

hal/src/generate/ResourceType.txt
hal/src/generated/main/java/edu/wpi/first/hal/FRCNetComm.java
hal/src/generated/main/native/include/hal/FRCUsageReporting.h
hal/src/generated/main/native/include/hal/UsageReporting.h
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java
wpimath/src/main/java/edu/wpi/first/math/MathUsageId.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryUtil.java
wpimath/src/main/native/cpp/trajectory/TrajectoryUtil.cpp
wpimath/src/main/native/include/frc/trajectory/TrajectoryUtil.h
wpimath/src/main/native/include/wpimath/MathShared.h

Add Usage Reporting for Choreo and PathWeaver

---

.github/workflows/gradle.yml
.github/workflows/sentinel-build.yml

Newer JDKs don't support Windows 32 Bit.

Remove 32 Bit Windows support (2027)

---

hal/src/main/native/systemcore/Notifier.cpp

Some of the variables in here were used in the old sim impl, which are not needed here. So remove them. Also adjust comment on function that will no longer be necessary in the future.

[hal] Clean up systemcore notifier impl

---

.github/workflows/gradle.yml
.github/workflows/sentinel-build.yml
buildSrc/build.gradle
shared/config.gradle
shared/opencv.gradle

Also bumps native-utils to 2025.9.0.

[build] Update arm builds to bookworm

---

shared/config.gradle

Remove athena completely from the 2027 build

---

.github/workflows/bazel.yml
.github/workflows/cmake-android.yml
.github/workflows/cmake.yml
.github/workflows/comment-command.yml
.github/workflows/documentation.yml
.github/workflows/gradle.yml
.github/workflows/lint-format.yml
.github/workflows/pregenerate.yml
.github/workflows/sanitizers.yml
.github/workflows/sentinel-build.yml
.github/workflows/tools.yml
.github/workflows/upstream-utils.yml

Blocked on Bookworm compilers.

[ci] Upgrade to Ubuntu 24.04

---

hal/src/main/native/systemcore/PWM.cpp
hal/src/main/native/systemcore/PortsInternal.h
hal/src/main/native/systemcore/SmartIo.cpp
hal/src/main/native/systemcore/SmartIo.h

The way the IO system handles PWM is a bit awkward, so hopefully it can change slightly in the future. But we're able to get most PWM functionality fairly easily.

[hal] Add initial PWM support for systemcore

---

developerRobot/build.gradle
hal/src/main/native/systemcore/HAL.cpp
hal/src/main/native/systemcore/HALInitializer.h
hal/src/main/native/systemcore/SmartIo.cpp

Increase connection timeout, fix ld path, properly initialize smart io.

[hal] Fixes for making PWM drive

---

hal/src/main/native/systemcore/CAN.cpp

Not the most efficient right now, but a minimum enough API to get this working for testing.

[hal] Enable periodic CAN sends

---

build.gradle
cameraserver/multiCameraServer/build.gradle
developerRobot/build.gradle
wpilibjIntegrationTests/build.gradle

Fixes deprecation warnings in build

[build] Update shadow plugin

---

developerRobot/build.gradle

Supersedes https://github.com/wpilibsuite/allwpilib/pull/7534

[developerRobot] Workaround Eclipse annotation processor issues

---

hal/src/main/java/edu/wpi/first/hal/CANAPITypes.java
hal/src/main/native/include/hal/CANAPITypes.h

[hal] Add CAN device type for servo controllers

---

hal/src/main/native/systemcore/SmartIo.cpp
hal/src/main/native/systemcore/SmartIo.h

* Integer microsecond setters and getters
* Per-port subtables

Update SmartIO PWM implementation

---

wpimath/algorithms.md

[wpimath] Fix algorithm link (NFC)

---

ntcore/src/main/native/cpp/net3/WireDecoder3.cpp
ntcore/src/main/native/cpp/net3/WireEncoder3.cpp
simulation/halsim_xrp/src/main/native/cpp/XRP.cpp
wpinet/src/netconsoleServer/native/cpp/main.cpp
wpinet/src/netconsoleTee/native/cpp/main.cpp
wpiutil/src/main/native/cpp/DataLog.cpp
wpiutil/src/main/native/cpp/DataLogReader.cpp

Use std::bit_cast

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Odometry3d.java
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/main/native/include/frc/geometry/Rotation3d.h
wpimath/src/main/native/include/frc/kinematics/Odometry3d.h

The code churn in Java is just making the function order consistent between languages.

[wpimath] Add Rotation3d rotation vector getter

---

thirdparty/imgui_suite/imgui/cpp/imgui_demo.cpp
upstream_utils/imgui.py

This has useful debugging functions; it was left out of the change from the separate thirdparty repo.

[upstream_utils] Add imgui_demo.cpp

---

wpilibc/src/main/native/cpp/simulation/DCMotorSim.cpp
wpilibc/src/main/native/include/frc/simulation/DCMotorSim.h

If this breaks, I'm not going to have time to fix it, so please fix for me.

[wpilibc] DCMotorSim: Add setAngle/setAngularVelocity (parity with Java)

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/LinearSystemId.java
wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h

[wpimath] Fix LinearSystemId return type and docs

---

wpilibc/src/main/native/cpp/I2C.cpp
wpilibc/src/main/native/include/frc/ADXL345_I2C.h
wpilibc/src/main/native/include/frc/I2C.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_I2C.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/I2C.java

Systemcore won't have the I2C issues.

Remove I2C Warnings

---

wpimath/CMakeLists.txt

[build] Fix missing nanopb headers in wpimath

---

developerRobot/build.gradle

ntcore now needs to be after hal.

[build] DeveloperRobot: Fix link order

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/AnnotationProcessor.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java

Fix epilogue breaking when package-info files are present

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.h

Addresses at least documenting #7332.
Improving the wording is an active discussion; This PR is open just to give a chance for feedback and discussion on how to improve it.

[wpimath] Document drift from desaturating discretized chassis speeds (NFC)

---

hal/src/main/java/edu/wpi/first/hal/SPIJNI.java
hal/src/main/native/cpp/jni/SPIJNI.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/SPI.java

The underlying Linux spidev supports up to page size length.

[hal] SPI: Remove byte limit on size

---

.github/workflows/labeler.yml

This means PRs that had labels for certain changes will have those labels removed if those changes are removed.

[ci] Turn on sync labels for the labeler

---

README.md

Add instructions for manual workarounds

[doc] Document that /format is disabled

---

CODE_OF_CONDUCT.md

updating language, keeping the same sentiments and original structure

[docs] Update code of conduct

---

simulation/halsim_xrp/src/main/native/cpp/XRP.cpp
xrpVendordep/src/main/java/edu/wpi/first/wpilibj/xrp/XRPServo.java
xrpVendordep/src/main/native/cpp/xrp/XRPServo.cpp

To enable servo's 3 and 4 usage on the new XRP board.

Updating XRP for new SparkFun RP2350  Board

---

wpimath/src/main/java/edu/wpi/first/math/controller/RamseteController.java
wpimath/src/main/native/include/frc/controller/RamseteController.h

The derivation was moved from the Controls Engineering in FRC book to a separate paper.

[wpimath] Update link to Ramsete controller derivation (NFC)

---

.github/workflows/tools.yml

Also switches to using Artifactory to store the caches.

[ci] Use sccache for RobotPy build

---

wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/native/include/frc/controller/HolonomicDriveController.h

See this issue on github for further details:
https://github.com/wpilibsuite/allwpilib/issues/7937

[wpimath] Fix coordinate frame docs in HolonomicDriveController

---

wpimath/src/main/native/cpp/StateSpaceUtil.cpp
wpimath/src/main/native/include/frc/StateSpaceUtil.h
wpimath/src/test/native/cpp/StateSpaceUtilTest.cpp

closes #7257 
I haven't included the Doxygen just yet, mostly because I wanted to compile something that seemed sensible and put it up in a draft pr. I will be copying that shortly.

[wpimath] Support dynamic matrix sizes in StateSpaceUtil

---

cscore/examples/usbviewer/usbviewer.cpp

Resolves https://github.com/wpilibsuite/allwpilib/issues/7900

[cscore] Fix memory leak in usbviewer example

---

wpimath/src/main/native/include/frc/system/NumericalJacobian.h
wpimath/src/test/native/cpp/system/NumericalJacobianTest.cpp

Add dynamic size support for numerical jacobian computation

---

cscore/src/main/native/objcpp/UsbCameraImplObjc.mm

This PR addresses an issue where certain USB cameras, specifically the ArduCam OV9281, would freeze when attempting to stream on macOS.
The previous logic started the `AVCaptureSession` (`startRunning`) *before* locking the device for configuration (`lockForConfiguration`). While this works for many cameras, it causes the OV9281 to become unresponsive.
Further investigation revealed:
1.  Moving `startRunning` to *after* `unlockForConfiguration` resulted in macOS overriding the custom format and frame rate settings applied within the lock.
2.  The reliable solution, inspired by findings shared in the community (e.g., [Stack Overflow](https://stackoverflow.com/questions/36689578/avfoundation-capturing-video-with-custom-resolution)), is to lock the device, apply the configuration, start the …

[cscore] Resolve macOS camera freeze with specific devices

---

wpilibcExamples/src/main/cpp/snippets/AnalogInput/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/AnalogPotentiometer/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/snippets.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/analogpotentiometer/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/analogpotentiometer/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/snippets.json

Add Analog Potentiometer Snippets

---

wpiunits/src/main/java/edu/wpi/first/units/Units.java

Added important Distance units like Furlongs, Miles, and Hands!

Added parity with C++ units.

---

shared/examplecheck.gradle
wpilibc/src/main/native/include/frc/AnalogAccelerometer.h
wpilibcExamples/src/main/cpp/snippets/ADXLAccelerometers/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/AccelerometerCollision/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/AccelerometerFilter/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/AnalogAccelerometer/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/BuiltInAccelerometer/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/snippets.json
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogAccelerometer.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/accelerometercollision/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/accelerometercollision/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/accelerometerfilter/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/accelerometerfilter/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/adxlaccelerometers/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/adxlaccelerometers/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/analogaccelerometer/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/analogaccelerometer/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/builtinaccelerometer/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/builtinaccelerometer/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/snippets.json

Delete AnalogAccelerometer comments about sensitivity and zero constants that don't exist

Add Accelerometer snippets

---

wpimath/src/test/native/cpp/estimator/AngleStatisticsTest.cpp

[wpimath] Add dynamic size support for angle statistics

---

.github/workflows/tools.yml

[ci] Disable Robotpy build

---

wpilibcExamples/example_projects.bzl
wpilibcExamples/src/main/cpp/snippets/AnalogInput/cpp/Robot.cpp
wpilibjExamples/example_projects.bzl

These were missed in the merge from main.

[examples] Fix up merge from main

---

.github/workflows/documentation.yml

Push 2027 docs to the '2027' path on tags containing '2027'

Deploy 2027 docs on tag

---

wpilibc/src/main/native/cpp/PneumaticHub.cpp
wpilibc/src/main/native/cppcs/RobotBase.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

This will use a much different mechanism in the future

Remove version writes

---

hal/src/main/native/systemcore/CAN.cpp

The canbus names are changing to ensure stable ordering

Use new canbus names for systemcore

---

CODE_OF_CONDUCT.md

- https://www.contributor-covenant.org/version/2/0/code_of_conduct/

Restore original language from original contributor covenant

---

hal/src/main/native/systemcore/IMU.cpp

Related to https://github.com/wpilibsuite/SystemCoreTesting/issues/26

[hal] Fix portrait yaw from onboard IMU

---

.github/workflows/aql/wpilib-mvn-development_unused.aql

We're approaching 1 TB of artifacts in the 2027 dev repo

[ci] Add 2027 development repo to cleanup task

---

ntcore/src/main/native/cpp/InstanceImpl.cpp
ntcore/src/main/native/cpp/InstanceImpl.h
ntcore/src/main/native/cpp/ListenerStorage.cpp
ntcore/src/test/native/cpp/ValueTest.cpp
ntcore/src/test/native/cpp/main.cpp
wpiutil/src/main/native/cpp/Synchronization.cpp

[wpiutil] Synchronization: fix shutdown use-after-free

---

epilogue-runtime/src/main/java/edu/wpi/first/epilogue/EpilogueConfiguration.java
wpilibc/src/main/native/cpp/IterativeRobotBase.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibc/src/main/native/include/frc/IterativeRobotBase.h
wpilibc/src/test/native/cpp/TimedRobotTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/TimedRobotTest.java

[wpilib] Remove robotInit()

---

build.gradle
settings.gradle

Fixes #8099. Gradle enterprise plugin has been replaced by develocity

[build] Update to develocity plugin

---

sysid/publish.gradle
wpical/Info.plist

Fix wpical and sysid icons on macOS

---

upstream_utils/eigen.py
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/CwiseNullaryOp.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/DenseBase.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/GenericPacketMath.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/MatrixBase.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/ProductEvaluators.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/SSE/PacketMath.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/products/Parallelizer.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/util/Macros.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/util/Serializer.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Eigenvalues/RealSchur.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/EulerAngles.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Geometry/Homogeneous.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/SVD/BDCSVD.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/SVD/JacobiSVD.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/SparseCore/SparseVector.h

Upstream slid the tag (again).

[upstream_utils] Recopy Eigen source

---

hal/src/main/java/edu/wpi/first/hal/HALUtil.java
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/sim/HAL.cpp
hal/src/main/native/systemcore/HAL.cpp
wpilibc/src/main/native/cpp/RobotController.cpp
wpilibc/src/main/native/include/frc/RobotController.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

[hal] Remove FPGA functions that won't exist on SC
