wpilibsuite/allwpilib

.github/workflows/gradle.yml

This makes it show up as passed instead of skipped so the result aggregator collapses.

[ci] Run combine but skip all steps

---

romiVendordep/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
xrpVendordep/CMakeLists.txt

The Romi and XRP vendordeps as well as wpilibNewCommands had 2 install commands for the config files, one for WITH_JAVA and another at the end of the file. This removes the extra install command in the WITH_JAVA block, as the other install command is enough.

Remove unnecessary CMake config installs

---

wpilibc/src/main/native/cpp/smartdashboard/SendableBuilderImpl.cpp
wpilibc/src/main/native/include/frc/smartdashboard/SendableBuilderImpl.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SendableBuilderImpl.java
wpiutil/src/main/java/edu/wpi/first/util/sendable/SendableBuilder.java
wpiutil/src/main/native/include/wpi/sendable/SendableBuilder.h

SendableBuilder: Add PublishConst methods

---

wpiutil/src/main/native/cpp/timestamp.cpp

Windows 8 added GetSystemTimePreciseAsFileTime().

[wpiutil] Get more precise system time on Windows

---

wpiutil/src/main/native/include/wpi/deprecated.h

robotpy-build doesn't set `__GNUC__` when preprocessing files, and probably shouldn't?

[wpiutil] Set WPI_{UN}IGNORE_DEPRECATED to empty when all else fails

---

ntcore/src/main/native/cpp/LocalStorage.cpp

The duplicates check for lastValue prevents the SetDefault from notifying locally, which breaks the sim gui NT display.

[ntcore] Fix notification of SetDefaultEntryValue

---

ntcore/src/main/native/cpp/net/NetworkOutgoingQueue.h

std::remove_if() is destructive--it can assume the removed elements are not used, but NetworkOutgoingQueue needs them to stay intact to be moved to a different queue. Use std::stable_partition() instead.
Fixes #5734.

[ntcore] Fix moving outgoing queue to new period

---

ntcore/doc/networktables4.adoc
ntcore/src/main/native/cpp/NetworkServer.cpp

This is useful for aliveness checking by clients that can't send WebSocket PING messages.

[ntcore] Add RTT-only subprotocol

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SchedulingRecursionTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulingRecursionTest.cpp

Fixes #5467.
`end` is now called first along with interrupt actions on both languages. Sets are used to defer cancels, ensuring infinite loops aren't possible.

Make command scheduling order consistent

---

ntcore/src/main/native/cpp/Value.cpp

It did not correctly check size prior to checking size=0.

[ntcore] Fix string array value comparison

---

wpilibcExamples/src/main/cpp/examples/SwerveBot/cpp/SwerveModule.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/SwerveModule.cpp
wpilibcExamples/src/main/cpp/examples/SwerveDrivePoseEstimator/cpp/SwerveModule.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/SwerveModule.java

Completes issue https://github.com/wpilibsuite/allwpilib/issues/5749.

[examples] Make swerve examples multiply desired module speeds by cosine of heading error

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Transform2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform3d.java
wpimath/src/main/native/cpp/geometry/Transform3d.cpp
wpimath/src/main/native/include/frc/geometry/Transform2d.h
wpimath/src/main/native/include/frc/geometry/Transform2d.inc
wpimath/src/main/native/include/frc/geometry/Transform3d.h

Adds overloads for Transform2d() constructor to accept x, y, and heading and for Transform3d() to accept x, y, z and rotation as a shorthand for the normal constructors.
Completes issue #5748.

[wpimath] Add overloads for Transform2d and Transform3d

---

CMakeLists.txt
apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cscore/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
romiVendordep/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
wpilibj/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiutil/CMakeLists.txt
xrpVendordep/CMakeLists.txt

This reverts commit 1c724884cadc00899806617f60622d4bf5e19ab8.
This commit broke local builds on the second run of cmake configure with the following error:
```
[build] hal/FRCNetComm.java:10: error: duplicate class: edu.wpi.first.hal.FRCNetComm
[build] public class FRCNetComm {
[build]        ^
[build] 1 error
```

Revert "[build] Add CMake option to build Java source jars (#5756)"

---

wpiutil/src/main/native/include/wpi/ct_string.h

This avoids a conflict with json.

[wpiutil] ct_string: Use inline namespace for literals

---

README-CMAKE.md

[docs] Add jinja2 to CMake prerequisites

---

wpimath/src/main/java/edu/wpi/first/math/Vector.java
wpimath/src/test/java/edu/wpi/first/math/VectorTest.java

[wpimath] Make Vector-Vector binary operators return Vector

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h

A command explicitly doing nothing and reserving a subsystem is a valid use, imo. It doesn't necessarily need to be inside a composition.

Add requirements parameter to Commands.idle()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

#3534 changed it from returning !isReal() to checking against a numeric value, but #3565 (merged earlier) had changed the value to an enum.

[wpilibj] Fix RobotBase.isSimulation()

---

hal/src/main/native/athena/mockdata/RoboRioData.cpp

Sometimes the compiler would throw an error about this, but it's inconsistent about that. Regardless, none of the other macros have a semicolon at the end.

Remove extra semicolon in RoboRioData

---

wpinet/src/main/native/cpp/uv/Stream.cpp

In the TryWrite case, EAGAIN is a normal return value, but we want to just map it to 0 rather than handling it as an error.

[wpinet] uv::Stream::TryWrite(): Return 0 on EAGAIN

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/NetworkOutgoingQueue.h
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

The object was being destroyed in the middle of a send due to the error handling path closing the connection. Instead, defer to the next loop cycle using a one-shot timer.
Properly handle error return values from Send functions.
Fix UB in accessing one past the end of a vector.

[ntcore] Fix crash on disconnect

---

wpilibc/src/main/native/cpp/Counter.cpp
wpilibc/src/main/native/include/frc/Counter.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Counter.java

default distance per pulse in java was 0 instead of 1
C++ didn't have that functionality at all.

[wpilib] Counter: fix default distance per pulse, give c++ parity

---

wpiutil/src/main/java/edu/wpi/first/util/struct/StructBuffer.java

`readArray` throws an `ArrayStoreException` because the class of the struct (`Struct<T>`) doesn't match the decoded type (`T`). Using `getTypeClass()` instead of `getClass()` fixes the issue.

[wpiutil] Fix Java struct array unpacking

---

.github/workflows/cmake.yml
vcpkg.json

- Add builtin registry baseline (fixes building locally with msvc builtin vcpkg)
- Add protobuf as an explicit dependency (previously was installed as a dependency of opencv)
- In windows CI, checkout repository before running vcpkg (silences warning that vcpkg.json was not found)

Windows CMake/vcpkg fixes

---

upstream_utils/llvm_patches/0032-Fix-compilation-of-MathExtras.h-on-Windows-with-sdl.patch
upstream_utils/update_llvm.py
wpiutil/src/main/native/thirdparty/llvm/include/wpi/MathExtras.h

On Windows, compilation fails with [error C4146](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4146?view=msvc-170) on the MathExtras.h header when using the /sdl compiler flag. Since unary minus performs two's complement, it is equivalent to performing ones' complement (bitwise NOT) on the unsigned number and adding one.
This fix was copied from the LLVM main branch: https://github.com/llvm/llvm-project/pull/68978

Fix compilation of MathExtras.h on Windows with /sdl

---

README.md
shared/cppJavaDesktopTestTask.gradle
shared/javacpp/setupBuild.gradle
shared/jni/setupBuild.gradle

Adds a `testDesktop` task that tests both java and c++ for desktop

[build] Add combined test meta-task

---

ntcore/src/main/native/cpp/LocalStorage.cpp

Only check the raw type value, as the type string may have been set by the user (particularly common for raw values).

[ntcore] Don't check type string on publishing an entry

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/DeferredCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Subsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/DeferredCommand.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/Subsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h
wpilibNewCommands/src/main/native/include/frc2/command/DeferredCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/DeferredCommandTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/DeferredCommandTest.cpp

Closes #5150
Allows commands to be constructed at runtime without proxying.
Requirements must be specified explicitly, even if there are no requirements. Java uses a `Set<Subsystem>`. Not sure how to accomplish this in c++. The reason for this is that requirements must be known before runtime (and therefore before the contained command is constructed, and users will likely forget to include the proper requirements. 
The other potential tripping point is that the supplier *must* create a new command each time it's called, because this is considered a command composition, so we don't want the supplied commands being used for other compositions or being scheduled directly.
Still needs c++ tests, will finish those up this weekend.

[cmd] Add DeferredCommand

---

wpiutil/src/main/native/cpp/protobuf/ProtobufMessageDatabase.cpp

The message destructor appears to call something on the descriptor.

[wpiutil] ProtobufMessageDatabase: Clear messages first

---

wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java

[wpiutil] DataLog.addSchema(): Don't add into a set view

---

wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanTypeFilter.java

It seems like making it package-private was accidental, and it prevents users from writing custom Kalman filter classes that can use the KF latency compensator.

[wpimath] Make KalmanTypeFilter interface public

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java

[java cmd] Fix CommandXboxController.leftTrigger() parameter order

---

wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooserTest.java

Using unique NT keys for each test seems to resolve the failure on Linux. Changed Java as well, for completeness.
Failed test log, for future reference
```
[----------] 4 tests from SendableChooserTests/SendableChooserTest
[ RUN      ] SendableChooserTests/SendableChooserTest.ReturnsSelected/0
/work/wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp:32: Failure
Expected equality of these values:
GetParam()
Which is: 0
chooser.GetSelected()
Which is: 3
[  FAILED  ] SendableChooserTests/SendableChooserTest.ReturnsSelected/0, where GetParam() = 0 (0 ms)
[ RUN      ] SendableChooserTests/SendableChooserTest.ReturnsSelected/1
/work/wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp:32: Failure
Expected equality of these values:
GetParam()
Which is: 1 …
```

[wpilib] Fix SendableChooser test

---

styleguide/checkstyle-suppressions.xml

Currently on main, the checkstyle rules for quickbuf and wpimath don't match on windows filepaths. This PR removes the file separator from the pattern, since they can be captured by wildcards without losing specificity.

Fix Checkstyle rules on Windows

---

simulation/halsim_ds_socket/src/main/native/cpp/DSCommPacket.cpp
simulation/halsim_ds_socket/src/main/native/cpp/main.cpp

If the DS extension is loaded, the robot program will continue to be enabled if the DS disconnects or closes. This adds timers to auto disable the program when it's been more than 100ms since the last DS packet.

[simulation] Autodisable the robot program if the DS is not connected

---

wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/cpp/WebSocketSerializer.h
wpinet/src/main/native/include/wpinet/WebSocket.h
wpinet/src/test/native/cpp/WebSocketIntegrationTest.cpp
wpinet/src/test/native/cpp/WebSocketSerializerTest.cpp

On Windows, TryWrite will always return 0 if there is a Write in progress. The previous behavior for SendFrames and SendControl just used a normal Write, which caused issues with code that combined these with TrySendFrames. Instead, have SendFrames and SendControl also use TryWrite under the hood if possible, and create write requests if not. The implementation preserves the priority of SendControl against an existing write request with multiple frames.
Fixes #5817 (the root cause for that was it was not sending the subscription frame due to the WS ping SendControl always occurring immediately before the TrySendFrames).

[wpinet] WebSocket: Fix write behavior

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
upstream_utils/llvm_patches/0033-raw_ostream-Add-SetNumBytesInBuffer.patch
upstream_utils/update_llvm.py
wpiutil/src/main/native/thirdparty/llvm/include/wpi/raw_ostream.h

The previous fix didn't handle all cases correctly. Instead, add a new function to raw_ostream (SetNumBytesInBuffer) to allow always using the full buffer size, and revamp write_impl to more cleanly handle all cases.

[ntcore] Fix write_impl

---

CMakeLists.txt
README-CMAKE.md
apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cscore/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
romiVendordep/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
wpilibj/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiutil/CMakeLists.txt
xrpVendordep/CMakeLists.txt

I built it twice this time and it doesn't complain about a duplicate class. The fix had nothing to do with the source jars, but with the HAL jar itself. When I noticed the error came from building the compiled jar, I confirmed it when building the HAL source jar target worked perfectly fine, but building the actual compiled HAL jar failed. The fix was to include `FRCNetComm.java` directly in `add_jar` instead of globbing it with the other Java files. This is actually how wpilibj includes its version file, and explains why I never saw wpilibj fail in my testing.
Some additional fixes are included to fix things that I missed the first time.
Also, is there some sort of styleguide/formatter for CMakeLists? They're a mix of 2/4 spaces, and spacing seems inconsistent in other areas.

[build] Add CMake option to build Java sources jars

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SelectCommand.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/RobotDisabledCommandTest.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/SelectCommandTest.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/selectcommand/RobotContainer.java

This allows users to use any type of map and selector without needing to explicitly match `Map<Object, Command>`

[java cmd] Make SelectCommand generic

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h

[cmd] Add Java and c++ finallyDo with zero-arg lambda

---

wpimath/src/main/java/edu/wpi/first/math/interpolation/InterpolatingDoubleTreeMap.java

InterpolatingDoubleTreeMap has a private constructor, which appears to be an oversight.

[wpimath] Expose InterpolatingDoubleTreeMap constructor

---

wpimath/CMakeLists.txt

For some reason, cmake does not create `PROTOC_OUT_DIR` when building using Make, so protoc can't generate code. This works around that by creating the appropriate folder.
fixes #5803

Fix protobuf generation when building with make

---

ntcoreffi/src/main/native/cpp/DataLogManager.cpp
ntcoreffi/src/main/native/include/DataLogManager.h
ntcoreffi/src/main/native/symbols.txt
wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/include/frc/DataLogManager.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogJNI.java
wpiutil/src/main/native/cpp/DataLog.cpp
wpiutil/src/main/native/cpp/jni/DataLogJNI.cpp
wpiutil/src/main/native/include/wpi/DataLog.h

Restarting a stopped log results in creating a new log file with fresh copies of the same start records and schema data records.
Also check to see if the file has been deleted or if the log file exceeds 1.8 GB, and start a new one.
Fixes #4625.

[wpiutil] Add DataLog and DataLogManager Stop()

---

docs/build.gradle

They take up a significant portion of the generated output (protobuf ~55MB, eigen ~119MB)

[docs] Exclude eigen and protobuf from doxygen

---

apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTagFieldLayout.h

This adds a small function to return a list of AprilTag objects to the C++ version of the AprilTag library. This already exists in Java.

Adds GetTags to C++ version of AprilTagFieldLayout

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileCommand.java
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibcExamples/src/main/cpp/examples/ElevatorTrapezoidProfile/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceArm/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceElevator/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatortrapezoidprofile/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacearm/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespaceelevator/Robot.java
wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrapezoidProfile.java
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.h
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.inc
wpimath/src/test/java/edu/wpi/first/math/trajectory/TrapezoidProfileTest.java
wpimath/src/test/native/cpp/trajectory/TrapezoidProfileTest.cpp

ProfiledPIDController and ExponentialProfile use current, then goal. This isn't a breaking change because this overload of calculate() is new for 2024.

[wpimath] Reorder TrapezoidProfile.calculate() arguments

---

ntcore/src/main/native/cpp/LocalStorage.cpp

In general, we shouldn't need or want to log `$pub$` and `$sub$` values and the like, only if specifically directed to log `$` prefixes.  This matches the behavior of subscriptions in general.

[ntcore] Only datalog meta-topics if specifically requested

---

hal/src/main/native/athena/FRCDriverStation.cpp

Netcomm writes garbage data before the DS connects. Make sure this doesn't make it up to the user.
Closes #5870

Fix garbage data for match info before DS connection

---

apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
cameraserver/multiCameraServer/src/main/native/cpp/main.cpp
glass/src/lib/native/cpp/Context.cpp
sysid/src/main/native/cpp/analysis/AnalysisManager.cpp
sysid/src/main/native/cpp/analysis/JSONConverter.cpp
wpimath/src/main/native/cpp/trajectory/TrajectoryUtil.cpp
wpiutil/src/main/native/thirdparty/llvm/include/wpi/MemoryBuffer.h

Add GetCharBuffer() to MemoryBuffer classes to make this easy.
Fixes #5876.

Use char instead of uint8_t for json::parse

---

wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/subsystems/SwerveModule.cpp

Required by newer versions of clang.

[wpilibcExamples] Match array parameter bounds

---

crossConnIntegrationTests/src/main/native/include/LifetimeWrappers.h
wpimath/src/test/native/cpp/StateSpaceUtilTest.cpp
wpimath/src/test/native/cpp/estimator/ExtendedKalmanFilterTest.cpp
wpimath/src/test/native/cpp/estimator/UnscentedKalmanFilterTest.cpp
wpimath/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp
wpimath/src/test/native/cpp/spline/QuinticHermiteSplineTest.cpp
wpiutil/src/test/native/cpp/ArrayTest.cpp

This clarifies intent. I didn't do this for thirdparty libraries or structured binding variables.

Replace static_cast<void>() with [[maybe_unused]] attribute

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagDetection.java
apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagDetector.java
apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
apriltag/src/main/native/include/frc/apriltag/AprilTagDetection.h
apriltag/src/main/native/include/frc/apriltag/AprilTagDetector.h

Mostly docs for JNI. Also fixes documentation for a `bitsCorrected` parameter. Addresses part of #5808 and #4920.

Improve AprilTag docs

---

ntcoreffi/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/cpp/DataLogManager.cpp

This ensures the thread has finished prior to returning from Stop().

[wpilibc,ntcoreffi] DataLogManager: join on Stop() call

---

.github/workflows/gradle.yml
buildSrc/build.gradle

Depends on https://github.com/wpilibsuite/native-utils/pull/174.

[build] Bump macOS deployment target to 12

---

wpiutil/src/main/native/cpp/timestamp.cpp

Note this doesn't use a full mutex, so there is still a shutdown race.

[wpiutil] timestamp: Fix startup race on Rio

---

wpilibc/src/main/native/cpp/simulation/DifferentialDrivetrainSim.cpp
wpilibc/src/test/native/cpp/simulation/DifferentialDrivetrainSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DifferentialDrivetrainSimTest.java

RK4 causes the same numerical stability issues the arm sim had with high gear ratios.

[wpilib] Use RKDP in DifferentialDrivetrainSim to fix numerical instability

---

ntcore/src/main/native/cpp/ntcore_meta.cpp

It's not uncommon to have more than 1000 publishers or subscribers on a particular client, so bump that limit to 10000.

[ntcore] Increase client meta-topic decoding limit

---

upstream_utils/fmt_patches/0001-Don-t-throw-on-write-failure.patch
upstream_utils/fmt_patches/0002-Suppress-warnings-we-can-t-fix.patch
upstream_utils/fmt_patches/0003-Remove-this-from-decltype.patch
upstream_utils/update_fmt.py
wpiutil/src/main/native/thirdparty/fmtlib/include/fmt/core.h

Using `this->` in decltype doesn't work in the latest MSVC.

[upstream_utils] Fix fmt compilation errors on Windows

---

ntcore/src/main/native/include/networktables/NetworkTableInstance.inc

Clang warns that the "this" capture is not required, even though a member function is being called.

[ntcore] NetworkTableInstance: Suppress unused lambda capture warning

---

ntcore/src/main/native/include/networktables/ProtobufTopic.h
ntcore/src/main/native/include/networktables/StructArrayTopic.h
ntcore/src/main/native/include/networktables/StructTopic.h

Some older compilers don't have atomic_flag::test().

[ntcore] Protobuf/Struct: Use atomic_bool instead of atomic_flag

---

shared/java/javacommon.gradle
wpilibjExamples/build.gradle

This fixes the warning message about automatic loading of test framework imlementation dependencies:
```
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.4/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
```
This *does not* fix the issue for wpilibjExamples- while I did update it for consistency, I believe the way the tests are created necessitates a different fix.
Applying the `junit-jupiter` dependency pulls in `junit-bom` to resolve …

Declare platform launcher dependency explicitly

---

CMakeLists.txt
apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cscore/CMakeLists.txt
glass/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
romiVendordep/CMakeLists.txt
wpigui/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
wpilibc/CMakeLists.txt
wpilibj/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiunits/CMakeLists.txt
wpiutil/CMakeLists.txt
xrpVendordep/CMakeLists.txt

It's been broken for a while, and probably isn't useful, since people can use CMake to pull in all the files.
Also removes some commented out flat install code.

[build] Remove CMake flat install option 

---

apriltag/build.gradle
apriltag/src/main/java/edu/wpi/first/apriltag/AprilTag.java
apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
apriltag/src/main/native/cpp/AprilTag.cpp
apriltag/src/main/native/cpp/jni/AprilTagJNI.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTag.h
cscore/src/main/java/edu/wpi/first/cscore/CameraServerJNI.java
cscore/src/main/java/edu/wpi/first/cscore/raw/RawSink.java
cscore/src/main/java/edu/wpi/first/cscore/raw/RawSource.java
cscore/src/main/native/cpp/RawSinkImpl.cpp
cscore/src/main/native/cpp/RawSinkImpl.h
cscore/src/main/native/cpp/RawSourceImpl.cpp
cscore/src/main/native/cpp/RawSourceImpl.h
cscore/src/main/native/cpp/cscore_c.cpp
cscore/src/main/native/cpp/jni/CameraServerJNI.cpp
cscore/src/main/native/include/cscore_c.h
cscore/src/main/native/include/cscore_cpp.h
cscore/src/main/native/include/cscore_raw.h
cscore/src/main/native/include/cscore_raw_cv.h
wpiutil/src/main/java/edu/wpi/first/util/RawFrame.java
wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/RawFrame.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/include/wpi/RawFrame.h

Per discussion on the FRC discord, users should be able to easily generate an OpenCV Mat of the two AprilTag families used in FRC. I tested it on my PC and it generated the images properly in Java and C++. 
I am unfamiliar with how people usually use OpenCV Mats in Java, but I think you would have to call .release() on the mat returned from the methods.
Not sure the best way to add a test for this...

Move RawFrame to wpiutil and add function to generate RawFrames of AprilTags

---

wpimath/src/main/java/edu/wpi/first/math/estimator/KalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SteadyStateKalmanFilter.java
wpimath/src/main/native/cpp/estimator/SteadyStateKalmanFilter.cpp
wpimath/src/main/native/include/frc/estimator/KalmanFilter.inc
wpimath/src/main/native/include/frc/estimator/SteadyStateKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/SteadyStateKalmanFilter.inc

[wpimath] Make KalmanFilter variant for asymmetric updates

---

wpiunits/src/main/java/edu/wpi/first/units/Angle.java
wpiunits/src/main/java/edu/wpi/first/units/BaseUnits.java
wpiunits/src/main/java/edu/wpi/first/units/Current.java
wpiunits/src/main/java/edu/wpi/first/units/Distance.java
wpiunits/src/main/java/edu/wpi/first/units/Energy.java
wpiunits/src/main/java/edu/wpi/first/units/ImmutableMeasure.java
wpiunits/src/main/java/edu/wpi/first/units/Mass.java
wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/main/java/edu/wpi/first/units/Mult.java
wpiunits/src/main/java/edu/wpi/first/units/MutableMeasure.java
wpiunits/src/main/java/edu/wpi/first/units/Per.java
wpiunits/src/main/java/edu/wpi/first/units/Power.java
wpiunits/src/main/java/edu/wpi/first/units/Temperature.java
wpiunits/src/main/java/edu/wpi/first/units/Time.java
wpiunits/src/main/java/edu/wpi/first/units/Unit.java
wpiunits/src/main/java/edu/wpi/first/units/Units.java
wpiunits/src/main/java/edu/wpi/first/units/Velocity.java
wpiunits/src/main/java/edu/wpi/first/units/Voltage.java

This is to add missing javadocs to the units library. I used consistent terminology for *dimension*, *unit*, and *measure*. I also added these definitions to frc-docs in a separate PR https://github.com/wpilibsuite/frc-docs/pull/2397. The intention is to make the units library easier to understand using Intellisense.

[wpiunits] Documentation improvements

---

wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h

[wpimath] Add SysId doc links to LinearSystemId in C++ (NFC)

---

wpilibc/src/main/native/include/frc/DriverStation.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java

kInvalid was replaced with an optional.

[wpilib] Update getAlliance() docs (NFC)

---

wpiutil/wpiutil-config.cmake.in

For one reason or another, some Linux distributions like Ubuntu/Debian seem to require the `Protobuf` dependency to be capitalized. Not sure why. This still works on other distributions, including Arch Linux, but this will need to be tested on Windows.

[build] cmake: fix protobuf dependency finding for certain distributions

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/java/edu/wpi/first/math/filter/MedianFilter.java
wpiutil/src/main/java/edu/wpi/first/util/DoubleCircularBuffer.java
wpiutil/src/main/native/include/wpi/circular_buffer.h
wpiutil/src/test/java/edu/wpi/first/util/DoubleCircularBufferTest.java

The original is now called DoubleCircularBuffer.

[wpimath] Add generic circular buffer class to Java

---

wpimath/src/main/java/edu/wpi/first/math/optimization/SimulatedAnnealing.java
wpimath/src/main/java/edu/wpi/first/math/path/TravelingSalesman.java
wpimath/src/main/native/include/frc/optimization/SimulatedAnnealing.h
wpimath/src/main/native/include/frc/path/TravelingSalesman.h
wpimath/src/test/java/edu/wpi/first/math/optimization/SimulatedAnnealingTest.java
wpimath/src/test/java/edu/wpi/first/math/path/TravelingSalesmanTest.java
wpimath/src/test/native/cpp/optimization/SimulatedAnnealingTest.cpp
wpimath/src/test/native/cpp/path/TravelingSalesmanTest.cpp

Co-authored-by: Ashray._.g <ashray.gupta@gmail.com>

[wpimath] Add simulated annealing

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Subsystem.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SubsystemBase.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/Subsystem.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/SubsystemBase.h
wpiutil/src/main/native/include/wpi/Demangle.h

Continuation from #4199 
Fixes #4191
My only concern is calling typeid in C++ may be expensive (as mentioned in #4199). Ideally, Subsystem handles generating the name, rather than CommandScheduler caching it. The problem is that Subsystem can't access the subclass' type info at construction time. Any ideas would be helpful

[cmd] Add GetName to Subsystem, use in Scheduler tracer epochs

---

wpimath/src/main/native/include/frc/interpolation/TimeInterpolatableBuffer.h
wpimath/src/test/java/edu/wpi/first/math/interpolation/TimeInterpolatableBufferTest.java
wpimath/src/test/native/cpp/interpolation/TimeInterpolatableBufferTest.cpp

Don't decrement buffer iterator if it's at the beginning of the container.

[wpimath] Fix TimeInterpolatableBuffer crash

---

wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/test/java/edu/wpi/first/units/MeasureTest.java

As opposed to returning Measure<Per<U, Time>>
Now matches the overload on Unit

[wpiunits] Overload Measure.per(Time) to return Measure<Velocity>

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.h

- correctly handle the first subscription being a send all
- don't restart outgoing timer if period didn't change
Fixes #5998.

[ntcore] Update transmit period on topic add/remove

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Command.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h

[cmd] CommandCompositionError: Include stacktrace of original composition

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java

[wpilibj] use final for joystick get axis methods

---

wpiutil/src/main/native/cpp/timestamp.cpp

There was also an issue where the clock zero offset would be incorrect due to the system time updating. This solves that issue for the rio

Zero out roborio system timestamp

---

wpilibc/src/main/native/include/frc/PS5Controller.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/PS5Controller.java

It's likely the original mappings were done from Linux sim, which had a kernel bug in the past where the mappings were not right. This matches the official DS with an official PS5 Controller. 
Closes https://github.com/wpilibsuite/2024Beta/issues/43

Fix PS5 Controller mappings

---

wpilibcExamples/src/main/cpp/examples/ArmBot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/ArmBotOffboard/include/Constants.h
wpilibcExamples/src/main/cpp/examples/ArmSimulation/include/Constants.h
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/Constants.h
wpilibcExamples/src/main/cpp/examples/ElevatorExponentialSimulation/include/Constants.h
wpilibcExamples/src/main/cpp/examples/ElevatorSimulation/include/Constants.h
wpilibcExamples/src/main/cpp/examples/Frisbeebot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/GyroDriveCommands/include/Constants.h
wpilibcExamples/src/main/cpp/examples/HatchbotInlined/include/Constants.h
wpilibcExamples/src/main/cpp/examples/HatchbotTraditional/include/Constants.h
wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RamseteCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RomiReference/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SelectCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/include/Constants.h
wpilibcExamples/src/main/cpp/examples/UnitTest/include/Constants.h
wpilibcExamples/src/main/cpp/examples/XRPReference/include/Constants.h
wpilibcExamples/src/main/cpp/templates/commandbased/include/Constants.h

Resolves #6047 
Note:
No adjustments made to sim examples because they used static specifier. This will ensure there is a new symbol of the same value push on the stack for every unit where the Constants.h file is included, however, I do not want to mess with those files because I don't know enough about sim. Let me know if those should be switched to 'inline constexpr' from 'static constexpr'

[wpilibcExamples] Add "inline" specifier to constants.h constants

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelSpeeds.java
wpimath/src/main/native/cpp/kinematics/MecanumDriveWheelSpeeds.cpp
wpimath/src/test/java/edu/wpi/first/math/kinematics/MecanumDriveKinematicsTest.java
wpimath/src/test/native/cpp/kinematics/MecanumDriveKinematicsTest.cpp

It didn't account for negative speeds when calculating the real max speed, so now it does.

Fix MecanumDriveWheelSpeeds desaturate()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SubsystemBase.java
wpilibNewCommands/src/main/native/cpp/frc2/command/SubsystemBase.cpp
wpilibNewCommands/src/main/native/include/frc2/command/SubsystemBase.h

This is important for correct reporting of subsystem names in any logging utilities that are initialized at initial construction-time.

[commands] Allow setting of SubsystemBase name in ctor

---

cscore/src/main/native/cpp/jni/CameraServerJNI.cpp

Closes https://github.com/wpilibsuite/2024Beta/issues/51
Broken in https://github.com/wpilibsuite/allwpilib/pull/5923, the class load was removed instead of changed to the new class.

Fix RawFrame class not being loaded in JNI

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTag.java
apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
apriltag/src/main/native/cpp/jni/AprilTagJNI.cpp

This fixes #6062 
However, there is an issue that I can't figure out. 
I think there is UB somewhere in this code. For some reason, sometimes when running, the image is corrupted at the top row only.
These images were generated from the same code, different runs.
Any help is appreciated!

Fix for generating apriltags in java

---

CMakeLists.txt
README-CMAKE.md
cmake/modules/CompileWarnings.cmake

-Werror always being enabled is relatively inconvenient, as it frequently requires patching to get it to build (like in https://aur.archlinux.org/packages/wpimath)

[build] Add NO_WERROR option to CMake to disable -Werror

---

glass/src/lib/native/cpp/Context.cpp

Fixes 6036.
Tested on Ubuntu 22.04, using cmake and gradle
The change is simply to move the WorkspaceResetImpl() before LoadWindowStorageImpl() instead of after.
It looks to me like this has always been broken, which doesn't make any sense to me, maybe somebody more familiar can help figure it out.  Regardless of the former scope of the issue, it seems good now, which is what I wanted.

[glass] Fix order of loading window settings

---

wpiutil/src/main/native/cpp/DataLog.cpp
wpiutil/src/main/native/include/wpi/DataLog.h
wpiutil/src/test/native/cpp/DataLogTest.cpp

Previously the thread could end without the file being written.
Fixes #6085.

[wpiutil] DataLog: Ensure file is written on shutdown

---

wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandHelper.h
wpilibNewCommands/src/main/native/include/frc2/command/SelectCommand.h

It was completely replaced with `ToPtr()`.

[cpp cmd] Deprecate TransferOwnership()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroup.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/MultiCompositionTestBase.java
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroupTest.java

Fixes #6080
Also makes `ParallelDeadlineGroup` error when the deadline appears in the other commands (with corresponding docs changes) and fixes an error message.
I looked into C++, but it doesn't have the exact same issue since registering commands as composed is done on the particular command, not on a map in the scheduler. I'm also not sure how the ownership semantics affect this issue.

[cmd] Improve error message when composing commands twice in same composition

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTag.java
apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
apriltag/src/main/native/cpp/AprilTag.cpp
apriltag/src/main/native/cpp/jni/AprilTagJNI.cpp
apriltag/src/main/native/include/frc/apriltag/AprilTag.h
apriltag/src/test/java/edu/wpi/first/apriltag/AprilTagGenerationTest.java
cscore/src/main/java/edu/wpi/first/cscore/CameraServerJNI.java
cscore/src/main/java/edu/wpi/first/cscore/raw/RawSink.java
cscore/src/main/java/edu/wpi/first/cscore/raw/RawSource.java
cscore/src/main/native/cpp/Image.h
cscore/src/main/native/cpp/RawSinkImpl.cpp
cscore/src/main/native/cpp/RawSourceImpl.cpp
cscore/src/main/native/cpp/jni/CameraServerJNI.cpp
wpiutil/src/main/java/edu/wpi/first/util/RawFrame.java
wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/RawFrame.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/include/wpi/RawFrame.h

RawFrame was broken in multiple ways, e.g. use-after-free in AprilTag.  Fix up API and use cases.

[wpiutil,cscore,apriltag] Fix RawFrame

---

sysid/src/main/native/cpp/analysis/AnalysisManager.cpp
sysid/src/main/native/cpp/analysis/FeedforwardAnalysis.cpp
sysid/src/main/native/cpp/analysis/OLS.cpp
sysid/src/main/native/cpp/view/Analyzer.cpp
sysid/src/main/native/include/sysid/analysis/AnalysisManager.h
sysid/src/main/native/include/sysid/analysis/FeedforwardAnalysis.h
sysid/src/main/native/include/sysid/analysis/OLS.h
sysid/src/test/native/cpp/analysis/FeedforwardAnalysisTest.cpp
sysid/src/test/native/cpp/analysis/OLSTest.cpp

[sysid] Fix adjusted R² calculation

---

wpilibc/src/main/native/cpp/shuffleboard/ShuffleboardInstance.cpp
wpilibc/src/main/native/cpp/smartdashboard/SmartDashboard.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/ShuffleboardInstance.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

Shuffleboard will report usage if `getTab` is called. SmartDashboard will report usage on any `put` or `set` calls, but not `get` calls, since you can't get something without putting something there in the first place.
Fixes #6066.

Fix usage reporting for static classes

---

ntcore/src/main/native/include/networktables/NetworkTable.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.h
ntcore/src/main/native/include/networktables/NetworkTableInstance.inc
ntcore/src/main/native/include/networktables/StructArrayTopic.h
ntcore/src/main/native/include/networktables/StructTopic.h
ntcore/src/test/native/cpp/StructTest.cpp
wpiutil/src/main/native/include/wpi/DataLog.h
wpiutil/src/main/native/include/wpi/struct/Struct.h
wpiutil/src/test/native/cpp/DataLogTest.cpp

This allows using Struct in a dynamically typed environment by passing additional information to the Struct serialization functions.
Fixes #5964.

[wpiutil] Struct: Add info template parameter pack

---

hal/src/main/native/cpp/jni/CANJNI.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/HALUtil.h

Currently if you only initialize the array and not inner objects, those values will just be skipped over. Solve this by just allocating in place.

Allocate CANStreamMessage in JNI if null

---

hal/src/main/java/edu/wpi/first/hal/can/CANJNI.java
hal/src/main/java/edu/wpi/first/hal/can/CANStreamOverflowException.java
hal/src/main/native/cpp/jni/CANJNI.cpp
hal/src/main/native/cpp/jni/HALUtil.cpp
hal/src/main/native/cpp/jni/HALUtil.h

Currently a stream overflow will just throw an exception. We want the exception to contain the data that was read, as there is still valid data. Its just that some data was lost.

Add method to detect if the CAN Stream has overflowed

---

wpimath/CMakeLists.txt

This allows using Greek letters in variable names, which is helpful to make implemented equations follow their source paper more closely.

[wpimath] Compile with UTF-8 encoding

---

hal/build.gradle

The existing one worked for build, but it had the base classpath wrong, so it didn't work for intellisense. Fixes it to match the othr generated classes.

Fix generated source set location in the HAL

---

.clang-format
hal/src/main/native/include/hal/Accelerometer.h
hal/src/main/native/include/hal/AnalogTrigger.h
hal/src/main/native/include/hal/CANAPITypes.h
hal/src/main/native/include/hal/Counter.h
hal/src/main/native/include/hal/DMA.h
hal/src/main/native/include/hal/DriverStationTypes.h
hal/src/main/native/include/hal/Encoder.h
hal/src/main/native/include/hal/HALBase.h
hal/src/main/native/include/hal/I2CTypes.h
hal/src/main/native/include/hal/LEDs.h
hal/src/main/native/include/hal/PowerDistribution.h
hal/src/main/native/include/hal/REVPH.h
hal/src/main/native/include/hal/SPITypes.h
hal/src/main/native/include/hal/SerialPort.h
hal/src/main/native/include/hal/SimDevice.h

The [Macros](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#macros) option is new in clang-format 17.

Fix formatting of HAL_ENUM enums

---

docs/build.gradle

This avoids thousands of warnings from JavaDoc 17 parsing the OpenCV source.

[docs] Link to external OpenCV docs

---

wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/DifferentialDriveWheelVoltages.java
wpimath/src/main/java/edu/wpi/first/math/controller/ElevatorFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Quaternion.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Transform3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Twist2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Twist3d.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveWheelSpeeds.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelSpeeds.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModuleState.java
wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/Trajectory.java
wpiutil/src/main/java/edu/wpi/first/util/WPISerializable.java
wpiutil/src/main/java/edu/wpi/first/util/protobuf/ProtobufSerializable.java
wpiutil/src/main/java/edu/wpi/first/util/struct/StructSerializable.java

It prevented inheritance hierarchies from working.

[wpiutil] Remove type param from serializable marker interfaces

---

wpilibc/src/main/native/cpp/event/EventLoop.cpp
wpilibc/src/main/native/include/frc/event/EventLoop.h
wpilibc/src/test/native/cpp/event/EventLoopTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/EventLoop.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/event/EventLoopTest.java

Had a report on discord that a team was seeing ConcurrentModificationExceptions in EventLoop, but they didn't know where. The exception is thrown late by Java, so if you get it, debugging the error is very difficult. Throw the error early if we know a crash is going to occur, to make debugging easier.

Throw early when EventLoop is modified while running

---

wpilibcExamples/src/main/cpp/examples/AprilTagsVision/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/apriltagsvision/Robot.java

Changes size to 6.5 inches per https://www.firstinspires.org/robotics/frc/blog/2023-technology-updates-past-present-future-and-beyond 
Uses 7 error bit correction as recommended in photonvision docs 
Fixes #5763

[examples] Update april tag family to 36h11 in examples

---

.clang-tidy

These are the warnings being disabled:
```
== clang-tidy /__w/allwpilib/allwpilib/wpimath/src/test/native/cpp/DARETest.cpp ==
/__w/allwpilib/allwpilib/wpimath/src/test/native/cpp/DARETest.cpp:51:16: warning: avoid using "_" in test name "NonInvertibleA_ABQR" according to Googletest FAQ [google-readability-avoid-underscore-in-googletest-name]
51 | TEST(DARETest, NonInvertibleA_ABQR) {
|                ^
/__w/allwpilib/allwpilib/wpimath/src/test/native/cpp/DARETest.cpp:67:16: warning: avoid using "_" in test name "NonInvertibleA_ABQRN" according to Googletest FAQ [google-readability-avoid-underscore-in-googletest-name]
67 | TEST(DARETest, NonInvertibleA_ABQRN) {
|                ^
/__w/allwpilib/allwpilib/wpimath/src/test/native/cpp/DARETest.cpp:89:16: warning: avoid using "_" in test name …
```

Disable clang-tidy warning about test case names

---

glass/src/libnt/native/cpp/NetworkTablesProvider.cpp

Currently glass does not display any other information within the Networktables->SmartDashboard menu other than the name of the sendable/widget.  This adds the sendable type (obtained from NT ``.type``) along side the widget name.

[glass] Add type information to SmartDashboard menu

---

wpilibc/src/main/native/include/frc/ADXL345_I2C.h
wpilibc/src/main/native/include/frc/ADXL345_SPI.h
wpilibc/src/main/native/include/frc/AnalogGyro.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_I2C.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADXL345_SPI.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogGyro.java

This avoids needing add redundant JavaDocs to them, and better reflects how we design our modern classes (the classes modified here were around with minimal changes since 2008 or so).

[wpilib] Make protected fields in accelerometers/gyros private

---

hal/src/main/java/edu/wpi/first/hal/CANAPITypes.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/CAN.java

Adds the CanApitypes to Java, and updates a  few magic values to use the enum.

[hal] Add CanApitypes to java (Feature Parity) 

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/native/include/frc/filter/LinearFilter.h

Resolves #5203 
Adds an overload `reset(double[] inputBuffer, double[] outputBuffer)` method (`Reset(std::span<const double> inputBuffer, std::span<const double> outputBuffer)` in C++) that resets the Linear Filter and initializes the internal input and output buffers with the values that the user specifies, to avoid the unexpected values returned initially (as seen [here](https://github.com/wpilibsuite/allwpilib/issues/5079)).
The documentation for these methods includes a table that specifies the expected number of inputs and outputs that each filter type has. This will throw an error if the sizes are not correct.

Adds LinearFilter reset() overload to initialize input and output buffers

---

apriltag/src/main/java/edu/wpi/first/apriltag/jni/AprilTagJNI.java
hal/src/main/java/edu/wpi/first/hal/AnalogJNI.java
hal/src/main/java/edu/wpi/first/hal/PWMJNI.java
wpinet/src/main/java/edu/wpi/first/net/WPINetJNI.java
wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogJNI.java

Replicates missing JNI docs from C++

[docs] Add Missing JNI docs from C++ (NFC)

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/FunctionalCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/NotifierCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RepeatCommand.java

They were already private in C++ and probably shouldn't be exposed. This also means we don't need to write redundant documentation for them.

[cmd] Make Java fields private

---

ntcore/src/main/native/cpp/net/ClientImpl.cpp

This was caused by not swallowing id=-1 messages after processing the first one.

[ntcore] Fix client "received unknown id -1"

---

sysid/src/main/native/cpp/view/DataSelector.cpp
sysid/src/main/native/include/sysid/view/DataSelector.h

This is somewhat slower / more memory hungry, but handles data files that are organized differently (e.g. entries grouped instead of purely sorted by time).

[sysid] Data selector: use timestamps instead of ranges

---

sysid/src/main/native/cpp/view/DataSelector.cpp
sysid/src/main/native/include/sysid/view/DataSelector.h

Currently the analysis portion only supports quasistatic and dynamic, forward and reverse. Check for anything not matching and remove it, along with providing diagnostics of what is being loaded.
Fixes #6188.

[sysid] Filter valid test names

---

wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

[wpilib] add ADIS16470 methods with no params

---

sysid/src/main/native/cpp/analysis/FilteringUtils.cpp
sysid/src/test/native/cpp/analysis/FilterTest.cpp

Fixes behavior of peak acceleration selection by taking into account the sign of each point's velocity.

[sysid] Fix peak acceleration filtering behavior in dynamic velocity test

---

glass/src/lib/native/cpp/other/Field2D.cpp

Also adds some border padding for the non-image case.

[glass] Fix Field2d position and scaling

---

wpilibcExamples/src/main/cpp/examples/AprilTagsVision/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/apriltagsvision/Robot.java

Values >3 are not supported. https://github.com/wpilibsuite/apriltag/blob/64be6ab26abf5e995321997fd0752c609a7e30f4/apriltag.c#L261-L266

Limit error bit correction in April Tag examples

---

sysid/src/main/native/cpp/Util.cpp
sysid/src/main/native/cpp/analysis/AnalysisManager.cpp
sysid/src/main/native/cpp/view/Analyzer.cpp
sysid/src/main/native/cpp/view/AnalyzerPlot.cpp
sysid/src/main/native/include/sysid/Util.h
sysid/src/main/native/include/sysid/analysis/AnalysisManager.h
sysid/src/main/native/include/sysid/view/Analyzer.h
sysid/src/main/native/include/sysid/view/AnalyzerPlot.h

Refactors SysId error handling to not completely cancel analysis when bad feedforward gains are encountered but instead show a warning next to the specific gains that are invalid (with reasoning) - closes #6198. ~~Also still needs to address #6248.~~ #6248 should instead be addressed in a separate PR.

[sysid] Show warning tooltips next to bad feedforward gains instead of throwing

---

cscore/cscore-config.cmake.in

Attempting to build with cscore results in the project being unable to find wpinet unless explicitly found with `find_package` earlier.

[build] cmake: add wpinet dependency to cscore-config.cmake

---

wpilibc/src/main/native/include/frc/drive/DifferentialDrive.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java

They accidentally got reverted when undeprecating MotorController in the review process for #6053.

[wpilib] Fix outdated DifferentialDrive docs

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

The comment wasn't correct, its actually another class that loads in OpenCV. So this was just forcing an early load of CsCore when it might not be needed. This saves about 3 MB for robot projects that don't use any camera things.

Don't automatically pull in CsCore for all robot projects

---

ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/ValueCircularBuffer.cpp
ntcore/src/main/native/cpp/ValueCircularBuffer.h
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/cpp/ntcore_cpp.cpp
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

From the C API, using the raw entry API's can be easier. However, there are times when doing a small amount of type filtering in the native layer can remove a lot of copies and extra allocations in higher layers. Adds type filtering versions of NT_GetEntryValue and NT_ReadQueueValue functions to accommodate this.

Add typed C GetEntryValue and ReadQueueValue functions

---

ntcore/src/generate/main/java/NetworkTableEntry.java.jinja
ntcore/src/generated/main/java/edu/wpi/first/networktables/NetworkTableEntry.java
ntcore/src/main/java/edu/wpi/first/networktables/NetworkTable.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Servo.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/MecanumDrive.java
wpimath/src/main/java/edu/wpi/first/math/StateSpaceUtil.java
wpimath/src/main/java/edu/wpi/first/math/controller/ControlAffinePlantInversionFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SteadyStateKalmanFilter.java
wpimath/src/main/java/edu/wpi/first/math/path/TravelingSalesman.java
wpimath/src/main/java/edu/wpi/first/math/system/LinearSystem.java
wpimath/src/main/java/edu/wpi/first/math/system/LinearSystemLoop.java
wpimath/src/test/java/edu/wpi/first/math/controller/LinearQuadraticRegulatorTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/SimpleMotorFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/QuaternionTest.java
wpiunits/src/main/java/edu/wpi/first/units/Mult.java
wpiunits/src/main/java/edu/wpi/first/units/Per.java
wpiunits/src/main/java/edu/wpi/first/units/Velocity.java
wpiunits/src/test/java/edu/wpi/first/units/MeasureTest.java
wpiutil/src/main/java/edu/wpi/first/util/struct/StructFieldDescriptor.java

This squashes a few Error Prone warnings:
- https://errorprone.info/bugpattern/FloatingPointLiteralPrecision
- https://errorprone.info/bugpattern/InvalidParam
- https://errorprone.info/bugpattern/ProtectedMembersInFinalClass
- https://errorprone.info/bugpattern/UnnecessaryMethodReference
- https://errorprone.info/bugpattern/UnnecessaryParentheses
- https://errorprone.info/bugpattern/OperatorPrecedence (bitwise ops only, checkstyle conflicts)

Fix trivial errorprone warnings (NFC)

---

wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/test/native/cpp/WebSocketServerTest.cpp

Add "remote close:" to messages coming from the remote end. Previously it was impossible to tell if the error was on the local side or communicated by the remote side.

[wpinet] WebSocket: Improve disconnect reason reporting

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

The written amount wasn't being tracked in the common case, so bulk announcements after a subscribe would result in a very large WebSocket frame.

[ntcore] Fix large text message splitting

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

This results in no message actually being sent.

[ntcore] Don't disconnect with 1005 error code

---

ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/NetworkPing.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.cpp
ntcore/src/main/native/cpp/net/WebSocketConnection.h
ntcore/src/main/native/cpp/net/WireConnection.h
ntcore/src/test/native/cpp/net/MockWireConnection.h
ntcore/src/test/native/cpp/net/ServerImplTest.cpp
wpinet/src/main/native/cpp/WebSocket.cpp
wpinet/src/main/native/include/wpinet/WebSocket.h

This relaxes the timeout constraint for long message transmissions.

[ntcore] Use last received time instead of last ping response

---

.github/workflows/gradle.yml

With the GitHub upgrade to 16 GB RAM, this should no longer be needed.

[ci] Unlimit Windows Gradle workers

---

hal/src/main/native/athena/AddressableLED.cpp

Due to something weird in the FPGA, calling strobeLoad() with a string length of 0 causes both CPUs to spin at 100%, basically shutting down everything else on the robot.
If a 0 length string happens to be passed, just bail out early.
Closes #6257

Don't write a 0 length led string to the FPGA

---

glass/src/lib/native/cpp/other/FMS.cpp
glass/src/lib/native/include/glass/other/FMS.h
glass/src/libnt/native/cpp/StandardNetworkTables.cpp
hal/src/main/native/sim/DriverStation.cpp
hal/src/main/native/sim/mockdata/DriverStationData.cpp
hal/src/main/native/sim/mockdata/DriverStationDataInternal.h
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
wpilibc/src/test/native/cpp/simulation/DriverStationSimTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DriverStationSimTest.java

The default state for the DS in the simulated HAL is changed to disconnected.
The FMS view is now only editable in DS disconnected state.
This enables more robot and field-like testing of robot code, as the alliance color and other parameters start in invalid states and are only set when the DS connects.
Fixes #6199.

[sim] Sim GUI DS: Add "Disconnected" state and start in it

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/sysid/SysIdRoutine.java
wpilibNewCommands/src/main/native/include/frc2/command/sysid/SysIdRoutine.h

Previously, this used `mechanism.m_subsystem.getName()`, instead of `mechanism.m_name`, meaning differently named SysId routines from the same subsystem would clobber each other when logged.

Fix SysIdRoutine Naming

---

hal/src/main/native/athena/DMA.cpp

Closes #6276 
Timestamps in DMA are now 64 bits. This means the buffer being read was 1 too small to hold all the data, which caused the DMA buffer to get out of sync with the actual data.
Fix the bug, and also put in a print if this state is ever detected again to report to wpilib. This should never happen if our code is correct.

Use 64 bit timestamp in DMA

---

datalogtool/publish.gradle
glass/publish.gradle
outlineviewer/publish.gradle
roborioteamnumbersetter/publish.gradle

Closes #6204
#5586 was grabbing the incorrect executable on macOS. Also for some reason I only applied that to Glass and RTNS, when it should have been applied to all tools. Fix Glass and RTNS, and update the other tools to fix the issue that PR was originally supposed to fix.

Fix macOS apps not always being an application

---

sysid/src/main/native/cpp/analysis/OLS.cpp
sysid/src/test/native/cpp/analysis/OLSTest.cpp

I misread the slide the equation came from.

[sysid] Fix SSTO calculation

---

glass/src/lib/native/cpp/other/Field2D.cpp

Looks like the field length is longer in 2024. Used the onshape model to measure the size. This was the only place in the codebase I could find the 15.9 number

Update field size defaults in Field2D.cpp

---

upstream_utils/update_expected.py
wpiutil/.styleguide
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/native/thirdparty/expected/include/wpi/expected
wpiutil/src/test/native/cpp/expected/ExpectedTest.cpp

Its tests use Catch2 instead of GoogleTest, so we can't import them.
Fixes #6275.

[upstream_utils] Add std::expected shim

---

wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.inc
wpimath/src/main/native/include/units/base.h

Fixes #6312.
Supersedes #6315.

[wpimath] Make Rotation2d implicitly convert from any angle unit

---

.gitattributes

Just marking a file as text will cause git to override the local core.autocrlf setting, and assume you want it to be `true`, which isn't what you want.

Force cpp files to be lf line endings

---

wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/cpp/RapidReactCommandBot.cpp
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/cpp/subsystems/Storage.cpp
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Storage.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/RapidReactCommandBot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Storage.java

This eases inter-subsystem communication by making it easier to hook command and triggers together regardless of location and also makes code much cleaner and more readable.

[examples] Move triggers to subsystem fields

---

wpiunits/src/main/java/edu/wpi/first/units/Units.java

Some built in units are already defined with singularized aliases (`Seconds`/`Second`, `Minutes`/`Minute`, etc). This PR adds singularized aliases to most of the other built in units where it makes sense.

[wpiunits] Add singularized aliases for built in units

---

wpilibcExamples/src/main/cpp/examples/MecanumControllerCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/main/cpp/examples/SwerveControllerCommand/cpp/RobotContainer.cpp
wpilibcExamples/src/test/cpp/examples/MecanumControllerCommand/cpp/MecanumControllerCommandTest.cpp
wpilibcExamples/src/test/cpp/examples/MecanumControllerCommand/cpp/main.cpp
wpilibcExamples/src/test/cpp/examples/RamseteCommand/cpp/RamseteCommandTest.cpp
wpilibcExamples/src/test/cpp/examples/RamseteCommand/cpp/main.cpp
wpilibcExamples/src/test/cpp/examples/SwerveControllerCommand/cpp/SwerveControllerCommandTest.cpp
wpilibcExamples/src/test/cpp/examples/SwerveControllerCommand/cpp/main.cpp

Fixes #6258
I also added tests to prevent something like this happening again. Strangely, when I was running locally, I couldn't get the swerve controller example to fail- Only the mecanum controller and ramsete examples would fail. Given the non-determinism associated with memory errors, it probably isn't that important (especially since the swerve controller example can clearly fail), but I thought I'd mention it.

[examples] Fix memory leak in C++ controller command examples

---

wpilibcExamples/src/main/cpp/examples/RamseteCommand/cpp/subsystems/DriveSubsystem.cpp
wpilibcExamples/src/main/cpp/examples/SimpleDifferentialDriveSimulation/cpp/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/StateSpaceDifferentialDriveSimulation/cpp/subsystems/DriveSubsystem.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/ramsetecommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/statespacedifferentialdrivesimulation/subsystems/DriveSubsystem.java

This isn't necessary anymore, and could lead to potentially incorrect results if used with can-based encoders (eg, if the data returned immediately after reset isn't up-to-date)

[examples] Don't reset encoders when resetting odometry

---

wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/test/java/edu/wpi/first/units/MeasureTest.java

Now the function allows comparison between negative numbers, positive numbers or one and the other.
I also added tests to make sure this feature works.

[wpiunits] Fix measure `isNear` function

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLEDBuffer.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/AddressableLEDBufferTest.java

Add methods for reading individual RGB values from LED buffers

---

.github/workflows/cmake.yml
.github/workflows/comment-command.yml
.github/workflows/gradle.yml
.github/workflows/lint-format.yml
cscore/src/main/native/objcpp/UsbCameraImpl.mm
cscore/src/main/native/objcpp/UsbCameraListener.mm
sysid/src/test/native/cpp/analysis/OLSTest.cpp

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
Our deployment target is still set to 12.

[ci] Upgrade to new macOS runner

---

wpilibc/src/main/native/include/frc/sysid/SysIdRoutineLog.h

Fixes the m_stateInitialized not being initialized which causes non deterministic behavior as to if the `sysid-test-state-` will appear in the log.

[wpilibc] SysIdRoutineLog: Initialize m_stateInitialized

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Quaternion.java
wpimath/src/main/native/cpp/geometry/Quaternion.cpp

Norm() doesn't look to be super cheap, and log seems to be called a decent amount. Easy optimization.

[wpimath] Remove duplicate calls to norm() in Quaternion::Log()

---

wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.h
wpilibc/src/main/native/include/frc/smartdashboard/SendableChooser.inc

The `std::unique_ptr` case was added in #512, but it seems we never tested if `std::unique_ptr` can actually be used for `SendableChooser`, and as #5071 discusses, move-only types (which includes `std::unique_ptr`) aren't valid for `SendableChooser`.

Remove unusable std::unique_ptr case for SendableChooser

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/java/edu/wpi/first/math/filter/MedianFilter.java
wpimath/src/main/java/edu/wpi/first/math/filter/SlewRateLimiter.java
wpimath/src/main/native/cpp/controller/RamseteController.cpp
wpimath/src/main/native/include/frc/filter/LinearFilter.h
wpimath/src/main/native/include/frc/filter/MedianFilter.h
wpimath/src/main/native/include/frc/filter/SlewRateLimiter.h

Adds the getValue method to return the current value of a SlewRateLimiter without recalculating the value.

[wpimath] Add lastValue() method to filters

---

wpilibcExamples/src/main/cpp/examples/SysId/cpp/SysIdRoutineBot.cpp
wpilibcExamples/src/main/cpp/examples/SysId/cpp/subsystems/Shooter.cpp
wpilibcExamples/src/main/cpp/examples/SysId/include/Constants.h
wpilibcExamples/src/main/cpp/examples/SysId/include/SysIdRoutineBot.h
wpilibcExamples/src/main/cpp/examples/SysId/include/subsystems/Shooter.h
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/SysIdRoutineBot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/subsystems/Drive.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/subsystems/Shooter.java

Adds a shooter wheel subsystem to the SysIdRoutine example to demonstrate logging angular data

Add angular subsystem to SysIdRoutine example

---

wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/ElevatorFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.java

Fix using kv instead of ka in the error message when a negative ka is provided in the Feed forward classes

Fix using incorrect 'k' value when negative ka is provided in Feed Foward

---

wpinet/build.gradle

I think this is a typo? It prevents the headers defined in the `tcpsockets` library from being packaged in Maven artifacts, so when I download the headers and sources for wpinet from Maven and try to build I get the error
```
wpinet/sources/HttpUtil.cpp:14:10: fatal error: 'wpinet/TCPConnector.h' file not found
#include "wpinet/TCPConnector.h"
^~~~~~~~~~~~~~~~~~~~~~~
```

[wpinet] Fix tcpsockets header publishing

---

hal/src/main/native/athena/HAL.cpp
wpiutil/src/main/native/cpp/timestamp.cpp
wpiutil/src/main/native/include/wpi/timestamp.h

This might help root cause of the spam error message on wpi::now() failing.

Error out of hal initialize if SetupRioNow fails

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp

This check was mistakenly removed in #5659.

[ntcore] Don't send value update to client setting value

---

ntcore/src/main/java/edu/wpi/first/networktables/PubSubOption.java
ntcore/src/main/java/edu/wpi/first/networktables/PubSubOptions.java
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/jni/NetworkTablesJNI.cpp
ntcore/src/main/native/cpp/ntcore_c.cpp
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h

This allows creating subscribers that aren't communicated with the network.

[ntcore] Add hidden subscribe option

---

hal/src/main/native/athena/FRCDriverStation.cpp
hal/src/main/native/sim/DriverStation.cpp
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/RobotModeTriggersTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/button/RobotModeTriggersTest.cpp

Replaces #6379 
We need to have the control word match the control data that is part of the whole DS data structure. However, we need to handle the case where the DS disconnects, which will cause a timeout. We already had the logic to do this on the roboRIO, copy that logic here.

[hal] HAL_RefreshDSData: Zero out control word on DS disconnected, Use cache in sim

---

glass/src/lib/native/cpp/other/FMS.cpp

Also don't require Enter for editing match time.

[glass] Fix FMS game data editing

---

.github/workflows/cmake.yml
vcpkg.json

We need fmtlib 10.2.1 to work around a compiler bug.
Also, reducing the number of jobs is no longer required with Actions runner upgrades.

[ci] Windows cmake: update vcpkg version

---

sysid/src/main/native/cpp/analysis/FeedbackAnalysis.cpp

[sysid] Fix arm characterization crash

---

hal/src/main/java/edu/wpi/first/hal/HAL.java
hal/src/main/native/cpp/jni/HAL.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotBase.java

On Rio, we simply want to restart the robot program as quickly as possible, and don't want to risk a hang somewhere that will keep that from happening.

[wpilibj] Call abort() on Rio on caught Java exception

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/LinearSystemId.java
wpimath/src/main/native/include/frc/system/plant/LinearSystemId.h

That's just a system with no back-EMF.

[wpimath] LinearSystemId: Don't throw if Kv = 0

---

sysid/src/main/native/cpp/analysis/FeedbackAnalysis.cpp

LinearSystemId's linear system factories throw on negative feedforward gains, but SysId can compute the feedback gains just fine in that case. Now we construct the system manually instead.
Fixes #6423.

[sysid] Fix crash on negative feedforward gains

---

sysid/src/main/native/cpp/analysis/FeedbackAnalysis.cpp
sysid/src/test/native/cpp/analysis/FeedbackAnalysisTest.cpp

This is a fix for issue #6432, including a new unit test.

[sysid] Fix wrong position Kd with unnormalized time

---

ntcore/src/main/native/cpp/net/WebSocketConnection.cpp

I stumbled upon a memory leak having to do with calls to `nt::net::WebSocketConnection::AllocBuf()` within `nt::net::WebSocketConnection::write_impl()` (only seems to happen as a result of sending large binary buffers over NT). I'm not sure if this is the correct solution but it seemed to fix the issue, so feel free to make or suggest changes as necessary.
For reference, here is a screenshot of the memory allocation trace - there is pretty obviously something wrong:

[ntcore] Fix memory leak due to missing deallocations before reference clearing

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java

This fixes a bug if you're passing a custom EventLoop to Trigger where composing the trigger will use the default event loop instead of the one passed. C++'s Trigger and BooleanEvent already do this, this is solely a deficiency in the Java Trigger implementation AFAICT.

Trigger: pass m_loop to new Trigger in composition functions

---

wpiutil/src/main/native/cpp/DataLog.cpp

When low on space, a log file won't be created. This is detected as a "deletion", and the DataLog thread will continously try to create a log, fail to do so because of low space, detect it as a "deletion", and do so in a loop.
If there's not enough space, the DataLog will be marked as stopped, preventing this infinite loop. Calls to start() will hit this code path and mark it as stopped again.

Don't constantly retry log creation when low on space

---

.github/workflows/cmake.yml
.styleguide
vcpkg-configuration.json
vcpkg-ports/liblzma/add_support_ios.patch
vcpkg-ports/liblzma/build-tools.patch
vcpkg-ports/liblzma/fix_config_include.patch
vcpkg-ports/liblzma/portfile.cmake
vcpkg-ports/liblzma/usage
vcpkg-ports/liblzma/vcpkg-cmake-wrapper.cmake
vcpkg-ports/liblzma/vcpkg.json
vcpkg-ports/liblzma/win_output_name.patch

uses https://github.com/bminor/xz to work around suspended repository
We should revert this once vcpkg updates to point to an accessible repo

[ci] Use mirror repository for liblzma

---

wpilibc/src/main/native/include/frc/simulation/LinearSystemSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/LinearSystemSim.java

Clamp function was missing from setInput on Java version of LinearSystemSim
Also added a getInput method to Linear System Sim similar to getOutput.

[wpilib] Add missing clamp function and getInput() to LinearSystemSim

---

wpilibcExamples/src/main/cpp/examples/AprilTagsVision/cpp/Robot.cpp
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/apriltagsvision/Robot.java

Hamming distance of 3 (used prior on the example) produced unfeasible memory allocations of 932 MB. Reduced to hamming 1 so that both the RoboRIO 1 + 2 will be able to run it comfortably, whereas the RIO 2 might be able to use hamming 2, so a comment was added to specify that.
Fixes #6516.

Fix memory over-allocation in Apriltag examples

---

myRobot/src/main/java/frc/robot/MyRobot.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/CommandScheduler.java

Fixes #6437
This is the resulting error message:
```
Error at frc.robot.MyRobot.robotInit(MyRobot.java:20): Unhandled exception: java.lang.IllegalArgumentException: Commands that have been composed may not be added to another composition or scheduled individually!
java.lang.Exception: Originally composed at:
at edu.wpi.first.wpilibj2.command.Command.andThen(Command.java:252)
at frc.robot.MyRobot.robotInit(MyRobot.java:19)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:107)
at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:365)
at edu.wpi.first.wpilibj.RobotBase.lambda$startRobot$0(RobotBase.java:433)
at java.base/java.lang.Thread.run(Thread.java:833)
at edu.wpi.first.wpilibj2.command.Command.andThen(Command.java:252)
at …
```

[cmd] Fix double composition error truncation issue

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WrapperCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/WrapperCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/WrapperCommand.h

[commands] Call wrapped command initSendable in WrappedCommand

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java
wpiutil/src/main/native/cpp/DataLog.cpp

Uses `getUsableSpace` in Java, matching how C++ determines available space (C++ calls it `available`, but they mean the same thing.) This fixes a bug where logs wouldn't get deleted due to incorrect available space detection.
The DataLog thread now checks if the state was marked as stopped after a call to StartLogFile.
And a typo was fixed.

DataLog: Fix behavior when low on space

---

wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

This fix should've been in place years ago. Adding this will prevent the sensor from re-initializing in an invalid state when the 3.3V rail browns out.

Add flash update capability to ADI IMUs

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WaitCommand.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/frisbeebot/RobotContainer.java

[command based] add Measure<Time> overload of WaitCommand

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFieldLayout.java
apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFields.java

This will decrease the impact of calling `AprilTagFieldLayout.loadAprilTagLayoutField()` repeatedly (seen a few times on Discord/team github repos).
It will unfortunately still allocate because the origin of the field layout is mutable and could be changed by callers, so a fresh construction is needed.
Not sure the most ergonomic/idiomatic way to do this for c++; Also not sure how necessary it is (in both performance impact and likelihood of userbase to make the same mistake)

Cache layout loaded from AprilTagFields resource json

---

CONTRIBUTING.md
wpiunits/src/main/java/edu/wpi/first/units/Units.java

Added Angular Acceleration Units
RotationsPerSecondPerSecond
RadiansPerSecondPerSecond
DegreesPerSecondPerSecond
Added Moment of Inertia Unit
KilogramsMetersSquared

Added Acceleration and MOI Units

---

wpimath/src/main/native/include/frc/fmt/Eigen.h
wpimath/src/main/native/include/units/formatter.h

This is required for compatibility with libc++'s std::format.

[wpimath] Templatize formatters

---

ntcore/src/main/native/cpp/NetworkServer.cpp

Resolves https://github.com/wpilibsuite/allwpilib/issues/6520

[ntcore] backup file if it fails to open

---

wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java
wpimath/src/main/native/include/frc/estimator/PoseEstimator.h
wpimath/src/main/native/include/frc/estimator/PoseEstimator.inc
wpimath/src/main/native/include/frc/interpolation/TimeInterpolatableBuffer.h
wpimath/src/test/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimatorTest.java
wpimath/src/test/native/cpp/estimator/DifferentialDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/SwerveDrivePoseEstimatorTest.cpp

Fixes #6366.
I named it `sampleAt()` instead of `getEstimatedPosition()` since that's what's in #5473, but I could rename it to match the method name in the issue title.
The tests are right now all in one test to make sure the whole history makes sense, but I could also see a point for splitting apart the tests.

[wpimath] Add PoseEstimator.sampleAt()

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagFields.java
apriltag/src/main/native/include/frc/apriltag/AprilTagFieldLayout.h

Replaces #6331 in tandem with #6377 (which is already merged).

[apriltag] Deprecate AprilTagFields.loadAprilTagLayoutField() and LoadAprilTagLayoutField()

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/native/cpp/frc2/command/CommandPtr.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/CommandDecoratorTest.java

Resolves https://github.com/wpilibsuite/allwpilib/issues/6538

[commands] deprecate deadlineWith add deadlineFor

---

glass/src/lib/native/cpp/support/ExpressionParser.cpp
glass/src/lib/native/cpp/support/ExtraGuiWidgets.cpp
glass/src/lib/native/include/glass/support/ExpressionParser.h
glass/src/lib/native/include/glass/support/ExtraGuiWidgets.h
glass/src/libnt/native/cpp/NetworkTables.cpp

This is for easier adjustment of NetworkTables values when tuning values. For example, you can increase an angle by 5 degrees easily by adding `+5` to the value instead of doing the addition yourself. We implemented a similar feature in our custom dashboard program, which we found very convenient during the build season.

[glass] Add math expression input for NetworkTables numerical values

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/AsynchronousInterrupt.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/SynchronousInterrupt.java

The existing masks were only handling the first interrupt instance. So any interrupts after the first initialized just would not work at all.
SynchronousInterrupt is fine, as is AsynchronousInterrupt in C++.

Fix AsynchronousInterrupt in Java

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProxyCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/ProxyCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h
wpilibNewCommands/src/main/native/include/frc2/command/ProxyCommand.h

Deprecates the `ProxyCommand` supplier constructor in favor of deferring a `ProxyCommand` as discussed in #6324

[commands] Deprecate proxy supplier constructor

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation3d.java
wpimath/src/main/native/include/frc/geometry/Rotation3d.h

A Rotation3d is not defined by one angle.

[wpimath] Fix incorrect docs for Rotation3d default constructor

---

.github/workflows/gradle.yml
buildSrc/build.gradle

macOS 12 is EOL in mid-October of 2024 based on when macOS 11 was dropped last year.
Depends on wpilibsuite/native-utils#197.

[build] Bump macOS deployment target to 13

---

.github/workflows/documentation.yml
README-CMAKE.md
README.md
docs/build.gradle

Build javadocs with JDK 17 and remove JDK 11 workarounds 
Switch jdk distribution to temurin
Update readme to say to install JDK 17

JDK 17 updates

---

wpiunits/src/main/java/edu/wpi/first/units/Angle.java
wpiunits/src/main/java/edu/wpi/first/units/BaseUnits.java
wpiunits/src/main/java/edu/wpi/first/units/Current.java
wpiunits/src/main/java/edu/wpi/first/units/Dimensionless.java
wpiunits/src/main/java/edu/wpi/first/units/Distance.java
wpiunits/src/main/java/edu/wpi/first/units/Energy.java
wpiunits/src/main/java/edu/wpi/first/units/Mass.java
wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/main/java/edu/wpi/first/units/Mult.java
wpiunits/src/main/java/edu/wpi/first/units/Per.java
wpiunits/src/main/java/edu/wpi/first/units/Power.java
wpiunits/src/main/java/edu/wpi/first/units/Temperature.java
wpiunits/src/main/java/edu/wpi/first/units/Time.java
wpiunits/src/main/java/edu/wpi/first/units/UnaryFunction.java
wpiunits/src/main/java/edu/wpi/first/units/Unit.java
wpiunits/src/main/java/edu/wpi/first/units/UnitBuilder.java
wpiunits/src/main/java/edu/wpi/first/units/Units.java
wpiunits/src/main/java/edu/wpi/first/units/Velocity.java
wpiunits/src/main/java/edu/wpi/first/units/Voltage.java
wpiunits/src/test/java/edu/wpi/first/units/DistanceTest.java
wpiunits/src/test/java/edu/wpi/first/units/ExampleUnit.java
wpiunits/src/test/java/edu/wpi/first/units/UnitsTest.java
wpiunits/src/test/java/edu/wpi/first/units/VelocityTest.java

Unit objects now have a reference to the base unit from which they're derived. Constructing a unit object without specifying a base unit implicitly signifies that it's its own base unit, eg `new Angle(null, 1, "Radian", "rad")` would be the base angle unit of radians, while `new Angle(Radians, 2 * PI, "Rotation", "R")` would be a new angle unit based on radians.
This fixes much of the hacky code surrounding the derived unit types `Velocity`, `Per`, and `Mult`, but is a breaking change for any user code that defines custom unit classes or uses the anonymous unit type

[units] Change units to track their base unit, instead of their base class

---

.github/workflows/lint-format.yml

No changes are necessary now, but may help make sure new contributions won't cause issues when we're ready to switch to JDK 21

Run Doc lint with JDK 21

---

upstream_utils/fmt_patches/0001-Suppress-warnings-we-can-t-fix.patch
upstream_utils/fmt_patches/0002-Fix-tautological-compare-warning.patch
upstream_utils/update_fmt.py
wpiutil/src/main/native/thirdparty/fmtlib/include/fmt/ranges.h

[upstream_utils] Fix fmtlib tautological-compare warning from GCC 14

---

upstream_utils/eigen_patches/0001-Disable-warnings.patch
upstream_utils/eigen_patches/0002-Intellisense-fix.patch
upstream_utils/eigen_patches/0003-Suppress-C-23-deprecation-warnings-for-std-has_denor.patch
upstream_utils/update_eigen.py
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/BFloat16.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/Half.h

std::has_denorm and std::has_denorm_loss were deprecated in C++23. This avoids deprecation warnings with Clang 18 set to C++23.

[upstream_utils] Suppress deprecation warnings for Eigen's has_denorm

---

upstream_utils/eigen_patches/0003-Suppress-C-23-deprecation-warnings-for-std-has_denor.patch
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/BFloat16.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/Half.h

I've confirmed this fixes the build with GCC 14 in C++23 mode.

[upstream_utils] Fix Eigen macro name

---

wpimath/src/main/native/include/frc/filter/LinearFilter.h

Previously, the two-parameter `LinearFilter::Reset` overload took `span<double>` parameters. However, m_inputs and m_outputs store T, so for any T that does not have an implicit constructor from double (such as the units library), the two-parameter Reset function is not usable.
The two possible solutions are to add an explicit T() in the push_back calls, or fix the overload to take `span<T>`. This PR does the latter.

Modify C++ `LinearFilter::Reset(span<double>, span<double>)` to take `span<T>`

---

wpimath/src/main/java/edu/wpi/first/math/interpolation/InterpolatingDoubleTreeMap.java

[wpimath] Add InterpolatingDoubleTreeMap.of()

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/main/native/include/frc/kinematics/ChassisSpeeds.h

[wpimath] Add ChassisSpeeds::ToTwist2d() to ChassisSpeeds

---

wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ADIS16448SimTest.java

Some tests for the ADIS16448 simulation, I may also get around to doing the ADIS16470 soon. #5136 
Any suggestions are welcome, I may have been a little overzealous with the number of test cases. 
I have a snippet saved that also checks all port combinations, but that doubles the test count (approx 1600 tests total) and is most surely overcomplicated/unnecessary.

Add test to ADIS16448 simulation

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/SharpIR.java

This was introduced by #6023, but for some reason the CI runs on `main` used the build cache for `wpilibj:compileJava` and did not get this error, and since our [checkout step](https://github.com/wpilibsuite/allwpilib/blob/e2545231b8858fc8957802e34bdfe564a7bcd99b/.github/workflows/gradle.yml#L40) only checks out the commit that triggered the CI run (the default for [actions/checkout](https://github.com/actions/checkout)) and the PR was based on an old version of main that was still on Java 11, the PR CI runs were with Java 11, which does not have the warning.
I'm concerned about the fact that this could happen (CI runs pass but local clean builds fail), but I'm not sure what the best fix for the root cause would be. (Figure out why the build cache was reused? Figure out how to avoid …

[wpilibj] Suppress this-escape warning on SharpIR

---

wpilibNewCommands/src/main/native/include/frc2/command/button/CommandXboxController.h

#6296 accidentally omitted the `public` specifier on `CommandGenericHID` in the base class section of `CommandXboxController`. Since `CommandXboxController` is declared using `class`, the default access for base classes is private, which prevents users outside the class from using methods declared in `CommandGenericHID`, which was the point of the PR.
I checked and the other files touched by that PR do not have the issue. I also confirmed locally that using methods declared in `CommandGenericHID` (such as `Button(int)`) on a `CommandXboxController` works with the following diff:
```diff
diff --git a/developerRobot/src/main/native/cpp/Robot.cpp b/developerRobot/src/main/native/cpp/Robot.cpp
index 238697d42..9f6075dae 100644
--- a/developerRobot/src/main/native/cpp/Robot.cpp
+++ …
```

[C++ cmd] Make CommandGenericHID as a public base class of CommandXboxController

---

wpiutil/src/main/java/edu/wpi/first/util/CombinedRuntimeLoader.java

The default extraction path code was removed, which made any use of the combined runtime loader throw an NPE. Fix that issue by adding the default path back in.

Fix CombinedRuntimeLoader default path

---

wpiutil/src/main/java/edu/wpi/first/util/CombinedRuntimeLoader.java

With DependentLoadFlags, we shouldn't need this function anymore. Add a way to test this easily without needing to modify allwpilib.

Add method to skip SetDllDirectory for windows loading

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CallbackStore.java

This is "strongly recommended" in the javadocs for the AutoCloseable.close(). See: https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html#close--

Make CallbackStore.close() idempotent.

---

hal/src/main/native/sim/DIO.cpp
wpilibc/src/test/native/cpp/simulation/DIOSimTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/DIOSimTest.java

SimDIOData already initializes the value to true, this fixes the case where you create a DIO object, set its value to false, destroy it, and create another DIO object on the same port. This always ensures the new DIO object initializes to true.

[hal] Initialize DIO to true in sim

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CallbackStore.java

This  is to allow 3rd party sim providers (eg vendors) to subclass this class so that the register methods of their sim classes can return CallbackStores like the builtin sims.
Although it was already possible to create such a subclass but passing dummy parameters to one of the other constructors, this eliminates the need to pass such dummy parameters and makes it clearer that subclassing is allowed.

Add protected default constructor for CallbackStore.

---

hal/src/main/java/edu/wpi/first/hal/SimDevice.java
hal/src/main/java/edu/wpi/first/hal/SimDeviceJNI.java
hal/src/main/native/include/hal/SimDevice.h
simulation/halsim_ws_core/doc/hardware_ws_api.md
simulation/halsim_ws_core/doc/wpilib-ws.yaml

The way the current documentation is written implies that WebSockets nodes of the type `CAN*` are created as `SimDevice` nodes that are differentiated by a unique naming convention. In actuality, they have unique device types, and the naming convention is how they are created through the WPILib C/Java API. This PR clarifies that distinction and updates the machine-readable spec, which was written with the incorrect interpretation in mind.

Clarify Sim CAN Device Documentation

---

fieldImages/src/main/java/edu/wpi/first/fields/FieldConfig.java
fieldImages/src/main/java/edu/wpi/first/fields/Fields.java
fieldImages/src/test/java/edu/wpi/first/fields/LoadConfigTest.java

Doesn't make sense in edu.wpi.fields, and resources are already in edu.wpi.first.fields
This will require changes in Shuffleboard and Pathweaver

Move Java fields to edu.wpi.first.fields

---

wpimath/src/main/java/edu/wpi/first/math/filter/LinearFilter.java
wpimath/src/main/native/include/frc/filter/LinearFilter.h

The current implementation of LinearFilter's lastValue() method causes a runtime exception when the size of the output gains buffer is 0, such as with a Moving Average Filter. In this case, outputs are not added to the buffer, and attempting to get the last value throws an index out-of-bounds exception. This behavior is not documented anywhere.
This fixes this issue by saving the last calculated value to a member variable and returning that when lastValue() is called, in both Java and C++.

[wpimath] Fix runtime exception thrown by LinearFilter lastValue()

---

upstream_utils/sleipnir_patches/0001-Remove-using-enum-declarations.patch
upstream_utils/sleipnir_patches/0002-Add-implicit-typename.patch
upstream_utils/sleipnir_patches/0003-Use-fmtlib.patch
upstream_utils/sleipnir_patches/0004-Remove-unsupported-constexpr.patch
upstream_utils/update_sleipnir.py
wpimath/src/main/native/thirdparty/sleipnir/.styleguide
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/Expression.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/VariableBlock.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/autodiff/VariableMatrix.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/util/Concepts.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/.styleguide

Upstream now uses std::format/std::print, so we have to backport it to fmtlib.

[upstream_utils] Update Sleipnir

---

.github/workflows/command-robotpy-pr.yml

[The docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) say that `GITHUB_TOKEN` will be given write permissions when using `pull_request_target`. Using `pull_request` means [the permissions will be read-only](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token).

Fix robotpy PR commenting for real this time

---

upstream_utils/eigen_patches/0001-Disable-warnings.patch
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/util/DisableStupidWarnings.h

```
In file included from /home/tav/frc/wpilib/allwpilib/wpimath/src/main/native/thirdparty/eigen/include/Eigen/Core:360,
from /home/tav/frc/wpilib/allwpilib/sysid/src/main/native/include/sysid/analysis/OLS.h:10,
from /home/tav/frc/wpilib/allwpilib/sysid/src/main/native/include/sysid/analysis/FeedforwardAnalysis.h:12,
from /home/tav/frc/wpilib/allwpilib/sysid/src/main/native/cpp/analysis/FeedforwardAnalysis.cpp:5:
/home/tav/frc/wpilib/allwpilib/wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/products/SelfadjointMatrixVector.h: In function ‘static void Eigen::internal::selfadjoint_product_impl<Lhs, LhsMode, false, Rhs, 0, true>::run(Dest&, const Lhs&, const Rhs&, const Scalar&) [with Dest = Eigen::Block<Eigen::Matrix<double, -1, 1>, -1, 1, false>; Lhs = …
```

[upstream_utils] Disable spurious maybe-uninitialized warning from GCC 14

---

wpiutil/src/main/native/cpp/DataLogBackgroundWriter.cpp

Accidently removed in #6590. Originally from #6468.

[wpiutil] DataLog: Don't constantly retry log creation when low on space

---

apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cscore/CMakeLists.txt
wpilibj/CMakeLists.txt

This adds a bunch of paths where OpenCV currently places its JAR and libraries, both on Windows and Linux, and in both installed and non-installed forms.
This also makes all the searches consistent.

[build] cmake: Improve OpenCV file search

---

wpilibc/src/main/native/cpp/motorcontrol/PWMMotorController.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/motorcontrol/PWMMotorController.java

Previously, in `MotorControllerGroup`s, calling `stopMotor()` or `disable()` stopped all the motors in that group. Now that this class is marked for deprecation, it recommends to use `PWMMotorController.addFollower()` to create groups. This functionality is not consistent in the PWMMotorController class, where calling either of these methods only applies to that motor, and not its followers. The JavaDocs also specify that the follower motor will follow the outputs of the leader. Thus, it is logical that calling either of these methods should also call them for all of that motor's followers.
This adds that functionality in both Java and C++.

[wpilib] Propagate PWMMotorController stopMotor() and disable() to followers

---

.github/workflows/pregenerate.yml
hal/generate_usage_reporting.py
ntcore/generate_topics.py
wpilibNewCommands/generate_hids.py
wpilibc/generate_hids.py
wpilibj/generate_hids.py
wpimath/generate_numbers.py
wpimath/generate_quickbuf.py

This stems from [this](https://github.com/wpilibsuite/allwpilib/pull/6742#issuecomment-2169133945) comment left on my other PR.
When I made the PWM generator, I copied the style of the other pregeneration tools. However the `Path` library is nice, and if that was requested in that PR, these other files should be updated for consistency. I also added type hints where possible, and snuck in command line arguments so that my bazel build can run the generation during a build.
In the cases where it existed, I removed the "only write if dirty" check. This isn't as crucial since the scripts don't get run during a build, and I thought it was better for the "least astonishment principle" if it _always_ generates the files, as its name suggests.

[pregen] Use pathlib in pre-generation scripts

---

.github/workflows/gradle.yml

Allows automation of tagging of tools on allwpilib tag.
Adapted from robotpy

Add dispatch actions task to ping tools on tag

---

.github/workflows/cmake.yml
.github/workflows/documentation.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/gradle.yml
.github/workflows/sanitizers.yml

Bump webfactory/ssh-agent to 0.9.0 (Node 20)
Switch to gradle/actions/wrapper-validation (Node 20)
Bump mozilla-actions/sccache-action to 0.0.5 (Node 20 for sanitizers only)
Bump actions/github-script to 7 (Node 20 for documentation only)
Bump wpilibsuite/import-signing-certificate to 2 (Node 20)
Bump JamesIves/github-pages-deploy-action to 4.6.1 (Node 20)
Resolves #5825.

[ci] Bump actions versions

---

.github/workflows/tools.yml

Fixes robotbuilder build that failed after 2025 alpha tag

Update tools build year to 2025

---

simulation/halsim_xrp/README.md
simulation/halsim_xrp/src/main/native/cpp/XRP.cpp

The XRP firmware has been updated to provide the encoder period along with the encoder count.  (See Pull Request wpilibsuite/xrp-wpilib-firmware#40)
This change allows WPILIB to use the encoder period data from the XRP so that the GetRate function can be used to determine the motor speed.
This change is designed to be backward compatible with previous versions of the XRP firmware that do not provide the encoder period.

Add Support for Encoder Period on XRP

---

build.gradle
wpimath/build.gradle

Since we pregen Jinja templates, we don't need jinjava anymore.

[build] Drop jinjava as a Gradle dependency

---

CMakeLists.txt
README-CMAKE.md
hal/CMakeLists.txt

It was broken in #2788. I don't see much utility in fixing this compared to just modifying hal/CMakeLists.txt to point to alternative HAL source files, especially because [a vendor](https://github.com/kauailabs/allwpilib/blob/master/hal/CMakeLists.txt) has already done just that.

[build] CMake: remove external HAL option

---

wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Ellipse2dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Pose2dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Pose3dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Rectangle2dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Rotation3dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Transform2dProto.java
wpimath/src/main/java/edu/wpi/first/math/geometry/proto/Transform3dProto.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/proto/MecanumDriveKinematicsProto.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/proto/SwerveModulePositionProto.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/proto/SwerveModuleStateProto.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/proto/TrajectoryProto.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/proto/TrajectoryStateProto.java
wpiutil/src/main/java/edu/wpi/first/util/protobuf/Protobuf.java

It was superseded by using `FileDescriptor.getDependencies()`.

[wpiutil] Remove Protobuf.getNested()

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.inc

[wpimath] Report error when x and y components of Rotation2d are zero

---

wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Odometry.java
wpimath/src/main/native/include/frc/estimator/PoseEstimator.h
wpimath/src/main/native/include/frc/estimator/PoseEstimator.inc
wpimath/src/main/native/include/frc/kinematics/Odometry.h

Requires https://github.com/wpilibsuite/allwpilib/pull/6702
Resolves https://github.com/wpilibsuite/allwpilib/issues/5001

[wpimath] Add Reset methods to PoseEstimator

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ConditionalCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelCommandGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelRaceGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RepeatCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SelectCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/SequentialCommandGroup.java

[commands] Update requirements consistently

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Command.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelCommandGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelDeadlineGroup.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ParallelRaceGroup.java
wpilibNewCommands/src/main/native/include/frc2/command/Command.h

Requires https://github.com/wpilibsuite/allwpilib/pull/6304

[commands] Make requirements private

---

wpimath/src/main/java/edu/wpi/first/math/spline/Spline.java
wpimath/src/main/java/edu/wpi/first/math/spline/SplineParameterizer.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/TrajectoryGenerator.java
wpimath/src/main/native/include/frc/spline/Spline.h
wpimath/src/main/native/include/frc/spline/SplineParameterizer.h
wpimath/src/main/native/include/frc/trajectory/TrajectoryGenerator.h
wpimath/src/test/java/edu/wpi/first/math/spline/CubicHermiteSplineTest.java
wpimath/src/test/native/cpp/spline/CubicHermiteSplineTest.cpp

Currently, a max iteration heuristic is used to determine when a spline is malformed. Instead, we can report a failure immediately if dx and dy are too small, because the heading won't be accurate either.
Fixes #6826.

[wpimath] Exit early when parameterizing malformed spline

---

upstream_utils/eigen_patches/0001-Disable-warnings.patch
upstream_utils/eigen_patches/0002-Intellisense-fix.patch
upstream_utils/eigen_patches/0003-Suppress-has_denorm-and-has_denorm_loss-deprecation-.patch
upstream_utils/update_eigen.py
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/BFloat16.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/arch/Default/Half.h

MSVC doesn't yet claim C++23 compliance for c++latest, so we have to be less specific in the preprocessor check.

[upstream_utils] Suppress has_denorm deprecation in Eigen

---

CMakeLists.txt
apriltag/CMakeLists.txt
cameraserver/CMakeLists.txt
cmake/modules/CreateSourceJar.cmake
cscore/CMakeLists.txt
hal/CMakeLists.txt
ntcore/CMakeLists.txt
romiVendordep/CMakeLists.txt
wpilibNewCommands/CMakeLists.txt
wpilibj/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiunits/CMakeLists.txt
wpiutil/CMakeLists.txt
xrpVendordep/CMakeLists.txt

An `add_source_jar` macro has been added to simplify maintaining source JARs. The old approach has many bugs, and is easily prone to falling out-of-date when new packages are introduced. Instead, the root directories where Java packages are located are given to the macro, and the macro will handle finding all the source files and assigning the right package to them. In addition, the minimum CMake version has been bumped to 3.21 to ensure the `RESOURCES` parameter is available.

[build] CMake: simplify source JAR creation and install

---

cmake/modules/CompileWarnings.cmake
shared/config.gradle

Currently, artifacts are broken on a number of non-wpilib windows JVMs due to the JVM using an older redistributable.

[build] Disable std::mutex constexpr constructor on Windows (again)

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Kinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveKinematics.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/Odometry.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/Kinematics.h

This saves on a deep copy of the wheel positions in `Odometry.resetPosition()` and `Odometry.update()`, and by extension `PoseEstimator.resetPosition()` and `PoseEstimator.update()`. Notably, for a 4 module swerve that's 5 object allocations (1 for the array and 1 per module), which given that `update()` is typically called every single robot loop can add up relatively quickly. It also doesn't effect what few custom kinematics implementations there are, since you could use the defaulted implementation.

[wpimath] Add and use kinematics.copyInto()

---

.github/workflows/upstream-utils.yml
upstream_utils/README.md
upstream_utils/eigen.py
upstream_utils/expected.py
upstream_utils/fmt.py
upstream_utils/gcem.py
upstream_utils/json.py
upstream_utils/libuv.py
upstream_utils/llvm.py
upstream_utils/memory.py
upstream_utils/mpack.py
upstream_utils/protobuf.py
upstream_utils/sleipnir.py
upstream_utils/stack_walker.py
upstream_utils/upstream_utils.py

Fixes #6818
Notes:
* For some reason, when running the script locally, mpack would get changed, and I'm not sure why. If I ran it on main, I could also have some local changes, but it'd be a different set of local changes. I'll wait to see what happens on CI.
* Eigen and sleipnir had changes to the index lines of the patches when running locally, and I'm not sure why.
* Stack walker also got trailing whitespace when running locally, for some reason.
* While working on this I had some ideas for additional commands. I don't know if we'd want to implement those in this PR or in separate PR(s).
* `./<lib>.py info`: Displays information about the library. (Mostly useful for clone directory, URL, tag, and patch list, but we might as well include the rest of the constructor arguments)
* …

[upstream_utils] Rework upstream_utils scripts

---

hal/src/main/native/sim/Interrupts.cpp
wpilibc/src/test/native/cpp/InterruptTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/InterruptTest.java

Fixes #6440, fixes #6515. Replaces #6688.

[hal] Fix interrupt edges being flipped in sim

---

wpilibc/src/main/native/cpp/TimedRobot.cpp
wpilibc/src/main/native/include/frc/TimedRobot.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/TimedRobot.java

If one of the *Init() functions takes several multiples of the nominal
loop time, the callbacks after that will run, then increment their
expiration time by the nominal loop time. Since the new expiration time
is still in the past, this will cause the callback to get repeatedly run
in quick succession until its expiration time catches up with the
current time.
This change keeps incrementing the expiration time until it's in the
future, which will avoid repeated runs. This doesn't delay other
callbacks, so they'll get a chance to run once before their expiration
times are corrected.
The other option is correcting all the expiration times at once, which
would starve the other callbacks even longer so that the callback
scheduling returns to a regular cadence sooner. The problem with this …

[wpilib] Fix repeat TimedRobot callbacks on loop overrun

---

wpilibc/src/test/native/cpp/InterruptTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/InterruptTest.java

Interrupt tests seem to be failing often only on Gradle Win64Debug, but different tests fail, and sometimes there's no failure. More time has been given to the interrupts to try and allow the state to propagate.

[wpilib] Increase time between interrupt operations in tests

---

wpilibc/src/main/native/cpp/LEDPattern.cpp

I'm guessing that on most systems, those header files would get included transitively anyways, but on mine (and maybe some others) they wouldn't.

[wpilibc] Add missing includes to LEDPattern.cpp

---

wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibc/src/main/native/include/frc/ADIS16448_IMU.h
wpilibc/src/main/native/include/frc/ADIS16470_IMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

Create acquire thread with method reference instead of Runnable class
Clean up comments and bad Javadoc (removed useless doc stubs, used single line comments instead of multi-line everywhere, removed low value comments)
Clean up variable declarations (declared and assigned variables when needed instead of declaring upfront and assigning later, made needsFlash a local in Java)
Remove unused gyro data variables (mostly average gyro data in Java)
Remove and/or inline a bunch of the conversion functions
Make toInt in Java take four ints instead of varargs to reduce allocations
Remove unnecessary parentheses and casts
Use InputModulus or angleModulus and remove custom angle wrapping
Use hypotf instead of manual calculation
Remove a bunch of warning suppressions as they were either fixed or …

[wpilib] Refactor and clean up ADIS IMU classes

---

hal/src/main/native/sim/mockdata/SimDeviceData.cpp
hal/src/main/native/sim/mockdata/SimDeviceDataInternal.h

This can cause lock inversions with other code (in particular with the simulation WebSockets interface).
Fixes #6842.

[hal] SimDevice: Don't hold lock during callbacks

---

wpimath/src/main/java/edu/wpi/first/math/controller/PIDController.java
wpimath/src/main/java/edu/wpi/first/math/controller/ProfiledPIDController.java
wpimath/src/main/native/cpp/controller/PIDController.cpp
wpimath/src/main/native/include/frc/controller/PIDController.h
wpimath/src/main/native/include/frc/controller/ProfiledPIDController.h

Adds a method `getAccumulatedError()` (`GetAccumulatedError()` in cpp) to get the accumulated value used for the integral gain of the PID controllers. This can be useful in debugging to determine how high the integral accumulates over time.
This has Java and CPP implementations for PIDController and ProfiledPIDController.

[wpimath] Add getAccumulatedError() to PIDController

---

wpiutil/src/main/java/edu/wpi/first/util/datalog/BooleanArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/BooleanLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogJNI.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLogWriter.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DoubleArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/DoubleLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/FloatArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/FloatLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/IntegerArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/IntegerLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/ProtobufLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/RawLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/StringArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/StringLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/StructArrayLogEntry.java
wpiutil/src/main/java/edu/wpi/first/util/datalog/StructLogEntry.java
wpiutil/src/main/native/cpp/DataLog.cpp
wpiutil/src/main/native/cpp/jni/DataLogJNI.cpp
wpiutil/src/main/native/include/wpi/DataLog.h
wpiutil/src/main/native/include/wpi/DataLogWriter.h
wpiutil/src/test/java/edu/wpi/first/util/datalog/DataLogTest.java
wpiutil/src/test/native/cpp/DataLogTest.cpp

Update() checks/updates the last value and appends only if changed. GetLastValue() gets the last value.
This is only implemented at the Entry object level, not the overall DataLog, to avoid needing to add a hashtable lookup.
TODO:

[wpiutil] DataLog: Add last value and change detection

---

upstream_utils/README.md
upstream_utils/apriltag.py
upstream_utils/eigen.py
upstream_utils/expected.py
upstream_utils/fmt.py
upstream_utils/gcem.py
upstream_utils/gl3w.py
upstream_utils/glfw.py
upstream_utils/googletest.py
upstream_utils/imgui.py
upstream_utils/implot.py
upstream_utils/json.py
upstream_utils/libuv.py
upstream_utils/llvm.py
upstream_utils/memory.py
upstream_utils/mpack.py
upstream_utils/protobuf.py
upstream_utils/sleipnir.py
upstream_utils/stack_walker.py
upstream_utils/stb.py
upstream_utils/upstream_utils.py

Resolves #6864
To simplify the logic for searching for the patch list, all libraries have a `patch_list` variable, even if there are no patches. (Inlining the list was originally done so that libraries not needing it have less clutter, but patches are pretty likely to be added at some point, so it's fine to make all libraries have an extra line or two for that. It also makes things more consistent, but by far the biggest factor was that otherwise, the logic for the auto replacement would have to be significantly more complex)
The patch list is no longer checked, since it should be up to date unless the contributor makes manual edits outside of the CLI, and there would be false positives when running `format_patch` since the check didn't use the updated list.

[upstream_utils] Determine patch list from patch files

---

hal/src/main/native/include/hal/CAN.h

- Puts CAN functions in their own group (separate from CAN Stream Functions)
- Document HAL_CANStreamMessage
- fix typo

[docs] Cleanup HAL CAN docs (NFC)

---

wpimath/src/main/native/include/frc/controller/ArmFeedforward.h
wpimath/src/main/native/include/frc/controller/ElevatorFeedforward.h
wpimath/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
wpimath/src/test/java/edu/wpi/first/math/controller/ArmFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/ElevatorFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/SimpleMotorFeedforwardTest.java
wpimath/src/test/native/cpp/controller/ArmFeedforwardTest.cpp
wpimath/src/test/native/cpp/controller/ElevatorFeedforwardTest.cpp
wpimath/src/test/native/cpp/controller/SimpleMotorFeedforwardTest.cpp

Previously, the constructors would assign to the argument.
Also makes SimpleMotorFeedforward's constructor match the others. (No IIFE, assign before warning about defaulting)

[wpimath] Fix C++ feedforward constructors and add tests

---

wpilibNewCommands/src/test/java/edu/wpi/first/wpilibj2/command/button/TriggerTest.java
wpilibNewCommands/src/test/native/cpp/frc2/command/button/TriggerTest.cpp

Add Trigger.onChange() test

---

hal/src/main/native/sim/CANAPI.cpp

Removed from API in #1868, sim definition was left dangling
Also adds `extern "C"` to the sim file

[hal] remove dangling periodic packet function from sim CANAPI (NFC)

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/AddressableLEDSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/AnalogGyroSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/AnalogInputSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/AnalogOutputSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/AnalogTriggerSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/BuiltInAccelerometerSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/CTREPCMSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DIOSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DigitalPWMSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DriverStationSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DutyCycleSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/EncoderSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/I2CSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PDPSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PWMSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/PneumaticsBaseSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/REVPHSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RelaySim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/RoboRioSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SPIAccelerometerSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SPISim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SimDeviceSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SolenoidSim.java

That behavior has not been present since PR #4158 was merged more than 2 years ago and imo should not be added back because it was surprising and not consistent with the most common use case of registering a callback permanently.

Fix sim javadocs to not say GC will cancel callbacks.

---

hal/src/main/java/edu/wpi/first/hal/CTREPCMJNI.java
hal/src/main/java/edu/wpi/first/hal/REVPHJNI.java
hal/src/main/native/include/hal/CTREPCM.h
hal/src/main/native/include/hal/REVPH.h

follow up to #6884, found some more

[hal][docs] Update PCM/PH HAL bitmap function docs (NFC)

---

wpilibc/src/test/native/cpp/InterruptTest.cpp
wpilibj/src/test/java/edu/wpi/first/wpilibj/InterruptTest.java

If the interrupt edge tests are running while under heavy CPU load (like building wpilib,) they are prone to failure since the interrupt thread doesn't have enough time to set up callbacks. The interrupt edge tests now behave like the original AsynchronousInterrupt test, which has a 0.5s delay after the interrupt is enabled. Running the new interrupt tests while building allwpilib causes almost no failures compared to the old tests.

[wpilib] Wait 0.5s after enabling interrupts in tests

---

wpilibNewCommands/src/generate/main/java/edu/wpi/first/wpilibj2/command/button/commandhid.java.jinja
wpilibNewCommands/src/generate/main/native/cpp/frc2/command/button/commandhid.cpp.jinja
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS4Controller.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS5Controller.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandStadiaController.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java
wpilibNewCommands/src/generated/main/native/cpp/frc2/command/button/CommandPS4Controller.cpp
wpilibNewCommands/src/generated/main/native/cpp/frc2/command/button/CommandPS5Controller.cpp
wpilibNewCommands/src/generated/main/native/cpp/frc2/command/button/CommandStadiaController.cpp
wpilibNewCommands/src/generated/main/native/cpp/frc2/command/button/CommandXboxController.cpp
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandGenericHID.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandJoystick.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandGenericHID.cpp
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandJoystick.cpp
wpilibj/src/generate/hid.java.jinja
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS5Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/StadiaController.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/XboxController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java

Fixes #5903, resolves #6445 by updating it to work with the HID templates. (Updating those is great by the way, you just have to change a few lines and regenerate!)

[wpilib, commands] Cache controller BooleanEvents/Triggers and directly construct Triggers

---

hal/src/main/native/athena/CANAPI.cpp
hal/src/main/native/sim/CANAPI.cpp

Currently, the call to `HAL_CAN_SendMessage` is not synchronized with updates to `periodicSends` (which represents the internal state of the netcomm sender thread). 
Now, the mutex is locked before `HAL_CAN_SendMessage` is called to ensure the update is atomic.
periodicSends and receives also now have their own mutexes to reduce unnecessary contention between send and receive functions.
Ex:
Thread A calls `HAL_StopCANPacketRepeating` with apiId 0
Thread B calls `HAL_WriteCANPacketRepeating` with apiId 0 and repeatMs 10
Inside `HAL_StopCANPacketRepeating`, Thread A calls `HAL_CAN_SendMessage`, which updates netcomm's state to not repeat the packet
Thread A is paused
Inside `HAL_WriteCANPacketRepeating`, Thread B calls `HAL_CAN_SendMessage`, which updates netcomm's state to repeat the …

[hal] Fix potential race in CANAPI

---

apriltag/CMakeLists.txt
apriltag/build.gradle

[build] Remove invalid MSVC warning suppression in apriltag

---

.github/workflows/tools.yml

It won't add them to PRs anyway because it doesn't have permissions, but the check run gets added to a random workflow in non-pr builds

disable check run and comments for robotbuilder ci

---

hal/src/main/native/sim/HAL.cpp

By default on Windows 11, power throttling will increase timer resolution if a window is occluded.  Disable that behavior.  Also enable high QOS to achieve maximum performance and turn off power saving.
Also use internal APIs to set timer precision to 500 us if available.

[hal] Windows sim: enable HighQoS and honor timer resolution requests

---

.gitignore

Running wpilibjExamples tests was writing a .bck file. Ignore this file.

Ignore .bck files it git

---

wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/commands/CloseClaw.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Drivetrain.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Elevator.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/cpp/subsystems/Wrist.cpp
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Elevator.h
wpilibcExamples/src/main/cpp/examples/GearsBot/include/subsystems/Wrist.h

the macro hasn't been used/available in a *long* time, and some usages of it were Broken.

[examples] Replace usages of SIMULATION macro with constexpr if

---

wpimath/src/main/native/include/units/base.h

If fmt isn't available/is disabled and iostream is not enabled UNIT_ADD_IO won't be defined

[units] Add default case for UNIT_ADD_IO

---

wpilibc/src/main/native/include/frc/IterativeRobotBase.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/IterativeRobotBase.java

The function no longer flushes to network like it did originally, and users generally would not want to disable flushing locally.

[wpilib] Deprecate setNetworkTablesFlushEnabled

---

hal/src/main/native/sim/DIO.cpp
hal/src/main/native/sim/DigitalInternal.h
wpilibc/src/main/native/cpp/DigitalGlitchFilter.cpp
wpilibc/src/main/native/include/frc/DigitalGlitchFilter.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DigitalGlitchFilter.java

fixes #6402 
Fixes error when >3 are constructed- in java, `m_filterAllocated[index]` would be evaluated before the bounds check and throw IndexOutOfBounds, in c++ a vague assertion error would be thrown.
Makes `DoAdd` static in c++
Makes the error message when `HAL_SetFilterSelect` fails consistent with java

[wpilib, hal] DigitalGlitchFilter: Fix sim crash and clean up construction 

---

wpiutil/src/main/java/edu/wpi/first/util/RuntimeDetector.java

It was used by multiple libraries and should have a deprecation cycle.
2027 seems the appropriate time to remove, as it would need updates for new robot controller, and seems unlikely to need updates before then.

Restore & deprecate RuntimeDetector

---

apriltag/CMakeLists.txt
apriltag/build.gradle
cscore/CMakeLists.txt
hal/CMakeLists.txt
wpimath/CMakeLists.txt
wpinet/CMakeLists.txt
wpiutil/CMakeLists.txt

Also removes the thirdparty AprilTag source directory from both CMake and Gradle's header setup.

[build] CMake: consolidate and clean up include dirs

---

cscore/src/main/java/edu/wpi/first/cscore/OpenCvLoader.java

On some Linux systems, installing the OpenCV package will actually install a debug version with a `d` postfix. Try loading that version if the first load attempt failed.

[cscore] Try loading debug OpenCV if release version fails

---

wpimath/src/main/java/edu/wpi/first/math/MatBuilder.java

[wpimath] Remove deprecated MatBuilder constructor

---

docs/build.gradle
shared/javacpp/publish.gradle

Fixes #6962
Don't specially include ntcore generated files from build directory in doxygen, as they are now pregenerated in source

[build] Publish source and headers of all generated files

---

.github/workflows/upstream-utils.yml
upstream_utils/README.md
upstream_utils/upstream_utils.py

The new upstream_utils command-line API has been nice, but the copy-upstream-to-thirdparty command has been annoying to type. Since it already has documentation, we can shorten it to make it easier to remember and type.

[upstream_utils] Shorten file copy command

---

wpilibc/src/main/native/cpp/simulation/SendableChooserSim.cpp
wpilibc/src/main/native/include/frc/simulation/SendableChooserSim.h
wpilibc/src/test/native/cpp/smartdashboard/SendableChooserTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/SendableChooserSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/smartdashboard/SendableChooserTest.java

A continuation of #6252, resolves #3731.

[sim] Add SendableChooserSim

---

hal/src/main/java/edu/wpi/first/hal/REVPHFaults.java
hal/src/main/java/edu/wpi/first/hal/REVPHStickyFaults.java
hal/src/main/native/include/hal/REVPH.h
wpilibc/src/main/native/include/frc/PneumaticHub.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLEDBufferView.java

Fix various typos

---

cscore/src/main/native/include/cscore_raw.h
docs/build.gradle
ntcore/src/generate/main/native/include/networktables/Topic.inc.jinja
ntcore/src/generated/main/native/include/networktables/BooleanArrayTopic.inc
ntcore/src/generated/main/native/include/networktables/BooleanTopic.inc
ntcore/src/generated/main/native/include/networktables/DoubleArrayTopic.inc
ntcore/src/generated/main/native/include/networktables/DoubleTopic.inc
ntcore/src/generated/main/native/include/networktables/FloatArrayTopic.inc
ntcore/src/generated/main/native/include/networktables/FloatTopic.inc
ntcore/src/generated/main/native/include/networktables/IntegerArrayTopic.inc
ntcore/src/generated/main/native/include/networktables/IntegerTopic.inc
ntcore/src/generated/main/native/include/networktables/RawTopic.inc
ntcore/src/generated/main/native/include/networktables/StringArrayTopic.inc
ntcore/src/generated/main/native/include/networktables/StringTopic.inc
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h
wpimath/src/main/native/include/frc/fmt/Eigen.h
wpiutil/src/main/native/include/wpi/jni_util.h

Resolves https://github.com/wpilibsuite/allwpilib/issues/6221

Fix Doxygen warnings for C++ code

---

cmake/modules/WpiProtobuf.cmake
wpimath/CMakeLists.txt

The hacks we needed to do to get the existing commands required cmake 3.28. We didn't want that, so just make a local slimmed down copy of the function just for our use. Even better, its much simpler in what it does, no weird hacks.

Include our own copy of protobuf_generate to use with plugin

---

upstream_utils/apriltag.py
upstream_utils/eigen.py
upstream_utils/fmt.py
upstream_utils/gcem.py
upstream_utils/glfw.py
upstream_utils/libuv.py
upstream_utils/protobuf.py

On windows those paths would be `.\foobar` and wouldn't match

[upstream_utils] use os path separator when matching path

---

wpilibc/src/generate/main/native/cpp/simulation/hidsim.cpp.jinja
wpilibc/src/generated/main/native/cpp/simulation/PS4ControllerSim.cpp
wpilibc/src/generated/main/native/cpp/simulation/PS5ControllerSim.cpp
wpilibc/src/generated/main/native/cpp/simulation/XboxControllerSim.cpp

Forgot to add these for C++. Fixes #7004.

[wpilibc] Add missing deprecated HID sim methods

---

datalogtool/publish.gradle
glass/publish.gradle
outlineviewer/publish.gradle
processstarter/publish.gradle
roborioteamnumbersetter/publish.gradle
shared/config.gradle
sysid/publish.gradle

The prefix has been unused for about 5 years (unused since wpilibsuite/build-tools#74).

[build] Remove redundant `_M_` prefix from artifact file name

---

hal/src/main/native/include/hal/simulation/SimDataValue.h

The issue also occurs in GCC <12 if the provided function is not constexpr. 
The suggested C++20 fix does not work due to another GCC bug, fixed in GCC 14 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70413)

Correct warning suppression and note in SimDataValue.h

---

wpilibcExamples/CMakeLists.txt

Also prefix example test targets with Example_ to make running tests easier

[build] cmake: Add meta target for examples and example tests

---

cmake/modules/CompileWarnings.cmake

4324 is issued at /W4 if alignas forces padding. Makes it impossible to use SmallVector from something compiled in /W4. Add it to the warning exclusion list.

Add 4324 to ignored warnings in cmake

---

upstream_utils/expected.py
wpiutil/src/main/native/thirdparty/expected/include/wpi/expected

Previously, both `wpi/expected` and JSON's `cpp_future.h` would define `enable_if_t` and `conjunction` in `wpi::detail`, leading to conflicts if both were included in the same cpp source file. By renaming the namespace `wpi/expected` uses, there is no longer a conflict.
Alternative to #7044 which should avoid needing any manual intervention when updating.

Rename expected's detail namespace to detail_expected

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/EpilogueGenerator.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/EpilogueGeneratorTest.java

Currently, users can only invoke Epilogue via `Epilogue.bind(TimedRobot)`. This PR adds a new method `Epilogue.update(TimedRobot)` so that Epilogue can manually called, in case a user is seeking more deterministic timing of their logs in reference to their control loops.

[epilogue] Add Epilogue.update()

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/AnalogEncoder.java

configureRolloverCounting was added and removed as part of the absolute encoder overhaul, this reference was left dangling

[wpilibj] AnalogEncoder: fix documentation

---

.github/workflows/cmake.yml
.github/workflows/sanitizers.yml

Supercedes #7025 
The GHA cache is not sufficient for the amount of data the cmake jobs are caching. Its eviction policy allows PR builds to evict entries from main, and PR caches can only be read by that PR, which results in even more thrashing as later PRs miss the cache and store their own entries.
This should work as-is- it's set up with the same user gradle uses, and is pointed at the `wpilib-generic-cache-cmake` repository.
Sccache won't continue trying to write if it doesn't have write access (PR builds).
There is one caveat- if for some reason artifactory is inaccessible when the sccache server starts for the first time, the build will fail. For some reason sccache doesn't allow graceful failure at startup.

[ci] Use artifactory for sccache backend

---

ntcore/src/dev/native/cpp/main.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h

The unpublish message must be sent on the outgoing queue before the handle indicating which queue to use is erased.
Related to #6734 (client side).

[ntcore] Fix client unpublish outgoing queue

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp

We emitted a warning but went on to do unsafe things.  This could cause a delayed crash.
Fixes #6734.

[ntcore] Avoid duplicate addition of publishers in server

---

.github/workflows/cmake.yml
.github/workflows/sanitizers.yml

Artifactory only allows WebDAV methods on local repositories, and does not allow MKCOL on the repository root.

Fix CMake caching to Artifactory

---

ntcoreffi/src/main/native/cpp/DataLogManager.cpp
ntcoreffi/src/main/native/include/DataLogManager.h
ntcoreffi/src/main/native/symbols.txt
wpilibc/src/main/native/cpp/DataLogManager.cpp
wpilibc/src/main/native/include/frc/DataLogManager.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DataLogManager.java
wpiutil/src/main/java/edu/wpi/first/util/FileLogger.java
wpiutil/src/main/java/edu/wpi/first/util/WPIUtilJNI.java
wpiutil/src/main/native/cpp/FileLogger.cpp
wpiutil/src/main/native/cpp/jni/WPIUtilJNI.cpp
wpiutil/src/main/native/include/wpi/FileLogger.h
wpiutil/src/test/native/cpp/FileLoggerTest.cpp

[wpiutil, wpilib] Add FileLogger and log console output

---

apriltag/src/main/native/cpp/AprilTagFieldLayout.cpp
cameraserver/multiCameraServer/src/main/native/cpp/main.cpp
datalogtool/src/main/native/cpp/Exporter.cpp
glass/src/lib/native/cpp/Context.cpp
glass/src/lib/native/cpp/other/Field2D.cpp
hal/src/main/native/athena/HAL.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
simulation/halsim_ws_server/src/main/native/cpp/HALSimHttpConnection.cpp
sysid/src/main/native/cpp/analysis/AnalysisManager.cpp
sysid/src/main/native/cpp/view/LogLoader.cpp
wpimath/src/main/native/cpp/trajectory/TrajectoryUtil.cpp
wpiutil/build.gradle
wpiutil/examples/printlog/printlog.cpp
wpiutil/src/main/native/thirdparty/llvm/cpp/llvm/MemoryBuffer.cpp
wpiutil/src/main/native/thirdparty/llvm/include/wpi/MemoryBuffer.h

Closes #7036.
I'm not completely happy with the idiom I went with, but I think it works relatively well. If anyone has suggestions for a cleaner one, I'd be happy to hear it!
Also, I'm a little worried about how long the `GetFile()` declaration line is in the header file, but it's excluded from format so I'm not sure what to do.

[wpiutil] Use wpi::expected in MemoryBuffer::GetFile

---

wpiutil/src/main/native/thirdparty/llvm/include/wpi/StringExtras.h

```
warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
```

Fix warning on msvc in parse_integer

---

wpilibc/src/main/native/include/frc/DoubleSolenoid.h
wpilibc/src/main/native/include/frc/Solenoid.h
wpilibc/src/main/native/include/frc/simulation/SolenoidSim.h

Relic from when SolenoidBase existed

[wpilibc] Solenoid classes: Make methods non-virtual

---

shared/java/javacommon.gradle

Instead of hardcoding to use the project name after `edu_wpi_first_`, which broke epilogue publishing. Both projects publish to the `edu.wpi.first.epilogue` group ID, instead of the `edu.wpi.first.epilogue-processor/runtime` group IDs that were computed by the build script.
This bug did not affect local maven publishing, since those tasks do not use those specially named and configured artifacts

Use project configured groupId in generated output artifact names

---

wpilibc/src/main/native/cpp/ADIS16448_IMU.cpp
wpilibc/src/main/native/cpp/ADIS16470_IMU.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16448_IMU.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

They were removed in #6719, but I've since realized that the null checks prevented crashes when the IMUs were disconnected, so I'm adding them back in.

[wpilib] ADIS IMUs: Add back null checks

---

.github/workflows/comment-command.yml
.github/workflows/pregen_all.py
.github/workflows/pregenerate.yml

A pregen_all Python script was added that calls all the other pregen scripts. This prevents the generated file checks and pregen command from falling out of sync. This is meant to only run in CI, since the script is not portable across platforms.

[ci] Use one script to pregenerate everything

---

wpimath/src/main/java/edu/wpi/first/math/system/plant/DCMotor.java
wpimath/src/main/native/include/frc/system/plant/DCMotor.h

This adds an overload to the `DCMotor::Current()` API to get motor current from torque output.
`DCMotor` already had an API to do the reverse (get torque output from motor current), as well as an API to get motor current from voltage and velocity.

Add `DCMotor::Current()` overload accepting torque

---

wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui.h
wpigui/src/main/native/include/wpigui_internal.h

Droid Sans example:
Fixes #5214 (except for changing the default, we can wait on that)

[wpigui] Add font selector

---

wpilibc/src/main/native/cpp/DigitalOutput.cpp
wpilibc/src/main/native/cpp/LEDPattern.cpp
wpilibc/src/main/native/cpp/SensorUtil.cpp
wpilibc/src/main/native/include/frc/LEDPattern.h
wpilibc/src/main/native/include/frc/SensorUtil.h

Resolves https://github.com/wpilibsuite/allwpilib/issues/7139

[wpilibc] Fix missing symbols on Windows

---

wpiutil/src/main/native/cpp/DataLogBackgroundWriter.cpp

An empty path isn't valid on it's own, so fs::space always returns an error. This results in `UINT_MAX_MAX` bytes being used instead of the actual free space, which means a default constructed DataLogBackgroundWriter won't stop for low space.
```DataLog: Logging to 'wpilog_4fbdb51d975c52e7.wpilog' (17179869184.0 GiB free space)```
Using "." instead makes the directory path the current working directory, which is the desired behavior

DataLogBackgroundWriter: Normalize empty path name

---

.github/workflows/cmake.yml

Apparently, a workflow file being invalid silently removes the check instead of reporting a failure.
Broken in #7153, the strategy key does not have access to the runner context. vcpkg also needs to be configured after checkout.

[ci] Fix cmake CI

---

wpiunits/generate_units.py
wpiunits/src/generate/main/java/Measure-interface.java.jinja
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Velocity.java
wpiunits/src/test/java/edu/wpi/first/units/measure/VelocityTest.java

Update code generator to allow arbitrary implementations of multiplication methods

[wpiunits] Make Velocity.mult(Time) return Measure<D>

---

wpilibc/src/main/native/include/frc/Alert.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/Alert.java

Console printing was removed when Alerts were added to wpilib.

[docs] Alert: fix incorrect `set` docs (NFC)

---

wpiutil/src/main/native/cpp/FileLogger.cpp
wpiutil/src/main/native/include/wpi/FileLogger.h
wpiutil/src/test/native/cpp/FileLoggerTest.cpp

FileLogger now logs entire flushed blocks of data, instead of breaking it up into lines.
Fixes #7135.

[wpiutil] Refactor FileLogger

---

ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.h

The stream can close (e.g. due to an error) while in the middle of writing.  The close callback would immediately destroy the connection object, resulting in the writing code having a use-after-free.  Fix this by deferring the deletion to the loop main using a single-shot timer.

[ntcore] Fix use-after-free on connection termination

---

wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveDriveKinematics.java
wpimath/src/main/native/include/frc/kinematics/SwerveDriveKinematics.inc

Introduced in #6767, `ToSwerveModuleStates` will emit an error when calculating a module's angle if its velocity is 0. This PR adds a preemptive check for a non-zero velocity, otherwise substituting the module's last heading.

[wpimath] SwerveDrivePoseEstimator: Fix stationary module emitting error when calculating angle in ToSwerveModuleStates

---

hal/src/main/native/athena/CTREPCM.cpp
hal/src/main/native/athena/CTREPDP.cpp
hal/src/main/native/athena/REVPDH.cpp
hal/src/main/native/athena/REVPH.cpp
hal/src/main/native/sim/CTREPCM.cpp
hal/src/main/native/sim/PowerDistribution.cpp
hal/src/main/native/sim/REVPH.cpp

REV: 1-63, 63 devices
CTRE: 0-62, 63 devices
One of the checks for each could also be removed- the resource containers also check the range.

Fix CAN ID validation and reporting for CTRE and REV devices

---

wpilibcExamples/src/test/cpp/examples/ArmSimulation/cpp/ArmSimulationTest.cpp
wpilibjExamples/src/test/java/edu/wpi/first/wpilibj/examples/armsimulation/ArmSimulationTest.java

Fixes issue #5908 
It seems that all of the checks were for the default arm position in the Preferences class instead of the current setpoint
The checks at the beginning of `teleopTest `were if the two keys were in the Preferences class and then checking if the arm position key was set to the default.  Then the preferences key was set to the setpoint.  I'm amazed the test didn't fail more often.  I guess it could on other systems.  I feel like the intended behavior was to check after the key was set to the tested setpoint if the preferences value contained that value before continuing.  That is basically the change I made here.  I also noticed some commenting issues.  It look like this class was originally a duplicate of the `ElevatorSimulationTest `which doesn't have this problem.  The …

[examples] fix flaky ArmSimulationTest

---

wpiutil/src/main/native/include/wpi/rotated_span.h
wpiutil/src/test/native/cpp/rotated_span_test.cpp

[wpiutil] Add rotated_span

---

wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/cpp/subsystems/Drive.cpp
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/Constants.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Drive.h
wpilibcExamples/src/main/cpp/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/Constants.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Drive.java

Replaces the GyroDriveCommands example. Closes #3114.

[examples] Add ProfiledPID command to RapidReactCommandBot

---

wpiutil/.styleguide
wpiutil/src/main/native/include/wpi/FastQueue.h
wpiutil/src/test/native/cpp/FastQueueTest.cpp

This is a heavily modified version of https://github.com/cameron314/readerwriterqueue that removes all atomics and barriers.
The name isn't great, not sure what a better option would be though.

[wpiutil] Add FastQueue

---

ntcore/src/main/native/cpp/Handle.h
ntcore/src/main/native/cpp/LocalStorage.cpp
ntcore/src/main/native/cpp/LocalStorage.h
ntcore/src/main/native/cpp/NetworkClient.cpp
ntcore/src/main/native/cpp/NetworkServer.cpp
ntcore/src/main/native/cpp/net/ClientImpl.cpp
ntcore/src/main/native/cpp/net/ClientImpl.h
ntcore/src/main/native/cpp/net/Message.h
ntcore/src/main/native/cpp/net/NetworkInterface.h
ntcore/src/main/native/cpp/net/NetworkLoopQueue.cpp
ntcore/src/main/native/cpp/net/NetworkLoopQueue.h
ntcore/src/main/native/cpp/net/NetworkLoopQueue.inc
ntcore/src/main/native/cpp/net/NetworkOutgoingQueue.h
ntcore/src/main/native/cpp/net/ServerImpl.cpp
ntcore/src/main/native/cpp/net/ServerImpl.h
ntcore/src/main/native/cpp/net/WireDecoder.cpp
ntcore/src/main/native/cpp/net/WireDecoder.h
ntcore/src/main/native/cpp/net/WireEncoder.cpp
ntcore/src/main/native/cpp/net/WireEncoder.h
ntcore/src/main/native/cpp/net3/ClientImpl3.cpp
ntcore/src/main/native/cpp/net3/ClientImpl3.h
ntcore/src/test/native/cpp/LocalStorageTest.cpp
ntcore/src/test/native/cpp/net/MockNetworkInterface.h
ntcore/src/test/native/cpp/net/ServerImplTest.cpp
ntcore/src/test/native/cpp/net/WireDecoderTest.cpp
ntcore/src/test/native/cpp/net/WireEncoderTest.cpp

Also make Handle functions constexpr.

[ntcore] Change internal interfaces and messages to use UIDs

---

glass/src/libnt/native/cpp/NetworkTables.cpp

This avoids a potential divide by 0.

[glass] Check for struct descriptor size 0

---

ntcore/src/main/native/cpp/NetworkClient.cpp

The server only binds to IPv4, so connection attempts via IPv6 are useless.

[ntcore] Client: only connect to IPv4 addresses

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/PIDSubsystem.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/ProfiledPIDSubsystem.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/TrapezoidProfileSubsystem.java
wpilibNewCommands/src/main/native/cpp/frc2/command/PIDCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/PIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/PIDSubsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/ProfiledPIDSubsystem.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileCommand.h
wpilibNewCommands/src/main/native/include/frc2/command/TrapezoidProfileSubsystem.h

Resolves #5352, closes #5067, depends on #7054.

[cmd] Deprecate control commands and subsystems

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysid/subsystems/Drive.java

Intellisense / copy pasta grabbed an improper import which the current build tools do not detect, but bazel did (for a while, forgot to make the PR)

[examples] Fix cross project import

---

ntcore/src/main/native/cpp/LocalStorage.cpp

The changes in #7189 caused an ambiguity between multi-subscribers and normal subscribers, because the handle type no longer is sent to the network.
Multi-subscribers now go to the network with negative UIDs, normal subscribers are positive UIDs.  UID 0 is never used.

[ntcore] Fix UID collisions between subscribers and multi-sub

---

sysid/src/main/native/cpp/analysis/FilteringUtils.cpp

Fixes #6438.
Here's what the error screen looks like when trying to load the log in the issue:
A bunch of the UI elements aren't present, but I think that's fine here since analysis isn't possible. The plot in the background is from a previous analysis.

[sysid] Fix crash when all data is filtered out during analysis

---

cscore/src/main/native/cpp/HttpCameraImpl.cpp
cscore/src/main/native/cpp/UnlimitedHandleResource.h
hal/src/main/native/include/hal/simulation/SimCallbackRegistry.h
hal/src/main/native/sim/HAL.cpp

Remove VS 2019 16.4.0 workaround

---

wpilibc/src/main/native/cpp/Counter.cpp
wpilibc/src/main/native/cpp/DigitalOutput.cpp
wpilibc/src/main/native/cpp/PWM.cpp
wpilibc/src/main/native/cpp/Relay.cpp
wpilibc/src/main/native/cpp/TimedRobot.cpp

Moved-from objects have invalid handles.
I *think* that's everything that uses a handle and does something with it in the destructor.

[wpilibc] Check for invalid handle in destructors (pt 2)

---

glass/src/lib/native/cpp/other/Field2D.cpp

Aligns the yellow border and the image for the Field2d widget when using a custom image without JSON.
Potential fix for #7211 
Before: 
After:

[glass] Align Field2d border and image padding for custom images

---

hal/src/main/native/include/hal/I2CTypes.h
hal/src/main/native/include/hal/SPITypes.h
wpilibc/src/main/native/cpp/SPI.cpp
wpilibc/src/main/native/include/frc/I2C.h
wpilibc/src/main/native/include/frc/SPI.h

This was overlooked by mistake in #7016. The destructors were removed but the handle wrappers didn't handle closing the ports.

[wpilibc] SPI & I2C: Use handle wrapper to close port

---

glass/src/lib/native/cpp/other/Alerts.cpp
glass/src/lib/native/include/glass/other/Alerts.h
glass/src/libnt/native/cpp/NTAlerts.cpp
glass/src/libnt/native/cpp/StandardNetworkTables.cpp
glass/src/libnt/native/include/glass/networktables/NTAlerts.h

This adds a widget to Glass for the Alerts published with https://github.com/wpilibsuite/allwpilib/blob/main/wpilibj/src/main/java/edu/wpi/first/wpilibj/Alert.java.
Currently the types of messages are distinguished by a label and by color. I think it would be nice to add icons like this:
https://raw.githubusercontent.com/Mechanical-Advantage/NetworkAlerts/main/example.png
The icons would be nice to make it more obvious and be helpful for people with color blindness. I'm not sure what the best way to do that is, so I would appreciate help with it.

[glass] Add Alerts widget

---

cameraserver/build.gradle
cscore/build.gradle
glass/build.gradle
hal/build.gradle
ntcore/build.gradle
romiVendordep/build.gradle
wpigui/build.gradle
wpilibNewCommands/build.gradle
wpilibc/build.gradle
wpimath/build.gradle
wpinet/build.gradle
wpiutil/build.gradle
xrpVendordep/build.gradle

As part of #6979, the symbol exporter in native-utils was updated and stopped exporting the excluded symbols.

[build] Remove unnecessary symbol exclusions

---

wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java
wpimath/src/main/native/include/frc/estimator/PoseEstimator.h
wpimath/src/test/java/edu/wpi/first/math/estimator/DifferentialDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/MecanumDrivePoseEstimatorTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/SwerveDrivePoseEstimatorTest.java
wpimath/src/test/native/cpp/estimator/DifferentialDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/SwerveDrivePoseEstimatorTest.cpp

Looks like #6751 wasn't properly updated against #6705.

[wpimath] Fix pose estimator reset methods

---

wpiutil/src/main/native/include/wpi/circular_buffer.h
wpiutil/src/main/native/include/wpi/static_circular_buffer.h

The circular buffer class that uses std::vector internally can be used in a constant expression as long as it doesn't survive to runtime.

[wpiutil] Make circular buffer classes constexpr

---

wpilibc/src/main/native/cpp/DataLogManager.cpp

[wpilibc] DLM: Rename console log entry to "console"

---

wpimath/src/main/native/cpp/estimator/DifferentialDrivePoseEstimator.cpp
wpimath/src/main/native/cpp/estimator/MecanumDrivePoseEstimator.cpp
wpimath/src/main/native/include/frc/estimator/PoseEstimator.h
wpimath/src/main/native/include/frc/estimator/SwerveDrivePoseEstimator.h
wpimath/src/test/native/cpp/estimator/DifferentialDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/MecanumDrivePoseEstimatorTest.cpp
wpimath/src/test/native/cpp/estimator/SwerveDrivePoseEstimatorTest.cpp

Prior to this change, because the base class (`PoseEstimator`) constructor was run before the derived class (e.g., `DifferentialDrivePoseEstimator`) constructor, `m_poseEstimate` would be initialized with `m_odometry.GetPose()` before `m_odometry` was actually initialized. Don't know how this passed asan...
I'm not sure if we should change Java as well, since this part of the initialization already differs.

[wpimath] Fix C++ pose estimator poseEstimate initialization

---

datalogtool/src/main/native/cpp/Sftp.cpp
datalogtool/src/main/native/cpp/Sftp.h
roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp

```
/home/tav/frc/wpilib/allwpilib/roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp: In member function ‘void rtns::SshSession::Execute(std::string_view)’:
/home/tav/frc/wpilib/allwpilib/roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp:89:44: warning: ‘int ssh_channel_get_exit_status(ssh_channel)’ is deprecated [-Wdeprecated-declarations]
89 |   INFO("{} {}", ssh_channel_get_exit_status(channel), cmd);
|                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
```
```
/home/tav/frc/wpilib/allwpilib/roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp:139:44: warning: ‘int ssh_channel_get_exit_status(ssh_channel)’ is deprecated [-Wdeprecated-declarations]
139 |   INFO("{} {}", ssh_channel_get_exit_status(channel), cmd);
| …
```

Fix libssh deprecation warnings

---

cscore/src/main/native/include/cscore_oo.h

[cscore] Add back VideoProperty handle member initializer

---

CMakeLists.txt
cmake/modules/AddDoxygenDocs.cmake

The output is slightly better than Gradle's because it properly strips the paths to the thirdparty headers. This is the first step to unblocking #7164. The next would be to have Gradle package up the docs into a zip file.
Before:
After:

[build] CMake: add Doxygen doc generation

---

ntcore/src/main/native/cpp/net/ServerImpl.cpp

This way all NT3 clients are not identified as just NT3

Use NT3 client identity in front of unique id

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java

Add Java unit support for RobotController

---

.github/workflows/pregen_all.py

Previously errors were ignored
Also makes the script more cross-platform by using the current python executable to run the subprocesses

[ci] Check return code of subprocesses in pregen_all

---

wpilibc/src/generate/main/native/include/frc/hid.h.jinja
wpilibc/src/generate/main/native/include/frc/simulation/hidsim.h.jinja
wpilibc/src/generated/main/native/include/frc/PS4Controller.h
wpilibc/src/generated/main/native/include/frc/PS5Controller.h
wpilibc/src/generated/main/native/include/frc/StadiaController.h
wpilibc/src/generated/main/native/include/frc/XboxController.h
wpilibc/src/generated/main/native/include/frc/simulation/PS4ControllerSim.h
wpilibc/src/generated/main/native/include/frc/simulation/PS5ControllerSim.h
wpilibc/src/generated/main/native/include/frc/simulation/XboxControllerSim.h
wpilibj/src/generate/main/java/hid.java.jinja
wpilibj/src/generate/main/java/hidsim.java.jinja
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS5Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/StadiaController.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/XboxController.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/simulation/PS4ControllerSim.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/simulation/PS5ControllerSim.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/simulation/XboxControllerSim.java

Based on feedback that some deprecations seemed to be done for no reason.
This is probably something we should start doing more generally.

[wpilib] Add explanation for HID GetBumper/Touchpad deprecations

---

.github/workflows/gradle.yml
.github/workflows/sentinel-build.yml

The 1 hour timeout is likely causing the occasional hang in macos signing. If the keychain times out before the signing is complete, signing will hang. Setting the keychain timeout to 6 hours will guarantee that this doesn't happen.

[macos build] Increase keychain timeout to 6 hours

---

wpiunits/generate_units.py

Makes wpiunits more consistent with the other generation scripts, since wpiunits was overhauled after #6745
Depends on #7308

[build] Use pathlib in wpiunits generation script

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/ElementHandler.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/LoggerGenerator.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/StringUtils.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/StringUtilsTest.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/Logged.java

eg "getFoo()" will now be logged as "Foo", or "m_leftMotor" as "Left Motor"
It is now a compilation error to reuse the same logged name for multiple elements (since whatever is declared last would overwrite anything logged before it)
Do not log record fields (just use the accessors). This also fixes an issue where records could never be logged due to identical member and accessor names
Also skips `toString`, `hashCode`, and `clone` methods when generating loggers

[epilogue] Autogenerate nicer data names by default, not just raw element names

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/AnnotationProcessor.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/LoggableHandler.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java

Instead of only using the logger for the declared type, epilogue will now log objects based on their runtime type
Fixes #7093

[epilogue] Check for the most appropriate logger at runtime

---

.github/workflows/bazel.yml

setup-go is warning because it can't find go.sum, which we don't have.

[ci] Disable caching for setup-go

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/main/native/include/frc2/command/CommandScheduler.h
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulerTest.cpp

Previously users would have to keep track of dynamically created CommandPtrs. This adds an ownership-taking version of schedule which places the command in a temporary store in the scheduler. The command will be freed when the command's lifecycle ends.

[c++ cmd] Allow CommandPtrs to be owned by the scheduler

---

.github/workflows/pregen_all.py
hal/generate_usage_reporting.py
ntcore/generate_topics.py
thirdparty/imgui_suite/generate_gl3w.py
upstream_utils/upstream_utils.py
wpilibNewCommands/generate_hids.py
wpilibc/generate_hids.py
wpilibc/generate_pwm_motor_controllers.py
wpilibj/generate_hids.py
wpilibj/generate_pwm_motor_controllers.py
wpimath/generate_numbers.py
wpimath/generate_quickbuf.py
wpiunits/generate_units.py

argparse will automatically read sys.argv, so we don't need to pass it in manually. Furthermore, none of our scripts customize argv.

Remove argv usage from Python scripts

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/LoggableHandler.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java

Fixes an issue where the variable names would clash with the field names of the associated VarHandles

[epilogue] Generate unique names for variables used in instanceof chains

---

glass/src/lib/native/cpp/Storage.cpp
glass/src/lib/native/include/glass/Storage.h

This reverts commit 309b370223e0e6db5197ec84417f18250868b23f.
Storage::GetChildArray never initializes the child array when the entry is new, so it returns invalid references.

Revert "[glass] Storage: Store Value by value"

---

wpiutil/src/main/java/edu/wpi/first/util/struct/StructDescriptor.java
wpiutil/src/main/java/edu/wpi/first/util/struct/StructFieldDescriptor.java
wpiutil/src/main/native/include/wpi/struct/DynamicStruct.h
wpiutil/src/test/java/edu/wpi/first/util/struct/DynamicStructTest.java
wpiutil/src/test/native/cpp/struct/DynamicStructTest.cpp

closes https://github.com/wpilibsuite/2025Beta/issues/25
After a struct-type field descriptor had offsets calculated once, IsBitField would return true, causing future calls to CalculateOffsets to calculate different, incorrect offsets.

Fix dynamic struct decoding for nested structs

---

wpimath/src/test/java/edu/wpi/first/math/controller/BangBangInputOutputTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/BangBangToleranceTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/PIDInputOutputTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/ProfiledPIDInputOutputTest.java
wpimath/src/test/native/cpp/controller/BangBangInputOutputTest.cpp
wpimath/src/test/native/cpp/controller/BangBangToleranceTest.cpp
wpimath/src/test/native/cpp/controller/PIDInputOutputTest.cpp
wpimath/src/test/native/cpp/controller/ProfiledPIDInputOutputTest.cpp

These test fixtures were adding complexity while only saving one line of object initialization per test. Our other tests like this just make the object at the top of each test.

[wpimath] Remove unhelpful test fixtures

---

wpimath/src/main/native/cpp/controller/PIDController.cpp

Almost all of the C++ getters added in #7088 weren't implemented correctly.

[wpimath] Fix PIDController error tolerance getters

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/WrapperCommand.java
wpilibNewCommands/src/main/native/cpp/frc2/command/WrapperCommand.cpp
wpilibNewCommands/src/main/native/include/frc2/command/WrapperCommand.h

Closes #7352
This reverts commit 7bc0380694916fdb0082c6a746d1d937d6258c03.
Calling initSendable on the wrapped command is fundamentally flawed as the wrapper is the command being sent.

[cmd] Revert "Call wrapped command initSendable (#6471)"

---

wpiutil/CMakeLists.txt

Protobuf.cpp only uses nanopb, which is fine to have even with WITH_PROTOBUF off.

Fix cmake build with WITH_PROTOBUF off

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/RobotController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DCMotorSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/FlywheelSim.java
wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/ElevatorFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.java

It only saves a single allocation and can cause confusing behavior on the caller (user) side.

[wpilib,wpimath] Don't use mutable units for return values

---

wpinet/src/main/native/macOS/ResolverThread.cpp

Implicit capture of this is deprecated, so fix it

Fix resolver thread on newer versions of macOS

---

wpinet/CMakeLists.txt
wpinet/examples/dsclient/dsclient.cpp
wpinet/examples/parallelconnect/parallelconnect.cpp
wpinet/examples/webserver/webserver.cpp
wpiutil/src/main/native/unix/StackTrace.cpp

Stacktrace isn't supported until SDK 33, which is pretty new. For now just comment out stacktrace and we can figure this out later.
The other changes are more trivial.

Allow compilation on android

---

CMakeLists.txt

It was leftover from the failed protoc stuff

Remove java requirement from cmake

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/TrapezoidProfile.java

They were assuming inputs were always going to be in SI units, which is not the case

[wpimath] Remove units from trapezoid profile classes

---

wpimath/build.gradle

PhotonVision depends on these being in the JAR to generate quickbuf classes.

[wpimath] Add proto files back to JAR

---

apriltag/src/main/java/edu/wpi/first/apriltag/AprilTagDetector.java
apriltag/src/test/java/edu/wpi/first/apriltag/AprilTagDetectorTest.java

Cropped images have stride != cols. However, AprilTagDetector assumed that stride == cols.

[apriltag] Fix AprilTagDetector cols/stride mixup

---

.github/workflows/gradle.yml
ntcoreffi/build.gradle
shared/config.gradle

NI has a hard time upgrading their MSVC runtime. The solution will be make their binary not require the static runtime

Use static runtime for 32 bit ntcoreffi

---

ThirdPartyNotices.txt
upstream_utils/debugging.py
upstream_utils/debugging_patches/0001-Guard-gnu-flatten-attribute.patch
upstream_utils/debugging_patches/0002-Remove-debugger_query-argument-from-Windows-and-macO.patch
upstream_utils/debugging_patches/0003-Fix-exception-mask-type-typo-on-macOS.patch
upstream_utils/debugging_patches/0004-Remove-NOMINMAX-macro-from-Windows.patch
upstream_utils/upstream_utils.py
wpiutil/BUILD.bazel
wpiutil/CMakeLists.txt
wpiutil/build.gradle
wpiutil/src/main/native/thirdparty/debugging/include/debugging.hpp
wpiutil/src/main/native/thirdparty/debugging/include/debugging/detail/psnip_debug_trap.h
wpiutil/src/main/native/thirdparty/debugging/src/linux.cpp
wpiutil/src/main/native/thirdparty/debugging/src/macos.cpp
wpiutil/src/main/native/thirdparty/debugging/src/windows.cpp
wpiutil/src/test/native/cpp/debugging/DebuggingTest.cpp

[upstream_utils] Add std::is_debugger_present() shim

---

wpiunits/src/generate/main/java/Measure-interface.java.jinja
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Acceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Angle.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Current.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Dimensionless.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Distance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Energy.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Force.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Frequency.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mass.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/MomentOfInertia.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mult.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Per.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Power.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Resistance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Temperature.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Time.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Torque.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Velocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Voltage.java
wpiunits/src/main/java/edu/wpi/first/units/Measure.java

It was changed to div in #7387, but 2024 used divide.

Restore and deprecate WPIUnits divide

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/LoggerGenerator.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/StringUtils.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java

```java
package foo;
class Outer {
@Logged
static class Inner {}
}
```
would attempt to generate a `foo/Outer/InnerLogger.java` file, where the `Outer` package name in the generated output would conflict with the `Outer` _class_ name in the user source
This fixes the issue by generating files like`foo/Outer$InnerLogger.java`
Resolves https://github.com/wpilibsuite/2025Beta/issues/54

[epilogue] Fix epilogue generating incorrect packages for inner classes

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/AnnotationProcessor.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/ConfiguredLoggerHandler.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java

This allows for custom loggers to be defined for generic types such as `Vector<?>`, and improves error messaging for generic logger types

[epilogue] Allow custom loggers for generic types

---

wpilibc/src/main/native/cpp/simulation/DCMotorSim.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DCMotorSim.java

The matrix variable was extracting the wrong row. It should be row index 1 and was row index 0.
Fixes #7448.

[wpimath] fix to acceleration getter for DCMotorSim

---

hal/src/generate/Instances.txt
hal/src/generated/main/java/edu/wpi/first/hal/FRCNetComm.java
hal/src/generated/main/native/include/hal/FRCUsageReporting.h
hal/src/generated/main/native/include/hal/UsageReporting.h
wpilibc/src/main/native/cpp/PowerDistribution.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/PowerDistribution.java

LabVIEW doesn't appear to report PDP. This should reduce the number of Unknowns in the parsed UsageReporting.

Change Power Distribution Usage Reporting to Instances

---

.github/workflows/lint-format.yml

The 2027 branch cannot run lint with the roborio compiler. So switch the lint task to just not use it.

Switch lint task to use base ubuntu image

---

.github/workflows/tools.yml

Roborio targets don't build anymore in 2027.

Build tools with systemcore image

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Rotation2d.java
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Rotation2dTest.java
wpimath/src/test/java/edu/wpi/first/math/kinematics/SwerveDriveKinematicsTest.java
wpimath/src/test/native/cpp/geometry/Rotation2dTest.cpp
wpimath/src/test/native/cpp/kinematics/SwerveDriveKinematicsTest.cpp

[wpimath] Remove rotation2d value field

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/MecanumControllerCommand.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/RamseteCommand.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdrivebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/differentialdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/drivedistanceoffboard/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorexponentialprofile/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatortrapezoidprofile/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/eventloop/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/flywheelbangbangcontroller/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Drive.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/rapidreactcommandbot/subsystems/Shooter.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/simpledifferentialdrivesimulation/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/SwerveModule.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/sysidroutine/subsystems/Shooter.java
wpimath/src/main/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.java
wpimath/src/main/native/include/frc/controller/SimpleMotorFeedforward.h
wpimath/src/test/java/edu/wpi/first/math/controller/SimpleMotorFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/trajectory/DifferentialDriveVoltageConstraintTest.java
wpimath/src/test/java/edu/wpi/first/math/trajectory/ExponentialProfileTest.java

Also roll back SimpleMotorFeedforward unit API until 2027.

[wpimath] Improve SimpleMotorFeedforward argument names and deprecation message

---

.github/workflows/tools.yml

Currently the systemcore compiler is the arm64 compiler. Native utils will pick this compiler up for both targets if its on PATH (It won't if its installed through gradlerio or in the wpilib folder). So for CI we need to skip linuxarm64 on the tools build to not run out of space.

Skip linux arm64 build on tools build

---

wpiutil/build.gradle

Replaces #7502 
We only need wpiutil to have the flag, as that will enable the msvc checks we added to work properly.

[build] Restore Windows constexpr mutex define on wpiutil

---

wpimath/src/main/java/edu/wpi/first/math/controller/LTVDifferentialDriveController.java
wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/cpp/controller/LTVDifferentialDriveController.cpp
wpimath/src/main/native/cpp/controller/LTVUnicycleController.cpp
wpimath/src/main/native/include/frc/controller/LTVDifferentialDriveController.h
wpimath/src/main/native/include/frc/controller/LTVUnicycleController.h

The Raspberry Pi 5 is fast enough that we no longer need it.
```
Running ./build/DAREBench
Run on (4 X 2400 MHz CPU s)
CPU Caches:
L1 Data 64 KiB (x4)
L1 Instruction 64 KiB (x4)
L2 Unified 512 KiB (x4)
L3 Unified 2048 KiB (x1)
Load Average: 0.47, 0.72, 0.45
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-------------------------------------------------------------------------------
Benchmark                                     Time             CPU   Iterations
-------------------------------------------------------------------------------
DARE_WPIMath_Dynamic                       34.4 us         34.4 us        20315
DARE_WPIMath_NoPrecondChecks_Dynamic       21.7 us         21.7 us        32266
DARE_WPIMath_Static …
```

[wpimath] Remove LUTs from LTV controllers

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Ellipse2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Rectangle2d.java
wpimath/src/main/java/edu/wpi/first/math/jni/Ellipse2dJNI.java
wpimath/src/main/native/cpp/geometry/Ellipse2d.cpp
wpimath/src/main/native/cpp/jni/Ellipse2dJNI.cpp
wpimath/src/main/native/include/frc/geometry/Ellipse2d.h
wpimath/src/main/native/include/frc/geometry/Rectangle2d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Ellipse2dTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Rectangle2dTest.java
wpimath/src/test/native/cpp/geometry/Ellipse2dTest.cpp
wpimath/src/test/native/cpp/geometry/Rectangle2dTest.cpp

This is easier to type and follows the naming of Pose2d::Nearest().
Since Ellipse2d and Rectangle2d were added for the 2025 season, we don't need to add deprecation notices.

[wpimath] Rename FindNearestPoint() to Nearest()

---

ntcore/src/main/native/cpp/net3/WireDecoder3.cpp
ntcore/src/main/native/cpp/net3/WireEncoder3.cpp
simulation/halsim_xrp/src/main/native/cpp/XRP.cpp
wpinet/src/netconsoleServer/native/cpp/main.cpp
wpinet/src/netconsoleTee/native/cpp/main.cpp
wpiutil/src/main/native/cpp/DataLog.cpp
wpiutil/src/main/native/cpp/DataLogReader.cpp

Blocked on upgrade past GCC 10 on Raspberry Pi.

Use std::bit_cast

---

upstream_utils/sleipnir.py
upstream_utils/sleipnir_patches/0002-Use-wpi-SmallVector.patch
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/optimization/OptimizationProblem.hpp
wpimath/src/main/native/thirdparty/sleipnir/include/sleipnir/optimization/solver/SQP.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/SQP.cpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/ErrorEstimate.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/FeasibilityRestoration.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/Filter.hpp
wpimath/src/main/native/thirdparty/sleipnir/src/optimization/solver/util/KKTError.hpp

It now uses SQP for problems without inequality constraints, which is faster.
main:
```
[ RUN      ] Ellipse2dTest.DistanceToPoint
0.203 ms
[       OK ] Ellipse2dTest.DistanceToPoint (0 ms)
[ RUN      ] Ellipse2dTest.FindNearestPoint
0.019 ms
[       OK ] Ellipse2dTest.FindNearestPoint (0 ms)
```
upgrade:
```
[ RUN      ] Ellipse2dTest.DistanceToPoint
0.197 ms
[       OK ] Ellipse2dTest.DistanceToPoint (0 ms)
[ RUN      ] Ellipse2dTest.FindNearestPoint
0.015 ms
[       OK ] Ellipse2dTest.FindNearestPoint (0 ms)
```

[upstream_utils] Upgrade Sleipnir

---

roborioteamnumbersetter/src/main/native/cpp/SshSession.cpp

This should fix https://github.com/wpilibsuite/2025Beta/issues/71. Unfortunately I don't have a way to test that it does, but it is clearly a bug and would cause the problem observed.

roborioteamnumbersetter: capture exitCode from ssh_channel_get_exit_status

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticHub.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/PneumaticsControlModule.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/CounterTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/DIOCrossConnectTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PDPTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/PIDTest.java
wpilibjIntegrationTests/src/main/java/edu/wpi/first/wpilibj/fixtures/DIOCrossConnectFixture.java
wpimath/src/main/java/edu/wpi/first/math/system/NumericalIntegration.java
wpiutil/src/main/java/edu/wpi/first/util/EventVector.java

Also remove unnecessary `@SuppressWarnings("overloads")` in NumericalIntegration.java.
I'm not sure if the unboxing will mess with the [JUnit4 Parameterized tests](https://github.com/junit-team/junit4/wiki/Parameterized-tests), since it appears to use reflection so compiling does not necessarily mean there will not be an error when running. (I can't run `./gradlew wpilibjIntegrationTests:run` locally since it couldn't `wpiHaljni` in `java.library.path`) Given the more or less abandoned status of wpilibjIntegrationTests, I suspect it will be fine to merge this in and on the off chance we actually do use wpilibjIntegrationTests again and this PR does mess with it, we'll just revert the change then.

Remove unnecessary boxing

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumbot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/mecanumdriveposeestimator/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervebot/Drivetrain.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervecontrollercommand/subsystems/DriveSubsystem.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/swervedriveposeestimator/Drivetrain.java
wpimath/src/main/java/edu/wpi/first/math/controller/HolonomicDriveController.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/ChassisSpeeds.java
wpimath/src/test/java/edu/wpi/first/math/kinematics/ChassisSpeedsTest.java

This reverts commit a3b12b3bd96ddcd29912752dbbed4039d6731dc7.

[wpimath] Revert "ChassisSpeeds fromRelative and discretize methods made instance methods (#7115)"

---

wpiutil/src/main/java/edu/wpi/first/util/RuntimeLoader.java

Now always includes the JVM location, and a link to the new docs page (page still WIP)

Make runtime loader exception message slightly better

---

wpiunits/src/main/java/edu/wpi/first/units/MomentOfInertiaUnit.java

`MomentOfInertiaUnit`'s constructor uses a `PerUnit` which causes issues when trying to make new units in the `MomentOfInertia` dimension. This should fix it

Refactor MomentOfInertiaUnit constructor to use MomentOfInertiaUnit instead of PerUnit

---

wpinet/src/main/java/edu/wpi/first/net/WPINetJNI.java
wpinet/src/main/java/edu/wpi/first/net/WebServer.java
wpinet/src/main/native/cpp/HttpUtil.cpp
wpinet/src/main/native/cpp/WebServer.cpp
wpinet/src/main/native/cpp/jni/WPINetJNI.cpp
wpinet/src/main/native/include/wpinet/HttpUtil.h
wpinet/src/main/native/include/wpinet/WebServer.h

Example use:
```java
WebServer.start(5800, Filesystem.getDeployDirectory());
```
TODO:
Closes #2518

[wpinet] Add simple web server

---

wpinet/src/main/native/cpp/WebServer.cpp

The order of evaluation of parameters is not defined; on Windows, the std::move was executed before the GetBuffer().

[wpinet] WebServer: Fix Windows

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/Trigger.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/Trigger.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/Trigger.h

This makes the logic clearer in the actual binding methods and will hopefully make it less annoying to make changes such as allowing control over initial edges.
Also changes Java to use previous and current to match C++.

[cmd] Extract common trigger binding logic

---

wpinet/src/main/native/cpp/WebServer.cpp

Also provide Content-Disposition filename header in response.
This fixes e.g. filenames with spaces in them.

[wpinet] WebServer: Unescape URI

---

wpilibNewCommands/src/main/native/cpp/frc2/command/CommandScheduler.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandScheduleTest.cpp
wpilibNewCommands/src/test/native/cpp/frc2/command/SchedulingRecursionTest.cpp

Because of the huge impact changing the Java `Command Scheduler` code has, this draft PR removes all the changes made to the Java side and only includes the changes made to C++ from the #6593 PR. 
This is still being [discussed in the FRC Discord server](https://discord.com/channels/176186766946992128/528555967827148801/1318255755677270056)

[commands] Fix C++ iterator invalidation bug

---

epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/EpilogueBackend.java

Add a measure's symbol to its name when logged by Epilogue

---

wpiutil/src/main/native/cpp/DataLogWriter.cpp

[wpiutil] DataLogWriter: Don't crash on file open error

---

upstream_utils/protobuf_patches/0001-Fix-sign-compare-warnings.patch
upstream_utils/protobuf_patches/0002-Remove-redundant-move.patch
upstream_utils/protobuf_patches/0003-Fix-maybe-uninitialized-warnings.patch
upstream_utils/protobuf_patches/0004-Fix-coded_stream-WriteRaw.patch
upstream_utils/protobuf_patches/0005-Suppress-enum-enum-conversion-warning.patch
upstream_utils/protobuf_patches/0006-Fix-noreturn-function-returning.patch
upstream_utils/protobuf_patches/0007-Work-around-GCC-12-restrict-warning-compiler-bug.patch
upstream_utils/protobuf_patches/0008-Disable-MSVC-switch-warning.patch
upstream_utils/protobuf_patches/0009-Disable-unused-function-warning.patch
upstream_utils/protobuf_patches/0010-Disable-pedantic-warning.patch
upstream_utils/protobuf_patches/0011-Avoid-use-of-sprintf.patch
upstream_utils/protobuf_patches/0012-Suppress-stringop-overflow-warning-false-positives.patch
upstream_utils/protobuf_patches/0013-Switch-descriptor-to-not-use-globals-from-header-inl.patch
upstream_utils/protobuf_patches/0014-Remove-deprecated-ATOMIC_VAR_INIT.patch
upstream_utils/protobuf_patches/0014-Remove-deprecated-ATOMIC_VAR_INT.patch
wpiutil/src/main/native/thirdparty/protobuf/src/stubs/common.cpp

Resolves #7576 
Supersedes PR #7577 by @horner

Patch thirdparty protobuf to remove deprecated ATOMIC_VAR_INIT

---

cscore/build.gradle
datalogtool/build.gradle
glass/build.gradle
outlineviewer/build.gradle
roborioteamnumbersetter/build.gradle
simulation/halsim_gui/build.gradle
sysid/build.gradle
thirdparty/imgui_suite/build.gradle
wpigui/build.gradle

Fixes mismatched library name between imgui_suite's build.gradle and publish.gradle by renaming the library to imguiSuite.
Fixes #7241.

[build] Fix imgui libraries not being published

---

wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorexponentialsimulation/subsystems/Elevator.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorprofiledpid/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorsimulation/subsystems/Elevator.java
wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/ElevatorFeedforward.java
wpimath/src/test/java/edu/wpi/first/math/controller/ArmFeedforwardTest.java
wpimath/src/test/java/edu/wpi/first/math/controller/ElevatorFeedforwardTest.java

PR #7489 replace usage of the units library with calculateWithVelocities.  
This does the same for ElevatorFeedforward and ArmFeedforward

Remove Units class from Elevator and Arm Feedforwards

---

.github/workflows/lint-format.yml

This should match what's on the 2027 branch, so we'll stop getting merge conflicts on wpiformat version bumps.

[ci] Install wpiformat into venv

---

wpimath/src/main/native/include/frc/ct_matrix.h
wpimath/src/main/native/include/frc/geometry/Rotation2d.h
wpimath/src/main/native/include/frc/geometry/Rotation3d.h

`<Eigen/LU>` doubles compilation times on MSVC, even if the Rotation3d rotation matrix constructor is unused. MSVC's frontend inefficiently parses large headers; GCC and Clang are largely unaffected.
This caught a bug in ct_matrix's 3x3 determinant.

[wpimath] Use ct_matrix instead of <Eigen/LU> for determinant in headers

---

wpimath/src/main/java/edu/wpi/first/math/controller/LTVUnicycleController.java
wpimath/src/main/native/include/frc/controller/LTVUnicycleController.h

Document the states and inputs so it isn't necessary to look at the code
Fix max velocity throws doc

[wpimath] improve LTVUnicycleController docs (NFC)

---

wpilibc/src/main/native/include/frc/Errors.h

This allows the macros to be used outside of the `frc` namespace.

[wpilibc] Fully qualify names in error macros

---

ntcore/src/main/native/include/networktables/GenericEntry.h
ntcore/src/main/native/include/networktables/NetworkTable.h
ntcore/src/main/native/include/networktables/NetworkTableEntry.h
ntcore/src/main/native/include/ntcore_c.h
ntcore/src/main/native/include/ntcore_cpp.h
wpilibc/src/main/native/include/frc/smartdashboard/SmartDashboard.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java

I would like to address #6334, but realized that some discussion about how the behavior should be documented would help before changing all of them. The code diff here contains a proposal that reflects my understanding of the actual behavior. 
Questions: 
1. Would you suggest different wording for documenting the behavior of these methods?
2. Should documentation in `NetworkTableEntry.java`, `NetworkTablesJNI.java`, `ntcore_c.h`, and `ntcore_cpp.h` also be addressed in the same PR, or in a second PR specific to the ntcore component?
More details about `NetworkTableEntry.java`, `NetworkTablesJNI.java`, `ntcore_c.h`, and `ntcore_cpp.h`: 
`SetDefault*` methods in `NetworkTableEntry.java` called by `SmartDashboard.setDefault*` document the return value as `@return False if the entry exists …

`SmartDashboard.setDefault*` documentation

---

wpical/src/main/native/cpp/WPIcal.cpp
wpical/src/main/native/cpp/fieldcalibration.cpp
wpical/src/test/native/cpp/test_calibrate.cpp

This fixes WPIcal's issue with a fixed tag range and allows for teams to have custom maps with no tag maximum. This also adds checks and warnings for users who have selected a pinned tag ID that isn't in their initial map JSON.

[wpical] Add support for new Apriltags (ID 16-22)

---

wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/Commands.java
wpilibNewCommands/src/main/native/cpp/frc2/command/Commands.cpp
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h

This changes the way deferred proxy is implemented to not use the deprecated ProxyCommand constructor.
This function serves a good purpose that should be kept IMO. The constructor was confusing but this is just good syntactic sugar over `defer(() -> supplier.get().asProxy())`.

[cmd] Undeprecate deferredProxy

---

glass/src/lib/native/cpp/other/Field2D.cpp

Too many people don't realize that glass/simgui field2d can load pathweaver JSON field files since it's hidden.

Make Field2D field picker show JSONs first

---

glass/src/lib/native/cpp/other/Field2D.cpp

My previous change from #7214 caused custom Field2d images to be slightly squished vertically, this fixes the padding so the image keeps the same aspect ratio.
Before:
After:

[glass] Fix custom image padding to maintain aspect ratio

---

epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/EpilogueBackend.java

This reverts commit 469bb3290d2f3cfd0a90c572fc8ab01f2cd0be53.

Revert "[epilogue] Add a measure's symbol to its name when logged by Epilogue (#7535)"

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Translation3d.java
wpimath/src/main/native/include/frc/geometry/Translation3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Translation3dTest.java
wpimath/src/test/native/cpp/geometry/Translation2dTest.cpp
wpimath/src/test/native/cpp/geometry/Translation3dTest.cpp

[wpimath] Implement Translation3d.RotateAround

---

hal/src/main/java/edu/wpi/first/hal/AddressableLEDJNI.java
hal/src/main/native/include/hal/AddressableLED.h
wpilibc/src/main/native/include/frc/AddressableLED.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/AddressableLED.java

Docs https://github.com/wpilibsuite/frc-docs/pull/2932

Add note about support for WS2815

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose2dTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose3dTest.java
wpimath/src/test/native/cpp/geometry/Pose2dTest.cpp
wpimath/src/test/native/cpp/geometry/Pose3dTest.cpp

[wpimath] Implement Pose2d and Pose3d rotateAround()

---

upstream_utils/eigen_patches/0001-Disable-warnings.patch
upstream_utils/eigen_patches/0002-Intellisense-fix.patch
upstream_utils/eigen_patches/0003-Make-assignment-constexpr.patch
wpimath/src/main/native/include/frc/ct_matrix.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/AssignEvaluator.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/EigenBase.h
wpimath/src/main/native/thirdparty/eigen/include/Eigen/src/Core/functors/AssignmentFunctors.h
wpimath/src/test/native/cpp/geometry/Rotation2dTest.cpp
wpimath/src/test/native/cpp/geometry/Rotation3dTest.cpp
wpimath/src/test/native/cpp/system/LinearSystemIDTest.cpp

[wpimath] Fix various constexpr support bugs

---

hal/src/main/native/systemcore/AnalogInput.cpp

Wrong scaling values were used.

[hal] Fix systemcore analog input scaling

---

.bazelrc
WORKSPACE
shared/bazel/compiler_flags/systemcore_flags.rc

This updates the toolchains version to one that supports systemcore, mostly for the 2027 branch. Also bumps a couple of versions that were updated in gradle but not in bazel.
I have tested builds in a more bazl'ified version of the 2027 branch and can make that PR once this gets merged over there.

[bazel] Update toolchain to support systemcore

---

wpiunits/src/generate/main/java/Measure-interface.java.jinja
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Acceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Angle.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/AngularVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Current.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Dimensionless.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Distance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Energy.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Force.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Frequency.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearAcceleration.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearMomentum.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/LinearVelocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mass.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/MomentOfInertia.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Mult.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Per.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Power.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Resistance.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Temperature.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Time.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Torque.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Velocity.java
wpiunits/src/generated/main/java/edu/wpi/first/units/measure/Voltage.java
wpiunits/src/main/java/edu/wpi/first/units/Measure.java
wpiunits/src/main/java/edu/wpi/first/units/VelocityUnit.java

Instead of only providing per(TimeUnit)
Useful for making conversion factors easier, eg `Inches.of(10).per(Rotation)` vs `Inches.of(10).per(Rotation.one())`
Update VelocityUnit.one() and VelocityUnit.zero() to return Velocity objects instead of generic `Measure<? extends VelocityUnit<D>>`; VelocityUnit is final, so the wildcard generic is unnecessary, and this makes the generated `per` functions possible for this type

[wpiunits] Add Measure.per overloads for all known unit types

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/ADIS16470_IMU.java

C++ allows either 16982 or 16470, do the same for Java.

[wpilibj] ADIS16470: Allow product ID of 16470

---

wpimath/src/main/native/include/units/base.h

Self explanatory. Found this while trying to understand how the units worked.

[wpimath] Fix macro name typo

---

wpilibNewCommands/src/generate/main/java/commandhid.java.jinja
wpilibNewCommands/src/generate/main/native/include/frc2/command/button/commandhid.h.jinja
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS4Controller.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandPS5Controller.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandStadiaController.java
wpilibNewCommands/src/generated/main/java/edu/wpi/first/wpilibj2/command/button/CommandXboxController.java
wpilibNewCommands/src/generated/main/native/include/frc2/command/button/CommandPS4Controller.h
wpilibNewCommands/src/generated/main/native/include/frc2/command/button/CommandPS5Controller.h
wpilibNewCommands/src/generated/main/native/include/frc2/command/button/CommandStadiaController.h
wpilibNewCommands/src/generated/main/native/include/frc2/command/button/CommandXboxController.h
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandJoystick.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandJoystick.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandJoystick.h
wpilibc/src/generate/main/native/include/frc/hid.h.jinja
wpilibc/src/generated/main/native/include/frc/PS4Controller.h
wpilibc/src/generated/main/native/include/frc/PS5Controller.h
wpilibc/src/generated/main/native/include/frc/StadiaController.h
wpilibc/src/generated/main/native/include/frc/XboxController.h
wpilibc/src/main/native/cpp/Joystick.cpp
wpilibc/src/main/native/include/frc/Joystick.h
wpilibj/src/generate/hids.json
wpilibj/src/generate/hids.schema.json
wpilibj/src/generate/main/java/hid.java.jinja
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS4Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/PS5Controller.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/StadiaController.java
wpilibj/src/generated/main/java/edu/wpi/first/wpilibj/XboxController.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/Joystick.java

Closes #7611.
Not completely sure about whether the link to the WPILib docs page should stay there or if there's a better way to include it (that also plays nicely with formatting).
CommandJoystick.h doesn't have the `getX()` and `getY()` direction clarifications since it doesn't have them.

[wpilibc, wpilibh, cmd] Improve HID direction documentation (NFC)

---

.github/workflows/aql/wpilib-mvn-development_unused.aql
.github/workflows/artifactory-nightly-cleanup.yml

Now that we've recovered from the Great Artifactory Purge and reorganized the repos, we can turn this back on. The query targets the local repo for extra safety.

[ci] Re-enable Artifactory cleaner cron job

---

wpimath/src/main/native/cpp/controller/ArmFeedforward.cpp

Small values of kₐ make the iterative solver ill-conditioned. This change reverts to the constant-acceleration feedforward in that case. It gives _very_ bad results (hence why we added the iterative solver in the first place), but it's better than hanging.
```
TEST(ArmFeedforwardTest, CalculateIllConditioned) {
constexpr auto Ks = 0.5_V;
constexpr auto Kv = 20_V / 1_rad_per_s;
constexpr auto Ka = 1e-2_V / 1_rad_per_s_sq;
constexpr auto Kg = 0_V;
frc::ArmFeedforward armFF{Ks, Kg, Kv, Ka};
// Calculate(currentAngle, currentVelocity, nextAngle, dt)
CalculateAndSimulate(armFF, 0_rad, 0_rad_per_s, 2_rad_per_s, 20_ms);
}
```
This produces 1 V and doesn't accelerate the system at all. Using nextVelocity instead of currentVelocity in the feedforward outputs 41 V and still only accelerates to 0.4 …

[wpimath] Fix infinite loop in ArmFeedforward::Calculate(xₖ, vₖ, vₖ₊₁)

---

wpiutil/src/main/native/cpp/DataLogBackgroundWriter.cpp
wpiutil/src/main/native/cpp/fs.cpp
wpiutil/src/main/native/include/wpi/fs.h

[wpiutil] use reinterpret_cast for kInvalidFile on Win32 via macro

---

.gitignore
fieldImages/CMakeLists.txt

By pre-pending the current build/binary directory to the generated output dir, it ensures the files are still found when allwpilib is used a subproject (cmake or meson).  Without doing this, the generated files are not found, do not compile, which ultimately leads to missing symbols when linking libfieldImages.

CMake: Reproducible Output Dir For Generated Field Images Code

---

wpinet/BUILD.bazel

I was getting:
external/arm_frc_linux_gnueabi_repo/bin/../arm-nilrt-linux-gnueabi/sysroot/usr/lib/gcc/arm-nilrt-linux-gnueabi/12/../../../../../../../arm-nilrt-linux-gnueabi/bin/ld: bazel-out/k8-opt--roborio/bin/external/com_github_wpilibsuite_allwpilib/wpinet/libwpinet.static.a(fs.o): undefined reference to symbol 'dlsym@@GLIBC_2.4' external/arm_frc_linux_gnueabi_repo/bin/../arm-nilrt-linux-gnueabi/sysroot/usr/lib/gcc/arm-nilrt-linux-gnueabi/12/../../../../../../../arm-nilrt-linux-gnueabi/bin/ld: external/arm_frc_linux_gnueabi_repo/bin/../arm-nilrt-linux-gnueabi/sysroot/lib/libdl.so.2: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status
This fixes that error for me.

Add missing -ldl when building libuv in bazel

---

wpinet/src/main/native/cpp/WebServer.cpp

It's currently a bit awkward to use the `WebServer` class for a web page that is intended to be opened in a browser (such as a dashboard), because the index page is always a directory listing rather than an HTML file. The solution here is just to replace the directory listing with the contents of `index.html` if such a file exists (I think this is fairly standard behavior for statically serving files). Note that the behavior when adding `format=json` is unchanged, which allows dashboards (e.g. Elastic) to get a directory listing even if `index.html` exists.

[wpinet] Serve index HTML file from WebServer if available

---

wpimath/src/main/java/edu/wpi/first/math/controller/ArmFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/ElevatorFeedforward.java
wpimath/src/main/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.java
wpimath/src/main/native/include/frc/controller/ArmFeedforward.h
wpimath/src/main/native/include/frc/controller/ElevatorFeedforward.h
wpimath/src/main/native/include/frc/controller/SimpleMotorFeedforward.h

[wpimath] Fix up order and docs for Feedforward gain setters

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/AnnotationProcessor.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/LoggerGenerator.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/Logged.java

Now a flag at the class level controls whether warning messages are printed
Defaults to false (no warning messages)
Fixes #7782

[epilogue] Make nonloggable type warnings configurable

---

wpilibc/src/main/native/include/frc/simulation/LinearSystemSim.h
wpilibc/src/test/native/cpp/simulation/ElevatorSimTest.cpp
wpilibc/src/test/native/cpp/simulation/SingleJointedArmSimTest.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/LinearSystemSim.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/ElevatorSimTest.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSimTest.java

Establishes the invariant that the state and measurement always match up, even immediately after construction.
Fixes #7761

[wpilib] Make LinearSystemSim setState() update output

---

sysid/src/main/native/include/sysid/analysis/FilteringUtils.h

The first part of the message already has one.

[sysid] Remove extra period from exception messages

---

glass/src/lib/native/cpp/other/Field2D.cpp

The default size is from the field JSON file in `fieldImages`, converted from feet to meters.

[Glass] Update default field to 2025 for Field2D

---

shared/ceres.gradle

Without this, generateVsCodeConfig doesn't work, as it can't find the sources artifact.

Remove sources from ceres-cpp

---

wpimath/src/main/java/edu/wpi/first/math/filter/Debouncer.java
wpimath/src/main/native/include/frc/filter/Debouncer.h
wpimath/src/test/java/edu/wpi/first/math/filter/DebouncerTest.java
wpimath/src/test/native/cpp/filter/DebouncerTest.cpp

Closes #7817
Signed-off-by: swurl <swurl@swurl.xyz>

[wpimath] Add Debouncer type and time setters

---

wpimath/src/main/native/cpp/geometry/Ellipse2d.cpp

The problem was ill-conditioned if either semiaxis had zero length.

[wpimath] Fix singularities in Ellipse2d::Nearest()

---

wpimath/src/main/java/edu/wpi/first/math/estimator/MerweScaledSigmaPoints.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/include/frc/estimator/MerweScaledSigmaPoints.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/UnscentedTransform.h
wpimath/src/test/java/edu/wpi/first/math/estimator/UnscentedKalmanFilterTest.java
wpimath/src/test/native/cpp/estimator/UnscentedKalmanFilterTest.cpp

Throughout the code the state sqrt covariance S and innovation covariance Sy are maintained as upper triangular cholesky factors of those covariance matrices. [The original paper](https://www.researchgate.net/publication/3908304) defines P=S*S', so S should be lower triangular. The functions in the paper reflect this. In the code implementation, the sqrt covariance matrices are upper triangular, but the algorithm expects them to be lower triangular. 
This bug was likely missed because the incorrect version of the filter is able to converge for some systems where all the states are observed, and the test case is set up such that all states are observed. 
To fix the bug, a couple things needed to be changed:
all instances of rankUpdate() needed to be changed to use the lower triangular …

[wpimath] Fix UnscentedKalmanFilter and improve math docs

---

wpiutil/doc/datalog.adoc
wpiutil/doc/datalog.ksy
wpiutil/doc/wpilog.ksy

Adds a [Kaitai Struct](https://kaitai.io/) definition for the WPILOG format. This can be used to generate code to read/write data log files without needing to build out a parser/serializer by hand. Or just an additional resource for readers to help understand the WPILOG format.

Add Kaitai Struct definition for data log format

---

glass/src/libnt/native/cpp/NetworkTables.cpp

```
/home/tav/frc/wpilib/allwpilib/glass/src/libnt/native/cpp/NetworkTables.cpp: In function ‘void UpdateProtobufValueSource(glass::NetworkTablesModel&, glass::NetworkTablesModel::ValueSource*, const google::protobuf::Message&, std::string_view, int64_t)’:
/home/tav/frc/wpilib/allwpilib/glass/src/libnt/native/cpp/NetworkTables.cpp:363:27: error: no match for ‘operator+’ (operand types are ‘const char [7]’ and ‘google::protobuf::internal::DescriptorStringView’ {aka ‘std::basic_string_view<char>’})
363 |   out->typeStr = "proto:" + desc->full_name();
|                  ~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~
|                  |                         |
|                  const char [7]            google::protobuf::internal::DescriptorStringView {aka std::basic_string_view<char>}
```

[glass] Fix compilation error with protobuf 30.1

---

README.md

Someone on the Discord couldn't build WPILib with just the command-line tools.
Fixes #7891.

[docs] Update readme to say Xcode is required

---

.github/workflows/cmake-android.yml
.github/workflows/cmake.yml
.github/workflows/sanitizers.yml

GitHub recently disabled their old caching system, so an upgrade is needed: https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts

[ci] Upgrade sccache action

---

shared/examplecheck.gradle
wpilibcExamples/CMakeLists.txt
wpilibcExamples/build.gradle
wpilibcExamples/src/main/cpp/snippets/Encoder/cpp/Robot.cpp
wpilibcExamples/src/main/cpp/snippets/snippets.json
wpilibjExamples/build.gradle
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/encoder/Main.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/encoder/Robot.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/snippets/snippets.json

This enables frc-docs to use RLIs for things that are currently in-line code blocks, and ensures they compile, which is important with the 2027 breaking changes coming. They are kept separate from the examples to ensure they don't polute the VSCode examples finder.
Adds the Encoder snippets used in the frc-docs Encoder article as the first instance of this.

[examples] Add compilable code snippets

---

.bazelrc

The .bazelrc was doing a relative import, not an absolute one.  This looks by accident, fix it.

[bazel] Make bazel work outside //

---

wpimath/src/main/java/edu/wpi/first/math/MathUtil.java
wpimath/src/main/native/include/frc/MathUtil.h

Reduces nesting by returning when the value is within the deadband.
Adjusts the algorithm to handle large values of maxMagnitude naturally (instead of needing a separate check).
Reformats the math comments.

[wpimath] Adjust applyDeadband logic

---

cscore/BUILD.bazel
shared/bazel/compiler_flags/osx_flags.rc

Currently in the Bazel build we link every C/C++/ObjC binary to the Foundation frameworks that `//cscore` requires, despite most things not having any Objective C deps otherwise.

[bazel] Avoid globally linking macOS SDK frameworks

---

.github/workflows/bazel.yml

Our Bazel Windows CI builds are currently horrifically slow, especially compared to our Linux and macOS builds. For a ~total cache miss the Windows jobs take 50 minutes wall clock time each.
This changes the CI job to use the default `--compilation_mode=fastbuild` rather than `--compilation_mode=opt`. This brings a Windows job down to 32 minutes in the worst case.
We can build with `-c opt` when we create releases rather than on every CI job.
https://bazel.build/docs/user-manual#compilation-mode

[ci] Use Bazel fastbuild compilation mode on Windows

---

cmake/modules/CompileWarnings.cmake
ntcore/src/test/native/cpp/ValueTest.cpp
upstream_utils/debugging_patches/0001-Guard-gnu-flatten-attribute.patch
upstream_utils/debugging_patches/0002-Remove-debugger_query-argument-from-Windows-and-macO.patch
upstream_utils/debugging_patches/0003-Fix-exception-mask-type-typo-on-macOS.patch
upstream_utils/debugging_patches/0004-Remove-NOMINMAX-macro-from-Windows.patch
upstream_utils/debugging_patches/0005-Add-emscripten-shim.patch
upstream_utils/memory_patches/0001-Group-doxygen-into-memory-module.patch
upstream_utils/memory_patches/0002-Remove-conflicting-doxygen-concept-alias.patch
upstream_utils/memory_patches/0003-Fix-deprecation-warning-for-UDLs.patch
wpiutil/src/main/native/thirdparty/debugging/src/emscripten.cpp
wpiutil/src/main/native/thirdparty/memory/include/wpi/memory/memory_arena.hpp
wpiutil/src/test/native/include/wpi/SpanMatcher.h

I ran the CMake configure with:
```bash
emcmake cmake -B build-wasm -S . \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS=OFF \
-DWITH_SIMULATION_MODULES=OFF \
-DWITH_PROTOBUF=OFF \
-DWITH_GUI=OFF \
-DWITH_CSCORE=OFF
```
* Turned off simulation modules because they require shared libraries
* Turned off GUI because glfw requires libssh
* Turned off cscore because it requires OpenCV
I still get the following compiler errors:
```
/home/tav/frc/wpilib/allwpilib/wpinet/src/main/native/thirdparty/libuv/src/unix/linux.cpp:43:10: fatal error: 'sys/epoll.h' file not found
43 | #include <sys/epoll.h>
|          ^~~~~~~~~~~~~
```
```
/home/tav/frc/wpilib/allwpilib/wpinet/src/main/native/thirdparty/libuv/src/unix/stream.cpp:991:56: error: comparison of integers of different signs: 'unsigned long' …
```

Fix more emscripten compiler errors

---

wpimath/src/main/java/edu/wpi/first/math/trajectory/TrapezoidProfile.java
wpimath/src/main/native/include/frc/trajectory/TrapezoidProfile.h
wpimath/src/test/java/edu/wpi/first/math/trajectory/TrapezoidProfileTest.java
wpimath/src/test/native/cpp/trajectory/TrapezoidProfileTest.cpp

Fixes the null pointer and adds docs to clarify the return value in this case or when calling totalTime.

[wpimath] fix null pointer when calling timeLeftUntill

---

wpimath/src/main/java/edu/wpi/first/math/filter/Debouncer.java
wpimath/src/main/native/cpp/filter/Debouncer.cpp
wpimath/src/main/native/include/frc/filter/Debouncer.h
wpimath/src/test/java/edu/wpi/first/math/filter/DebouncerTest.java
wpimath/src/test/native/cpp/filter/DebouncerTest.cpp

Closes #7867
Properly resets the baseline upon switching the debounce type, and adds
a test for such.
Signed-off-by: swurl <swurl@swurl.xyz>

[wpimath] Fix Debouncer type-changing behavior

---

wpinet/BUILD.bazel

The headers in `wpinet/src/main/native/cpp/*.h` aren't intended to be used by dependents, so they shouldn't get propagated.

[bazel] Hide wpinet implementation headers

---

wpiutil/src/main/java/edu/wpi/first/util/datalog/DataLog.java

When adding struct schemas, the current logic is to add the parent/outer schema, and then add the schemas for any nested inner schemas.
This necessitates a bunch of extra logic for consumers of the datalog format, since you may see a sequence of struct schema definitions like this:
```
Start(150, name='/.schema/struct:Pose2d', type='structschema', metadata='') [14.160558]
Data(150, size=45) <name='/.schema/struct:Pose2d', type='structschema'> [14.160558]
Start(151, name='/.schema/struct:Rotation2d', type='structschema', metadata='') [14.160558]
Data(151, size=12) <name='/.schema/struct:Rotation2d', type='structschema'> [14.160558]
```
Here the `Pose2d` struct schema is defined, which references `Translation2d` and `Rotation2d` as nested schemas. The issue is that we are referencing the …

[wpiutil] Add nested struct schemas before parent schema

---

cscore/BUILD.bazel
cscore/CMakeLists.txt
cscore/build.gradle
cscore/src/main/native/objcpp/UsbCameraImpl.h
cscore/src/main/native/objcpp/UsbCameraImplObjc.h
cscore/src/main/native/objcpp/UsbCameraImplObjc.mm
cscore/src/main/native/objcpp/UvcControlImpl.h
cscore/src/main/native/objcpp/UvcControlImpl.mm
shared/config.gradle

This MR enhances the cscore project on macOS by implementing UVC (USB Video Class) protocol communication for USB cameras, while also fixing a frame rate precision issue in the AVCaptureDevice configuration.
- Added UVC protocol support for USB cameras on macOS
- Implemented common camera property controls through UVC protocol:
- Exposure
- Brightness
- White Balance
- And other standard UVC properties
- The original implementation was insipred from [openpnp-capture](https://github.com/openpnp/openpnp-capture/blob/master/mac/uvcctrl.mm)
- The video streaming still uses AVFoundation, UVC is only used for camera property controls.
- Fixed frame rate precision loss when configuring AVCaptureDevice camera FPS on macOS
- Implemented a matching algorithm to:
- Take the requested FPS value as …

[cscore] Add UVC Protocol Support for USB Camera Controls on macOS

---

wpimath/src/test/native/cpp/controller/ControlAffinePlantInversionFeedforwardTest.cpp

```
In file included from /usr/include/c++/15.1.1/functional:61,
from /home/tav/frc/wpilib/allwpilib/thirdparty/googletest/include/gtest/gtest-matchers.h:43,
from /home/tav/frc/wpilib/allwpilib/thirdparty/googletest/include/gtest/internal/gtest-death-test-internal.h:47,
from /home/tav/frc/wpilib/allwpilib/thirdparty/googletest/include/gtest/gtest-death-test.h:43,
from /home/tav/frc/wpilib/allwpilib/thirdparty/googletest/include/gtest/gtest.h:65,
from /home/tav/frc/wpilib/allwpilib/wpimath/src/test/native/cpp/controller/ControlAffinePlantInversionFeedforwardTest.cpp:7:
In copy constructor ‘std::function<_Res(_ArgTypes ...)>::function(const std::function<_Res(_ArgTypes ...)>&) [with _Res = Eigen::Matrix<double, 2, 1>; _ArgTypes = {const Eigen::Matrix<double, 2, 1, 0, 2, 1>&, const …
```

[wpimath] Fix warning false positive from GCC 15

---

wpilibNewCommands/src/main/native/include/frc2/command/Command.h
wpilibNewCommands/src/main/native/include/frc2/command/CommandPtr.h
wpilibNewCommands/src/main/native/include/frc2/command/Commands.h
wpilibNewCommands/src/main/native/include/frc2/command/Subsystem.h
wpilibNewCommands/src/test/native/cpp/frc2/command/CommandPtrTest.cpp
wpilibcExamples/src/main/cpp/examples/DriveDistanceOffboard/include/subsystems/DriveSubsystem.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Drive.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Intake.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Pneumatics.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Shooter.h
wpilibcExamples/src/main/cpp/examples/RapidReactCommandBot/include/subsystems/Storage.h

Classes can be marked as [[nodiscard]] such that if they are ever returned from a method its as if that method has the [[nodiscard]] attribute. (https://en.cppreference.com/w/cpp/language/attributes/nodiscard)
Seeing as all the CommandPtr decorators were marked as [[nodiscard]], I thought this would achieve the goal more succinctly.
This has the added benefit of also making user created CommandPtr factories benefit as well.
What motivated this is that I've seen student code like the following several times
```cpp
CommandPtr ActivateIntake() {
return RunEnd(
[this] {SetIntakeSpeed(0.5);},
[this] {SetIntakeSpeed(0.0);});
}
CommandPtr IntakeCoral() {
return Run([this] {ActivateIntake();})
.Until([this] {return CoralDetected();});
}
```
This code currently happily compiles without warnings …

[commands] Mark CommandPtr class as [[nodiscard]]

---

MavenArtifacts.md
apriltag/build.gradle
cscore/build.gradle
ntcore/build.gradle
shared/jni/publish.gradle
shared/jni/setupBuild.gradle

The loading framework for the `-jni` artifacts was removed in #6600, so these just don't work anymore. We can remove them to reduce the amount of space used when building and save some time as well (although the gains seem to be marginal).
Reference for CI build times and space savings: https://github.com/Gold856/allwpilib/actions/runs/12348391056

[build] Remove statically linked JNI artifacts

---

wpiunits/src/main/java/edu/wpi/first/units/Units.java

This reverts commit 3dee19a435e6bcb3aec55c033caf13db307afa6d.
This was merged without sufficient review or discussion as to whether these units are value-add for the Java units library.

Revert "Added parity with C++ units. (#7965)"

---

wpilibc/src/main/native/include/frc/event/BooleanEvent.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/event/BooleanEvent.java

These were apparently a meme about state being hard to manage rather than a statement about the code itself. I spent a while trying to find some complex logic this comment was alluding to that would indicate why it's "a nightmare to manage".

[wpilib] Remove unhelpful comments from BooleanEvent

---

wpinet/src/main/native/cpp/http_parser.cpp

Hi Development Team,
I identified a vulnerability in a clone function http_parser_execute() in `wpinet/src/main/native/cpp/http_parser.cpp` sourced from [nodejs/node](https://github.com/nodejs/node). This issue, originally reported in [CVE-2020-8287](https://nvd.nist.gov/vuln/detail/cve-2020-8287), was resolved in the repository via this commit https://github.com/nodejs/node/commit/fc70ce08f5818a286fb5899a1bc3aff5965a745e.
This PR applies the corresponding patch to fix the vulnerabilities in this codebase.
Please review at your convenience. Thank you!

Fix potential vulnerable cloned function

---

wpinet/src/main/native/include/wpinet/MulticastServiceResolver.h
wpinet/src/main/native/linux/MulticastServiceResolver.cpp
wpinet/src/main/native/macOS/MulticastServiceResolver.cpp
wpinet/src/main/native/windows/MulticastServiceResolver.cpp

Without this, the only way to read items is to use the event. And in my use case, adding that would require adding my own thread _just_ for handling that event.

Add callback for mDNS service resolver

---

hal/src/main/native/systemcore/Power.cpp

Lots of higher level code in allwpilib depends on this, so we should return at least a valid and sane value, rather then erroring

Add temp value for HAL_GetUserVoltage3V3

---

hal/src/main/native/systemcore/DutyCycle.cpp

The units are nanoseconds, not microseconds

Fix dutyCycle high time units

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/native/include/frc/geometry/Pose2d.h
wpimath/src/main/native/include/frc/geometry/Pose3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Pose3dTest.java
wpimath/src/test/native/cpp/geometry/Pose3dTest.cpp

This pull request adds a nearest() method to the Pose3d class, mirroring the existing functionality in Pose2d.
I ran into this while working on robot code and initially assumed Pose3d already had a nearest() method. When I realized it didn’t, I thought I would try  to implement it. Since I am not that familiar with C++, I based the implementation as closely as possible on the one in Pose2d. I tried to follow all the requirements in CONTRIBUTING.md and believe this new feature fits the suggestions, but was not sure about the python wrapping requirements.
Let me know if there’s anything I should adjust or improve!

[wpimath] Add nearest() method to Pose3d (mirroring Pose2d)

---

hal/src/main/java/edu/wpi/first/hal/IMUJNI.java
hal/src/main/native/cpp/jni/IMUJNI.cpp
hal/src/main/native/include/hal/IMU.h
hal/src/main/native/include/hal/IMUTypes.h
hal/src/main/native/sim/IMU.cpp
hal/src/main/native/systemcore/HAL.cpp
hal/src/main/native/systemcore/HALInitializer.h
hal/src/main/native/systemcore/IMU.cpp
wpilibc/src/main/native/cpp/OnboardIMU.cpp
wpilibc/src/main/native/include/frc/OnboardIMU.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/OnboardIMU.java

The HAL API exposes the atomic read capability of the backend including timestamp. The upper level API currently only allows reading one value at a time (with the exception of the quaternion) and no timestamps- I wasn't sure how we wanted this API to look (we are _not_ returning a double array), and the current API is probably better for beginners. Related, I don't love the way the java api works currently (nt array->hal type->double array in jni->java array->high level API extracts value).
The upper level getYaw function in java returns radians (c++ obviously can uses units)- this is a break from prior WPILib gyro implementations which return in degrees. Is this something we're ok with?
I didn't implement java units yet as I'm not sure what our stance is there.
Sim still needs to be …

[hal, wpilib] Add systemcore IMU

---

wpimath/src/main/native/include/frc/geometry/Translation2d.h

Quick fix to update nearest method of Translation2d to pass values by const ref instead of by value in min_element's llamada. 
When adding the Translation3d method, [calcmogul](https://github.com/calcmogul) noticed both C++ translation methods needed a fix.
> Translation2d should be updated similarly, now that I'm looking at it. The rule of thumb is to pass anything larger than the machine word size (e.g., 32 bits on a 32-bit system) by const ref.
> Separate branch/PR.

[wpimath] Pass Translation2d by const reference instead of by value

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Pose2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Pose3d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation3d.java

Update parameter type of `nearest()` methods on geometry classes in Java to take in a `Collection` instead of specifically a `List`. This is helpful because `Collection` is a super interface of `List`, letting the function take in more general data instead of unnecessarily requiring ordered lists. 
This requires no change of the method itself and keeps the same functionality.
Fixes #7873

[wpimath] Update parameter type from list to collection in Java nearest methods

---

wpilibc/src/main/native/cpp/drive/DifferentialDrive.cpp
wpilibj/src/main/java/edu/wpi/first/wpilibj/drive/DifferentialDrive.java
wpimath/src/main/java/edu/wpi/first/math/MathUtil.java
wpimath/src/main/native/include/frc/MathUtil.h
wpimath/src/test/java/edu/wpi/first/math/MathUtilTest.java
wpimath/src/test/native/cpp/MathUtilTest.cpp

EDIT: Name of method has been updated to copySignPow
This PR adds the simple util method of `applyPowerCurve(value, exponent, maxMagnitude)` to the Java and C++ `MathUtil` classes. This method transforms `value` to be on the power curve of x to the `exponent` while keeping its sign. It also handles a maxMagninude value that is used to keep the curve consistent (and the value in range) whether `value` is between the default of [-1,1] or some other magnitude like [-100,100]. 
Usage:
```java
final double MAX_SPEED = 12.3;
double value = xbox.getLeftX() * MAX_SPEED; // get value from joystick
value = MathUtil.applyDeadband(value, 0.05, MAX_SPEED); // handle deadzone, filters speeds under 0.05
value = MathUtil.applyPowerCurve(value, 2.0, MAX_SPEED); // place the value on the curve of x^2 while …
```

[wpimath] Add copySignPow to MathUtil for joystick input shaping

---

hal/src/main/native/systemcore/I2C.cpp

We'll just have to document that alpha is backwards.

Fix I2C order on systemcore

---

glass/src/libnt/native/cpp/NTMechanism2D.cpp
glass/src/libnt/native/include/glass/networktables/NTMechanism2D.h

```
In file included from /Users/runner/work/allwpilib/allwpilib/glass/src/libnt/native/cpp/NTMechanism2D.cpp:5:
In file included from /Users/runner/work/allwpilib/allwpilib/glass/src/libnt/native/include/glass/networktables/NTMechanism2D.h:7:
In file included from /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/memory:898:
In file included from /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__memory/shared_ptr.h:31:
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__memory/unique_ptr.h:66:19: error: invalid application of 'sizeof' to an incomplete type '(anonymous …
```

[glass] Fix compilation errors from C++23 Clang

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/Preferences.java
wpilibj/src/test/java/edu/wpi/first/wpilibj/PreferencesTest.java

Use case: Our team has a shared library that includes wrapper APIs for the
Java Preferences API. The wrapper API adds a topic (with a topic name starting
with ".") where it stores non-persistent data that is used for validation.
The code for our wrapper API is [here](https://github.com/Prospect-Robotics/lib2813/blob/main/lib/src/main/java/com/team2813/lib2813/preferences/PersistedConfiguration.java).
The unit tests for those classes use Preferences.setNetworkTableInstance()
to ensure that the tests are isolated. Since there is no current API to get
the current preference table, our wrapper APIs either have to take in a
NetworkTableInstance (which makes the classes less simple to use) or our code
to add these internal topics needs to use the default network table instance (making the
tests …

[wpilibj] Add Preferences.getNetworkTable()

---

ntcore/doc/networktables4.adoc
ntcore/src/main/native/cpp/net/WireDecoder.cpp
ntcore/src/test/native/cpp/server/ServerImplTest.cpp

[ntcore] Check id ranges in control messages

---

hal/src/main/java/edu/wpi/first/hal/simulation/DriverStationDataJNI.java
hal/src/main/native/cpp/jni/simulation/DriverStationDataJNI.cpp
hal/src/main/native/include/hal/DriverStationTypes.h
hal/src/main/native/include/hal/Types.h
hal/src/main/native/include/hal/simulation/DriverStationData.h
hal/src/main/native/sim/mockdata/DriverStationData.cpp
hal/src/main/native/sim/mockdata/DriverStationDataInternal.h
hal/src/main/native/systemcore/FRCDriverStation.cpp
hal/src/main/native/systemcore/mockdata/DriverStationData.cpp
hal/src/test/native/cpp/mockdata/DriverStationDataTest.cpp
simulation/halsim_ds_socket/src/main/native/cpp/DSCommPacket.cpp
simulation/halsim_gui/src/main/native/cpp/DriverStationGui.cpp
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/CommandGenericHID.java
wpilibNewCommands/src/main/java/edu/wpi/first/wpilibj2/command/button/POVButton.java
wpilibNewCommands/src/main/native/cpp/frc2/command/button/CommandGenericHID.cpp
wpilibNewCommands/src/main/native/include/frc2/command/button/CommandGenericHID.h
wpilibNewCommands/src/main/native/include/frc2/command/button/POVButton.h
wpilibNewCommands/src/test/native/cpp/frc2/command/POVButtonTest.cpp
wpilibc/src/main/native/cpp/DriverStation.cpp
wpilibc/src/main/native/cpp/GenericHID.cpp
wpilibc/src/main/native/cpp/simulation/DriverStationSim.cpp
wpilibc/src/main/native/cpp/simulation/GenericHIDSim.cpp
wpilibc/src/main/native/include/frc/DriverStation.h
wpilibc/src/main/native/include/frc/GenericHID.h
wpilibc/src/main/native/include/frc/simulation/DriverStationSim.h
wpilibc/src/main/native/include/frc/simulation/GenericHIDSim.h
wpilibj/src/main/java/edu/wpi/first/wpilibj/DriverStation.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/GenericHID.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DriverStationSim.java
wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/GenericHIDSim.java

#7977 updated the meaning of the POV values, but did not update all of the usages. This PR switches everything to use the new HAL_JoystickPOV and DriverStation.POVDirection enums. In addition, it changes DriverStationJNI.setJoystickPOV to use a byte for the value parameter instead of an int to match the other POV JNI functions and adds a `HAL_ENUM_WITH_UNDERLYING_TYPE` macro.

[hal,wpilibc,wpilibj,cmd] Update POV to use enums

---

.github/workflows/cmake.yml

protobuf@3 will be deactivated July 1st, so it's been replaced with protobuf@29.

[ci] Update Homebrew protobuf version for CMake

---

apriltag/BUILD.bazel
datalog/BUILD.bazel
hal/BUILD.bazel
ntcore/BUILD.bazel
romiVendordep/BUILD.bazel
shared/bazel/rules/cc_rules.bzl
simulation/halsim_ds_socket/BUILD.bazel
simulation/halsim_ws_core/BUILD.bazel
simulation/halsim_ws_server/BUILD.bazel
simulation/halsim_xrp/BUILD.bazel
wpilibNewCommands/BUILD.bazel
wpilibc/BUILD.bazel
wpimath/BUILD.bazel
wpinet/BUILD.bazel
wpiutil/BUILD.bazel
xrpVendordep/BUILD.bazel

This is another watered down version of #8025 that does the bare minimum to get most of the libraries building and linking shared libraries. Austins PR seems to attempt to get very accurate comparison results with the gradle publishing process, such as splitting out debug symbols. That implementation is still very linux focused, so this breaks out the majority of the important guts, which might unblock his unpublished maven work.
The symbol exports in DLL's are not perfect, but get pretty close without having to change bazels default compiler flags. The same was true of linux .so's. The windows implementation of `cc_shared_library` does not seem to handle transitive deps on purpose, so that results in more explicit `dynamic_deps` call outs.

[bazel] Simple shared library implementation

---

wpimath/generate_nanopb.py
wpimath/generate_quickbuf.py

The generator was calling a binary of the wrong architecture and failing internally, but passing the build (incorrectly).  Explode right away.

Check results of subprocess.run in wpimath/generate_quickbuf.py

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/simulation/DCMotorSim.java

We took away the units as part of the function name but didn't comment them back

[wpilib] Add unit docs for return type of DCMotorSim getters

---

BUILD.bazel
WORKSPACE

Improves toolchain support for windows arm, and should make it easier to enable transitions for the artifact publishing.

[bazel] Update bazel toolchain, libssh, opencv

---

wpiutil/src/main/native/include/wpi/priority_mutex.h

Everything is part of glibc, so no special toolchain or patches needed. 
`priority_mutex_test` passes on my laptop after setting `WPI_HAVE_PRIORITY_MUTEX` and enabling the priority inversion tests.

Update and enable priority_mutex for systemcore

---

.github/workflows/bazel.yml

[This](https://github.com/wpilibsuite/allwpilib/pull/8006) PR removed the `setup-bazelisk` step for all of the actions. This works for the native builds because bazel(isk) has been added to the default runners. However, in the 2027 branch we build linux on the `wpilib/ubuntu-base:24.04` so that we can get the gui related sytem libraries (xwindows, etc) by default. The image does not have bazelisk, so it must be done with an explicit step. We can update the image as well, but this fixes (minus the cache issue) the build now.

[bazel] Install bazel on docker image builds

---

wpimath/src/main/java/edu/wpi/first/math/estimator/MerweScaledSigmaPoints.java
wpimath/src/main/java/edu/wpi/first/math/estimator/MerweUKF.java
wpimath/src/main/java/edu/wpi/first/math/estimator/S3SigmaPoints.java
wpimath/src/main/java/edu/wpi/first/math/estimator/S3UKF.java
wpimath/src/main/java/edu/wpi/first/math/estimator/SigmaPoints.java
wpimath/src/main/java/edu/wpi/first/math/estimator/UnscentedKalmanFilter.java
wpimath/src/main/native/cpp/estimator/MerweUKF.cpp
wpimath/src/main/native/cpp/estimator/S3UKF.cpp
wpimath/src/main/native/include/frc/estimator/MerweScaledSigmaPoints.h
wpimath/src/main/native/include/frc/estimator/MerweUKF.h
wpimath/src/main/native/include/frc/estimator/S3SigmaPoints.h
wpimath/src/main/native/include/frc/estimator/S3UKF.h
wpimath/src/main/native/include/frc/estimator/SigmaPoints.h
wpimath/src/main/native/include/frc/estimator/UnscentedKalmanFilter.h
wpimath/src/main/native/include/frc/estimator/UnscentedTransform.h
wpimath/src/test/java/edu/wpi/first/math/estimator/ExtendedKalmanFilterTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/MerweUKFTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/S3SigmaPointsTest.java
wpimath/src/test/java/edu/wpi/first/math/estimator/S3UKFTest.java
wpimath/src/test/native/cpp/estimator/MerweUKFTest.cpp
wpimath/src/test/native/cpp/estimator/S3SigmaPointsTest.cpp
wpimath/src/test/native/cpp/estimator/S3UKFTest.cpp

Adds `S3SigmaPoints` based on `MerweScaledSigmaPoints`. In addition, restructures `UnscentedKalmanFilter` to support different sigma point generators and provides `MerweUKF` and `S3UKF` for convenience when working with either kind of filter.
`S3UKFTest` is copied from `MerweUKFTest` (which is a rename of `UnscentedKalmanFilterTest`). Curiously, however, in Java the original tolerance used in `MerweUKFTest.testDriveConvergence()` for the final rotation was too low for `S3UKFTest`, so the tolerance is increased from 0.000005 (5e-6) radians to 0.00015 (1.5e-4) radians. However, the C++ version still uses the original tolerance. (This difference is probably because Java uses a final rotation of 5.846 *degrees* while C++ uses a final rotation of 5.846 *radians*)
Closes #8072.
Breaking …

[wpimath] Implement Scaled Spherical Simplex Filter (S3F)

---

hal/build.gradle
ntcore/build.gradle
shared/javacpp/publish.gradle
wpilibc/publish.gradle
wpimath/build.gradle
wpinet/build.gradle
wpiutil/build.gradle

Gradle publishing does not capture all of the source files that are used during a build. This should get most of them, and get it equivalent to what bazel pushes out.

Add missing sources to published zip files

---

wpinet/src/test/native/cpp/uv/UvGetAddrInfoTest.cpp

See https://github.com/wpilibsuite/allwpilib/discussions/8104. This test consistently fails when ISPs 'helpfully' resolve an invalid name.
Before this change we see 196 active tests when running `./gradlew wpinet:runWpinetTestOsxuniversalDebugGoogleTestExe `: 
```
[==========] 196 tests from 23 test suites ran. (2427 ms total)
[  PASSED  ] 196 tests.
```
With this change applied we now see 195 active tests with 1 disabled:
```
[==========] 195 tests from 23 test suites ran. (2421 ms total)
[  PASSED  ] 195 tests.
YOU HAVE 1 DISABLED TEST
```

[wpinet] Disable Uv FailedLookup test

---

wpilibNewCommands/WPILibNewCommands.json

Doing this on main so we can have a single vendor dep. It doesn't hurt anything.

Add systemcore to command vendor dep

---

simulation/halsim_gui/src/main/native/cpp/main.cpp
simulation/halsim_gui/src/main/native/include/HALSimGuiExt.h
wpigui/src/main/native/cpp/wpigui.cpp
wpigui/src/main/native/include/wpigui.h

This enables GUI libraries to be linked statically with shared context.

[simgui] Add GUI context getter hooks

---

shared/bazel/compiler_flags/windows_flags.rc

This needs to be short enough to fit in the windows path restriction. The full name was too long for some targets.

[bazel] Shorten the platform suffix for windows arm

---

wpimath/src/main/java/edu/wpi/first/math/geometry/Translation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation3d.java
wpimath/src/main/native/include/frc/geometry/Translation2d.h
wpimath/src/main/native/include/frc/geometry/Translation3d.h
wpimath/src/test/java/edu/wpi/first/math/geometry/Translation2dTest.java
wpimath/src/test/java/edu/wpi/first/math/geometry/Translation3dTest.java
wpimath/src/test/native/cpp/geometry/Translation2dTest.cpp
wpimath/src/test/native/cpp/geometry/Translation3dTest.cpp

Adds methods to compute the dot and cross products between `Translation2d`s and `Translation3d`s, as well as methods to compute the square of `Distance` and `Norm`, which allows avoiding some calls to `sqrt` in many cases. I'm not sure what the cross product of `Translation3d`s should return, since returning another `Translation3d` is not dimensionally correct (the returned vector should have components of `square_meter_t`, but `Translation3d` has `meter_t` components).

[wpimath] Add vector product and squared length operations to Translation2d/3d

---

cscore/BUILD.bazel

Statically link opencv, and make it work on all the architectures.

[bazel] Link cscorestatic correctly

---

.bazelrc
.github/workflows/bazel.yml

Windows is proving to be a *lot* slower than everything else.  I supect this is because we are building both arm64 and x86 every time, which ends up being twice the work.  Leave those builds in place, but skip doing them in CI.  This should be a 2x speedup when building Windows code.

[bazel] Reduce number of windows builds in CI

---

.github/workflows/upstream-utils.yml

Now it links to the README in upstream_utils.

[ci] Make upstream_utils check error with a more clear message

---

datalog/src/main/native/include/wpi/datalog/DataLogReaderThread.h

It is useful when programmatically interacting with DataLogs to be able to retrieve an record's associated metadata (entry name, type, and metadata string), but the only reference to an entry that a record contains is the id. `DataLogReaderThread` already builds a map of id->`DataLogReaderEntry`, but it was unexposed until now.
Fixes #8126

[datalog] Overload DataLogReaderThread::GetEntry to accept an entry id

---

shared/examplecheck.gradle

```
> Task :wpilibcExamples:checkCommands
Script '/home/tav/frc/wpilib/allwpilib/shared/examplecheck.gradle': line 135
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 10.0. This API is incompatible with the configuration cache, which will become the only mode supported by Gradle in a future release. Consult the upgrading guide for further information: https://docs.gradle.org/8.14.3/userguide/upgrading_version_7.html#task_project
at examplecheck_4wsg1s37eigy9vs5arzst20ga$_run_closure5$_closure16$_closure17.doCall$original(/home/tav/frc/wpilib/allwpilib/shared/examplecheck.gradle:135)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
```
Moving the project access outside the doLast block makes it occur …

Fix Gradle Task.project deprecation warning

---

shared/config.gradle
upstream_utils/protobuf_patches/0001-Fix-sign-compare-warnings.patch
upstream_utils/protobuf_patches/0002-Remove-redundant-move.patch
upstream_utils/protobuf_patches/0003-Fix-maybe-uninitialized-warnings.patch
upstream_utils/protobuf_patches/0004-Fix-coded_stream-WriteRaw.patch
upstream_utils/protobuf_patches/0005-Suppress-enum-enum-conversion-warning.patch
upstream_utils/protobuf_patches/0006-Fix-noreturn-function-returning.patch
upstream_utils/protobuf_patches/0007-Work-around-GCC-12-restrict-warning-compiler-bug.patch
upstream_utils/protobuf_patches/0008-Disable-MSVC-switch-warning.patch
upstream_utils/protobuf_patches/0010-Disable-pedantic-warning.patch
upstream_utils/protobuf_patches/0011-Avoid-use-of-sprintf.patch
upstream_utils/protobuf_patches/0012-Suppress-stringop-overflow-warning-false-positives.patch
upstream_utils/protobuf_patches/0013-Switch-descriptor-to-not-use-globals-from-header-inl.patch
upstream_utils/protobuf_patches/0014-Remove-deprecated-ATOMIC_VAR_INIT.patch
upstream_utils/protobuf_patches/0015-Ignore-GCC-15-warning.patch
upstream_utils/protobuf_patches/0015-ignore-a-warning-that-GCC15-introduced.patch
wpiutil/src/main/native/thirdparty/protobuf/src/generated_message_tctable_lite.cpp

On Arch Linux, the GCC package is GCC 15.1.1, which introduced some new warnings. Small changes were made here to build on 15.1.1.

Small fixes to build on GCC 15

---

docs/build.gradle

In the recent gradle or gradle dependencies update, the documentation zips were being published as documentation-version-unspecified, where the unspecified was coming from archiveVersion. It looks like we use a different method of setting the version, so make sure that archiveVersion is empty

Explicitly set Documentation archiveVersion

---

epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/ClassSpecificLogger.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/FileBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/LazyBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/MultiBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/NTEpilogueBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/NestedBackend.java
epilogue-runtime/src/test/java/edu/wpi/first/epilogue/logging/NestedBackendTest.java

Closes #8189
Data was collected with JFR and AdvantageScope using a real (and fairly small) robot program running in simulation. The program was running at a 200Hz loop rate on Java 21 with ZGC and a 512MB max heap size. Larger programs with more logged fields will see better performance improvements
Key changes:
- Caching path concatenations in `NestedBackend` avoids huge numbers of memory allocations stemming from byte array and string object instantiations.
- Replacing lambdas with imperative equivalents (for lambdas with local captures) or caching in class members (for lambdas without local captures) slightly improves runtime performance and also saves several megabytes of object allocations, helping with GC pressure.
Results:
- Saved 2.73GiB of memory allocations per minute on byte …

[epilogue] Optimize time and memory usage of epilogue backends

---

epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/ClassSpecificLogger.java
styleguide/pmd-ruleset.xml
wpilibj/src/main/java/edu/wpi/first/wpilibj/smartdashboard/SmartDashboard.java
wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/elevatorprofiledpid/Robot.java
wpiunits/src/main/java/edu/wpi/first/units/collections/ReadOnlyPrimitiveLongSet.java

Code readability is much more important than saving three bytes per redundantly-initialized field

Remove PMD.RedundantFieldInitializer rule

---

glass/src/libnt/native/cpp/NetworkTables.cpp

The union that upb returns will contain a value of NULL if an array is empty or a submessage doesn't exist (submessages are always optional). Fix libglass so it doesn't crash if it encounters an empty array or empty submessage, and display a blank space instead. Also make it display a blank space for any optional fields that weren't explicitly set.
Comparision between 2025 Glass (left) and modified Sim GUI (using #6518 as a base to provide empty arrays and empty optional fields).

[glass] Fix handling for optionals and empty arrays

---

wpilibj/src/main/java/edu/wpi/first/wpilibj/util/Color.java
wpimath/src/main/java/edu/wpi/first/math/MathUtil.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation2d.java
wpimath/src/main/java/edu/wpi/first/math/geometry/Translation3d.java
wpimath/src/main/java/edu/wpi/first/math/interpolation/Interpolator.java
wpimath/src/main/java/edu/wpi/first/math/interpolation/InverseInterpolator.java
wpimath/src/main/java/edu/wpi/first/math/interpolation/TimeInterpolatableBuffer.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/DifferentialDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/MecanumDriveWheelPositions.java
wpimath/src/main/java/edu/wpi/first/math/kinematics/SwerveModulePosition.java
wpimath/src/main/java/edu/wpi/first/math/trajectory/Trajectory.java
wpimath/src/test/java/edu/wpi/first/math/MathUtilTest.java

C++ already has this in its standard library, so I'm surprised Java doesn't.

[wpimath] Refactor MathUtil.interpolate() and MathUtil.inverseInterpolate() to handle extrapolation

---

epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/AnnotationProcessor.java
epilogue-processor/src/main/java/edu/wpi/first/epilogue/processor/ProtobufHandler.java
epilogue-processor/src/test/java/edu/wpi/first/epilogue/processor/AnnotationProcessorTest.java
epilogue-runtime/BUILD.bazel
epilogue-runtime/build.gradle
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/EpilogueBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/FileBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/LazyBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/MultiBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/NTEpilogueBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/NestedBackend.java
epilogue-runtime/src/main/java/edu/wpi/first/epilogue/logging/NullBackend.java
epilogue-runtime/src/test/java/edu/wpi/first/epilogue/logging/LazyBackendTest.java
epilogue-runtime/src/test/java/edu/wpi/first/epilogue/logging/TestBackend.java

For parity with struct-serializable types
Change struct serialization to only apply to types with a `public static final <type> struct` field, instead of relying only on the marker interface (which is not always followed). Doing this allows fallthrough to the protobuf handler for types with dynamic structs but static protobuf serializers

[epilogue] Support logging of protobuf-serializable types

---

glass/src/lib/native/include/glass/hardware/LEDDisplay.h

The color order of the internal AddressableLED buffer changed from BGR to RGB on the 2027 branch, but the sim GUI was never updated to reflect this change. This causes red and blue to be swapped when visualizing LEDs in sim.

[glass] Fix color order for sim GUI LEDs

---

WORKSPACE
shared/bazel/rules/packaging.bzl
upstream_utils/eigen.py
upstream_utils/eigen_patches/0001-Disable-warnings.patch
upstream_utils/eigen_patches/0002-Intellisense-fix.patch
upstream_utils/eigen_patches/0003-Add-build-files-from-bzlmod-for-eigen.patch
upstream_utils/eigen_patches/0003-bazel-build-files.patch
wpimath/BUILD.bazel
wpimath/src/main/native/thirdparty/eigen/include/BUILD.bazel
wpimath/src/main/native/thirdparty/eigen/include/COPYING.APACHE
wpimath/src/main/native/thirdparty/eigen/include/COPYING.BSD
wpimath/src/main/native/thirdparty/eigen/include/COPYING.MINPACK
wpimath/src/main/native/thirdparty/eigen/include/COPYING.MPL2
wpimath/src/main/native/thirdparty/eigen/include/COPYING.README

This sets us up to use AOS, which wants `@eigen` to resolve, without introducing a second version or copy of eigen.

[bazel] Put eigen in an external repo like bzlmod

---

wpiutil/src/main/native/include/wpi/circular_buffer.h
wpiutil/src/main/native/include/wpi/static_circular_buffer.h
wpiutil/src/test/native/cpp/CircularBufferTest.cpp
wpiutil/src/test/native/cpp/StaticCircularBufferTest.cpp

Changes to circular_buffer and static_circular_buffer:
- Made iterator and const_iterator bidirectional
- Added reverse_iterator and const_reverse_iterator using std::reverse_iterator<>
- Added relevant rbegin(), rend(), crbegin(), crend() functions
- Added unit tests for both iterators
I also added comments to circular_buffer to match the ones in static_circular_buffer

[wpiutil] Add reverse iterators to wpi::circular_buffer and wpi::static_circular_buffer, make other iterators bidirectional
